### ISSUE TITLE
Add Firefox Reality to "Productivity" category on Oculus Store

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1000]
## Hardware
Oculus Go

## Steps to Reproduce
1. Load [Samsung Internet's app-detail page on the Oculus store](https://www.oculus.com/experiences/go/849609821813454/), and notice the _Categories_ list: **Productivity**, **Utility**:
    
    ![image](https://user-images.githubusercontent.com/203725/54189364-e32d5100-446e-11e9-97e6-fda46df0dcf5.png)
    
3. Load [Oculus Browser's app-detail page on the Oculus store](https://www.oculus.com/experiences/go/1257988667656584/), and notice the _Categories_ list: **Movie**, **Productivity**, **Utility**:
    
    ![image](https://user-images.githubusercontent.com/203725/54189492-28ea1980-446f-11e9-8c7f-5e53e4edaf49.png)
    
5. Load [Firefox Reality's app-detail page on the Oculus Store](https://www.oculus.com/experiences/go/2208418715853974), and notice the _Categories_ list: **360 Experience (non-game)**, **News & Information**, **Utility**:
    
    ![image](https://user-images.githubusercontent.com/203725/54189425-fe985c00-446e-11e9-9f21-c82bec814209.png)
    
7. I'd expect [Firefox Reality](https://www.oculus.com/experiences/go/2208418715853974/) to also list **Productivity** and **Movie** in the _Categories_ list.

## Current Behavior
On the [Firefox Reality's app-detail page on the Oculus Store](https://www.oculus.com/experiences/go/2208418715853974/), **Productivity** and **Movie** are missing from the _Categories_ list: **360 Experience (non-game)**, **News & Information**, **Utility**:
    
![image](https://user-images.githubusercontent.com/203725/54189425-fe985c00-446e-11e9-9f21-c82bec814209.png)

## Expected Behavior
On the [Firefox Reality's app-detail page on the Oculus Store](https://www.oculus.com/experiences/go/2208418715853974/), **Productivity** and **Movie** should be included in the _Categories_ list.

## Possible Solution
In the Oculus Store, update the _Categories_ list for [Firefox Reality](https://www.oculus.com/experiences/go/2208418715853974/) to contain **Productivity** and **Movie**.

## Context
Discovered this when recently searching for and reinstalling [Samsung Internet](https://www.oculus.com/experiences/go/849609821813454/) on my Oculus Go.

**Comment by cvan** [comment]
@larsbergstrom: can you take a look here, and, if you agree, can you update the _Categories_ listed? if these categories were explicitly chosen, and there's not a limit, we can close this issue. otherwise, it would be nice to add **Productivity** and **Movie**. thank you in advance for your help. :+1:

**Comment by larsbergstrom** [comment]
@cvan They were picked somewhat randomly (and long before we knew what users would use the browser for!), and we have a limit of 3. I've submitted a request to change them to the same as the Oculus Browser ones. Typically changes to store art/text/etc. take from 2 days to a week to update. Thanks for looking into this!

**Comment by jvonitter** [comment]
just need to check that this happened and then we can close

**Comment by jvonitter** [comment]
We are labeled "productivity" in the app store
![Screenshot_20190603-112917](https://user-images.githubusercontent.com/48839872/58825336-1bb67400-85f3-11e9-96e0-e0d04caacda7.png)
!
