### ISSUE TITLE
Support `<datalist>` HTML element correctly with an autocompletion drop-down UI

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1006]
## Hardware
- Oculus Go
- Pico G2 (WaveVR)

## Steps to Reproduce
1. Navigate to https://webxr.sh/dropdowns#datalist.
2. Press the `<datalist>` element (it looks like a default text field).
3. When the keyboard appears, type the letters `pe`.
4. Notice no UI appears to show the children of the `<datalist>` element.

## Current Behavior
A drop-down UI for the `<datalist>` element does not appear.

![image](https://user-images.githubusercontent.com/203725/54269989-a5e2c500-453b-11e9-95fa-f99cc55290cf.png)

![image](https://user-images.githubusercontent.com/203725/54269994-a8451f00-453b-11e9-8b6d-bed78625c096.png)

## Expected Behavior
A drop-down UI for the `<datalist>` element appears.

## Context
_Note:_ I haven not tested GeckoView / Fennec directly. I don't know the implementation details, but it may be possible that the `<datalist>` DOM element is properly implemented in GeckoView and the events are properly fired, but that there are simply missing hooks and UI in FxR's implementation. I'll leave it up to @MozillaReality/fxr-eng to determine that.

**Comment by philip-lamb** [comment]
Appears to lack support in Geckoview; I tested on Focus on Android (Gecko 64) and no dropdown is offered.
