### ISSUE TITLE
`<option disabled>` appears invisible (white text on a white background)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1007]
## Hardware
Oculus Go

## Steps to Reproduce
1. Load https://webxr.sh/dropdowns#multiple-optgroup.
2. Press the `<optgroup>` field, and scroll down.
3. Notice there is a white gap, a seemingly empty row, where the text `Hamster` should go.

## Current Behavior

In FxR, the text of `<option disabled>` in an `<optgroup>` (or `<select>`) element appears invisible (as white text on a white background).

This is the accompanying [HTML](https://webxr.sh/dropdowns#multiple-optgroup):

```html
<optgroup>
  <option value="hamster" disabled>Hamster</option>
</optgroup>
```

### Firefox Reality

![screenshot of invisible text in `<option disabled>`](https://user-images.githubusercontent.com/203725/54270013-b2ffb400-453b-11e9-803d-b447acf9325b.png "screenshot of invisible text in `<option disabled>`")

### Oculus Browser

![screenshot](https://user-images.githubusercontent.com/203725/54270123-e6dad980-453b-11e9-99f8-26f20835803b.png)

### Firefox for desktop (macOS)

![screenshot](https://user-images.githubusercontent.com/203725/54270162-fc500380-453b-11e9-9e5e-30b795d8f526.png)

**Comment by MortimerGoro** [comment]
This looks like a GeckoView issue. The disabled option is correctly displayed in the Prompt Dialog.

**Comment by MortimerGoro** [comment]
I filed this GeckoView issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1535275

**Comment by bluemarvin** [comment]
This might be an oculus platform bug? As this works in NoAPI
![Screenshot_20190314-094139](https://user-images.githubusercontent.com/3066/54375008-76b47c80-463d-11e9-8563-a399cfa154aa.png)

**Comment by MortimerGoro** [comment]
@bluemarvin I think it's a random issue. I was able to reproduce it two times, but it was ok on other tries

**Comment by bluemarvin** [comment]
No one was able to reproduce it today in GV triage.

**Comment by cvan** [comment]
I can consistently reproduce on Pico G2 (WaveVR) and Oculus Go this highlight issue with `<option selected>` in `<select multiple>` and `<option disabled>` being hidden.

On Pico G2:

![image](https://user-images.githubusercontent.com/203725/54394674-d1b09880-466a-11e9-9d7e-844b51afa4c2.png)

**Comment by bluemarvin** [comment]
I think this might be a Gecko platform bug. I'll see if I can reproduce it in GVE app.

**Comment by cvan** [comment]
Dan Holbert and I tested this in MV and were unable to reproduce on the Go with the same test case. Probably a graphics bug fixed in a Gecko upgrade since this was reported. [Bug resolved as WORKSFORME](https://bugzilla.mozilla.org/show_bug.cgi?id=1535275#c15).
