### ISSUE TITLE
Extend `<Button>` for DRY modal buttons (positive, negative, and neutral)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1009]
## Hardware
Any

## Steps to Reproduce
1. Load https://webxr.sh/dialogues, https://webxr.sh/basic-auth, or https://webxr.sh/dropdowns.
2. Notice the buttons in the modals.
3. Notice there is a lot of shared code in the corresponding XML layout files for the various types of similarly repeated buttons: `@+id/positiveButton`, `@+id/negativeButton`, and `@+id/neutralButton`.

### positive buttons
- [`prompt_alert.xml`](https://github.com/MozillaReality/FirefoxReality/blob/f666370/app/src/main/res/layout/prompt_alert.xml#L48-L64)
- [`prompt_auth.xml`](https://github.com/MozillaReality/FirefoxReality/blob/92d3b45/app/src/main/res/layout/prompt_auth.xml#L166-L179)
- [`prompt_choice.xml`](https://github.com/MozillaReality/FirefoxReality/blob/f666370/app/src/main/res/layout/prompt_choice.xml#L94-L106)
- [`prompt_confirm.xml`](https://github.com/MozillaReality/FirefoxReality/blob/f666370/app/src/main/res/layout/prompt_confirm.xml#L87-L99)
- [`prompt_text.xml`](https://github.com/MozillaReality/FirefoxReality/blob/f666370/app/src/main/res/layout/prompt_text.xml#L88-L100)

### negative buttons
- [`prompt_auth.xml`](https://github.com/MozillaReality/FirefoxReality/blob/92d3b45/app/src/main/res/layout/prompt_auth.xml#L151-L164)
- [`prompt_auth.xml`](https://github.com/MozillaReality/FirefoxReality/blob/92d3b45/app/src/main/res/layout/prompt_auth.xml#L151-L164)
- [`prompt_choice.xml`](https://github.com/MozillaReality/FirefoxReality/blob/f666370/app/src/main/res/layout/prompt_choice.xml#L80-L92)
- [`prompt_confirm.xml`](https://github.com/MozillaReality/FirefoxReality/blob/f666370/app/src/main/res/layout/prompt_confirm.xml#L59-L71)
- [`prompt_text.xml`](https://github.com/MozillaReality/FirefoxReality/blob/f666370/app/src/main/res/layout/prompt_text.xml#L74-L86)

### neutral buttons
- [`prompt_confirm.xml`](https://github.com/MozillaReality/FirefoxReality/blob/f666370/app/src/main/res/layout/prompt_confirm.xml#L73-L85)

## Expected Behavior
The `<Button android:id="@+id/positiveButton"/>`, `<Button android:id="@+id/negativeButton"/>`, and `<Button android:id="@+id/neutralButton"/>` inherit styles from a commonly defined layout element.

## Context
Originally reported here in PR #985: https://github.com/MozillaReality/FirefoxReality/pull/985/files#r264567458

**Comment by philip-lamb** [comment]
_DRY acronym: https://changeorder.typepad.com/weblog/2014/09/three-engineering-acronyms-every-ux-designer-should-know.html_
