### ISSUE TITLE
[e10s] Crash upon attempting to exit WebVR and frame stuck in LÖVR examples

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1017]
## Hardware
- Oculus Go: [1.1.3a](https://github.com/MozillaReality/FirefoxReality/releases/tag/1.1.3a) (ab033b4)

## Steps to Reproduce
1. Turn on `Enable Multiprocessing` in **Settings > Developer Options**
2. Load https://lovr.org/docs/360_Photo
3. Press the **Enter VR** button
4. Look around
5. Notice the frame is frozen
6. Try to press the Back button to exit VR

## Current Behavior
VR presentation fails on head tracking. Here's a stuck frame:

![image](https://user-images.githubusercontent.com/203725/54420637-c63f8a80-46c7-11e9-924a-bd835cabc2e9.png)

The user cannot exit VR mode. And, the loading throbber slows to a halt:

![image](https://user-images.githubusercontent.com/203725/54420676-e2432c00-46c7-11e9-9442-3d7aa64f3971.png)

FxR eventually becomes completely unresponsive and eventually crashes. Here's my crash report: https://crash-stats.mozilla.com/report/index/13817285-20cd-4207-b8b7-9d0760190315

## Expected Behavior
WebVR presentation works and, if performance degrades to a halt, the user can still exit VR mode.

## Crash Report
https://crash-stats.mozilla.com/report/index/13817285-20cd-4207-b8b7-9d0760190315

**Comment by philip-lamb** [comment]
Could not reproduce on Vive Focus.

**Comment by cvan** [comment]
> Could not reproduce on Vive Focus.

With Multiprocessing (e10s) enabled in Settings > Developer Options?

**Comment by philip-lamb** [comment]
> > Could not reproduce on Vive Focus.
> 
> With Multiprocessing (e10s) enabled in Settings > Developer Options?

Yes.

**Comment by cvan** [comment]
Interesting. Good to know, thanks. I will test with my Focus this week, do some profiling in both the Pico G2 and Focus and report back here.

**Comment by bluemarvin** [comment]
I am unable to reproduce on Pico G2 with [master](https://github.com/MozillaReality/FirefoxReality/commit/e475629fc9b51a1c0e95a6cbd57d412d7610261d)

**Comment by cvan** [comment]
thanks!
