### ISSUE TITLE
PanoMoments in WebVR do not play on WaveVR

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1018]
## Hardware
- Pico G2: [1.1.3a](https://github.com/MozillaReality/FirefoxReality/releases/tag/1.1.3a) (ab033b4)
- Oculus Go: [1.1.3a](https://github.com/MozillaReality/FirefoxReality/releases/tag/1.1.3a) (ab033b4)

## Steps to Reproduce
1. Load https://my.panomoments.com/u/MomentCaptureStudio/m/sutro-baths?hideInfo=1
2. Press the VR button
3. Once in VR mode, move your head around
4. Notice the scene is frozen and doesn't move, as if the underlying video cannot be played

## Current Behavior
PanoMoments does not play as expected. Works fine on the Oculus Go.

## Expected Behavior
PanoMoments play as expected as on the Oculus Go.

## Context
See these related platform bugs:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1529812#c28
- https://bugzilla.mozilla.org/show_bug.cgi?id=1531373#c14

Could be related. Need to do some further digging.

**Comment by cvan** [comment]
Will investigate further and post here and in the Bugzilla bugs.

**Comment by philip-lamb** [comment]
I can no longer reproduce with 1.1.3e on Vive Focus. @cvan please repro on Pico and close if fixed.

**Comment by bluemarvin** [comment]
I am unable to reproduce on Pico G2 with build from [master.](https://github.com/MozillaReality/FirefoxReality/commit/e475629fc9b51a1c0e95a6cbd57d412d7610261d)

**Comment by cvan** [comment]
thanks!

**Comment by philip-lamb** [comment]
Reopening this to track landing of fix in https://bugzilla.mozilla.org/show_bug.cgi?id=1540573 in our ingested Geckoview.

**Comment by philip-lamb** [comment]
Fix in https://bugzilla.mozilla.org/show_bug.cgi?id=1540573 is in GV and FxR v1.2.
