### ISSUE TITLE
In 360 Video playback, controller models always (YouTube, Vimeo, direct MP4 video)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1022]
_(**Disclaimer:** I've filed this as a P0 bug. If the behaviour I've reported was changed intentionally – or if the agreed-upon impact is low, please feel free to adjust the labels. I wanted to make sure this issue gets properly looked at before the this release is pushed.)_

<hr>

## Hardware
- Oculus Go:
    - [1.1.3a](https://github.com/MozillaReality/FirefoxReality/releases/tag/1.1.3a) (ab033b4)
    - [1.1.2](https://github.com/MozillaReality/FirefoxReality/releases/tag/1.1.2) (4049807)
- Pico G2:
    - [1.1.3a](https://github.com/MozillaReality/FirefoxReality/releases/tag/1.1.3a) (ab033b4)
    - [1.1.2](https://github.com/MozillaReality/FirefoxReality/releases/tag/1.1.2) (4049807)

## Steps to Reproduce
1. Launch the FxR Feed
2. Click on a **[YouTube 360 video](https://www.youtube.com/watch?v=JL6NAIVpl54&mozVideoProjection=360_auto)**, or load a **[direct video file](https://ia600603.us.archive.org/5/items/youtube-lHxVj94RPDU/BLUE_LAGOON_Iceland_360_Virtual_Tour_Video-lHxVj94RPDU.mp4&mozVideoProjection=360_auto)** (linked from https://webxr.sh/?#360-raw)
3. Notice the controller model now persisents appears in the UI, even after clicking on the video
4. Try click outside of the media transport controls
5. Notice the controller still appears and doesn't go away as the video is playing

## Current Behavior
Controller model shows disappears when a projected 360 video is playing, which the controller is useful for interacting with the transport Media Controls.

#### [1.1.3a](https://github.com/MozillaReality/FirefoxReality/releases/tag/1.1.3a) (ab033b4)
![image](https://user-images.githubusercontent.com/203725/54425439-95188780-46d2-11e9-9a26-ca38be05a52c.png)
![image](https://user-images.githubusercontent.com/203725/54425432-91850080-46d2-11e9-9f7e-67984ef0b744.png)
![image](https://user-images.githubusercontent.com/203725/54425436-934ec400-46d2-11e9-8fe0-eace0ff29bf1.png)

#### [1.1.2](https://github.com/MozillaReality/FirefoxReality/releases/tag/1.1.2) (4049807)
![image](https://user-images.githubusercontent.com/203725/54425799-7070df80-46d3-11e9-825f-d4d25c4a7a07.png)
![image](https://user-images.githubusercontent.com/203725/54425806-736bd000-46d3-11e9-8055-9e8429cf9055.png)

### Pico G2 (WaveVR)
I wasn't able to [capture the screenshots at this time](https://github.com/MozillaReality/FirefoxReality/issues/1019), but this happens in playback of Vimeo videos, a **[direct video file](https://ia600603.us.archive.org/5/items/youtube-lHxVj94RPDU/BLUE_LAGOON_Iceland_360_Virtual_Tour_Video-lHxVj94RPDU.mp4&mozVideoProjection=360_auto)** (linked from https://webxr.sh/?#360-raw), and likely YouTube 360 videos (but that's blocked on an unrelated (but-new-to-me) issue: #1019).

## Expected Behavior
Controller model is not visible when a projected 360 video is first played, but upon pressing the primary button on the scene, the controller model reappears (which is useful for interacting with the transport Media Controls). Click again outside the transport Media Controls. And **the controller model disappears**, as expected.

Something in the [**commits landed since**](https://github.com/MozillaReality/FirefoxReality/compare/1.1.2..1.1.3) from [1.1.2](https://github.com/MozillaReality/FirefoxReality/releases/tag/1.1.2) (4049807) appears to be the culprit of this **regression** (unless this is is the unexpected behaviour made by a new intentional change).

**Comment by MortimerGoro** [comment]
Fixed iin https://github.com/MozillaReality/FirefoxReality/pull/1023. Please reopen it if you find any issues
