### ISSUE TITLE
The feed page can't scroll after pushing the back button

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#1025]
## Hardware

Oculus 6DOF device

## Steps to Reproduce

1. Go down to the lowest column in the feed and click one item. 
2. Go to the page from the item.
3. After finishing the page loading, push the `back` btn or `menu` btn until be back to the homepage.

## Current Behavior

 Try to push the joystick and we can't move, the homepage seems to stop scrolling.

## Expected Behavior

The scroll works properly.

## Context

It probably is because we have two controllers, it causes confusion in the touch emulator of Gecko.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by daoshengmu** [comment]
I notice pressing `Refresh` icon, it still gets stuck. But pressing `Home` icon can help us go back to the proper mode.

**Comment by cvan** [comment]
I think this is related to https://github.com/MozillaReality/ContentFeed/issues/204. I will prioritise it for next week. Thanks for filing! :+1:

**Comment by daoshengmu** [comment]
It looks better in 1.1.3d. It only happens once during my whole morning.

**Comment by bluemarvin** [comment]
I think this is a content feed bug where if you open something on the bottom of the page then go back, the page is no longer able to scroll. Something (javavscript maybe?) seems to be keeping the page scrolled to the end.

**Comment by cvan** [comment]
Yep, will fix it.

**Comment by cvan** [comment]
Clearing the milestone because I can fix this at any time, not tied to an FxR binary release. Tracking here: MozillaReality/ContentFeed#204

**Comment by philip-lamb** [comment]
OK, given it's tracked elsewhere I'll close this.
