### ISSUE TITLE
Add a pref to enable developer options

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/FirefoxReality#1027]
The same way we can set a pref to enable `e10s` it could be great to have a preference to enable remote debugging and redirect logcat as everytime I run a test I restart the browser and these preferences get lost.

**Comment by cvan** [comment]
If adb props get persisted on headset reboot (forget, but I think they do not), can we support those too?

This would be a helpful addition. Thanks for filing.

**Comment by philip-lamb** [comment]
See also #874.
