### ISSUE TITLE
Add l10n toml

### ISSUE THREAD

**Issue by Delphine** [MozillaReality/FirefoxReality#1034]
This is only a configuration change, to be used by the upcoming l10n ecosystem. Thus not tests or changelogs or QA tags on this one.
CC @Pike

**Comment by Pike** [comment]
We have one, but I need to make a slight twist to it.

**Comment by philip-lamb** [comment]
@Pike Is there anything I can do to move this along? We have a l10n.toml, but does this issue relate to us getting an entry into https://github.com/mozilla-l10n/android-l10n/blob/master/config.toml ?

**Comment by philip-lamb** [comment]
Fixed by #1086
