### ISSUE TITLE
Add Winter and Underwater environments and update Meadow

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1037]
- Add the _Winter_ environment
- Add the _Underwater_ environment
- Replace _Meadow_ with revised version
- Rename _Island_ to _Offworld_

**Comment by cvan** [comment]
@philip-lamb: could you help me obtain the Blender sources for Winter, Underwater, and Meadow? or at the very least, have the cubemaps rendered at 1024×1024 (those three by Podipo are 1000×1000, and I couldn't find the sources). thanks!

opened PR #1038. the new + updated environments load, but you can see there are visual gaps in the cubemapping.

thanks!

**Comment by MortimerGoro** [comment]
Fixed via https://github.com/MozillaReality/FirefoxReality/pull/1038

**Comment by cvan** [comment]
thanks for the assist, @MortimerGoro - much appreciated :+1:
