### ISSUE TITLE
Scrollbars too close in Environments list (Settings)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1040]
## Steps to Reproduce

1. Load **Settings > Environments**.
2. Notice the vertical scrollbars are too close, and they touch the other elements.

![2019-03-22_16:36:02](https://user-images.githubusercontent.com/203725/54858251-ee7b4a80-4cc0-11e9-89ce-a74695c5e979.png)

The scrollbars look fine in **Settings > Languages**:

![2019-03-22_16:38:58](https://user-images.githubusercontent.com/203725/54858269-0bb01900-4cc1-11e9-8a5c-635845251ae5.png)

**Comment by MortimerGoro** [comment]
Fixed in #1067
