### ISSUE TITLE
Focus/Full screen should remember window size set by user

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#105]
STR:
1) Go into focus mode
2) Set window size to 3x
3) Leave exit focus mode
4) Go back into focus mode

Expected result: Screen should still be 3x
Actual result: screen is default size.

**Comment by keianhzo** [comment]
There is one case that i find unnatural for the user:

- Go into focus mode
- Set windows size to 0.5x
- Leave focus mode
- Go to another site and ie. open a video
- Make it full screen

Making a video full screen in that case will make it 0.5x which is not probably what the user expects when going full screen from inside a web site.

**Comment by MortimerGoro** [comment]
`There is one case that i find unnatural for the user:`
I Agree. Currently full screen always starts with 2x
