### ISSUE TITLE
Make it so Taskcluster also compiles with Servo enabled

### ISSUE THREAD

**Issue by paulrouget** [MozillaReality/FirefoxReality#1054]
It doesn't have to ship with Servo enabled, but we'd like to avoid regressions every time GeckoView gets updated.

To compile with Servo, add `enableServo=1` to `user.properties`.

**Comment by bluemarvin** [comment]
I would rather not block on something that does not ship. Also, just because it compiles, doesn’t mean it will run properly. Additionally, this would double our taskcluster build time which is already approaching four hours 😓

**Comment by philip-lamb** [comment]
We can consider adding this to our planned taskcluster tests, tracked in #1065
