### ISSUE TITLE
Hide YouTube's "Full screen is unavailable" disclaimer when Fullscreen 360 Media Controls opened

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1056]
## Hardware
All

## Steps to Reproduce
1. Load a YouTube video, such as https://www.youtube.com/watch?v=JL6NAIVpl54&mozVideoProjection=360
2. Notice this disclaimer in the bottom-right corner of the video: `Full screen is unavailable. Learn More`

![image](https://user-images.githubusercontent.com/203725/55434712-0e2a3280-554d-11e9-814f-3d10c0e3b127.png)

## Current Behavior
A disclaimer appears in the bottom-right corner of YouTube videos when fullscreened before entering a projection: `Full screen is unavailable. Learn More`

## Expected Behavior
As `Full screen is unavailable. Learn More` disclaimer is confusing and unnecessary, it should not appear in the bottom-right corner of YouTube videos when fullscreened before entering a projection.

## Possible Solution
We informed YouTube of this WebCompat issue a while back, but there's been no response. In the meantime, FxR can hide this disclaimer with its YouTube Web Extension [content script](https://github.com/MozillaReality/FirefoxReality/tree/master/app/src/main/assets/web_extensions/youtube_webcompat), which was added in PR #1047 and improved upon in PR #1052.

**Comment by cvan** [comment]
I have fixed this locally and will make a PR shortly.

so, my bad: this was *supposed* to be fixed in PR #1052, but Firefox chokes on the syntax error in the style selector here https://github.com/MozillaReality/FirefoxReality/pull/1052/files#r283601515, which causes the `Full screen is unavailable` message to still be visible.

**Comment by philip-lamb** [comment]
Fixed in #1217.
