### ISSUE TITLE
Input broken in Youtube

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#1063]
![blur6](https://user-images.githubusercontent.com/1070794/55730623-e8070580-5a18-11e9-8ebf-38b3393e8ef4.png)

Youtube shows a new dialog about data protection laws. In order to read it I had to scroll a bit but after scrolling input does not work correctly. For example if I click the "next button" it performs a click in "points" word because of the wrong input offset.

I wonder if this is also the reason that sometimes Youtube UI is hard to click or unresponsive (e.g quality selector, fullscreen). 

cc @cvan @bluemarvin

**Comment by bluemarvin** [comment]
@MortimerGoro I don't see the pop-over. I can scroll the page and events seem to be in the correct location so I am not able to reproduce the issue. I was using [master](https://github.com/MozillaReality/FirefoxReality/commit/3e47cb1df7ea039a04fa9efe8f56852a9c627f48).

**Comment by philip-lamb** [comment]
@bluemarvin This is likely to be region-specific. GDPR rules apply to data retention in the EU.

**Comment by MortimerGoro** [comment]
I can't longer reproduce it because after acepting the dialog it doesn't appear again (even after clear install or different devices)

**Comment by cvan** [comment]
> I can't longer reproduce it because after acepting the dialog it doesn't appear again (even after clear install or different devices)

wonder if I should purchase a European VPN to test it. we could reach out to YT and look in support/user forums to see if anyone's experienced a similar issue.

the input `click` event seems scary and indicative of a larger issue possibly (or a YT bug).

**Comment by cvan** [comment]
old thread but seems related: https://www.reddit.com/r/techsupport/comments/489lq6/circumventing_youtubes_before_you_continue_dialog/

next time you see this, could you open up `about:debugging` in Firefox Desktop, open the Dev Tools > Inspector, and search for `before you continue` in the DOM?

and then

```
copy(document.documentElement.outerHTML);
```

and send over the contents so we can inspect it.

if we can find the selector (possibly `div.yt-dialog-content`, we could better reproduce a test case.

**Comment by philip-lamb** [comment]
Not scheduling for work until we can reliably reproduce.
