### ISSUE TITLE
Add basic automated functional tests with Taskcluster CI

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1065]
It would be nice to have some basic functional tests to catch regressions, especially during GeckoView version bumps. Ideally, we could use CI to run each a suite of tests on each PR.

@bluemarvin: Do you know how the GeckoView/Focus/Fennec teams do automated end-to-end testing? Also, do you know if Taskcluster supports Travis/Circle-like continuous integration?

**Comment by bluemarvin** [comment]
@cvan Tests can absolutely be run in taskcluster. They can be run along side any build and can be required to pass. Focus has test that run with each build. GeckoView also has test that run but obviously it isn't done through GitHub.

**Comment by cvan** [comment]
Awesome to hear!

Some links for folks:
- https://tools.taskcluster.net/
- https://docs.taskcluster.net/docs/manual
- https://docs.taskcluster.net/docs/tutorial
- https://docs.taskcluster.net/docs/reference
- https://docs.taskcluster.net/docs/resources

**Comment by keianhzo** [comment]
I've added support for instrumentation test and a few basic sample tests here: `v8/ui_tests`. We can probably start to define the test suite.

**Comment by keianhzo** [comment]
Related: https://github.com/MozillaReality/FirefoxReality/pull/2747
