### ISSUE TITLE
Rough scrolling in FxR

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#1066]
## Hardware

Oculus Go.
https://github.com/MozillaReality/FirefoxReality/commit/fdff5b97fe5be54696ef933f36a0163d018650ac

## Steps to Reproduce

1.
2.
3.

## Context
https://bugzilla.mozilla.org/show_bug.cgi?id=1542935

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by philip-lamb** [comment]
Not a blocker for 1.1.x.

**Comment by MortimerGoro** [comment]
This is already fixed

**Comment by philip-lamb** [comment]
Fixed in https://github.com/MozillaReality/FirefoxReality/commit/9399f888008254438566a0ff6edd8e72e5d188fc
