### ISSUE TITLE
[meta] Move from Geckoview nightly to beta

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#1068]
## Hardware
All

## Current Behavior
We currently build from Geckoview nightly.

## Expected Behavior
We should be building from Geckoview beta. Amongst other things, nightly has additional debug logging/tracing included.

## Possible Solution
Identify all Geckoview functionality that we depend on that is currently in nightly and when it will land in Geckoview beta.

## Context
Direct dependencies (add in the format shown)
* needs #967 

List of things fixed in GV that we must wait to transition to GV beta:
* #1049 & #1060

Other GV bugs tracked in Bugzilla:
Fixed in GV 68:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1528279

**Comment by bluemarvin** [comment]
I think we also need a good strategy for making it easy to test against nightly. Waiting for features to hit beta is too late to wait to find bugs.

**Comment by cvan** [comment]
WebCompat sites affected by e10s (to my knowledge):

- [https://chromatic.funktroniclabs.com/](https://github.com/MozillaReality/FirefoxReality/issues/1048)
- [https://lovr.org/docs/360_Photo](https://github.com/MozillaReality/FirefoxReality/issues/1017)
- [https://hubs.mozilla.com/](https://github.com/mozilla/hubs/issues/899#issuecomment-482025876) (broken w/ and w/o e10s)

**Comment by philip-lamb** [comment]
needs #1127

**Comment by cvan** [comment]
> needs #1127

done :+1:

**Comment by philip-lamb** [comment]
I'm going to close this as tackling the issue of using a stable geckoview build needs to be addressed via a different strategy and there's nothing actionable in this ticket.
