### ISSUE TITLE
If presenting while closing a tab, FxR blocks on the spinning torus

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/FirefoxReality#1071]
## Hardware
Oculus Go

## Steps to Reproduce
1. Launch the `webgfx-tests` or any website that has a link to a webvr experience (`target = _blank`)
2. Click on one of the tests, it will open the new tab (on WebIDE it will show as two tabs, the initial page and the new one with the WebVR app).
3. Enter VR
4. The tab is closed because the tests is over using `window.close()`, but we are still presenting

## Current Behavior
- The spinning torus appears, and it won't let me go back to the previous page or exit that mode. Even closing the app and opening it again will show the spinning torus, I need to force quit the app from ADB to restart.

## Expected Behavior
- Exit presenting mode and/or at least be able to exit and go back to the previous tab when pressing the "back" button.

**Comment by philip-lamb** [comment]
@cvan Do you have a link to the issue blocking this?

**Comment by cvan** [comment]
@philip-lamb I don't recall which issue this was blocked by. Feel free to remove the label if you cannot find it neither.
