### ISSUE TITLE
Generate outdated new L10n strings (from English `strings.xml`)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1072]
FxR's L10n `strings.xml` files for [non-English locales](https://github.com/MozillaReality/FirefoxReality/blob/b230f01/l10n.toml#L4-L13) are out of date [since Dec 14, 2018](https://github.com/MozillaReality/FirefoxReality/compare/95098ff..master#diff-01dafb3fd0217441330103cfc8300094).

[**View the changeset**.](https://github.com/MozillaReality/FirefoxReality/compare/95098ff..master#diff-01dafb3fd0217441330103cfc8300094) A few string values have been added, removed, changed, and a few string identifiers changed.

Files:
- [app/src/main/res/values/strings.xml](https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/main/res/values/strings.xml)
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml

## Context

For [version 1.1](https://blog.mozvr.com/firefox-reality-update-supports-360-videos-and-7-additional-languages/), @Delphine and @Pike [added the initial L10n strings to FxR](https://github.com/MozillaReality/FirefoxReality/commits/master?author=Pike) for non-English locales:
1. Nov 14, 2018: 54f045e: `Make l10n paths more common, add l10n.toml config for checks (#882)`
2. Dec 14, 2018: 95098ff: `Fixes #729, add localizations to FirefoxReality (#730)`

**Comment by cvan** [comment]
Filed https://github.com/mozilla-l10n/android-l10n/issues/16 for advice from the awesome L10n folks on next steps.

**Comment by Delphine** [comment]
I've based myself off of this for the diff: https://github.com/mozilla-l10n/android-l10n/compare/fe18cda7f6f82a76f60641399d2606f9bfe25023...FirefoxReality-quarantine

My review [is here](https://github.com/MozillaReality/FirefoxReality/issues/1089).

Let me know if I missed any strings. Otherwise I think we can close this issue :)

**Comment by philip-lamb** [comment]
OK, closing this as now tracked in #1089
