### ISSUE TITLE
Need to remove usage of Google services on non-google platforms

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#1077]
Oculus is now scanning all applications for usage of services that are not available on the platform. We currently reference the Google Speech services and need to remove that dependency.

We cannot update our in-store assets until this is fixed (it blocks the more formal review process).

cc @MortimerGoro

**Comment by larsbergstrom** [comment]
Some notes:
1) Explicit dependency on `com.google.vr:sdk-audio:1.190.0@jar` 
2) also found some some speech references in GeckoView: `import android.speech.tts.TextToSpeech;`
for `WebSpeech API`

May need to use proguard or some other post-processing tool.

**Comment by bluemarvin** [comment]
The `com.google.vr:sdk-audio` should be fine. It is cross platform and not tied to play. If they are flagging that, it is a error on their end. The `android.speech.tts.TextToSpeech` is our problem. I think is is used for a11y in GeckoView.

**Comment by bluemarvin** [comment]
But we can completely remove the `sdk-audio` if needed since it isn't even currently used.
