### ISSUE TITLE
URL bar scaling issues on fresh startup

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1079]
## Hardware

Wave. Image captured on Pico G2
## Steps to Reproduce

1. Do a clean install of FxR
2. Launch FxR

## Current Behavior

Some times the URL bar will be too large at start up:
![bar](https://user-images.githubusercontent.com/3066/56071969-25380400-5d47-11e9-8c28-213f7cfc0354.png)

## Expected Behavior

URL bar should be scaled correctly.

## Notes
This seems to be intermittent but I believe the regression was caused by #790

**Comment by bluemarvin** [comment]
This is 100% reproducible on the Pico G2.
![resize](https://user-images.githubusercontent.com/3066/56998536-724a1180-6b60-11e9-8f03-17fabf28dbe5.png)

**Comment by bluemarvin** [comment]
I still see the nav bar resize issue on Focus as well.

**Comment by bluemarvin** [comment]
I believe this is a regression from https://github.com/MozillaReality/FirefoxReality/pull/790

**Comment by cvan** [comment]
Filed issue #1137, referenced this issue. Will investigate. Thanks!
