### ISSUE TITLE
Consider supporting a no-controller mode

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1080]
## Hardware

Pico G2
## Context

The Pico G2 has buttons on the head set that makes a no-controller option possible. I don't believe it would be much work to support this mode on the device.

**Comment by bluemarvin** [comment]
![IMG_0652](https://user-images.githubusercontent.com/3066/56072164-ff136380-5d48-11e9-8ff3-20f5c9beafc9.jpg)
Top: app button
Middle: confirm button
Bottom: home button

**Comment by RealMG** [comment]
Also, have this trouble.
This might be caused by the limitation of VivePort, you could meet the same experience inside HTC VivePort

**Comment by jvonitter** [comment]
duplicated by #1578

**Comment by cjyjae35** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DE-80 Gaze Mode](https://trello.com/c/vKHoXnV6/488-de-80-gaze-mode)

**Comment by bluemarvin** [comment]
Fixed by #2959
