### ISSUE TITLE
Viveport release apk works well, but svr version shows black screen and long time no response.

### ISSUE THREAD

**Issue by RealMG** [MozillaReality/FirefoxReality#1081]
## Hardware
PicoVR G2
Qualcomm SVR845

## Steps to Reproduce

1.VivePort version works fine on PicoVR G2
2.SVR version works with a long time no response on G2 . (SVR SDK could work on Pico's devices)
3.SVR version works with a long time no response on Qualcomm SVR845

## Current Behavior
SVR version always shows a black screen and no response, click anywhere and a force close window pops up. 

## Expected Behavior
SVR version could work.

```
```

</details>

**Comment by philip-lamb** [comment]
Not assigning a current milestone as we are not providing full support for any bare SVR devices, but will accept patches.
