### ISSUE TITLE
Review of l10n strings for next release

### ISSUE THREAD

**Issue by Delphine** [MozillaReality/FirefoxReality#1089]
Please find below my comments about the string review I did, coming from the [l10n quarantine PR here](https://github.com/mozilla-l10n/android-l10n/pull/19).
@philip-lamb @larsbergstrom: could you please help confirm [this is in fact the diff](https://github.com/mozilla-l10n/android-l10n/compare/fe18cda7f6f82a76f60641399d2606f9bfe25023...FirefoxReality-quarantine#diff-94c00033169dcdc3c847971fdb6ef5ba) of strings from last time we worked together in Dec?

Review:
* "settings_privacy_policy": string ID is changed although string remains the same. Want to make sure that is expected?
* [L275](https://github.com/mozilla-l10n/android-l10n/compare/fe18cda7f6f82a76f60641399d2606f9bfe25023...FirefoxReality-quarantine#diff-5bf7ef0fb54e59bdde826c6df99abe87R275): seems like there is a missing string there
* developer_options_env_offworld: probably better to give a small explanation of what "Offworld" is like so translators know how to translate it correctly
* security_options_permissions_title: I think it's ok to keep the branding here, but just want to call out that "Firefox" is localizable here. Your call
* "homepage_hint": same heads-up about branding here

**Comment by philip-lamb** [comment]
Awesome, thanks Delphine. Comments inline below:

>     * "settings_privacy_policy": string ID is changed although string remains the same. Want to make sure that is expected?
Yes, that is as expected.

>     * [L275](https://github.com/mozilla-l10n/android-l10n/compare/fe18cda7f6f82a76f60641399d2606f9bfe25023...FirefoxReality-quarantine#diff-5bf7ef0fb54e59bdde826c6df99abe87R275): seems like there is a missing string there
This comment can be ignored; it appears to be left over from a move of the comment and the string to [L245](https://github.com/mozilla-l10n/android-l10n/blob/6dedbefb96fab51e9431dd1d47c7e4e488443517/MozillaReality/FirefoxReality/app/src/main/res/values/strings.xml#L245)

>     * developer_options_env_offworld: probably better to give a small explanation of what "Offworld" is like so translators know how to translate it correctly
OK, I'll add some explanatory text in the comment. It refers to the sci-fi themed desert environment.

>     * security_options_permissions_title: I think it's ok to keep the branding here, but just want to call out that "Firefox" is localizable here. Your call
Well spotted. Will correct this.

>     * "homepage_hint": same heads-up about branding here
Ditto.
