### ISSUE TITLE
Security risk  with Focus Mode

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#110]
Current URL is hidden while in Focus mode. If the user clicks a link it doesn't see the real URL where he is navigating to.

We need to show the URL change someway

**Comment by bluemarvin** [comment]
see #106

**Comment by MortimerGoro** [comment]
Potential idea to fix the security risk and confusion from some users of not having navigation buttons.

We could show the navigation bar buttons/URL when the remote controller is pointing to the space below the window, and hide them when not (to get the reduced Focus mode wants to achieve).

Need a decision made about this soon to have it time to ship it for the user testing

**Comment by avrignaud** [comment]
@thenadj - can you take a look? Issue is that there is a security risk in Focus Mode because the URL bar isn't shown. As such, it is possible that a user might click on a URL and be taking to a hostile/phishing site and not recognize it (think fake Bank page trying to capture login credentials).

**Comment by thenadj** [comment]
Ok, we have a solution. We're going to add a small UI at the top of the window with a preview of the URL as a user hovers over a link. When a user is in the new page, they can then check what URL they are in by hovering over that area above the window to bring that UI back up. UI Spec coming shortly, we'll attach it to this issue when it's done. 

FYI - We discussed options to put the URL bar below the window, but it would mean more significant changes as we'd then have to move the resize button, so we'll tag that for v1.1
@MortimerGoro @avrignaud

**Comment by MortimerGoro** [comment]
Thanks for the update.

I still have to see how the UI looks to get the idea better but just based on the description, isn't it confusing to have the URL below the window in regular mode and above the window in Focus mode?

**Comment by thenadj** [comment]
We're working through it and will show you the design soon. I wanted to keep the dev work to an absolute minimum but I think we can make the URL bar work at the bottom without too much shuffling of current UI.

**Comment by thenadj** [comment]
We have a solution for this problem. See attached PDF

[Bug-15 Focus Mode URL Preview_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2214711/Bug-15.Focus.Mode.URL.Preview_001.pdf)

**Comment by MortimerGoro** [comment]
Implemented the URL bar visibility when a webpage is in a loading state. I didn't implement the show/hide because of a technical problem (programmatic hover listeners on Android were not very reliable).

`For v1.1 we'll have more time to really think the design through.`

Ok ;) The thing I'm missing while using the app is full navigation with a different window size than the default one. If we can  find a good way to untie resizing from focus mode I think users are gonna like it.
