### ISSUE TITLE
String update needed because error in placeholder 

### ISSUE THREAD

**Issue by Delphine** [MozillaReality/FirefoxReality#1105]
My co-worker let me know he found an error in two strings while he was doing localization work.

Two strings have errors in their placeholders:
* video_controls_seek_forward
* video_controls_seek_backward
Strings both read: "%1$", while they should be "%1$s" (missing "s" at the end).

This probably means this isn't working for en-US version, either.

**Comment by cvan** [comment]
fixed in PR #1106, now on `master`. thanks! let us know if there's anything else.
