### ISSUE TITLE
HTTPS sites fail to load (intermittent; required a reinstall)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1112]
## Hardware
**Oculus Go**
master (9399f88)

## Steps to Reproduce
1. Launch FxR.
2. Notice the Feed doesn't load (since it's served over HTTPS).
3. Navigate to http://example.com, and notice it loads.
4. Navigate to an HTTPS-only site such as https://sketchfab.com/, and notice it doesn't load.
5. Load the Oculus Browser, and notice HTTPS sites work as expected.
6. Force stop FxR (`adb shell am force-stop org.mozilla.vrbrowser`), and notice HTTPS sites still don't work.
7. Had to uninstall (`adb uninstall org.mozilla.vrbrowser`) and reinstall FxR for HTTPS sites to load properly.

- Checked the system clock in case issue with certificate expiry dates, but the clock was correct. And Oculus Browser had no issue with loading the sites.
- Switched WiFi networks, and I was still able to reproduce this issue.

### HTTPS
![image](https://user-images.githubusercontent.com/203725/56552153-3222d780-653f-11e9-9247-be28ee76cad1.png)
![image](https://user-images.githubusercontent.com/203725/56552158-3818b880-653f-11e9-8211-f63d830b20c8.png)

### HTTP
![image](https://user-images.githubusercontent.com/203725/56552164-3a7b1280-653f-11e9-840e-a9840043a934.png)

## Expected Behavior
HTTPS sites load properly.

## Error Logs and Stack Traces

[`adb logcat`](https://github.com/MozillaReality/FirefoxReality/files/3105706/fxr-https-failure-logcat.txt)

**Comment by bluemarvin** [comment]
@snorp is this the same issue fenix is seeing?

**Comment by philip-lamb** [comment]
@cvan Was this on a public wifi network?

**Comment by philip-lamb** [comment]
P2 without milestone until we can reliably reproduce on a release build.

**Comment by cvan** [comment]
> @cvan Was this on a public wifi network?

twice: twice on residential WiFi (Comcast) and once on commercial Mozilla WiFi (ateam)

**Comment by bluemarvin** [comment]
Over a year with no additional reports.
