### ISSUE TITLE
Links in "Firefox Reality internals: graphics pipeline" seems old

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/FirefoxReality#1115]
In wiki page "Firefox Reality internals: graphics pipeline" includes some links to specific source code line.

https://github.com/MozillaReality/FirefoxReality/wiki/Firefox-Reality-internals%3A-graphics-pipeline

For example

> Firefox Reality exposes a render Surface to GeckoView https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java#L312.

But the links seem old. They link to master branch source code. But master branch keeps being updated so the line number can be old quickly. Probably linking to the tagged one is more robust, for example

https://github.com/MozillaReality/FirefoxReality/blob/1.1.4/app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java#xxx

**Comment by philip-lamb** [comment]
Good point. Pinned the links to recent version.
