### ISSUE TITLE
Increase click targets for Settings radio buttons

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1118]
## Hardware
Oculus Go

## Steps to Reproduce

1. Launch the Settings from the Tray.
2. Press Languages.
3. Scroll down the list of languages.
4. Try to select Español.
5. Notice it can take a couple hard trigger-presses to get the radio button to get properly selected.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by keianhzo** [comment]
@jvonitter I can't reproduce this.

**Comment by jvonitter** [comment]
if this comes back, we'll resurrect it.
