### ISSUE TITLE
Crash from `NotoSansCJK-Regular.ttc@0x92a1f3` on Samsung Galaxy S7

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1123]
## Hardware
Samsung Galaxy S7

## Steps to Reproduce
1. Load a web page that uses [Noto Sans CJK](https://en.wikipedia.org/wiki/Noto_fonts#CJK).
2. See if FxR crashes.

## Error Logs and Stack Traces
**[Submitted crash report.](https://crash-stats.mozilla.com/report/index/98c82288-3373-4525-887d-9fb950190415)**

**Comment by cvan** [comment]
Assigning to myself to create a test case of a web page to determine if it's caused by a web page or usage of the default system font, [Noto Sans](https://www.google.com/get/noto/) on newer Android versions.

**Comment by philip-lamb** [comment]
@cvan If you don't think you'll get to this by v1.2 code freeze, push to v1.3 milestone please.

**Comment by cvan** [comment]
So, I investigated this. [Turns out](https://stackoverflow.com/a/49159155) you can't import [TTC fonts](https://en.wikipedia.org/wiki/TrueType#Font_formats) as web fonts with CSS' `@font-face`, so this was not caused by a web page, *phew*.

It looks an Android system crash is occurring in [rendering UI](https://github.com/MozillaReality/FirefoxReality/blob/3e47cb1/app/src/main/cpp/Widget.cpp#L85-L105) by using `android:fontFamily="sans-serif"` with the Japanese (`ja-JP`) locale on Samsung Galaxy S7 (or non-Oculus/non-HTC) Android phones. The crash been reported by only one user so far, and we don't officially support the S7, correct?

It looks like there's a history of issues with Gecko and the Noto font family on Android.

- https://bugzilla.mozilla.org/show_bug.cgi?id=1529673
- https://bugzilla.mozilla.org/show_bug.cgi?id=1403436
- https://bugzilla.mozilla.org/show_bug.cgi?id=1122693
- https://searchfox.org/mozilla-central/search?q=noto+sans+cjk

Can we close this as it's an unsupported platform? Or if the Gecko folks have ideas, we can file a Bugzilla bug to follow up. Thoughts?

**Comment by philip-lamb** [comment]
Thanks for the detailed investigation. My inclination is to close as `invalid` because this is an unsupported platform. We can reopen if we get identify a fix or it crops up on a supported platform.

**Comment by cvan** [comment]
At the very least, I'll move out of 1.2. Feel free to close as whatever. Thanks!
