### ISSUE TITLE
Add graph for device types to telemetry dashboard

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#1140]
It would be useful to track the prevalence of different device models so that we can make informed decisions about optimisation, device support effort etc.

This information is already collected in the mobile telemetry core ping in field `device`. (See See https://github.com/mozilla-mobile/android-components/blob/master/components/service/telemetry/src/main/java/org/mozilla/telemetry/ping/TelemetryCorePingBuilder.java#L48 and https://github.com/mozilla-mobile/android-components/blob/master/components/service/telemetry/src/main/java/org/mozilla/telemetry/measurement/DeviceMeasurement.java#L26 for reference).

We need to design a query that extracts device types and graphs it appropriately.

Two draft queries:
* https://sql.telemetry.mozilla.org/queries/62523/source#160532
* https://sql.telemetry.mozilla.org/queries/62521/source#160528

This enhancement requires:
* Refinement of the telemetry query to display a grouped line chart showing % share of total device use over time.
* Possible second query with grouped line chart showing total device usage over time.
* Addition of one or both charts to the Firefox Reality telemetry dashboard: https://sql.telemetry.mozilla.org/dashboard/firefox-reality_1

**Comment by daoshengmu** [comment]
I have updated the device types telemetry (amount and percentage) at https://sql.telemetry.mozilla.org/dashboard/firefox-reality_1. Regarding to the total device usage over time, we can just take the DAU chart as the reference.
