### ISSUE TITLE
Design UI + UX for viewing History

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1141]
Originally discussed in **issue #635**. This issue covers the design of how a user will view their browsing History.

**Issue #336** will cover how users will clear their browsing History (including single deletion, group deletion, and entire deletion).

The ability to search History and filter by preset date ranges (see other Firefox platforms' implementations) can be handled in this issue or deferred to implement at a later date.

This design should be informed by the existing History implementations in Firefox on desktop, Firefox for iOS, Fenix on Android, and the functionality provided by [GeckoView and its android-components](https://github.com/mozilla-mobile/android-components/search?q=history&unscoped_q=history). See **issue #614**.

<hr>

Tracked by parent meta **issue #957**.

**Comment by jvonitter** [comment]
User flow for seeing history, clearing history and changing history settings: https://trello.com/c/VUiURGJ1/337-uf-62-history

**Comment by jvonitter** [comment]
this is done. closing this ticket since it's just for the design task. implementation task (#1283) is still opened

Final spec is here: https://trello.com/c/CPyXxcZp/371-uis-78-history
