### ISSUE TITLE
Allow keyboard to be repositioned

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#1146]
Allow keyboard to be repositioned.

(UX and design aspects are covered in related user testing master issue #480. This issue is to track implementation work.)

- [ ] Implement dynamic positioning (i.e relative to web content) based on design specification.
- [ ] Implement a UI element which allows user to reposition temporarily.
- [ ] Allow the user to pin the keyboard in a preferred location, and to unpin and revert to dynamic positioning.

needed-by #480

**Comment by jvonitter** [comment]
@thenadj and I have tried the latest of @MortimerGoro 's changes and we love the movable keyboard! the only update we'd like to see is for the keyboard to stay where the user puts it. When the app restarts or the keyboard gets into a weird state (though I'm not sure how that would happen) it can reset itself, but otherwise it should stay where a user left it.

**Comment by MortimerGoro** [comment]
@jvonitter @thenadj APK with the latest movable keyboard updates: https://send.firefox.com/download/2d50a0430111b165/#3T5GGvRpX8SOlqeNnVTT_Q

Now it saves the latest position

**Comment by jvonitter** [comment]
Awesome! I'll give it a try today.

**Comment by thenadj** [comment]
Looks and feels great!

**Comment by jvonitter** [comment]
It's great, overall! I did notice one minor issue - let me know if you want a separate ticket for it:
The pointer gets detached from the move button depending on where the keyboard is when you select/drag. It's particularly noticeable if you put the keyboard all the way to the bottom left, then grab the move button to pull it back into the center. It doesn't do this when the keyboard is at the top of the screen, so my guess is that it's something to do with the angle the keyboard has when it's at the bottom of the screen.
