### ISSUE TITLE
Allow windows to be repositioned

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#1147]
Allow windows to be repositioned.

(UX and design aspects are covered in related user testing master issue #480. This issue is to track implementation work.)

- [ ] Implement dynamic positioning algorithm based on design specification.
- [ ] Implement UI element(s) that collect user positioning intent as input to algorithm.
- [ ] Connect algorithm to scenegraph.

needed-by #480

**Comment by jvonitter** [comment]
We covered this as part of multiwindow
