### ISSUE TITLE
Allow tray to be repositioned

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#1148]
Allow tray to be repositioned.

(UX and design aspects are covered in related user testing master issue #480. This issue is to track implementation work.)

- [ ] Implement dynamic positioning (i.e relative to user position) based on design specification.
- [ ] Implement a UI element which allows user to reposition temporarily.
- [ ] Allow the user to pin the tray in a preferred location, and to unpin and revert to dynamic positioning.

needed-by #480

**Comment by jvonitter** [comment]
Multiwindow depends on the tray being in a fixed location, though now the tray moves with the user as they look at different windows.
