### ISSUE TITLE
Select Chinese Pinyin keyboard by default when user's OS locale is set as such

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1150]
**Is your feature request related to a problem? Please describe.**
When the user's locale is `zh-TW`, should the Chinese Traditional (`zh-TW`) keyboard be shown by default? Currently, it shows the English keyboard. And the user has to know to click the Globe icon to change the keyboard.

**Describe the solution you'd like**
Ideally, on application launch FxR uses the keyboard corresponding to the system locale (i.ge, English vs. Pinyin today).

When the user changes the keyboard, FxR persists that changed system locale. Any subsequent relaunches use that system locale. The user could change it, etc.

**Describe alternatives you've considered**
Possibly leave it as is.

**Additional context**
This can be augmented by the work to be done in #1134.

**Comment by MortimerGoro** [comment]
Android has some utilities to get the best locale match based on the system keyboard. I used that in #1151 to implement this
