### ISSUE TITLE
Missed keys on the keyboard

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#1154]
It's easy to miss a keyboard click if you move the controller fast after pressing the key (before releasing it inside).

Probably is a regression from: https://github.com/MozillaReality/FirefoxReality/pull/1070

We can add a timer check to fix this issue or back-out that commit.

**Comment by cvan** [comment]
I noticed this but just assumed it was an issue with my controllers or perception. Thanks for filing :+1:

**Comment by philip-lamb** [comment]
I agree that #1070 has made rapid typing much more difficult. What was the original issue that it was trying to address? I'm in favour of backing it out.

**Comment by MortimerGoro** [comment]
@philip-lamb The original issue was that keys are detected but you can write a different key if you release the input outside of the wanted key. The PR fixed the problem but has caused missed keys instead.

I pushed a new solution in https://github.com/MozillaReality/FirefoxReality/pull/1159, which captures the down key until the press is released, so it always types the correct key even if you release the pointer outside.
