### ISSUE TITLE
Restore the .com key plus add other top level domains to keyboard

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1156]
**Is your feature request related to a problem? Please describe.**
The keyboard use to have a `.com` key that was removed with the current updates.

**Describe the solution you'd like**
The domains should be added to the `.` pop up like is done on iOS

**Comment by jvonitter** [comment]
Noted! We'll try to get some data around this when we test the keyboard. Putting it in the backlog for now.

**Comment by bluemarvin** [comment]
The `.com` key has been restored.
