### ISSUE TITLE
Consider highlighting actively selected locale in Language Selection pop-up menu

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1165]
**Is your feature request related to a problem? Please describe.**
It's not a problem per se, but the UX is a tad confusing because.

**Describe the solution you'd like**
per my review comment in PR #1151: https://github.com/MozillaReality/FirefoxReality/pull/1151#pullrequestreview-234145327:

> 2. when I click the keyboard's 🌐globe icon, the last locale is highlighted because the cursor is hovering over it. can we add a threshold to only hover if the cursor is changed drastically so it's not automatically highlighted?
> 
> 3. per the [`UIS-6.017` spec](https://github.com/MozillaReality/FirefoxReality/files/3149409/UIS-6_Keyboard_017.pdf), the name of the Locale should appear in the space bar. @thenadj: does this apply to only non-English locales? (perhaps we should have the text read `Space` in the appropriate current keyboard locale?)
>     
>     ![image](https://user-images.githubusercontent.com/203725/57248051-40203000-6ff6-11e9-8170-2f23827a21eb.png)
>     ![image](https://user-images.githubusercontent.com/203725/57248073-4dd5b580-6ff6-11e9-803b-763b3ace4446.png)
>     

[`DE-12.012` design exploration](https://github.com/MozillaReality/FirefoxReality/files/3149416/DE-12_Keyboard_012.pdf) suggests a different approach using the `Space` key:

> 4. per the [`DE-12.012` design exploration](https://github.com/MozillaReality/FirefoxReality/files/3149416/DE-12_Keyboard_012.pdf), can we highlight or change the text colour to denote the active keyboard locale?
>     
>     ![image](https://user-images.githubusercontent.com/203725/57247808-a6588300-6ff5-11e9-9d31-68ca73442f9d.png)
> 

**Describe alternatives you've considered**
Could **bold** the text, use a `@color/fog` (#e2e6eb) background colour (à la actively selected tray items), or in some other way that users can visually tell which locale is being used for the keyboard layout.

**Additional context**
See issue #1134, issue #1150, PR #1151, and PR #1151 comment https://github.com/MozillaReality/FirefoxReality/pull/1151#pullrequestreview-234145327 for context.

**Comment by thenadj** [comment]
@cvan Can you please share an APK with me so I can take a look at the current implementation?

**Comment by MortimerGoro** [comment]
@thenadj the APK I just sent via slack already have this, you can use that one

**Comment by cvan** [comment]
@thenadj you can use the APK @MortimerGoro sent. or [download here](https://fxr.glitch.me/oculusvr) the latest APK of `master`, which includes @MortimerGoro's recent changes in merged PR #1151.

**Comment by philip-lamb** [comment]
Pushing to backlog in v1.3.

**Comment by MortimerGoro** [comment]
This has been fixed in #1201.

@philip-lamb just saw that it was moved to 1.3.  I had some pending  fixes for the lang selector view so I also did this one.
