### ISSUE TITLE
modifier keys should be displayed in uppercase when Shift on (not just Caps Lock)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1179]
reported in https://github.com/MozillaReality/FirefoxReality/pull/1158#pullrequestreview-234156708:

when ⇪ **Caps Lock** (enabled by double-clicking on the up arrow) is enabled, the modifier keys appear as uppercased, as expected. but when only the **Shift** key is active (enabled by single-clicking on the up arrow), the modifier keys appear lowercased. can we have the modifier keys appear in uppercase or lowercase depending on the Shift state as well?
    
![image](https://user-images.githubusercontent.com/203725/57249343-8aef7700-6ff9-11e9-8f1d-e5ec101ec129.png)

vs.

![image](https://user-images.githubusercontent.com/203725/57249519-081aec00-6ffa-11e9-9e83-0cf540207305.png)

**Comment by philip-lamb** [comment]
Fixed by #1220
