### ISSUE TITLE
Prevent modifier-keys group  from wrapping to two lines (`Ṇ`/`ṇ` in Spanish keyboard)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1180]
reported in PR for Español keyboard in https://github.com/MozillaReality/FirefoxReality/pull/1158#pullrequestreview-234156708:

can the `Ṇ`/`ṇ` keys appear on the same row as the other `N`/`n` modifier keys? it looks like a bug that the `Ṇ`/`ṇ` keys appear isolated in a single row below the row for the modifier key.
    
![image](https://user-images.githubusercontent.com/203725/57249503-fafdfd00-6ff9-11e9-8368-bff41a477160.png)
    
![image](https://user-images.githubusercontent.com/203725/57249506-fdf8ed80-6ff9-11e9-8b45-aafcc9711771.png)
    
![image](https://user-images.githubusercontent.com/203725/57249510-00f3de00-6ffa-11e9-9931-a6673bb84d8e.png)

**Comment by philip-lamb** [comment]
Fixed by #1221
