### ISSUE TITLE
Improve autocompletion line width for layout changes

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#1183]
See #1173 

Some keyboards will have a different width so the value won't match and the ideal thing is detect onResize changes. It works ok for chinese keyboard for now, as it size is fixed.

**Comment by philip-lamb** [comment]
Backlog in v1.3 as workaround is OK for v1.2.

**Comment by philip-lamb** [comment]
needed-by #1183

**Comment by MortimerGoro** [comment]
@philip-lamb `needed-by` link seems work, it self-references

**Comment by philip-lamb** [comment]
> @philip-lamb `needed-by` link seems wrong, it self-references

Thanks, corrected now.
