### ISSUE TITLE
Shader compile+link time is much longer than Oculus Browser on Oculus Go

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/FirefoxReality#1186]
## Hardware
Oculus Go

## Steps to Reproduce

1. Open this test page https://raw.githack.com/takahirox/KHR_parallel_shader_compile_test/master/blocktime.html
2. Click run button
3. See the elapsed time

Code snippet

```javascript
function runTest(id) {
  const startTime = performance.now();

  const vertexShader = gl.createShader(gl.VERTEX_SHADER);
  gl.shaderSource(vertexShader, vertexShaderCode);
  gl.compileShader(vertexShader);

  const fragmentShader = gl.createShader(gl.FRAGMENT_SHADER);
  gl.shaderSource(fragmentShader, fragmentShaderCode);
  gl.compileShader(fragmentShader);

  const program = gl.createProgram();

  gl.attachShader(program, vertexShader);
  gl.attachShader(program, fragmentShader);

  gl.linkProgram(program);

  const status = gl.getProgramParameter(program, gl.LINK_STATUS);
  const endTime = performance.now();

  document.getElementById(id).innerText = (endTime - startTime).toFixed(2) + 'ms, ' + status;
}
```

## Current Behavior

FireFox Reality: 45ms
Oculus Browser: 18ms

## Expected Behavior

FireFox Reality is as fast as Oculus Browser

## Possible Solution

I'm facing the same performance issue FireFox vs Chrome on my desktop Windows. Maybe the same root issue on Gecko?

https://bugzilla.mozilla.org/show_bug.cgi?id=725467#c1

## Context

Longer shader compile+link time can lead to more big frame drop on web application start up.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
This would be a Gecko issue and should probably be filed against the core graphics WebGL component.

**Comment by philip-lamb** [comment]
@takahirox If you file a bugzillla bug for this, please copy a link to it back here.

**Comment by philip-lamb** [comment]
@fernandojsg You mentioned today that you were looking at WebGL performance. Would you like to take this bug and update it with any findings?
