### ISSUE TITLE
Transition from Proguard to R8

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#1190]
R8 is replacing Proguard in Android tools.

We have a number of dependencies on proguard in our build system to manipulate library dependencies.

We should transition to R8, first in compatibility mode, and eventually in native mode.

https://android-developers.googleblog.com/2018/11/r8-new-code-shrinker-from-google-is.html

**Comment by philip-lamb** [comment]
@bluemarvin Would you like to take this one? If not, @MortimerGoro perhaps?

**Comment by philip-lamb** [comment]
R8 is reported to be a lot faster than Proguard; this could lower our release build duration.

**Comment by MortimerGoro** [comment]
Fixed in #1428
