### ISSUE TITLE
Settings UI dims background but background UI can still be interacted with

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#1195]
## Hardware
HTC Vive Focus Plus
FxR f0c5f45a8d970e0087f08dce6e3d35c381f583c4
From testing partner report.

## Steps to Reproduce
Open settings pane. 

## Current Behavior
Observe background is dimmed, as if interacting with modal window, but background UI is still able to be interacted with.

## Expected Behavior
Is this by design? If so, we can close this as `invalid`.

**Comment by MortimerGoro** [comment]
Fixed via #1211
