### ISSUE TITLE
Radio button should hover state when raycast pointed on

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#1196]
## Hardware
HTC Vive Focus Plus
FxR f0c5f45a8d970e0087f08dce6e3d35c381f583c4
From testing partner report.

## Steps to Reproduce
Hover pointer over radio button (in settings UI? or in webpage? Not clear from report).

## Current Behavior
Radio button does not hover state when raycast pointed on

## Expected Behavior
Radio button should hover state when raycast pointed on

## Notes
If this report refers to web content, what is the expected behaviour? Same question for Android UI. We can close as `invalid` if what we do is expected behaviour.

**Comment by MortimerGoro** [comment]
I think this is related to radio buttons in settings. At least they don't have any hover effect right now.

cc @thenadj we need some design for radio button hover (e.g. the ones in environment selector lists or voice search language selectors in UI settings). We could add a hover effect to the whole row or only to the radio button itself

**Comment by philip-lamb** [comment]
OK, I'm happy to push this to 1.3.

**Comment by thenadj** [comment]
@MortimerGoro @philip-lamb Adding this to our design list.

**Comment by thenadj** [comment]
Attached is UIS-66 for radio button interaction states.

[UIS-66 Toggle and Radio Button States_002.pdf](https://github.com/MozillaReality/FirefoxReality/files/3199266/UIS-66.Toggle.and.Radio.Button.States_002.pdf)

https://trello.com/c/rY0zvwbF/311-uis-66-toggle-and-radio-button-states

**Comment by thenadj** [comment]
Attached is the updated version for the radio button UIS as per [GH-1339](https://github.com/MozillaReality/FirefoxReality/pull/1339)
[UIS-66 Toggle and Radio Button States_003.pdf](https://github.com/MozillaReality/FirefoxReality/files/3312113/UIS-66.Toggle.and.Radio.Button.States_003.pdf)
