### ISSUE TITLE
Go to second layer in Settings, the transition between two screens looks like flashing

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#1197]
## Hardware
HTC Vive Focus Plus
FxR f0c5f45a8d970e0087f08dce6e3d35c381f583c4
From testing partner report.

## Steps to Reproduce
Go to second layer in Settings

## Current Behavior
The transition between two screens looks like flashing

## Expected Behavior
Should not flash.

## Notes

**Comment by philip-lamb** [comment]
Fixed by #1218

**Comment by cvan** [comment]
_(for reference, if someone's looking at this issue and haven't read through the comments in PR #1218)_

PR #1218 fixed the issue at hand here, but do notice my comment here https://github.com/MozillaReality/FirefoxReality/pull/1218#pullrequestreview-238121687:
> even though the yellow outline seems to be a minor regression with these changes, I agree we can defer to this issue: https://github.com/MozillaReality/FirefoxReality/issues/1005#issuecomment-492862157 (hopefully HTC doesn't have a problem with it.)
