### ISSUE TITLE
Deploy bleeding-edge APK download service to a more stable service than Glitch

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1200]
In PR #1172, I added links to the README for a [service](https://fxr.glitch.me/) ([view source](https://glitch.com/edit/#!/fxr?path=server.js:1:0)) I created to more easily download the APKs from the most recently **completed** Taskcluster build:

![](https://user-images.githubusercontent.com/203725/57356124-7d82db80-7124-11e9-9015-611640b8e860.png)

[Glitch](https://glitch.com/) is a great tool for prototyping web services, but because Glitch is currently free, there's an aggressive daemon that hibernates idle projects when the page is not being actively used by users, which often causes projects to take a while to cold launch.

Let's deploy the server code to a Heroku instance (we have a Mozilla Corporation account used for various one-off projects).

Looking longer term, @bluemarvin suggested in https://github.com/MozillaReality/FirefoxReality/pull/1172#issuecomment-490573922 that  Taskcluster could start providing a similar method of serving artifacts on demand without having to cumbersomly calling Taskcluster API endpoints (e.g., with helper redirect URLs à la https://github.taskcluster.net/v1/repository/MozillaReality/FirefoxReality/master/latest). I've filed a feature request for Taskcluster: taskcluster/taskcluster#724.

**Comment by cvan** [comment]
BTW, I contacted someone at Glitch, and https://fxr.glitch.me will now always be alive and not need to be restarted after idle time.

The project's [source code here](https://glitch.com/edit/#!/fxr?path=server.js:1:0) is viewable on Glitch, so if someone wants to migrate this service elsewhere, feel free to. Also, see this Taskcluster issue if you want to simplify the code path: https://github.com/taskcluster/taskcluster/issues/724#issuecomment-491277957

**Comment by avrignaud** [comment]
Quick note, looks like fxr.glitch.me is down. We might indeed want to move
this if it's an issue.
-- 
Andre Vrignaud — Head of Mixed Reality Platform Strategy | Emerging
Technologies | Mozilla
avrignaud@mozilla.com | +1 (206) 245-6067 <%2B1.206.245.6067> | Skype:
andrevrignaud

**Comment by jvonitter** [comment]
we'll use taskcluster for this instead. see #1905
