### ISSUE TITLE
Z-fighting between display and URL bar in curved-display mode

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#1207]
## Hardware
All
FxR v1.2-rc1

## Steps to Reproduce
Switch to curved display mode in settings. Resize content window to large size.

## Current Behavior
Content window and URL bar z-fight.

## Expected Behavior
Correct depth occlusion.

## Possible Solution
Enable z-test.

## Error Logs and Stack Traces
Video: https://drive.google.com/file/d/1QrTVOEybaojvL_pUNT_tQae-WgoGBGD6/view?usp=sharing

**Comment by bluemarvin** [comment]
Due to the way async layers work on Oculus hardware, there is no z-buffer since the layers are composed in the system vr compositor.

**Comment by MortimerGoro** [comment]
Seems to be related to the fact that the url and window cylinders don't match, I'l take a look.
