### ISSUE TITLE
Automatically append `&mozVideoProjection=360_auto` to YouTube 360 URLs

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1215]
## Hardware
Oculus Go

## Steps to Reproduce
1. Load [_Curated x Kai_'s YouTube channel page](https://www.youtube.com/channel/UC0XhbNGFvsdU7Vv6S3JbR2w).
2. Scroll to the bottom to find and click on the 360 video titled [_The Official Obama Portraits - Curated x Kai_](https://www.youtube.com/watch?v=4GMSoPN8suM).
3. Notice the URL does not contain `mozVideoProjection=360_auto`, which means the user has to first click the Fullscreen icon, click on the VR-goggles icon, and then manually select the projection to get in the correct 360° projection.

**Comment by philip-lamb** [comment]
Fixed in #1217.
