### ISSUE TITLE
Keyboard's Modifier Keys appear uppercased in pop-up menu when Caps Lock was enabled previously in the user's previous keyboard

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1225]
## Hardware
**Oculus Go**
- `master` (78508515)
- `release-1.2` (25662250)
- `keyboard_shift` (PR #1220, ea6790d5)

## Steps to Reproduce
1. Press the URL bar to open the keyboard.
2. Double-press the Shift key to enable Caps Lock.
3. Press-and-hold on a character to expose its Modifier Keys.
4. Notice the modified characters are expectedly listed in uppercase and upon press do print the correctly uppercased modified character.
4. Switch keyboards by pressing the Globe 🌐key.
5. In the new keyboard (without touching the Shift key), press-and-hold on a character to expose its Modifier Keys.
6. Notice the modified characters are unexpectedly listed in uppercase but upon press print the lowercased modified character.

## Current Behavior
Modifier Keys are displayed in uppercase (but printed in lowercase) when Caps Lock was previously enabled in the user's previously used keyboard.

[**Watch video capture**<br><br><img src="https://im.ezgif.com/tmp/ezgif-1-68f92850224f.jpg" alt="Screenshot of video capture">](https://vimeo.com/336302599/9798656b39)

## Expected Behavior
Modifier Keys should be displayed in lowercase (that is, Caps Lock state should be reset when changing keyboards), even if Caps Lock was previously enabled before the user switched to a different keyboard.

## Context
Similar issue: #1179 (fixed in PR #1220).

**Comment by philip-lamb** [comment]
Fixed by #1277
