### ISSUE TITLE
Load desktop `youtube.com` URL if mobile `m.youtube.com` URL is requested

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1229]
## Hardware
Oculus Go

## Steps to Reproduce

1. Load https://www.google.com/
2. Type `youtube 360 lions`
3. Notice the Google Search returns page lists https://m.youtube.com/ URLs (as opposed to https://youtube.com/ URLs)
4. Click on the first result: https://m.youtube.com/watch?v=14O7AxqjiVY
5. Notice the YouTube video uses the mobile layout, which we don't want because it doesn't let us provide the 360 video playback w/ the high-res layout

## Current Behavior
Google search results link to https://m.youtube.com/ video URLs, which Firefox Reality cannot support properly for 360 + 2D video playback w/ high-res layout.

## Expected Behavior
Even if a page (e.g., Google search results) links to https://m.youtube.com/watch?v=14O7AxqjiVY, Firefox Reality should intercept the URL request and load https://youtube.com/watch?v=14O7AxqjiVY

If the user explicitly enters the URL into the URL bar, perhaps we should not redirect from `m.youtube.com` -> `youtube.com`. But I think for the time being, we should redirect regardless.

**Comment by philip-lamb** [comment]
Fixed in #1230
