### ISSUE TITLE
WebGL context will get lost after entering and exiting WebVR immersive mode multiple times.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#123]
May be a Gecko issue.

**Comment by bluemarvin** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1474847

**Comment by bluemarvin** [comment]
@MortimerGoro has found there is an issue with surface textures not getting released and we eventually reach the system limit.

**Comment by MortimerGoro** [comment]
Created this GV patch: https://phabricator.services.mozilla.com/D4236

We can close this issue when the patch is merged

**Comment by MortimerGoro** [comment]
GV patch already merged
