### ISSUE TITLE
Can't enable autoplay for embedded audio media

### ISSUE THREAD

**Issue by hhxiaohei** [MozillaReality/FirefoxReality#1231]
## Hardware
Pico VR G2

## Steps to Reproduce
1.A vr web page
```html
<audio id="music" src="1.mp3" autoplay="autoplay"></audio>
```
2.on Chrome,FF PC can autoplay,but in FirefoxReality audio is not work

FirefoxReality tell me:
```javascript
 The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
```

`How can the audio autoplay by js or other? Thx!`

**Comment by philip-lamb** [comment]
@bluemarvin I believe you worked on adding API for autoplay settings to GV. Is this just a case of carrying them through to FxR?

See also:
* https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoRuntimeSettings.html#setAutoplayDefault-int-
* https://github.com/mozilla-mobile/firefox-tv/issues/2040

**Comment by bluemarvin** [comment]
The settings dialog just needs the option added to it. GeckoView should already have the required API.

**Comment by philip-lamb** [comment]
Based on UX design from Firefox, add setting in Security and Privacy pane, below the permissions settings, English text "Block websites from automatically playing sound", defaulting to enabled.

**Comment by philip-lamb** [comment]
We'll need a separate issue to track allowing this on a per-site basis.

**Comment by jvonitter** [comment]
@thenadj - We're going to add this setting in since it's also in desktop and mobile. It'll use the same language and placement as we do there. No design needed, just FYI
