### ISSUE TITLE
Korean Keyboard

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1235]
Spec is here: https://trello.com/c/4MSGPrFY/198-uis-57-korean-keyboard
cc @thenadj

**Comment by daoshengmu** [comment]
@jvonitter I can't access this spec. Could I get the permission to access it via my email?

**Comment by thenadj** [comment]
@daoshengmu I just added you to the Trello board. Look for an invite in your inbox.

**Comment by MortimerGoro** [comment]
@thenadj I found two errors in the spec. I checked both iOS/Android system keyboards and the Korean Jamo tables to confirm the final values. Here is an image with the correct keys marked:

![Screenshot_20190611-121718](https://user-images.githubusercontent.com/1070794/59265564-e5f23a80-8c45-11e9-9e4a-3bc399d104c9.png)

**Comment by MortimerGoro** [comment]
@thenadj Also found that iOS/Mac represents the marked bottom key in a different way: 
![IMG_1913](https://user-images.githubusercontent.com/1070794/59266171-52216e00-8c47-11e9-8838-7f97d51e1583.PNG)

But they seem to be the same. If I email or copy paste the key from iOS to Android both representations are different but it's the same key for jamo table combinatios or search results.

**Comment by MortimerGoro** [comment]
@Pike There are some differences in the space key. We are using `가기` in Firefox Reality, but if you check space key labels on both images from Android and iOS all of them are different. Could you check with translators that `가기` is the right value? I didn't find a way to attach images in pontoon

**Comment by MortimerGoro** [comment]
@Pike I found that Android keyboard uses "Korean" in the space key. So the difference is between iOS and Firefox Reality, which both use "SPACE" translated to each language

**Comment by MortimerGoro** [comment]
@Pike other difference is the label for the enter key using the "Go" action, `keyboard_go_label`stringx.xml entry. Firefox Reality uses `가기` but iOS keyboard is using another string (check the text of the blue button next to the `.`)

**Comment by Pike** [comment]
Forwarding this to our PM @Delphine here.

**Comment by Delphine** [comment]
I'll get in touch with localizers and circle back here, thanks

**Comment by Delphine** [comment]
@cs09g, @hyeonseok: Could you please advise on this issue? thank you!

**Comment by cs09g** [comment]
The different look is caused by font.
![image](https://user-images.githubusercontent.com/7428017/59404082-2eddf680-8de0-11e9-87ec-5d3628884557.png)

for "SPACE", "간격" would be better than "공백".
for "Go", "이동" would be better than "가기".
