### ISSUE TITLE
Consolidate language settings

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#1242]
We have a bunch of language-related settings:

- System language - this determines the language we show for menus, buttons, etc. This is set by the device and we can't change it.
- HTTP accept-language settings - determines the order in which we'll try to display webpages (See #794 )
- Voice-search language - determines the language the user wants to speak to do voice-search
- Keyboard input language. The "globe" button on the keyboard that changes the keys to different languages
- Speech permissions - allowing users to opt-in and out of voice data collection (See #641)

Consider how and where users set these and decide if anything should move/change to be more streamlined.

**Comment by jvonitter** [comment]
needed by #1243

**Comment by jvonitter** [comment]
fixed by  #1372
