### ISSUE TITLE
Remove User-Agent overrides for Delight-VR hosts

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1247]
## Hardware
Oculus Go

## Steps to Reproduce
1. Build FxR locally with the User-Agent Override list cleared of all the non-YouTube origins.
2. Launch https://delight-vr.com/video-player-module/#dl8--8566450414 and https://delight-vr.com/documentation/getting-started/#embed
2. Notice the **START** button plays as expected with FxR's default `User-Agent` (`Mozilla/5.0 (Android 7.1.1; Mobile VR; rv:68.0) Gecko/68.0 Firefox/68.0`)! 🎉😃 

## Context
As of five hours ago, [Delight-VR rolled out a new version](https://delight-vr.com/video-player-module/#dl8--8566450414) to support the upcoming Oculus Quest release. Based on our email correspondence, they prioritised fixing FxR, and the fix has rolled out into production on the CDN-served Delight-VR player, so this fix is propagated to all the sites using Delight-VR. I tested a handful of sites, and they all worked properly without our custom UA override.

This allows us to remove the UA strings (the appended ` BlackBerry` to trick Delight-VR's device detection that was detecting FxR as an `UnknownTablet`). We appended ` BlackBerry` to the default FxR UA in PR #1216 (and, in an earlier attempt, via a content script in PR #1213) and updated more origins in PR #1245.

**Comment by philip-lamb** [comment]
Fixed by #1248
