### ISSUE TITLE
minor changes to Pinyin keyboard

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1253]
Minor updates based on feedback. Latest spec is here:
https://trello.com/c/GeLVSIig/119-uis-27-chinese-keyboard-pinyin

Waiting for one more piece of feedback and then we'll be at final design.

**Comment by thenadj** [comment]
Attached is the updated UIS for the Pinyin keyboard. It is now ready to be implemented.
[UIS-27 Chinese Keyboard (Pinyin)_005.pdf](https://github.com/MozillaReality/FirefoxReality/files/3210086/UIS-27.Chinese.Keyboard.Pinyin._005.pdf)
