### ISSUE TITLE
Show history and bookmarks in awesomebar results

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1257]
needs #1141

**Comment by jvonitter** [comment]
When a user begins to enter text into the awesomebar, the search results below should include sites that are in the user's history and bookmarks. 
The sites should have a visual indication of whether they are history, bookmark or regular search results.

For reference, desktop Firefox shows this:
![showing history and bookmarks in the awesomebar](https://user-images.githubusercontent.com/48839872/58288081-73d5b680-7d67-11e9-8f72-92c85b4e489d.png)

**Comment by jvonitter** [comment]
Spec is ready: https://trello.com/c/vZoboQMn/360-uis-75-history-bookmarks-in-awesomebar

**Comment by keianhzo** [comment]
@thenadj I can't find the icons in the spec, can you add the to the Trello card above?

**Comment by thenadj** [comment]
We're using the same icon as for the tray. Use this one: 
[icon-tray-history.svg.zip](https://github.com/MozillaReality/FirefoxReality/files/3398527/icon-tray-history.svg.zip)

**Comment by keianhzo** [comment]
@jvonitter @thenadj You can review the new awesome bar spec here that includes support for showing and filtering bookmark and history entries in the awesome bar:
https://send.firefox.com/download/9a58bce1a376fd73/#ZZSzGHI_kuZlWKcfKufDug

**Comment by thenadj** [comment]
Looks good, thank you!
