### ISSUE TITLE
Reported crashes opening the settings screen on Go?

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#1267]
## Hardware
Oculus Go

## Steps to Reproduce
1. Attempt to open settings screen

## Current Behavior
Crashing for some users.

## Context
At least one report and 3 upvotes in the store reviews on this issue:

<img width="1026" alt="Screen Shot 2019-05-25 at 7 38 05 AM" src="https://user-images.githubusercontent.com/475847/58369460-320c5380-7ec0-11e9-8de1-56fca16ee9ec.png">

**Comment by bluemarvin** [comment]
Could be related to https://github.com/MozillaReality/FirefoxReality/issues/1142 which seemed to go away for me so maybe it is intermittent. Probably reported on go since we have the most users there.

**Comment by bluemarvin** [comment]
I don’t see any relevant stacks on crash-stats so either they didn’t submit the crash report or our crash reporting still isn’t working correctly.

**Comment by larsbergstrom** [comment]
Yeah, we don't have any new crashes in the Google store (and still quite a few users!) and that tends to be pretty good at catching our crashes even when our internal reporting is not doing well.

**Comment by MortimerGoro** [comment]
It seems that #1142 was fixed in https://github.com/MozillaReality/FirefoxReality/commit/14c81cf29dbd86e5b64882281866ea8111b77e58 (at least testing on the Android 9 emulator)

@larsbergstrom  Is it possible to know if the crash mentioned is from v1.1.4? #1142  should be fixed in v1.2?

**Comment by bluemarvin** [comment]
I don't think 1.1.4 was ever released to the oculus store?

**Comment by bluemarvin** [comment]
Does the oculus store allow us to ask questions in the reviews. I think we need more information at this point.

**Comment by bluemarvin** [comment]
#1282 was preventing us from see Java crashes. We might want to chem spill this.

**Comment by larsbergstrom** [comment]
I would not be against doing a quick update to pick up this fix!

I'm fine with replying/responding, but AFAIK the reporter does not get a notification about it, and I've never gotten a followup when I've requested more info in the past from people, sadly.

Were you able to find crashes in the settings dialog when you dug through the crash-stats, assuming that you were able to filter them out? Or do you need the chem spill to get the reported crashes landing someplace we can see them at all?

**Comment by bluemarvin** [comment]
@MortimerGoro triaged some of them but there are over 70 pages of individual crashes which was the only way I could find to list all current FxR crashes. I don't know if he was able to find one related to the preference menu. I definitely think we should spin up a new release with crash reporter fixes and the fixes for the top crashers if applicable.

**Comment by philip-lamb** [comment]
@jvonitter and I discussed and have resolved to close this in favour of tracking individual crashes that have STR. Related: #810.
