### ISSUE TITLE
Implement about:crashes

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1268]
**Is your feature request related to a problem? Please describe.**
User has no way to know what crashes have been submitted or any way of sharing it. 

**Describe the solution you'd like**
`about:crashes` should give the user a list of reported crashes. The page should give a list of links to the crashes submitted. It would be nice if the user could submit a GitHub issue right from the page. An additional feature I would like to see is a list of unsubitted crashes and the option to submit them. 

**Additional context**
Desktop and fennec both have `about:crashes` pages.

**Comment by jvonitter** [comment]
I'd call this nice to have, but not urgent. Popping it into 1.x but we can pull it in opportunistically.

**Comment by bluemarvin** [comment]
I sort of disagree. One pain point is getting crash information from other people. Right now if some one submits a crash report, unless they are watch the logcat at the time they submit the crash report, there is no way to get a direct link to the crash report other than going to crash-stats and guessing which report is theirs. By saving the link, they can later go to `about:crashes` and find the link.

**Comment by bluemarvin** [comment]
To get a basic `about:crashes` that only shows a page of links of all submitted crashes is about a days worth of work. Being able to open a github issue from a specific crash on the page would probably be about a weeks worth of work. Being able to save crashes if not submitted so the user can submit latter would also probably be about a weeks of work.

**Comment by bluemarvin** [comment]
GitHub reset API for creating issues: https://developer.github.com/v3/issues/

**Comment by bluemarvin** [comment]
@emstanley I think we should consider pulling this into v11 or v12.
