### ISSUE TITLE
Running FirefoxReality headless on HoloLens

### ISSUE THREAD

**Issue by HedwigAR** [MozillaReality/FirefoxReality#1269]
**Is your feature request related to a problem? Please describe.**
I am working on a project where I have to render multiple webpages in Unity3D on a HoloLens. Right now the only way to do that is to render Edge WebViews as controls on a 2D UWP app, screenshot those and send them as byte[] to the Unity application. Running a browser and having control over when it renders and getting screenshots quick in UWP would be very helpful to HoloLens developers.

**Describe the solution you'd like**
A way to run the FirefoxReality browser in a UWP application and having control over when it renders and easy access to the renders.

**Comment by bluemarvin** [comment]
FxR only support Android based devices.

**Comment by thetuvix** [comment]
Firefox Reality support for HoloLens 2 is [available now](https://blog.mozvr.com/firefox-reality-hololens/)!
