### ISSUE TITLE
Experiment with 6DOF environments

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#1271]
We can do some experiment with combining a model for the near and a skybox for the far.

We should make some decisions after the experiments:
- Is the combined model & skybox approach enough for our needs?
- Do we need a better format such as GLTF? 
- Can we stick with the current render engine, needs more work or would it be better to integrate an external renderer?
- A list of 6DOF requirements the designers (vertices, baked textures, etc)

**Comment by jvonitter** [comment]
Putting this into 1.3 for now. Still needs estimation and prioritization.

**Comment by philip-lamb** [comment]
Adding Kip.

**Comment by bluemarvin** [comment]
Updating since it is currently on v12 roadmap.
