### ISSUE TITLE
Stop passing WebVR Foveation level into DeviceDelegate 

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#1275]
## Current Behavior

This is a refactor bug and follow up for #1255. We pass WebVR foveated level to DeviceDelegate but we have no solutions to do this in FxR side, we will need to do it in WebGL, so it is unnecessary to pass it to DeviceDelegate.

## Expected Behavior

Remove WebVR foveated level parameter and do it outside of FxR.

```
```

</details>

**Comment by philip-lamb** [comment]
@daoshengmu Please add a size estimate for this item, so we can work out its priority.

**Comment by daoshengmu** [comment]
It will be very quick, just need to remove unused parameters. I will do it this week.
