### ISSUE TITLE
Wrong text of enter button on Zhuyin keyboard

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#1276]
## Hardware

I saw it on Oculus Go and believe Vive Focus also shows the same result.

## Steps to Reproduce

1. Switch to Zhuyin keyboard and take a look at the enter button.

## Current Behavior

It shows `衝!` instead of `前往` like what we did in Pinyin keyboard. I think they should be no difference.

## Expected Behavior

It should show `前往`

## Context

When I saw `衝!`, that is a little funny to me, it means _sprint and unstop_ in Chinese meaning, we seem using a wrong translation.

```
```

</details>

**Comment by daoshengmu** [comment]
![org mozilla vrbrowser-20190528-222720](https://user-images.githubusercontent.com/1263177/58532447-6fabfd80-819a-11e9-8aee-7deeb255fff1.jpg)

**Comment by philip-lamb** [comment]
@daoshengmu Can you take a look at https://pontoon.mozilla.org/zh-TW/android-l10n/MozillaReality/FirefoxReality/app/src/main/res/values/strings.xml/?string=198962 and make a translation suggestion if you think it can be improved? This is the text used when the enter key takes an action of taking the user to an entered location.

**Comment by daoshengmu** [comment]
I have made a suggestion to choose the same text as zh-CN, https://pontoon.mozilla.org/zh-CN/android-l10n/MozillaReality/FirefoxReality/app/src/main/res/values/strings.xml/?string=198962.

**Comment by philip-lamb** [comment]
@Delphine If an improved translation has been suggested, does it need approval in Pontoon to replace the existing one? See https://pontoon.mozilla.org/zh-TW/android-l10n/MozillaReality/FirefoxReality/app/src/main/res/values/strings.xml/?string=198962

**Comment by Delphine** [comment]
Hi Phil! Yes, it does. Can you give me some more background if this needs approval? thanks

**Comment by philip-lamb** [comment]
fixed in #1293
