### ISSUE TITLE
Java crash reporter broken

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1281]
## Hardware

All
## Steps to Reproduce

1. Cause a java crash in FxR

## Current Behavior

App doesn't restart.

## Expected Behavior

App should restart and present a crash dialog so that the report may be submitted.

## Possible Solution

Fix the infinite-restart code so that it doens't block restarts after normal crashes.

**Comment by philip-lamb** [comment]
Fixed in #1280
