### ISSUE TITLE
Java crash reports contain the wrong version and build id

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1282]
## Hardware

All
## Steps to Reproduce

1. Cause a java crash
2. Report crash

## Current Behavior

Crash does not show up in FirefoxReality crash reports on crash-stats.

## Expected Behavior

Java crashes should be visible on crash stats.

## Possible Solution

Ensure the crash reports have the correct version and build id.

## Context

Crash stats finds FxR crashes using both the app name and the geckoview version. Java crashes were using the FxR version instead and thus were not showing up with the native crashes.

**Comment by philip-lamb** [comment]
Fixed in #1280
