### ISSUE TITLE
move Bookmarks from in-window to a panel

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1288]
needed by #635 
To enable multiple windows and as a start to enabling a broader "library" concept in FxR, we need a place outside of the content window for links to bookmarks. 

This task covers moving bookmarks display from the content window into a panel next to the content window. It also covers the behavior of the panel in relation to the window(s) including opening, closing and repositioning.

Final visual design is TBD and will be in a separate ticket.

**Comment by thenadj** [comment]
@jvonitter Looks like we're not going to move forward with this feature... at least for now. Do you want to close this issue?

**Comment by jvonitter** [comment]
Decided not to do this after all
