### ISSUE TITLE
[HTC#1112] Controller beam direction not the same as Launcher

### ISSUE THREAD

**Issue by kaipinglee** [MozillaReality/FirefoxReality#1291]
## Hardware
Vive Focus Plus

## Steps to Reproduce

1. Pairing the 2 controllers then open firefox ap
2. Controller flat on the desktop, and observe the controller beam direction 
3. Pressing on Home button to invoke Quick Menu, compare the direction displayed by the controller
4. Return to home launcher, compare the controller beam direction again within firefox ap

Timestamp:
5/30 12:28

![1112-1](https://user-images.githubusercontent.com/31957856/58782136-5084f400-8610-11e9-9eb1-545014d7f028.png)
![1112-2png](https://user-images.githubusercontent.com/31957856/58782139-511d8a80-8610-11e9-9ee0-fa7568848caf.png)
![1112-3](https://user-images.githubusercontent.com/31957856/58782141-511d8a80-8610-11e9-8322-aa65d9fbb1ed.png)

## Current Behavior

Controller beam direction not the same as Launcher.

## Expected Behavior

Controller beam direction the same as Launcher.

## Error Logs and Stack Traces

<details open>
[https://drive.google.com/open?id=18JVDjoAGr5gIKFKtuI0ngrN2lGU6Op9o](url)
[https://drive.google.com/open?id=1YSI5frw-17se9Ltk4UqKlyQ-eNK3yS0A](url)

```
```

</details>

**Comment by bluemarvin** [comment]
I don't believe there is an API in the native APK that defines the beam direction.

**Comment by daoshengmu** [comment]
> I don't believe there is an API in the native APK that defines the beam direction.

@bluemarvin 
I was thinking if the beam we attached should adjust its initial orientation a little bit to match their beams.

**Comment by bluemarvin** [comment]
@daoshengmu I thought about it, but would have to guess the values at this point. If they want the beam direction to be uniform, there really needs to be an API to get offset and orientation. Also an API to get access to the controller model would also be nice. Since it seems each device contains a model for its unique controller, there just doesn't seem to be a native API to get a path to it.

**Comment by philip-lamb** [comment]
I'll see if we can get the values used on the Unity or Unreal SDKs. I'll also log a feature request with HTC.

**Comment by bluemarvin** [comment]
I've found an orientation and offset that seem to match the platform pretty close: 
```
    if (aController.is6DoF) {
      transform = vrb::Matrix::Rotation(vrb::Vector(1.0f, 0.0f, 0.0f), -vrb::PI_FLOAT / 5.0f);
      transform.TranslateInPlace(vrb::Vector(0.0f, -0.03f, -0.05f));
    }
```

**Comment by bluemarvin** [comment]
I asked about it here: https://community.viveport.com/t5/Vive-Wave-SDK/Accessing-device-specific-controller-models-and-data-from-native/m-p/31403#M2056
