### ISSUE TITLE
FirefoxReality Crash Report [@ java.lang.IllegalStateException: at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java) ]

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#1295]
https://crash-stats.mozilla.com/signature/?product=FirefoxReality&signature=java.lang.IllegalStateException%3A%20at%20org.mozilla.geckoview.GeckoSession.acquireDisplay%28GeckoSession.java%29&date=%3E%3D2018-11-30T17%3A43%3A00.000Z&date=%3C2019-05-30T17%3A43%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1

**Comment by philip-lamb** [comment]
Needs steps to reproduce before we can prioritise.

**Comment by philip-lamb** [comment]
8 intances. Two recent instances of this were on Quest (during Quest testing phase). Then a bit of a gap back to older ones which are on Go and sideloaded on two different Samsung phones.
