### ISSUE TITLE
[HTC#1104] In Firefox AP, one controller disappear but connected sine have response when pressing on Home button to invoke Quick Menu

### ISSUE THREAD

**Issue by kaipinglee** [MozillaReality/FirefoxReality#1297]
## Hardware

Vive Focus Plus
## Steps to Reproduce

when resuming the MI6 in Firefox AP, one controller disappear but connected sine have response when pressing on Home button to invoke Quick Menu (twice)(exit firefox AP or suspend/resume to recover)

Timestamp:
5/29 19:43 & 19:45

![1104 screen](https://user-images.githubusercontent.com/31957856/58945009-916a3d80-87b5-11e9-8124-064bcc89c881.png)

## Error Logs and Stack Traces

<details open>

https://drive.google.com/open?id=1IM0xN0az-8V-WgIKm2YTCTfaYiaXHbEh
https://drive.google.com/open?id=10Bp9HX3txpALCQbCqcQ5Nq1XPFGgZ8pH

```
```

</details>

**Comment by bluemarvin** [comment]
This screen shot is showing a bug in the system not FxR. The system renders the controllers when the mini-menu is shown.

**Comment by philip-lamb** [comment]
If I interpret this correctly, "resume" implies re-activating the headset after removal during a browsing session. I'll have a go at reproducing.

**Comment by bluemarvin** [comment]
I can reproduce the controller disappearing, but it only disappears for the mini menu, which we do not render. I'm pretty sure this is a system bug and not an FxR issue. I can take the head set off, wait for a bit and then put it back on and we get both controllers.

**Comment by philip-lamb** [comment]
I was able to reproduce this issue in a completely different application (Vive Browser). Closing as not our bug.
