### ISSUE TITLE
[HTC#1108] When swinging the head left and right in firefox, can see black frame and display a little lag on lens boundary.(firefox streaming video by WITHIN homepage)

### ISSUE THREAD

**Issue by kaipinglee** [MozillaReality/FirefoxReality#1298]
## Hardware

Vive Focus Plus
## Steps to Reproduce

When swinging the head left and right in Firefox, can see the black frame and display a little lag on lens boundary
(firefox>select BATMERSIVE streaming video to play>press ENTER VR UI button>then select back to menu)(https://vr.with.in/)

Timestamp:
5/29 11:30-11:32

## Error Logs and Stack Traces

<details open>

https://drive.google.com/open?id=1gco6S6MdixhV-xlpmJIvoqTz4rXGUlCf
https://drive.google.com/open?id=1y2ETroIu7w2Gi36fgB0-5CCkM7sslt1w

```
```

</details>

**Comment by philip-lamb** [comment]
This is a performance issue which is blocked on two things; 64-bit javascript engine performance improvements (which will likely land in 1.4) which also requires 64-bit WaveVR SDK support, and an asynchronous timewarp pose feedforward mechanism in WaveVR, as currently exists on Oculus VR platform.
