### ISSUE TITLE
[HTC#1113] When select Vimeo streaming video to play, the content will show black but it’s OK when playing in full screen

### ISSUE THREAD

**Issue by kaipinglee** [MozillaReality/FirefoxReality#1299]
## Hardware

Vive Focus Plus
## Steps to Reproduce

1. Open Firefox AP and select "Viome 360 Shorts" category streaming video
2. Play the video and by default screen size.

Symptom:
When select Vimeo streaming video to play, the content will show a black but it’s OK when playing in full screen

Timestamp:
5/30 12:30

![Issue#1113_screen2](https://user-images.githubusercontent.com/31957856/58946603-dc398480-87b8-11e9-9bd9-795235ca10f6.png)
![Issue#1113_screen](https://user-images.githubusercontent.com/31957856/58946604-dc398480-87b8-11e9-9073-c86de435c899.png)

## Error Logs and Stack Traces

<details open>

https://drive.google.com/open?id=1fNpKZCCYZOJql7OniLLU1620Jjbj0hTL
https://drive.google.com/open?id=1QG0OAH7LPXVq4JNZPuACNhSsgVUiDbep

```
```

</details>

**Comment by Softvision-GeluHaiduc** [comment]
I will remove the QA label for now as there is nothing actionable by QA.
If QA attention is needed in the future please add the label again and we will address it.
