### ISSUE TITLE
Investigate if `VRAPI_ACTIVE_INPUT_DEVICE_ID`can be used to ensure the correct controller has focus at application start on Oculus Quest

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1302]
**Is your feature request related to a problem? Please describe.**
We have to guess which controller has focus when FxR launches on Quest. Evaluate if `VRAPI_ACTIVE_INPUT_DEVICE_ID` may be used to detect which controller has focus at launch.
 My initial tests didn't have the results I expected. Need to reevaluate to see if I was holding it wrong.

**Comment by bluemarvin** [comment]
Probably less than a days worth of work.

**Comment by philip-lamb** [comment]
Awesome, feel free to adjust the size labelling as required.

**Comment by daoshengmu** [comment]
IIRC, last time I tried `VRAPI_ACTIVE_INPUT_DEVICE_ID ` that didn't work as my expectation. I will look forward if they have a new update on it.

**Comment by bluemarvin** [comment]
Now that both controllers are active in the Oculus Home environment I'm not sure there is much value in pursuing this.

**Comment by daoshengmu** [comment]
I would look forward to seeing FxR start to use two controllers interaction as Oculus Home.
