### ISSUE TITLE
Removing VR screen buffer in Gecko

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#1309]
## Current Behavior

We currently ask for an additional buffer to get the AndroidSurfaceTexture from WebGL context. It looks like the gl->Screen() is already been copied the frame result from WebGL framebuffer. We should just use it.

## Expected Behavior

Remove VR screen buffer, just us gl->Screen(). I have filed [Bug 1558333](https://bugzilla.mozilla.org/show_bug.cgi?id=1558333) to work on.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by philip-lamb** [comment]
@daoshengmu Let's chat about the relationship between this bug and the work tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1537961

**Comment by daoshengmu** [comment]
> @daoshengmu Let's chat about the relationship between this bug and the work tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1537961

According to the review comment at https://phabricator.services.mozilla.com/D34435. It still has some concerns about deadlocks (WebVR using the same texture at the same time of compositor). Therefore, I think we can close this issue, and the following works will be #1429.

**Comment by jvonitter** [comment]
thanks @daoshengmu !
