### ISSUE TITLE
[meta] multi-window

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1319]
needs #1318 , #1320 , #1322 , #1323, #1324 , #1325 , #1326 , #1327 , #1328 , #1329 , #1330 , #1331

**Comment by keianhzo** [comment]
@thenadj @jvonitter Latest multi-window build: https://send.firefox.com/download/65b9b2c6b9dd5c37/#OUYWDuGzLNmAXQ1BdTSIhw

**Comment by keianhzo** [comment]
@jvonitter @thenadj Latest multiwindow https://send.firefox.com/download/fd9adae027bbdb95/#UEV9TI-e9s5evux_H8xQgQ

**Comment by keianhzo** [comment]
@jvonitter @thenadj Latest multi-window including new Setting/UA specs
https://send.firefox.com/download/fbd2e0fad343430f/#oFyn69r7x6M0jyM-F52sbg

**Comment by keianhzo** [comment]
Closed by #1467

**Comment by jvonitter** [comment]
needs #1525 needs #1521 needs #1518 needs #1469 needs #1373 needs #1571 needs #519
