### ISSUE TITLE
Add support for external keyboard (bluetooth)

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/FirefoxReality#1321]
I have been playing around with connecting a bluetooth keyboard to the quest/go and I go it working without problems with most of the apps, including Oculus Browser, so I could easily type urls, write emails and even code a bit on glitch.
But it doesn't seem to work at all on Firefox Reality.
I believe it would be great if we could add support for it so we could improve the input options when dealing with bigger texts.

**Comment by philip-lamb** [comment]
Duplicate of #775
