### ISSUE TITLE
Make and place long-press context button

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1322]
When a link appears within a webpage, the user can long-press the link to invoke a button that says “Open in New Window”.

The button appears slightly above and to the right of where the user long-pressed. (See UIS-71 300 special cases for when the button would not fit.)

[Window positioning spec](
https://trello.com/c/McQtjuOB/344-uis-71-open-link-in-new-window)

Needed by #1319. Related to #1318

**Comment by keianhzo** [comment]
Closed by #1467
