### ISSUE TITLE
Make and place new window

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1323]
Needed for #1319 

- Open a new (empty) window by clicking the “+” button on the tray or by long-pressing on a link See UIS-70 500-800. Relates to #1318 and #1322
- Generally, new windows open to the right of the current window. (UIS-70 625 and 725 for all positioning cases)

[Multi-window spec](
https://trello.com/c/78zHL5U4/343-uis-70-window-positioning-3-windows)
[Window positioning spec](
https://trello.com/c/McQtjuOB/344-uis-71-open-link-in-new-window)

**Comment by keianhzo** [comment]
Closed by #1467
