### ISSUE TITLE
make and place "too many windows" dialog

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1324]
If three windows are already opened, the user can still click the + button in the tray or the context menu button. In this case, a new window is not created, but instead a dialog appears with error text. (UIS-70 800)

needed by #1319 

[Multi-window spec](
https://trello.com/c/78zHL5U4/343-uis-70-window-positioning-3-windows)
[Window positioning spec](
https://trello.com/c/McQtjuOB/344-uis-71-open-link-in-new-window)

**Comment by keianhzo** [comment]
Closed by #1467
