### ISSUE TITLE
Window activation states

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1326]
- A window may be active or inactive. Only one window may be active at a time and there must always be one inactive window. 
- When another window is activated (by clicking anywhere in the window) all others are inactive.
- When a window is active, window controls for close, move left and move right (UIS-70 100) appear above the window and the URL bar/buttons appear below it. 
- When a window is inactive, window controls are not displayed for that window. 

Consider whether GeckoView changes are needed.

[Multi-window spec](
https://trello.com/c/78zHL5U4/343-uis-70-window-positioning-3-windows)

Needed by #1319

**Comment by keianhzo** [comment]
Closed by #1467
