### ISSUE TITLE
Make windows move and close

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1328]
- Hook up the move and close window controls (Relates to #1327) so that windows behave according to spec  (UIS-70 600 and 700)
- Use basic transitions - no fancy animations 
- Investigate what happens when curved window setting is turned on.

[Multi-window spec](
https://trello.com/c/78zHL5U4/343-uis-70-window-positioning-3-windows)

Needed by #1319

**Comment by keianhzo** [comment]
Closed by #1467
