### ISSUE TITLE
Telemetry for multi-window 

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1329]
- How many too-many-window dialogs happen / what percentage
- Long press discovery
- +tray button use
- How long is a window open for / window life
- Frequency of window moves
- Frequency of window resizes (and most common size if we can)
- Curved windows setting - how many users use it / what percentage
- When a session is multi-window, what percentage of time is each position the active window
- Average of how many windows are open at a time, per session

Needed by #1319

**Comment by thenadj** [comment]
@jvonitter Can we add three more?

+ What position is most often used for active window (left, middle, right)
+ Resizing: What window sizes are used? How often?
+ How many windows are open at a time?

**Comment by jvonitter** [comment]
@thenadj Yeah, we can add those. I'll update the ticket above

**Comment by keianhzo** [comment]
@jvonitter do we have a final list of events that we want to add to multiwindow?

**Comment by jvonitter** [comment]
updated the description to be a bit clearer

**Comment by jvonitter** [comment]
I've reached out to the data steward for ET to review this data collection. Stay tuned!

**Comment by keianhzo** [comment]
Closed by #1467

**Comment by jvonitter** [comment]
Data review form, attn Janice Tsai - 
[datareview-multiwindow.txt](https://github.com/MozillaReality/FirefoxReality/files/3518546/datareview-multiwindow.txt)

Wiki update in progress

**Comment by jvonitter** [comment]
https://github.com/MozillaReality/FirefoxReality/wiki/Telemetry has been updated with the info here. closing this!
