### ISSUE TITLE
Private browsing page not loading 

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#1335]
## Hardware
All

## Steps to Reproduce
1. Open FxR
2. Click on the Private Browsing button

## Current Behavior
No page is loaded and no error is shown

## Expected Behavior
The private browsing page should be loaded

## Possible Solution
Related to this GV issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1556540

## Error Logs and Stack Traces

<details open>

```
2019-06-14 21:31:20.678 14590-14615/org.mozilla.vrbrowser W/GeckoConsole: [JavaScript Warning: “Navigation to toplevel data: URI not allowed (Blocked loading of: “data:text/html;base64,PCFET0NUWVBFIGh0bWw+CjwhLS0g...“)”]
```

</details>

**Comment by philip-lamb** [comment]
I gather that private browsing still functions and it's just the message that doesn't display, but can we verify this?

**Comment by bluemarvin** [comment]
We did. It’s just the info page that fails to load. Has nothing to do with private browsing functionality.

**Comment by philip-lamb** [comment]
https://phabricator.services.mozilla.com/D37343
