### ISSUE TITLE
Check entitlement on Oculus Quest

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#1344]
## Hardware
Oculus Quest

## Steps to Reproduce

>_Oculus guidelines:_
>The app must perform an Oculus Platform entitlement check within 10 seconds of launch.
>
>On your device, ensure developer mode is enabled and log in to Oculus Home with a user who doesn’t have an entitlement to the app (either via release channel, keys, or store purchase).
>In a terminal window, install the app with the command adb install path-to-apk.
>Launch the app from the Oculus Home library.

## Current Behavior
App runs as normal

## Expected Behavior
>_Oculus guidelines:_
> App should either exit, display an error message, or go into a limited demo mode.

## Possible Solution
Need to perform entitlement check on Quest Store version.

We need to consider the behaviour here, since we want to support sideloading in general. Perhaps produce a binary specifically for Quest Store, and another for Oculus 6dof (non-store)?

## Context
https://developer.oculus.com/distribute/latest/concepts/vrc-quest-security-1/
https://developer.oculus.com/documentation/platform/latest/concepts/pgsg-native-gsg/#initialize-the-sdk-and-perform-the-entitlement-check

**Comment by keianhzo** [comment]
@philip-lamb shouldn't this one be closed by #1349?

**Comment by philip-lamb** [comment]
Indeed it should, although #1349 didn't reference this bug (e.g. with a "fixes" keyword) so it had to be done manually.
