### ISSUE TITLE
Don't request camera permissions (either in manifest or in-app) on Oculus VR.

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#1345]
## Hardware
Oculus Quest
Oculus Go

## Current Behavior
* Current `app/src/main/AndroidManifest.xml` includes: `<uses-permission android:name="android.permission.CAMERA" />` and this shows on launch on Quest:
![OFR-16](https://user-images.githubusercontent.com/5752887/60238863-f706a100-98ff-11e9-8ce7-6e6772eea3bd.jpg)
* Security and privacy pane includes prompts to allow camera permissions.
* Web pages requesting camera access are not currently automatically denied access on Oculus Go and Quest platforms.

## Expected Behavior
From Quest guidelines:
> "[VRC.Quest.Security.2] The app must request the minimum number of permissions required to function." 

## Possible Solution
On Oculus builds, remove camera permission from manifest, from security prefs, and deny webpages access to camera automatically.

## Context
https://developer.oculus.com/distribute/latest/concepts/vrc-quest-security-2/

**Comment by assadollahi** [comment]
wouldn't it be cooler to actully support the access to a camera? like in here: https://glitch.com/~webcam-as-aframe-texture
