### ISSUE TITLE
Blocked permission requests makes the app flicker

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#1350]
## Hardware
All

## Steps to Reproduce
1. Fresh install
2. open https://simpl.info/getusermedia/sources/
3. Deny the RECORD_AUDIO permission
4. Reload the page
5. Deny the RECORD_AUDIO permission and check "Don't ask again"
6. Reload the page

## Current Behavior
Even though the system's permission request dialog is not shown the app flickers.

## Expected Behavior
The app shouldn't flicker as from the user's perspective nothing should be happening.

## Possible Solution
There is no easy solution for this as Android doesn't offer an API for knowing if the permission is blocked before requesting it. You can know it after requesting it so we could try to keep track of the blocked permissions to not request them in the future but in case the user resets the permissions there is no way we can remove that permission from our black list.

## Context
It affects users that have denied forever (blocked) any permission (but the CAMERA on Oculus as it's already blacklisted by default) the next time any website requests that permission again.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
I'm not sure this is something we can fix and is probably okay to live with. What does the Oculus Browser do? Does it come with the permissions already enabled?

**Comment by bluemarvin** [comment]
I checked the Oculus Browser on both Go and Quest and it seems they cache the result so that if a user changes the permission from out side of the app, they don't know. I think our behavior is better in that we check each time. It seems to only really be an issue on the Go where the permission check takes long enough to be visible.
