### ISSUE TITLE
Telemetry fails to upload

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1353]
## Hardware

All
## Steps to Reproduce

1. Visit Mozilla telemetry

## Current Behavior

Notice drop off in stats.
## Expected Behavior

Telemetry should continue to be uploaded.

## Possible Solution

Update the android-component telemetry service to use an alternative method for uploading telemetry.

## Context

PR https://github.com/MozillaReality/FirefoxReality/pull/1085 broke telemetry when we removed the android permission `RECEIVE_BOOT_COMPLETED`. The service was using this permission to upload telemetry. With this permission removed, we need to find an alternative solution that is permissible in the Oculus store for uploading telemetry.

**Comment by daoshengmu** [comment]
@pocmo Per our discussion at https://github.com/MozillaReality/FirefoxReality/pull/1300#issuecomment-505661982, we are asking for assistance to avoid to use `RECEIVE_BOOT_COMPLETED` permission, and our workaround fix at issue #1300 still only be able to upload about 25% data to the telemetry system.

**Comment by jvonitter** [comment]
Can we turn the permission back on for non-Oculus builds?

**Comment by MortimerGoro** [comment]
@jvonitter yes we can do that. The permission removal was only done for Quest, so maybe we can even enable it for Oculus go (we have already separate builds)

**Comment by daoshengmu** [comment]
> Can we turn the permission back on for non-Oculus builds?

That's a good thought. We should roll back it for other platforms except Quest. We also can see if our MAU number in telemetry is really getting back.

**Comment by MortimerGoro** [comment]
@jvonitter @daoshengmu I'll create a PR with the permission enabled again except for Quest

**Comment by pocmo** [comment]
> @pocmo Per our discussion at #1300 (comment), we are asking for assistance to avoid to use RECEIVE_BOOT_COMPLETED permission

So we did see the telemetry drop for *all* builds / devices? From the docs I would expect it to still run the job and retry it. What's weird is that we take care of persisting pings so the next schedule should send all ping that have not uploaded yet. So in the worst case this should make pings come in slower but not lose them.

Some things we could try:

* Calling `Telemetry.scheduleUpload()` early, e.g. on app start. It will schedule a job to pick up all the pings that are still on disk and try to upload them.

* Switch to a WorkManager-based scheduler. We have a PR for that in AC - but I'm not sure how helpful that will be without `RECEIVE_BOOT_COMPLETED`- but we could try. Over all WorkManager is more stable than JobScheduler on its own.

* Implement a custom scheduler that uploads ping from a background service (are those restricted too?) or just a background thread while the app is in the foreground.

**Comment by MortimerGoro** [comment]
> So we did see the telemetry drop for all builds / devices? From the docs I would expect it to still run the job and retry it. What's weird is that we take care of persisting pings so the next schedule should send all ping that have not uploaded yet. So in the worst case this should make pings come in slower but not lose them.

Is it possible that we are missing the users who only open the app once? If they don't open the app again the next schedule won't be triggered again.

> Calling Telemetry.scheduleUpload() early, e.g. on app start. It will schedule a job to pick up all the pings that are still on disk and try to upload them.

 `onStart` or `onResume` should be good places to call that method right? That way it's also called when the app is opened from the background without having killed it

> Implement a custom scheduler that uploads ping from a background service (are those restricted too?) or just a background thread while the app is in the foreground.

Doesn't `TelemetryJobService` take care of this?

**Comment by pocmo** [comment]
> Is it possible that we are missing the users who only open the app once? If they don't open the app again the next schedule won't be triggered again.

I'd still expect those to upload from jobscheduler. But maybe background jobs are somehow limited on those devices?

> onStart or onResume should be good places to call that method right? That way it's also called when the app is opened from the background without having killed it

Yes, onStart sounds like a good candidate. We would call it too often - but that should not be too bad: If there's nothing to upload the job will do nothing and stop.

> Doesn't TelemetryJobService take care of this? I see that right now there is only a call to scheduleUpload() in onStop, do we miss that ping if the activity is killed before the service runs the job or should it be able to finish it?

In theory it does. But it relies on the `JobScheduler` system service which seems to act somewhat weirdly without persisting its job.

**Comment by philip-lamb** [comment]
Partially addressed in #1359

**Comment by philip-lamb** [comment]
Holding open in 1.4 until we can observe recovery of the telemetry pings.

**Comment by MortimerGoro** [comment]
@daoshengmu mentioned that It looks like our telemetry are getting back.

Can we close this one?

**Comment by jvonitter** [comment]
I think so. @larsbergstrom and @philip-lamb are you happy with what we're getting back?

**Comment by larsbergstrom** [comment]
Oculus appears to be reporting correctly. WaveVR platform seems a little low, but I know that it's still rolling out, right?

**Comment by philip-lamb** [comment]
Yes, I vote to close. WaveVR build update was a of a week later to hit devices so I’d expect its lift to take a little longer to show

**Comment by jvonitter** [comment]
done and done!
