### ISSUE TITLE
Full screen transitions in Hubs do not work as expected

### ISSUE THREAD

**Issue by gfodor** [MozillaReality/FirefoxReality#1362]
## Hardware
Oculus Quest

## Steps to Reproduce
- Set your screen size in FxR to 3x
- Go to hubs.mozilla.com and create an enter a room
- When in VR, hit the "magic wand" button in the HUD to open the media browser
- Go through the flow to show the media browser full screen by clicking on Continue
- Notice the content is clipped and the viewport is reset to 1x

## Current Behavior
- When an app calls the fullscreen API, it appears the CSS layout is happening at the user's viewport size (1x-3x) but the actual screen quad is reset to 1x. This results in clipping of the content.

## Expected Behavior
- FxR should *either*
  - Restore the user's screen size properly when entering full screen mode, and apply the proper CSS layout
  - Always set the screen size to 3x in full screen mode (I would suggest this option, since it provides the best analog to "full screen" in an immersive browser, and works nicely this way in Oculus Browser)

## Possible Solution
- When an application requests full screen support, change the size to 3x and fade the background, regardless of the user's non-full screen viewport settings.

## Context
We rely upon this behavior to provide nice, full UX for browsing, etc.

```
```

</details>

**Comment by philip-lamb** [comment]
Moving into 1.3 P3 for @MortimerGoro.

**Comment by bluemarvin** [comment]
@gfodor What version were you running? I'm having trouble reproducing the issue to verify the PR that contains the fix is working.

**Comment by bluemarvin** [comment]
I think I can reproduce the issue with 1.1.4 (current version in the Quest Store). The media browser seems to be offset and partially off screen. Is that what you are seeing?

**Comment by gfodor** [comment]
Yup, that is what I am seeing, and confirm it is 1.1.4. Sorry if it was just me using the wrong version :(

**Comment by bluemarvin** [comment]
No problem, just wanted to make sure I understood the issue. Here is a link to the next Quest release version working it's way through the store approval process (1.2.4):

https://queue.taskcluster.net/v1/task/CO9CavemTqW571F695HlBw/runs/0/artifacts/public/FirefoxReality-1.2.4-31902108-oculusvrStore-arm-release-signed-aligned.apk

You should be able to side load it.

**Comment by jvonitter** [comment]
@gfodor let us know if this is ok to close?

**Comment by gfodor** [comment]
Yup, looks good @jvonitter !

**Comment by gfodor** [comment]
thanks for the quick fix! 🎉
