### ISSUE TITLE
Curved mode switch is broken

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#1366]
## Hardware
All

## Steps to Reproduce

1. Open FxR
2. Open the Settings menu 
3. Go to "Display" Settings
4. Enable "Curved display"
5. Close the settings menu
6. Open the Settings menu
7. Go to "Display" Settings

## Current Behavior

The switch is disabled.

## Expected Behavior

The switch should be enabled.

## Possible Solution

Update the curved display switch according to the current setting state.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by philip-lamb** [comment]
Another curved-mode bug: #1207
