### ISSUE TITLE
No Daydream version in Play Store / Daystream Store for supported device - please update app in Play Store!

### ISSUE THREAD

**Issue by mick3-de** [MozillaReality/FirefoxReality#1368]
## Hardware 
a) Motorola Moto Z (XT1650) Daydream compatible phone
(Android version 8.0.0, Daydream app version 1.20.190204006)
b) Google Daydream VR headset

## Steps to Reproduce
1. Search for "Firefox Reality" in Play Store / Daydream Store

## Current Behavior
1. Search for "Firefox Reality"
2. Get "this app is incompatible with all of your devices" (see attached image)
![incompatible](https://user-images.githubusercontent.com/18657663/60769018-46508c80-a0cb-11e9-845b-ce2e804e0255.png)

3. Can't install the app from Store

## Expected Behavior
1. Search for "Firefox Reality"
2. Get the app description as result
3. Install the app

## Possible Solution

Update the app in Play Store to version 1.2.3 or higher.
## Workaround
Download the APK and install it.

## Context
Google Play Store tells me app is version 1.1.3. and  got updated April 15, 2019 last time.

<details open>

```
```

</details>

**Comment by philip-lamb** [comment]
Thanks for this report. Our 1.3 release will be uploaded to the Play Store soon.

**Comment by mick3-de** [comment]
Sure, in the meantime I may use the downloaded apk version 1.2.3 or already test one of the 1.2.4+ taskcluster builds.
Thanks, M.

**Comment by jvonitter** [comment]
This should be done now. @mick3-de, can you confirm and close?

**Comment by fsiefken** [comment]
Same issue here with the new Play store version Firefox Reality 1.3, 24 juli 2019, 74M
https://play.google.com/store/apps/details?id=org.mozilla.vrbrowser

I use a Samsung S9, Exynos 9810 soc
Android 9

Is it because of the Samsung S9 Exynos chip?
https://en.wikichip.org/wiki/samsung/exynos/9810

The Motorola Moto Z has a Kryo
https://en.wikipedia.org/wiki/Kryo

Is the apk installer doing a check if for example an arm64 build is contained in the apk?

**Comment by mick3-de** [comment]
> This should be done now. @mick3-de, can you confirm and close?

It still says the app is not compatible in Android Google Chrome and it does not appear in the Play Store. Sorry for the late reply.

What's your build target?

Best, M.

**Comment by mick3-de** [comment]
Motorola Moto Z2 Force, another Daydream certified device gets reported as "not compatible" and no app to be seen in Play Store.

Model: XT1789-06
Android version: 9
Daydream app verison: 1.20.190204006

Seems at least some Daydream certified devices do not get Firefox Reality. Do you have any recent download stats from PS? Which smartphone models actually can install it from GPS?

> Same issue here with the new Play store version Firefox Reality 1.3, 24 juli 2019, 74M
> https://play.google.com/store/apps/details?id=org.mozilla.vrbrowser
> 
> I use a Samsung S9, Exynos 9810 soc
> Android 9
> 
> Is it because of the Samsung S9 Exynos chip (there is a snapdragon S9 version)?
> https://en.wikichip.org/wiki/samsung/exynos/9810
> 
> The Motorola Moto Z has a Kryo, a Snapdragon 820
> https://en.wikichip.org/wiki/qualcomm/kryo
> 
> Is the apk installer doing a check if for example an arm64 build is contained in the apk?

**Comment by jvonitter** [comment]
waiting for response from Google store

**Comment by jvonitter** [comment]
Google is discontinuing support of Daydream, so we'll no longer maintain a store entry.
