### ISSUE TITLE
Settings IA and verbiage updates

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1372]
See https://trello.com/c/P52DGGmp/88-uis-16-settings for all changes. 

This ticket covers these items:
- Reorganizing the Privacy and Security category (200) and updating text (300b)
- Reorganizing Language settings (200 and 300a)
- Moving "Autoplay Media" to the Display category (300c)
- Removing user agent control from Display category (and adding it to the awesomebar instead - needs #962 )
- Adding Help category to Settings and removing it from the Tray. Functionality is the same, just in a new location.

fixes #1242, fixes #994 and fixes #752

**Comment by MortimerGoro** [comment]
> Removing user agent control from Display category (and adding it to the awesomebar instead - needs #962 )

@jvonitter I don't think we want to remove that from settings. One idea we talked about a long time ago is that users want to temporarily toggle this only for specific page, and not change the default for all. So the value in settings could be the default one and the one in the URL bar the temporary one

**Comment by keianhzo** [comment]
@thenadj @jvonitter A few questions that arised while implementing this spec:

**Comment by keianhzo** [comment]
@thenadj @jvonitter A few notes regarding the new spec:
- I see a DRM settings in Privacy but DRM is not currentty supported by Gecko so I assume is future thinking (Also the Learn More link is not provided in the spec)
- MSAA used to the a 3 options combo (Disabled/2x/4x) and in the latest spec is a switch. Is that correct? In case it is, what's the default option for enabled 2x or 4x?
- The Language changes are also the ones in "Near Future Thinking Not this Release"? I assume not but I don't see many changes in the languages dialog in the new spec apart from removing the header text.
- Just FYI, until Multiwindow lands (v1.4) the tray is only going to have 3 items as the help button has been movd to settings.

**Comment by thenadj** [comment]
@keianhzo 
Comments inline below:

- I see a DRM settings in Privacy but DRM is not currentty supported by Gecko so I assume is future thinking (Also the Learn More link is not provided in the spec)
--> Ignore DRM for now, it will be in the next release.

- MSAA used to the a 3 options combo (Disabled/2x/4x) and in the latest spec is a switch. Is that correct? In case it is, what's the default option for enabled 2x or 4x?
--> Keep the 3 radio buttons we currently have. The spec still has an old dialog before engineering implemented this feature way back when. Thx for catching this!

- The Language changes are also the ones in "Near Future Thinking Not this Release"? I assume not but I don't see many changes in the languages dialog in the new spec apart from removing the header text.
--> Keep the language dialog the way it is in the current build (1.2). We'll address 'near future thinking' in 1.4. 

- Just FYI, until Multiwindow lands (v1.4) the tray is only going to have 3 items as the help button has been movd to settings.
--> Correct.

**Comment by jenniferhoang** [comment]
@keianhzo Please see attached for updated UIS-16.
[UIS-16_Settings_022.pdf](https://github.com/MozillaReality/FirefoxReality/files/3374360/UIS-16_Settings_022.pdf)

**Comment by thenadj** [comment]
@keianhzo  
Attached is the updated UIS-16. For now we kept MSAA as a switch. 

@bluemarvin 
Let us know if a toggle works or if we'll stick with 3 radio buttons for MSAA.

[UIS-16_Settings_022.pdf](https://github.com/MozillaReality/FirefoxReality/files/3374789/UIS-16_Settings_022.pdf)

**Comment by keianhzo** [comment]
@thenadj @jvonitter Here it is the first version of the latest settings spec. The main thing missing is the new user agent switch in the navigation bar and some minor styles fixes. Let me know anything you see. https://send.firefox.com/download/1cfcfbd4b35ab038/#6GxE3d7DirSP9Au8_ZjOHQ

**Comment by keianhzo** [comment]
BTW that version still has the previos MSAA, I'll update that tomorrow.

**Comment by keianhzo** [comment]
@thenadj where can I find the icon for the user agent mobile/desktop switch in the navigation bar?
![Anotación 2019-07-10 115742](https://user-images.githubusercontent.com/837184/60960231-f14e8980-a309-11e9-9153-2376dad5c494.png)

**Comment by thenadj** [comment]
@keianhzo Please find the icons attached.
[UA icons.zip](https://github.com/MozillaReality/FirefoxReality/files/3379704/UA.icons.zip)

**Comment by keianhzo** [comment]
@thenadj @jvonitter I have added the UA switch. It currently changes the UA for the current Gecko Session. The settings switch updates the navigation bar one but the navigationbar switch doens't alter the settings one. I haven't added the tooltip as there is a task for adding tooltips to all the UI elements and adding it just to this one now will make the UI inconsistent. 

I haven't changed the MSAA settings until @bluemarvin confirms if we need the switch or a radio button.

@thenadj Maybe it's just me but I find the icons confusing, without the tooltip I don't really know wether I'm on desktop or VR mode. 

https://send.firefox.com/download/60a444da947c60e1/#yjuC6PzS_kAw5gqd_6WEPQ

**Comment by jvonitter** [comment]
thanks @keianhzo! can we move the UA apk/conversation over to https://github.com/MozillaReality/FirefoxReality/issues/962 ?

@thenadj give that apk a test and let us know what you think.

**Comment by thenadj** [comment]
@keianhzo It is confusing without the tooltips. Let's use these icons instead. 

[icons.zip](https://github.com/MozillaReality/FirefoxReality/files/3384455/icons.zip)

**Comment by keianhzo** [comment]
@thenadj @jvonitter Build update with the latest icons: https://send.firefox.com/download/1d55f5368b7dd951/#6QfZo-unOvH4lmkfO6ppQQ
