### ISSUE TITLE
Quest Frame rate within with.in.

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#1387]
_Reproduced from Oculus QA report_

## Hardware
Oculus Quest
Firefox Reality 1.2.4.

## Steps to Reproduce
1. Launch the title to homepage
2. Select Lego Batman experience.
3. Click Play. 

## Current Behavior
Result (10/10):
Consistent FPS drops is observed after clicking Play on Lego Batman experience, (averaging 63 FPS, lowest value being 59). Heavy judder is observed during the consistent FPS drops. 

## Expected Behavior
The FPS remains smooth throughout title. 

## Context
Notes:
1. Please see attachment for reference.
2. Please note that the issue also occurs for Crow: the Legend experience.
3. The issue is more noticeable in the HMD.
4. It should be re-emphasized that this FPS drop occurs outside the "WITHIN" experience.
5. This issue was entered according to the Oculus Quest Guidelines under the Performance subsection, which states:
"[VRC.Quest.Performance.1] The app displays graphics in the headset at 72 frames per second." 

## Error Logs and Stack Traces
https://drive.google.com/file/d/1XCf-wUUv-tMYi4zp8pjrKYgrCBkj6QrQ/view?usp=sharing

https://jira.babelmedia.com/projects/OFR/issues/OFR-20
see also https://jira.babelmedia.com/projects/OFR/issues/OFR-6?filter=allissues

**Comment by philip-lamb** [comment]
Tracking issue, closing to reflect status of source.

**Comment by philip-lamb** [comment]
Better STR from Oculus QA:

> Steps to Reproduce:
> 1.       Launch title.
> 2.       Select “Lego Batman Video” or “Crow: The Legend” or any other 360* video.
> 3.       Select Play.
> 4.       Upon seeing the Window, select Oculus Home and then resume the app.
 > 
> Upon attempting to view the surrounding area of the Mozilla App – the user will experience some time-warps, graphical tearing and FPS drops. This issue can also be reproduced via selecting “WITHIN” however upon further investigation was determined that the user will not need to go inside the “WITHIN” experience. The issue appears to be less frequently when selecting YouTube videos or other available content.
 > 
> This issue was reproduced on 3 separate PVT model HMDs all running the latest version of the OS 256550.6170.5 (DK15). And the severity of the issue was pretty much identical, with all HMDs being near to full battery life & identical scenarios where recording wasn’t active nor OVR metrics not being active/present.

**Comment by larsbergstrom** [comment]
For now, we will remove all of the WITHIN entries from the content feed. https://github.com/MozillaReality/ContentFeed/pull/343
