### ISSUE TITLE
syncing logins

### ISSUE THREAD

**Issue by grigoryk** [MozillaReality/FirefoxReality#1394]
As a follow-up to https://github.com/MozillaReality/FirefoxReality/pull/1389 & #717.

Once that #1389 lands, it's fairly trivial to also sync logins. However, they need to be exposed somehow. There are two main avenues here:
- auto-fill support
- basic "password manager" UI, which lets people search and copy/paste passwords

Ideally, both are added at some point. Copy/paste support is tracked in #189.

**Comment by keianhzo** [comment]
@emstanley Maybe we should move this to v12 when Autofill is ready as it doesn't make much sense to show the logins SyncEngine without support for actually exposing the auto fill in the UI.
