### ISSUE TITLE
Better bookmarks UI: navigation

### ISSUE THREAD

**Issue by grigoryk** [MozillaReality/FirefoxReality#1395]
Currently bookmarks library view displays the `mobile` root. #1389 introducing bookmark syncing, which brings an entirety mobile and desktop bookmarks from other Firefox devices, and at that point the current UI is no longer sufficient.

Things that will need to happen here:
-  proper treatment of separators - display in the UI, ignore clicks
- add synthetic `Desktop Bookmarks` folder if logged into `Sync` (or if there are desktop bookmarks around)
- handle folder navigation
- display human-friendly names for the set of default desktop folders

Fenix's codebase could be a good starting point here (if a bit convoluted..).
See: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt and https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/ext/BookmarkNode.kt#L16

**Comment by jvonitter** [comment]
Relates to #1581
