### ISSUE TITLE
Megazord configuration for native Rust libraries

### ISSUE THREAD

**Issue by grigoryk** [MozillaReality/FirefoxReality#1397]
To efficiently consume multiple appservices libraries, a megazord configuration is necessary.

Currently only `libplaces` is being used, for bookmarks storage.
#1389 adds a dependency on `libfxaclient` as well, and we'll need `liblogins` as well for #1394 and password management.

And so, we need to use a "megazord" which contains all the libraries we're using, compiled together.
In the near future consuming non-megazord appservices libraries will not be supported, so this needs to happen on a fairly quick timeline.

The actual work should be fairly straightforward: configuration gradle module substitutions, rust logging, and initializing megazord with a `concept-fetch` client implementation (e.g. gecko fetch client). Follow either what `reference-browser` or `fenix` are doing here.

**Comment by grigoryk** [comment]
Changes to how megazords are consumed are coming in https://github.com/mozilla-mobile/android-components/pull/3806, so let's wait for that to land.

**Comment by bluemarvin** [comment]
Is this required for v6 and FxA? Is it still on track or can we push it to v7?

**Comment by keianhzo** [comment]
This has been already included in #1973 I followed the instructions above. @grigoryk can you confirm that everything is ok?

**Comment by keianhzo** [comment]
Megazrod wasn't fully integrated. Addressed in https://github.com/MozillaReality/FirefoxReality/pull/2129

**Comment by keianhzo** [comment]
Megazord wasn't fully integrated. Addressed in #2129
