### ISSUE TITLE
FxA account settings UI

### ISSUE THREAD

**Issue by grigoryk** [MozillaReality/FirefoxReality#1398]
#1389 adds a rudimentary accounts UI, as a single button that switches states between `Sign in`, `Sign out` and `Reconnect`.

Ideally, we need a separate UI screen:
- displays some basic account details (username, email, avatar)
- has a "Sync now" and "Sign out" buttons
- (optionally) specifying a custom tokenserver url (for users who want to self-host their own sync servers)
- (optionally) allows changing device name

Work to allow disabling sync of bookmarks/history is currently in progress in A-C and A-S, see https://github.com/orgs/mozilla-mobile/projects/37 - so we can't do that just yet.

**Comment by jvonitter** [comment]
likely covered by #1589 but keeping it open for now
