### ISSUE TITLE
The browser functionalities are broken after entering and exiting the private window for several times on certain websites

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1399]
**[Affected Versions]:**
- Firefox Reality 1.3-31930328 (rc1)
- Firefox Reality 1.3-31972323 (rc2)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Pacific - Android 7.1.2 (Oculus Go)

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Open the following web page: https://vr.with.in/watch/the-batmersive-experience
2. Click the play button. (do not enter VR)
3. Click the private window button.
4. Click the "X" button at the top of the view.
5. Repeat step 3 and 4 several times.
6. Click the navigation buttons and observe the behavior.

**[Expected results]:**
- The navigation buttons are working as expected.

**[Actual results]:**
- The navigation buttons are clicked but nothing happens.

**[Notes]:**
- The following functionalities are affected by this issue:
	- The video content is frozen.
	- The audio continues to play even after the browser is closed.
	- The resizing functionality doesn't work properly because of the frozen video.
	- If the private window button is clicked again, the private window is opened with the frozen video.
- The issue is not reproducible if the bookmark or settings buttons are clicked. 
- The issue is not reproducible with a youtube video.
- Attached a screen recording of the issue: [link](https://drive.google.com/file/d/1sm0Gtg64vrjy97gYAjTjDUR3Al2RcovR/view?usp=sharing)

**Comment by Softvision-GeluHaiduc** [comment]
The issue is reproducible in Firefox Reality 1.3-31972323 (rc2) with the Oculus Go headset.

**Comment by MortimerGoro** [comment]
I did some research and I think it's related to: https://bugzilla.mozilla.org/show_bug.cgi?id=1561667

The issue happens when we try to resume a GV session running WebGL content (session.setActive(true) and attach it to a display), and we close the previous GV session (I checked that it happens with any of the session.stop() or session.close() calls). If I don't close/stop the previous GV session the new attached GV session runs WebGL correctly

**Comment by MortimerGoro** [comment]
I pushed  GV patch to fix this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1561667. We can close this when it gets landed

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest FirefoxReality 1.4-32072251 installed on the Oculus Go headset. 
Now, the browser functionalities are not broken after entering and exiting the private window for several times.
