### ISSUE TITLE
Implement Tray theme

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#140]

**Comment by nancyhang** [comment]
@thenadj

**Comment by thenadj** [comment]
We have a new UI Spec for the tray, see attached.

**Comment by thenadj** [comment]
[UIS-26 Mini Tray_002.pdf](https://github.com/MozillaReality/FirefoxReality/files/2212005/UIS-26.Mini.Tray_002.pdf)

**Comment by thenadj** [comment]
Here are the art assets. Not sure if it's easier to have one file with all buttons or all 3 buttons separately, so supplied both, just in case. :)

[mini-tray_icons.zip](https://github.com/MozillaReality/FirefoxReality/files/2212126/mini-tray_icons.zip)
[tray_buttons.zip](https://github.com/MozillaReality/FirefoxReality/files/2212133/tray_buttons.zip)
