### ISSUE TITLE
When sideloading latest to Quest: Firefox Reality does not have permission to run on this device and will now exit

### ISSUE THREAD

**Issue by kennardconsulting** [MozillaReality/FirefoxReality#1407]
## Hardware
Oculus Quest

## Steps to Reproduce
1. Install SideQuest (https://github.com/the-expanse/SideQuest)
2. Drop latest (17-07-2019) Firefox Reality nightly APK into SideQuest and install
3. Open Firefox Reality from 'Unlisted Sources' in Quest

## Current Behavior
See message 'Firefox Reality does not have permission to run on this device and will now exit'. Even though Firefox Reality *does* appear to be running fine just underneath this message.

## Expected Behavior
Firefox Reality has permission :) But seriously, other sideloaded apps (Tea for God) don't have this problem.

<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
The builds were changed. You need to side load the APK that does not have `Store` in the name. Like this one https://queue.taskcluster.net/v1/task/bdu5nfd0SYiASp6MlMcH9Q/runs/0/artifacts/public/FirefoxReality-1.3-31971807-oculusvr-arm-staging-signed-aligned.apk

**Comment by kennardconsulting** [comment]
Okay I was using the 'Oculus Go & Quest (oculusvr)' link on the homepage. It goes direct to an APK. So that maybe needs improving?

**Comment by bluemarvin** [comment]
Yes that is probably the real issue. That link is broken. This one works to find latest builds https://github.taskcluster.net/v1/repository/MozillaReality/FirefoxReality/master/latest

I’ll try and fix the readme tomorrow.

**Comment by kennardconsulting** [comment]
Cool. Thanks for your wonderful support!
