### ISSUE TITLE
Remove androidcomponents_strings.xml files, to use localizations from a-c upstream

### ISSUE THREAD

**Issue by Pike** [MozillaReality/FirefoxReality#1410]
It seems we still have the `androidcomponents_strings.xml` from way back when in the repository.

We should remove those and use the localizations that come with a-c now.

CC @Delphine @pocmo

**Comment by keianhzo** [comment]
@pocmo wouldn't it make sense to serve the internal pages based on the locales set in Gecko so we can serve based on the user's content language order?

**Comment by pocmo** [comment]
Does that differ from the app's locale order in your case? Do you have settings to change that?

I do not really have a strong opinion here - using the app's locale is just way easier, I think. I guess you could consider the error pages being app UI and therefore should use the same language as the app UI?

**Comment by keianhzo** [comment]
In FxR we are adding support for content locales, so you can define a locale order for setting in Gecko throught `setLocales`. Not really sure, I'd expect an error page to follow the same rules as any other web page but I guess it's not a big deal.
