### ISSUE TITLE
Jank Detector UX

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1416]
When performance decreases past acceptable levels, we need to kill the page and let the user know what's happening.

Consider both single and multi-window

Needed by #1401

**Comment by jvonitter** [comment]
Current behavior is to pop this dialog when the page chokes:
![org mozilla vrbrowser-20190717-160516](https://user-images.githubusercontent.com/48839872/61419424-0e0f3200-a8b3-11e9-8bb6-17993fd06f7c.jpg)

**Comment by jvonitter** [comment]
Update body text to say:
_Try reducing the window size to improve performance. Unblocking this page may crash Firefox Reality._

**Comment by jvonitter** [comment]
Now that the text is updated, can we close this? @bluemarvin

**Comment by Softvision-GeluHaiduc** [comment]
Test for this feature are completed.
I will remove the QA label.
