### ISSUE TITLE
Obtain a production FxA client ID

### ISSUE THREAD

**Issue by grigoryk** [MozillaReality/FirefoxReality#1419]
For `feature/fxa` work. See #1389 and #1417 .

**Comment by keianhzo** [comment]
@jvonitter Is there anybody I can contact for this?

**Comment by jvonitter** [comment]
We can clone this bug to request it: https://bugzilla.mozilla.org/show_bug.cgi?id=1584212

**Comment by keianhzo** [comment]
Requested here: https://bugzilla.mozilla.org/show_bug.cgi?id=1585480
