### ISSUE TITLE
The browser view glitches after clicking the enable button for permissions

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1424]
**[Affected Versions]:**
- Firefox Reality 1.3-31972323 (rc2)
- Firefox Reality 1.3-31981701 (rc3)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Click the settings button (gear icon).
2. Click the "Privacy & Security" button.
3. Under the "Permissions" section click the "Enable" button for "Microphone".
4. Observe the behavior.

**[Expected results]:**
- A pop up to "Allow Permissions" appears.

**[Actual results]:**
- After the button is clicked the view glitches after witch the pop up appears.

**[Notes]:**
- The issue is reproducible with all the permissions. (Microphone, Location and Storage)
- The issue is not reproducible on the Oculus Quest or the HTC Vive Focus Plus headset.  
- Attached a screen recording of the issue: [link](https://drive.google.com/file/d/1Rz4Cyt5IqOg8I_v19WNgOgl0qresz06O/view?usp=sharing)

**Comment by keianhzo** [comment]
I see this behavior happening in other apps int he Go (ie. Samsung Browser) so I suspect this might be system related.

**Comment by philip-lamb** [comment]
If this is out of our control, let's file a platform bug with Oculus and close this with `invalid`.
