### ISSUE TITLE
The navigate forward button is inactive for videos on youtube.com

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1426]
**[Affected Versions]:**
- Firefox Reality 1.3-31972323 (rc2)
- Firefox Reality 1.3-31981701 (rc3)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Visit the following web page: https://www.youtube.com/watch?v=Tbp9AyitsJ8&mozVideoProjection=360_auto
2. Click on another video from the "Up Next" section.
3. Click the navigate back button (arrow pointed to the left).
4. Click the navigate forward button (arrow pointed to the right).

**[Expected results]:**
- The previously visited video is loaded.

**[Actual results]:**
- The navigate forward button can not be clicked, it's inactive.

**[Notes]:**
- The issue is reproducible with any videos from youtube.
- The issue is not reproducible on the vimeo website.  
- Attached a screen recording of the issue: [link](https://drive.google.com/file/d/1aFS2YskB6QVo1D_ycgxF-I6Ljqina0x-/view?usp=sharing)

**Comment by philip-lamb** [comment]
This may be related to the webext reload behaviour.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest FirefoxReality 1.4-32072251 installed on the Oculus Go headset. 
Now, the navigate forward button is active for videos on youtube.
