### ISSUE TITLE
The enable button for camera permissions on the HTC Vive Focus Plus headset is not working

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1427]
**[Affected Versions]:**
- Firefox Reality 1.3-31930328 (rc1)
- Firefox Reality 1.3-31972323 (rc2)
- Firefox Reality 1.3-31981701 (rc3)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Click the settings button (gear icon).
2. Click the "Privacy & Security" button.
3. Under the "Permissions" section click the "Enable" button for "Camera".
4. Observe the behavior.

**[Expected results]:**
- A pop up to "Allow Permissions" appears.

**[Actual results]:**
- After the button is clicked nothing happens, no pop up appears.

**[Notes]:**
- The issue is not reproducible on the Oculus Quest or the Oculus Go headset, the camera permission is not present on these headsets.
- The issue is not reproducible with the remaining permissions: microphone, location and storage
- Attached a screen recording of the issue: [link](https://drive.google.com/file/d/1n1pHrR5VD3q7mBVuLqmz6Dq8OrSrSJ3B/view?usp=sharing)

**Comment by philip-lamb** [comment]
Related to #929

**Comment by jvonitter** [comment]
we should remove the camera permission setting for Wave devices

**Comment by bluemarvin** [comment]
We need to hide the options on Oculus too. Currently we ignore requests for camera permission on Wave and Oculus.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.4-32142025 (08.05.2019) installed on the HTC Vive Focus Plus headset. 
Now, the camera permissions button is hidden from in the "Permissions" section.
