### ISSUE TITLE
The content continues playing in the background even though the headset lost track of position

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1430]
**[Affected Versions]:**
- Firefox Reality 1.3-31930328 (rc1)
- Firefox Reality 1.3-31972323 (rc2)
- Firefox Reality 1.3-31981701 (rc3)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to any 360 video or VR content.
2. Enter immersive mode.
3. Block all the cameras views.
4. Observe the behavior.

**[Expected results]:**
- The screen goes blue, a pop up appears informing that the tracking was lost and the content is paused.

**[Actual results]:**
- The screen goes blue, a pop up appears informing that the tracking was lost and the content continues playing in the background.

**[Notes]:**
- Attached a screen recording of the issue: [link](https://drive.google.com/file/d/1cK2NqqvVusn1esrtfzdCkUZvhpFq9p7r/view?usp=sharing)

**Comment by philip-lamb** [comment]
Related #1431
