### ISSUE TITLE
New window size is save even when not used

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1434]
## Hardware

All

## Steps to Reproduce

1. Click window resize button
2. Click `0.5x` button
3. Press back button to cancel resize and restore window size
4. Kill FxR
5. Launch FxR

## Current Behavior

Window size is `0.5x`

## Expected Behavior

Window size should be same as when FxR was killed.

## Regression
Regressed by https://github.com/MozillaReality/FirefoxReality/pull/1411

**Comment by philip-lamb** [comment]
@MortimerGoro Is this covered in the current window size work?

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest FirefoxReality 1.4-32072251 installed on the Oculus Go headset. 
Now, the window size that was not saved is not used after a restart of the browser.
