### ISSUE TITLE
Using AndroidStudio Native type debugger can't enter Hubs.mozilla

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#1435]
This is just a note, and I don't think this is high priority. It looks like running GV in the debug mode will go to unpredictable code path.

## Hardware

Oculus Go and Wave Focus Plus

## Steps to Reproduce

1. Go to http://hubs.mozilla.com and create a room
2. Enter VR

## Current Behavior

1. In Oculus Go, it will show `this browser doesn't support WebAssembly, please use a new browser`
2. In Wave Focus Plus, it will crash at the first visit (https://crash-stats.mozilla.com/report/index/a8870c74-e6ec-499d-ad21-f1fdc0190716), after that, it will be good.

## Expected Behavior

Using Native debug type should work as using Java type to debug. We should be able to enter Hubs.mozilla without issues.

## Possible Solution

It is very possible that we disable/enable something when we are doing debug with AndroidStudio. Use debugger to dig into it.

## Context

Can't run Hubs when we need to debug native code with symbols.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by philip-lamb** [comment]
We can reopen if necessary, but nothing actionable on this right now.
