### ISSUE TITLE
Test WaveVR 64-bit build

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#1439]
While WaveVR SDK 64-bit version is in restricted testing phase, we should configure and test 64-bit WaveVR builds.

Steps:
* verify ability to build
* basic performance profile
* regression testing

This is part of a larger requirement to test and verify performance of 64-bit builds on all platforms.

**Comment by MortimerGoro** [comment]
PR ready for testing here: https://github.com/MozillaReality/FirefoxReality/pull/1442

Remember to update the third party repo
