### ISSUE TITLE
The "Autoplay Media" option is not reset to it's default value if the "Reset" button is clicked

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1440]
**[Affected Versions]:**
- Firefox Reality 1.3-31981701 (rc3)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Pacific - Android 7.1.2 (Oculus Go)
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- All Firefox settings are set to their default values.

**[Steps to reproduce]:**
1. Click the "Settings" button.
2. Click the "Privacy & Security" button.
3. Click the "Autoplay Media" button.
4. Click the "Reset" button and observe the behavior.

**[Expected results]:**
- The "Autoplay Media" option resets to the "Off" default value.

**[Actual results]:**
- The "Autoplay Media" option remains set on the "On" value.

**[Notes]:**
- Attached a screen recording of the issue: [link](https://drive.google.com/open?id=1y6vQvOyVetrHBglhKc34GTtkrrnaYyqf)

**Comment by keianhzo** [comment]
Will get fixed when #1440 is merged.

**Comment by keianhzo** [comment]
@Softvision-RemusDranca This should be fixed in the latest staging build.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the 1.3-32040913 version of the browser. The "Autoplay Media" option is now reset to its default value if the "Reset" button is clicked.
I will close this issue as verified-fixed.
Tested on Oculus Pacific - Android 7.1.2 (Oculus Go) and Oculus Quest - Android 7.1.1.
