### ISSUE TITLE
Crash when exiting from immersive mode on Wave

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1446]
## Hardware
HTC Focus running 64 bit FxR

## Steps to Reproduce

1. Go to https://webvr.soundboxing.co/
2. enter immersive mode
3. Press home button
4. Exit to home shell

## Current Behavior
Intermittent crash: https://crash-stats.mozilla.com/report/index/abd3cafb-9b14-4833-91db-6895b0190722
## Expected Behavior

Should not crash. Only happened once. Not been able to reproduce.

**Comment by philip-lamb** [comment]
Needinfo until we can consistently reproduce. Can also close if we cannot reproduce with production WaveVR 64-bit.
