### ISSUE TITLE
UI not visible after reopening the app

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#1447]
## Hardware
Oculus

## Steps to Reproduce
It happens sometimes when closing and restoring FxR. Video: [hidden_ui.mp4.zip](https://github.com/MozillaReality/FirefoxReality/files/3422496/hidden_ui.mp4.zip)

I believe it only happens when launching the app from Android Studio, and closing and resuming after that. Or at least that increases the chances that it happens.

## Current Behavior
UI is not visible, only the browser window.

## Expected Behavior
Everything should be visible.

**Comment by philip-lamb** [comment]
Need accurate steps to reproduce before we action.

**Comment by MortimerGoro** [comment]
I believe that #1485 and #1486 also fix this bug

**Comment by MortimerGoro** [comment]
Fixed in https://github.com/MozillaReality/FirefoxReality/pull/1487
