### ISSUE TITLE
The headset does not go to sleep if the 360 video on screen controls are active

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1448]
**[Notes]:**
- The issue is only reproducible when the 360 video on-screen controls are displayed.

**[Affected Versions]:**
- Firefox Reality 1.3-31981701

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to any 360 youtube video longer than 5 minutes.
2. Start playing the video in 360 mode.
3. Press the trigger button on the controller to see the on-screen controls.
4. Remove the headset for more than 5 minutes and put it back.
5. Observe if the headset goes to sleep.

**[Expected results]:**
- The headset goes to sleep.

**[Actual results]:**
- The headset does not go to sleep and the video continues playing.

**[Additional Notes]:**
- The issue is not reproducible on the Oculus Quest headset.
- The issue is only reproducible on videos from youtube.

**Comment by philip-lamb** [comment]
@MortimerGoro Can you check whether the sleep event is being ignored by us here?

**Comment by jvonitter** [comment]
@Softvision-GeluHaiduc can you check if this still happens? if it's only the Go and only YouTube it'll be lower pri.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.5-32741905 (1c04b86a) installed on the Oculus Go headsets.
Now, the headset does go to sleep even if the 360 video on screen controls are active.
