### ISSUE TITLE
The "Settings" button is not highlighted while the "Settings" menu is opened

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1452]
**[Notes]:**
- I logged this issue because, there is an inconsistency between the "Settings" button compared with the "Private Browsing" and "Bookmarks" buttons, which are highlighted. 

**[Affected Versions]:**
- Firefox Reality 1.3-32040913

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Pacific - Android 7.1.2 (Oculus Go)
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- Have the latest Firefox Reality apk installed.

**[Steps to reproduce]:**
1. Open the Firefox Reality browser from prerequisites.
2. Click the "Settings" button and observe the button.

**[Expected results]:**
- The button is highlighted, as for the "Enter Private Browsing" and the "Open Bookmarks" button.

**[Actual results]:**
- The button is not highlighted.

**[Additional Notes]:**
- Attached a screenshot of the issue:
![Settings menu](https://user-images.githubusercontent.com/40061643/61803172-5fcb3580-ae3a-11e9-87d2-6546843a6cc6.png)

**Comment by philip-lamb** [comment]
@jvonitter please repro.

**Comment by jvonitter** [comment]
@thenadj i think this is by design because bookmarks and private browsing show up in the main window, while settings opens in a new window. can you confirm?

**Comment by thenadj** [comment]
@jvonitter Correct, this is by design.
