### ISSUE TITLE
SSL Check Fault

### ISSUE THREAD

**Issue by ScottWitte** [MozillaReality/FirefoxReality#1453]
When a URL is entered without a protocol, Firefox Reality automatically rewrites the URL with the https: protocol. This can lead to problems.

## Hardware
Oculus Go

## Steps to Reproduce
Go to blue.com

## Current Behavior
When no protocol is given, Firefox Reality rewrites a secure URL, https://blue.com, which results in a "Secure connection failed" error since the site has no SSL certificate. If you manually type the insecure URL, http://blue.com, FFR doesn't rewrite the URL but indicates that the URL is insecure, as with all other browsers.

## Expected Behavior
Send the URL request as typed. Indicate an insecure domain if a secure one isn't returned automatically. If a secure domain is provided, test to be sure the SSL certificate is valid, as happens in all other browsers.

## Possible Solution
Send the URL request as typed.

## Context
Reality check: A huge number of sites, a good 30-40%?, don't have SSL certs, probably because they don't feel the need since they don't ask for anything from visitors and don't want the hassle and expense of getting and maintaining an SSL cert. (We are talking what is, not what should be. Only a bare majority offer https: by default.)

The VAST majority of web users don't type the protocol in a URL. This has to be especially true in a VR browser since it is much more hassle to point and click type vs using a keyboard. For some 40% of sites, this results in a scary "Secure connection failed" error and they are blocked from the site. It will never occur to the vast majority of them to try again using "http:" It even took me a lot of deliberate effort to figure out what was actually happening and why. That is not user-friendly. 

```
```

</details>

**Comment by philip-lamb** [comment]
@bluemarvin Your input on this would be helpful.

**Comment by ScottWitte** [comment]
So this seems to have stalled. What info is still needed?
