### ISSUE TITLE
Add developer option to clear cache

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1454]
Requested by @ScottWitte - 
"As a developer, I need to be certain that the changes I make in code and upload are indeed being used when viewing in FxR. If a change doesn't work, is it because I didn't really fix it or the old code is stuck in cache?

BTW, I really hate Safari wiping out everything when I just want a clean cache. Please don't do THAT.

**Comment by jvonitter** [comment]
related to #336

**Comment by jvonitter** [comment]
I think this is as simple as a "clear cache" button in the Developer Options section of Settings. @keianhzo let me know if you want designs for it.

**Comment by keianhzo** [comment]
@jvonitter this is ready for review. At the moment we just wipe out all the cache. This could be implemented in a more granular way (cookies, dom, image, network, etc) but that would require an spec to know how we should integrate it on the settings, so this will help to devs in the meantime.

**Comment by jvonitter** [comment]
@keianhzo Thanks for this! I've asked Nadja to update the settings spec with options similar to what's in Firefox desktop. I'll update here when they're done.

**Comment by ScottWitte** [comment]
Looking forward to having this ability!

**Comment by keianhzo** [comment]
@jvonitter This was originally adding a button in the developer options (privacy later per @bluemarvin request) but I see that it's referenced here https://github.com/MozillaReality/FirefoxReality/issues/336 as part of the history clear but we are also waiting for a spec per https://github.com/MozillaReality/FirefoxReality/pull/1517. Should we make this part of the History clear or should we keep it independent in it's own privacy panel setting? In case of the later, do we still need a spec for that? 

The PR for just the clear option in the privacy panel is ready in case we just need that for the moment.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality 1.5-32661642 (74326741) installed on the Oculus Go, Quest, HTC Vive Focus, Focus Plus and Lenovo Mirage Solo headsets.
The options to clear “Cookies & Site Data” and to clear “Cached Web Content” are part of the “Privacy and Security” card from Settings.
Also, the option to clear the history is available in the History View.
