### ISSUE TITLE
The "Enable Curved Display" option is not reset to it's default value if the "Reset" button is clicked

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1457]
**[Affected Versions]:**
- Firefox Reality 1.3 - 32040913

**[Affected Platforms]:**
- Oculus Pacific - Android 7.1.2 (Oculus Go)
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- All Firefox settings are set to their default values.

**[Steps to reproduce]:**
1. Click the "Settings" button.
2. Click the "Display" card.
3. Click the "Enable Curved Display" button.
4. Click the "Reset" button and observe the behavior.

**[Expected results]:**
- The "Enable Curved Display" option resets to the "Off" default value.

**[Actual results]:**
- The "Enable Curved Display" option remains set on the "On" value.

**[Notes]:**
- This issue is also reproducible in the production version (1.3-31981701) of the Firefox Reality browser.
- I wasn't able to test this issue using the HTC Vive Focus Plus headsets because a signature error is displayed when trying to install the latest Firefox version. I will follow up with a comment as soon as the install failure is fixed for this device.
- Attached a screen recording of the issue: [link](https://drive.google.com/open?id=14jsb8xYWP-cg23lLRy1KRflB0Whl7hmn)

**Comment by jvonitter** [comment]
Sounds related to #1440

**Comment by keianhzo** [comment]
Seems to be a different issue.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the 1.4 - 32122206 (07.30.2019) apk. version.
Tested on Oculus Pacific - Android 7.1.2 (Oculus Go) and Oculus Quest - Android 7.1.1.
