### ISSUE TITLE
The vertical scrollbar is wrongly displayed for the "Language" card even though no scrollable content is available

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1461]
**[Affected Versions]:**
- Firefox Reality 1.3 - 32040913

**[Affected Platforms]:**
- Oculus Pacific - Android 7.1.2 (Oculus Go)

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- Have the latest Firefox Reality 1.3 - 32040913 browser installed.

**[Steps to reproduce]:**
1. Open the browser from prerequisites.
2. Click the "Settings" button.
3. Click the "Display" card.
4. Observe the right side of the menu.

**[Expected results]:**
- No scrollbar is displayed because all the menu's content fits on the first view of the page.

**[Actual results]:**
- The scrollbar is displayed.

**[Notes]:**
- On Oculus Pacific(Oculus Go) device the scrollbar is correctly displayed because not all the menu's content fits on the first view of the page.
- I wasn't able to test this issue using the HTC Vive Focus Plus headsets because a signature error is displayed when trying to install the latest Firefox version. I will follow up with a comment as soon as the install failure is fixed for this device.
- Attached a screen recording of the issue: [link](https://drive.google.com/open?id=1ukLwZBLRgfeaGoo_TPVPG7VpmP8dRZVe)

**Comment by philip-lamb** [comment]
@keianhzo I think you were working on this. If so, add a link to the pull request.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest 1.4-32192006 (08.08.2019) apk. version on the Oculus Quest and HTC Vive Focus devices.
However, this issue is now reproducible on the Oculus Pacific(Oculus Go), device. 
I will reopen this issue and update the affected platforms section.

**Comment by keianhzo** [comment]
Should have been closed as part of #1484

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the 1.4-32322148 (08.20.2019) apk. version.
Tested on Oculus Pacific (Oculus Go), Oculus Quest and HTC Vive Focus Plus.
