### ISSUE TITLE
Menus appear behind the window in curved mode

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1468]
## Hardware
Quest with v1.3 (+ Imanol's keyboard changes)

## Steps to Reproduce
1. Turn 'curved display' option to ON
2. Navigate to a 2D movie (I used https://vimeo.com/349748860) and make it full screen using the on-screen controls
3. Click the projection options or brightness button

## Current Behavior
The menus appear behind the viewport and can not be selected.

## Expected Behavior
The menu should appear in front of the view, not behind it

```
```

</details>

**Comment by MortimerGoro** [comment]
This is fixed in https://github.com/MozillaReality/FirefoxReality/pull/1467

**Comment by MortimerGoro** [comment]
It has been improved in #1467 but not fixed. The problem is related to depth sorting with layers in Oculus.

**Comment by keianhzo** [comment]
I've seen this happening also with the context menu and the awesomebar when showing on the left/right windows.
