### ISSUE TITLE
Pointer does not render on close button

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#147]
STR:
1) Go into private browsing mode
2) Point at the close button.
expected results: Red pointer is visible on close button
actual results: The button is highlighted and clickable but the red pointer arrow is not.

**Comment by bluemarvin** [comment]
I have confirmed it is a scale issue.

**Comment by nancyhang** [comment]
This may change with the new design @bluemarvin

**Comment by bluemarvin** [comment]
This was fixed in #186
