### ISSUE TITLE
More natural translation of "Environment" in Japanese setting menu

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/FirefoxReality#1472]
In Japanese setting menu, "Environment" is translated into "実行環境". Yes, "environment" can be literally translated into it but "実行環境" sounds like more "platform" like Operating system, CPU, etc where software runs on.

I'd like to suggest replacing "実行環境" with "背景" (background). I think it sounds more natural to us Japanese.

![org mozilla vrbrowser dev-20190729-145549](https://user-images.githubusercontent.com/7637832/62086549-8c54c800-b213-11e9-8420-555a23faedb6.jpg)

**Comment by takahirox** [comment]
Suggested on Pontoon.

https://pontoon.mozilla.org/ja/android-l10n/MozillaReality/FirefoxReality/app/src/main/res/values/strings.xml/?search=%E5%AE%9F%E8%A1%8C%E7%92%B0%E5%A2%83

**Comment by philip-lamb** [comment]
@Delphine Let me know how we can get @takahirox 's suggestion accepted.

**Comment by Delphine** [comment]
I'll start a convo with the localizers to communicate about this and see what their opinion is. thanks

**Comment by Delphine** [comment]
@marsf Just remembered you were on GitHub. Wanted to add you to this conversation so you can possibly give some feedback about all this. Thank you!

**Comment by marsf** [comment]
I agree with @takahirox for "実行環境".

IMO, "背景" (background) is just like 2D "stage background".  I feel "environment" is more 3D surrounding, so, it includes sky and ground.

I'd like to suggest "景色" (landscape), if the ground is always in the "environment".
@takahirox, how do you think?

**Comment by takahirox** [comment]
I think "景色" sounds good. Thanks for the suggestion @marsf

**Comment by marsf** [comment]
I just changed the translations.
Thanks.

https://pontoon.mozilla.org/ja/android-l10n/MozillaReality/FirefoxReality/app/src/main/res/values/strings.xml/?search=environment&string=197871
