### ISSUE TITLE
Add ping for telemetry enable/disable

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#1477]
We don't have a clear idea of what percentage of users disable telemetry. When a user elects to disable it, we should transmit a "goodbye" ping, and conversely a "hello" ping when a user enables the function.

This will help gauge user sentiment around collecting data to improve the browser.

**Comment by philip-lamb** [comment]
requires #561

**Comment by philip-lamb** [comment]
@jvonitter It'd be good to pull this into 1.5 as part of our telemetry boost.

**Comment by jvonitter** [comment]
- Data review needs to be completed during implementation. Form is here: https://github.com/mozilla/data-review/blob/master/request.md and can be submitted to @harraton when ready.
- https://github.com/MozillaReality/FirefoxReality/wiki/Telemetry should also be updated to show the new event(s)

**Comment by keianhzo** [comment]
@jvonitter the PR is ready for review. Shouldn't be closed before the data review is approved though.

**Comment by jvonitter** [comment]
From Manuel:
I got some info about how to implement it from the Telemetry team. They pointed out a couple of things though:
- They were concern about sending a ping after the the user opts out, we need to really justify the need of this so we can pass the data review
- It seems that some sort of user information is sent with the event ping so we will be able to group by user through backend queries
- They told me that there is always a discrepancy between our telemetry and external sources and trying to hard to fill the gap might be a time sink and lead nowhere: “In general things never match with external data sources” (edited)

**Comment by jvonitter** [comment]
Moving this into 6 so we can consider the feedback and figure out the right path.

**Comment by keianhzo** [comment]
Data review form, attn @harraton
[datareview-telemetry-status.txt](https://github.com/MozillaReality/FirefoxReality/files/3706400/datareview-telemetry-status.txt)

Wiki update in progress

**Comment by philip-lamb** [comment]
Link to ping used for this purpose on desktop: https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/data/optout-ping.html

**Comment by keianhzo** [comment]
@philip-lamb I talked to the Telemetry team before implementing this and they recommended using an event ping vs the opt-out ping: 

> @manuel.martin so what I’m saying is if you send an event, or tack it on the settings of the event ping, we can group by user if we use the opt-out ping, we cannot

**Comment by keianhzo** [comment]
@harraton Any updates on this?

**Comment by harraton** [comment]
**Data Review Form** 

Instructions: Data Stewards will review a request for data collection and endorse responses to each question. If the request does not provide answers to questions, reviewers give an r- and point to the questions that can’t be answered.

1. Is there or will there be documentation that describes the schema for the ultimate data set in a public, complete, and accurate way? 
Yes (Wiki)

2. Is there a control mechanism that allows the user to turn the data collection on and off? 
Yes, there is a telemetry switch. This new data allows the team to understand if that switch has been turned to On or Off.


 4. Using the category system of data types on the Mozilla wiki, what collection type of data do the requested measurements fall under?
Category 2.

  5. Is the data collection request for default-on or default-off?
Default-On

6. Does the instrumentation include the addition of any new identifiers.
No.

 7. Is the data collection covered by the existing Firefox privacy notice? 
Covered by the Firefox Reality Privacy Notice.

8. Does there need to be a check-in in the future to determine whether to renew the data? Yes

9. Does the data collection use a third-party collection tool? 
No.

**Comment by harraton** [comment]
Ping approved.

**Comment by keianhzo** [comment]
@jvonitter The Telemetry wiki page has been updated.
