### ISSUE TITLE
Using resize multiplier button can fail to properly resize window in focus mode

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#148]
STR:
1) Go into focus mode
2) Resize window to 2x
3) Manually make window wider
4) Press resize 2x button again
expect results: Window is restored to 2x size
actual results: window stays same size but content gets resized.

**Comment by keianhzo** [comment]
I've been trying for a while and can't reproduce it, Could this be a duplicate of #108 ?
