### ISSUE TITLE
Move window buttons get stuck in hover state

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1482]
## Hardware
Quest - multiwindow apk from 7/31

## Steps to Reproduce
1. Open a second window
2. Change the position of the window left and right
3. Move pointer off the left/right arrows

## Current Behavior
Sometimes the button stays in the hover state even though you're not hovering. (see image)
![org mozilla vrbrowser-20190731-165543](https://user-images.githubusercontent.com/48839872/62256107-e50f9680-b3b4-11e9-9d4a-692609c1c267.jpg)

## Expected Behavior
The button returns to its normal state when the pointer isnt on it.

```
```

</details>

**Comment by keianhzo** [comment]
@jvonitter  Fixed in multi-window branch. You can test it here: https://send.firefox.com/download/b19a13f1cd13cdb2/#yPrFg64e1SUhq_8Ya6UsMA
