### ISSUE TITLE
Touch events are broken in noAPI flavor

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#149]
Looks like the touch events for noapi are broken. Scrolling a page does not work and typing on keyboard is very difficult. Specifically the mouse move events look like they are not being generated.

**Comment by nancyhang** [comment]
P2

**Comment by philip-lamb** [comment]
Is this still present in 1.1.2?

**Comment by MortimerGoro** [comment]
This can be closed
