### ISSUE TITLE
Settings icon looks too much like brightness icon

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1491]
New icon incoming from @thenadj

**Comment by thenadj** [comment]
We're updating this as part of UIS-73 to ensure it matches the rest of the tray icons. I'll upload the SVG as soon as it's done.

**Comment by jvonitter** [comment]
Settings icon (and others needed for tray updates) are done! 
[icon-tray-settings-v3.svg.zip](https://github.com/MozillaReality/FirefoxReality/files/3506573/icon-tray-settings-v3.svg.zip)
