### ISSUE TITLE
On Youtube and Google Photos, no quality control.

### ISSUE THREAD

**Issue by wonson** [MozillaReality/FirefoxReality#1494]
## Hardware
Oculus Go

## Steps to Reproduce
1. Go to Google Photo
2. Open a VR Video
3. Cannot find a quality control near the full screen button in VR Mode, Desktop Mode, nor Mobile Mode

## Current Behavior
Cannot find a quality control near the full screen button, just like using it in a mobile phone.
If you use Google Photo on a mobile phone, there is no quality control and only use "auto".

## Expected Behavior
Find a quality control near the full screen button.
 I prefer VR looks more like Desktop PC browser. However, in fact it happens even when UA is "Desktop".

## Possible Solution
Hmmm.. Maybe solve UA and resolution problem? or remove the cap of resolution/use a scale-up resolution to lie to the web app?

## Context
I want to watch my VR Video in full quality, but "auto" only gave me < 1080s. Then I found I have no way to accomplish it as I do in PC.

## Error Logs and Stack Traces
---

```
```

</details>

**Comment by philip-lamb** [comment]
The selection of the quality level on the Oculus Go is deliberate because this device struggles with high-definition youtube playback. We're currently looking at some functionality changes in the youtube webext included in FxR and will consider this as part of that work.

Should be considered as part of work in #1433

**Comment by philip-lamb** [comment]
Manually changing the quality is possible by adjusting using the youtube in-content control in fullscreen mode, so not something we currently intend to support via custom controls.
