### ISSUE TITLE
Crash report settings label not left-aligned

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#1495]
## Configuration
https://github.com/MozillaReality/FirefoxReality/commit/21217126e6feeb2aca5998e303ae961ece93ab3e

## Steps to Reproduce
Look at Settings->Privacy and security, label for "Send backlogged crash reports"

## Current Behavior
Label appears to be centred.
![Screenshot_20190804_214439](https://user-images.githubusercontent.com/5752887/62440499-92fbb600-b7a4-11e9-81f2-37b6a4b44edf.png)

## Expected Behavior
Label should be left-aligned.

needed-by #1243

**Comment by keianhzo** [comment]
Fixed by # https://github.com/MozillaReality/FirefoxReality/pull/1484
