### ISSUE TITLE
The newly installed FxR app can not be closed after pressing the vive/oculus button on the controller

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1498]
**[Notes]:**
- The FxR app is closed only after the headset is removed for ~30 seconds.

**[Affected Versions]:**
- Firefox Reality 1.4-32142025 (08.05.2019)
- Firefox Reality 1.4-32171914 (08.06.2019)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on.
- Sideload the latest build of the FxR app.

**[Steps to reproduce]:**
1. Open the newly installed FxR app.
2. Press the vive button on the controller.
3. Select the "Home" option on the pop up.
4. Observe the behavior.

**[Expected results]:**
- The FxR app is closed and the Vive home screen is displayed.

**[Actual results]:**
- The FxR app is resumed.

**[Additional notes]:**
- The issue is reproducible if the "Store", "Library", "Account" or "Settings" options from the pop up are selected.
- Attached a screen recording of the issue: [link](https://drive.google.com/file/d/1DfYQlplt2msNDZUT0iTuHy9abrPMCjBU/view?usp=sharing)

**Comment by Softvision-GeluHaiduc** [comment]
This issue is also reproducible with the latest Firefox Reality 1.4-32171914 (08.06.2019) installed on the **Oculus Quest** headset and is still present on the **HTC Vive Focus Plus** as well. 
Also, a crash happens every time the app is wrongly resumed.
Attached a screen recording of the issue [link](https://drive.google.com/file/d/1sjesmU5r8jxb4C9sg0HMELf5uQYIXS7p/view?usp=sharing)
I will also update the title and description of the issue accordingly.

**Comment by MortimerGoro** [comment]
This should be fixed by #1501 and #1510

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.4-32182105 (08.07.2019) installed on the Oculus Quest and HTC Vive Focus Plus headset. 
Now, the newly installed FxR app can be closed after pressing the vive/oculus button on the controller.
