### ISSUE TITLE
UI issues occur when trying to navigate Plex web app

### ISSUE THREAD

**Issue by lboyce** [MozillaReality/FirefoxReality#1503]
## Hardware
Oculus Quest

## Steps to Reproduce

1.log-in to Plex via web access at app.plex.tv (can provide server access if needed. Requires account)
2.Play a 3D movie and move to full-screen
3.Choose "3D Side-by-Side" in the Firefox controls

## Current Behavior

The first bug is related to the on-screen UI from Plex. The transport control UI does disappear after a couple seconds as it is supposed to, creating a problem in the Side-by-Side view. And often, the 3D Side-by-Side section tool gets hidden behind the video screen, preventing you from selecting it.  

## Expected Behavior

After playing a movie and selecting 3D Side-by-Side, the Plex transport UI should disappear allowing for a clean view of the 3D movie.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by philip-lamb** [comment]
Related: #1504

**Comment by philip-lamb** [comment]
@lboyce Are you able to capture a screenshot or video of the problem to help us out? Instructions for capture are here: https://github.com/MozillaReality/FirefoxReality/wiki/Tips-for-recording-videos
