### ISSUE TITLE
Stereo video mode for 2D content

### ISSUE THREAD

**Issue by lboyce** [MozillaReality/FirefoxReality#1504]
**Is your feature request related to a problem? Please describe.**
Watching 3D movies from my online server via a solution like Plex or Emby for instance forces me to only be able to watch copies of films that use Side-by-Side implementation. 

**Describe the solution you'd like**
An additional option to watch Over/Under 3D implementation would increase 3D viewing options. 

**Describe alternatives you've considered**

**Additional context**

**Comment by bluemarvin** [comment]
There is a 180 over/under option (accessed by pressing the glasses icon in the video controls, it's the last option in the list.). Do yo need something other than 180 over/under?

**Comment by lboyce** [comment]
Yes, a 3D over/under for 3D feature films (blu-ray) that utilize over/under implementation, not 180.

**Comment by philip-lamb** [comment]
This needs a couple of extra 2D stereo video modes added to our current movie mode; over-under, side-by-side, and over-under half height and half-side-by-side modes.
