### ISSUE TITLE
Firefox Reality doesn't open A-frame built .html page in VR mode on Oculus Quest

### ISSUE THREAD

**Issue by ZeljkoVR** [MozillaReality/FirefoxReality#1516]

**Comment by ZeljkoVR** [comment]
Hello! I use Firefox Reality on Oculus Quest. I built very simple, test .html page in A-frame - http://www.virtual.zeljkozoricic.com, and this is what happens: while I attempt to open it by writing URL via Firefox Reality in Quest, it shows content in a screen mode only while refusing to open it in a VR mode. When I click on a VR icon, VR headset vision gets dark and stays that way indefinitely. Help, please? Is it a bug or I do something wrong? Thank you in advance!

**Comment by philip-lamb** [comment]
Does this work in the built-in browser on that platform? If not, it might be an issue with the code.

**Comment by philip-lamb** [comment]
/remind me in 2 days Move or close

**Comment by ZeljkoVR** [comment]
Philip, thank you for your time, and effort. It doesn't work in the Oculus Quest built-in Chrome browser either. Are you familiar with A-frame, please?

**Comment by philip-lamb** [comment]
It's outside the scope of the support I can provide, but I recommend engaging with the A-Frame community and learning resources, e.g. https://aframe.io/community/ Thanks!

**Comment by ZeljkoVR** [comment]
Philip, thank you!
