### ISSUE TITLE
multiwindow polish - center tray with active window

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1521]
The tray should be centered beneath the active window (instead of staying fixed in the center)

**Comment by keianhzo** [comment]
@jvonitter @thenadj still working on fixing the tooltips but you can check this out here:
https://send.firefox.com/download/83c94e9a4503fc73/#sj-gGTtXGr2vlUEJkA58PQ

**Comment by MortimerGoro** [comment]
@jvonitter @thenadj new APK for testing: https://send.firefox.com/download/1680ed60b990aad4/#sLaHOuepFsdzFdQd9peV_A
