### ISSUE TITLE
multiwindow polish- force curved mode

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1522]
Force curved mode in multiwindow (even if flat mode is on for one window)

**Comment by philip-lamb** [comment]
Does this imply that users won't be able to choose flat mode? If so, we're going to get some push-back on this one.

**Comment by jvonitter** [comment]
@philip-lamb with multiple windows, yes. if we get pushback, we can address it then. for now this solves a bunch of problems with the other UI clipping into the windows and feels super slick :)
