### ISSUE TITLE
Telemetry for changing environments.

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1524]
Relates to #1513 

Can we track how many people change their environment? 

Bonus points if we can report how often the people who change environments do it - maybe an average of time per image? 

(Needs data collection approval before we can take it live.)

**Comment by keianhzo** [comment]
@jvonitter We can. Maybe to be consistent with the rest of the Telemetry we could do it a frequency per times/session duration. The second part you mean how long they use each environment? We can send a ping at the end of the session with the session time and the used env so we can see what's the most popular one.
