### ISSUE TITLE
multiwindow polish- URL bar for tiny windows

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1525]
When a user makes a window small and they have multiple-windows, the URL bar can extend beyond the bounds of the small window.

To fix this, we'd like to 
- Set the minimum window size to .5x (so users cant make the window smaller than that)
- Dynamically shrink the URL bar to match the window size.

Spec for how to shrink the URL bar are in the pdf attached here:
https://trello.com/c/LETzDCDK/389-bug-28-url-bar-for-small-window-size

We will test to see if .5x is small enough to satisfy what users want from a small window and whether the smaller URL bar is usable.

**Comment by MortimerGoro** [comment]
@jvonitter Tall but narrow width windows are used a lot in japan to read manga. Can we confirm that we are not harming their use case?

**Comment by jvonitter** [comment]
I don't think we know yet. I want to try it this way, but I don't know for sure that we'll keep the min size at .5x. Once we have the shrinking toolbar, we can evaluate how it works with skinnier windows. Probably makes sense to do the toolbar first, then we can make some choices about minimum size.
