### ISSUE TITLE
user agent polish- tooltip & icon update

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1527]
Right now the user agent toggle in the awesome bar says "switch user agent"
It should say something more user friendly/familiar. I suggest "Request desktop site" to align with mobile.

We should also remove the "VR" icon and use just the monitor icon with a checkmark when it's active.

needs #1473

**Comment by jvonitter** [comment]
These are the correct icons
[UA_Icons.zip](https://github.com/MozillaReality/FirefoxReality/files/3474539/UA_Icons.zip)

**Comment by keianhzo** [comment]
@jvonitter @thenadj This is under review. Testing APK: https://send.firefox.com/download/1ac9371fe061bd0d/#xwc4tnweFrRrhP1XGGrb-Q
