### ISSUE TITLE
English disappears from the preferred language list

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1528]
## Steps to Reproduce
Open language settings
Select the Edit button for 'Preferred language for displaying websites'
Note English (default) shows up in the left column.
Click a language in the right column

## Current Behavior
English disappears from the left column until you move the pointer, then it comes back again.

## Expected Behavior
English stays on the list and doesn't disappear when you click on another language.

related to #794 

```
```

</details>

**Comment by jvonitter** [comment]
related to #1529

**Comment by keianhzo** [comment]
It appears again if you move the cursor, seems to be a bug in the Android RecyclerView. I've added a workaround in #1551.

APK for testing: https://send.firefox.com/download/7dd604036062eafc/#-5IbRAUYh2hXm7lzvE6WmA
