### ISSUE TITLE
preferred website language setting polish

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1529]
- [x] Display is spelled incorrectly (it says 'dispaly')
- [ ] Scrollbar is the incorrect color and moves the wrong direction when clicking/dragging
- [x] Up/down arrows should only be visible when hovering over a language in the left column
- [x] Line height is too small. Need more vertical space between lines
- [x] Checkmarks should not appear in the left column. They should appear in the right column next to languages that have been selected.
- [x] The overall height of the dialog is too big
- [x] Vertical spacing above and below the reset button is not even

additional visual/spec details attached 

[BUG-29c_Preferred_Website_Languages_001(1).pdf](https://github.com/MozillaReality/FirefoxReality/files/3474667/BUG-29c_Preferred_Website_Languages_001.1.pdf)

**Comment by keianhzo** [comment]
@jvonitter @thenadj A few notes on the above:
- We have reused the same scrollbar style as we are using in the rest of the app. Do we want to use a specific style for the scroll bars in this dialog?
- The scrollbar movement is also the same as in the rest of the app, I'd leave it as it currently is in the rest of the app or change across the app.

APK for testing: https://send.firefox.com/download/817ffbca73be608a/#d8TTW99vNzKnCvJ80g9C2g

**Comment by jvonitter** [comment]
Leave it as is for now but we may address it in the future. Thanks @keianhzo!
