### ISSUE TITLE
Vulkan support

### ISSUE THREAD

**Issue by kennardconsulting** [MozillaReality/FirefoxReality#1531]
**Is your feature request related to a problem? Please describe.**
Performance in WebVR is critical to comfort.

**Describe the solution you'd like**
Apparently the Vulkan API offers closer access to the hardware. Is Firefox Reality considering supporting Vulkan to improve WebVR performance?

**Comment by philip-lamb** [comment]
We don't have plans for immediate support for Vulkan in the project, but graphics APIs are always an area of focus. Thanks for logging this, and we'll keep it on Ice for future reference.

**Comment by philip-lamb** [comment]
There has been some recent discussion around WebGPU and we would likely implement WebGPU with Vulkan as the underlying implementation rather than direct Vulkan support. Closing for now.
