### ISSUE TITLE
Revise language selection strings to not have CDATA in the middle

### ISSUE THREAD

**Issue by Pike** [MozillaReality/FirefoxReality#1534]
The strings added in #1474 are not supported by the l10n toolchain.

`CDATA` is fine, but it needs to span the complete string, not just a part of it as in these strings.

Can you please revise those strings? No ID change necessary.

CC @Delphine @keianhzo

**Comment by Delphine** [comment]
Seems like we have https://github.com/mozilla-l10n/android-l10n/pull/62/commits/f203c93f31249a6ecb66405dbf4d1c8764f654c9 but still waiting on a commit for this.
Just a friendly reminder in case :D (cc @keianhzo)
