### ISSUE TITLE
FxR fails to enter VR

### ISSUE THREAD

**Issue by joshmarinacci** [MozillaReality/FirefoxReality#1543]
## Hardware
Oculus Quest with today's build of FxR 1.4

## Steps to Reproduce
1.  go to this page: https://vr.josh.earth/jinglesmash-ecs/
2. click button to play the game in VR

## Current Behavior

The screen shows the spinning rings forever instead of entering VR. 

## Expected Behavior

The game should enter VR.

## Context

This is one of our test apps. It works correctly in FxR 1.3 and Oculus Browser, but fails in today's build of FxR 1.4.

## Error Logs and Stack Traces
The console shows this error inside of threeJS:

TypeError: array is null
three.module.js:2300:3
    fromArray https://vr.josh.earth/jinglesmash-ecs/node_modules/three/build/three.module.js:2300
    getCamera https://vr.josh.earth/jinglesmash-ecs/node_modules/three/build/three.module.js:22668
    render https://vr.josh.earth/jinglesmash-ecs/node_modules/three/build/three.module.js:24187
    setupGame https://vr.josh.earth/jinglesmash-ecs/game.js:190
    onAnimationFrame https://vr.josh.earth/jinglesmash-ecs/node_modules/three/build/three.module.js:15190

<details open>

```
```

</details>

**Comment by philip-lamb** [comment]
@joshmarinacci Can you reproduce with latest built from https://github.taskcluster.net/v1/repository/MozillaReality/FirefoxReality/master/latest? If so, we'll try to reproduce on other devices.

**Comment by bluemarvin** [comment]
Immersive mode is broke in latest builds until https://bugzilla.mozilla.org/show_bug.cgi?id=1574218 lands in Gecko.

**Comment by philip-lamb** [comment]
Related to #1564

**Comment by MortimerGoro** [comment]
I think this is a different issue from https://github.com/MozillaReality/FirefoxReality/issues/1564, I'll look into it.

**Comment by MortimerGoro** [comment]
Gecko fix ready here! https://bugzilla.mozilla.org/show_bug.cgi?id=1574996
