### ISSUE TITLE
Private browsing window fails to be recreated on resume

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1544]
## Hardware

Oculus
## Steps to Reproduce

1. Launch FxR
2. Switch to private browsing
3. Pause FxR by pressing oculus home button.
4. Resume FxR

## Current Behavior

The private browsing screen fails to be displayed
![Screen_Shot_1908083702](https://user-images.githubusercontent.com/3066/62725847-c4ee6180-b9ca-11e9-9ffe-ef8295e94e8f.png)

## Possible Solution

The private browsing screen should be displayed.

**Comment by keianhzo** [comment]
@bluemarvin I've added a few commits to https://github.com/MozillaReality/FirefoxReality/pull/1554 that should fix this
