### ISSUE TITLE
Hubs fails to enter immersive mode on first try

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1559]
## Hardware

All
## Steps to Reproduce

1. Go to hubs and enter a room

## Current Behavior

Stuck at the FxR spinner. Pressing back button and then pressing `Enter VR` button on the page allows FxR to enter immersive mode.

## Expected Behavior

FxR should enter immersive mode on the first try. I tested this on 1.3 and was able to enter immersive mode one the first try so it would seem something may have changed that causes the VR RaF to never start.

**Comment by kwadroke** [comment]
I've seen a similar issue like this on the Oculus Browser on the Quest lately too. Sometimes when it switches to immersive mode, I get the Oculus Browser spinner. If I back out and try again, it usually works. Had this problem last night during the M3 chat.
I'm wondering if this is a Hubs issue and not just FxR.

**Comment by larsbergstrom** [comment]
I just went to the Hubs meetup today and was never able to enter it on the Vive Focus Plus, but was able to immediately enter on the Quest. Other WebVR experiences worked fine on the Vive Focus Plus.

**Comment by bluemarvin** [comment]
I just tested Hubs with the [current](https://tools.taskcluster.net/groups/T4F6iJQcTvqF7ZC150_riA/tasks/T4F6iJQcTvqF7ZC150_riA/runs/0/artifacts) FxR on Focus Plus that includes @MortimerGoro 's fix for immersive mode and I see the same behavior as I do on the Quest. The first attempt to enter immersive mode fails, but pressing the back button and then entering a second time works. I'll turn on logging and see if there are any JavaScript errors. If there is an unhandled error in hubs, that could prevent the immersive from starting.

**Comment by bluemarvin** [comment]
Here is the log, I think it might be a Javascript error.
First try:
```08-16 13:11:05.365  4212  4240 D GeckoViewProgress: onLocationChange: location=https://hubs.mozilla.com/b9GZtyP/nutritious-acclaimed-roundtable, flags=0x1
08-16 13:11:05.366  4212  4240 D GeckoViewProgress[C]: onLocationChange: location=https://hubs.mozilla.com/b9GZtyP/nutritious-acclaimed-roundtable, flags=0x1
08-16 13:11:05.366  4212  4240 D GeckoViewProgress[C]: ProgressTracker changeLocation https://hubs.mozilla.com/b9GZtyP/nutritious-acclaimed-roundtable
08-16 13:11:05.366  4212  4240 D GeckoViewNavigation: onLocationChange
08-16 13:11:05.449  4212  4240 E GeckoConsole: [JavaScript Error: "TypeError: e is null" {file: "https://assets-prod.reticulum.io/hubs/assets/js/engine-919307e6a33f255e7a9a.js" line: 1}]
08-16 13:11:05.449  4212  4240 E GeckoConsole: fromArray@https://assets-prod.reticulum.io/hubs/assets/js/engine-919307e6a33f255e7a9a.js:1:338498
08-16 13:11:05.449  4212  4240 E GeckoConsole: Io/this.getCamera@https://assets-prod.reticulum.io/hubs/assets/js/engine-919307e6a33f255e7a9a.js:1:643827
08-16 13:11:05.449  4212  4240 E GeckoConsole: Ho/this.render@https://assets-prod.reticulum.io/hubs/assets/js/engine-919307e6a33f255e7a9a.js:1:669525
08-16 13:11:05.449  4212  4240 E GeckoConsole: value@https://assets-prod.reticulum.io/hubs/assets/js/engine-919307e6a33f255e7a9a.js:1:75490
08-16 13:11:05.449  4212  4240 E GeckoConsole: Ho/<@https://assets-prod.reticulum.io/hubs/assets/js/engine-919307e6a33f255e7a9a.js:1:669188
08-16 13:11:05.449  4212  4240 E GeckoConsole: i@https://assets-prod.reticulum.io/hubs/assets/js/engine-919307e6a33f255e7a9a.js:1:494655
08-16 13:11:05.449  4212  4240 E GeckoConsole: i@https://assets-prod.reticulum.io/hubs/assets/js/vendor-538313eeb21f9716bf68.js:487:96837
08-16 13:11:05.458  4212  4240 E GeckoConsole: [JavaScript Error: "TypeError: e is null" {file: "https://assets-prod.reticulum.io/hubs/assets/js/engine-919307e6a33f255e7a9a.js" line: 1}]
08-16 13:11:05.458  4212  4240 E GeckoConsole: fromArray@https://assets-prod.reticulum.io/hubs/assets/js/engine-919307e6a33f255e7a9a.js:1:345939
08-16 13:11:05.458  4212  4240 E GeckoConsole: Io/this.getCamera@https://assets-prod.reticulum.io/hubs/assets/js/engine-919307e6a33f255e7a9a.js:1:643927
08-16 13:11:05.458  4212  4240 E GeckoConsole: Ho/this.render@https://assets-prod.reticulum.io/hubs/assets/js/engine-919307e6a33f255e7a9a.js:1:669525
08-16 13:11:05.458  4212  4240 E GeckoConsole: value@https://assets-prod.reticulum.io/hubs/assets/js/engine-919307e6a33f255e7a9a.js:1:75490
08-16 13:11:05.458  4212  4240 E GeckoConsole: i@https://assets-prod.reticulum.io/hubs/assets/js/engine-919307e6a33f255e7a9a.js:1:494655
```
And then the log from the successful entry:
```
08-16 13:11:32.358  4212  4240 D GeckoViewContent[C]: handleEvent: focusin
08-16 13:11:32.435  4212  4240 W GeckoConsole: [JavaScript Warning: "Error: WebGL warning: drawElements: Drawing to a destination rect smaller than the viewport rect. (This warning will only be given once)" {file: "https://assets-prod.reticulum.io/hubs/assets/js/engine-919307e6a33f255e7a9a.js" line: 1}]
```

**Comment by jvonitter** [comment]
cc @Misslivirose

**Comment by gfodor** [comment]
thanks for digging, that's a three.js call stack inside of WebVRManager

**Comment by gfodor** [comment]
if those line offsets are right (and they look right) this is the call. it's very odd, it looks like `pose.orientation` passes a null check and yet when its received by `fromArrays` it's null. the babel-ified code has `e` as the binding for the first argument for `fromArrays`, so I think that's what's null when it tries to index into it in `fromArrays` as an array.

https://github.com/mrdoob/three.js/blob/dev/src/renderers/webvr/WebVRManager.js#L301

**Comment by bluemarvin** [comment]
This very well could be a bug in FxR. When I try with FxR 1.3 I don't see the issue and the WebVR code in Gecko is getting refactored to support WebXR so it is possible something broke.

**Comment by gfodor** [comment]
are there any scenarios where the underlying data structures backing `pose` could null out the `orientation`? it seems very unlikely to be hit since it's just statement after the null check (in the babel-ified code, it's several statements)

**Comment by MortimerGoro** [comment]
I think it's related to https://bugzilla.mozilla.org/show_bug.cgi?id=1569605, I'm looking into it

**Comment by MortimerGoro** [comment]
Gecko fix ready here! https://bugzilla.mozilla.org/show_bug.cgi?id=1574996

**Comment by gfodor** [comment]
awesome, thanks for investigating!
