### ISSUE TITLE
Controller pointer not visible in private mode

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#156]
When in private mode the controller pointer and ray can't be seen outside the browser window. If you want' to click on a tray option you can't see where you are pointing at.

**Comment by keianhzo** [comment]
Check if it's still an issue with the Android UI try

**Comment by keianhzo** [comment]
@nancyhang I've tried this with the new Tray and now you can see the pointer in the tray but it's still an issue when you point outside any UI, you just can't see the pointer. Maybe @thenadj should take a look at it to redesign. Probably related to #196

**Comment by MortimerGoro** [comment]
I think that we can just avoid tinting the controller related geometries to fix this

**Comment by thenadj** [comment]
yes, we're addressing this in bug 196. We are designing a new pointer.
