### ISSUE TITLE
Wrong URL show for default private browsing window.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1561]
## Steps to Reproduce

1. Launch FxR
2. Switch to Private Browsing
3. Switch back to non-Private Browsing
4. Switch back to Private Browsing

## Current Behavior

The URL is incorrect. It shows the unlocked padlock and has a `data:` URL:
![image](https://user-images.githubusercontent.com/3066/62887330-dcdb2380-bcf1-11e9-9701-f10ae61ce6b6.png)

## Expected Behavior

The URL should not show the unlocked padlock and should say `Search the Web or enter address`

**Comment by keianhzo** [comment]
@bluemarvin I've added commits to #1554 that should fix this.
