### ISSUE TITLE
No browser window on resume

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1565]
## Hardware

Go
## Steps to Reproduce

1. Launch FxR
2. Press back button on controller
3. Select exit from oculus menu
4. launch FxR

## Current Behavior

No browser window is visible.
![Screen_Shot_1908130651](https://user-images.githubusercontent.com/3066/62980677-1425ff00-bddc-11e9-9d27-78531dcdce6e.png)

## Expected Behavior

Browser window should be visible.

Should the user be able to quit FxR on Oculus by pressing the back button on the controller? I can't remember what platforms it is expected. I thought it wasn't supported on Oculus?

**Comment by keianhzo** [comment]
@bluemarvin In Oculus it was always possible to quit pressing the back button as long as there are not any stacked sessions and you cann't go back in history any more, otherwise you just remove the stacked session or navigate back.

I think this might be related to #1544

**Comment by keianhzo** [comment]
@bluemarvin this should be fixed after https://github.com/MozillaReality/FirefoxReality/pull/1598

**Comment by bluemarvin** [comment]
Works in current master.
