### ISSUE TITLE
Scrollbars in setting's dialogs are not draggable

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1567]
## Hardware

Go
## Steps to Reproduce

1. open settings dialog
2. open env dialog
3. try to drag the scrollbar

## Current Behavior

The scroll bar cannot be dragged.
## Expected Behavior

scroll bar should be draggable.

**Comment by philip-lamb** [comment]
AFAICT the scroll bars have never been draggable. In 1.3 the voice search language and environments settings pane both have scrollbars. See #317 and item 4 in #1530.

**Comment by jvonitter** [comment]
this is covered by those other two bugs, so we'll use those to track. closing this as a duplicate.
