### ISSUE TITLE
Gear VR Touchpad Support

### ISSUE THREAD

**Issue by ScottWitte** [MozillaReality/FirefoxReality#1578]
**Is your feature request related to a problem? Please describe.**
The primary reason we use Gear VR headsets is that you don't need a separate, easy to lose controller to interact with our web apps. Why is FxR the only browser that requires a Gear VR controller and ignores the touchpad?

**Describe the solution you'd like**
Use the Touchpad for Gear VR (as well as the separate controller).

**Describe alternatives you've considered**
Use another browser, but FxR is rapidly becoming the best solution for our needs (eg at trade shows). It is SO clean and much easier to keep users out of trouble.

**Additional context**
By requiring the use of a Gear VR controller and ignoring the touchpad you effectively make FxR useless on all but the last generation of Gear VR headsets or at least require the purchase of a separate controller just to run FxR. In our case, such as at trade shows or visitor centers, having a separate controller causes problems. The controller is easily lost or misplaced. Keeping the right controller and headset together can be an issue. Keeping headset AND controller charged is one more hassle clients don't want if possible.

**Comment by jvonitter** [comment]
Thanks Scott! We'll keep this in mind for future milestones.

**Comment by cjyjae35** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DE-80 Gaze Mode](https://trello.com/c/vKHoXnV6/488-de-80-gaze-mode)

**Comment by ScottWitte** [comment]
Thanks Jae. Not sure it matters anymore since Gear VR is no longer supported.
