### ISSUE TITLE
androidspeech currently uses cz.msebera.android.httpclient

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1580]
**Is your feature request related to a problem? Please describe.**
The androidspeech library used for voice searches currently uses `cz.msebera.android.httpclient` for it's http client. It would be good to reduce the number of HTTP client stacks in FxR to a number approaching 1.

**Describe the solution you'd like**
Converting androidspeech to use the WebExecutor in GeckoView would allow it to use the same HTTP client as FxR. 

There is this corresponding issue in the androidspeech issues:
https://github.com/mozilla/androidspeech/issues/18

**Comment by bluemarvin** [comment]
I'll see if we can get this done for the code freeze. Worst case we punt it to milestone 6.

**Comment by keianhzo** [comment]
Working on it but the speech proxy doesn't seem to like the GBE request. I'm working with @andrenatal on debugging this.

**Comment by jvonitter** [comment]
@andrenatal @keianhzo - think this will get unblocked/finished before fxr8 freeze on Tuesday? or should we push it out?
