### ISSUE TITLE
Add support for tabs inside windows

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1583]
Flow: Opening a tab https://trello.com/c/LxRAeKpK/447-uf-90-open-new-tabs
Flow: Select, multi-select, close tabs https://trello.com/c/kWiCIMsP/423-uf-86-tabs-in-fxr

**Comment by jvonitter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UIS-59 Tabs](https://trello.com/c/bD4mkmpj/475-uis-59-tabs)

**Comment by jvonitter** [comment]
@MortimerGoro now that the spec is done, can you do a visual pass on the UI to make it match the design? There's a bit of polish work needed there - in particular I noticed that the tabs panel is not positioned correctly. It should be in front of the windows, similar to the settings dialog.

**Comment by jvonitter** [comment]
@MortimerGoro Updates to the tray icons in https://trello.com/c/ENtbk8O4/352-uis-73-tray-with-library-buttons
What's new: better tabs icon. keeping the + for new window

**Comment by jvonitter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UIS-73 Tray with Library Buttons](https://trello.com/c/ENtbk8O4/352-uis-73-tray-with-library-buttons)

**Comment by MortimerGoro** [comment]
Closed via #2028
