### ISSUE TITLE
Enable multi-select on tabs

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1585]
So actions can be taken on more than one tab at a time. Related to #1584
Flow: https://trello.com/c/kWiCIMsP/423-uf-86-tabs-in-fxr

**Comment by jvonitter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UIS-59 Tabs](https://trello.com/c/bD4mkmpj/475-uis-59-tabs)

**Comment by MortimerGoro** [comment]
Closed via #2028
