### ISSUE TITLE
Enable advanced actions on tabs

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1586]
Advanced actions include mute tab, pin tab, duplicate tab

**Comment by jvonitter** [comment]
depends on #1584

**Comment by TssT16** [comment]
So this means also that you have multiple tabs open around you?

**Comment by jvonitter** [comment]
@TssT16 we're shipping the ability to have multiple windows in our upcoming 1.4 release. we'll be enabling tabs after that, so you'll be able to have more than one tab in a window. 
Does this answer your question?

**Comment by TssT16** [comment]
@jvonitter When you can see all the windows ones, than yes. Thanks :)
