### ISSUE TITLE
Enable manual account sync

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1587]
Users will be able to manually sync library content (bookmarks, history) from within those views. 

Flow - https://trello.com/c/UiK5H7cG/420-uf-83-sync-account
Spec - [History](https://trello.com/c/CPyXxcZp/371-uis-78-history) & [Bookmarks](https://trello.com/c/jBtMLMKO/234-uis-62-bookmarks)

**Comment by jvonitter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UIS-78 History](https://trello.com/c/CPyXxcZp/371-uis-78-history)

**Comment by jvonitter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UIS-62 Bookmarks](https://trello.com/c/jBtMLMKO/234-uis-62-bookmarks)

**Comment by jvonitter** [comment]
History and bookmarks both get a button in the upper right corner with a few different states. Design is ready to go!

**Comment by keianhzo** [comment]
I've updated the FxA PR with this.
