### ISSUE TITLE
Show signed in/out status in UI

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1588]
Users will see a tile in the Settings menu that prompts them to sign in (if signed out) or manage their account (if signed in).

Overview - https://trello.com/c/j8eAOiyY/419-de-63-account-settings
Spec - [UIS-16](https://trello.com/c/P52DGGmp/88-uis-16-settings)

**Comment by keianhzo** [comment]
This should have been closed by https://github.com/MozillaReality/FirefoxReality/pull/1973
