### ISSUE TITLE
Add 'Account Settings' section to settings

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1589]
Users can see identifying information about their account (username, email and account picture) manage sync settings and sign in/out.

Spec [UIS-16](https://trello.com/c/P52DGGmp/88-uis-16-settings)

See also #1588

**Comment by jvonitter** [comment]
related to #1398

**Comment by keianhzo** [comment]
@jvonitter @thenadj We need a default icon for the settings account button when the user is logged out.

**Comment by jvonitter** [comment]
Icon has been added here https://drive.google.com/open?id=1xQlhISlSZv_3eXPWJQN7DUhkJX1ct9XT
