### ISSUE TITLE
New Languages - Swedish, Dutch, Finnish, Danish, Norwegian and Polish

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1594]
New locales are complete (see https://bugzilla.mozilla.org/show_bug.cgi?id=1566664)

When we get new strings merged, we can close this. 
Once they're on, QA should check that the languages show up as options and that app text changes to the selected language (at least as much as you can tell between the languages)

**Comment by jvonitter** [comment]
@MortimerGoro @keianhzo @bluemarvin If we don't need to do anything for this, please close!

**Comment by jvonitter** [comment]
Update: we dont need to do anything except wait for the PR

**Comment by bluemarvin** [comment]
The new languages will need to be added to the `Firefox Display Language` settings dialog.

**Comment by keianhzo** [comment]
@Pike @Delphine I guess we should get a PR from you in the FxR repo adding this new languages right? If that's the case I'll review it then and add the support for them in the Display languages setting.

**Comment by jvonitter** [comment]
@keianhzo I think we also need to check that the keyboards are correct for the new languages. I know some of them have special characters...

**Comment by jvonitter** [comment]
Also update: https://github.com/MozillaReality/FirefoxReality/wiki/Localizing-Firefox-Reality

**Comment by jvonitter** [comment]
@thenadj is investigating what (if anything) needs to change about the keyboards. please make a new ticket for each keyboard that needs to be updated.

**Comment by jvonitter** [comment]
needs #1750 needs #1751 needs #1752 needs #1753 needs #1754 needs #1755 needs
