### ISSUE TITLE
Need a way to bypass failing SSL certificates

### ISSUE THREAD

**Issue by gfodor** [MozillaReality/FirefoxReality#1595]
**Is your feature request related to a problem? Please describe.**
To help debug and fix issues with Hubs, its necessary to be able to hit a local webserver running the app. Right now, you can't bypass a failing SSL certificate in Firefox Reality, so it's not possible to test WebVR apps running on your local LAN on an IP address.

**Describe the solution you'd like**
A way in developer options to enable a SSL certificate bypass, similar to desktop Firefox.

**Describe alternatives you've considered**
There might be a way to get DNS working so I can get a SSL cert working on my LAN, but seems like the wrong solution to the problem.

**Comment by bluemarvin** [comment]
Unfortunately there isn't currently a way to do this due to limitations in the GeckoView API. I've asked and it isn't really even on the road map. I can probably get it onto the road map but even then it probably won't be done any time soon.

**Comment by gfodor** [comment]
Ah OK. Any suggestions on how to work around this at the OS/adb level? I can do some investigation but I suspect I won't be able to do much since I can't root the device. The only thing I can think of is a custom FxR build with an additional root cert.

**Comment by bluemarvin** [comment]
I'm filing a bug against GeckoView in bugzilla to get things started and I can query if there are any hacks we might employ to work around it such as  pref we can set.

**Comment by bluemarvin** [comment]
Here is the bug in bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1574640
@gfodor So this might be a solution that will work for you.
You can use `adb reverse` to make a server running on you host PC look like it is a localhost on the device.
For example I started a web server on my PC on port 8000. I then ran:
```
adb reverse tcp:8000 tcp:8000
```
Then from FxR on my phone I was able to load the url `http://localhost:8000/index.html`
I was told localhost is consider secure in Gecko.

**Comment by gfodor** [comment]
ah great trick, thanks! no need to push on this if that's a simple workaround.

**Comment by gfodor** [comment]
hmm, this doesn't seem to work for me -- i still get blocked on "secure connection failed" when trying to access over SSL

**Comment by bluemarvin** [comment]
I think the key is to not use https?

**Comment by gfodor** [comment]
Yup, I ended up backing out of using http -- that's a sufficient workaround for now. Thanks!

**Comment by philip-lamb** [comment]
Tracking bug for Fenix (target Q1 fix) https://bugzilla.mozilla.org/show_bug.cgi?id=1553265

**Comment by keianhzo** [comment]
This has already been closed by https://github.com/MozillaReality/FirefoxReality/pull/2530
