### ISSUE TITLE
Error running on pixel 2

### ISSUE THREAD

**Issue by andrenatal** [MozillaReality/FirefoxReality#16]
I followed the instructions and built the project successfully, but when tried to run on my pixel 2, got the error: `Device supports, but APK only supports armeavi-v7a`

**Comment by andrenatal** [comment]
Yes: `gvr-android-sdk`

**Comment by bluemarvin** [comment]
We now have taskcluster builds of the GVR version. I've seen similar issues when there were adb versioning issues.
