### ISSUE TITLE
MediaRecorder camera in Hubs no longer working

### ISSUE THREAD

**Issue by gfodor** [MozillaReality/FirefoxReality#1604]
## Configuration

Firefox Reality version: 1.3
Firefox Reality build ID: 9000adc

Oculus Quest

## Steps to Reproduce
1. Create a new room at hubs.mozilla.com
2. Open the camera tool and create a video
3. The video creation fails

## Current Behavior
We currently use the MediaRecorder API to record frames blitted over to a HTML canvas into a video for the user. The relevant code is here: https://github.com/mozilla/hubs/blob/master/src/components/camera-tool.js

Once I was able to debug a bit, what it looks like is that the `ondataavailable` callback from the recorder is now yielding small (200 byte) chunks, vs blobs of encoded video content. This code works on Oculus Browser, and used to work in Firefox Reality. I don't think this code has changed since the last time I saw it working in FxR, but can't be completely sure. Unfortunately, trying the simple MDN examples of recording work fine. I can confirm the incoming texture we are rendering to is valid, since that's visible in the camera viewfinder -- I also was able to rule out the blit operation we do with WebGL2 to flip + scale the texture by removing it. So it seems like something is going on with the recorder either failing to read the data (and encoding an empty/black video) or something causing the encoded stream to fail to write out.

## Expected Behavior
Chunks should be yielded on `ondataavailable` of significant size, and a video should spawn in the room.

```
```

</details>

**Comment by bluemarvin** [comment]
The MediaRecorder seems to work fine in hubs and FxR as long as FxR isn't in immersive mode. I've relayed some questions to the media team to try and figure out the cause.

**Comment by bluemarvin** [comment]
I've gone back far as FxR 1.2 and the MediaRecorder does not appear to work so I don't think this is a very recent regression. I'm discussing the issue with media team in an attempt to root cause it.

**Comment by gfodor** [comment]
Interesting, I know I had the video camera working at some point because for a while it was a differentiator vs Oculus Browser (which had bugs with it as well.)

**Comment by bluemarvin** [comment]
Found the breaking commit https://bugzilla.mozilla.org/show_bug.cgi?id=1537967

**Comment by bluemarvin** [comment]
I have found a fix. Working with layout team to get it right.

**Comment by bluemarvin** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1575694

**Comment by bluemarvin** [comment]
This will require a GeckoView version bump once it lands.
