### ISSUE TITLE
Unable to refresh page in Hubs after using (broken) video camera

### ISSUE THREAD

**Issue by gfodor** [MozillaReality/FirefoxReality#1605]
## Configuration

Firefox Reality version: 1.3
Firefox Reality build ID: 9000adc

Oculus Quest

## Steps to Reproduce

1. Create a new room in hubs.mozilla.com
2. Spawn the camera and take a 3s video (which fails due to https://github.com/MozillaReality/FirefoxReality/issues/1604
3. Exit immersive mode and try to reload the page, it will hang

## Current Behavior
Firefox Reality hangs up when trying to refresh the page after using the broken MediaRecorder API. Also, if you force quit from the shell using the oculus button, relaunching the app shows it did not kill the process, so you need to reboot your headset.

## Expected Behavior
Page reloads should always work.

```
```

</details>

**Comment by bluemarvin** [comment]
I was able to record media with 1.4 and go in and out of immersive mode. If possible could you retest with 1.4 staging builds?  I used:

https://queue.taskcluster.net/v1/task/A7Vb1yiySAOJTopgkF-Dgw/runs/0/artifacts/public/FirefoxReality-1.4-32321428-oculusvr-arm64-staging-signed-aligned.apk

On thing I did notice is that the hud would disappear and was not visible in immersive mode. However if I exited immersive mode it was visible and I was able to click the camera then go back into immersive mode and take pictures and video. The only way to make the camera go away was exit immersive mode and use the hud out side of immersive mode.

**Comment by gfodor** [comment]
Ah great, thank you. I will test on an updated build.

**Comment by bluemarvin** [comment]
The linked staging build does still contain the failure to enter immersive mode on first try. Hopefully that fix will land in the next few days.

**Comment by gfodor** [comment]
strange, not working for me. I also see the disappearing HUD issue (have not seen that before, so seems likely to be some kind of FxR-level regression, but can't be sure until debugging further. The media still fails to spawn, though I'll have to attach a debugger to check if it's emitting the 200 byte files like I saw in 1.3. you're clicking the 3s record button at the bottom of the camera right?

**Comment by bluemarvin** [comment]
It's possible I didn't understand what I was testing. I found the camera control very confusing.

**Comment by gfodor** [comment]
Sorry about that. If you create the camera using the right hand side button in the HUD (in 2d as you mentioned b/c of the other issue) then the 3D camera pops up. It has a "take photo" button at the top, and a "take video" button at the bottom (with a 3 over it, since it's a 3 second duration video.) Click the bottom button and then there is a 3 second countdown timer, and a 3 second video recording that will occur. Once that completes you should hear a loading sound, but no video will appear, it'll just keep loading. (In a working build, it can take 20-30 seconds to spawn a video if our AWS lambdas are cold, which is usually the case given the low usage of the feature in absolute terms)

**Comment by bluemarvin** [comment]
Okay, yes, I see the issue of the video never showing up after recording. But I am able to exit and reload the page I believe. I will investigate the recorded video not showing up to see if I can see anything in the logs to give a clue.

**Comment by gfodor** [comment]
great thanks!

**Comment by bluemarvin** [comment]
The video shows up and plays in GeckoView_example. This suggest there is something about immersive mode that is breaking this. I noticed I can't test the camera except in immersive mode. I would like to verify that the camera would work when not in immersive mode in FxR.

**Comment by bluemarvin** [comment]
After changing FxR to a mobile UA, the camera video tool works. So immersive mode seems to break the media recorder.

**Comment by bluemarvin** [comment]
I also suspect the hang/failure to reload is from a stuck script.

**Comment by philip-lamb** [comment]
The fix for failure to enter immersive mode is now landed, so it'd be good to test this again.

**Comment by jvonitter** [comment]
@gfodor can you give it a try and let us know if it still happens?

**Comment by gfodor** [comment]
yup will check this out tonight/tomorrow. thanks for the fix!

**Comment by gfodor** [comment]
fix is confirmed, looks great!
