### ISSUE TITLE
Tabs telemetry

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1609]
- [x] number of users who open a new tab ever (not including receiving a tab)
- [x] of users who open a new tab, average number of tabs opened/session
- [x] of users who open a new tab, average number of activated/session
- [x] open tabs per session
- [x] number of new tabs explicitly opened per session
- [x] percentage of new tabs opened via long press vs tab dialog per session
----------

- [x] Do data review
- [x] Implement telemetry

**Comment by jvonitter** [comment]
cc @daoshengmu

**Comment by daoshengmu** [comment]
Because it would like to collect data by sessions, it is blocked by #2241.
