### ISSUE TITLE
The size of the browser window is wrongly changed to 2x size after resizing in fullscreen mode

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1614]
**[Affected Versions]:**
- Firefox Reality 1.4-32322148 (21.08.2019) 

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The dimensions of the window is set to 0.5x size.

**[Steps to reproduce]:**
1. Navigate to the following webpage: "https://permission.site/".
2. Click the "Fullscreen" button on the page. (if necessary scroll down the page to find the button.)
3. I fullscreen mode resize the window to 0.5x size.
4. Click the back button on the fullscreen controls.
5. Observe the size of the window.

**[Expected results]:**
- The size of the browser window is the same as before entering fullscreen mode.

**[Actual results]:**
- The size of the browser window is changed to 2x size.

**[Notes]:**
- The issue is reproducible with any resize dimension in fullscreen mode.
- The issue is reproducible with just entering and exiting resize mode while in fullscreen mode.
- the issue is not reproducible if the size of the browser window is equal or bigger than 2x size. 
- Attached a screen recording of the issue: [link](https://drive.google.com/file/d/1gCUq3C5PnEI8mFJXXeY5K7srFhWpJYRY/view?usp=sharing)

**Comment by MortimerGoro** [comment]
I think this is expected behavior. cc @jvonitter should the regular and fullscreen sizes be separated? Example of use case: I open a fullscreen video on youtube, optionally adjust to a different size and then go back to the default navigation size.

**Comment by jvonitter** [comment]
@thenadj Can you check this out?

**Comment by MortimerGoro** [comment]
`It appears that the size in the default window only changes if the user resizes the window in fullscreen mode and then goes back. If they just enter fullscreen mode and then return, the window remains the same size.`

That's the problem. I misunderstood something while reading the issue first time. Fix ready here:  #1690

@bluemarvin can you file a different issue for the aspect ratio concerns?

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.4-32402232 installed on the Oculus Go, Oculus Quest and HTC Vive Focus Plus headsets. 
Now, the size of the browser window remains unchanged after resizing in fullscreen mode.
