### ISSUE TITLE
The multiwindows are overlapping when their position is switched after restoring the app 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1615]
**[Affected Versions]:**
- Firefox Reality 1.4-32322148 (08.20.2019)

**[Affected Platforms]:**
- Oculus Pacific - Android 7.1.2 (Oculus Go)
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- Have the latest Firefox Reality 1.4 - 32122206 (07.30.2019) apk. installed.
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**
1. Open 1 or 2 new windows using the "+" button from the tray.
2. Quit and restore the app.
3. Move the position of the windows displayed by clicking the actionable "<" or ">" buttons.
4. Observe the behavior.

**[Expected results]:**
- The windows position is switched and they are rendered correctly.

**[Actual results]:**
- The windows position is switched but they are overlapping.

**[Notes]:**
- I was not able to reproduce this issue on HTC Vive Focus Plus.
- The windows are rendered correctly after one of the windows is closed or if a new window is opened (if only 2 are opened).
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1-PFvXlB-O3_MZUceEggA5RJsVYyc6y1l)

**Comment by keianhzo** [comment]
@Softvision-RemusDranca this should be fixed after https://github.com/MozillaReality/FirefoxReality/pull/1624 Could you please verify & close is it's so?

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the 1.4-32332324 (08.21.2019) apk. version.
Tested on Oculus Pacific (Oculus Go) and Oculus Quest.
I will close this issue as verified-fixed.
