### ISSUE TITLE
Navigation unresponsive after trying to run https://voxels.glitch.me/ on Oculus Quest. Persists on app restart.

### ISSUE THREAD

**Issue by kettle11** [MozillaReality/FirefoxReality#1625]
Firefox Reality version: 1.3
Firefox Reality build ID: 2019-07-17

Hardware: Oculus Quest

## Steps to Reproduce
1. Navigate to https://voxels.glitch.me/
2. Press "Enter VR"
3. Press back to get away from the page
3. Attempt to further navigate.

## Current Behavior
After viewing the demo and pressing back I cannot navigate forward, back, home, or by typing a URL. Pressing "report an issue" does not work as well.

This behavior persists across app restarts, however I was able to escape it by restarting the Oculus Quest.

I have reproduced this twice in a row.

## Expected Behavior
Navigation is possible.

https://voxels.glitch.me/ does run on the built in Oculus Quest browser without a similar issue.

```
```

**Comment by philip-lamb** [comment]
We need to test this against the performance monitor introduced in 1.4.

**Comment by kettle11** [comment]
I wanted to clarify some of the wording from my initial report:

When I said that this behavior "persists across app restarts" I meant Firefox Reality, not restarting the web app.

Following the repro steps above gets Firefox Reality in a permanently unusable state until you power cycle the Oculus Quest.

**Comment by bluemarvin** [comment]
Unfortunately quitting FxR on the Quest doesn't actually quit the app. There is no good way to force an app to quit except with adb: `adb shell am force-stop org.mozilla.vrbrowser`. Launching other applications can cause memory pressure to cause background applications to quit. What you are probably encountering is a hung javascript in the page. I think the hang detector may be broken in the version of GeckoView we are using. I know it is being worked on and hopefully we will be able to address hung (hanged?) scripts better in the near future.

**Comment by jvonitter** [comment]
@bluemarvin when you get a chance, please link the GV ticket here

**Comment by bluemarvin** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1521094
