### ISSUE TITLE
Crash on resume

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1627]
## Configuration

Firefox Reality version: 1.4
Firefox Reality build ID: fe39b275e69c5621c5e1e0ca3c8b730245a34545

Hardware: NoAPI

## Steps to Reproduce

1. Resume FxR

## Current Behavior

Intermittent crash.
## Expected Behavior

FxR shouldn't crash on resume.
## Possible Solution

Looks like the [PermissionDelegate](https://github.com/MozillaReality/FirefoxReality/blob/fe39b275e69c5621c5e1e0ca3c8b730245a34545/app/src/common/shared/org/mozilla/vrbrowser/browser/PermissionDelegate.java#L165) has a `null` `mContext` when called.

https://crash-stats.mozilla.com/report/index/6246f82e-5713-45f5-a2cf-7d7500190821

**Comment by Softvision-GeluHaiduc** [comment]
I also saw this behavior on the Oculus Go and Quest headsets and was at the point of logging a bug. 
The app crashes intermittently after resuming from a device sleep. I’ve attached a screen recording of the issue [here](https://drive.google.com/file/d/12Fpjkml2MyIuu3qxgYXQLlhYPeZIz9F4/view?usp=sharing).

@bluemarvin Do you think this is related or a separate issue?

**Comment by keianhzo** [comment]
@Softvision-GeluHaiduc Do you have a stacktrace for what you see? They might be different issues

**Comment by Softvision-GeluHaiduc** [comment]
@keianhzo I will try to get a logcat on the crash, but as the issue is happening intermittently it will take some time.

**Comment by Softvision-GeluHaiduc** [comment]
I managed to get a logcat of the issue.
You can find the logcat file [here](https://drive.google.com/file/d/15D1V4YoLtsrkyaw-ydBw_ZvJea5hFyNx/view?usp=sharing).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.4-32400804 installed on the Oculus Go and Quest headset. 
Now, the app doesn't crash on resume.
