### ISSUE TITLE
The hover effect of suggestions from the Awesomebar wrongly overlaps the scrollbar button

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1635]
**[Affected Versions]:**
- Firefox Reality 1.4-32332324 (08.21.2019)

**[Affected Platforms]:**
- Oculus Pacific - Android 7.1.2 (Oculus Go)
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- Have the latest Firefox Reality 1.4-32332324 (08.21.2019) apk. installed.
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**
1. Click the Awesomebar.
2. Write one or two letters so that suggestions are displayed.
3. Hover over the suggestion displayed in front of the scrollbar button.
4. Observe the scrollbar button.

**[Expected results]:**
- The scrollbar button is visible.

**[Actual results]:**
- The hover effect overlaps the scrollbar button and it's no longer visible.

**[Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1qeeLhPjwbeIHjp9pcz9PwY5hAAlxpJAH)

**Comment by MortimerGoro** [comment]
I think this needs some design feedback cc @thenadj

**Comment by keianhzo** [comment]
It seems that at some point the scrollbar style has changed int he specs but it hasn't been updated in the app, I've added a PR with the style update that should fix this issue.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest 1.4-32420004 (RC1) build. 
Tested on Oculus Go, Oculus Quest and HTC Vive Focus Plus, devices.
