### ISSUE TITLE
Use the same cylinder geometry for all borders/widgets

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#1646]
Requires: https://github.com/MozillaReality/vrb/issues/73

I want to reuse a single cylinder geometry for all widgets (on non layers devices) and for all resize/hover borders with layer devices. This will avoid some small delays while creating new cylindrical widgets or borders (e.g. resize, hover)

**Comment by bluemarvin** [comment]
I'm hoping fixing this issue will also fix the jank that happens when creating a new window.

**Comment by bluemarvin** [comment]
This may not actually be feasible. Additionally, the jank was primarily caused by shader compilation which should be fixed by #2773
