### ISSUE TITLE
Daydream exit WebVR using remote controller

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#165]
Currently we use back action to exit from WebVR. Daydream doesn't have a back button in the controller so we need to implement the way to exit WebVR, via the APP button.

**Comment by larsbergstrom** [comment]
Should the menu button also perform back in general in the browser? I noticed that the menu button does not do anything in 2D browsing either.

**Comment by MortimerGoro** [comment]
According to daydrem docs: "App button: This button depends on the app you’re using. For example, it might show menus, pause, go back, or change modes."

So it's a good idea to map that button to the general back action
