### ISSUE TITLE
The windows titles and navigation bar are overlapping when multiple windows are set to the minimum horizontal size

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1672]
**[Affected Versions]:**
- Firefox Reality 1.4-32390648

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Click the resize button on the far right of the navigation bar. 
2. Manually resize the window to the minimum horizontal size.
3. Create a new window by clicking the "+" button from the menu tray.
4. Resize this window to the minimum horizontal size as well.
5. Create a new window and resize it to the minimum horizontal size as well.
6. Observe the window title and the navigation bar.

**[Expected results]:**
- The title for the inactive windows are not overlapping the navigation bar from the active window.

**[Actual results]:**
- The title for the inactive windows and the navigation bar from the active window are overlapping and flickering.

**[Notes]:**
- The navigation bar buttons and the windows titles are not actionable while they are flickering.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1LSj8v3NjqcjjlJl0AnXpKYsddhZ0eXc6/view?usp=sharing).

**Comment by MortimerGoro** [comment]
Fixed in #1666

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.4-32400715 installed on the Oculus Go headset. 
Now, the windows titles and navigation bar are not overlapping when multiple windows are set to the minimum horizontal size.
