### ISSUE TITLE
Add support for 180/360 videos

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#168]

**Comment by MortimerGoro** [comment]
@thenadj We are going to need a design for this. It seems that the 360 video playback options (e.g. in youtube) are not created by the website but by the browser. You can check the UI that Oculus added for youtube.

cc @avrignaud  I think that this should be higher priority because users are going to see this as a failure.

**Comment by avrignaud** [comment]
Yes agree. We need to prioritize video support for 1.0 for a variety of reasons, including content feed support now that that's coming into focus.

@nancyhang can we please put this as P0 for 1.0 launch? And @thenadj we do need a design for video playback for 360 and 180 videos (and likely pictures).

**Comment by thenadj** [comment]
![spinner for link traversal](https://user-images.githubusercontent.com/13240857/43748744-04ed6196-99a6-11e8-9c39-efe43c0eb37b.png)
PNG attached for spinner graphic. @MortimerGoro Please animate it in code to make it look like it's spinning from the center clockwards.

**Comment by thenadj** [comment]
[3D_Spinner.zip](https://github.com/MozillaReality/FirefoxReality/files/2325886/3D_Spinner.zip)
Attached is the 3D Spinner for link traversal. 
@MortimerGoro

**Comment by MortimerGoro** [comment]
@thenadj how should we animate the model? rotation in what angles?

**Comment by MortimerGoro** [comment]
the 3D model is heavy: 50K faces and three 2048K textures

Can I get a lower poly version? cc @keianhzo if you can help with the blender export

**Comment by thenadj** [comment]
@MortimerGoro 
For animation I'd start with vertical axis animation as medium speed. We might add a twist into the animation to make it look more interesting, any way you could add a couple of animations and share so we can pick?

**Comment by MortimerGoro** [comment]
Closing because duplicated: https://github.com/MozillaReality/FirefoxReality/issues/344
