### ISSUE TITLE
Disable ofuscation in release builds

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1683]
**Is your feature request related to a problem? Please describe.**
The stack traces from release builds are obfuscated and that makes them difficult to use. 

**Describe the solution you'd like**
Disable obfuscation on release builds.

**Describe alternatives you've considered**
Uploading trace files for each build would require crash-stats support.

**Additional context**
Obfuscation does not seem to add much value for an open source based application.

**Comment by philip-lamb** [comment]
Agreed. We should disable this.
