### ISSUE TITLE
Set up a stable GeckoView build

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#169]
We are pulling GeckoView dependency from maven nightly. It can change anytime and we can build with different versions depending on gradle cache race conditions.

It would be great to add some version mechanism to GV builds

**Comment by bluemarvin** [comment]
As long as we are on nightly this is going to be a pain point. One thing that we might be able to do is change the gradle maven rule for nightly so it checks every time we build instead of every 24 hours?

**Comment by larsbergstrom** [comment]
We now pin the maven build. Yay!
