### ISSUE TITLE
The hover state of a history log is wrongly kept when you click & hold on a item from the list

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1695]
**[Affected Versions]:**
- Firefox Reality 1.4-32400715 (08.28.2019)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- Have the latest Firefox Reality 1.4-32400715 (08.28.2019) apk. installed.
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**
1. Navigate and bookmark a few websites using the "star" button from the URL search bar.
2. Click the "History" button from the menu tray.
3. Click & hold on an item from the list and move the pointer away from it.
4. Observe the behavior.

**[Expected results]:**
- The hover effect is dismissed and the date is redisplayed.

**[Actual results]:**
- The hover effect is kept and the delete along with the three dot menu button remains displayed. 

**[Notes]:**
- The hover effect is dismissed after the item is once more hovered.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1LihdQzWLSaaJ6cR20XUdkpvgcZPAJUPX)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.4-32481747 RC3 installed on the Oculus Go headset. 
Now, the hover state of a history log is no longer kept when you click & hold on a item from the list.
