### ISSUE TITLE
Windows MR platform 

### ISSUE THREAD

**Issue by pretzer** [MozillaReality/FirefoxReality#17]
Please provide build/target for Windows Mixed Reality platform.

**Comment by larsbergstrom** [comment]
Hi, @pretzer! Firefox Reality is for standalone/mobile headsets today. For desktop WebVR, we'd recommend using Firefox along with Microsoft's SteamVR bridge to Windows MR or the Edge browser.

**Comment by arpu** [comment]
:/  i want to see this in FirefoxReality, so i can use this with linux
