### ISSUE TITLE
Tray should be hidden when settings dialog is shown

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1710]
## Configuration

Firefox Reality version: 1.4
Firefox Reality build ID: 105bd17f0b91f82d0be8c144dddba1daa6cf328f

Hardware: All

## Steps to Reproduce

1. Open Settings Dialog from tray

## Current Behavior

tray is still visible
## Expected Behavior

Tray should be hidden

**Comment by jvonitter** [comment]
For now, it's ok that the tray stays visible. UX will explore whether to turn the tray off during all modal interactions and update the specs accordingly.

**Comment by jvonitter** [comment]
UX decided not to make any changes here. Closing this.
