### ISSUE TITLE
The "Bookmarks" button is no longer in a press state after refocusing the window

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1715]
**[Affected Versions]:**
- Firefox Reality 1.4-32420004 (RC1) build.

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- Have the latest Firefox Reality 1.4-32420004 (RC1) build installed.
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**
1. Click the "Bookmarks" button from the tray menu.
2. Click the "+" button to open a new window.
3. Click the window where the "Bookmarks" page was opened.
4. Observe the "Bookmarks" button.

**[Expected results]:**
- The button is focused.

**[Actual results]:**
- The button is not focused.

**[Notes]:**
- If the "Bookmarks" button is clicked after reproducing this issue, the "Bookmarks" page is successfully closed.
- This issue is not reproducible with the "History" button.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1FK6bt6CJPM2R0OreshI0ONjxchC0_ro-)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.4-32481747 RC3 installed on the Oculus Go headset. 
Now, the "Bookmarks" button is still in a pressed state after refocusing the window.
