### ISSUE TITLE
Support multiple background environments

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#172]
I actually like the space theme a lot and I'd like to use it instead of the meadow.

We need to support a way to change between the multiple available environments

**Comment by avrignaud** [comment]
Thanks Imanol! @larsbergstrom and I are working with @nancyhang to build a bug review process that will allow us to take suggestions like this and prioritize (with design / @thenadj support) in the queue.

**Comment by avrignaud** [comment]
@thenadj - this is a P2. We are ok with a single environment for launch.

**Comment by cvan** [comment]
This has landed in the Developer Options. There are several other issues about selecting third-party assets or uploading custom environments. Can this issue be closed?

**Comment by larsbergstrom** [comment]
Thanks for pointing that out, @cvan! Closing.
