### ISSUE TITLE
[Deutsch] The special characters (ä, ö or ü) are wrongly added in the search bar at long press and no other character can be added from the displayed list

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1733]
**[Affected Versions]:**
- Firefox Reality 1.4-32450938 (RC2)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The language of the on screen keyboard is set to German.

**[Steps to reproduce]:**
1. Click inside the awesomebar so that the keyboard appears.
2. Long press a special character (e.g. ä, ö, ü) and observe the behavior.
3. Click on a character from the list and observe the behavior.

**[Expected results]:**
Step 2: A special character list appears.
Step 3: A special character can be selected to be added in the input field.

**[Actual results]:**
Step 2: The long pressed special character is added in the input field.
Step 3: A list is displayed but the special character selected can not be added to the input field.

**[Notes]:**
- The long press functionality is working as expected for the other characters.
- Attached a screen recording of the issue: [here](https://drive.google.com/file/d/1zGLBffOoi7sJqKGzRlI1ZS68VJz9jHkS/view?usp=sharing).

**Comment by jvonitter** [comment]
@Softvision-GeluHaiduc does this happen with the other keyboards with special characters? or just german?

**Comment by Softvision-GeluHaiduc** [comment]
Only for the german keyboard.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 5-32762123 (93b664b9) installed on the Oculus Go, Quest, HTC Vive Focus, Focus Plus and Lenovo Mirage Solo headsets.
Now, the special characters (ä, ö and ü) are not added in the search bar at long press and other characters can be added from the displayed list.
