### ISSUE TITLE
The selected language is not displayed in the spacebar for the on screen keyboard

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1734]
**[Affected Versions]:**
- Firefox Reality 1.4-32450938 (RC2)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Click inside the awesomebar so that the keyboard appears.
2. Click the Language button (the button with the planet icon from the keyboard).
3. Select a different language and observe the text displayed inside the spacebar

**[Expected results]:**
- The name of the selected language is displayed in the spacebar.

**[Actual results]:**
- The name of the selected language is not displayed in the spacebar.

**[Notes]:**
- Attached a screen recording of the issue: [here](https://drive.google.com/file/d/1_vISBUI5D4PyWHBbggjmcPQ7uQvW-JSu/view?usp=sharing).

**Comment by jvonitter** [comment]
Won't fix this one. Design is updating the spec to reflect current behavior.

**Comment by philip-lamb** [comment]
Adding `worksforme` to reflect that the current behaviour is the desired one.
