### ISSUE TITLE
The vertical separators are not displayed on the tray menu

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1736]
**[Affected Versions]:**
- Firefox Reality 1.4-32450938 (RC2)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on.

**[Steps to reproduce]:**
1. Open the app.
2. Observe the tray menu.

**[Expected results]:**
- Vertical separators are displayed between the "Private Browsing" and "Bookmarks" buttons and between the "Downloads" and "Settings" buttons.

**[Actual results]:**
- No vertical separators are displayed.

**[Notes]:**
- Attached a screen shots of the issue: 
![Capture](https://user-images.githubusercontent.com/40061643/64123978-7c9a4780-cdae-11e9-8b5a-2481df466735.PNG)

**Comment by jvonitter** [comment]
added this as a polish task in https://github.com/MozillaReality/FirefoxReality/issues/1530

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the Firefox Reality version 5-32821846 RC1 (58b59be).
Tested on Oculus Quest and HTC Vive Focus Plus devices.
