### ISSUE TITLE
A check sign is briefly displayed when clicking a language from the "Available Languages" section

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1742]
**[Affected Versions]:**
- Firefox Reality 1.4-32450938 (RC2)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The 1.4-32450938 (RC2) build is installed on the device.
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**
1. Click the "Settings" menu.
2. Click the "Language" card.
3. Click the "Edit" button for the "Preferred Language for displaying Websites:" option.
4. Click on one of the languages displayed in the "Available Languages" section.
5. Observe the behavior.

**[Expected results]:**
- The language is added to the "Preferred Languages" section and the "check" sign remains displayed.
**OR**
- The language is not added to the "Preferred Languages" section and the "check" sign is not displayed.

**[Actual results]:**
- The language is NOT added to the "Preferred Languages" section and the "check" sign is briefly displayed instead of the "+" sign.

**[Notes]:**
- Attached a screen recording of the issue: [link](https://drive.google.com/open?id=1A2ntgGzrnXbjPRHtZ_38myOUc4oWpMMQ)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.4-32481747 RC3 installed on the Oculus Go headset. 
Now, the check sign is not displayed when clicking a language from the "Available Languages" section.
