### ISSUE TITLE
The left or right window is wrongly active in the same time as the center window after switching from normal browsing to PB and vice versa

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1744]
**[Affected Versions]:**
- Firefox Reality 1.4-32450938 (RC2)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The 1.4-32450938 (RC2) build is installed on the device
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**
1. Click the "+" button from the menu tray to open a new window.
2. Click the "Private Browsing" button.
3. Click the "+" button to open a new window in PB.
4. Focus the window on the left and click the "Private Browsing" button.
5. Hover over and click the window on the left displayed in normal browsing.
6. Observe the behavior.

**[Expected results]:**
- The window gains a hover effect an the tray menu moves in front of it.

**[Actual results]:**
- No hover effect is displayed and the tray menu remains displayed in front of the center window.

**[Notes]:**
- This issue is also reproducible if the new window is position on the right side.
- The content of the left/right window is scrollable and clickable.
- The menu tray is moved in front of the right/left window if the title bar is clicked.
- Attached a screen recording of the issue: [link](https://drive.google.com/open?id=1C2-_OEZ7PZ_GY0II08v15GMqOkQGvlrO)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.4-32481747 RC3 installed on the Oculus Go, Quest and HTC Vive Focus Plus headsets. 
Now, the left or right windows are no longer active at the same time as the window in position 2 (center) after switching from normal browsing to PB and vice versa.
