### ISSUE TITLE
Clearing history does not update the forward button.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1749]
## Configuration

Firefox Reality version: 1.4
Firefox Reality build ID: 03c4d09c54bfc736d2ac69f7352bd13e815af626

Hardware: All

## Steps to Reproduce

1. click on a link
2. press back button
3. clear history

## Current Behavior

The forward button is still clickable.
## Expected Behavior

After clearing history, the forward button should not be clickable.

**Comment by bluemarvin** [comment]
Based on the desktop, clearing history should also reset the back button as well.

**Comment by keianhzo** [comment]
@bluemarvin We don't seem to have any control over the GV history so even after wiping out the history from the history storage GV still reports it's internal history list state through CanGoBack CanGoForward. Is there any resort we can use to also clear GV's history?

**Comment by bluemarvin** [comment]
I've created a GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1583265
The temporary solution is to create a new GeckoSession with the URL.

**Comment by keianhzo** [comment]
Opened a new task to update this when the GV API is ready.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 5-32762123 (93b664b9) installed on the Oculus Go, Quest, HTC Vive Focus, Focus Plus and Lenovo Mirage Solo headsets.
Now, clearing the history updates the forward button as well.
