### ISSUE TITLE
Danish Keyboard

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1751]
Implement Danish keyboard. Design is here:
https://trello.com/c/K0cfGN5a/438-de-68-danish-keyboard

**Comment by Delphine** [comment]
Contacted localizer for feedback, waiting to hear back.

**Comment by jakobkappel** [comment]
DE-68_Danish_Keyboard_001.pdf looks just fine. 

The punctuation marks in the lower right corner on "100 default keyboard" differ quite a lot from regular Danish keyboards. But I guess this is on purpose because it makes it easier to enter URLs without opening the symbols keyboard.

**Comment by jvonitter** [comment]
Thanks @jakobkappel !

**Comment by keianhzo** [comment]
This should have been closed after merging https://github.com/MozillaReality/FirefoxReality/pull/1890
