### ISSUE TITLE
Finnish Keyboard

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1752]
Implement Finnish Keyboard. Design is here:
https://trello.com/c/RGJbDyIM/437-de-67-finnish-keyboard

**Comment by Delphine** [comment]
Contacted localizer, now waiting to hear back

**Comment by lliehu** [comment]
Looks good. The layout of basic letters is expected and the same as Swedish. Most commonly used accented letters are also included, good.

Comparing with the Swedish keyboard https://github.com/MozillaReality/FirefoxReality/issues/1755, I was surprised to find that Swedish has ë, ê, ū, û but Finnish does not. Not that I know any significant use for them outside some foreign proper nouns (for example Citroën) and transliterations. If including a few more accents for e and u is not harmful, having those would be appreciated, I guess.

**Comment by jvonitter** [comment]
Thanks @lliehu! We'll add those in.

**Comment by jvonitter** [comment]
Spec updates are being made to add the additional characters but otherwise this is good to go.
