### ISSUE TITLE
Dutch Keyboard

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1753]
Implement Dutch keyboard. Design is here: 
https://trello.com/c/ucpYci9d/436-de-66-dutch-keyboard

**Comment by Delphine** [comment]
Contacted localizer, now waiting to hear back

**Comment by jvonitter** [comment]
@Delphine any word from our Dutch colleagues?

**Comment by Delphine** [comment]
Unfortunately, I have not heard anything back. I pinged the localizer again so hopefully we can get an answer soon

**Comment by Fjoerfoks** [comment]
> Unfortunately, I have not heard anything back. I pinged the localizer again so hopefully we can get an answer soon

Working on it...

**Comment by Fjoerfoks** [comment]
100 - DEFAULT KEYBOARD is OK.
200 - SYMBOLS overall OK, but we might consider to put € next to ¢ instead as first.
300 - LONG PRESS:
e: add to the right ě (U+011B), ĕ (U+0115),  ə (U+0259)
a: add to the right ă (U+0103), ą (U+0105)
o: add to the left ő (U+0151)
u: add to the left ů (U+016F), ų (U+0173)
. : add .nl, but one could also consider to put special characters under that one like ! ? , @

Are there any other considerations to deal with? And can this be tested somewhere? I only have a cardboard VR.

**Comment by jvonitter** [comment]
Thanks @Fjoerfoks !
We'll add the extra long press characters here. We'll keep the rest as is to be consistent with the other keyboards.
Spec is being updated but @keianhzo can make the updates when ready.
