### ISSUE TITLE
Norwegian Keyboard

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1754]
Implement Norwegian keyboard. Design is here: https://trello.com/c/sgyWbRxa/435-de-65-norwegian-keyboard

**Comment by Delphine** [comment]
Contacted localizers, now waiting to hear back

**Comment by jvonitter** [comment]
@Delphine any word from our Norwegian colleagues?

**Comment by Delphine** [comment]
Unfortunately I haven't heard back. I pinged them again, so hopefully we'll get an answer soon.

**Comment by havarh** [comment]
> @Delphine any word from our Norwegian colleagues?
Yes, this looks good. I was only able to open the PDF file, as the trello.com site required a login.
Maybe add .no to the long press for dot? It now has .org, .net and .com.

**Comment by jvonitter** [comment]
Thanks @havarh !
