### ISSUE TITLE
Swedish Keyboard

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1755]
Implement Swedish Keyboard. Design is here: https://trello.com/c/ANHF3mV1/434-de-62-swedish-keyboard

**Comment by Delphine** [comment]
Contacted localizer, now waiting to hear back

**Comment by andy-moz** [comment]
> 
> 
> Implement Swedish Keyboard. Design is here: https://trello.com/c/ANHF3mV1/434-de-62-swedish-keyboard

I can't open this link.

**Comment by andy-moz** [comment]
This looks good. Can we replace .com with .se [https://blog.mozilla.org/wp-content/uploads/2018/09/fxr-private-browsing-1.jpg]?
