### ISSUE TITLE
Allow per-site content permissions

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1758]
For sites that request microphone use, users should be able to grant permission once or always for that site. Users should also be able to revoke permission from sites they have allowed in the past.

Current behavior allows a site to ask for permissions multiple times in a single session, with no way for a user to say yes/no persistently for a site.

There's precedent and a model for this for Popup Blocking on #593  and the spec is here: https://trello.com/c/LserbZRw/428-uis-86-pop-up-blocking-override

**Comment by keianhzo** [comment]
**Scope extension**

We should add support for per-site permissions for all the supported content permissions: Microphone, Location, Auto-play, WebXR, PopUps. We are already doing it for Pop-Ups and WebXR so it makes sense to extend it to all of them.

Also after discussing it, it might be a good idea to remove the Android permissions from the privacy settings as you can't revoke them from inside the apps and you always get the system prompt if the permission is requested so it doesn't make much sense to have the switch there and it creates confusion between the system and browser equivalents.

**Comment by emstanley** [comment]
@keianhzo I'm cleaning up/ prioritizing our milestones in Github and I realized I have this scheduled for v14, not 12 in the original draft of our roadmap? Have you started on this yet?

**Comment by keianhzo** [comment]
Not yet, we can move it to v14.
