### ISSUE TITLE
Detect and suspend GeckoSessions causing performance issues.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1775]
## Problem
With the addition of multiple windows, the Performance Monitor had to be disabled due to the fact that it had no mechanism for determining what GeckoSession was causing the performance degradation.

## Possible Solution
By adding APIs to GeckoView it would be possible re-enable the performance monitor. The two enhancements to GeckoView are documented in these bugzilla issues:

[Bug 1578942 - Add the ability to complete suspend a GeckoSession](https://bugzilla.mozilla.org/show_bug.cgi?id=1578942)
[Bug 1578944 - Add the ability to be notified when a WebGL context is created or destroyed](https://bugzilla.mozilla.org/show_bug.cgi?id=1578944)

By knowing which sessions contain WebGL contexts (via [1578944),](https://bugzilla.mozilla.org/show_bug.cgi?id=1578944) it would be possible to suspend them (via [1578942)](https://bugzilla.mozilla.org/show_bug.cgi?id=1578942).

**Comment by jvonitter** [comment]
Backlogging this for now. Will pull it in again if needed.
