### ISSUE TITLE
Crash in mozilla::gl::SharedSurface_SurfaceTexture::Commit

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#1776]
This is one of the top crashers in FxR: https://crash-stats.mozilla.com/report/index/766714a4-de4c-4eed-a0c5-ef35f0190902

I created this bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1579028

**Comment by bluemarvin** [comment]
Fixed by https://github.com/MozillaReality/FirefoxReality/pull/1802
