### ISSUE TITLE
 The projections menu in the video transport controls for 360 videos stop working after the entering a 360 video the second time

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#1784]
## Configuration

Firefox Reality version: 
Firefox Reality build ID: 

Hardware: Oculus

## Steps to Reproduce

1. Open 360 video
2. Enter 360 playback
3. Show Video projection in the media controls
4. Exit VR playback
5. Enter VR playback again
6. Show Video projection menu in the media controls

## Current Behavior

VideoProjection menu is not visible on the second time

## Expected Behavior

It should be visible

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by jvonitter** [comment]
Duplicated by #1808

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.5-32691850 (49ffa844) installed on the Oculus Go, Quest, HTC Vive Focus, Focus Plus and Lenovo Mirage Solo headsets.
Now, the "Video Projection" button is still actionable after reentering immersive mode.
