### ISSUE TITLE
Enhance scaling and window's resizing behavior

### ISSUE THREAD

**Issue by ziomio** [MozillaReality/FirefoxReality#179]
From https://www.reddit.com/r/OculusGo/comments/8zccmj/firefox_reality_w_webvr_superalpha_release/e2hsj7k/

_Original text is below:_ 

"I have played with scaling/window resizing features and here's my feedback:

In resizing/scaling mode when you drag any of 4 corner circles - browser window becomes bigger or smaller. But it also moves browser window closer or further from my eyes. Instead, I propose to break this feature into 3 sub-features:

1. Browser positioning: I want to position browser in 3 dimensional space whethever I want - closer/further to my eyes or more to the left/to the right/to the top/to the bottom.

2. Browser window resizing: I want to resize browser window to any size and proportions I want. I want browser window at least 2 times bigger that you are currently allowing.

3. Zooming: I want to click on +/- buttons and be able to change zoom of web page. This feature should work the same way as in desktop browsers.

These 3 features should work independently and don't affect each other. That is, when I am zooming - I don't want my browser window size to change. And so on.

Also, in resizing/scaling mode navigational buttons (Back/Refresh) are hidden and URL input box also. But I need them - how am I supposed to click "Back" without them?"

**Comment by MortimerGoro** [comment]
Thanks a lot for the feedback @ziomio! Really useful

`In resizing/scaling mode when you drag any of 4 corner circles - browser window becomes bigger or smaller. But it also moves browser window closer or further from my eyes`

We are actually not moving the position of the browser window when scaling. But as the content size is the same when scaling with the same aspect ratio it looks like a visual effect of moving (I mean scaling down a  bit  looks equal to it moving far a way a bit)

**Comment by ziomio** [comment]
I still believe you are moving browser's window :)
Please have a look at these 2 images - I will try to explain my point of view using them.

1) https://imgur.com/e8Vhu73
2) https://imgur.com/GwcMLDY

Green circle represents a person, white disc below it is your 3D model of a plate and red plane is a browser's window.

On first image there is a 'normal' situation when a browser window is located at some distance from a person.

Interesting thing starts to happen on 2nd image - the more I increase a browser's window using resize corner circles - the closer browser's window floats to me - I can see its change in position because the bigger browser's window gets - the bigger part of 3D plate is intersected with it.
Did not you notice it?

**Comment by ziomio** [comment]
This guy confirms too that browser window gets closer when you resize it.
Skip to 4:15mins to see it https://youtu.be/YfF0R2v0kEk

**Comment by bluemarvin** [comment]
This video show the window does not move when resized: https://youtu.be/DZELzJUgaAo

**Comment by ziomio** [comment]
Even if you does not move window closer in code upon resizing my brain and
eyes are still "think" and feel that window  is moved closer.  It is an
interesting visual illusion which need to be dealt with.

**Comment by nancyhang** [comment]
@thenadj

**Comment by avrignaud** [comment]
We should finish implementing window control design and revisit.

**Comment by philip-lamb** [comment]
Closing as duplicate as these issues have been broken out into separate tracking items. Zoom #379. Resizing and positioning #480.
