### ISSUE TITLE
The UI for the "History" and "Bookmarks" empty pages is cut out if the window is resized to the "0.5x" size

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1799]
**[Affected Versions]:**
- Firefox Reality 1.4-32500011 (RC4) build.

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- Have the latest 1.4-32500011 (RC4) build installed.
- The headset is turned on and the app is opened.
- No history feeds or bookmarks are available.

**[Steps to reproduce]:**
1. Click the "Bookmarks" or "History" button from the tray.
2. Click the "Resize" button displayed under the window.
3. Select the "0.5x" size and click the "Check" button to apply.
4. Observe the "Bookmarks" or "History" page's UI.

**[Expected results]:**
- The pages are correctly displayed.

**[Actual results]:**
- The UI from the bottom of the pages is cut out.

**[Notes]:**
- Attached are screen shots of the issue:
   - Bookmarks page:
![Bookmarks0 5x](https://user-images.githubusercontent.com/40061643/64546702-d44b2c80-d333-11e9-85f6-224e235fbb88.png)

    - History page:
![History0 5x](https://user-images.githubusercontent.com/40061643/64546737-e3ca7580-d333-11e9-9eb1-f3709e31228d.png)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.5-32661642 (74326741) installed on the Oculus Go, Quest, HTC Vive Focus, Focus Plus and Lenovo Mirage Solo headsets.
Now, the UI for the "History" and "Bookmarks" empty pages are fitted for the 0.5x size window.
