### ISSUE TITLE
Specifically supporting the coil.com plugin

### ISSUE THREAD

**Issue by anselm** [MozillaReality/FirefoxReality#1800]
We want to try out different web monetization strategies overall to see if we can help creators in fxr get compensated more easily. If we can show adoption here then any campaign we do could migrate to firefox as a whole. Right now coil.com is an appealing strategy to try but of course plugins are not enabled yet.

Either we could wait for fxr to support plugins as a whole, or their specific plugin could be rolled into the local package. See https://addons.mozilla.org/en-US/firefox/addon/coil/

**Comment by jvonitter** [comment]
related to #299

**Comment by bluemarvin** [comment]
There are three options for supporting an add-on. The first is to bundle the add-on with FxR releases. In order for this to be viable however, the add-on's license must be compatible with FxR. The second option will be to get the add-on from AMO. However, AMO support is not scheduled to be supported in GeckoView until Q1 2020. AMO support will also require work being done in Android Components. Currently there are no issue on file in android Components to support AMO. The third option is we can manually install the add-on from a trusted source through GeckoView.

Regardless of how the add-on is made available in FxR, an audit needs to be done to determine what Web Extension APIs the add-on requires. GeckoView only supports a sub set of the Web Extension API. Any APIs that the add-on requires that are not supported by GeckoView would need to be added. The current work in GeckoView is to [enable adblocking](https://bugzilla.mozilla.org/show_bug.cgi?id=1582194). Any additional APIs would need to be added to GeckoView's roadmap.

**Comment by jvonitter** [comment]
@anselm could you investigate 
1. whether the Coil add-on license is compatible with FxR?
2. what web extension API's the Coil add-on needs (so we can cross reference with what GV supports)

**Comment by anselm** [comment]
Stefan at Coil says the license is Apache 2.0 and all the source is available here:

https://github.com/coilhq/web-monetization-projects

I don't know what all extension API's the coil plugin requires but it does actually work on FXR right now as is - I baked it into a custom build as a test. It does almost certainly look at "idle" and the current URL as well. For non FXR environments it has a user interface that shows up in the tab bar but on FXR obviously (since there is none) it does not have one - although it still seems to work anyway.

I can ask Coil specifically which API's are used - but if there is a way for us to actually know this ourselves it would be helpful. I assume these are the API's : https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API

**Comment by bluemarvin** [comment]
Grepping the code for `browser` should be sufficient for locating all API usage. The UI is probably a browser action which is currently under active development in GeckoView.

**Comment by bluemarvin** [comment]
From @agi90 
```
➜  web-monetization-projects git:(master) git grep "chrome\." | grep -oE "chrome\.[a-zA-Z\-\.]*" | sort | uniq
chrome.com
chrome.runtime.MessageSender
chrome.runtime.connect
chrome.runtime.getPlatformInfo
chrome.runtime.getURL
chrome.runtime.onMessage
chrome.runtime.onMessage.addListener
chrome.runtime.sendMessage
chrome.tabs.Tab
chrome.tabs.create
chrome.tabs.onRemoved.addListener
chrome.tabs.query
chrome.tabs.sendMessage
```
(chrome is the same as browser for compat with chrome extensions)

He says we currently support all of those Web Extension APIs.
