### ISSUE TITLE
Korean keyboard l10n suggestions

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1804]
User feedback on the Korean keyboard -

"Enter" Key
"엔터" is a phonetic way to write"Enter" with the Korean alphabet. Meanwhile, "입력" means "Input" in Korean, which is easier to be understood by people who are not familiar with English. Also, it's already being used in mobile keyboards, so Koreans are familiar with "입력" labeling.

"Space" Key
"공백" means "Blank or Empty" and "간격" means "Gap, Interval, and Space." Two words have different meanings, and some users may get confused by the “공백 (Blank/Empty)” labeling. I recommend using “간격” instead of “ 공백” to avoid any confusion.

"Go" Key (Enter Key State)
"가기" means "to go (somewhere)" and it requires an adverb to sound natural. Meanwhile, "이동" means "Move (from one place to another)." The word makes sense by itself since it does not require an adverb. Just like "입력 (input)" key, it's already being used in mobile keyboards so Korean people are already familiar with "이동" compared to "가기."

cc @Delphine - let me know if there's anything we can do to get these addressed

**Comment by Delphine** [comment]
Thanks for reporting these back to us. I'm CCing here @hyeonseok who is the manager of the Korean locale. He can let us know the reason they chose these terms over another choice, and if it makes sense to update them or not.
Note that if they are updated, we should be sure to reflect that across all other products in Korean for consistency, and probably mention them in a Style Guide or Glossary. Thank you

**Comment by hyeonseok** [comment]
All suggestions are applied at Pontoon. The suggestions are same with the strings used on iOS keyboard layout, and I agree that these are familiar with users.

In terms of consistency, these changes should be applied to keyboard layout only. I reviewed some other cases and found that former one is more appropriate in many contexts.

**Comment by keianhzo** [comment]
@jvonitter I've checked all the cases and all of them are already in master.
