### ISSUE TITLE
The 360 videos from Vimeo can not be played after entering in immersive mode using the on screen controls

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1805]
**[Notes]:**
- On 360 videos from Youtube, while in immersive mode, the "Pause" button is displayed for the on screen controls even if the video is not played. However, if the button is clicked the video is played.

**[Affected Versions]:**
- Firefox Reality 1.4-32522317 (RC5) build.

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- Have the latest 1.4-32522317 (RC5) build installed.
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**
1. Open a video recommended from Vimeo.
2. Open the video in immersive mode..
3. Perform a click while in immersive mode.
4. Click the "Play" button from the on screen controls displayed.
5. Observe the behavior.

**[Expected results]:**
- The video starts playing.

**[Actual results]:**
- The video is not played.

**[Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1QbkZ_81hFCjC2tbbFhZEPZeSiNIakaly)

**Comment by MortimerGoro** [comment]
Blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1524092
