### ISSUE TITLE
The logged history feed is deleted after the website's page is refreshed

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1806]
**[Affected Versions]:**
- Firefox Reality 1.4-32522317 (RC5) build.

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- Have the latest 1.4-32522317 (RC5) build installed.
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**
1. Click the "+" button to open a new window (I opened a new window for a better observation of the issue).
2. Click the "History" button to open the "History" page.
3. Focus the other window and navigate to a website eg: "www.wikipedia.org".
4. Refresh the page with the opened website.
5. Observe the "History" feed from the other window.

**[Expected results]:**
- The history feed remains displayed.

**[Actual results]:**
- The history feed is deleted.

**[Notes]:**
- Attached is a screen recording and the logcat while reproducing the issue: 
	- Screen recording: [link](https://drive.google.com/open?id=1ZcV75ATe18ybaWkhcXHAnyihnZTPXHp_)
	- Logcat: [link](https://drive.google.com/file/d/1srU_xdYmTKPmBaNNXhdVb25uzDYh0kuJ/view?usp=sharing)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.5-32691850 (49ffa844) installed on the Oculus Go, Quest, HTC Vive Focus, Focus Plus and Lenovo Mirage Solo headsets.
Now, the logged history feed is not deleted after the websites page is refreshed.
