### ISSUE TITLE
Add an option to change 3D 'space stars' background to another one

### ISSUE THREAD

**Issue by ziomio** [MozillaReality/FirefoxReality#181]
I want just black void around me. Other people may prefer other color. The best way I think is to allow them to choose any color they want as a background around them.

**Comment by cvan** [comment]
this is configurable from the Developer Options now accessible from clicking the Settings icon in the Tray.

can we close this, or is there more work to be done?

**Comment by avrignaud** [comment]
Have added environments, and will be adding further customization capabilities in future.
