### ISSUE TITLE
The "Delete"(trash) and "..."(3 dot menu) buttons from the Bookmarks and History views have no pressed state

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1812]
**[Affected Versions]:**
- Firefox Reality 1.4-32522317 (6eec2b6) 
- Firefox Reality 1.5-32550021 (3ae64f9) 

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- Have at least one website bookmarked.
- Have at least one website in the history feed.
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Click the "Open Bookmarks" or "Open History" button from the menu tray.
2. Click and hold the "..." (3 dot menu) button for one of the bookmarked/visited pages.
3. Observe the behavior.
4. Click and hold the "Delete" (trash) button for one of the bookmarked/visited pages.
5. Observe the behavior.

**[Expected results]:**
Step 3 - The button has a press state.
Step 5 - The button has a press state.

**[Actual results]:**
Step 3 - The button disappears.
Step 5 - The button disappears.

**[Notes]:**
- When the click is released the function of the button is performed.
- If the controller is moved while clicking the buttons, the functionality of the button is not performed.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1kyhKyHfuVl2dX9qTWWFP9pddcycKW3sY/view?usp=sharing).

**Comment by heres-maria** [comment]
I have verified this issue using the Firefox Reality version 8-33452219 (bfee54ee) build and it is partially fixed. 
The buttons on the Bookmarks view now have pressed states.
On the History view the "..."(3 dot menu) button now does have a pressed state. But the "Delete"(trash) button does not. 
If the trash button is long clicked, both buttons corresponding to that URL are no longer displayed. Releasing the button deletes the entry.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 8-40062127 (8a91dcb6) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the trash and 3 dot menu buttons from the Bookmarks and History views have a pressed state.
