### ISSUE TITLE
The keyboard is wrongly dismissed when the "Next" key is clicked

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1816]
**[Affected Versions]:**
- Firefox Reality 1.5-32550021 (3ae64f9) 

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to a website where multiple input fields are available, eg: https://www.facebook.com/.
2. Click inside the first input field.
3. Click the "Next" button from the keyboard and observe the behavior.

**[Expected results]:**
- The next input field is focused and the keyboard remains displayed.

**[Actual results]:**
- The next input field is focused and the keyboard is dismissed.

**[Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1ta7FQBGU-dyrygS8qMS5m4Uzjk8uQANR).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.5-32570012 (6090cf4) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the keyboard is not dismissed when the "Next" key is clicked.
