### ISSUE TITLE
Remove Window Size from display settings

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1822]
Since users can resize windows using resize mode, the Display settings are no longer relevant. They are also confusing now that we have multiple windows. We should remove them from Settings.

Within Settings -> Display:
![Screenshot_20190912-100006](https://user-images.githubusercontent.com/48839872/64808668-8b21f500-d54c-11e9-9999-950875cfdf56.png)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified these changes on the latest Firefox Reality 1.5-32632345 (3838bdf5) installed on the Oculus Go, Quest, HTC Vive Focus Focus Plus and Lenovo Mirage Solo headsets. The "Window Size" setting are no longer present in the “Display” settings.
