### ISSUE TITLE
The on screen controls for 360 videos are no longer displayed at all on subsequent videos or they are wrongly positioned to the far right/left

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1830]
**[Affected Versions]:**
- Firefox Reality 1.5-32552323 (4078203)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Open any video from the FxR homepage and enter immersive mode.
2. Press the trigger button on the controller.
3. Exit immersive mode and click the “+” (New Window) button.
4. Open another video from the FxR homepage and enter immersive mode.
5. Press the trigger button on the controller and observe the position of the on screen controls.
6. Exit immersive mode and dismiss the window with the first video.
7. Enter immersive mode for the remaining video.
8. Press the trigger button on the controller and observe the position of the on screen controls.

**[Expected results]:**
Step 5. The on screen controls are displayed on the screen in front of the view.
Step 8. The on screen controls are displayed on the screen in front of the view.

**[Actual results]:**
Step 5. The on screen controls are displayed to the far left of the view and rotated.
Step 8. The on screen controls do not appear.

**[Notes]:**
- If two videos are opened the issue will reproduce on the second video played regardless of which video was opened first.
- Depending on the position of the first video played the on screen controls are either displayed to the far left or right.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1ySoktWB8WJYKEgKUWkLAwM-qbPU37wg6/view?usp=sharing).

**Comment by bluemarvin** [comment]
This looks like the media menu does not get it's parent updated when multiple windows have media so it is always rendering relative to the first parent it attaches to.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.5-32570012 (6090cf4) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the on screen controls for 360 videos are displayed in front of the view for all videos.
