### ISSUE TITLE
The buttons in the awesomebar have the wrong color scheme for hover and pressed state in Private Browsing

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1831]
**[Affected Versions]:**
- Firefox Reality 1.5-32552323 (4078203)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Click the "Enter Private Browsing" button from the menu tray.
2. Navigate to any website.
3. Using the controller hover the pointer over each button in the awesomebar.
4. Observe the color scheme of the hovered buttons.
5. Using the controller click and hold each button in the awesomebar.
4. Observe the color scheme of the clicked buttons.

**[Expected results]:**
- The buttons in the awesomebar have the private browsing color scheme.

**[Actual results]:**
- The buttons in the awesomebar have a fog colored background with the icon having an asphalt color.

**[Notes]:**
- The normal browsing color scheme is also applied to the pressed state.
- Attached a screenshot of the issue below:
![Fri09-13-2019_14-32-02 51](https://user-images.githubusercontent.com/51400741/64868577-5004ec00-d648-11e9-892a-4f39b445a105.png)

**Comment by jvonitter** [comment]
@thenadj what's should the correct color be?

**Comment by thenadj** [comment]
Color Fog for hover is correct but on click the color should be Blackberry.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 5-32802136 (860995be) installed on the Oculus Go, Quest, HTC Vive Focus, Focus Plus and Lenovo Mirage Solo headsets.
Now, the buttons in the awesomebar have the correct color scheme for the pressed state in Private Browsing, for the hover state the color scheme was the correct one already.
