### ISSUE TITLE
History Page animations do not seem to run when page does not have focus

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1832]
## Configuration

Firefox Reality version: 1.4

Hardware: Quest (probably all)

## Steps to Reproduce

1. Open history
2. Open second window
3. open pages in new second window

## Current Behavior

The history page sporadically update and gets stuck mid animation until it is given focus.

## Expected Behavior

Animations should run smoothly in the history page even when it doesn't have focus.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.5-32691850 (49ffa844) installed on the Oculus Go, Quest, HTC Vive Focus, Focus Plus and Lenovo Mirage Solo headsets.
Now, the "History" page animations run even when the page is not focused.
