### ISSUE TITLE
Keyboard done key text does not change when text field changes.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1833]
## Configuration

Firefox Reality version: 1.4

Hardware: HTC (probably all)

## Steps to Reproduce

1. Go to `facebook.com`
2. Select `Mobile number or email` field (note the done key says `NEXT`)
3. Select `Password` field

## Current Behavior

Done button says `NEXT`
## Expected Behavior

Done button should say `GO`

## Additional information
If you do the opposite order it will always say `GO`.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 5-32772008 (4f9f8cf0) installed on the Oculus Go, Quest, HTC Vive Focus, Focus Plus and Lenovo Mirage Solo headsets.
Now, the keyboard “Next” key updates to “Done” key when needed.
