### ISSUE TITLE
[Enhancement] Non special character should be inserted in the input field on click

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1838]
**[Affected Versions]:**
- Firefox Reality 1.5-32570012 (6090cf4)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Using the controller click inside the awesomebar.
2. Long click and hold one of the non special characters. (e.g. numeric keys, `{`, `}`, `[`, `]`etc)
3. Observe the behavior.

**[Expected results]:**
- The character is inserted in the input field.

**[Actual results]:**
- Nothing happens.

**[Notes]:**
- The character is only added when the click is released.
- If the pointer is moved to another non special character, the pressed state is moved to that character and when released, the initially selected character is inputted instead.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1CkKf2lwrLYyad_salUoOTKclkYc8VKKX/view?usp=sharing).

**Comment by bluemarvin** [comment]
This is by design. I think we could fix the key highlighting to make it more obvious. When a key is pressed, it is supposed to capture the pointer until the click is released. I think maybe the key that was presses should stay highlighted and other keys should not highlight until the click is released. @jvonitter ?

**Comment by jvonitter** [comment]
Working on an updated spec for this. Possible interaction steps (to be evaluated by @thenadj and co):

- Hover over button: key color change to Asphalt on Fog
- Long press down: key color change to Void on Asphalt
- Long press up: special characters hover menu appears (Asphalt on Fog); keyboard background changes from Asphalt to Void
- Hover over special characters: key color change to Fog on Asphalt
- Click down: key color change to Fog on Void
- Click up: special character is added and hover menu disappears

**Comment by jvonitter** [comment]
Updated spec with new interactions (and colors) https://trello.com/c/VLsCI8iC/35-uis-6-english-keyboard

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 8-40100049 (1500ba50) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the non special characters are inserted in the input field on a long click.
