### ISSUE TITLE
Two or three history feeds are wrongly logged when URL is change via javascript

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1839]
**[Affected Versions]:**
- Firefox Reality 1.5-32570012 (6090cf4)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Click the "+" button to open a new window (I opened a new window for a better observation of the issue).
2. Click the "History" button to open the "History" page.
3. Focus the other window and navigate to "www.youtube.com".
4. Click on a suggested video and observe the "History" page.

**[Expected results]:**
- A history feed is logged for the opened video.

**[Actual results]:**
- Two or three history feeds are logged for the opened video.

**[Notes]:**
- The logs have the same URL.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=19oP4kQI-bfkgv0nQlmM1LfUzD7fWxXUd)

**Comment by keianhzo** [comment]
@bluemarvin Might this be related to the Youtube overriding that we do?

**Comment by bluemarvin** [comment]
It probably is, I think we need to use the flag that overwrites history when doing the redirect?

**Comment by bluemarvin** [comment]
Blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1555337

**Comment by bluemarvin** [comment]
Still waiting for fix in GV.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 8-33472001 (6ba38814) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, only one history feed is logged when navigating on different videos on youtube or twitch.
