### ISSUE TITLE
The "TODAY" string from the "History" page glitches while scrolling

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1842]
**[Affected Versions]:**
- Firefox Reality 1.5-32570012 (6090cf4)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The history logs exceed the "History" page view. 

**[Steps to reproduce]:**
1. Click the "History" button from the tray menu.
2. Click>hold and scroll the page so that the "TODAY" string fades in the background on the top of the page. 
3. Observe the string.

**[Expected results]:**
- The string fades without glitches.

**[Actual results]:**
- At a certain point the string glitches while fading.

**[Notes]:**
- I could not verify the issue with the "YESTARDAY" and "LAST WEEK" strings because I had no available feeds for this sections.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1qG1t7zneXsqfzV0YrXx1m2sX10bfGX31)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.5-32691850 (49ffa844) installed on the Oculus Go, Quest, HTC Vive Focus, Focus Plus and Lenovo Mirage Solo headsets.
Now, the "TODAY" string from the "History" page does not glitch while scrolling.
