### ISSUE TITLE
Random recommended video from homepage is highlighted while hovering the "Open in a new Window" button

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1843]
**[Affected Versions]:**
- Firefox Reality 1.5-32570012 (6090cf4)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Click and hold on a recommended video from homepage.
2. Hover multiple times over the "Open in a new Window" button.
3. Observe the recommended videos while hovering the the "Open in a new Window" button.

**[Expected results]:**
- No UI changes occur for the videos.

**[Actual results]:**
- A random video is highlighted.

**[Notes]:**
- If the "Open in a new Window" button is clicked, the correct video is opened.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1DEoza0u7K92pzGpJ46Urwa-snv1AI4xE)

**Comment by bluemarvin** [comment]
I'm not sure I under stand the issue. The page should remain responsive when the context menu is shown. I see the same behavior on desktop when long clicking on a link to show the context menu. @jvonitter  Are we expecting different behavior in FxR?

**Comment by Softvision-RemusDranca** [comment]
@bluemarvin, I seem to have caused a bit of confusion with this issue.
The problem is that when the "Open in a new Window" button from the context menu is hovered, other cards from the page are enlarged (like they are hovered). 
It’s quite hard to put in words, as the video that is highlighted this way is a random one.

Hopefully the screenshot below makes more sense, where the "Open in a new Window" button is hovered and the "En Machina" card from the top of the page is enlarged.
![HoverContextMenuHomepage](https://user-images.githubusercontent.com/40061643/65026703-c2741580-d941-11e9-9f86-0575a941e924.PNG)

**Comment by bluemarvin** [comment]
@Softvision-RemusDranca Thanks for the clarification. I understand what the issue is now.

**Comment by joshmarinacci** [comment]
I just tested it today and it doesn't seem to happen anymore. When I long press on a video the "open in a new window" popup appears where it should be.

**Comment by jvonitter** [comment]
@Softvision-RemusDranca can you verify this and close if fixed?

**Comment by Softvision-RemusDranca** [comment]
This issue is no longer reproducible since the new Context menu was implemented in version 6 of Firefox Reality. Now, the page behind the menu is no longer focused.
I will close this issue as verified-fixed.
