### ISSUE TITLE
The blue focus border is displayed outside the window's border if it was previously manual resized to maximum and then the "2x" size is set 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1851]
**[Affected Versions]:**
- Firefox Reality 1.5-32600111 (5d08acb)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Click the "Resize" button. 
2. Click>hold on the window's borders and drag them to the max width and hight possible.
3. Click the Check button to save the size.
4. Click the "+" button from the menu tray.
5. Focus the window on the left and click the "Resize" button.
6. Select the "2x" size and click the Check button to save the size.
7. Focus the other window.
8. Hover over the unfocused window and observe the top and bottom borders.

**[Expected results]:**
- The blue focus border is correctly displayed around the window's border.

**[Actual results]:**
- The blue focus border is displayed outside the window's border.

**[Notes]:**
- The issue is also reproducible if three windows are opened and the window is resized to the "1.5x" size.
- The issue is not reproducible if the window is resized to the other available sizes.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1ykBM6zFknasd6GCCONdc2Vtkhpjztdvx)

**Comment by Softvision-RemusDranca** [comment]
After more investigation it seems that the issue is also reproducible after manual resizing the width to the maximum size and the height to the minimal size. In this situation the blue focus borders are displayed inside the window's content.
I've attached a video recording with this behavior as well: [link](https://drive.google.com/open?id=1npHOpzOlMN3NpQlq8E4KHgi09FEHfcOu)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.5-32632345 (3838bdf5) installed on the Oculus Go, Quest, HTC Vive Focus Focus Plus and Lenovo Mirage Solo headsets.
Now, the blue focus border is displayed inside the window's border after a manual and then a 2x resize.
