### ISSUE TITLE
Dissable 32 bit builds

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#1855]
**Is your feature request related to a problem? Please describe.**
Now that we are shipping 64 bit builds to the stores. We should disable 32 bit builds.

**Additional context**
Now that we aren't using 32 bit builds we could reduce our taskcluster build times by almost half.

**Comment by jvonitter** [comment]
Do it! If we find we need them, we can always turn them back on.

**Comment by philip-lamb** [comment]
Hold please. We need 32-bit SVR builds for an upcoming partner.

**Comment by philip-lamb** [comment]
Janice and I discussed and we've concluded that we can safely disable the 32 bit builds with the exception of WaveVR, although I expect that platform to also move entirely off 32-bit before too long.
