### ISSUE TITLE
Settings for turning off and clearing autocomplete

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1857]
Users need a way to turn off autocomplete in the address bar.
They also need a way to clear past autocomplete information.

**Comment by jvonitter** [comment]
Source: https://support.mozilla.org/en-US/questions/1268628

**Comment by thenadj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UIS-16 Settings](https://trello.com/c/P52DGGmp/88-uis-16-settings)

**Comment by jvonitter** [comment]
this has been added to the spec

**Comment by keianhzo** [comment]
@jvonitter It's unclear to me what the issue refers to. Auto-fill in web pages input fields? Auto-completion in the address bar? Awesome bar suggestions? We don't have keyboard suggestions yet so it can't be that.

The address bar auto-completion only provides domain completion based on the most popular domains.

**Comment by jvonitter** [comment]
It's the awesome bar suggestions (which I believe are based off history?) - these:
![org mozilla vrbrowser-20200109-170546 (2)_LI](https://user-images.githubusercontent.com/48839872/72117491-d2ee3880-3302-11ea-8b45-c564906b812b.jpg)

Basically, a way to just turn off auto-complete so your history entries dont show up in the address bar.

**Comment by bluemarvin** [comment]
Are we sure autocomplete isn't when FxR pings google to get a suggestion? for example, if I press `a`, google will tell us `amazon.com` is the mostly likely address. People don't like that because it reports every key stroke to google (or whatever search engine for their region).

**Comment by bluemarvin** [comment]
Looking at how desktop handles this I think we have it all wrong. In fact I think private browsing windows are the inverse of what they should be.

**Comment by jvonitter** [comment]
pushing this to 9 so we can figure out the right path

**Comment by keianhzo** [comment]
@emstanley I think we should bring this up in the next team meeting to decide if we want this feature and how exactly we should implement it.
