### ISSUE TITLE
The window’s placeholder wrongly has the same background as the max window pop-up

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1862]
**[Affected Versions]:**
- Firefox Reality 1.5-32622233 (cfdab616)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2
- Lenovo Mirage Solo - Android 8.0.0

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- Have 2 windows already opened.

**[Steps to reproduce]:**
1. Click the “+” new window button in the menu tray twice.
2. Observe the max window popup while the window’s placeholder is displayed.

**[Expected results]:**
- The background for the popup and the placeholder are easily distinguishable.

**[Actual results]:**
- The popup’s background can be confused with the background of the placeholder.

**[Notes]:**
- The issue is most prominent on the Oculus Go.
- On the other devices the popup has a shadow which separates it from the placeholder background.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1xcTrQUQYFGFkKkSPQRnJq7qlKDn5H-DW/view?usp=sharing).

**Comment by bluemarvin** [comment]
I think a lighter gray for the background would work well. @jvonitter

**Comment by jvonitter** [comment]
you can try iron =#5d5d5d

**Comment by bluemarvin** [comment]
This is with iron:
![image](https://user-images.githubusercontent.com/3066/65340609-73b5be00-db83-11e9-9ea1-f22df187f3ab.png)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.5-32632345 (3838bdf5) installed on the Oculus Go, Quest, HTC Vive Focus Focus Plus and Lenovo Mirage Solo headsets.
Now, the window’s placeholder has an iron color and the backgrounds can not be confused.
