### ISSUE TITLE
Browser window can render over pointer when pointing at close button

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#187]
The current alpha sorting can cause the browser window to render over the pointer when it is on the private browsing close button due to z-buffer writing being disabled when it is rendered. Depends on https://github.com/MozillaReality/vrb/issues/16 to correctly fix.

**Comment by philip-lamb** [comment]
I wasn't able to reproduce this on 1.1.2. @bluemarvin Is this still an issue?

**Comment by cvan** [comment]
@philip-lamb: I am still able to reproduce this on `v1.1.2` and `master`. It is noticeable in a Private Browsing session.

**Comment by bluemarvin** [comment]
This was fixed.
