### ISSUE TITLE
Clear GV history using the GV API

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#1875]
**Is your feature request related to a problem? Please describe.**
At the moment we can clear the Places history but there is not a way to clear the internal GV history so things like the navigation buttons state are not correctly updated after clearing the history.

**Describe the solution you'd like**
GV is going to get a history API so we can clear the internal GV history properly.

**Describe alternatives you've considered**
We are currently recreating the session to reset the internal history but is not the optimal way to do it.

**Additional context**
https://bugzilla.mozilla.org/show_bug.cgi?id=1583265

Related https://github.com/MozillaReality/FirefoxReality/issues/1749

**Comment by bluemarvin** [comment]
Fixed by  #1903
