### ISSUE TITLE
A thin vertical gap is wrongly displayed between different buttons in many different locations on the Lenovo Mirage Solo

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1880]
**[Affected Versions]:**
- Firefox Reality 1.5-32661642 (74326741)

**[Affected Platforms]:**
- Lenovo Mirage Solo - Android 8.0.0

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Click the “+” new window button in the menu tray.
2. Observe the multiwindow controls.
3. Resize the 2 windows to “2x” size.
4. Click the “Resize” button again and observe the predefined window sizes.
5. Click the Click the “+” new window button in the menu tray.
6. Resize all 3 windows to “1.5x” size.
7. Click the “Resize” button again and observe the predefined window sizes.
8. Click the “Save” (checkmark) button to exit resize mode.
9. Navigate to any video and enter full screen mode.
10. Click the “Resize” button and resize the full screen size to “2x”.
11. Click the “Save” (checkmark) button and observe the full screen menu underneath the window.
12. Click the “Resize” button again and observe the predefined window sizes.

**[Expected results]:**
Step 2 - The multiwindow controls have no gap between them.
Step 4 - The predefined options have no gap between them.
Step 7 - The predefined options have no gap between them.
Step 11 - The full screen menu has no gap between the buttons.
Step 12 - The predefined options have no gap between them.

**[Actual results]:**
Step 2 - The multiwindow controls have gaps between them.
Step 4 - The predefined options have a gap between the “2x” size and the “1x” size.
Step 7 - The predefined options have a gap between the “1.5x” size and the “1x” size.
Step 11 - The full screen menu has a gap between the “Back” and “Resize” button.
Step 12 - The predefined options have a gap between the “3x” size and the “2x” size.

**[Notes]:**
- The same behavior can be observed while in Private browsing.
- Attached a screen recording of the issue [here](https://drive.google.com/drive/folders/1Yx2yTOeqbX6kiRKJQF5-h2x-XpIG49VH?usp=sharing).

**Comment by bluemarvin** [comment]
Closing since we no longer support this device.
