### ISSUE TITLE
Unable to update or uninstall Firefox Reality

### ISSUE THREAD

**Issue by psiinon** [MozillaReality/FirefoxReality#1886]
## Configuration

Firefox Reality version: 1.2.4
Firefox Reality build ID: Unknown

Hardware: Oculus Quest

## Current Behavior
Firefox Reality is stuck on version 1.2.4.
I've tried updating and while the new version is downloaded it just fails to install with no explanation. It says its "Installing..." but that then disappears and when I open the app it still says there is an update.
I've tried uninstalling it but that fails too with no explanation, even after a restart.
I've got plenty of space on the device and have not experienced this problem with any other apps.
I contacted Oculus and they suggested turning off developer mode, rebooting and trying to update / delete - I tried that but the same thing happened.

## Expected Behavior
Firefox Reality should update :)

## Context
I'm guess this is specific to my headset as I've not found this issue mentioned anywhere else.
Sorry if I should have raised it elsewhere but this was the only place I could find.
I did have developer mode turned on and Side Quest installed, but other than that I've not done anything 'unusual' to the Quest.

## Error Logs and Stack Traces

Dont know what would be useful, but I'm technical (and work at Mozilla:) so happy to get whatever you need.
<details open>

```
```

</details>

**Comment by joshmarinacci** [comment]
I've seen this happen when trying to upgrade through the store over a version that was sideloaded.  You should remove it over USB using adb and then do a new install from the store.

**Comment by psiinon** [comment]
Doh, I completely forgot I'd sideloaded it as I'd installed the last version from the store. Removing the sideloaded one fixed the problem.
Many thanks :)
