### ISSUE TITLE
Remove 'too many windows' dialog

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1897]
Now that we will have tabs, if a user tries to create a new window, it should create a new tab (in their active window) instead. The 'too many windows' dialog should be removed.

The new window ( + ) button should disappear/be disabled when there are three windows. There should not be two buttons next to each other, both of which open a new tab. 
cc @thenadj

**Comment by jvonitter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UIS-70 Window Positioning (3 Windows)](https://trello.com/c/78zHL5U4/343-uis-70-window-positioning-3-windows)

**Comment by jvonitter** [comment]
@MortimerGoro i still get this popup in the apk you gave me on 10/21

**Comment by MortimerGoro** [comment]
Closed via #2028
