### ISSUE TITLE
add hamburger button next to the awesomebar for page options

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1898]
Since we're adding a new page option for Send Tab, we need to make room for it in the page controls.

- [x] Replace resize button (to the right of the awesomebar) with hamburger button
- [x] Remove User Agent toggle from awesomebar
- [x] When clicked, hamburger button should trigger a context menu with three options:
1. `Send Tab` with send icon.  See UF-85 and #1866 
2. `Resize Window` with resize icon (no change to icon or behavior)
3. `Request Desktop Site` with UA icon either with or without checkmark, depending on settings.

**Comment by keianhzo** [comment]
@thenadj We will need icons for the hamburger menu the send tab.

**Comment by Softvision-GeluHaiduc** [comment]
Do we have an ETA on the final design for this?

**Comment by thenadj** [comment]
We're updating UIS-21 to reflect the new hamburger menu functionality. I'll add icons to this issue shortly.

**Comment by thenadj** [comment]
[FxR Hamburger Menu.zip](https://github.com/MozillaReality/FirefoxReality/files/3740631/FxR.Hamburger.Menu.zip)

**Comment by jvonitter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UIS-21 Window w/ Controls Below & Thumbnails](https://trello.com/c/rg6PsZgI/85-uis-21-window-w-controls-below-thumbnails)

**Comment by keianhzo** [comment]
@jvonitter I can't find the URL for the help icon in the send tabs dialog header

**Comment by jvonitter** [comment]
@keianhzo You can't find it because there isn't one! The flow had that button, but the final spec does not. I pulled this from UIS-59 (which is the main send tab one)

![sendtabdialog](https://user-images.githubusercontent.com/48839872/67226869-d9979e80-f3ea-11e9-994d-40f2aa4c97ae.PNG)

**Comment by keianhzo** [comment]
@jvonitter At the moment the settings dialogs that are children of the **Main Settings** panel have this style:

![org mozilla vrbrowser dev-20191022-110908](https://user-images.githubusercontent.com/837184/67272352-a9b8cb80-f4bc-11e9-8916-890d4afbbc9f.jpg)

The **Clear History** dialog that opened from the clear cache button in the History panel has a different style:

![org mozilla vrbrowser dev-20191022-110850](https://user-images.githubusercontent.com/837184/67272424-cbb24e00-f4bc-11e9-9a9e-4bab7f0e55c8.jpg)

I did the style of the **Send Tabs** dialog to match the **Clear History** dialog as both are independent dialogs not related or children of the settings panel:

![org mozilla vrbrowser dev-20191022-110836](https://user-images.githubusercontent.com/837184/67272565-16cc6100-f4bd-11e9-927a-0af99cafb5bb.jpg)

Do we want this to be styled as the **Settings Dialogs** or as the **Clear History** one? Is not a big deal changing it, just want to make sure that we keep the UI consistency.

**Comment by thenadj** [comment]
The 'Clear History' dialog should follow the children of the main settings dialog! We're updating UIS-16 right now to include this.

The 'Send Tab to Device' dialog should also follow the children of the main settings dialog. It's specified in UIS-59 section 500, 200e, and 200i.
