### ISSUE TITLE
Long press on the URL bar shouldn't show the keyboard

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#191]
It should actually show an actions menu but we don't have support for that yet. When long pressing you should be able to scroll the text without the keyboard showing. Keyboard should only show on short click. After long click the actions menu should show up.

**Comment by thenadj** [comment]
Yes! Short click brings up keyboard, long press allows user to scroll over text and select it. Will we add support for that in v1.1?

**Comment by cvan** [comment]
Highlighting on focus/click is the behaviour consistent with mobile, desktop, and VR browsers. I would expect clicking on a favicon, Info button, or the protocol to expose site information.

Related bug: #374

**Comment by jvonitter** [comment]
I think this doesnt happen anymore. QA please verify and close

**Comment by jvonitter** [comment]
I think this doesnt happen anymore. QA please verify

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.4-32352315 installed on the Oculus Go and Quest headset.
If the URL bar is empty the keyboard appears after the long press is released.
If the URL bar is active (it has an address inside it) after long pressing the URL bar the keyboard is displayed and the app crashes. I’ve logged issue #1654 for this.

**Comment by Softvision-GeluHaiduc** [comment]
Because #1654 was fixed I have verified this issue again with the latest Firefox Reality 1.4-32400715 installed on the Oculus Go and Quest headset.
The issue is again reproducible by long pressing a URL bar (active or not) the keyboard appears.

**Comment by keianhzo** [comment]
After discussing with @bluemarvin we have agreed that bringing up the keyboard after a long press it's the expected behavior and it's how the Android system handles this type of interaction. Closing this as it's the expected behavior.
