### ISSUE TITLE
add domain button to the keyboards

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1914]
lots of users have asked us to add the most common domains (particularly for their country/language) to the keyboard.

TBD- where these will show up on the keyboards

All: .com .net .org . co
English .uk .us
French .fr
Italian .it
German .de
Japanese .jp
Korean .kr
Swedish .se
Norwegian .no
Danish .dk
Dutch .nl
Finnish .fi
Polish .pl
Russian - none
Spanish - none
Chinese (pinyin) - none
Chinese  (zhuyin) - none

**Comment by philip-lamb** [comment]
With the massive proliferation in TLDs (see e.g. https://tld-list.com/tlds-from-a-z), any attempt to guess appropriate ones are going to on average be wrong for most users. IMHO this should be based on a kind of top-sites-like algorithm. Populate it with the user's most X visited top-level (and possibly second-level) domains.

**Comment by jvonitter** [comment]
I was just going to go with the requests we've had from localizers to put their countries TLD

**Comment by jvonitter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UIS-6 English Keyboard](https://trello.com/c/VLsCI8iC/35-uis-6-english-keyboard)
