### ISSUE TITLE
A thin blue line is wrongly displayed underneath the dialog separator for the "Display", “Display Language” and “Voice Search Language” cards while scrolling down

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1923]
**[Affected Versions]:**
- Firefox Reality version 5-32772008 (4f9f8cf0)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- Lenovo Mirage Solo - Android 8.0.0

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Click the “Settings” (gear icon) button from the menu tray.
2. Click the “Display” card and scroll down.
3. Observe the top of the “Display” dialog.

**[Expected results]:**
- The “Display” dialog is rendered correctly.

**[Actual results]:**
- A thin blue line is displayed underneath the separator of the “Display” dialog.

**[Additional Notes]:**
- The issue is not reproducible on the HTC devices.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1B87wICiNolr87gzJqBJzWx0Hv6628uVo/view?usp=sharing).

**Comment by keianhzo** [comment]
@Softvision-GeluHaiduc I don't seem to be able to reproduce this one anymore. We have made quite a lot of UI polishing lately, can you check if it is still happenning?

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this with the latest Firefox Reality version 5-32802136 (860995be) installed on the Oculus Go, Quest, HTC Vive Focus, Focus Plus and Lenovo Mirage Solo headsets.
The issue seems to not be reproducible anymore, the thin blue line in the "Display", “Display Language” and “Voice Search Language” cards after scrolling down does not appear.
