### ISSUE TITLE
Clunky scrolling in History and Bookmarks

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#1928]
Video:
[scroll.mp4.zip](https://github.com/MozillaReality/FirefoxReality/files/3698968/scroll.mp4.zip)

Scrolling performance is much better in other scrollviews. Is any view being recreated in those lists?

**Comment by philip-lamb** [comment]
Assigning to @keianhzo but reassign if you need to.

**Comment by keianhzo** [comment]
Will be fixes (or substantially improved) by https://github.com/MozillaReality/FirefoxReality/pull/1973
