### ISSUE TITLE
Resizing handles input overlap focus mode buttons

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#193]
Sometimes you want to just click on exit but the resizing handles get the input. Easier to explain with a video.

https://youtu.be/QDldqtoJTYc

**Comment by MortimerGoro** [comment]
I remember that the spec defined a smaller touch area for the resizing handle in that corner. We need to do that

**Comment by MortimerGoro** [comment]
Hit are is tested here, I used the doubled size of the handle
```
      if (distance < kHandleRadius * 2.0f) {
        return handle;
      }
```
