### ISSUE TITLE
The Video Projection menu is not dismissed when clicking the other buttons from the on screen controls

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1935]
**[Affected Versions]:**
- Firefox Reality version 5-32802136 (860995be)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to any 360 video and enter immersive mode.
2. Press the trigger button on the controller and click the "Video Projection" button from the on screen controls.
3. Click on the Play/Pause button from the on screen controls and observe the Video Projection menu. 

**[Expected results]:**
- The Video Projection menu is dismissed.

**[Actual results]:**
- The Video Projection menu is NOT dismissed.

**[Additional Notes]:**
- This issue is also reproducible if the progress bar, Volume, Forward/Back 30 sec, buttons are clicked. 
- As a side affect of this issue, the volume bar is not fully actionable.
- The issue is no longer reproducible if the Back or the Video Projection button are clicked.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=18oBtiOUmmhSvcYFEuJBXkGANt5xIc4Du)

**Comment by heres-maria** [comment]
I have verified this issue and it is no longer reproducible with the Firefox Reality version 7 RC4 (143a88ad) build. The Video Projection menu is dismissed when clicking on any of the other buttons.
Tested on Oculus Quest (Android 7.1.1) and HTC Vive Focus Plus (Android 7.1.2).
