### ISSUE TITLE
Save/restore library panels when the app is reopened

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#1945]
**Is your feature request related to a problem? Please describe.**
At the moment FxR is saving the layout and restores it after the app is reopened but in only restores browser windows, not library panels.

**Describe the solution you'd like**
I'd like to be able to restore also library panels so my exact layout is restored upon app reopen. See the screenshot.

**Describe alternatives you've considered**
Also would be great if I could save/restore specific layouts that I might use for different tasks. For example a layout that I use for reading different newspapers, a layout for developing or a layout for general browsing or watching movies.

**Additional context**
![org mozilla vrbrowser dev-20191008-234253](https://user-images.githubusercontent.com/837184/66435563-6e7ebd00-ea25-11e9-9033-545a5e893489.jpg)

**Comment by jvonitter** [comment]
The design calls for library panels to also be restored, so this is a bug.
The additional idea about layout profiles is interesting, but it should get it's own enhancement issue.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9-40430119 (abd4f531) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the library panels, Bookmark and History Views, are restored when the app is reopened.
