### ISSUE TITLE
I'd like to copy the URL from the awesome bar to the URL bar

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#1946]
**Is your feature request related to a problem? Please describe.**
When you start typing and the awesome bar starts showing results sometimes you need to copy the URL to the URL bar to edit it and remove/add something. At the moment we only offer the option of clicking on it to go to that URL.

**Describe the solution you'd like**
I'd like to have a button to copy that URL to the URL bar to be able to edit it without navigating to that URL. Ideally we could add a button to the right of the awesome bar item that just copies the URL to the URL bar, closes the awesome bar and places the cursor at the end of the URL bar text so you can start editing it.

**Describe alternatives you've considered**
We could also add other options like, sharing the URL as a tab through FxA "Send tab service" or just copy the URL to past it somewhere else.

**Additional context**
![photo5829939885937636135](https://user-images.githubusercontent.com/837184/66462891-479fa580-ea7c-11e9-93e6-b927f488055d.jpg)

**Comment by jvonitter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UIS-75 History & Bookmarks in Awesomebar](https://trello.com/c/vZoboQMn/360-uis-75-history-bookmarks-in-awesomebar)

**Comment by jvonitter** [comment]
@keianhzo is there a reason why we cant long-press here and do a copy the regular way?

**Comment by jvonitter** [comment]
we decided to keep copy/paste working the regular way. the menu was the same color as the background, so we added a line around the copy/paste menu.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this enhancement with the latest Firefox Reality version 8-40101959 (3c2a71e2) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
By long pressing on a awesomebar suggestion a Copy context menu appears centered above the suggestion and the URL can be copied from that suggestion regardless of the type of suggestion (bookmark, history, search or default).
