### ISSUE TITLE
Improve Navigation Bar transitions

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#195]
The transitions between URL bar view and focus mode view make some glitches and the views are sometimes out of bounds for millisecs.

Use TransitionManager to try to handle this in a seamless way.

**Comment by cvan** [comment]
Can you share a video capture to illustrate this (so we can better prioritise)? (Heh, I know it's already a `P0`.)

**Comment by keianhzo** [comment]
Here you can appreciate the issue. When entering focus mode, when the saved preset is smaller than 1x you can see that the navigation bar is during half a sec outside the browser window bounds.

![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/837184/43789822-396cf0dc-9a71-11e8-983c-a8de98eab719.gif)

**Comment by nancyhang** [comment]
@keianhzo is this a ship blocker for v1?

**Comment by larsbergstrom** [comment]
@keianhzo I assume we should punt this to V1.1?
