### ISSUE TITLE
Pointer/Cursor needs design improvements

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#196]
REPRODUCE: Home/Everywhere
CURRENT BEHAVIOR: Pointer/cursor needs design improvements
EXPECTATION: Pointer should match rest of design/brand direction.
RECOMMENDATION: Design TBD 

@thenadj @avrignaud (for tracking)

**Comment by MortimerGoro** [comment]
Some dev-chat we had about this:

- Using a circle/sphere could be a good idea but could impact precision

**Comment by thenadj** [comment]
Those are different. 196 is about creating a new visual design for the way the laser beam and cursor look. 221 is about repositioning the controller in space.

**Comment by cvan** [comment]
This seems quite important. I know it is a P0 already. Any user feedback or design suggestions here? I would suggest we do something similar to Oculus Browser's cursor, personally.

**Comment by avrignaud** [comment]
It's P0 (as you say), and very high on design's priority list as well. We should be seeing design for feedback/implementation soon.

**Comment by thenadj** [comment]
It's being designed right now.

**Comment by thenadj** [comment]
We have a design for this. See attached. Ideally we'd implement 3 different versions (colors) to compare. If time does not permit, then we'll just go with #1 white. 
[UIS-36 Pointer, Cursor, Laser Wand_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2255852/UIS-36.Pointer.Cursor.Laser.Wand_001.pdf)

**Comment by cvan** [comment]
@thenadj: these designs look *splendid*! very excellent work!

I'm thrilled to play with this wand in action :+1:
