### ISSUE TITLE
help users figure out how to exit immersive mode

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1966]
many users never figure out that they have to click the left-controller menu button to exit immersive mode. we should figure out how to teach that gesture. we should also explore ways we might consolidate all gestures on to a single controller.

Most likely way to do this is to have an interstitial screen as the user enters immersive mode. it could show the controller model with the correct button/gesture.

The interstitial should also include:
"[URL] is requesting information that can uniquely identify you, including your height and size of your room"
"You can control whether sites are allowed to enter immersive mode in Settings"

**Comment by feiss** [comment]
My first idea would be showing a modal popup when they click on the "ENTER XR" button, to remind how to exit immersive mode: ("Use MENU button on the LEFT controller to exit immersive mode") and an OK button to continue, and also a "Don't remind again" checkbox.

Another idea would be showing a tooltip whenever the user aims over the "ENTER XR" button. This is less intrusive than a popup, but would require detecting the actual button... not sure of the technical feasibility of that.

Another option to exit immersive mode (that would need to be teached, too) would be *press and hold* a specific button for some seconds (in any controller). A button that almost never is pressed for long time, like thumbpad/joystick. Although I kinda prefer the current option in the left-controller menu button, it's simpler.

**Comment by thenadj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UIS-16 Settings](https://trello.com/c/P52DGGmp/88-uis-16-settings)

**Comment by thenadj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UF-93 Exit immersive mode](https://trello.com/c/pZOfsuYc/481-uf-93-exit-immersive-mode)

**Comment by jvonitter** [comment]
This flow is finished, but note we won't do the long-press option shown in UF-93.
