### ISSUE TITLE
Hubs audio sounds like death robots on Vive Focus Plus

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#1968]
## Configuration

Firefox Reality version: 1.4.1
Firefox Reality build ID: 

Hardware: HTC Vive Focus Plus

## Steps to Reproduce

1. Enter a Hubs room with other users present and talking

## Current Behavior

The audio from the users sounds choppy/robotic.

## Expected Behavior

Smooth, clear audio.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by misslivirose** [comment]
@larsbergstrom - did you notice if audio playback was also bad by any chance or if it was just other users? I'll try to get a repro now that we have a Focus Plus

**Comment by jvonitter** [comment]
This looks like a hubs issue. Moved it over to https://github.com/mozilla/hubs/issues/1818
