### ISSUE TITLE
Controllers invisible after enter/exit VR on Focus Plus

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#1969]
## Configuration

Firefox Reality version: 1.4.1
Firefox Reality build ID: 

Hardware: HTC Vive Focus Plus

## Steps to Reproduce

1. Use a WebVR experience (e.g., Hubs) and enter and exit VR

## Current Behavior

controllers disappear. You will have just a laser.

## Expected Behavior

Controllers remain visible.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
It isn't entering and exiting VR. The controller models were not included with the APK. Fixed by https://github.com/MozillaReality/FirefoxReality/pull/1929

**Comment by larsbergstrom** [comment]
👍
