### ISSUE TITLE
Update Launcher icon to match Fennec Nightly icon layout.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#197]
The Fennec Nightly icon layout was just updated. We should probably match that (mostly making Fx logo a little smaller and centered).

**Comment by nancyhang** [comment]
@thenadj Just a heads up, I believe Manuel already reached out to you on this

**Comment by thenadj** [comment]
We'll take another stab at this. The previous file I sent had them centered but now that I see Randall's post of Nightly I want to make them smaller so they all match. We'll have the new version to you tomorrow.

**Comment by thenadj** [comment]
@keianhzo Since your day starts before ours, please go ahead and take a stab at matching the size and positioning of Nightly and add a screenshot to this issue and tag me in it (@thenadj). If it needs change we'll create it tomorrow.

**Comment by thenadj** [comment]
![screenshot 7](https://user-images.githubusercontent.com/13240857/42978367-594cd42a-8b81-11e8-9185-175b3ead1c1a.png)
Attached screenshot is the latest I have seen from Manuel and it looks good to me.

**Comment by thenadj** [comment]
Where do they show up? If they are app icons on hardware devices, then I'd probably keep the background white. I'd have to see them in their final place to make the right decision.
