### ISSUE TITLE
[French] The name of the "Clear Data" buttons is not fully visible for the "Cookies and site Data" and "Cached Web Content" options

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1974]
**[Affected Versions]:**
- Firefox Reality version 5-32821846 RC1 (58b59be3)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The app's language is set in "Francais".

**[Steps to reproduce]:**
1. Click the "Settings" button from the tray menu,
2. Click the "Privacy & Security" card.
3. Observe the "Clear Data" button for the "Cookies and site Data" option.

**[Expected results]:**
- The name is correctly displayed.

**[Actual results]:**
- The string displayed on the second line is cut off. 

**[Additional Notes]:**
- Attached is a screen shot of the issue:
![Mon10-14-2019_11-57-28 99](https://user-images.githubusercontent.com/40061643/66746289-0d724180-ee8a-11e9-8125-ace12350e277.png)

**Comment by jvonitter** [comment]
Ideally the button would expand to accommodate longer text. If that's problematic, we can ask for a shorter translation.

**Comment by keianhzo** [comment]
This has been fixed by #2609

**Comment by heres-maria** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9-40240151 (7e03c94) build. 
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
