### ISSUE TITLE
The “Try Again” button wrongly remains in a click state and the page is not refreshed if it’s long pressed

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1977]
**[Affected Versions]:**
- Firefox Reality version 5-32821846 RC1 (58b59be3)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Disconnect the device from the internet connection.
2. Try to visit a website.
3. Using the controller long press the “Try Again”. 
4. Release the button and observe the state and action. 

**[Expected results]:**
- The state of the button is reverted to default and the page is refreshed.

**[Actual results]:**
- The button remains in a click state and the page is not refreshed.

**[Additional Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1QixLQeuk7GxYkSTgjVnDdyLX4asXLGJj/view?usp=sharing).

**Comment by bluemarvin** [comment]
The error page is HTML and found here app/src/main/res/raw/error_pages.html. Probably should wait until GeckoView supports better error pages.
