### ISSUE TITLE
[Spanish][Russian] The "Firefox Reality Home (Default)" string is not entirely visible in the Display setting

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1978]
**[Affected Versions]:**
- Firefox Reality version 5-32821846 RC1 (58b59be3)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The app's language is set to Spanish or Russian.

**[Steps to reproduce]:**
1. Click the "Settings" button from the tray menu.
2. Click the "Display" card.
3. Observe the "Firefox Reality Home (Default)" string from the "Homepage" option.

**[Expected results]:**
- The entire string is correctly displayed and visible.

**[Actual results]:**
- Only the first words of the string are visible.

**[Additional Notes]:**
- Attached are screen shots of the issue for each language:
	- Spanish:
![HomepageSp](https://user-images.githubusercontent.com/40061643/66757978-05c09600-eea6-11e9-997c-bcf52bfb0d06.png)
	- Russian:
![HomepageRu](https://user-images.githubusercontent.com/40061643/66758060-30aaea00-eea6-11e9-9baf-0de07a66cbcd.png)

**Comment by jvonitter** [comment]
Ideally the list would expand to accommodate longer text. If that's problematic, we can ask for a shorter translation.

**Comment by keianhzo** [comment]
This specific setting is an editable one so the displayed text could have any length based on the user input. For this one I'd say it makes sense to show an ellipsis at the end of the user input string as we will never going to be able to anticipate it's size.

**Comment by heres-maria** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9-40240151 (7e03c94) build.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
