### ISSUE TITLE
[Russian] The "Foveation Level (App)" setting’s name is wrongly overlapping with the "Disabled" radio button

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1979]
**[Affected Versions]:**
- Firefox Reality version 5-32821846 RC1 (58b59be3)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The app's language is set to "Russian".

**[Steps to reproduce]:**
1. Click the "Settings" button from the menu tray.
2. Click the "Display" card.
3. Observe the "Foveation Level (App)" option.

**[Expected results]:**
- The name is correctly displayed.

**[Actual results]:**
- The name of the option is overlapping with the "Disabled" radio button. 

**[Additional Notes]:**
- Attached is a screen shot of the issue:
![HoveacionRu](https://user-images.githubusercontent.com/40061643/66758275-a3b46080-eea6-11e9-8927-9ac315ea993e.png)

**Comment by jvonitter** [comment]
Ideally the list would expand to accommodate longer text. If that's problematic, we can ask for a shorter translation.

**Comment by keianhzo** [comment]
This has been addressed in https://github.com/MozillaReality/FirefoxReality/pull/2680 The settings dialog has been made wider to better fit all supported languages.

**Comment by heres-maria** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9-40240151 (7e03c944) build.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
