### ISSUE TITLE
All FirefoxReality devices will appear in telemetry as "External" headsets

### ISSUE THREAD

**Issue by kearwood** [MozillaReality/FirefoxReality#198]
We need to extend the VR External Interface in GeckoView to support sending more specific identifiers for each of the headset types.

**Comment by daoshengmu** [comment]
@kearwood If you are worried about the device string in GeckoView telemetry, we already use our build info as the tag,
https://github.com/MozillaReality/FirefoxReality/blob/a512cdf5b47b0fc9491896d8f843d3b8db2e5c8e/app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java#L51.

Probably, we only need to care about the desktop platform.

**Comment by larsbergstrom** [comment]
@daoshengmu I believe this is complete now, right? Is this set to close?

**Comment by daoshengmu** [comment]
The headset names are `FirefoxReality_googlevr`, `FirefoxReality_wavevr`, and `FirefoxReality_oculusvr` in telemetry probes. So, I think we can close it.
