### ISSUE TITLE
[L10n] The "Allow Firefox Reality to send.." setting’s name is not entirely displayed

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1980]
**[Affected Versions]:**
- Firefox Reality version 5-32821846 RC1 (58b59be3)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The app's language is set to "Russian".

**[Steps to reproduce]:**
1. Click the "Settings" button from the tray menu.
2. Click the "Privacy & Security" card.
3. Observe the name of the "Allow Firefox Reality to send.." option.

**[Expected results]:**
- The name is correctly displayed.

**[Actual results]:**
- The name is not entirely visible. 

**[Additional Notes]:**
- Attached is a screen shot of the issue:
![P SRussian](https://user-images.githubusercontent.com/40061643/66758589-381ec300-eea7-11e9-8032-c0118c3dc493.png)

**Comment by jvonitter** [comment]
Ideally the list would expand to accommodate longer text. If that's problematic, we can ask for a shorter translation.

**Comment by Softvision-RemusDranca** [comment]
This issue is also reproducible with the "IT" locale. Attached is a screenshot of the issue:
![Privacy SecurityITDisabled](https://user-images.githubusercontent.com/40061643/71368212-f9487000-25af-11ea-822a-16dddff1adf9.jpg)

**Comment by keianhzo** [comment]
Already fixed by: https://github.com/MozillaReality/FirefoxReality/pull/2609

**Comment by heres-maria** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9-40240151 (7e03c944) build.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
