### ISSUE TITLE
The browser's "Back" button is wrongly actionable after opening a link in a new window from Context menu

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1982]
**[Notes]:**
- As a side effect for this issue, after clicking the "Back" button, the "Forward" button is not actionable and the website can't be accessed by clicking it. 

**[Affected Versions]:**
- Firefox Reality version 5-32821846 RC1 (58b59be3)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Open a website that has links available (eg: wikipedia.org)
2. Long click on one of the links.
3. Click the "Open in a New Window" option from the menu displayed.
4. Click the browsers "Back" button and observe the behavior.

**[Expected results]:**
- Nothing happens the button is not actionable.

**[Actual results]:**
- The Window's content is no longer displayed.

**[Additional Notes]:**
- This issue is reproducible if the links are opened from the "Bookmarks" and "History" pages.
- This issue is also reproducible with the 1.4 production version of Firefox Reality.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1lwNM6yXGl_6uhGC1CjcAHSUxav387B0m)

**Comment by MortimerGoro** [comment]
fixed via #2051

**Comment by Softvision-RemusDranca** [comment]
I've verified this issue and it's no longer reproducible with the Firefox Reality 6 RC1 (a83b2bf9) build. 
Tested on Oculus Quest and HTC Vive Focus Plus devices.
