### ISSUE TITLE
First-run FxA explainer page

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1984]
What are Firefox Accounts and why should people get them / use them in FxR?

Intent is to show some information the first time a user gets a version of FxR with FxA enabled.

**Comment by jvonitter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UF-92 What’s New for Accounts](https://trello.com/c/Q669mbqD/473-uf-92-whats-new-for-accounts)

**Comment by Softvision-GeluHaiduc** [comment]
Do we have an ETA on the final design for this?

**Comment by jvonitter** [comment]
@Softvision-GeluHaiduc probably end of next week. it will probably be a single page with some text, so hopefully won't need heavy testing.

**Comment by jvonitter** [comment]
@keianhzo you can get started on this. jenni will be delivering a UIS for the dialog, but it would be good to get ahead of it.

**Comment by jvonitter** [comment]
see section 200h: https://trello.com/c/25qaflLv/400-sl-7-componentsdialogs
