### ISSUE TITLE
The mobile version of a webpage is displayed even though the desktop user agent is selected in settings on newly created windows

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1985]
**[Affected Versions]:**
- Firefox Reality version 5-32821846 RC1 (58b59be3)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2
- Lenovo Mirage Solo - Android 8.0.0

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Go to Settings->Display and for the "User-Agent Mode" setting select the "Desktop" option.
2. Dismiss the menu and click the “New Window” button from the menu tray.
3. In the newly created window visit a website that supports both mobile and desktop versions. (e.g. facebook, twitter, twitch, ...)
4. Observe the loaded webpage.

**[Expected results]:**
- The desktop version of the webpage is displayed.

**[Actual results]:**
- The mobile version of the webpage is displayed.

**[Additional Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1sHTWIgOEbU3n5zPKFfFefzCxiyME2gAR/view?usp=sharing).

**Comment by jvonitter** [comment]
@MortimerGoro will this also be a problem for tabs?

**Comment by bluemarvin** [comment]
It should be easy to fix as part of the tabs work. Although I think we need to rethink how this setting and the URL bar switch work together. I don't think it is well defined, at least not to me.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 6 RC3 (1e9e4a85) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the correct version of a webpage is displayed depending on the user agent selected in settings, but only for new windows/tabs created.
