### ISSUE TITLE
The "Bookmarks" and "History" pages are not scrolled all the way down or up if scrolled using the scrollbar

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1986]
**[Affected Versions]:**
- Firefox Reality version 5-32821846 RC1 (58b59be3)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- Have enough feeds/bookmarks so that they exceed the pages view.

**[Steps to reproduce]:**
1. Click the "History" or "Bookmarks" button from the menu tray.
2. Click and hold the scrollbar on the right.
3. Scroll the page all the way down and observe the behavior.

**[Expected results]:**
- The page is scrolled all the way down.

**[Actual results]:**
- The page is not scrolled all the way down.

**[Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=14N9KW2S0SP3iKvctYvZB4bcrhm0tsr_c)

**Comment by daoshengmu** [comment]
We got a wrong number of the vertical value at `updateScrollPosition`[1].

After making
```
        LinearLayoutManager layout = (LinearLayoutManager)(recyclerView.getLayoutManager());
        layout.setSmoothScrollbarEnabled(false);
```
Although we have no scrollbar, it makes more sense.

[1] https://github.com/MozillaReality/FirefoxReality/blob/dc39a84e8c56705acf4107cce19cf7b6139dbf27/app/src/common/shared/org/mozilla/vrbrowser/ui/views/CustomFastScroller.java#L381.

**Comment by daoshengmu** [comment]
The root cause is because our scrollbar range is from [0 ~ mRecyclerViewHeight], it is supposed the origin is the top of the scrollbar, however, when moving the view with the scrollbar, we will use the center of scrollbar as its origin.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 7 RC4 (143a88ad) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the "Bookmarks" and "History" pages are scrolled all the way down or up if scrolled using the scrollbar.
