### ISSUE TITLE
[HTC] The app crashes after dismissing unsuccessful voice searches popups multiple times

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1988]
**[Affected Versions]:**
- Firefox Reality version 5-32821846 RC1 (58b59be3)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Click the “Voice Search” (microphone) button in the awesomebar.
2. Perform a voice search using sound but not words.
3. Dismiss the voice search popup.
4. Repeat steps 1 to 3 for approximately 6-7 times.
5. Observe the behavior.

**[Expected results]:**
- The voice search popup is dismissed.

**[Actual results]:**
- The app crashes.

**[Notes]:**
- On the HTC Vive Focus Plus the issue is reproducible only in multiwindow.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1ZU4RUwALL-0DgOrYkONSHAuvWWTBpbwH/view?usp=sharing).
- Attached the logcat file [here](https://drive.google.com/file/d/1IuCRm_d_NmpU15m-nT3nbKvOgmUA4b_r/view?usp=sharing).
- The crash report can be found [here](https://crash-stats.mozilla.com/report/index/b71800b3-36bc-4454-85ea-8615b0191016).

**Comment by bluemarvin** [comment]
From the crash report, this looks like some sort of HTC bug. It isn't a gecko thread that is crashing. `libwebrtc_jni.so` isn't a FxR component nor is it a part of GeckoView.

**Comment by bluemarvin** [comment]
I have found making a `pffft` sound seems to trigger the "I can't understand you" dialog.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 6 RC3 (1e9e4a85) installed on the HTC Vive Focus and Focus Plus headsets.
Now, the app doesn't crash after dismissing unsuccessful voice searches popups multiple times.
