### ISSUE TITLE
[HTC] No new voice searches can be performed in the same session if the first one was not understood

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1989]
**[Affected Versions]:**
- Firefox Reality version 5-32821846 RC1 (58b59be3)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Click the “Voice Search” (microphone) button in the awesomebar.
2. Perform a voice search using sound but not words.
3. Perform another voice search using words. (e.g. 360 videos)
4. Observe the behavior.

**[Expected results]:**
- The voice search is successfully performed.

**[Actual results]:**
- The voice search is NOT performed and the "Sorry! I could not understand. Please try again." message remains displayed.

**[Notes]:**
- The "Sorry! I could not understand. Please try again." message is intermittently displayed after dismissing the original pop up and clicking the microphone button.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1c4mpWp4sWwZdoWBTBsMPfPaXiDj1cDow/view?usp=sharing).
- Attached the logcat file [here](https://drive.google.com/file/d/10ATG-Ix1EyChvVQvifYANBJGShCxo-z-/view?usp=sharing).

**Comment by bluemarvin** [comment]
I can reproduce this in 1.3.2 on HTC Focus Plus.

**Comment by jvonitter** [comment]
@andrenatal We're not jumping on this yet, but when we do we might need your help

**Comment by andrenatal** [comment]
ok

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 6 RC3 (1e9e4a85) installed on the HTC Vive Focus and Focus Plus headsets.
Now, new voice searches can be performed in the same session.
