### ISSUE TITLE
The inactive window Play/Pause button is cut off in private browsing mode

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1991]
**[Affected Versions]:**
- Firefox Reality version 5-32821846 RC1 (58b59be3)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2
- Lenovo Mirage Solo - Android 8.0.0

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- Private Browsing mode is entered.

**[Steps to reproduce]:**
1. Navigate to any video and play it.
2. Click the “New Window” button from the menu tray.
3. Observe the inactive window Play/Pause button.

**[Expected results]:**
- The inactive window Play/Pause button is displayed correctly.

**[Actual results]:**
- The inactive window Play/Pause button is cut off at the right side.

**[Notes]:**
- Attached a screenshot of the issue.
![Tue10-15-2019_17-16-46 76 - Copy](https://user-images.githubusercontent.com/51400741/66914448-7c34d380-f01f-11e9-9ac1-5bce5f8c7ab2.png)

**Comment by jvonitter** [comment]
Either this was incidentally fixed or it's so subtle that I can't see it in FxR8

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue with the latest Firefox Reality version 8-40100049 (1500ba50) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
From what I saw the cut off from the Play/Pause button in PB mode is no longer there.
