### ISSUE TITLE
The suggestions scrollbar from the Awesomebar is wrongly displayed in the last scrolled position on subsequent searches

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1993]
**[Notes]:**
- As a result of this issue, the most suggestive results will not be displayed in the user's first view. 

**[Affected Versions]:**
- Firefox Reality version 5-32821846 RC1 (58b59be3)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2
- Lenovo Mirage Solo - Android 8.0.0

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Click inside the Awesomebar and insert a letter.
2. Scroll down the suggestions displayed. 
3. Click the "x" Close button from the right side of the Awesomebar.
3. Insert the same or a different letter.
4. Observe the position of the suggestions scrollbar.

**[Expected results]:**
- The scrollbar is displayed at the top.

**[Actual results]:**
- The scrollbar is displayed in the last scrolled position.

**[Additional Notes]:**
- The issue is reproducible even if the user navigates on new websites between searches.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1IyRIGsXzfU9KOjR5KsP0shLe8KZvm4gU)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 7 RC2 (ff64d298) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the suggestions scrollbar from the Awesomebar is displayed at the top of the view on subsequent searches.
