### ISSUE TITLE
On Oculus Go, the app will silently exit on first controller button press with first run of a clean install.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#200]
STR:

1) Unistall FxR: (% adb unistall org.mozilla.vrbrowser)
2) Install FxR (% adb install FirefoxReality-oculusvr-release-signed-aligned.apk)
3) Start FxR (% adb shell am start -a android.intent.action.LAUNCH org.mozilla.vrbrowser/org.mozilla.vrbrowser.VRBrowserActivity)
4) Click any where in the browser window

Expected results: item under pointer is clicked.
Actual results: Application quits with no log information

Investigating the issue, FxR is exiting in the call to AInputQueue_preDispatchEvent(app->inputQueue, event) on line 192 in Android/sdk/ndk-bundle/sources/android/native_app_glue/android_native_app_glue.c

This only happens on the first run of a clean install on the first interaction with a controller button. If the application is immediately relaunched every thing works as expected. I have placed logging around AInputQueue_preDispatchEvent and the function never returns.

**Comment by joshmarinacci** [comment]
Yep. This is the bug I saw too.

**Comment by MortimerGoro** [comment]
I found that this is fixed after I updated the Oculus SDK to v1.15 (https://github.com/MozillaReality/FirefoxReality/pull/303)
