### ISSUE TITLE
 Firefox Reality crash when try to launch

### ISSUE THREAD

**Issue by kaipinglee** [MozillaReality/FirefoxReality#2001]
## Configuration

Firefox Reality version: 1.4
Firefox Reality build ID: 

Hardware: Vive Focus plus

## Steps to Reproduce

1. Launch FxR on Vive Focus Plus HMD.
2. Sometimes FxR crashes after launch.
3. Sometimes FxR crashes after finishing a video on youtube and pressing the second one.
4.  Sometimes FxR crashes after suspend and resume the HMD.

## Current Behavior

FxR crashes and displays an error dialog as blow.
![2019-10-17 10_24_48-htceasap1 htc com tw_its_servlet_SqaLogDownloadServlet_fileName=UITS_324494_FA94](https://user-images.githubusercontent.com/31957856/66972984-09803280-f0c9-11e9-8d1c-632cfe2c159f.png)

## Expected Behavior

FxR launches and works correctly. 

## Error Logs and Stack Traces

[https://drive.google.com/open?id=181hIcT4K_a7y33Tt00rO8HhEi7JrpMO_](url)
<details open>

```
```

</details>

**Comment by jvonitter** [comment]
Thanks Kaiping. This matches a few other bugs we're tracking - #1446 #1959 #1770 #1658 
Some are fixed and being validated for our FxR6 release in November. I'm going to close this as a duplicate, but let me know if what you're seeing doesn't match any of those.
