### ISSUE TITLE
FirefoxReality runtime

### ISSUE THREAD

**Issue by 15102377525** [MozillaReality/FirefoxReality#2002]
The error displayed when packaging as APK or running the project is:

* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForGooglevrArm64Debug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process E:\android\FirefoxReality-master\app\build\intermediates\javac\googlevrArm64Debug\compileGooglevrArm64DebugJavaWithJavac\classes

Please provide the demo that can be run in Windows Android studio.

**Comment by jvonitter** [comment]
Not sure what this is, so I'm closing it. @15102377525 let me know if there's an actual issue here.
