### ISSUE TITLE
The on screen controls are slightly positioned above the eye level if entering immersive mode from a 3x size window

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2003]
**[Affected Versions]:**
- Firefox Reality version 5-32821846 RC1 (58b59be3)
- Firefox Reality version 6-32891835 (f856c035)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The window size is set at x3 size.

**[Steps to reproduce]:**
1. Navigate to any 360 video and enter immersive mode.
2. Press the trigger button on the controller.
3. Observe the position of the on screen controls.

**[Expected results]:**
- The on screen controls are positioned at the eye sight level.

**[Actual results]:**
- The on screen controls are positioned above the eye sight level.

**[Notes]:**
- The issue is also reproducible with any window sizes larger than x3.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1yqqruKv87TSLIUr7MsECdCvKEc-KBkJT/view?usp=sharing).

**Comment by jvonitter** [comment]
I'm ok leaving this as is
