### ISSUE TITLE
Copy&Paset doesn't popup when double clicking on the URL bar

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#2005]
## Configuration

Firefox Reality version: 6
Firefox Reality build ID: bcc0f45

Hardware: 
All

## Steps to Reproduce

1. Write something in the URL bar
2. double click to select all the text

## Current Behavior

The copy&paste menu doesn't pop up

## Expected Behavior

The copy&paste menu should pop up

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 6 RC2 (67257542) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the Copy/Paste context menu appears when double clicking on the URL bar.
