### ISSUE TITLE
The last selected projection option is wrongly highlighted after reentering immersive mode

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2009]
**[Affected Versions]:**
- Firefox Reality version 6-32891835 (f856c035)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Open a 360 video and play it in immersive mode.
2. Click the trigger button from the controller.
3. Click the projection button from the on screen controls.
4. Select an option from the projection menu displayed.
5. Exit and reenter again in immersive mode.
6. Reopen the projection menu and observe the displayed options.

**[Expected results]:**
- No option is highlighted.
OR
- The option reflecting the active projection mode is highlighted.

**[Actual results]:**
- The last selected option is highlighted even if the video is played in a different projection mode.

**[Notes]:**
- The issue is also reproducible if the option is selected in theater mode or for next videos played.
- This issue is also reproducible with the production version (v5) of Firefox Reality.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1i6QUU8oF5SV3taarOcYN8p346FDnNeHV)

**Comment by heres-maria** [comment]
I have verified this issue and it is no longer reproducible with the Firefox Reality version 7 RC3 (7b66fb14) build. The option reflecting the active projection mode is now highlighted. The default projection mode is now 360.
Tested on Oculus Quest (Android 7.1.1) and HTC Vive Focus Plus (Android 7.1.2).
