### ISSUE TITLE
Pages visted while using private browsing can be shown as a sugestion in the awesome bar.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#2012]
## Configuration

Firefox Reality version: 6
Firefox Reality build ID: f4384ca149463e6a64351245827944d87bb8678d

Hardware: Quest

## Steps to Reproduce

1. Clear history.
2. Enter private browsing
3. Visit a web site
4. leave private browsing
5. click on the URL bar and press `.` on the keyboard

## Current Behavior

The URL visited in private browsing is suggested in the awesome bar suggestion menu.
## Expected Behavior

URLs visited only in private browsing should not be used as suggestions in the pop up bar

**Comment by keianhzo** [comment]
@bluemarvin can't reproduce this using a4d79683b305d4a44ab26768e0829e2d03ae547c Could you confirm that it's still happening?
