### ISSUE TITLE
Keyboard language label intermitently disapears from the space bar in the keyboard

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#2013]
## Configuration

Firefox Reality version: 6
Firefox Reality build ID: f4384ca149463e6a64351245827944d87bb8678d

Hardware: Quest

## Steps to Reproduce

1. Open keyboard
2. Switch to a different language such as Polish
3. Start typing

## Current Behavior

The language type in the space bar key will disappear.
![org mozilla vrbrowser-20191017-150043](https://user-images.githubusercontent.com/3066/67051076-f97b4980-f0ee-11e9-9d64-69ab85f6385b.jpg)

## Expected Behavior

The language type should always be visible.
![org mozilla vrbrowser-20191017-150054](https://user-images.githubusercontent.com/3066/67051083-fd0ed080-f0ee-11e9-83b1-3a817770ee9f.jpg)

**Comment by jvonitter** [comment]
The language name shouldnt disappear

**Comment by keianhzo** [comment]
@jvonitter @thenadj This was in the **UIS-6_Keyboard_021.pdf** design spec: https://trello.com/c/VLsCI8iC:

<img width="639" alt="Screen Shot 2019-11-15 at 15 26 42" src="https://user-images.githubusercontent.com/837184/68950553-a8797680-07bc-11ea-97ad-d63b5e5a6e73.png">

Should we revert?

**Comment by keianhzo** [comment]
I still see this in [UIS-6_Keyboard_025.pdf](https://trello-attachments.s3.amazonaws.com/5a260c5d480978f87ffad6aa/5a94a051a70bcf7bc7ccea89/f128572db4311f4eb5e82cc89e9fdd18/UIS-6_Keyboard_025.pdf)

**Comment by MortimerGoro** [comment]
We also have to take into account that some languages use space bar to show the mode of some action (e.g. pinyin) so showing the language would block that at least temporarily.

We also have the `space` key label translated, so we want to show that on all languages?

This is how iOS resolves it:
- It shows the language level for 2-3 seconds
-  Then it shows the `space` label on the selected language

I added a blocked label until we decide the correct behavior (cc @jvonitter)

**Comment by jvonitter** [comment]
Thanks for the extra info! Let's leave it disappearing after a few seconds. Closing this!

**Comment by bluemarvin** [comment]
Can we at least make it fad out or something? The way it just abruptly disappears while typing looks like a bug

**Comment by MortimerGoro** [comment]
Also do we want to show `space` when the lang text dissapears?

**Comment by jvonitter** [comment]
I'll have Nadja look at it and update the spec with any recommended changes, then make a new ticket when we decide to make changes. For now it's fine as is.
