### ISSUE TITLE
Sometimes the pointer is drawn behind UI elements

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#2014]
## Configuration

Firefox Reality version: 6
Firefox Reality build ID: f4384ca149463e6a64351245827944d87bb8678d

Hardware: Quest

## Steps to Reproduce

1. Switch to private browsing
2. Click various elements on nav bar

## Current Behavior

The pointer is sometimes drawn behind the UI elements.
## Expected Behavior

The pointer should always be on top.

**Comment by jvonitter** [comment]
i cant repro this. if we get better STRs or a video that can help understand what's going on, we'll pull it in.

**Comment by bluemarvin** [comment]
I'm seeing this all the time now on all platforms. It is always the browser window that stops showing the pointer. It usually happens after a dialog has been dismissed.
