### ISSUE TITLE
The close window button is still visible when only one window is open

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#2021]
## Configuration

Firefox Reality version: 6
Firefox Reality build ID: 94c6c127e8bac27bd1c8a99537c5d13dc433052a

Hardware: Quest

## Steps to Reproduce

1. Launch FxR from clean install

## Current Behavior

![image](https://user-images.githubusercontent.com/3066/67127422-2e020a80-f1ae-11e9-87e1-0d6fd2c3e345.png)

## Expected Behavior

The close window button should not be visible.

**Comment by bluemarvin** [comment]
Also note that both of the arrows on either side of the close button are clickable. Clicking one of them makes bad things happen. such as https://crash-stats.mozilla.com/report/index/36c7aa2a-3e6e-4434-a422-520300191018

**Comment by MortimerGoro** [comment]
Closed via #2028
