### ISSUE TITLE
site thumbnail image is replaced with content feed thumbnail

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#2024]
## Configuration
Firefox Reality version: 6
Firefox Reality build ID: FirefoxReality-6-32911546
Hardware: Quest

## Steps to Reproduce
1. open tab panel.
2. click + icon to make a new tab.
3. in that tab's awesomebar, type something and hit "Go"
4. open the tab panel and note that two tabs are now showing - one with the feed and one with the google search results page.
5. select the content feed tab. notice it is brought to the foreground and the panel is dismissed.
6. open the panel again and see that both thumbnails show thow the content feed thumbnail image.

## Expected Behavior
Tab thumbnail should be correct

Video of this behavior [here](https://drive.google.com/open?id=16UfIElkJx-myNb4cCyKqNn4KYWqdGmVc)

```
```

</details>

**Comment by MortimerGoro** [comment]
Closed via #2028
