### ISSUE TITLE
title of FxR home tab is incorrect

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#2025]
In the tabs panel, the text under the content feed thumbnail says the URL of the content feed (webxr.today)

It should say "Firefox Reality Home"

![badtabtitle](https://user-images.githubusercontent.com/48839872/67135030-6c0d2780-f1ca-11e9-9385-ca89dc39adfd.PNG)

**Comment by MortimerGoro** [comment]
Closed via #2028
