### ISSUE TITLE
closed tab not disappearing from tabs panel

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#2026]
## Configuration
Firefox Reality version: 6
Firefox Reality build ID: FirefoxReality-6-32911546
Hardware: Quest

## Steps to Reproduce
1. open three windows and navigate to at least two different sites (so you can tell the windows/tabs apart)
2.  from the far right window, open the tab panel
3.  close the tab currently active in the far left window
4.  note the thumbnail changes to be the FxR home page
5.  look at the far left window and see that it is displaying the home page
6.  (tabs panel is still open in the right-most window) click the "X" button on the left-most window
7.  notice the window disappear. now look back to the right-most window

## Current Behavior
- The FxR home tab is still showing up in the tabs panel, even though the window (and visible tab) were closed (in step 7)
- Without closing the tabs panel, you can make the tab go away by clicking the tab button again.

[Video here](https://drive.google.com/open?id=1BfpvAlSFuLo_wRB9OhvnaSUGBKFPgOqC), for reference

## Expected Behavior
- If you click outside the tabs panel, it should close - this includes clicking on the close button in another window and clicking the tab button 
- If you close a window, the tab it's showing also closes. It should disappear from the tabs panel. You shouldn't see it disappear, however, because the tabs panel should have closed when you clicked outside of it.

**Comment by MortimerGoro** [comment]
Closed via #2028
