### ISSUE TITLE
Link is not added to History

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#2032]
## Configuration

Firefox Reality version: Dev Build 6
Firefox Reality build ID: d396a2e7

Hardware: 
Oculus Quest/Go.

## Steps to Reproduce

1. Go to http://webvr.info/samples/
2. Check history if this link be added to History->Today.
3.

## Current Behavior

That link doesn't be added to History.

## Expected Behavior

http://webvr.info/samples/ should be the first item because it is visited recently.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by jvonitter** [comment]
Working fine for me on a build from 10/18. @daoshengmu please update and let me know if this is still happening.
![org mozilla vrbrowser-20191021-163053](https://user-images.githubusercontent.com/48839872/67250462-5d1fb280-f420-11e9-8a46-862660bc670d.jpg)

**Comment by daoshengmu** [comment]
I got `E/places::ffi: Unexpected error: SqlError(SqliteFailure(Error { code: ConstraintViolation, extended_code: 1811 }, Some("FOREIGN KEY constraint failed")))` when I was trying to insert  http://webvr.info/samples/ link to the History. I guess the SqlLite changed its key or something. Should I force to delete the sql file on my device?

**Comment by daoshengmu** [comment]
> I got `E/places::ffi: Unexpected error: SqlError(SqliteFailure(Error { code: ConstraintViolation, extended_code: 1811 }, Some("FOREIGN KEY constraint failed")))` when I was trying to insert http://webvr.info/samples/ link to the History. I guess the SqlLite changed its key or something. Should I force to delete the sql file on my device?

That's very clear for now. I have a couple of links can't be added to History will show the same error log.

**Comment by daoshengmu** [comment]
@keianhzo Do you see this error log, `E/places::ffi: Unexpected error: SqlError(SqliteFailure(Error { code: ConstraintViolation, extended_code: 1811 }, Some("FOREIGN KEY constraint failed")))` before?

**Comment by keianhzo** [comment]
@daoshengmu do you have STRs? testing with http://webvr.info/samples/ in the current master logs the history entry successfully. We have a known issue when opening a new link in a tab in background ie. using the context menu. Might it be that?

**Comment by keianhzo** [comment]
@daoshengmu After some more testing I also was able to reproduce it consistently and it seems like a bug in Places when deleting a history entry. We also delete the history entries for a URL before adding so we don't have duplicated entries for the same URL, we just bump it to the top. I'll report and add the bug URL here.
