### ISSUE TITLE
History display order is reversed in Quest

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#2033]
## Configuration

Firefox Reality version: Developer Build version 6
Firefox Reality build ID: d396a2e7

Hardware: 
Oculus Quest

## Steps to Reproduce

1. Open History, I can see the order is from old to new instead of new to old.

## Current Behavior

I am not sure if doing a clean build could fix this problem because my Quest didn't do any updates for new versions in last few weeks. I think the history order should be from old to new instead of from new to old.

## Expected Behavior

It should be the same with Oculus Go. That is from new to old.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by jvonitter** [comment]
In the build i'm using from 10/18, history shows up in the right order. @daoshengmu can you update and check to see if this still happens for you?

**Comment by daoshengmu** [comment]
> In the build i'm using from 10/18, history shows up in the right order. @daoshengmu can you update and check to see if this still happens for you?

I was using the master branch source code to build, so I think mine is new enough.

**Comment by jvonitter** [comment]
i must have been confused by your comment in the bug. could you add the build you were using so we can try to repro?

**Comment by daoshengmu** [comment]
> i must have been confused by your comment in the bug. could you add the build ID you were using so we can try to repro?

sorry about that. d396a2e7

**Comment by daoshengmu** [comment]
Fixed by #2180
