### ISSUE TITLE
minor UX updates to tabs panel

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#2034]
minor UX updates to tabs panel -

- [ ] different "new tab" tab icon for tabs panel
- [ ] thinner outline around new tab box
- [ ] new active tab highlight treatment
- [ ] size/position is different from the settings panel. should be the same size/position.
- [ ] back button (<--) is the wrong size. should use the same icon at the same size as in Settings

Updates are in https://trello.com/c/bD4mkmpj/475-uis-59-tabs-panel

**Comment by jvonitter** [comment]
design has been updated

**Comment by jvonitter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UIS-59 Tabs Panel](https://trello.com/c/bD4mkmpj/475-uis-59-tabs-panel)

**Comment by MortimerGoro** [comment]
Closed via #2028
