### ISSUE TITLE
Clicking on survey show empty window while loading.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#2040]
## Configuration

Firefox Reality version: 6 
Firefox Reality build ID: 72a2790fd875fd1953540b2a5336893247bd6cea

Hardware: Quest

## Steps to Reproduce

1. Open settings dialog
2. Click survey

## Current Behavior

The window is empty while the survey loads
![Screenshot from 2019-10-22 17-10-11](https://user-images.githubusercontent.com/3066/67345302-6cb9fc80-f4ef-11e9-80e1-79fd4f0f4efe.png)

## Expected Behavior

Temporary window should be shown while page is loading.

## Notes
The bug link in the settings dialog also has this behavior while the help button does not.

**Comment by jvonitter** [comment]
if we can't get a fix for this in 6, we should pull the link out until we can fix it.

**Comment by bluemarvin** [comment]
I don't think it is a blocking issue. It's strictly aesthetic. The page does eventually load and is visible. The bug report link has the same behavior.

**Comment by bluemarvin** [comment]
This now works. Probably fixed by #2338
