### ISSUE TITLE
How does Firefox reality view the web console input log on VIVE

### ISSUE THREAD

**Issue by 15102377525** [MozillaReality/FirefoxReality#2042]
In the project, if there is an error in the loaded URL JS, how can I know where the error is and see the error log?

**Comment by MortimerGoro** [comment]
@15102377525 You can enable redirect console to logcat in Settings->Developer Options

**Comment by bluemarvin** [comment]
You can also enable remote debugging and attach the Firefox debugger to FxR.

**Comment by bluemarvin** [comment]
https://blog.mozvr.com/remote-debugging-firefox-reality/

**Comment by philip-lamb** [comment]
See also https://github.com/MozillaReality/FirefoxReality/wiki/Debugging
