### ISSUE TITLE
Migrate FirefoxReality project to community taskcluster deployment

### ISSUE THREAD

**Issue by owlishDeveloper** [MozillaReality/FirefoxReality#2059]
Hi!

I work on the Taskcluster team at Mozilla, and I'm writing to let you know about an upcoming change to our deployment of Taskcluster that will affect this project's use of Taskcluster for CI/CD.

We're splitting Taskcluster for Firefox and Taskcluster for community projects into separate deployments, which unfortunately involves a change for end users like this project.

The first step of the conversion work happened here: #1809, that PR upgraded the syntax of the taskcluster.yml file and Github integration to v1.

There are a couple next steps:

* changing the Taskcluster Github app used by this project to [this one](https://github.com/apps/community-tc-integration/)
* changing the provisionerId and workerType in your taskcluster.yml - I will be doing that for you in #2057.

After you swap the Github Integration over, merging that PR should get you in a good state.

Let me know if you have any questions or need guidance!

cc @djmitche

**Comment by bluemarvin** [comment]
Fixed by #2086
