### ISSUE TITLE
show number of tabs in tray

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#2061]
When a user is not logged in, we should show a badge with the number of tabs they have open on the tabs button in the tray.

If a user is logged in, we may not know how many tabs they have because we dont check for sent tabs until the tabs panel opens. So, if a user is logged in, we should replace the number badge with a sync badge.

**Comment by jvonitter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UIS-73 Tray with Library Buttons](https://trello.com/c/ENtbk8O4/352-uis-73-tray-with-library-buttons)

**Comment by thenadj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UIS-73 Tray](https://trello.com/c/rVGzj2OP/487-uis-73-tray)

**Comment by jvonitter** [comment]
@thenadj recommends that we dont do this. it's a deceptively complex feature that doesnt add enough user value. we can revisit if we get user feedback.
