### ISSUE TITLE
Settings buttons stop working

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#2064]
## Configuration
Firefox Reality version: 6
Firefox Reality build ID: 32971354

## Steps to Reproduce
Not totally sure how this happened, but I had been playing with the build for a while. I was able to sign in to my account successfully, so I know the buttons in the settings dialog worked at least once.

Now when I try to go into any of the settings categories, I can see the hexagon buttons responding to hover and press, but the the individual settings menus don't come up. Every so often one of them will work, but it's unpredictable. The privacy button specifically never works.

Video [here](https://drive.google.com/open?id=1YxenK_Ey1QSrDPNRNy2FeqpZib2eCjvQ)

**Comment by jvonitter** [comment]
Update - it turns out if i click the other buttons verrrry carefully while holding the controller in both hands to minimize pointer movement, The buttons work reliably (except for privacy - that never works).
Also if I click down, then move around on the button, the click seems to be released.

**Comment by bluemarvin** [comment]
We need to make the settings honey comb buttons sticky like the keys on the keyboard.

**Comment by bluemarvin** [comment]
I have a patch that increases the dead zone by the widgets resolution but even then, as long as the pointer was in the button when pressed, it should get the click no matter how far it moves.

**Comment by keianhzo** [comment]
I've seen this behavior but it's not particular to the settings but any widget. I need to do a bisect to see when this was introduced.

**Comment by keianhzo** [comment]
I've posted https://github.com/MozillaReality/FirefoxReality/pull/2072 that fixes the click on the privacy button issue but we have to investigate the widgets corruption issue.
