### ISSUE TITLE
Support loading an environment from a known location

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#207]
Suggestion: in order to make it easier for the art team to iterate on-device more quickly, it would be nice if we could probe a known location (e.g. `/sdcard/reality/FILE`) before loading the version of the environment in the app package. Then, they could iterate locally, `adb push` their changes, and restart the app to see it rather than having to drop it to the engineering team.

cc @MortimerGoro @keianhzo @thenadj

**Comment by MortimerGoro** [comment]
I'm going to work on this. It will be very useful for the designers and hopefully improve the design iteration process a lot.
