### ISSUE TITLE
missing clicks on some buttons

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#2076]
This is related to #2064, but applies more generally to buttons. Apart from the keyboard, buttons throughout the UI often miss my clicks. This has happened for a long time, so isn't new to fxr6.

Expected: all the buttons should work the same - they should reliably click when clicked.
additional video [here](https://drive.google.com/open?id=1YvwP6lC8Ju039XusrZat6-kSk4_TZp9R)

**Comment by MortimerGoro** [comment]
A new utility and settings honeycomb buttons have been fixed in #2096

**Comment by bluemarvin** [comment]
The honeycomb buttons were fixed. The remaining buttons can be fixed in v7 after an audit.

**Comment by keianhzo** [comment]
@jvonitter I can't reproduce this anymore, I think this might be fixed with the dialogs refactor.

**Comment by MortimerGoro** [comment]
Closing this one. It's been also covered with https://github.com/MozillaReality/FirefoxReality/pull/2633 and related PRs
