### ISSUE TITLE
tab thumbnails not showing up

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#2077]
Firefox Reality version: 6
Firefox Reality build ID: 32981359

**Steps to reproduce:**
1. With one window and one tab, go to a website
2. Find a link on that page, long press and select "open in new tab"
3. Find another link and do that again, so now you have three tabs open, but you're still looking at the page you went to in step 1.
4. Navigate to another site.
5. Switch to one of the other tabs
6. Open the tabs panel

**Results**: generic thumbnails are shown for the tabs from steps 2 and 3 and 5. even after loading the tabs into the foreground, the thumbnail is not updated.
**Expected**: once a page is loaded, it should have a thumbnail in the tabs panel. the generic thumbnail should only appear if we've never rendered the page before (or I suppose if the thumbnail we have is super old)

Video [here](https://drive.google.com/open?id=1mBGVlONroDxLgfHkLnVFYYKzHR35err7)

**Comment by MortimerGoro** [comment]
fixed in #1865
