### ISSUE TITLE
WebXR gamepad module support

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#2095]
As it is FxR which has knowledge of the platform, controllers, and their state, support for WebXR gamepad module will require FxR to report device characteristics and state via the VRShMem to Gecko WebXR core.

This will require:
* paying attention to the timing of implementation of WebXR gamepad module in Gecko and concomitant additions/changes in fields in VRShMem.
* new code to appropriately reporting the controller state to WebXR via the VRShMem.

**Comment by bluemarvin** [comment]
Fixed by #2521
