### ISSUE TITLE
The "Open in a New Window" button from the three dot menu has no background when opened from History or Bookmarks pages

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2099]
**[Affected Versions]:**
- Firefox Reality 6 RC1 (a83b2bf9)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- Have bookmarks and history feeds available in the History and Bookmarks pages.

**[Steps to reproduce]:**
1. Click the History or Bookmarks button from the tray.
2. Hover over a history feed/bookmark and click the three dot menu.
3. Observe the "Open in a New Window" button.

**[Expected results]:**
- The button is correctly rendered.

**[Actual results]:**
- The button's background is not displayed. 

**[Notes]:**
- The background is redisplayed after the button is hovered.
- Attached is a screen recording of the issue: 
	- Screen recording: [link](https://drive.google.com/open?id=1sX5UO_mhOErTTh0uNbvaOcVQZ7Vm-s1x)

**Comment by bluemarvin** [comment]
@keianhzo I think I saw that you were going to include this fix with another issue?

**Comment by keianhzo** [comment]
Not sure, anyways it's included now in this PR: https://github.com/MozillaReality/FirefoxReality/pull/2106

**Comment by Softvision-RemusDranca** [comment]
@keianhzo I'm not sure if the PR also includes the situation where the "Open in a New Window" button is no longer displayed when 3 windows are opened, but I think that it's worth mentioning.

**Comment by keianhzo** [comment]
@Softvision-RemusDranca Yes, the PR included that.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the Firefox Reality RC2 6-33052017 (67257542) build.
Tested on the Oculus Quest (Android 7.1.1), Oculus Go (Android 7.1.2), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2) devices.
