### ISSUE TITLE
Need to show FxR Nightly Version number in builds

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#210]
Hardware: all
Steps to Reproduce: N/A
Actual Behavior: Nightly version number not shown anywhere
Expected Behavior: Nightly version number is visible to end users in "About Firefox Reality" button, and is automatically submitted as part of bug report when user selects "Report an issue" from within FxR
Recommendation: Nightly version number is visible to end users in "About Firefox Reality" button, and is automatically submitted as part of bug report when user selects "Report an issue" from within FxR

**Comment by cvan** [comment]
the Nightly version or the git sha of Firefox Reality build?

**Comment by avrignaud** [comment]
I'm not sure of the difference? I'm imagining we need whatever version
number would most easily allow us to recognize the build the user
experienced an issue on. My understanding from Lars is that we'll be trying
to push up the nightly task cluster build to the store as "Nightly" - and
eventually have a beta version, and then a release version. So it might be
as simple as the date?

**Comment by larsbergstrom** [comment]
I had been considering just the Nightly/release version of the GeckoView AAR that we'd picked up. The goal was to have some version number we can tie back to a version of Gecko in case it's a platform bug we're picking up rather than a UI bug and we can know if it was fixed or not.

It looks like in Firefox desktop we use:
63.0a1 (2018-07-20) (64-bit)

Maybe the date is sufficient? So Firefox Reality 1.0 (2018-07-23) ?

**Comment by bluemarvin** [comment]
Every APK built on task cluster has a version number as follows:

        // The Google Play Store does not allow multiple APKs for the same app that all have the
        // same version code. Therefore we need to have different version codes for our ARM and x86
        // builds.
        // Our generated version code has a length of 8 (See tools/gradle/versionCode.gradle).
        // We will prefix our ARM builds with 1 and our x86 builds with 2. Our x86 builds need a
        // higher version code to avoid installing ARM builds on an x86 device with ARM
        // compatibility mode.


Where the version code is generated as such:

// This gradle scripts generates a "unique" version code for our release versions.
//
// The result of the version code depends on the timezone. We assume that this script will only be used
// for release versions and running on our build servers with a fixed timezone.
//
// The version code is composed like: yDDDHHmm
//  * y   = Double digit year, with 16 substracted: 2017 -> 17 -> 1
//  * DDD = Day of the year, pad with zeros if needed: September 6th -> 249
//  * HH  = Hour in day (00-23)
//  * mm  = Minute in hour
//
// For September 6th, 2017, 9:41 am this will generate the versionCode: 12490941 (1-249-09-41).
//
// Note that we only use this generated version code for builds we want to distribute. For local
// debug builds we use a fixed versionCode to not mess with the caching mechanism of the build
// system.


Our fixed local build number is 1 :)

-Randall

**Comment by bluemarvin** [comment]
This version number can be obtained in java code from BuildConfig.VERSION_CODE

**Comment by thenadj** [comment]
Attached is UIS-16 with an updated version number below the logo. Add second line with date. 
[UIS-16 Settings_010.pdf](https://github.com/MozillaReality/FirefoxReality/files/2220351/UIS-16.Settings_010.pdf)

**Comment by bluemarvin** [comment]
Can we not use point releases in our version number? Since mobile apps tend to release so often it is easer to just have a whole number. Otherwise we just end up with something like version 1.102 and the leading 1 is meaningless.

**Comment by daoshengmu** [comment]
I think the version number in builds need to be sync to https://product-details.mozilla.org/1.0/ after some discussions with release engineers.
