### ISSUE TITLE
Cannot build to Oculus Go with (MacOS) Android Studio 3.1.3

### ISSUE THREAD

**Issue by nbackous** [MozillaReality/FirefoxReality#211]
Hardware: MacBookPro w/OS X (10.13.6), Oculus Go

Steps to Reproduce: 

Follow steps in README.md
open project in Android Studio
Attempt build
Select Oculus Go connected via USB and start build

Actual Behavior: Build fails, this error is provided:

```
Build command failed.
Error while executing process /Users/studio/Library/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /Users/studio/git/firefoxreality/firefoxreality/app/.externalNativeBuild/cmake/googlevrDebug/armeabi-v7a --target native-lib}
ninja: error: '../../../../../gvr-android-sdk/libraries/jni/armeabi-v7a/libgvr.so', needed by '../../../../build/intermediates/cmake/googlevr/debug/obj/armeabi-v7a/libnative-lib.so', missing and no known rule to make it
```

Expected Behavior: Build succeeds, Firefox Reality launches on Oculus Go

Recommendation: n/a

**Comment by larsbergstrom** [comment]
Did you also install the gvr libraries? From the readme:

```
cd gvr-android-sdk && ./gradlew :extractNdk
```

**Comment by bluemarvin** [comment]
For building with Oculus, you have to go to the oculus developer site and down load the mobile SDK from there. The README could probably give a little more detail on how to set that up. It hasn't been a priority because side loading on the Go and other GearVR phones is so difficult.

**Comment by nategroadie** [comment]
I had assumed that the gvr libraries were only needed for Dayream devices. I went ahead and did it to see if if helped anything and it did, sorta, I get a successful build **_but_** I get a warning (presented across the entire screen rather than stereo, so its unreadable) that implies I need to have a Daydream device. The error cannot be dismissed with the Oculus Go controller and requires that I reboot the device. Any ideas?

As for needing the Oculus SDK, I've already downloaded everything I need to successfully build-to-device some Oculus test projects and to build from Unity, so I should be good to go, right?

**Comment by larsbergstrom** [comment]
Yes, though you may need to put the Oculus files into specific places in the build system. Also, make sure to change the build flavor from googleVR to one of the Oculus ones!

**Comment by philip-lamb** [comment]
Have tested and works as described in the documentation.

**Comment by cvan** [comment]
@nbackous: I see you said you followed the instructions in the README.

in the [**Setup instructions**](https://github.com/MozillaReality/FirefoxReality/blob/0005880/README.md#setup-instructions) section:

> *Open the project with [Android Studio](https://developer.android.com/studio/index.html)* then build and run it. Depending on what you already have installed in Android Studio, the build may fail and then may prompt you to install dependencies. Just keep doing as it suggests. To select the device to build for, go to `Tool Windows > Build Variants` and select a build variant corresponding to your device.

in Android Studio, if you change the **Build Variant** to `oculusvrArmDebug`, this should work. @nbackous: can you confirm?

thank you for filing :+1:
