### ISSUE TITLE
The “Pop-up Blocked” bubble is wrongly re-displayed after navigating back from a page with a pop-up

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2119]
**[Affected Versions]:**
- Firefox Reality version 6 RC1 (a83b2bf9)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to “http://popuptest.com/”.
2. Click on any of the pop-up techniques.
3. Click the “Back” button in the navigation bar.
4. Observe the behavior.

**[Expected results]:**
- The previous website is displayed.

**[Actual results]:**
- The previous website is displayed and the “Pop-up Blocked” bubble is re-displayed.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=13zk1HJuVTEaocpvFWv__7-Db6W9W_Nc9).

**Comment by bluemarvin** [comment]
Fixed by #2126

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 6 RC2 (67257542) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the "Pop-up Blocked" bubble is NOT re-displayed after navigating back from a page with a pop-up.
