### ISSUE TITLE
Enable option to toggle/remove "Flying Saucer" platform user stands on

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#212]
Hardware: All
Steps to Reproduce: N/A
Actual Behavior: Saucer platform appears under user in Space environment
Expected Behavior: Option exists to remove platform 
Recommendation: Offer option to toggle platform or make not applicable by not being necessary in environments

From YouTube review: https://t.co/BvNg8Wjg4y

**Comment by avrignaud** [comment]
We can investigate this as part of 1.1 custom environments. @thenadj - something to explore. Not sure if it makes sense to have a "platform" in future, but it could make sense for user to have no environment selected and just see basic/default loading one.

**Comment by thenadj** [comment]
Yes, we definitely want a platform in the future and allow people to use a 360 photo. @avrignaud Can you add this to the feature list? Trello card added: https://trello.com/c/MyNntEQF/135-environment-w-platform-for-360-photos

**Comment by avrignaud** [comment]
Added to 1.1 vision document, but we will likely need to reprioritize this
list based on Nancy's investigation into time/scope after we ship 1.0.

**Comment by cvan** [comment]
The flying saucer is no longer visible in the default environment (the forest) for 1.0, just FYI.

**Comment by larsbergstrom** [comment]
Will we do this for 1.1?

**Comment by keianhzo** [comment]
I think this was related to the initial space theme where there was a circular platform but there are no "flying saucers" anymore in any of the environments so I guess this can be closed.
