### ISSUE TITLE
Implement inertial scrolling

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#213]
Hardware: All
Steps to Reproduce: slide finger on touchpad to scroll window
Actual Behavior: window scrolls very quickly with barely any finger motion, doesn't dampen scroll at end when stopping
Expected Behavior: window scrolls smoothly with a wider/longer finger motion, and damps motion when ending
Recommendation:  Scroll window smoothly with a wider/longer finger motion, and dampen motion when ending

From Youtube Review: https://t.co/BvNg8Wjg4y

**Comment by MortimerGoro** [comment]
@bluemarvin Is inertial scrolling supported in GV?

**Comment by bluemarvin** [comment]
It is. You can even use it now. If you scroll by clicking and moving the controller it uses the inertia scrolling you can even press, fling, and release. It's not easy to do. To tie it into the touch pad might not be trivial. It might require some GV work to get is right since right now the touch pad is sending mouse wheel scroll events.

**Comment by thenadj** [comment]
Scrolling in Oculus browser in Oculus Go feels really good. It's more sensitive to smaller movements and accelerates nicely.

**Comment by keianhzo** [comment]
@bluemarvin Do we need work to be done in GV to implement this? Is there a GV related issue to track it from here?

**Comment by avrignaud** [comment]
Additional suggestion from UR: explore adding a dead zone on pad so simply touching pad doesn't immediately cause scrolling/reaction.

**Comment by MortimerGoro** [comment]
We landed the dead zone and improved the scrolling speed on Oculus.

I think it's good enough for V1.

**Comment by MortimerGoro** [comment]
Inertial scrolling will require quite work so it should go to 1.1

**Comment by MortimerGoro** [comment]
@thenadj we are going to publish a new build in Oculus betas very soon ;)

**Comment by cvan** [comment]
This seems fine with 6DoF-joystick scrolling. Can we close? Or do we think we need to handle this for 3DoF (Oculus Go) scrolling?
