### ISSUE TITLE
Use WebChannels for communicating with the FxA

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#2130]
**Is your feature request related to a problem? Please describe.**
Pre @grigoryk comment on: https://github.com/MozillaReality/FirefoxReality/pull/1973#issuecomment-544984467

> Since we're using Gecko, we should use WebChannels for communicating with the FxA web content, instead of intercepting URL loads.
> 
> This is basically all you need: https://github.com/mozilla-mobile/fenix/pull/4931/files#diff-bf0b57d467da0e3d5ef96c23fc828376R383
> 
> I'm assuming there shouldn't be a problem with installing a WebExtension in FxR, right?
> 
> Once you integrate the webchannels support, for free you get handling of "Choose what to sync" selection during FxA sign-up, which your current interceptor-based integration doesn't support. Also with a tiny bit of extra work, ability to add "Manage Account" button to your FxA settings page.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by keianhzo** [comment]
Waiting for info about where to get the webchannels extension.

**Comment by jvonitter** [comment]
@keianhzo is there an ETA for when we'll hear about this? or should i shift it to the backlog until we get news?

**Comment by keianhzo** [comment]
@jvonitter We have decided to talk to the AC team in the All-Hands and expose them the need of making AC more aware of FxR in general. This is part of that conversation. We should provide time estimation and a proposal to evaluate and maybe contribute.
