### ISSUE TITLE
FxR cross app dialog standarization

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#2131]
**Is your feature request related to a problem? Please describe.**
Dialogs in the app are using different styles that cause consistency issues. We should standardize the dialog styles based on the latest spec: https://trello.com/c/25qaflLv/400-sl-7-componentsdialogs

- [x] Permissions
- [x] Restart
- [x] PopUp Blocking
- [x] Crash dialog
- [x] Remove Max Windows dialog
- [x] Collect Voice samples
- [x] What's new
- [x] Sign out
- [x] Voice Search

**Describe the solution you'd like**
Create base dialog styles and reuse them in the different dialogs.

**Describe alternatives you've considered**

**Additional context**

**Comment by jvonitter** [comment]
@keianhzo do you have a size estimate for this?

**Comment by keianhzo** [comment]
@jvonitter added!
