### ISSUE TITLE
Keyboard UI polishing

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#2132]
**Is your feature request related to a problem? Please describe.**
There are some nits that we could address to improve the current keyboard implementation:

- [x] **Order of keyboards in the language selector**: We don't currently follow any order other the the integration time for he languages in the language selector in the keyboard (and the display and voice language dialogs). Any specific order we ant to follow?
- [x] **Refactor hardcored language strings from non_al10n.xml**: We still have some hardcoded language strings in non_al10n.xml. We should get rid of that and just retrieve the translated language string from localized strings forcing the desired locale.
- [x] **Better layout for the language selector panel**: The language selector panel int he keyboard is almost overflowing the keyboard size. We should consider another layout, maybe increasing the row number?
- [x] **German keyboard would also be used in Austria and Switzerland, so this should have included .at and .ch.**: https://github.com/MozillaReality/FirefoxReality/pull/2308#discussion_r347824936 
- [x] **Remove Spanish and Russian domains**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jvonitter** [comment]
@keianhzo do you have a size estimate for this?

**Comment by keianhzo** [comment]
@jvonitter added!

**Comment by jvonitter** [comment]
thanks! @keianhzo 
the domain button for the keyboard is already in 7 - #1914 
i'll pull this into 7 as well, though it still needs to be prioritized.
