### ISSUE TITLE
The texts of the data collection and use options are dynamically repositioned depending on the state of the switch buttons

### ISSUE THREAD

**Issue by heres-maria-sv-inactive** [MozillaReality/FirefoxReality#2133]
**[Affected Versions]:**
- Firefox Reality version 6 RC2 (67257542)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Open the "Privacy & Security" card from Settings.
2. Click the switch button of the "Allow Firefox Reality to send technical and interaction data to Mozilla" option.
3. Observe the text of the option.

**[Expected results]:**
- The text doesn't change its positioning between states.

**[Actual results]:**
- A word changes position from one row to another depending on the state of the option.
 
**[Notes]:**
- This issue is also reproducible for the "Allow Firefox Reality to send backlogged crash reports on your behalf" option.
- Attached is a screen recording of the issue.
![text](https://user-images.githubusercontent.com/53752296/68129060-94fb1f80-ff21-11e9-99b6-c78fb409aee1.gif)

**Comment by jvonitter** [comment]
This still happens in FxR8, but only for the last option.
