### ISSUE TITLE
Windows smaller than 2x lead to YouTube UI being non-responsive

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2134]
**[Affected Versions]:**
- Firefox Reality version 6 RC2 (67257542)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- Make sure the window size is set to 1x.
 
**[Steps to reproduce]:**
1. Go to [YouTube](https://www.youtube.com/).
2. Observe the website’s content.

**[Expected results]:**
- The website content fits the window size.

**[Actual results]:**
- The website's content doesn’t fit the window size.

**[Notes]:**
- The issue is not reproducible on the Oculus browser or Responsive Design Mode of Firefox desktop.
- Attached is a screen recording of the issue.
![youtube 3](https://user-images.githubusercontent.com/53752296/68129494-59148a00-ff22-11e9-8908-9c7b927803bb.gif)

**Comment by jvonitter** [comment]
@heres-maria does this only happen with YouTube? or all video sites / all sites generally?

**Comment by Softvision-GeluHaiduc** [comment]
Yes, this only happens with YouTube.

**Comment by MortimerGoro** [comment]
This is already fixed

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 8-40072114 (81fef4e7) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Due to the YouTube Web Extension refactor the issue is no longer reproducible.
