### ISSUE TITLE
Oculus Quest: Hardware Keyboard is Completely Inactive

### ISSUE THREAD

**Issue by zodywoolsey** [MozillaReality/FirefoxReality#2137]
## Configuration

Firefox Reality version: 5
Firefox Reality build ID: 2019-10-9

Hardware: 
Oculus Quest

## Steps to Reproduce

1. Connect bluetooth keyboard or usb keyboard
2. Open Firefox Reality browser
3. Attempt to type with the keyboard

## Current Behavior

Nothing happens

## Expected Behavior

Accept the input from the bluetooth or usb keyboard

## Possible Solution

Add code to handle hardware keyboard inputs

## Context

VR headsets will be the next computing platform. I can see the potential of replacing laptops with VR headsets in many situations. I tried to get some productive work done using Firefox Reality (since it's the highest quality browser in vr right now) but hardware keyboard inputs do not work. I was attempting to write code on Gitpod and do some homework in Blackboard for my college class, I had to resort to sideloading the regular firefox browser or to using remote desktop to connect to my pc.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
V6 scheduled for release November 12 has Bluetooth keyboard support. It is available now in the release candidates.

**Comment by zodywoolsey** [comment]
> 
> 
> V6 scheduled for release November 12 has Bluetooth keyboard support. It is available now in the release candidates.

I was unaware! Thanks! Apologies for the useless issues addition.
