### ISSUE TITLE
The websites opened from Tabs View are not logged in history

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2139]
**[Affected Versions]:**
- Firefox Reality version RC2 6-33052017 (67257542)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- Have multiple tabs added in Tabs view.

**[Steps to reproduce]:**
1. Click the Tabs View from the tray.
2. Select a tab from the list displayed.
3. Click the History button from the tray.
4. Observe the first feed added in the "Today" section.

**[Expected results]:**
- The website is logged in the History section.

**[Actual results]:**
- The website opened with the tab from Step 2 is not logged.

**[Notes]:**
- This issue is also reproducible if the tab is opened from Context Menu.
- The website opened is logged in History after a page refresh.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1dKPQVKo1qpZExRACxtWzrUdazkukbyyD)

**Comment by bluemarvin** [comment]
Opening an existing tab in a window is not expected to change the history feed. However opening a new tab from the context menu should add that tab to the history and is a bug.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the Firefox Reality 6-33100022 RC3 (1e9e4a85) build. Now the new tabs opened from Context menu are logged in history after they are opened.
Tested on the Oculus Quest (Android 7.1.1), Oculus Go (Android 7.1.2), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2) devices.
