### ISSUE TITLE
UR Finding: Users would like to choose between different 3D environments

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#214]
Hardware: All
Steps to Reproduce: N/A
Actual Behavior: cannot customize/select different 3D environments
Expected Behavior: can select between different 3D environments to personalize browser
Recommendation: make it so

**Comment by cvan** [comment]
I think this requires Design work. Forgive me if it is already filed and being worked on.

**Comment by cvan** [comment]
I see this was originally filed as issue #181. Shall we close one of them as a dupe?

**Comment by thenadj** [comment]
Yes, they seem like dupes. Once we have multiple environment we'll allow the user to switch them. We already have a preliminary design for this (UF-12 Settings_005) but will have to revisit in the future when we will officially work on this feature.

**Comment by avrignaud** [comment]
Moving out of 1.1, should be addressed by overall customization UI in future,

**Comment by thenadj** [comment]
Environment selector is in the latest Settings UI spec for Settings.
[UIS-16 Settings_014.pdf](https://github.com/MozillaReality/FirefoxReality/files/2539887/UIS-16.Settings_014.pdf)

**Comment by cvan** [comment]
looking good, thanks.

![image](https://user-images.githubusercontent.com/203725/47882875-2e13c980-dde8-11e8-99c1-2041936b25b6.png)

1. could we have each row follow the list style (with the _Iron_ 1pt line and the padding)?
2. could we change `Environment Override` (with the `On`/`Off` toggle) to be consistent with the other environment rows (with a radio field)? as is, enabling the `Environment Override` will invalidate the selected custom environment anyway, so it'd make sense to treat them the same.
3. could we put a heading/title at the top of the modal to say `Environment`? I think it'd be helpful for all the other settings to have a contextual title too.

great work on these Settings changes! 👍

**Comment by thenadj** [comment]
@jenniferhoang See comments above.

**Comment by jenniferhoang** [comment]
Thank you for the recommendations @cvan, Please see attached for updated changes. 
[UIS-16 Settings_015.pdf](https://github.com/MozillaReality/FirefoxReality/files/2555353/UIS-16.Settings_015.pdf)

1 and 2. Row dividers with list style & Environment override UI change
![screen shot 2018-11-06 at 1 50 17 pm](https://user-images.githubusercontent.com/41343760/48099586-ee2c5800-e1d4-11e8-96fe-6130aa817114.png)

3. Dialog Menu title spec
![screen shot 2018-11-06 at 1 51 54 pm](https://user-images.githubusercontent.com/41343760/48099579-e79de080-e1d4-11e8-9678-dbc04ea450a4.png)

**Comment by MortimerGoro** [comment]
Implemented in https://github.com/MozillaReality/FirefoxReality/pull/984
