### ISSUE TITLE
[Intermittent] The app doesn't recognize a successful login into an FxA account

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2142]
**[Notes]:**
- From 10 login attempts, 7 failed.

**[Affected Versions]:**
- Firefox Reality version RC2 6-33052017 (67257542)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The app is freshly install or updated.
- Have a valid FxA account.

**[Steps to reproduce]:**
1. Open the app and click the "Sign in" button from the prompt displayed.
2. Log in with the FxA account from prerequisites.
3. Observe the behavior after logging in.

**[Expected results]:**
- The manage FxA account prompt is displayed.

**[Actual results]:**
- Nothing happens and in Settings the "Sign Into Account" string is displayed on the FxA card.

**[Additional Notes]:**
- This issue is mostly reproducible on the Quest devices. On the HTC devices I was only able to reproduce it 2 times from 10 attempts.
- This issue is reproducible with an existing and also with new created FxA accounts.
- I was able to reproduce this issue even if the log in was performed from "Settings".
- In some attempts the Manage your account prompt was not displayed, even if the login was successful and the account was visible in settings.
- The login is successful after more than 1 attempt.
- Attached are a screen recording and the logcat of the issue.
	- Screen recording: [link](https://drive.google.com/open?id=1noiptvD2v3vRlJJLxA4jN4ps5j5BA08k)
	- Logcat: [link](https://drive.google.com/open?id=1GMTH3qy2_z-zxUM8uZ6xDXz-8q9L2PyM)

**Comment by bluemarvin** [comment]
We will try and fix this for v6 but may be server side related.

**Comment by keianhzo** [comment]
I've been trying to reproduce this one but I couldn't trigger the error after a several times in a row in both quest and the emulator. I tried to use different network speeds but that didn't help.

**Comment by keianhzo** [comment]
@Softvision-GeluHaiduc we added some logs in the app to track this issues. If you bump into this again, please share the logcat.

**Comment by Softvision-GeluHaiduc** [comment]
@keianhzo I managed to reproduce the issue using Firefox Reality version 6 RC5 (33a031c7) following these steps:
1. Disconnected the internet.
2. Sign Out of the account in VR.
3. Reconnected to the internet.
4. Re-logged in with the same account.

I started the logcat after step 3 (it took a few tries to reproduce).
Attached the logcat file [here](https://drive.google.com/open?id=1z3uPOzmk5tihFYUzZ5aumZ9bwUvKK8JN).

**Comment by keianhzo** [comment]
I cannot reproduce it following this STRs but I've sent a debug build to @Softvision-GeluHaiduc so logs are not stripped and we can get a full log.

**Comment by Softvision-GeluHaiduc** [comment]
I managed to reproduce the issue. The logcat file can be found [here](https://drive.google.com/open?id=1EbWYOCcaXyx29SwLujfAzikaTCJy5I0U), and the screen recording [here](https://drive.google.com/open?id=1eBBJ-IG3MBD2MDv0ROVAcrYpHxe8kZEH).

**Comment by keianhzo** [comment]
Thanks @Softvision-GeluHaiduc So this seems not tp have anything to do with slow or intermittent internet connection, it has to do with calling `beginAuthenticationAsync` several times in a row. That seems to mess up the FxA login flow.

The STRs to reproduce are:
- Launch FxA
- Open settings
- Click on the FxA login button several times in a row before the panel is dismissed
- Complete the login flow

Result:
- Login flow is not completed

Expected:
- Login flow is completed

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 7 RC1 (b772e6d7) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the app recognizes every successful login into an FxA account.
