### ISSUE TITLE
Install on Gear VR??

### ISSUE THREAD

**Issue by ScottWitte** [MozillaReality/FirefoxReality#2149]
Installed FxR from the Oculus store. Last worked with it in August. I recently went to test something and it was no longer in the library. I went to the Oculus store from the Gear VR Oculus environment and it is no longer there. Then downloaded an APK from the release page to sideload with ADB. It failed because.... it was already installed. I uninstalled that version via ADB and installed the new download with "success." But, it doesn't appear in the library and doesn't appear on an apps page on the phone. Tried with several of the Oculus/ARM versions in the 1.4 and 5.0 releases with no luck.

Any idea what is going on?

And, is there a better place to ask such questions? Seems a little off-topic here.

**Comment by jvonitter** [comment]
Hey @ScottWitte 
We unfortunately don't currently support Firefox reality on Daydream or GearVR phones - only on standalone VR devices. You are welcome to sideload (https://github.com/MozillaReality/FirefoxReality/wiki/Sideload ) a build, but unfortunately the engineering costs of supporting so many different phone types directly are too large for the team right now.
