### ISSUE TITLE
The “Sync” button from Bookmarks or History remains in a hover state after it is clicked and syncing is complete

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2152]
**[Affected Versions]:**
- Firefox Reality version 6 RC2 (67257542)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- Make sure an FxA user is logged in.

**[Steps to reproduce]:**
1. Click the History or Bookmarks button from the menu tray.
2. Click the “Sync” button and wait for syncing to be done.
3. Observe the “Sync” button.

**[Expected results]:**
- The button border, icon and text have a fog color and the background has a grey color.

**[Actual results]:**
- The button has a hover state.

**[Notes]:**
- The button remains in a hover state until it is hovered again.
- Attached a screenshot of the issue.
![Tue11-05-2019_10-12-51 75](https://user-images.githubusercontent.com/51400741/68199633-15c02700-ffc7-11e9-93cb-4c58883cfe80.png)
![Tue11-05-2019_10-13-01 22](https://user-images.githubusercontent.com/51400741/68199647-1a84db00-ffc7-11e9-8d35-db1a76d7ddca.png)

**Comment by daoshengmu** [comment]
@keianhzo It looks like the FxA sync UI logic are disabled by `BookmarksView::ACCOUNTS_UI_ENABLED` and `HistoryView::ACCOUNTS_UI_ENABLED` in #2183. If so, it seems like this issue will not happen anymore. Should we close this?

**Comment by keianhzo** [comment]
Yep, I forgot to add this one to the fix list in the PR. We can close it as we are not showing that UI anymore.
