### ISSUE TITLE
The “FxA Account" card has the wrong icon

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2153]
**[Affected Versions]:**
- Firefox Reality version 6 RC2 (67257542)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Make sure an FxA user is NOT logged in

**[Steps to reproduce]:**
1. Click the “Settings” button from the menu tray.
2. Observe the icon for the “FxA Account" card.

**[Expected results]:**
- The card has a sync icon symbolized by 2 arrows pointed to each other aligned in a circle. 

**[Actual results]:**
- The card has a user icon.

**[Notes]:**
- The expected icon can be found in issue #1589.

**Comment by bluemarvin** [comment]
This is the correct icon. It was changed at some point to match desktop.
![Screenshot from 2019-11-05 08-17-29](https://user-images.githubusercontent.com/3066/68225131-c9fc8600-ffa4-11e9-8569-0500d789daf0.png)
