### ISSUE TITLE
The “Sync” switch buttons for bookmarks and history from the “Manage Account” dialog switch back automatically

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2155]
**[Affected Versions]:**
- Firefox Reality version 6 RC2 (67257542)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened and the Settings menu is displayed.
- Make sure an FxA account is logged in.

**[Steps to reproduce]:**
1. Click the “FxA Account" card.
2. Click the “Sync” switch button for bookmarks or history.
3. Observe the switch button.

**[Expected results]:**
- The switch button remains in the position it was set.

**[Actual results]:**
- The switch button sometimes switches back to the state it was before.

**[Notes]:**
- The buttons are switched back to their initial state even if the “Manage Account” dialog is dismissed.
- The behaviour is inconsistent, sometimes only one button switches back, sometimes both.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1UN0i6MvRajG2KiGbKcfNiLn1vQSNpEUN).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 6 RC3 (1e9e4a85) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Unfortunately the "Sync" switch buttons for bookmarks and history are still switch back automatically, but only after the "Manage Account" dialog is dismissed.

**Comment by keianhzo** [comment]
We have updated the UI and this should happen anymore.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 6 RC4 (f2e90af0) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
However because of the changes 2 new issues appeared that are logged in #2202 and #2203.
