### ISSUE TITLE
On certain websites the play/pause button is wrongly displayed under an unfocused window even if there is no active video

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2158]
**[Affected Versions]:**
- Firefox Reality version 6 RC2 (67257542)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
 
**[Steps to reproduce]:**
1. Navigate to the [YouTube homepage](https://www.youtube.com/).
2. Open a new window.
3. Observe the components displayed under the inactive YouTube window.

**[Expected results]:**
- Only the window’s title is displayed.

**[Actual results]:**
- The play/pause button is displayed even if there is no active video.

**[Notes]:**
- This issue is reproducible for any window position as long as it is unfocused.
- Nothing happens if the “Play/Pause” button is clicked.
- I was also able to reproduce this issue on the Netflix homepage.
- I was not able to reproduce this issue on the Twitch homepage.
- It may take a few seconds for the button to appear.
- Attached is a screen capture of the issue.
![youtube play 1](https://user-images.githubusercontent.com/53752296/68211296-f97cb400-ffdf-11e9-9cff-77f6706a2f0a.gif)

**Comment by MortimerGoro** [comment]
Related issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1524092

**Comment by heres-maria** [comment]
I have verified this issue and it's no longer reproducible with the Firefox Reality 7-33130007 RC1 (b772e6d7) build. The play button doesn't appear on pages with no videos.
Tested on the Oculus Quest (Android 7.1.1), Oculus Go (Android 7.1.2) and HTC Vive Focus Plus (Android 7.1.2) devices.
