### ISSUE TITLE
Enable Curved Windows (and explore whether to also support flat as option)

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#216]
Hardware: All
Steps to Reproduce: N/A
Actual Behavior: flat window
Expected Behavior: option to enable curved window, and presumably control curvature
Recommendation: enable option to toggle between flat and curved windows, and explore whether curvature window control makes sense

From YouTube video review: https://youtu.be/YfF0R2v0kEk?t=250

**Comment by thenadj** [comment]
Trello card created for this issue. We'll explore designs for this as part of the v1.1 work. 
https://trello.com/c/IlzAFoYG/133-curved-browser-window-control

**Comment by MortimerGoro** [comment]
- It might affect multiple window support or window placements designs. Does a curved design work if you don't look at it from the center? how can you move a curved window if you need to be on the center?
- Resizing may be affected too

**Comment by thenadj** [comment]
@avrignaud What's the verdict on this? Seems like window positioning and cylindrical/curved windows don't play well together.

**Comment by larsbergstrom** [comment]
I believe that we will not be doing this for v1.1. We are working on purely flat layers for 1.1, which will enable us to experiment with / investigate for post-1.1.

**Comment by cvan** [comment]
a lot of folks complain about the curvature on [Reddit](https://www.reddit.com/r/OculusGo). personally, I don't find it helps readability, but I'm also not reading comic books or Wikipedia articles for hours, so I'm probably not the best person to weigh in on this. if we do allow the option, I'd recommend it be buried as a non-default preference in the Settings.

**Comment by cvan** [comment]
cc @joshmarinacci: Might be nice to promote here on this Reddit thread this upcoming feature in the next release of FxR: https://www.reddit.com/r/OculusGo/comments/asegfn/oculus_browser_with_a_flat_screen_rather_than/
