### ISSUE TITLE
Newly opened videos can't be played using the inactive window's "Play" button 

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2160]
**[Affected Versions]:**
- Firefox Reality version 6 RC2 (67257542)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2

**[Prerequisites]:** 
- The headset is turned on and the browser is opened.
 
**[Steps to reproduce]:**
1. Navigate to [YouTube](https://www.youtube.com/).
2. Open a video but don’t begin playing it.
3. Open a new window from the tray.
4. Click on the play button displayed under the inactive window.
5. Observe the video.

**[Expected results]:**
- The video begins playing.

**[Actual results]:**
- The video doesn’t begin playing.

**[Notes]:**
- This issue is only reproducible if the user doesn’t begin playing the video by using the YouTube play button first.
- This issue is reproducible for any window position.
- Attached is a screen recording of the issue.

![youtube play 2](https://user-images.githubusercontent.com/53752296/68216710-030b1980-ffea-11e9-9334-21e28fbc6104.gif)

**Comment by bluemarvin** [comment]
I believe this is a result of this GeckoView bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1524092

**Comment by keianhzo** [comment]
We have decided to only show the media controls if the media has already been played. The linked PR should fix this issue.

**Comment by heres-maria** [comment]
I have verified this issue and it's no longer reproducible with the Firefox Reality 7-33130007 RC1 (b772e6d7) build. The play button doesn't appear until a video is played.
Tested on the Oculus Quest (Android 7.1.1), Oculus Go (Android 7.1.2) and HTC Vive Focus Plus (Android 7.1.2).
