### ISSUE TITLE
Browser window does not have round corners

### ISSUE THREAD

**Issue by thenadj** [MozillaReality/FirefoxReality#220]
Hardware: Oculus Go
REPRODUCE: go to default browsing window
CURRENT BEHAVIOR: the browser window has no rounded corners
EXPECT: should be rounded like in UIS-21
RECOMMENDATION: Round the corners 5px
[Bug-1 Rounded Corners on Browser Window_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2214725/Bug-1.Rounded.Corners.on.Browser.Window_001.pdf)

**Comment by cvan** [comment]
The designs look nice. And I like the corners. The curvature could cause undesired, unexpected behaviour for existing sites for web developers.

The Oculus Browser, Samsung Browser, and [Google VR Browser](https://youtu.be/qhVfFnhOELg) all do not have curved corners on the browser windows.

Is there an advantage to using curved corners, aside from aesthetics?

**Comment by bluemarvin** [comment]
This should probably be a low priority for 1.0 if we do decide to go forward. The browser content is not generated by android widgets so we have far less control over its appearance. There a two way I can think of for creating rounded corners on the browser window and neither is a trivial amount of work.

1) A polygon mesh with rounded corners that we map the browser texture on to.
2) A rounded corner mask we apply in a custom shader made for browser windows.

**Comment by avrignaud** [comment]
@bluemarvin Design was previously done on this one. Is there any more design discussion to be had, or can we assign for implementation? Either of your possible solutions seems fine - we'd lean on your recommendation.

**Comment by bluemarvin** [comment]
Web pages should not have rounded corners. I thought we weren't going to do this. I believe @cvan had thoughts on this.

**Comment by avrignaud** [comment]
I don't think it's the actual page, it's the frame edge around the page? Is this an opinion, or is there a technical reason for this to consider? Thanks!

**Comment by bluemarvin** [comment]
Currently pages don't have a frame, the content is edge to edge.

**Comment by avrignaud** [comment]
Ok, gotcha. What effort would be involved to add a frame such that the design could be implemented? Is it the same work you mention above (pasted below)? Or is there additional extra effort? Basically trying to understand the total effort/time to implement the current design. (Note: not saying we absolutely will/must do that design - am trying to understand the effort to do so so we can discuss value/tradeoffs). 

    A polygon mesh with rounded corners that we map the browser texture on to.
    A rounded corner mask we apply in a custom shader made for browser windows.

**Comment by bluemarvin** [comment]
Adding a frame would be easier as it would be very similar to the resize handles. But I think it would look weird and server no functional purpose other than take up space.

**Comment by avrignaud** [comment]
Ok, have a better understanding of the issues involved here now. At a high level, making a square web page work well within a frame with curved corners has challenges:
- web page needs to be inset by some amount from frame - might look odd
- inset web page would have a border around which needs to be addressed - is it matching color of page? Clear? Something else?
- control affordances become difficult to use - is user aiming for corner of window? Of web page itself?
- Finally, we are likely to implement curved windows to help improve font rendering and perf - curved corners on those might be odd as well.

All-in-all, feels like this may not make sense to implement at this time. Will close, and we can revisit if we find it makes sense in future.
