### ISSUE TITLE
Companion App for Keyboard Input?

### ISSUE THREAD

**Issue by moocow1452** [MozillaReality/FirefoxReality#2200]
**Is your feature request related to a problem? Please describe.**

Using a VR controller to hunt and peck for keys is less than ideal for anything more involved than a web search. Can we do better with what we have? 

**Describe the solution you'd like**

A companion app or web solution that would allow users to input text on a phone, and have that register as a Text Input within Firefox Reality. Maybe some autocorrections and feedback could be displayed in VR, or it's just a dumb text pipe.

**Describe alternatives you've considered**

Normal keyboards are difficult to use in VR, due to not having a visual reference on where the keys and keyboard are, and often being in a position that is not conducive to normal typing. Specialized hardware such as TAP is cost prohibitive and requires a learning curve.

**Additional context**

This was a kind of off the cuff idea, and may not be anywhere close to feasible. But I like the idea of VR enhanced productivity, and existing input methods are lacking. But I can do a decent job at typing blindly into a phone and getting what I want to come out of it. Could this be something to look into for VR?

**Comment by jvonitter** [comment]
hi there @moocow1452! thanks for the suggestion - i'll put this into the backlog for us to investigate in the future.
also note that we do plan to add some predictive text functionality to help decrease the amount of hunt-and-peck folks have to do. you can follow that effort here - https://github.com/MozillaReality/FirefoxReality/issues/413
