### ISSUE TITLE
The "History" title and the "Clear History" button is wrongly displayed on the empty History page

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2207]
**[Affected Versions]:**
- Firefox Reality Firefox Reality 6-33112229 RC4 (f2e90af0) build.

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Open the History page from the tray.
2. Delete all the history feeds.
3. Observe the top of the empty History page.

**[Expected results]:**
- The "History" title and the "Clear History" button are NOT displayed.

**[Actual results]:**
- The "History" title and the "Clear History" button are displayed.

**[Notes]:**
- As a side effect of this issue the "You can access your browsing history here" string from the bottom of the page is slightly cut for the "y and g" letters on the bottom.
- The "Clear History" button is not actionable on the empty History page. 
- Attached is a screen shot of the issue:
![Fri11-08-2019_11-12-50 08](https://user-images.githubusercontent.com/40061643/68481953-25e33b00-0241-11ea-99d9-53da26a6177d.png)

**Comment by keianhzo** [comment]
I think this is the expected behaviour, the title is visible and the clear button is disabled.

**Comment by Softvision-RemusDranca** [comment]
This 2 elements are not displayed in version 5 of the app. And based on the latest mockups from trello (https://trello.com/c/CPyXxcZp/371-uis-78-history) the Empty History page only had the "Sync" button which is now moved into Manage Account card.

**Comment by jvonitter** [comment]
Remus is correct - please use the spec he referenced (specifically section 200).
As a side note, we very very rarely have disabled buttons. If you find yourself putting one in, it's a good idea to double check the spec.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 7 RC1 (b772e6d7) build. The "History" title and the "Clear History" button are no longer displayed on the empty History page.

Tested on the Oculus Quest (Android 7.1.1), Oculus Go (Android 7.1.2), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2) devices.
