### ISSUE TITLE
Controller placement needs to be adjusted

### ISSUE THREAD

**Issue by thenadj** [MozillaReality/FirefoxReality#221]
Hardware: Oculus Go
REPRODUCE: Home
CURRENT BEHAVIOR: Controller feels placed too high in space
EXPECT: Controller to be in the same placement in VR as in real life
RECOMMENDATION: Move controller 10cm down and 10cm closer

**Comment by cvan** [comment]
I think this is a dupe of issue #196. Feel free to close if you feel it is.

**Comment by thenadj** [comment]
Those are different. 196 is about creating a new visual design for the way the laser beam and cursor look. 221 is about repositioning the controller in space.

**Comment by avrignaud** [comment]
@thenadj Can you take a look and see if this is still an issue?

**Comment by thenadj** [comment]
@avrignaud Nope, that has been fixed a long time ago. Closing issue.
