### ISSUE TITLE
Static text should not remain highlighted after it's copied

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#2215]
Question from QA: `Should the static text remain highlighted after it's copied? On desktop it remains highlighted and on mobile it's not and I wanted to be sure on what the right behavior should be in FxR`

From what I have tried:
- Desktop: it remains highlighted
- iPhone mobile: it remains highlighted
- Android mobile: it's dimissed

The context menu can also be cleared using the back button, But just found that the back button clears if there is a Context Menu but not if there is a selection without context menu.

We need a UX decision
**Decision is: highlight should dismiss after copy**

**Comment by jvonitter** [comment]
@thenadj I think i prefer the highlight be dismissed after it's copied. do you agree?

**Comment by thenadj** [comment]
@jvonitter I agree.
