### ISSUE TITLE
[Intermittent] The app freezes or has bad performance issues after opening multiple unloaded tabs from Tabs View 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2227]
**[Affected Versions]:**
- Firefox Reality 6 RC5 (33a031c7) build.

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to a website with multiple pages available (ex: https://www.youtube.com/)
2. Long click on the suggested videos and click the "Open in a new Tab" button.
3. Perform Step 2 for approximately 10 videos.
4. Click the Tabs View button and open the added tabs one after another.
5. Observe the behavior after opening the tabs.

**[Expected results]:**
- The tabs are successfully opened and no performance issues occur.

**[Actual results]:**
- The app freezes or has bad performance issues.

**[Notes]:**
- This issue mainly affects the Oculus devices.
- On the HTC devices the issue only affects the performance of the app but in a lot smaller effect in comparison with the Oculus devices.
- Here is a link with the logcat where the Oculus Quest device totally froze: [link](https://drive.google.com/open?id=1N-MOnJT1OCBrhQhj0LPz0Oy-EItOJxw8)
- Attached is a screen recording and the logcat of the issue: 
	- Screen recording: [link](https://drive.google.com/open?id=1Fgx83jQzP4-_dOoLS86VDUk1TV_gMi72)
	- Logcat: [link](https://drive.google.com/open?id=1itGh2T3V0TO50ZETCDThowSdyGxAxnsu)

**Comment by Softvision-RemusDranca** [comment]
Please let me know if extra testing is needed for this issue or if the logcats don't provide enough information. I came across it late in the day and it's intermittently reproducible. The first time I reproduced it on the Oculus Quest, the device was unresponsive and I had to close and reopen it. As a result the screen recording was unfortunatly discarded.

**Comment by bluemarvin** [comment]
I'm guessing this is a memory pressure issue. I'll investigate that first.

**Comment by bluemarvin** [comment]
The patch that landed improves the situation but I can still exhaust memory on the Go. Reopening while I work on a more aggressive memory trimming PR.

**Comment by bluemarvin** [comment]
Should be fixed by #2295

**Comment by heres-maria** [comment]
I have verified this issue and it is no longer reproducible with the Firefox Reality version 7 RC3 (7b66fb14) build. No performance issues can be detected and the app didn't freeze on any device.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
