### ISSUE TITLE
Hover/select state in URL Bar in Private Browsing Mode is missing

### ISSUE THREAD

**Issue by thenadj** [MozillaReality/FirefoxReality#223]
Hardware: Oculus Go
[Bug-9 URL in PB Mode_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2214752/Bug-9.URL.in.PB.Mode_001.pdf)

REPRODUCE: home >> private browsing mode
CURRENT BEHAVIOR: There is no hover or selected state for the URL bar in PB mode
EXPECT: There should be a hover and selected state color for the URL bar
RECOMMENDATION: Specs have been added to UIS-11_006. Please use specs attached!

**Comment by keianhzo** [comment]
Related to #67 and #66
