### ISSUE TITLE
WebXR Input Event support and Select gesture

### ISSUE THREAD

**Issue by kearwood** [MozillaReality/FirefoxReality#2237]
To support WebXR in #690, additional fields will be exposed by Gecko in the ShMem struct used to communicate the state of the XR hardware.

WebXR includes support for the XRInputSource interface:

https://immersive-web.github.io/webxr/#xrinputsource-interface

To populate this interface, each platform supported by FxR will need to determine how/when the user is performing the "primary action":

https://immersive-web.github.io/webxr/#primary-action

This will be used generate XRInputSourceEvent events, representing the "select" gesture:

https://immersive-web.github.io/webxr/#xrinputsourceevent

This change will need to be done within the Android project, possibly with platform specific implementations to choose the correct pose for the ray and buttons/inputs used for the primary action.

**Comment by daoshengmu** [comment]
I can start to investigate it this week.

**Comment by jvonitter** [comment]
please hold off for a bit @daoshengmu. need to prioritize tasks for 7 first.
