### ISSUE TITLE
The “Pop-Up Blocked” notification reappears after the “Cancel” button is clicked in the pop-up blocked prompt

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2247]
**[Affected Versions]:**
- Firefox Reality version 6 RC5 (33a031c7)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- The "Block Pop-Up Windows" option is enabled.

**[Steps to reproduce]:**
1. Navigate to the following website: "http://popuptest.com/”
2. Click on a pop-up technique.
3. Click the “Pop-Up Blocked” notification.
4. Click the “Cancel” button in the pop-up blocked prompt.
5. Observe the behaviour.

**[Expected results]:**
- The pop-up blocked prompt is dismissed.

**[Actual results]:**
- The pop-up blocked prompt is dismissed and the “Pop-Up Blocked” notification reappears.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1uPLR9d6e_fumhRHbbxdjoYIXB-5FiS_N).

**Comment by jvonitter** [comment]
I think this is ok. It's pretty edge-casey and the notification dismisses itself pretty quickly.
