### ISSUE TITLE
The FxA first-run explainer page buttons in a click sate have the same background as the page

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2258]
**[Affected Versions]:**
- Firefox Reality version 6 RC5 (33a031c7)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Make sure an FxA account is NOT logged in.

**[Steps to reproduce]:**
1. Click the Hamburger menu and select the “Send Tab to Device” option.
2. Using the controller click and hold the “Start Browsing” or “Sign In” button.
3. Observe the button.

**[Expected results]:**
- The background of the buttons change to a void color and the text inside change to a fog color.

**[Actual results]:**
- The background of the button changes to the same color as the background of the explainer page.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1zgowFJmfiRu0ZiKroBrfmqC5uUeiwjes).

**Comment by keianhzo** [comment]
There is a task about dialogs standarization https://github.com/MozillaReality/FirefoxReality/issues/2131. Maybe we want to update the spec talking this into consideration. @jvonitter @thenadj

**Comment by jvonitter** [comment]
Yep, we can look at that once Nadja and co are back from their break. For now let's just fix these buttons and backgrounds to have the same colors as dialogs usually do. Refer to [SL-7](url
![image](https://user-images.githubusercontent.com/48839872/68874124-82b57a00-06b5-11ea-85f9-853e18f5b1ab.png)
) for spec

**Comment by jvonitter** [comment]
Yep, we can look at that once Nadja and co are back from break. For now, let's just make this one match the colors for backgrouds and buttons that we usually use. [See SL-7 for spec](https://trello.com/c/25qaflLv/400-sl-7-componentsdialogs)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 7 RC3 (7b66fb14) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the FxA first-run explainer page buttons in a click sate have a different background color as the page
