### ISSUE TITLE
Buttons get stuck in hover state after clicking them multiple times 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2264]
**[Affected Versions]:**
- Firefox Reality version 6 RC5 (33a031c7)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to a website.
2. Click the Back button.
3. Click the Forward button.
4. Click again on the Back button and observe the Forward button.

**[Expected results]:**
-  No hover effect is applied.

**[Actual results]:**
- The button gains a hover effect and remains in that state.

**[Notes]:**
- The hover effect is dismissed after hovering over the button.
- The button's icon is no longer displayed after entering and exiting PB mode.
- This issue is also reproducible in Private browsing mode. 
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1dqzxiWgpmufxLYmetfGnVhZwPPKDlBm7).

**Comment by keianhzo** [comment]
Ralted to https://github.com/MozillaReality/FirefoxReality/issues/2358 and https://github.com/MozillaReality/FirefoxReality/issues/2357

Looks like a bug in how Android handles the animated selector and states.

**Comment by keianhzo** [comment]
This one is pretty old and I can't reproduce this anymore so there are chances that it got fixed. Could you @Softvision-RemusDranca please test again and close in case it is?

**Comment by Softvision-RemusDranca** [comment]
I've retested this issue and it's no longer reproducible with the latest Firefox Reality version 8-40131058 (dd3477c).
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).

Considering this I will close this issue as verified-fixed.
