### ISSUE TITLE
Migrate FxA implemetation to WebChannels instead of interceptor

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#2267]
**Is your feature request related to a problem? Please describe.**
Since we're using Gecko, we should use WebChannels for communicating with the FxA web content, instead of intercepting URL loads.

Based on this comment: https://github.com/MozillaReality/FirefoxReality/pull/1973#issuecomment-544984467

**Additional context**
Once we integrate the webchannels support, for free we get handling of "Choose what to sync" selection during FxA sign-up, which our current interceptor-based integration doesn't support. Also with a tiny bit of extra work, ability to add "Manage Account" button to your FxA settings page.

This requires WebChannels webext integration.

**Comment by keianhzo** [comment]
@jvonitter We better push this to v9. We have decided to talk to the AC team in the All-Hands and expose them the need of making AC more aware of FxR in general. This is part of that conversation. We should provide time estimation and a proposal to evaluate and maybe contribute.

**Comment by keianhzo** [comment]
This is not going to happen for v9. We decided to do a staged migration to better integrate AC-FxR. First stage completed, second should add support for WebChannels in FxR without needing to implement the whole Engine/EngineSession interface.

**Comment by bluemarvin** [comment]
This is still blocked on a-c

**Comment by keianhzo** [comment]
@emstanley After the PR lands we are good to start working on Addons support and FxA "Manage Account" settings.
