### ISSUE TITLE
[Meta] Migrate telemetry metrics to Glean

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#2278]
**Is your feature request related to a problem? Please describe.**
Tracking the related issues about migrating to Glean.

Needs #1420 #1854 #2241 #2230 #2279 #2311 #2514

**Comment by keianhzo** [comment]
@daoshengmu I think this is all done, right?

**Comment by Dexterp37** [comment]
@daoshengmu @keianhzo is there an issue/PR for removing `service-telemetry`? We're deprecating this at the end of this quarter, and it will be removed from Android Components.

**Comment by daoshengmu** [comment]
Our new Glean migration are happened in v.11 that hasn't released yet.
We will remove `service-telemetry` in our milestone 12. That will happen in July.

**Comment by daoshengmu** [comment]
Issues are done, Thanks for all your efforts

**Comment by Dexterp37** [comment]
@daoshengmu  is there an issue or a bug to track the removal?

**Comment by daoshengmu** [comment]
Here is it, #3519
