### ISSUE TITLE
The "First-run FxA explainer" prompt is not displayed after an update or a fresh install

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2280]
**[Affected Versions]:**
-  Firefox Reality version 7 RC1 (b772e6d7) build.

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.2
- Oculus Go - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on.
- An older version of the app is installed on the device (v5 production).

**[Steps to reproduce]:**
1. Update the app to the latest version (v7)  RC1 using the `adb install -r` command.
2. Open the app.
3. Observe if the "First-run FxA explainer" prompt is displayed.

**[Expected results]:**
- The prompt is displayed.

**[Actual results]:**
- The prompt is NOT displayed.

**[Notes]:**
- This issue is not reproducible if the "Send Tab to Device" buttons are clicked while an FxA account is not logged in.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1_0DRtHYFM09EYkRDGxcveD7s3B0asZLG)

**Comment by keianhzo** [comment]
We only wanted to show it for version 6 show the version check was hardcoded, we need to update to 7 now that we have bumped the version.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 7 RC2 (ff64d298) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the First-run FxA explainer page is displayed after an update or a fresh install.
