### ISSUE TITLE
The video/audio from the previous tab is wrongly played in the background after receiving a tab

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2281]
**[Affected Versions]:**
- Firefox Reality 7 RC1 (b772e6d7) build.

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- Make sure that the FxA account is logged on the VR device and also on a second device.
- The volume of the VR device is turned on.

**[Steps to reproduce]:**
1. Open a normal video and play it.
2. Send a tab from a second device to the VR device.
3. Click the "Tabs View" button from the tray menu.
4. Listen if the video/audio from the previous tab is still playing. 

**[Expected results]:**
- The video/audio is paused.

**[Actual results]:**
- The video/audio is playing in the background.

**[Notes]:**
- This issue is also reproducible after the device exits sleep mode.
- The video/audio continues to play in the background until it's paused from the tab that was initially played.
- This issue is not reproducible if the video is played in theater or immersive mode.
- This issue is not reproducible if the tabs are switched while a video is playing. 
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1_6thaxVuhgBY_UC2_pu3xFmD3W1DYTvj)

**Comment by Softvision-RemusDranca** [comment]
I'm currently blocked on verifying this issue by #2315.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 7 RC3 (7b66fb14) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the video/audio from the previous tab is not played in the background after receiving a tab.
