### ISSUE TITLE
The "New Tab Added" notification for a received tab is not displayed after exiting immersive/theater mode if the device was in sleep mode

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2283]
**[Affected Versions]:**
- Firefox Reality 7 RC1 (b772e6d7) build.

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- Make sure that the FxA account is logged on the VR device and also on a second device.

**[Steps to reproduce]:**
1. Open a 360 video and play it in immersive mode.
2. Send a tab from a second device to the VR device.
3. While in immersive mode take the headset off for ~ 15 seconds.
4. Put the headset back.
5. Exit immersive mode and observe the behavior.

**[Expected results]:**
- The "New Tab Added" notification is displayed.

**[Actual results]:**
- No notification is displayed for the received tab.

**[Notes]:**
- This issue is not reproducible if the video is played in normal view.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1xZzGJZE0PiXGfGGuth5o1pGmXxVyvEX-).

**Comment by jvonitter** [comment]
this is by design. the new tab should appear in the tabs panel but it's ok if the notification doesnt show up.
