### ISSUE TITLE
The Swedish and Finnish language names are incorrectly written in their native forms in the “Firefox Reality Display Language” list

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2286]
**[Affected Versions]:**
- Firefox Reality version 7 RC1 (b772e6d7)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Open the "Language" card from the "Settings" menu.
2. Click on the “Edit” button from the “Display Language for App” option.
3. Observe the words for Finnish and Swedish.

**[Expected results]:**
- The languages should be written as “Suomi” and “Svenska”.

**[Actual results]:**
- The languages are written as “Suomea” and “Svensk”.

**[Notes]:**
- After setting the app language to either Swedish or Finnish, the text under the “Display Language for App” option will display “Suomi” or “Svenska”.
- Attached is a screen-shot of the issue.
![languages](https://user-images.githubusercontent.com/53752296/68957033-e46b0680-07d1-11ea-9cef-f4e5d8807b1a.png)

**Comment by jvonitter** [comment]
@Delphine can you check if these are correct? if not, can we update?

**Comment by Delphine** [comment]
Thanks for flagging! I've emailed the two localizers here so they can explain their choice. I think that's what we've been using elsewhere, but just in case :)
I will update here once I get a reply.

**Comment by Delphine** [comment]
Update: I'm a bit puzzled by Finnish because I see the translation that has been done is in fact "Suomi": https://pontoon.mozilla.org/fi/android-l10n/MozillaReality/FirefoxReality/app/src/main/res/values/strings.xml/?search=Suo&string=204839
Are we sure these are coming from our localizations?

**Comment by jvonitter** [comment]
@keianhzo any ideas why there'd be a discrepancy?

**Comment by heres-maria** [comment]
@jvonitter @Delphine This issue seems to have been fixed.
This issue is no longer reproducible using the latest Firefox Reality version 8-40131058 (dd3477cd) build. The app languages are displayed as "Svenska" and "Suomi".
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
