### ISSUE TITLE
[Intermittent] The "Select All" option is wrongly displayed when trying to paste content in empty input fields 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2287]
**[Affected Versions]:**
- Firefox Reality 7 RC1 (b772e6d7) build.

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to a website that has a search bar (eg: https://en.wikipedia.org/wiki/Main_Page).
2. Long click on a text area or a link and copy it.
3. Focus the page search bar.
4. Long click in the focused search bar and observe the behavior.

**[Expected results]:**
- Only the "Paste" option is displayed.

**[Actual results]:**
- The "Select All" option is also displayed on the right side of the "Paste" option.

**[Notes]:**
- This issue is not reproducible with the Awesomebar.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1W2pJPRr_tYTDbqcuUUmbgJVRo2CY18cU).

**Comment by MortimerGoro** [comment]
This requires a Gecko patch. Pushed here: https://bugzilla.mozilla.org/show_bug.cgi?id=1597707

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 7 RC4 (143a88ad) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the "Select All" option is no longer wrongly displayed when trying to paste content in empty input field.
