### ISSUE TITLE
[Intermittent] The "Paste" option is autodismissed when trying to paste content in empty input fields

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2288]
**[Affected Versions]:**
- Firefox Reality 7 RC1 (b772e6d7) build.

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to a website that has a search bar (eg: https://en.wikipedia.org/wiki/Main_Page).
2. Long click on a text area or a link and copy it.
3. Focus the page search bar.
4. Long click in the focused search bar and dismiss the "Paste" menu a few times. 
5. Observe the behavior.

**[Expected results]:**
- The "Paste" option is displayed and remains displayed until is manually dismissed.

**[Actual results]:**
- The "Paste" option is sometimes autodismissed.

**[Notes]:**
- This issue is also reproducible if the Awesomebar is empty.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1iU0kchcMz6_7m3EjdI0BSWk-UZDYhgBB).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 7 RC4 (143a88ad) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the "Paste" option is not dismissed when trying to paste content in an empty input field.
