### ISSUE TITLE
The scrollbars from the Bookmarks and History views remain stuck in the pressed state if clicked only once

### ISSUE THREAD

**Issue by heres-maria-sv-inactive** [MozillaReality/FirefoxReality#2289]
**[Affected Versions]:**
- Firefox Reality version 7 RC1 (b772e6d7)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- Make sure there are enough bookmarks entries and enough history feeds to have a scrollbar displayed.

**[Steps to reproduce]:**
1. Click the History or Bookmark button from the menu tray.
2. Click the scrollbar.
3. Observe the scrollbar.

**[Expected results]:**
- The scrollbar returns to its default state after no longer being clicked.

**[Actual results]:**
- The scrollbar remains stuck in its pressed state after only being clicked once.

**[Notes]:**
- Attached is a screen recording of the issue.
![scrollbar click](https://user-images.githubusercontent.com/53752296/68957431-b1754280-07d2-11ea-9f6c-6901da7c4ba3.gif)

**Comment by jvonitter** [comment]
We need to do a better job with scrollbars generally. Backlog for this until we have a plan to address.
