### ISSUE TITLE
Text entry in Gecko is broken on the Go

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#2290]
## Configuration

Firefox Reality version: 7
Firefox Reality build ID: b772e6d791d2a99091b2ac018e8a73a81efb84f0

Hardware: Oculus Go

## Steps to Reproduce

1. Open settings and click account button 
2. attempt to enter email address `mr.noob@aol.com`

## Current Behavior

The text is incorrectly entered as `mroobaol.com@.n`
![org mozilla vrbrowser-20191115-123956](https://user-images.githubusercontent.com/3066/68975050-16b33e80-07a7-11ea-8cdb-0ce9a6cd62f5.jpg)

## Expected Behavior

The text is correctly entered.

**Comment by bluemarvin** [comment]
Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1596920

**Comment by bluemarvin** [comment]
I don't think we can ship on the Go until this is fixed.

**Comment by heres-maria** [comment]
I investigated this issue using Firefox Reality version 7 RC1 (b772e6d7) on Oculus Go - Android 7.1.2 and couldn’t reproduce it in the following cases:

1. After a new install, using the on-screen keyboard as well as copy/paste.
2. After updating from v5 to v7, using the on-screen keyboard as well as copy/paste.
3. After signing out of an existing account and relogging using a typed or copy/pasted input.
4. Using the on-screen keyboard as well as copy/paste while the keyboard was set to every keyboard language available.

@bluemarvin Are there any other steps necessary to reproduce this issue? Was the on screen keyboard used or a bluetooth connected keyboard?

**Comment by bluemarvin** [comment]
You have to type very fast. I can get it to happen with the virtual keyboard, Bluetooth keyboard, and direct input via adb.

**Comment by bluemarvin** [comment]
I can also reproduce this in the emulator.

**Comment by jvonitter** [comment]
I'm going to pull the blocker tag unless someone else can repro this. We should still figure out what's happening, but it doesnt need to block FxR7

**Comment by bluemarvin** [comment]
I can easily reproduce this and some one on the GV team is currently working on the issue.

**Comment by bluemarvin** [comment]
The fix has landed in GeckoView. I will try bumping GV version.

**Comment by bluemarvin** [comment]
I've retested in latest GeckoView nightly and the issue is unfortunately still reproducible. I've re-opened the bugzilla issue.

**Comment by bluemarvin** [comment]
The version of GV I tested was 75.0.20200221095110
