### ISSUE TITLE
The "Pop-Ups Permissions" entries dismiss button does not have a hover or click state

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2297]
**[Affected Versions]:**
- Firefox Reality version 7 RC1 (b772e6d7)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Make sure the "Block Pop-Up Windows" option is enabled.
- Make sure the "Pop-Ups Permissions" list has at least 2 entries.

**[Steps to reproduce]:**
1. Go to Settings -> Privacy & Security.
2. Click the “Advanced” button for the “Block Pop-Up Windows” option.
3. Using the controller hover the pointer over the dismiss button for one of the sites from the list.
4. Observe the behavior.
5. Using the controller click and hold the dismiss button for one of the sites from the list.
6. Observe the behavior

**[Expected results]:**
Step 4. The dismiss button enlarges to 125% and changes to a smoke color.
Step 6. The dismiss button decreases back to 100% changes to a void color.

**[Actual results]:**
Step 4. The dismiss button doesn’t have a hover effect.
Step 6. The dismiss button doesn’t have a click effect.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1Ep9iTHfj-M-diinXpSrfBo2MtGaiHjqJ).

**Comment by jvonitter** [comment]
Align the button style to others in the build. The spec may have more recent design intent, but we want consistency in the app until we make the new designs live.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 7 RC3 (7b66fb14) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the "Pop-Ups Permissions" entries dismiss button has a hover and click state.
