### ISSUE TITLE
The keyboard is wrongly displayed in Resize mode if an input/search field was previously focused

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2298]
**[Affected Versions]:**
- Firefox Reality 7 RC1 (b772e6d7) build.

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to a website that has a search bar (eg: https://www.youtube.com/)
2. Focus the website's search bar.
3. Click the Hamburger button.
4. Click the "Window Resize" button from the Hamburger menu.
5. Observe if the keyboard is displayed.

**[Expected results]:**
- The keyboard is not displayed.

**[Actual results]:**
- The keyboard is displayed.

**[Notes]:**
- This issue is reproducible even if the keyboard is dismissed before entering Resize mode.
- The keyboard is actionable while in Resize mode.
- This issue is not reproducible on HTC Vive Focus devices.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1OdsdCTwmf9pe0kj0pzMXV0zLcigwglP3).

**Comment by jvonitter** [comment]
if there are other issues related to this, please add links

**Comment by heres-maria** [comment]
I have verified this issue and it is no longer reproducible with the Firefox Reality version 7 RC3 (7b66fb14) build. The keyboard is no longer displayed in Resize mode after an input field was previously focused.
Tested on the Oculus Quest (Android 7.1.1) and Oculus Go (Android 7.1.2).
