### ISSUE TITLE
A history log can't be be deleted by clicking once on the trash can icon if the same website was visited multiple times

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2299]
**[Affected Versions]:**
- Firefox Reality 7 RC1 (b772e6d7) build.

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to a website and refresh the website a few times.
2. Click the History button from the tray.
3. Hover over the history log for the visited website.
4. Click the Delete trash icon and observe the behavior.

**[Expected results]:**
- The history log is deleted.

**[Actual results]:**
- The history log is not deleted.

**[Notes]:**
- The history log is deleted only after clicking the Delete trash can icon as many times as the website was visited/refreshed.
- This issue is not reproducible if the history logs are deleted from "Clear History".
- As a side effect of this issue, if multiple logs are available on the History page, when the Delete trash icon is clicked the page is scrolled down and then back up. 
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1uDBkwPuB2GIsYUwGPjZA_7K8DDpk4WEZ).

**Comment by jvonitter** [comment]
Delete should remove all the instances of a URL, not just the first.

**Comment by heres-maria** [comment]
I have verified this issue and it is no longer reproducible with the Firefox Reality version 7 RC3 (7b66fb14) build. History logs for websites visited multiple times can now be deleted by clicking once on the trash button.
Tested on the Oculus Quest (Android 7.1.1), Oculus Go (Android 7.1.2), HTC Vive Focus (Android 7.1.2) and HTC Vive Focus Plus (Android 7.1.2).
