### ISSUE TITLE
Add Screenshot Functionality to FxR for Bug Reporting and Content Sharing

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#230]
Hardware: All
Steps to Reproduce: NA
Actual Behavior: NA
Expected Behavior: Option to capture undistorted screenshot of whatever is being shown in Firefox Reality and easily share or export
Recommendation: Explore implementing Firefox Desktop screenshot sharing?

@thenadj - possible 1.1 feature, will add to list. @cvan - love any input on how this functionality might best be implemented to allow to be used for bug issue reports?

**Comment by cvan** [comment]
a few technical options that come to mind:

1. if GeckoView can expose and install WebExtensions (Firefox/Edge's browser extensions), we could use this API: `[`browser.tabs.captureVisibleTab`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/captureVisibleTab) (or [`chrome.tabs.captureVisibleTab`](https://developer.chrome.com/extensions/tabs#method-captureVisibleTab) in Chrome extensions). 2. we could use the system-level Android screenshot capture
3. use whichever screenshot service is provided by the SDK of the hardware/software vendors for that particular headset

if I think of more, I'll add them here.

**Comment by avrignaud** [comment]
Thanks Cvan! We are looking at WebExtension support in the future, but it might be limited initially to "just" password managers. Need to do investigation.

**Comment by cvan** [comment]
We can use the Oculus/Focus/GoogleVR-provided APIs (or Android's) to achieve this. For 1.0, I feel like this is critical so we can get dogfooders rocproperly report bugs and get screen captures without hassle.

Any chance we can bump this to 1.0?

**Comment by bluemarvin** [comment]
Getting the screen shot is easy. Where we put it might not be. At a minimum we can put it in /sdcard/Pictures. Beyond that, there might be some platform specific things we can do to have better integration.

Also are we talking screen shot of just the browser window or the whole 3d environment including the browser window?
