### ISSUE TITLE
The Hamburger menu is not dismissed if the "Bookmark" or "Voice Search" buttons are clicked

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2301]
**[Affected Versions]:**
- Firefox Reality 7 RC1 (b772e6d7) build.

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to a website.
2. Click the Hamburger button.
3. Click the "Bookmark" or "Voice Search" button while the Hamburger menu is displayed.
4. Observe the Hamburger menu.

**[Expected results]:**
- The Hamburger menu is dismissed.

**[Actual results]:**
- The Hamburger menu remains displayed.

**[Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1S7kNdJdiaq5-SQHfArwix2vRe2kne9C7).

**Comment by heres-maria** [comment]
I have verified this issue and it is no longer reproducible with the Firefox Reality version 7 RC3 (7b66fb14) build. The hamburger menu is now dismissed when clicking on the Bookmark or Voice Search buttons.
Tested on the Oculus Quest (Android 7.1.1) and HTC Vive Focus Plus (Android 7.1.2).
