### ISSUE TITLE
need a better way to show/hide popups and other UI

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#2307]
We get a lot of bugs that boil down to "this piece of UI doesn't disappear when it should", primarily with popups.  See bugs like #2301 as an example.

There should be a way to easily and reliably hide UI based on user actions, without having to control each other piece of UI individually.

**Comment by keianhzo** [comment]
https://github.com/MozillaReality/FirefoxReality/pull/2351 have probably alleviated this issue but would be great to audit every dialog/widget as part or together with https://github.com/MozillaReality/FirefoxReality/issues/2131
