### ISSUE TITLE
add option to clear bookmarks and history on sign out

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#2309]
When a user signs out, they should be able to easily clear their history and bookmarks data that has sync'd.

To accomplish this, we should add a sign out confirmation similar to what you see on desktop:
![disconnectfxa](https://user-images.githubusercontent.com/48839872/69100112-4e252380-0a11-11ea-9335-c6f285b62b04.PNG)

It should use our standard dialog UI as shown in [SL-7 200](https://trello.com/c/25qaflLv/400-sl-7-componentsdialogs)

- Image should be the user account image or default icon.
- Title should say "Sign out of your Firefox Account?"
- Body text should say "When you sign out, you won't be able to send or receive tabs from other devices. Your bookmarks and history will also stop syncing."
- Checkbox option should say "Clear history and bookmarks from this device". 
- Buttons should be Sign Out (left, grey) and Cancel (right, blue)

If a users checks the box and signs out, their bookmarks and history should be cleared. User will know that they were cleared because no entries will show up in their bookmarks and history view (as though they just opened the app for the first time).
If they choose not to check the box, they are signed out but their data remains.
If they cancel, nothing is changed and they remain signed in.

**Comment by keianhzo** [comment]
I'm seeing different behaviors in mobile/desktop for syncing.

If from Fenix/Fennec/FxR:
- Sync bookmarks
- Sign out
- Delete a bookmark
- Sign in again

The bookmarks are deleted and disappear in the other devices.

Same thing in Firefox/Firefox Nightly, the deleted bookmarks while signed out are synced again after signing in.

I've asked the FxA team if this is the expected behavior but I suspect it is as I'm seeing the same across mobile devices.

**Comment by keianhzo** [comment]
Related AC issue: https://github.com/mozilla/application-services/issues/2250

**Comment by keianhzo** [comment]
@jvonitter there is no easy way of doing this without a fix in AS/AC as the storage is common to all users and we can't even filter using userid/timestamp to show/hide records between different users and also can't delete records. I guess for the time being we should just go the Fenix way, leave everything between logins and hope that people just use a single account.

**Comment by keianhzo** [comment]
@jvonitter I've found a way of doing this in a safe way that seems to work fine at least until AC/AS fixes the issue.
