### ISSUE TITLE
Require the user enable loading a custom environment from local storage.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#231]
This issue needs to be fixed before we ship. A back door was added so that updated environment s could be uploaded to the device and tested. Before we ship this feature needs to be explicitly turned on by the user or completely disabled.

**Comment by thenadj** [comment]
We're only shipping with one environment for v1 and not supporting the option to support a custom environment. This will need design post v1 once we enable custom environments which will also include other features like loading a 360 image, etc. @avrignaud If there is a feature I am not aware of that needs to get in before v1, please let me know.

**Comment by keianhzo** [comment]
@thenadj This is related to #283 This option should be available in that panel

**Comment by keianhzo** [comment]
Closed pero#391
