### ISSUE TITLE
The app is closed and crashed after receiving a tab

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2315]
**[Affected Versions]:**
- Firefox Reality version 7 RC2 (ff64d298)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Make sure that the FxA account is logged on the VR device and also on a second device.

**[Steps to reproduce]:**
1. Send a tab from a second device to the VR device.
2. Click the "View Tabs" button from the tray menu.
3. Observe the behavior.

**[Expected results]:**
- The received tab is opened in the focused window.

**[Actual results]:**
- The app is closed and crashed.

**[Notes]:**
- The issue is also reproducible if the tab is received after the device exits sleep mode.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1n5ZPW6iQchy29cmlWV9ZHa2lETgH0RVl).
- Attached the logcat file of the issue [here](https://drive.google.com/open?id=1G20XDRPCTX7qHARWE8blciDqkjsd5iGW).
- The crash report can be found [here](https://crash-stats.mozilla.com/report/index/bp-bda08653-2205-488e-9aed-13daa0191119).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 7 RC3 (7b66fb14) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the app doesn’t crash after receiving a tab.
