### ISSUE TITLE
Going back when in full screen causes the page to be unscrollable.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#232]
Hardware: All
Steps to Reproduce:
1) Go to youtube.com
2) Start a video in fullscreen mode.
3) Go back.

Actual Behavior:
Page is unscrollable.
Expected Behavior:
Page should be scrollable.
Recommendation:
We aren't checking in SessionStore.goBack() if we are in fullscreen and exiting fullscreen.

**Comment by keianhzo** [comment]
@bluemarvin I tried master in the Oculus Go and I couldn't reproduce the issue. For me master and this patch behave the same, in both cases it exits fullscreen and scroll works fine. Might it be specific to a hardware?

**Comment by bluemarvin** [comment]
You have go back. It may not be possible to go back on Oculus. On Focus and GVR double back swipe will go back.
