### ISSUE TITLE
The unfocused window freezes after switching tabs between windows

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2328]
**[Affected Versions]:**
- Firefox Reality version 7 RC2 (ff64d298).

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Open a new window.
2. Click the "View Tabs" button from the tray menu.
3. Select the tab that is opened in the unfocused window.
4. Focus the unfocused window and interact with its content.

**[Expected results]:**
- The window's content is responsive.

**[Actual results]:**
- The window's content is frozen.

**[Notes]:**
- As a side effect of this issue, if a video that is playing gets "stuck" in that window, the audio continues to play in the background.
- The website from the affected window can no longer be scrolled and no new other searches can be performed.
- The window controls are no longer actionable, as well as the "Homepage" button and navigation buttons.
- The affected window can be closed or moved using the window's controls.
- The window gets unfrozen if the "Bookmarks" or "History" pages are opened in it.
- Attached is a screen recording of the issue [here](https://drive.google.com/open?id=1KKNGVA3rg8LTDtv9zr18nH7dH1-yRzAq).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 7 RC3 (7b66fb14) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the unfocused window doesn’t freeze after switching tabs between windows.
