### ISSUE TITLE
The "Send Tab to Device" prompt is auto dismissed when trying to send a tab from the Hamburger menu after the app is resumed

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2329]
**[Affected Versions]:**
- Firefox Reality version 7 RC2 (ff64d298)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Make sure that the FxA account is logged on the VR device and also on a second device.

**[Steps to reproduce]:**
1. Click the "Oculus" button from the controller.
2. Click the "Resume" button from the prompt displayed.
3. Click the Hamburger button.
4. Click the "Send Tab to Device" button from the Hamburger menu.
5. Observe the "Send Tab to Device" prompt.

**[Expected results]:**
- The prompt is displayed and remains displayed.

**[Actual results]:**
- The prompt is briefly displayed and after it's auto dismissed.

**[Notes]:**
- The issue is reproducible when trying to send a tab after the device exits sleep mode.
- The issue is also reproducible after reopening the app.
- This issue is not reproducible if the tab is sent from "View Tabs".
- The issue is no longer reproducible after trying to send a tab on a second attempt.
- I was not able to reproduce this issue on the HTC Vive Focus devices.
- Attached a screen recording of the issue: [here](https://drive.google.com/open?id=1Sds8T7xLEYey-YwssFToHIEHOsrFRu0w).

**Comment by bluemarvin** [comment]
This worked in v7 rc1. Will do a bisect to try and narrow down the commit causing the regression.

**Comment by bluemarvin** [comment]
Maybe it didn't work in v7 rc1. Still trying to track down the issue.

**Comment by bluemarvin** [comment]
Looks like it was caused by #2228

**Comment by bluemarvin** [comment]
Looks like it was caused by this change https://github.com/MozillaReality/FirefoxReality/pull/2228/files#diff-4f3b7fc6e7c2e6cb9d5359555ffe7e67L45-R46

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 7 RC4 (143a88ad) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the "Send Tab to Device" prompt is not dismissed when trying to send a tab from the Hamburger menu after the app was resumed.
