### ISSUE TITLE
[Meta][Tabs] The text doesn’t match the mock-ups

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2333]
**[Affected Versions]:**
- Firefox Reality version 7 RC2 (ff64d298)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- Make sure to have at least 5 tabs opened.

**[Steps to reproduce]:**
1. Click the “View Tabs” button from the menu tray.
2. Observe the left part of the top section of the Tabs dialog.
3. Click the “Select” button.
4. Observe the left part of the section underneath the breakline.
5. Observe the text of the buttons in the right part of the section underneath the breakline.
6. Using the controller select 2 tabs.
7. Observe the text of the buttons in the right part of the section underneath the breakline.

**[Expected results]:**
Step 2. The text "# Tabs Open" is displayed where # is the number of created tabs.
Step 4. The text "# Tabs Selected" is displayed where # is the number of selected tabs.
Step 5. The text of the buttons displayed are “Close All” and “Select All”.
Step 7. The text of the buttons displayed are “Close Tabs” and “Select None”.

**[Actual results]:**
Step 2. The text "# Tabs" is displayed.
Step 4. The text "# Tabs selected" is displayed.
Step 5. The text of the buttons displayed are “Close all” and “Select all”.
Step 7. The text of the buttons displayed are “Close tabs” and “Unselect all”.

**[Notes]:**
- Attached screenshots of the issues below:
![actual tabs](https://user-images.githubusercontent.com/51400741/69252610-faa30900-0bbb-11ea-8757-4de8ac348868.png)

**Comment by jvonitter** [comment]
This is ok as is.
