### ISSUE TITLE
The time that the FxA account was last synced is wrongly kept for a new login

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2337]
**[Affected Versions]:**
- Firefox Reality version 7 RC2 (ff64d298).

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Make sure that the FxA account is logged in.

**[Steps to reproduce]:**
1. Open the "Manage Account" card from Settings.
2. Click the "Sync Now" button and wait for 1 minute after the sync is done.
3. Click the "Sign Out" button.
4. Log in again the FxA account using the same or a different account.
5. Observe if the "Last synced 'time'" from the previous sync is displayed.

**[Expected results]:**
- The sync time from the previous login is not displayed.

**[Actual results]:**
- The sync time from the previous login is displayed.

**[Notes]:**
- The sync time is updated after the current account is synced.
- Attached is a screen recording of the issue: [here](https://drive.google.com/open?id=1kzLYPVxmq60UPxoDrp1B8mbtLf-eKDbV).

**Comment by jvonitter** [comment]
related to #2309

**Comment by keianhzo** [comment]
Related to this FxA bug: https://github.com/mozilla-mobile/android-components/issues/5118

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 7 RC3 (7b66fb14) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the time that the FxA account was last synced is not kept for a new login.
