### ISSUE TITLE
Implement UI for <select> fields

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#234]
Hardware: All
Steps to Reproduce:
1) Go to: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select
2) Scroll to Examples.
3) Click on selection drop down list.

Actual Behavior:
Nothing happens.

Expected Behavior:
A selection list is presented and the user may select an item in the list.

Recommendation:
FxR need to implement UI for the various selection types a web page may present.

**Comment by bluemarvin** [comment]
The PromptDelegate supports the following prompts:

1) Alert
2) Text Prompt
3) Auth Prompt
4) Choice Prompt
5) Color Prompt
6) Date and Time Prompt
7) File Prompt

Maybe @cvan has a good link that gives examples of each one? We would need design work for each type of prompt we want to support.

**Comment by bluemarvin** [comment]
Here is the geckoview_example implementation of the PromptDelegate:

https://searchfox.org/mozilla-central/source/mobile/android/geckoview_example/src/main/java/org/mozilla/geckoview_example/BasicGeckoViewPrompt.java

**Comment by cvan** [comment]
Can we change the bug title to better reflect the nature of this issue? `window.alert`, `window.confirm`, `window.prompt`, Basic Auth, "door hangers" (à la Firefox Desktop), etc. … and probably one of the most crucial bits, the [**Permissions API**](https://w3c.github.io/permissions/) (there's [a long list of APIs](https://w3c.github.io/permissions/#permission-registry) that use the Permissions API, or will soon use them; Chrome is more up to date on the Permissions API transition, just FYI).

**Comment by bluemarvin** [comment]
@cvan feel free to update the tittle, I'm not sure what the correct terminology is to cover all the missing UI elements.

**Comment by thenadj** [comment]
@avrignaud We need to add this to the design priority list.

**Comment by avrignaud** [comment]
@bluemarvin @cvan Can you help us by pointing to examples of each of needed prompts, along with your thoughts on which are absolutely needed for 1.0 versus 1.1? Design needs a bit more to be able to create.

Is this the total list we need? 

    Alert
    Text Prompt
    Auth Prompt
    Choice Prompt
    Color Prompt
    Date and Time Prompt
    File Prompt

**Comment by cvan** [comment]
FYI: I'm working on compiling the list with test cases right now. When the list is completed, I'll push it somewhere online to test in the headset.

When I get a moment in between the New Tab/Feed work, I'll test each one manually and identify the ones that pass/fail. Let me know if you need me to prioritise this, and I can carve out some time to complete this right now.

**Comment by thenadj** [comment]
Thanks, @cvan - it can wait till Thursday. Ideally we'd get screenshots of the areas that need UI elements so we know exactly what they currently look like and get a bit of context.

**Comment by cvan** [comment]
Finished: https://github.com/MozillaReality/fxr-html-tests#html-tests-for-firefox-reality

Here are the test cases for checking parity of HTML features in Firefox Reality.

**[View Test List](https://mixedreality.mozilla.org/fxr-html-tests/index.html)** ([`https://mzl.la/2MGlwdI`](https://mzl.la/2MGlwdI)) (<-- that's a lowercased **L** and an uppercased **i** at the end, lol sigh)

- [Forms](https://mixedreality.mozilla.org/fxr-html-tests/index.html#forms)
- [Media](https://mixedreality.mozilla.org/fxr-html-tests/index.html#media)

**Comment by cvan** [comment]
If someone doesn't get to the manually testing before I do, I'll follow up in a few days to provide a hand to make a short-list of the items: broken/missing, to-design/to-fix, and to-postpone-for-later. Thanks!

**Comment by avrignaud** [comment]
@cvan Looks like we can definitely use your help here! Nadja can't design without a bit more guidance here.

**Comment by cvan** [comment]
@avrignaud does anyone have cycles to go through and compare how Oculus Browser vs. Firefox Reality render the following:

- form elements (e.g., `<select>`, `<input type="number">`, `<input type="text" pattern="…" required>`),
- media (e.g., `<video controls>`, `<audio controls>`), and
- dialogues (e.g., `window.alert`, `window.prompt`, `window.confirm`, etc.)

in the [test-case list](https://mixedreality.mozilla.org/fxr-html-tests/index.html) I created above.

**Comment by larsbergstrom** [comment]
Is this a blocker for V1? I'm seeing few sites where this is killing us right now, and would rather focus on voice search and other UX/UI engineering work and push this to post-V1.

**Comment by cvan** [comment]
Getting `<select>` working seems like the only P0 blocker IMO. alert/confirm/prompt: P1. Basic-Auth password prompts: P2.

anyone disagree with that?

**Comment by thenadj** [comment]
@cvan Can you send me a screenshot of where this appears? I'll go ahead and create the design asap. Anything else I need to know? Size, states, etc?

**Comment by cvan** [comment]
@thenadj sure thing - will sent it before lunch

**Comment by MortimerGoro** [comment]
I was going to say the same thing that @cvan  mentioned. Select is the only one I'd consider P0.

**Comment by nancyhang** [comment]
Ok, I'll change this ticket to implement UI for <select> fields and create another one for the rest. I'll tag the rest for v1.1 and this one can be kept as P0.

**Comment by cvan** [comment]
1. Load https://mixedreality.mozilla.org/fxr-html-tests/select.html in Oculus Browser.
2. Load https://mixedreality.mozilla.org/fxr-html-tests/select.html in Firefox Reality.
3. Notice that in both Oculus Browser and Firefox Reality, the `<select>` fields do highlight the correct `<option selected>`.
4. In Firefox Reality , the `<select>` field cannot be focused and does not show the `<option>`s at all. ⚠️

![select-oculus-browser](https://user-images.githubusercontent.com/203725/44774304-aa0f3e00-ab27-11e8-9173-dfb349de5214.gif)
![select-fxr-browser](https://user-images.githubusercontent.com/203725/44774307-abd90180-ab27-11e8-88ae-b709b5712229.gif)

**Comment by bluemarvin** [comment]
Unassigning this since I'm probably not the one doing the UI work.

**Comment by keianhzo** [comment]
@cvan I've an implementation of this in the "select" branch in case you want to take a look. This is how it looks right now:

- Single
![single](https://user-images.githubusercontent.com/837184/45168761-5de58d00-b1fc-11e8-8a6f-7008e38d6bfc.png)

- Grouped
![groups](https://user-images.githubusercontent.com/837184/45168752-57efac00-b1fc-11e8-9dab-6fcfadeb6437.png)

- Multiple
![multiple](https://user-images.githubusercontent.com/837184/45168781-650c9b00-b1fc-11e8-92f5-8b0ab950f9c4.png)

@thenadj Whenever you have the design ready let me know so I can integrate it.

**Comment by thenadj** [comment]
@keianhzo Attached is the UI spec for this. 
[UIS-45 HTML Fields & Prompts_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2359050/UIS-45.HTML.Fields.Prompts_001.pdf)
