### ISSUE TITLE
[Polish] UI localization issues for Settings

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2344]
[Polish] UI issues for Settings

**[Affected Versions]:**
- Firefox Reality version 7-33242239 (98c54a46)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- The Polish language is set for the app.

**[Steps to reproduce]:**
1. Click the "Settings" button from the tray menu
2. Observe the "Developer Options" card.
3. Click the "Display" card.
4. Observe the "Homepage" and "Foveation Level" options.
5. Open the "Manage Account" card and observe the "Reset" button.

**[Expected results]:**
- The UI is correctly displayed.

**[Actual results]:**
- Step 2: The card's name reaches the card's margins.
- Step 4: The "Firefox Reality Home (Default) string is not entirely displayed.
- Step 4: The "Foveation Level (App)" string overlaps with the first radio button.
- Step 5: The "Reset" button name's is not fully visible. 

**[Notes]:**
- The "Reset" button is correctly displayed for the other menus in this language.
- Attached are screen shots of the issues:
	- Developer Options card:
![PolishDeveloperOptions](https://user-images.githubusercontent.com/40061643/69355500-8f743800-0c8a-11ea-971d-662ef9b3928b.jpg)
	- Display card:
![PolishDisplay](https://user-images.githubusercontent.com/40061643/69355520-956a1900-0c8a-11ea-8306-6cca109df020.jpg)
	- Manage Account:
![org mozilla vrbrowser-20191121-181025](https://user-images.githubusercontent.com/40061643/69355529-9ac76380-0c8a-11ea-8245-00f1d6afcfa3.jpg)

**Comment by heres-maria** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9-40240151 (7e03c944) build. 
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
