### ISSUE TITLE
Add new telemetry for tracking window is opened.

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#2347]
**Is your feature request related to a problem? Please describe.**
- What's the answer you want to get from this telemetry? Please describe it.
We wanna collect the data about how many windows users create in a session.
- Is it measured by time, counter, or a string?
By Counter. Maybe Label counter.
- When will the telemetry metric be sent? Daily? In the end of a session? or something else?
In the end of a session.

**Comment by daoshengmu** [comment]
@jvonitter Per our discussion, we wanna add telemetry for a window is opened. Are we interested in understanding if it is a general window or a private one?

**Comment by jvonitter** [comment]
@daoshengmu only general windows
