### ISSUE TITLE
[Intermittent] Some input fields aren’t populated with the entered keyboard input

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2350]
**[Notes]:**
- On HTC Vive Focus Plus, it was reproducible in 2/10 attempts.
- On HTC Vive Focus, it was reproducible in 2/10 attempts.
- On Oculus Go it was reproducible in 8/10 attempts.
- On Oculus Quest, it was reproducible in 5/10 attempts.

**[Affected Versions]:**
 - Firefox Reality version 7-33260123 (6bef00e1)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Go to [Google](https://www.google.com/).
2. Click “Sign in”.
3. Click inside the “Email or phone” input field.
4. Enter an input using the on-screen keyboard.

**[Expected results]:**
- The input field is populated with the characters entered.

**[Actual results]:**
- The input field is not populated with the characters entered.

**[Additional Notes]:**
- This issue is reproducible on the FxA sign-in page (“Enter your email” field) as well, but very intermittently. I could not find a pattern for its occurrence. 
- This issue is seemingly not reproducible on other websites.
- The field is correctly populated after it is refocused.
- Clicking on the input field while the page is still loading will cause this issue to not be triggered.
- The issue is not reproducible if trying to sign in using “Add a new account”.
- Attached is a screen recording of the [issue](https://drive.google.com/file/d/1oRAvRAuAU10k4PcvAxLqVPq7rPPq4cES/view?usp=sharing).
- Attached is the logcat [file](https://drive.google.com/file/d/1jJDlOOQpzJd8ZD0DgGptvaYC0W5i1dYq/view?usp=sharing).

**Comment by bluemarvin** [comment]
This is a gecko bug. I can reproduce the issue on Fenix Nightly.

**Comment by bluemarvin** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1598782

**Comment by heres-maria** [comment]
I have verified this issue is no longer reproducible with the latest Firefox Reality version 8-33472001 (6ba38814) build. The fields are now populated with the entered characters. This is true for "Enable Multiprocess" turned both on and off.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
