### ISSUE TITLE
Add a setting to enable/disable restoring previous tabs

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#2354]
**Is your feature request related to a problem? Please describe.**
We are by default restoring the opened tabs when the browser is reopened. Would be great to have a setting to change that in case the user just wants a fresh start after closing the app.

Desktop does this by default and just opens home. Mobile doesn't and keep all the tabs as we do. At least giving the option would be nice.

**Describe the solution you'd like**
Add a setting to enable/disable session restoration as Desktop does.

<img width="381" alt="Screen Shot 2019-11-20 at 16 04 24" src="https://user-images.githubusercontent.com/837184/69424938-23491100-0d2a-11ea-9ecd-ef42e8fe15c2.png">

**Comment by thenadj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UIS-16 Settings](https://trello.com/c/P52DGGmp/88-uis-16-settings)

**Comment by keianhzo** [comment]
@thenadj I don't see any "restore previous session" option in UIS-16.

**Comment by jvonitter** [comment]
@keianhzo it's in 400C, but not in the right place. I'll update the trello card with feedback and @thenadj can update

**Comment by thenadj** [comment]
@keianhzo It somehow fell off our latest version. The updated version is back in the Trello card:
https://trello.com/c/P52DGGmp/88-uis-16-settings
