### ISSUE TITLE
Add support for opening tabs from ADB

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#2355]
**Is your feature request related to a problem? Please describe.**
We currently support opening a URL from [ADB](https://github.com/MozillaReality/FirefoxReality/wiki/ADB-command-cheat-sheet) in the current active session/tab. but we don't currently support opening the URL in a new tab. This can useful for testing.

**Describe the solution you'd like**
We can follow the same approach as chrome where you can do it through a `create_new_tab` boolean extra parameter:

`adb shell am start -a android.intent.action.VIEW --ez create_new_tab true -d https://www.mozilla.com/ -t application/browser -n org.mozilla.vrbrowser/org.mozilla.vrbrowser.VRBrowserActivity
`

Additionally we could also give the option to open it in background.

**Comment by jvonitter** [comment]
@keianhzo can you put an estimate label on this?

**Comment by keianhzo** [comment]
Added
