### ISSUE TITLE
[Oculus] The “Manage Account” card can not be dismissed using the controller back button immediately after signing in

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2359]
**[Affected Versions]:**
- Firefox Reality version 7-33260123 (6bef00e1)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on and the browser is open.

**[Steps to reproduce]:**
1. Click the "Sign into Account" card from settings.
2. Sign in using valid credentials.
3. Press the back button on the controller.
4. Observe the behaviour.

**[Expected results]:**
- The “Manage Account” card is dismissed.

**[Actual results]:**
- The “Manage Account” card remains open.

**[Notes]:**
- The issue is not reproducible on the HTC devices.
- The issue is not reproducible if the card is opened from the settings menu.

**Comment by keianhzo** [comment]
@heres-maria Fixed by https://github.com/MozillaReality/FirefoxReality/pull/2351

**Comment by heres-maria** [comment]
I have verified this issue and it is no longer reproducible with the Firefox Reality version 7 RC4 (143a88ad) build. The “Manage Account” card can now be dismissed using the controller.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
