### ISSUE TITLE
The app is closed and crashed after adding a tab from Context menu and disabling/enabling "Tracking Protection"

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2360]
**[Affected Versions]:**
- Firefox Reality version 7-33260123 (6bef00e1)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Htc Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- "Tracking Protection" is enabled.

**[Steps to reproduce]:**
1. Open a website with hyperlinks eg: "https://en.wikipedia.org/wiki/Main_Page".
2. Long click on a hyperlink an click the "Open in a new tab" button.
1. Open the "Privacy and Security" card from Settings.
2. Click the radio button for the "Tracking Protection".
3. Observe the behavior.

**[Expected results]:**
- The "Tracking Protection" option is disabled.

**[Actual results]:**
- The app closes and after it's reopened the crash dialog is displayed.

**[Notes]:**
- The tabs added in the current session are deleted.
- I think that the unloaded tab is the cause of this issue, since with the steps above I was able to reproduce this issue every single time, and hopefully the logcat will can confirm that.
- This issue is not reproducible if the taps are opened.
- Attached is a screen recording a logcat and the crash report recorded while reproducing this issue: 
	- Logcat: [link](https://drive.google.com/open?id=1JtlNfZ8gJCZoUQsYBKwtqA3tcmFPlFti).
	- Video Recording: [link](https://drive.google.com/open?id=10YVQYWlI2SGW6wDDaajHiHFrekfUhYZr).
	- Crash Report: [link](https://crash-stats.mozilla.com/report/index/bp-766237ba-c403-4148-9940-526630191122).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 7 RC3 (7b66fb14) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the app doesn’t crash after adding a tab from the context menu and disabling/enabling "Tracking Protection".
