### ISSUE TITLE
[Intermittent] A new FxA account can’t be verified

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2372]
**[Affected Versions]:**
- Firefox Reality version 7 RC3 (7b66fb14)
- Firefox Reality version 7-33291756 (66da79cc)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Make sure an FxA account is NOT logged in.

**[Steps to reproduce]:**
1. Go to the Settings menu and click the “Sign Into Account” card.
2. Fill in a never before used valid email address and click the “Continue” button.
3. Fill in the required fields and continue.
4. Enter the 6 digit verification code sent to the email address used.
5. Click the “Verify” button and observe the behavior.

**[Expected results]:**
- The account is verified and the Settings menu is redisplayed.

**[Actual results]:**
- Nothing happens.

**[Notes]:**
- At the next sign in attempt the user can sign in using this account like it was verified.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1eiy5z26U4tEx7bj76tjrlNffYsX11-FI).
- Attached the logcat file of the issue [here](https://drive.google.com/open?id=1Iy2E0dMd9yRaAjhi8OQdDF4VgTqQetlw).

**Comment by keianhzo** [comment]
Cannot reproduce. I've sent a build with logs to @Softvision-GeluHaiduc to get a full logcat.

**Comment by keianhzo** [comment]
Cannot reproduce. I've sent a build with logs to @Softvision-GeluHaiduc to get a full logcat.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 7 RC5 (0706b656) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, a new FxA account can be verified.
