### ISSUE TITLE
[Intermittent] An FxA user can’t sign in at first attempt

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2373]
**[Affected Versions]:**
- Firefox Reality version 7 RC3 (7b66fb14)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- Make sure that the app is freshly installed on the device. 
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Go to the Settings menu and click the “Sign Into Account” card.
2. Fill in a valid email address of an FxA account.
3. Click the “Continue” button and observe the behavior.

**[Expected results]:**
- The user can sign in using a valid email address.

**[Actual results]:**
- Nothing happens.

**[Notes]:**
- The issue is also reproducible if using a never before used valid email address to create an account.
- At the next sign in attempt the user can sign in normally.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1cVsNUV3Bot9lFAqQo86yKowI7JL7dWZs).
- Attached the logcat file of the issue [here](https://drive.google.com/open?id=1ICdeqtsh1EtdfqJVQliFekzEW2J0__J4).

**Comment by Softvision-GeluHaiduc** [comment]
Might be related to #2372.

**Comment by keianhzo** [comment]
Cannot reproduce. I've sent a build with logs to @Softvision-GeluHaiduc to get a full logcat.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 7 RC5 (0706b656) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, an FxA user can sign in at the first attempt.
