### ISSUE TITLE
Migrate Glean to the latest build system

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#2388]
**Is your feature request related to a problem? Please describe.**
Latest version of Glean uses a different build system based on a glean gradle plugin. We should keep up to date with the latest Glean version and migrate our build system to the new one.

We can safely follow what Fenix does on this regard.

**Additional context**
https://mozilla.github.io/glean/book/user/adding-glean-to-your-project.html

**Comment by daoshengmu** [comment]
I didn't see any difference after adding the below script into build.gradle,
```
 maven {
            url "https://maven.mozilla.org/maven2"
        }
        dependencies {
            classpath "org.mozilla.telemetry:glean-gradle-plugin:$deps.android_components_version"
        }
```

I look forward it can help us re-generate `metrics.md` once I do changes at its *.yaml.
