### ISSUE TITLE
Support WebXR permission in FxR

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#2389]
**Is your feature request related to a problem? Please describe.**
Once [Bug 1580567](https://bugzilla.mozilla.org/show_bug.cgi?id=1580567) is landed, WebVR websites will be unable to activate VR displays until we support WebXR permission.

**Describe the solution you'd like**
Support WebXR pop-up permission UI. We can take this [geolocation sample](https://chrisdavidmills.github.io/location-finder-permissions-api/) as our UI reference.

**Comment by daoshengmu** [comment]
There is a follow-up discussion. Should we pop-up this WebXR permission UI in our FxR standalone? If so, there are lots of WebXR-related websites will show up this prompt, even http://webxr.today. I am thinking if we should make it allow by default and opt-out. Users can enable this UI in our setting.

**Comment by jvonitter** [comment]
@kearwood and I discussed this at length. Kip, correct me if I'm wrong, but I think we decided against doing a popup permission here. Here's a snippet from our Slack conversation, with added links:

What we need is:
1) a default-on setting that is "Allow Immersive Experiences" - we can add a description or link out if that's useful to let users know what it is/why it matters (covered by #2062)
2) a list of sites who are blocked from allowing immersive experiences (exclusions) similar to what we do for popups (#593), and eventually location (#1758) and microphone (#1759 )
3) an interstitial page between regular and immersive mode that explains a)how the user can get out of immersive mode and b) shows the URL taking them to immersive mode and c) "The site is requesting information that can uniquely identify you, including your height and size of your room." (part of #1966 )

**Comment by MortimerGoro** [comment]
Closing this because the flow is already covered in the spec explorations posted in #2062

**Comment by bluemarvin** [comment]
> Closing this because the flow is already covered in the spec explorations posted in #2062

I think the spec is now out of date and we are not longer going to show the popup.
