### ISSUE TITLE
[Intermittent] The UI freezes after resuming the app with multiprocess turned on

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2395]
**[Affected Versions]:**
- Firefox Reality version 7 RC5 (0706b656)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Make sure to have at least 2 windows opened and multiple tabs created.

**[Steps to reproduce]:**
1. Go to the Settings menu and click the “Developer Options” card.
2. Switch on the “Enable Multiprocess” option and dismiss the settings menu.
3. Press the Oculus/Vive button on the controller.
4. Reopen the app and observe the windows.

**[Expected results]:**
- The session is restored and the open windows can be navigated.

**[Actual results]:**
- The windows are frozen and can’t be navigated.

**[Notes]:**
- The affected windows can be closed.
- New windows and tabs created are working as expected.
- The issue is not reproducible with only one window opened.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1w8cWlDBunQRazPDxuckF0OcnDN_qInz9).
- Attached the logcat file of the issue [here](https://drive.google.com/open?id=1SKKAfNOB9h5N18UqLyaR46FJrDpO5mbI).

**Comment by MortimerGoro** [comment]
I can't reproduce this one. @Softvision-GeluHaiduc can you confirm it still happens?

**Comment by Softvision-GeluHaiduc** [comment]
@MortimerGoro Using the latest master I tried to reproduce this issue, here is what I found:
Oculus Quest - The issue was not reproduced.
HTC Vive Focus - The issue was not reproduced.
HTC Vive Focus Plus - The issue was not reproduced but the app did have small jerky movement right after being reopened.
Oculus Go - After 15 minutes of stressing the app and trying to reproduce the issue app froze and I had to restart the headset. On the second attempt to reproduce the issue with video and logcat the issue could not be reproduced but the app did begin to lag (this also might be a hardware limitation), here is the [video](https://drive.google.com/open?id=1ULts_Vu75loscBfVmSPplHDOaFnoqjEC) of the second attempt and the [logcat](https://drive.google.com/open?id=1cyCt6pzL0EnFvvyknMgvmPsfqpN8sZvl).

I don’t know if the behavior on the Oculus Go is related to this issue or if it is a hardware limitation, also keep in mind that this issue is intermittent.

**Comment by jvonitter** [comment]
I want to keep an eye on this but it can wait till 9.

**Comment by bluemarvin** [comment]
I believe this issue has been resolved. If it comes back we should re-open.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10-140800017 (b4842842) installed on the Oculus Go, HTC Vive Focus Plus and Pico Neo2 headsets.
The “Enable Multiprocess” setting from the “Developer Options” card was removed and multiprocess is turned on by default. Also, the UI doesn’t freeze after resuming the app.
