### ISSUE TITLE
The “Enable UI Hardware Acceleration” option is not reset to the default value after clicking the “Reset” button in the “Developer Options” card

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2396]
**[Affected Versions]:**
- Firefox Reality version 7 RC5 (0706b656)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2 
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on and the browser is open.
- Make sure to have the “Enable UI Hardware Acceleration” option turned on.

**[Steps to reproduce]:**
1. Click the “Settings” button and select the “Developer Options” card.
2. Click the “Reset” button.
3. Observe the state of the “Enable UI Hardware Acceleration” option.

**[Expected results]:**
- The option is reset to the default value.

**[Actual results]:**
- The option remains the same (turned on).

**[Notes]:**
- Attached is a recording of the [issue](https://drive.google.com/open?id=1IlII22-TOyb3nWPkDQJlbw3TeD1EsQJa).

**Comment by thenadj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UIS-16 Settings](https://trello.com/c/P52DGGmp/88-uis-16-settings)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 7 RC6 (b01367aa) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the “Enable UI Hardware Acceleration” option is reset to the default value after clicking the “Reset” button.
