### ISSUE TITLE
The pop-up tabs are not shown if they are opened while the “View Tabs” dialog is opened

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2404]
**[Affected Versions]:**
- Firefox Reality version 7 RC5 (0706b656)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Make sure the "Block Pop-Up Windows" option is enabled.

**[Steps to reproduce]:**
1. Navigate to the following website: "http://popuptest.com/” and click on a pop-up technique.
2. Click the “Pop-Up Blocked” notification and click the “Don’t show again for this site” option.
3. Click the “Show” button.
4. Click the “View Tabs” button in the menu tray.
5. Close all the pop-up tabs until the tab with the selected pop-up technique from strep 1 is opened in the background.
6. Observe the tabs.

**[Expected results]:**
- The pop-ups are opened in new tabs.

**[Actual results]:**
- The pop-ups are opened in the background but are not displayed in the “View Tabs” dialog.

**[Notes]:**
- If there are more tabs opened before these steps when closing the tab from step 1 the pop-up tabs are displayed in the same position as the previous step. 
- The tabs appear after the “View Tabs” dialog is closed and reopened.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1TRMhojYcpDl5q8zMLBPf35WlJDtO3em0).
- Attached the logcat file of the issue [here](https://drive.google.com/open?id=1YGbDhyxFVghhc0_Uv2-XJG_qcxDLsYiD).

**Comment by keianhzo** [comment]
@Softvision-GeluHaiduc This doens't apply anymore after the permissions standardization in the URL bar. Can you verify/close?

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 11-141551002 (8f4de9a4) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, when the tab with the pop-up technique is opened in the background the pop-ups are not automatically opened.
Giving this I will close the issue.
