### ISSUE TITLE
The Restart Required prompt is wrongly displayed when clicking the "Reset" button for Display Language even if the default option is set

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2416]
**[Affected Versions]:**
-  Firefox Reality version 7 RC6 (b01367aa)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- All options are set to default.

**[Steps to reproduce]:**
1. Open the "Language" card from Settings.
2. Click the "Edit" button for the "Display Language for App" option.
3. Click the "Reset" button and observe the behavior.

**[Expected results]:**
- Nothing happens, all options are already set to default.

**[Actual results]:**
- The Restart Required prompt is displayed.

**[Notes]:**
- This issue is also reproducible if the "Reset" button from the "Language" card is clicked.
- This issue is not reproducible on the Oculus Go device.
- I will follow up with a comment tomorrow with the results on Oculus Quest. 
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1_yQwOfbNYcXx27nL81FV8IeGolao-ti4).

**Comment by keianhzo** [comment]
This has been fixed by https://github.com/MozillaReality/FirefoxReality/pull/2672

**Comment by Softvision-RemusDranca** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 8 RC4 (f9c92a2). The Restart Required prompt is no longer displayed when the default option is set.

Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
