### ISSUE TITLE
Oculus Quest version is old

### ISSUE THREAD

**Issue by 10lk** [MozillaReality/FirefoxReality#2419]
**Is your feature request related to a problem? Please describe.**
Looking at the Oculus Quest store, the last update date is July 26, 2019.
https://www.oculus.com/experiences/quest/2180252408763702/
Since there is no function of multiple windows, it is very inconvenient.
Could you update it?

**Describe the solution you'd like**
Update store apps.

**Describe alternatives you've considered**
Nothing.

**Additional context**
Nothing.

**Comment by bluemarvin** [comment]
The last update to the Quest store was Oct 15, 2019 and is version 5. If you have side loaded Firefox Reality at any time, it can block the store update. You may need to uninstall FxR from your device to receive updates.

**Comment by 10lk** [comment]
It worked when I reinstalled. I'm sorry.

**Comment by joshmarinacci** [comment]
No problem. It messes me up sometimes too.
