### ISSUE TITLE
Native crash when closing the app

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#242]
Hardware: Oculus Go
Steps to Reproduce:
- Open FxR
- Click on the back button
- Close the app

Actual Behavior: There is a native crash
Expected Behavior: The shouldn't be a crash
Recommendation:

**Comment by bluemarvin** [comment]
This is actually an issue in VRB. https://github.com/MozillaReality/vrb/issues/41

**Comment by bluemarvin** [comment]
Fixed by https://github.com/MozillaReality/vrb/commit/266478268680e12715e3a5f062721f7242e8876f
