### ISSUE TITLE
[Oculus] Movement is choppy and there are glitches in the Bookmark/History Views if the window size is greater than 0.5x

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2428]
**[Affected Versions]:**
-  Firefox Reality version 7 RC6 (b01367aa)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Resize the window to 3x size.
2. Click the Bookmark/History button in the menu tray.
3. Move the headset vertically or horizontally and observe the behavior.

**[Expected results]:**
- The movement is smooth and there are no visual glitches.

**[Actual results]:**
- The movement is choppy and there are visual glitches.

**[Notes]:**
- The issue is reproducible with any window size greater than 0.5x size.
- The issue is most visible if the window is 3x size.
- The glitches are not visible in the video recording.
- The issue is not reproducible on the HTC devices.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=18s7nPoxXWOIxzbk0NhBqOn_c2pM6B7o9).
- Attached the logcat file of the issue [here](https://drive.google.com/open?id=1eQ40s8jJ5rc2WJ8InXLevBfMIGYTEN7S).

**Comment by bluemarvin** [comment]
This seems to be cause by software rendering. @MortimerGoro Maybe we can enable hardware rendering for history and bookmarks?

**Comment by bluemarvin** [comment]
Disabling async layers also causes the issue to go away. So this seems to be some sort of interaction between software rendering of large UI textures (history, bookmarks) and Oculus async layers.

**Comment by MortimerGoro** [comment]
> This seems to be cause by software rendering. @MortimerGoro Maybe we can enable hardware rendering for history and bookmarks?

We can try but I'm concerned that having both render modes in different views in the same window can cause more bugs.

Another thing we can try is ignore all renders after onStop/onDestroy is called (trying to find a workaround for the original crash without using soft rendering)

**Comment by bluemarvin** [comment]
I'm wondering if there is something going wrong when we replace the browser window with the history or bookmark widget. I don't see this issue with the tabs window.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 8-40101959 (3c2a71e2) installed on the Oculus Go and Oculus Quest headsets.
Now, the movement is no longer choppy and there are no glitches in the Bookmark/History Views regardless of the window size.
