### ISSUE TITLE
Redirecting the Console to Logcat is only accomplished with “Enable Debug Logging” enabled 

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2437]
**[Affected Versions]:**
- Firefox Reality version 7 RC6 (b01367aa)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2 
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on and the browser is open.
- The headset is connected to a PC.
- The “Redirect Console to Logcat” option is enabled from “Developer Options”.

**[Steps to reproduce]:**
1. Open a “Command Prompt” prompt on the connected PC.
2. Run the "adb logcat -s GeckoConsole" command in the “Command Prompt”.
3. Using the VR device, navigate to “https://threejs.org/examples/webxr_vr_ballshooter” and click the “ENTER_VR” button.
4. Observe the logcat file on the “Command Prompt”.

**[Expected results]:**
- The logcat is populated with entries.

**[Actual results]:**
- The logcat is not populated with entries.

**[Notes]:**
- Setting “Enable Debug Logging” to “On” will populate the logcat.

**Comment by bluemarvin** [comment]
This was fixed in #3153

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 11-141610021 (84494ec1) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the “Redirect Console to Logcat” setting and the “Enable Debug Logging” setting are merged into one and works as expected.
