### ISSUE TITLE
Editable text remains highlighted after being copied

### ISSUE THREAD

**Issue by heres-maria-sv-inactive** [MozillaReality/FirefoxReality#2445]
**[Affected Versions]:**
- Firefox Reality version 7 RC6 (b01367aa)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2 
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on and the browser is open.

**[Steps to reproduce]:**
1. Go to a website that has an input field (e.g. https://en.wikipedia.org/wiki/Main_Page).
2. Enter a few words in the input field.
3. Long press the trigger button on the controller to select a word.
4. Click the "Copy" button and observe the behavior.

**[Expected results]:**
- The word is no longer highlighted.

**[Actual results]:**
- The word is still highlighted.

**[Notes]:**
- Attached is a recording of the [issue](https://drive.google.com/file/d/168983wl1MhUVRjyZo2jM7oLcC2AH7hAD/view?usp=sharing).

**Comment by jvonitter** [comment]
related to #2215
