### ISSUE TITLE
Immersive mode can not be exited from the controller after changing the projection mode

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2448]
**[Affected Versions]:**
- Firefox Reality version 8-33431308 (aee8a16e);

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2 
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on and the browser is open.

**[Steps to reproduce]:**
1. Open a 360 video and play it in immersive mode.
2. Press the trigger button from the controller.
3. Click the projection button from the on screen controls.
4. Change the projection mode.
5. Press the back button on the controller and observe the behavior.

**[Expected results]:**
- Immersive mode is exited.

**[Actual results]:**
- Immersive mode is not exited.

**[Notes]:**
- The issue is not reproducible if the projection mode is not changed.
- Tracked by #1760.

**Comment by jvonitter** [comment]
@heres-maria is this youtube-specific?

**Comment by Softvision-GeluHaiduc** [comment]
No, it's not a youtube specific issue, this behavior can also be seen with Vimeo videos.

**Comment by heres-maria** [comment]
I have verified this issue is no longer reproducible with the latest Firefox Reality version 8-40040048 (ef08ff15) build. You can now exit immersive mode after changing the projection mode by pressing the controller button.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
