### ISSUE TITLE
The search field is automatically focused and the text caret appears when visiting the YouTube homepage

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2450]
**[Affected Versions]:**
- Firefox Reality version 8-33431308 (aee8a16e)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to the following website: “https://www.youtube.com/”
2. Observe the search field.

**[Expected results]:**
- The search field is not focused.

**[Actual results]:**
- The search field is automatically focused and the text caret appears.

**[Notes]:**
- The issue is not reproducible on any other website tried.
- Needed by #1760.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1I6Lem8CfOELDchRGFuz1D6dqs5lRiA6c).

**Comment by jvonitter** [comment]
I think this is probably ok. It doesnt prevent the user from doing anything on the page. 
@Softvision-GeluHaiduc if a user clicks into the search field when it's in this state, does the keyboard come up as expected?

**Comment by Softvision-GeluHaiduc** [comment]
Yes, if the user clicks the search field the keyboard appears.
If the search field is long pressed (and there is some text copied already) the paste context menu appears. So functionality is not affected.
The strange thing is that this behavior can only be seen on the youtube homepage, no other websites that I've tried had this.

**Comment by jvonitter** [comment]
It is weird, but I don't think we need to do anything about it.
