### ISSUE TITLE
The copy/paste context menu is positioned to the far left from the beginning of the search field on YouTube

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2451]
**[Affected Versions]:**
- Firefox Reality version 8-33431308 (aee8a16e)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- The window size is set to 1x.
- The YouTube home page is loaded.

**[Steps to reproduce]:**
1. Copy the URL link from the awesomebar.
2. Scroll the home page horizontally to the edge of the page.
3. Using the controller long click in the search bar.
4. Observe the position of the context menu.

**[Expected results]:**
- The context menu is positioned above the text caret at the beginning of the search field.

**[Actual results]:**
- The context menu is positioned to the far left from the beginning of the search field.

**[Notes]:**
- The issue is also reproducible if the window size is smaller than 1x.
- The issue is not reproducible if the window size is equal or greater than 2x.
- The issue is not reproducible if the search field is focused before scrolling.
- Needed by #1760.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1eAe59SGFNhuT9jqXZToYAyKG5W4YcF1y).

**Comment by keianhzo** [comment]
@Softvision-GeluHaiduc I can't reproduce this anymore, Can you confirm it still happens and that the STRs are still valid?

**Comment by Softvision-GeluHaiduc** [comment]
@keianhzo I have verified that this issue is no longer reproducible with the latest Firefox Reality version 11-141351718 (9d848c46) installed on the Oculus Go, HTC Vive Focus Plus and Pico G2 4K headsets.
Now, the copy/paste context menu is positioned at the beginning of the search field on YouTube.
As it is no longer reproducible I will close the issue.
