### ISSUE TITLE
MSAA discrepancies between FxR and Oculus Browser

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#2455]
Load https://webvr.info/samples/03-vr-presentation.html in OB and FxR. You can see that it looks quite more pixelated in FxR because JavaScript is not enabling MSAA (antialias parameter when creating WebGL context)

The current MSAA options in FxR settings only applies if JavaScript enabled MSAA, it doesn't force it. On the other hand oculus is forcing MSAA to improve quality by default.

cc @jvonitter we need a decision about if we should force it or not. We had MSAA force enabled in older versions, this behaviour was changed after a WebGL code change in Gecko (cc @jdashg for more info)

**Comment by jvonitter** [comment]
if i understand it correctly, sites are supposed to specify if they want it or not... so forcing it would overrule how they have it set. the effect would be nicer-looking but possibly less-performant.

i think we should respect a site's settings, but we should be smart about whether our default is on or off. @MortimerGoro - can you confirm what the default is for mobile vs desktop? i suspect we'll want to align with the way mobile does it.

**Comment by MortimerGoro** [comment]
The problem happens when the site doesn't specify if they want antialias or not. In that case OB defaults to MSAA enabled and FxR doesn't. So rather than forcing a value we should talk about the default value when the site doesn't specify it.

btw WebXr changes the way to initialize the render surface and they have a antialuas=true default value here:
https://www.w3.org/TR/webxr/#dictdef-xrwebgllayerinit

@kearwood can you confirm that we can stop caring about this issue in WebXR?

**Comment by bluemarvin** [comment]
In the WebVR case I have seen sites become unusable when forcing MSAA on. That would be my concern.

**Comment by kearwood** [comment]
I can confirm that this won’t be an issue with WebXR.  WebXR explicitly makes antialiasing the default, without affecting the behaviour of non XR canvases.  Sites are still able to disable antialiasing if it would conflict with their algorithms

**Comment by jvonitter** [comment]
ok, based on all of this i think we can safely leave things as they are. @MortimerGoro go ahead and close this if you're satisfied.

**Comment by MortimerGoro** [comment]
Perfect, I'm glad we can stop caring about this in WebXR
