### ISSUE TITLE
Some of the YouTube controls/buttons flicker when they are hovered in a window size equal or smaller than 1x

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2459]
**[Affected Versions]:**
- Firefox Reality version 8-33452219 (bfee54ee)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- The window size is set to 1x.

**[Steps to reproduce]:**
1. Navigate to any video and play the video. (if immersive mode is entered exit)
2. Using the controller hover the video controls. (play, Next, volume, CC, …)
3. Observe the behavior.

**[Expected results]:**
- The video controls appear and are actionable.

**[Actual results]:**
- The video controls flicker.

**[Notes]:**
- The flicker can be seen on the “Upload” button tooltip as well, when the button is hovered.
- The flicker can be seen on the “Watch Later” button as well, when the button is hovered.
- The issue is not reproducible on a window size bigger than 1x size.
- The video controls flicker is much more visible on the HTC device.
- Needed by #1760.
- Attached a screen recording of the issue on the HTC device [here](https://drive.google.com/open?id=1HGaLgyqNHfFGtWNthpegR5ZTw6ocIUrl).
- Attached a screen recording of the issue on the Oculus device [here](https://drive.google.com/open?id=1COaRdmn1waIvgBWxZNFsbS1WMoU7fiSs).

**Comment by jvonitter** [comment]
Not sure there's anything we can do about this, as it's the site's UI and now our own.

**Comment by Softvision-GeluHaiduc** [comment]
@jvonitter, This issue is not reproducible with the production version of the app (V7) and therefore I took it as a regression since it is reproducible with yesterday's build from master (version 8-33452219 (bfee54ee)).
However, using today's latest build from master the issue is only partially reproducible, the video controls are no longer flickering, but some tooltips and buttons are still affected by this issue.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality build 8-33521753 (379b8f1f) from master.
Tested on Oculus Quest (Android 7.1.1), Oculus Go (Android 7.1.2), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
