### ISSUE TITLE
[Intermittent] On some videos on YouTube immersive mode is not entered on the first click

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2461]
**[Affected Versions]:**
- Firefox Reality version 8-33452219 (bfee54ee)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to any immersive video on youtube. (e.g. [GoPro VR](https://www.youtube.com/watch?v=4yB_hwKe4Dc))
2. Click on the video.
3. Observe the behavior.

**[Expected results]:**
- The video starts playing in immersive mode.

**[Actual results]:**
- The video starts playing without entering in immersive mode.

**[Notes]:**
- Needed by #1760.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=15DtN0iv6d9auuc4ZR6wgiB2U0WztiU6s).

**Comment by jvonitter** [comment]
@MortimerGoro I think this is likely going to be fixed by the bunch of other youtube issues you're tackling, so i'm keeping it in, but i dont think there's enough info to work on it directly.

**Comment by MortimerGoro** [comment]
This should be already fixed.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 8-40072114 (81fef4e7) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, immersive mode is entered on the first click on the videos that I tried it on.
