### ISSUE TITLE
The theater mode is exited when playing the next video

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2462]
**[Affected Versions]:**
- Firefox Reality version 8-33452219 (bfee54ee)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to a normal video on Youtube.
2. Play the video in theater mode.
3. Click the "Next" button fro the video controls.
4. Observe the behavior.

**[Expected results]:**
- The next video is played in theater mode

**[Actual results]:**
- The theater mode is exited but the next video is played.

**[Notes]:**
- This issue is also reproducible if the next video is auto-played or if a suggested video is clicked while in theater mode. 
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=16wWayAJVskYUP5D7Ckv2SFyKNSvXNIYU).

**Comment by MortimerGoro** [comment]
I can reproduce the same issue in Fenix. I created this GV issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1604450
