### ISSUE TITLE
The 360 video projection mode is set as default for all immersive videos

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2465]
**[Affected Versions]:**
- Firefox Reality version 8-33452219 (bfee54ee)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2 
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on and the browser is open.

**[Steps to reproduce]:**
1. Navigate to a 360 Stereo video (e.g. https://vimeo.com/214224792).
2. Play it and enter immersive mode.
3. Press the trigger button to display the on-screen controls.
4. Observe the active projection mode.

**[Expected results]:**
- The 360 Stereo projection mode is selected.

**[Actual results]:**
- The 360 projection mode is selected.

**[Notes]:**
- This issue is reproducible for all projection modes that are automatically opened in immersive mode.
- This issue is reproducible on multiple websites.
- Attached is a recording of the [issue](https://drive.google.com/file/d/13Y4QsyD1NK2-RptFSSDbaQ_Z7Lm4NB7r/view?usp=sharing).

**Comment by jvonitter** [comment]
Not sure I understand what's happening here. Is the problem that "360" should be shown as selected but "360 stereo" is shown instead? Is it clear what the differences is between those two selections?

**Comment by heres-maria** [comment]
@jvonitter The "360 Stereo" should be shown selected, but "360" is shown instead. 

- The behavior we expected is that immersive mode automatically selects the right projection mode for the video played. I hope we understood this expected behavior correctly.

- The difference between those two projection modes, as we understand it, is that "360" is monoscopic while "360 Stereo" is stereoscopic, the difference being the way they are filmed and meant to be projected. Videos made to be watched in "360 Stereo" will be doubled and distorted if the "360"  mode is selected.

- Additionally, regarding the first note: there are some videos that might be 180 degree that automatically open in immersive mode on "360", but we are unsure if they truly are 180 degree or if they were mislabeled. An example would be [this video](https://youtu.be/bi7FBwYeExI). 

I hope this explains any uncertainties. Please let us know if we have the wrong idea.

**Comment by MortimerGoro** [comment]
There isn't a standard and reliable way to detect the video projection type. All we can do for now is just do some text search. We search for `360`, we could search also for `stereo` to detect this case

**Comment by heres-maria** [comment]
I have verified this issue and it is no longer reproducible with the latest Firefox Reality version 8 RC1 build (7a444d0c). 
The "360 Stereo" projection mode is now automatically selected for this type of videos, including: 
    https://vimeo.com/214224792
    https://www.youtube.com/watch?v=vxNriWfhRRA

Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
