### ISSUE TITLE
The last active projection mode remains selected in theater mode for itself as well as subsequent videos

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2471]
**[Affected Versions]:**
- Firefox Reality version 8-33471216 (e14e5956)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Open a normal video and play it in theater mode (e.g. https://www.youtube.com/watch?v=RxAtuMu_ph4).
2. Open the projection mode menu and select an option.
3. Exit immersive mode. 
4. Open the projection menu and observe it.

**[Expected results]:**
- No option is highlighted.

**[Actual results]:**
- The last active option is highlighted.

**[Notes]:**
- This issue is reproducible on multiple websites (e.g. Vimeo, YouTube) and the projection mode remains selected across different websites.
- The projection mode remains selected for all subsequent videos except for those that automatically enter the immersive mode - see #2465.
- This issue is also reproducible for videos played in theater mode after an immersive mode video was played.
- Related to #2009.
- Attached is a recording of the [issue](https://drive.google.com/file/d/1yhx6vDtAbMC38pKLnLisMadF6U9JAPcx/view?usp=sharing).

**Comment by jvonitter** [comment]
While I can't really think of a reason why someone would try to put a normal video into a different projection mode, the menu itself should still work correctly.

**Comment by heres-maria** [comment]
I have verified this issue and it is partially reproducible with the latest Firefox Reality version 8-40040048 (ef08ff15) build. 
The last active projection mode is very briefly highlighted when opening the projection menu from theater mode. 
This behavior can be observed on the Oculus Go (Android 7.1.2), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2) devices, but not on the Oculus Quest (Android 7.1.1).

**Comment by MortimerGoro** [comment]
Fixed in #2500

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 8-40131058 (dd3477cd) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the last active projection mode no longer remains selected in theater mode for itself or any subsequent video.
