### ISSUE TITLE
The "Back" navigation button is wrongly actionable after opening a link that opens in a new tab

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2473]
**[Notes]:**
- After the "Back" button is clicked the previous page can no longer be accessed by clicking the "Forward" button. 

**[Affected Versions]:**
- Firefox Reality version 8-33470001 (52a50579)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to https://www.w3schools.com/jsref/met_win_prompt.asp
2. Click the "Click on "Try it yourself" button.
3. Click the "Back" navigation button.

**[Expected results]:**
- Nothing happens, the button is not actionable.

**[Actual results]:**
- The previous page is displayed and the "Forward" button is no longer actionable.

**[Additional Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=12KIBJVbElNnJiEaxYKeRXOm9td_VNycM).

**Comment by keianhzo** [comment]
This should be the expected behavior. Tabs opened through `window.open` are treated as stacked sessions and are un-stacked going back in history. @jvonitter 

Maybe one thing that we could change is not showing the `New Tab added` notification when the tab is opened in foreground.

**Comment by jvonitter** [comment]
i agree, this is expected behavior. no changes for now.
