### ISSUE TITLE
Window is scrolled too when bookmarks/history are scrolled

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#2475]
STR:
- Visit: http://prosperxr.com/vrportfolio#phoenix
- Open history
- Scroll down and you can notice the history scroll ups immediately with new items
- It's worse in this page because they create new items when the page is scrolled so it's impossible to use the history while in this page

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 8-33472001 (6ba38814) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the window is not scrolled when bookmarks/history is scrolled.
