### ISSUE TITLE
The Copy/Paste context menu appears when long clicking on an empty space in the live chat on YouTube

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2479]
**[Affected Versions]:**
- Firefox Reality version 8-33472001 (6ba38814)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to the following video: https://www.youtube.com/watch?v=EEIk7gwjgIM. (or any YouTube video with a live chat)
2. Using the controller long click inside the live chat on an empty space.
3. Observe the behavior.

**[Expected results]:**
- Nothing happens.

**[Actual results]:**
- The Copy/Paste context menu appears at the top of the live chat.

**[Notes]:**
- The draghandels also appear at the bottom of the chat.
- If the window is scrolled the context menu appears outside the window.
- If the live chat is scrolled the context menu remains in the same position.
- Needed by #1760.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1oLMUtJWvW7KA9ZcETRBOGwdcuHeuJ6bX).

**Comment by keianhzo** [comment]
@Softvision-GeluHaiduc I can't reproduce this anymore, Can you confirm it still happens and that the STRs are still valid?

**Comment by Softvision-GeluHaiduc** [comment]
@keianhzo I have verified that this issue is no longer reproducible with the latest Firefox Reality version 11-141351718 (9d848c46) installed on the Oculus Go, HTC Vive Focus Plus and Pico G2 4K headsets.
Now, the Copy/Paste context menu doesn’t appear when long clicking on an empty space in the live chat on YouTube.
As it is no longer reproducible I will close the issue.
