### ISSUE TITLE
The Copy/Paste context menu appears positioned to the far right when long clicking on a word in the live chat on YouTube

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2480]
**[Affected Versions]:**
- Firefox Reality version 8-33472001 (6ba38814)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to the following video: https://www.youtube.com/watch?v=EEIk7gwjgIM. (or any YouTube video with a live chat)
2. Using the controller long click on a word inside the live chat.
3. Observe the position of the context menu.

**[Expected results]:**
- The Copy/Paste context menu appears positioned centered above the word.

**[Actual results]:**
- The Copy/Paste context menu appears positioned to the far right of the word. (outside the window)

**[Notes]:**
- If the window is scrolled the context menu appears outside the window and keeps moving up while scrolling down on the page.
- If the live chat is scrolled the context menu disappears after the selected word is scrolled.
- On window sizes equal or larger than 1.5x the context menu appears positioned centered above the the word selected but when the window is scrolled the context menu still appears outside the window.
- Needed by #1760.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1Vk0APKHCx1LR2mIQ_2GVmKoeskT9NKuk).

**Comment by keianhzo** [comment]
@Softvision-GeluHaiduc I can't reproduce this anymore, Can you confirm it still happens and that the STRs are still valid?

**Comment by Softvision-GeluHaiduc** [comment]
@keianhzo I have verified that this issue is no longer reproducible with the latest Firefox Reality version 11-141351718 (9d848c46) installed on the Oculus Go, HTC Vive Focus Plus and Pico G2 4K headsets.
Now, the Copy/Paste context menu appears positioned above the word long clicked in the live chat on YouTube.
As it is no longer reproducible I will close the issue.
