### ISSUE TITLE
The on screen keyboard can not be dismissed by clicking just outside the keyboard left/bottom border

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2490]
**[Affected Versions]:**
- Firefox Reality version 8-33472001 (6ba38814)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Click inside the URL bar.
2. Using the controller click just outside the left/bottom keyboard border.
3. Observe the behaviour.

**[Expected results]:**
- The on screen keyboard is dismissed.

**[Actual results]:**
- The on screen keyboard is not dismissed and the “Move” button has a click effect.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1teiLlkHArUQkSwYhCpc_-bvmdZTSbweM).

**Comment by jvonitter** [comment]
possibly related to #2565 ?

**Comment by keianhzo** [comment]
Unrelated. We need to handle unhandled keyboard events to dismiss the keybord.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9-40240151 (7e03c944) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the on screen keyboard can be dismissed by clicking just outside the keyboard left/bottom borders.
