### ISSUE TITLE
The navigate forward button is no longer actionable after clicking on a card in the homepage

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2491]
**[Affected Versions]:**
- Firefox Reality version 8-33472001 (6ba38814)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to any website. (e.g. facebook.com)
2. Click the “Back” button from the navigation controls.
3. Click on any card from the homepage.
4. Observe the “Forward” button.

**[Expected results]:**
- The “Forward” button is still actionable.

**[Actual results]:**
- The “Forward” button is no longer actionable.

**[Notes]:**
- After dismissing the card navigating back to the visited website is still not possible.
- If no card is clicked navigating back to the website is still possible.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1JqUZU5WW5wrxZ2_wcdL3ku6Lx8QKDc5B).

**Comment by keianhzo** [comment]
@jvonitter Last time I checked this is related to how the content feed manages the history state. It is related to this issue: https://github.com/MozillaReality/FirefoxReality/issues/2268#issuecomment-553988947 (although it has been moved and I don't have access to that repo so I don't know the status)

**Comment by jvonitter** [comment]
Yep, that's #381 over in the content feed repo. Closing it here.
