### ISSUE TITLE
The tabs from the second row forward slightly jumps up when being dismissed in the tab view

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2492]
**[Affected Versions]:**
- Firefox Reality version 8-33472001 (6ba38814)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Make sure to have at least 7 tabs created.

**[Steps to reproduce]:**
1. Click the Tabs button in the menu tray.
2. Using the controller hover one of the tabs from the second row.
3. While the tab is hovered click the dismiss “X” button.
4. Observe the behaviour.

**[Expected results]:**
- The tab is dismissed.

**[Actual results]:**
- While dismissed the tab slightly jumps up.

**[Notes]:**
- The issue is reproducible on any row from the second row forward.
- The issue is not reproducible on tabs from the first row.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1bDzQRIUspRa69gt47zB_fsmkfmdt5c1L).

**Comment by jvonitter** [comment]
This is ok as is.
