### ISSUE TITLE
Let you set the name of your device / FxR instance or delete old ones

### ISSUE THREAD

**Issue by joshmarinacci** [MozillaReality/FirefoxReality#2494]
**Is your feature request related to a problem? Please describe.**
When I send a tab to a device from my desktop Firefox I see several devices called Oculus Quest. This is probably because I have installed and then removed FxR several times. 

**Describe the solution you'd like**
There should be a way to list all of my devices, to rename them (so they aren't all called Firefox Reality on Oculus Quest) and delete devices I don't need anymore.

**Comment by bluemarvin** [comment]
The accounts api currently does not support this. You have to do all device management from https://accounts.firefox.com/

**Comment by joshmarinacci** [comment]
Until this is possible we should have a button in the settings somewhere to jump to this page so people can edit it there.

**Comment by jvonitter** [comment]
Yeah, it wouldn't be too hard to put a link in account settings so they can do it in the headset. At the same time, we have this problem more than most users will.

Putting this in our next polish milestone.

**Comment by keianhzo** [comment]
@emstanley @bluemarvin  I've put together a UI for this, similar to what Desktop has:

<img width="371" alt="Screen Shot 2020-06-23 at 10 43 15" src="https://user-images.githubusercontent.com/837184/85381685-7ee8b080-b53e-11ea-970a-9c9977b547ed.png">

The button doesn't have state and it just opens the settings URL in a new window. Is that what we want?

**Comment by keianhzo** [comment]
The method already exists in AS but it needs to be exposed in AC. Waiting until the add that. Pinged the AC team to see if they can add it to an upcoming sprint.

**Comment by grigoryk** [comment]
Is this about renaming the currently signed-in FxA device? If so, everything you need has been around for a while (e.g. Fenix has had this functionality since sometime last year).

You'd need to do something like this:
```
accountManager.authenticatedAccount()
                    ?.deviceConstellation()
                    ?.setDeviceNameAsync(newValue, context)
                    ?.await()
```

Here's an example from Fenix's account settings UI: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt#L290-L304

**Comment by keianhzo** [comment]
Thanks @grigoryk! We should have updated the issue title, this issue evolved from device management to account management at some point and that's the reason why we wanted to use the `getManageAccountUrl` method. WebChannels has already landed in FxR so we should be ok but given that there still some missing functionality and that it's probably going to take a while to expose it maybe we can re purpose this issue and just fix the original device management issue and open another one for the general account management page.

**Comment by keianhzo** [comment]
Opened a different issue for the Manage Account feature as it's going to take a while: https://github.com/MozillaReality/FirefoxReality/issues/3564
