### ISSUE TITLE
The Hamburger menu is positioned to the left of the button in multiwindow

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2495]
**[Affected Versions]:**
- Firefox Reality version 8-33512130 (8dd6bffd)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Click "+" button in the menu tray twice to create two new windows.
2. Click the Hamburger menu in each window.
3. Observe the position of the menu.

**[Expected results]:**
- The Hamburger menu is positioned centered above the button.

**[Actual results]:**
- The Hamburger menu is positioned above the button to the left.

**[Notes]:**
- The issue is reproducible with 2 windows as well.
- The issue is not reproducible with a single window.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1wRocvDM-eNyMeoA0dWtDkeE6lKT_BDcs).

**Comment by jvonitter** [comment]
This is ok. It keeps the hamburger menu in the boundaries of the page and makes it feel responsive.
