### ISSUE TITLE
The “New Tab Added!” and “Saved to Bookmarks!” notifications are positioned to the left of the button in multiwindow

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2496]
**[Affected Versions]:**
- Firefox Reality version 8-33512130 (8dd6bffd)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Click "+" button in the menu tray twice to create two new windows.
2. Click on the window to the right and navigate to the following page: “https://en.wikipedia.org/wiki/Main_Page”.
3. Bookmark the page.
4. Observe the position of the notification.

**[Expected results]:**
- The “Saved to Bookmarks!” notification is positioned centered above the button.

**[Actual results]:**
- The “Saved to Bookmarks!” notification is positioned above the button to the left.

**[Notes]:**
- The issue is also reproducible with the “New Tab Added!” notification.
- The issue is reproducible with 2 windows as well.
- The issue is not reproducible with a single window.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1GlTUICJt-bKn2JJYLMKn1jfD0KEYJiFi).

**Comment by keianhzo** [comment]
@jvonitter I wouldn't consider this an issue, the notification position is ok it's just a question of perspective. I guess we could correct the perspective moving the notifications when they are on the sides but I'm not sure if it's really worth it.

**Comment by jvonitter** [comment]
I agree, this is fine as is.
