### ISSUE TITLE
The app crashes if the First Explainer page is dismissed by clicking outside it's borders if it was opened from "Send Tab to Device" option

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2498]
**[Notes]:**
- If the First Explainer page is triggered from "View Tabs", when clicking outside it's borders, the View Tabs and First Explainer page are overlapping and only after the "Start Browsing" button is clicked the app crashes. If the "Sign In" button is clicked the sign in process is started and the app is NOT crashed.
Here is a screen recording with this behavior: [link](https://drive.google.com/open?id=17mEGMZGs1AGC8IpikKUhEugSQsQkGvU7).

**[Affected Versions]:**
- Firefox Reality version 8-33512130 (8dd6bffd)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- You are not logged into an FxA account.

**[Steps to reproduce]:**
1. Click the "Hamburger" button.
2. Click the "Send Tab to Device" option.
3. Click outside the First Explainer page boundaries.
4. Observe the behavior.

**[Expected results]:**
- The page is dismissed.

**[Actual results]:**
- The app crashes.

**[Additional Notes]:**
- This issue is also reproducible with the production version of the app (v7).
- This issue is not reproducible is dismissed if the First Explainer page is displayed after installing/updating the app.
- Attached are crash the report, logcat and the screen recording of the issue:[link]().
	- Screen recording: [link](https://drive.google.com/open?id=1CgxUswDWeXHXVfBuGEahlGdGHgEHQvN3).
	- Logcat: [link](https://drive.google.com/open?id=1G-lWF8Ncf8qWrJOMLQgfvD0n5N98vC03).
	- Crash Report: [link](https://crash-stats.mozilla.com/report/index/bp-83c55d84-0fcf-48c2-a64d-1f92a0191218).

**Comment by heres-maria** [comment]
I have verified this issue is no longer reproducible with the latest Firefox Reality version 8-33580833 (777a0ae00) build. The app no longer crashes when clicking outside the First Explainer page.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
