### ISSUE TITLE
The First View page is not rendered correctly in other languages

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2499]
**[Affected Versions]:**
- Firefox Reality version 8-33512130 (8dd6bffd)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The app's language is set in "Francais".
- You are not logged into an FxA account.

**[Steps to reproduce]:**
1. Click the "Hamburger" button.
2. Click the "Send Tab to Device" option.
3. Observe the propmt's UI.

**[Expected results]:**
- The UI is rendered correctly.

**[Actual results]:**
- The strings are overlapping with other elements and the buttons are not aligned.

**[Notes]:**
- Attached is a screen shot of the issue:
![org mozilla vrbrowser-20191218-151017](https://user-images.githubusercontent.com/40061643/71098086-ca9a5600-21b9-11ea-8264-de8f2cfc98f4.jpg)

**Comment by jvonitter** [comment]
@Softvision-RemusDranca Can you let us know if this is a problem for languages other than French?
@Delphine can we try for some shorter strings here?

**Comment by Softvision-RemusDranca** [comment]
@jvonitter I've retested this issue and is not reproducible on any of the available locales with the latest build 8-33531244 (c7f86edb) from master. However a new behavior occurs that is affecting the description of the prompt. This issue is documented in : #2519.

**Comment by Delphine** [comment]
Please let me know if you still need anything from me. As I understand it, this isn't an issue on master anymore.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 8-40040048 (ef08ff15) build. The UI is now rendered correctly.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
