### ISSUE TITLE
How to switch to VR on Daydream?

### ISSUE THREAD

**Issue by poVoq** [MozillaReality/FirefoxReality#25]
I feel stupid asking this, but after installing the released .apk on my Daydream compatible device I can use FirefoxReality fine as a mobile browser, but there seems to be no way to actually switch into VR mode?

Does it only work with the Daydream headset NFC tag? I am using a third party headset that doesn't come with this NFC tag, but all other Daydream apps can be switched to VR manually.

**Comment by poVoq** [comment]
OK, it can be started from within Daydream, but some option to start it from the 2d GUI would help I think.

**Comment by bluemarvin** [comment]
Current builds only launch in VR now.
