### ISSUE TITLE
Youtube site has horizontal scrolling in Desktop Mode

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#2501]
## Configuration

Firefox Reality version: 33452219
Firefox Reality build ID: bfee54e 

Hardware: All

## Steps to Reproduce

1. Open youtube
2. Click on a video
3. Switch to Desktop Mode

## Current Behavior

The video page has horizontal scrolling which it doesn't have in VR/Mobile mode.

## Expected Behavior

No horizontal scrolling is expected.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 8-40062127 (8a91dcb6) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the YouTube site has no horizontal scrolling in desktop mode.
