### ISSUE TITLE
[Intermittent] A video is not played when clicking the play button from the on-screen controls in immersive mode

### ISSUE THREAD

**Issue by heres-maria-sv-inactive** [MozillaReality/FirefoxReality#2504]
**[Note:]**
- This issue seems to be hard to reproduce and I was not able to determine whether there are other parameters that would influence its occurence.

**[Affected Versions]:**
- Firefox Reality version 8-33521753 (379b8f1f)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- Make sure “Autoplay Media” is turned off.

**[Steps to reproduce]:**
1. Go to a 360 YouTube video, but do not play it.
2. Enter immersive mode by clicking the full screen button.
3. Press the trigger button to display the on-screen controls.
4. Click the play button and observe the behavior.

**[Expected results]:**
- The video starts playing.

**[Actual results]:**
- The video doesn’t start playing.

**[Additional Notes]**
- The issue is reproducible for videos that have immersive mode opened from theater mode as well as those that automatically open in immersive mode.
- The button does function when resuming a video that was paused.
- I was not able to reproduce this issue on websites other than YouTube(e.g. Veoh).
- Needed by #1760.
- Attached is a recording of the [issue](https://drive.google.com/file/d/1YXCZ34c0yPkxihRsoAolNJSefYqcVIah/view?usp=sharing).

**Comment by jvonitter** [comment]
Randall thinks this might be caused by an autoplay bug the is blocking the GV API https://bugzilla.mozilla.org/show_bug.cgi?id=1524092
