### ISSUE TITLE
Oculus Quest Handtracking

### ISSUE THREAD

**Issue by ghost** [MozillaReality/FirefoxReality#2505]
** Is your feature request related to a problem? Please describe. **
It is awkward to operate without a controller.

** Describe the solution you'd like **
We want you to support hand tracking that was supported by Oculus Quest.

** Describe alternatives you've considered **
Have a controller.

** Additional context **

**Comment by jvonitter** [comment]
Handtracking is something we may explore in the future, but not just yet.

**Comment by 10lk** [comment]
I am looking forward to.☺
