### ISSUE TITLE
The Youtube's Sidebar menu is briefly displayed and dismissed when resizing the window to a 3x size 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2511]
**[Affected Versions]:**
- Firefox Reality version 8-33521753 (379b8f1f)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to Youtube website.
2. Click the Hamburger menu.
3. Click the "Resize Window" button.
4. Select the 3x size and click the Save(check sign) button.
5. Observe the left side of the page.

**[Expected results]:**
- The Youtube's Sidebar menu is displayed and remains displayed.
OR
- The Youtube's Sidebar menu is not displayed.

**[Actual results]:**
- The Youtube's Sidebar menu is briefly displayed and auto-dismissed.

**[Notes]:**
- Needed by #1760.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1PdOGeYGDBy90l2eWBBVc7LLG0WIN7Iyo).

**Comment by MortimerGoro** [comment]
Already fixes, this happened using the old UA and layout

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 8-40101959 (3c2a71e2). Now, the Sidebar remains displayed after resizing to a 3x size.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
