### ISSUE TITLE
Add invalid certificate bypass to ssl error pages.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#2512]
**Is your feature request related to a problem? Please describe.**
User that need to use self-signed certs need a way to accept them.

**Describe the solution you'd like**
Now that https://bugzilla.mozilla.org/show_bug.cgi?id=1553265 has landed in GV we can add a bypass button to the FxR ssl error pages.
![org mozilla vrbrowser dev-20191219-093032](https://user-images.githubusercontent.com/48839872/71195465-d716c100-2242-11ea-9955-7486174c5ec7.jpg)

**Additional context**
WebXR requires `https` so developers are likely to use self signed certs and will need a way to bypass the error page to view their work.

**Comment by jvonitter** [comment]
To test the SSL error, use https://untrusted-root.badssl.com/

Next to the "try again" button there should be an "advanced" button that, when pressed, shows additional information - similar to this:
![SSLadvanced](https://user-images.githubusercontent.com/48839872/71195545-02011500-2243-11ea-9746-5e8b6f85b4fa.PNG)

The button that says "Accept the risk and continue" should bypass the error.

**Comment by keianhzo** [comment]
We are currently using the AC `browser-errorpages` component for this. There is an opened issue in the backlog for this here: https://github.com/mozilla-mobile/android-components/issues/3960
