### ISSUE TITLE
Glean doesn't collect data from `org.mozilla.vrbrowser.wavevr`

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#2514]
## Configuration

Firefox Reality version: v.7
Firefox Reality build ID: 

Hardware: 
HTC Focus and Focus+

## Steps to Reproduce

1. Run WaveVR with the local build version.
2. Start Glean debugger with `adb shell am start -n org.mozilla.vrbrowser/mozilla.telemetry.glean.debug.GleanDebugActivity`. It will fail
3. If using `adb shell am start -n org.mozilla.vrbrowser.wavevr/mozilla.telemetry.glean.debug.GleanDebugActivity`. It works.

## Current Behavior

Getting failures to start Glean debugger, and there is no data be collected in `org_mozilla_vrbrowser` schema.

## Expected Behavior

The data from `org.mozilla.vrbrowser.wavevr` should still be able to uploaded to `org_mozilla_vrbrowser` schema.

## Context

`wavevr` is not an actual distribution channel, that is for separating the build for our partner whose distribution channel is `wavevrStore`. Therefore, we have two application id, `org.mozilla.vrbrowser` for deploying and `org.mozilla.vrbrowser.wavevr ` for developing.

```
```

</details>

**Comment by daoshengmu** [comment]
@Dexterp37. Is there an approach to let `org_mozilla_vrbrowser` schema has our application `org.mozilla.vrbrowser.wavevr` data? Or you can tell me where those data are put. These data come from developers, they do not really download our app from the store.

**Comment by Dexterp37** [comment]
Hey, a few questions first, because I'm not entirely sure I understand the problem:

1. Are both `org.mozilla.vrbrowser.wavevr` and `org.mozilla.vrbrowser` used in *released* applications? 
2. Is **only used for local developer builds**? I'm asking since you say:

> we have two application id, `org.mozilla.vrbrowser` for deploying and `org.mozilla.vrbrowser.wavevr` for developing.

3. When running `adb shell am start -n org.mozilla.vrbrowser/mozilla.telemetry.glean.debug.GleanDebugActivity`, are you trying to debug a [`wavevr` variant](https://github.com/MozillaReality/FirefoxReality/blob/c7f86edb88b80e4e8771692c013a698dd4e22030/app/build.gradle#L186-L196)? Because that has a different application id, `org.mozilla.vrbrowser.wavevr`, so trying to trigger the debug activity on `org.mozilla.vrbrowser` will definitely fail, as it's the wrong application id.

@daoshengmu , in [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1592705) it was asked to enable just  `org.mozilla.vrbrowser`, not `org.mozilla.vrbrowser.wavevr`. If you need to collect data from a released application that has the latter id, it needs to be activated as well. I filed [this new bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1605319). Please let me know if that's the case, so that I can enable that before we go out on PTO :)

**Comment by daoshengmu** [comment]
1 `org.mozilla.vrbrowser.wavevr`  only for developers and QAs. It is not actually released for distribution. The number of that DAU just a few, but they are only for developing.
2. Yes. for developers.
3. using adb shell am start -n `org.mozilla.vrbrowser.wavevr/mozilla.telemetry.glean.debug.GleanDebugActivity` Glean Debugger works.

Per our Slack conversation, we feel we don't need to collect these telemetry that are from non-released channels. We just have to make sure our data from application id `org.mozilla.vrbrowser` works properly.

**Comment by daoshengmu** [comment]
I think we still need to fix this issue but I would like to take a look at what else application id we have instead of `org.mozilla.vrbrowser`. I wonder there would be a case that people make their own build and distribute our app outside these official channels.

**Comment by daoshengmu** [comment]
See also, #1476

**Comment by Dexterp37** [comment]
> 
> 
> I think we still need to fix this issue but I would like to take a look at what else application id we have instead of `org.mozilla.vrbrowser`.

Please note that this is strictly for collecting telemetry from devs and QA teams. Before making this happen, you should check with Data Stewards if this is in compliance with our policy.

> I wonder there would be a case that people make their own build and distribute our app outside these official channels.

If you collect telemetry by default using the 'dev' id, then this might become a problem. If you are worried about people forking this repo and publishing an application using the real application id, this shouldn't be an issue: the stores forbid other applications to have the same app id of a published one.

**Comment by daoshengmu** [comment]
Per our internal discussion, we wanna leave it as is for now. Most of the users who are using `org.mozilla.vrbrowser.wavevr` are QA and developers. We might have some users outside our knowledge but it is not a big number.

**Comment by daoshengmu** [comment]
Close it because we have decided to remove `org.mozilla.vrbrowser.wavevr` table

**Comment by Dexterp37** [comment]
> 
> 
> Close it because we have decided to remove `org.mozilla.vrbrowser.wavevr` table

@daoshengmu , what would "removing" mean in this case? Does it mean that the id `org.mozilla.vrbrowser.wavevr` will be removed from the sourcecode?

**Comment by daoshengmu** [comment]
> > Close it because we have decided to remove `org.mozilla.vrbrowser.wavevr` table
> 
> @daoshengmu , what would "removing" mean in this case? Does it mean that the id `org.mozilla.vrbrowser.wavevr` will be removed from the sourcecode?

I closed it because the dataset of `org-mozilla-vrbrowser-wavevr` has been moved to `UnwantedDataEception`. The `org.mozilla.vrbrowser.wavevr` id still exists in our source code, we just are not interested in their data more.

**Comment by Dexterp37** [comment]
> 
> 
> > > Close it because we have decided to remove `org.mozilla.vrbrowser.wavevr` table
> > 
> > 
> > @daoshengmu , what would "removing" mean in this case? Does it mean that the id `org.mozilla.vrbrowser.wavevr` will be removed from the sourcecode?
> 
> I closed it because the dataset of `org-mozilla-vrbrowser-wavevr` has been moved to `UnwantedDataEception`. The `org.mozilla.vrbrowser.wavevr` id still exists in our source code, we just are not interested in their data more.

I understand that, but this is still being sent. I would suggest to change the code so that for these builds no telemetry is sent at all. It is straightforward, Fenix does this as well.
