### ISSUE TITLE
[L10n] The description from the First View page doesn't indicate that it is scrollable

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2519]
**[Notes]:**
- This issue can mislead the end users since the part of the description that is not visible can be missed.

**[Affected Versions]:**
- Firefox Reality version 8-33531244 (c7f86edb)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The app's language is set in "Francais".
- You are not logged into an FxA account.

**[Steps to reproduce]:**
1. Click the "Hamburger" button.
2. Click the "Send Tab to Device" option.
3. Observe the description from the middle of the prompt.

**[Expected results]:**
- The description fits the prompt's view.
OR
- The description indicates that is scrollable.

**[Actual results]:**
- The description doesn't indicate that is scrollable and doesn't fits the prompt's view.

**[Additional Notes]:**
- The locales on which this issue is reproducible are: NL, FR, DE, ES, and RU.
- As a side effect of this issue some localized descriptions are scrollable even if they fit the prompt's view.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1-OWQFFd1wMUy4a4ee6QA8o3zvM0flGGL).

**Comment by keianhzo** [comment]
I guess this shouldn't be scrollable, we should just find the right dialog size so every language fits.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and is no longer reproducible with the latest Firefox Reality version 8-40040048 (ef08ff15) build. The UI is now rendered correctly on the affected locales that were mentioned in this issue.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
