### ISSUE TITLE
The focus area for the cards from Settings is wrongly actionable outside their top borders

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2524]
**[Affected Versions]:**
- Firefox Reality version 8-33550026 (933fcd51)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Click the Settings button.
2. Hover over the top sections of the cards.
3. Observe the behavior.

**[Expected results]:**
- The cards are not highlighted.

**[Actual results]:**
- The cards are highlighted and if the outside area is clicked their menus are opened.

**[Notes]:**
- As a side effect of this issue, the bottom cards are highlighted when hovering the top cards.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1bwGVCop41FYp4400fsftb3cY_DRz9VC-).

**Comment by keianhzo** [comment]
I don't think this is a regression, we have never had input clipping for the settings menu buttons that I know.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 8-40101959 (3c2a71e2) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the focus area for the cards from Settings is no longer actionable outside their top borders.
