### ISSUE TITLE
[L10n] The "Reset" button's name from the "Manage Account" prompt is cut off

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2528]
**[Affected Versions]:**
- Firefox Reality version 8-33550026 (933fcd51)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The app's language is set in "Polish".
- You are logged into an FxA account.

**[Steps to reproduce]:**
1. Click the Settings button.
2. Click the "Manage Account" card.
3. Observe the "Reset" button.

**[Expected results]:**
- The button is correctly displayed.

**[Actual results]:**
- The name of the button is cut off.

**[Additional Notes]:**
- I was only able to reproduce this issue with the "PL" locale.
- Attached is a screenshot of the issue:
![ManageAccountResetPL](https://user-images.githubusercontent.com/40061643/71365246-0dd43a80-25a7-11ea-85ab-663c76818f63.jpg)

**Comment by jvonitter** [comment]
seems like if this happens for "reset" in one dialog, it probably happens in all of them. or are we using a different/shorter phrase in other places?

**Comment by Softvision-RemusDranca** [comment]
@jvonitter This issue is only reproducible on the Polish locale and on the "Manage Account" prompt. Maybe we could use only the  first word "Przywróć" as for the other prompts where the "Reset" button is available? I attached a screen shot from the Privacy and Security prompt for reference.

![PolishReset](https://user-images.githubusercontent.com/40061643/71887884-ab06a580-3147-11ea-853b-876a87cf0318.jpg)

**Comment by jvonitter** [comment]
Checked with a native Polish speaker and learned:
if we had the descriptive sentence next to the button then `Przywróć` for makes sense on the button.
But right now it says `Reset original...` missing third word.

@Delphine can we get the strings for the description and the button updated?

**Comment by Delphine** [comment]
CC @piotrdrag
Adding the Polish localizer to this discussion, so he can help advise.
Thanks so much for flagging!

**Comment by piotrdrag** [comment]
I’d prefer to go with “Przywróć domyślne” (and are you sure there are no languages with longer strings, e.g. German?), but I’ll change the string to the shorter version for now.

**Comment by Delphine** [comment]
I don't have access to builds right now, but I agree it would be good to double check with other languages, such as German.
@Softvision-RemusDranca: Could you possibly help us with this please?

**Comment by Softvision-RemusDranca** [comment]
Hey @Delphine, glad to help. 
I checked the other languages and none of them seem to have long strings that break the "Reset" buttons UI.
There is only one small concern because Korean and Finland languages are not yet translated, or not yet uplifted in the latest build. But this is a small concern and on other cards where the "Reset" button is available there are no UI issues.
I've also attached a screenshot with other languages:
![Untitled](https://user-images.githubusercontent.com/40061643/72354261-1b846800-36ee-11ea-8055-a751ba257090.png)

**Comment by Delphine** [comment]
Thanks for checking!
I see Korean is at 65% translated on Pontoon, and Finnish is at 82% - but we don't require 100% completion for locales unless it's French and German (as per our SLA with Leadership).
So it's not surprising that they don't appear entirely localized :)

**Comment by keianhzo** [comment]
@Softvision-RemusDranca Per the conversation above and the latest PR that addressed this https://github.com/MozillaReality/FirefoxReality/pull/2609, this issue should be now fixed.
We are still exposed to this type of problems for other languages in the future though but as commented in https://github.com/MozillaReality/FirefoxReality/issues/2532 growing the buttons more to adjust more languages doesn't make much sense as it makes buttons for other languages to look empty.

**Comment by keianhzo** [comment]
@Softvision-RemusDranca I believe this issue has been fixed for the reported languages.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using Firefox Reality 11-141720334 (f5972af). Now only the "Przywróć" string is displayed for the Reset button for "Polish" language.
Tested on HTC Vive Focus (Android 7.1.2), Oculus Quest (Android 7.1.1), and Pico Neo 2 (Android - 8.1.0) devices.

Considering this I will close this issue as verified fixed.
