### ISSUE TITLE
[L10n] The "Syncing" button's name from the "Manage Account" prompt is cut off

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2532]
**[Affected Versions]:**
- Firefox Reality version 8-33550026 (933fcd51)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The app's language is set in "Italian".
- You are logged into an FxA account and the account is synced.

**[Steps to reproduce]:**
1. Click the Settings button.
2. Click the "Manage Account" card.
3. Click the the "Sync Now" button.
4. Observe the "Syncing" button.

**[Expected results]:**
- The button is correctly displayed.

**[Actual results]:**
- The name of the button is cut off.

**[Additional Notes]:**
- The locales on which this issue is reproducible are: DE, NL, IT and PL.
- Attached is a screenshot of the issue:
![Manage Acount Syncing](https://user-images.githubusercontent.com/40061643/71367205-10399300-25ad-11ea-8a21-393c6f8e929a.png)

**Comment by jvonitter** [comment]
related to #2529

**Comment by keianhzo** [comment]
This has already been addressed in https://github.com/MozillaReality/FirefoxReality/pull/2609 for these specific languages. I see that this is still an issue for French but I don't feel that growing this button anymore with be a good solution as for most other languages the button will feel half empty. As we want to keep a constant width for all the buttons (@thenadj correct me if I'm wrong) I think the best approach is to adjust the translation and try to shorten it . That's probably something where @Pike could help with?

**Comment by thenadj** [comment]
I agree, let's try to adjust the translation and make it work.

**Comment by Pike** [comment]
Moving over to Delphine, who's the L10n PM for FxR.

**Comment by Delphine** [comment]
@TheoChevalier: Seems like this is still an issue for French, so wanted to loop you in, in case you had any suggestions to shorten the translation.
I admit that on my side, I can't really find an alternative for a shorter French translation ("Synchroniser maintenant"), so not sure this can be fixed on l10n side.

**Comment by keianhzo** [comment]
@Delphine Any updates on this?

**Comment by TheoChevalier** [comment]
Hi, I don’t see an easy way to shorten the French translation. Maybe just using "Synchroniser" (Sync)? Which, in French is obvious to be a verb, unlike English

I also don’t have a way of testing that UI and don’t see how it’s showing up in the screenshots above

**Comment by keianhzo** [comment]
@Delphine @TheoChevalier This is a problem is several languages, could we safely drop the "Now" from that string?
