### ISSUE TITLE
[L10n] The "Reset Block Pop-ups.." string from the "Pop-up Permissions" prompt is cut off

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2534]
**[Affected Versions]:**
- Firefox Reality version 8-33550026 (933fcd51)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The app's language is set in "Spanish".

**[Steps to reproduce]:**
1. Click the Settings button.
2. Click the "Privacy and Security" card.
3. Click the the "Advanced" button.
4. Observe the string from the bottom left part of the prompt.

**[Expected results]:**
- The string is correctly displayed.

**[Actual results]:**
- The last word of the string is cut off.

**[Additional Notes]:**
- I was only able to reproduce this issue with the "ES" locale.
- Attached is a screenshot of the issue:
![PermissionsPromptES](https://user-images.githubusercontent.com/40061643/71367594-36abfe00-25ae-11ea-97df-e8a3715fee66.jpg)

**Comment by jvonitter** [comment]
@keianhzo can we allow wrapping to fit in this space?

**Comment by keianhzo** [comment]
I've made all the settings widgets to wrap their content instead of a fixed height as descriptions are usually very variable in size and we are going to have this problem with other languages

**Comment by keianhzo** [comment]
Already fixed by #2609

**Comment by heres-maria** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9-40240151 (7e03c944) build. The last word is no longer cut off.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
