### ISSUE TITLE
[L10n] The "Reset Voice Search.." string from the "Voice Search Language" menu is cut off

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2535]
**[Affected Versions]:**
- Firefox Reality version 8-33550026 (933fcd51)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The app's language is set in "Francaise".

**[Steps to reproduce]:**
1. Click the Settings button.
2. Click the "Language" card.
3. Click the the "Edit" button from the "Voice Search Language" option.
4. Observe the string from the bottom left part of the prompt.

**[Expected results]:**
- The string is correctly displayed.

**[Actual results]:**
- The last words of the string are cut off.

**[Additional Notes]:**
- I was only able to reproduce this issue with the "FR" and "NL" locales.
- Attached is a screenshot of the issue:
![Untitled](https://user-images.githubusercontent.com/40061643/71368838-ad96c600-25b1-11ea-97f4-3bba2e8b91ef.png)

**Comment by jvonitter** [comment]
related to #2534

**Comment by keianhzo** [comment]
Already fixed by https://github.com/MozillaReality/FirefoxReality/pull/2609

**Comment by heres-maria** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9-40240151 (7e03c94) build. The words are no longer cut off.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
