### ISSUE TITLE
[L10n] The name of the "Report an Issue" card from "Settings" has no padding

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2537]
**[Affected Versions]:**
- Firefox Reality version 8-33550026 (933fcd51)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The app's language is set in "Russian".

**[Steps to reproduce]:**
1. Click the Settings button.
2. Observe the name of the "Report an Issue" card.

**[Expected results]:**
- The name is correctly displayed inside the card.

**[Actual results]:**
- The name has no padding.

**[Additional Notes]:**
- I was only able to encounter this issue with the "RU" and "SE" locales.
- Attached is a screenshot of the issue:
![Report Site Issue](https://user-images.githubusercontent.com/40061643/71371147-da9aa700-25b8-11ea-9b67-4c7f63d68934.png)

**Comment by keianhzo** [comment]
@Softvision-RemusDranca This should be fixed already, can you please verify?

**Comment by Softvision-RemusDranca** [comment]
I've retested this issue and it's no longer reproducible with the Firefox Reality version 10-140941948 (b539410) build. The string is correctly displayed inside the card on the locales mentioned in the issue.
Tested on Oculus Quest (Android 7.1.1), HTC Vive Focus (Android 7.1.2) and Pico Neo 2 (Android 8.1.0).

Considering this I will close this issue and mark it as verified fixed.
