### ISSUE TITLE
[L10n] The name of the "Sign Into Account" card from "Settings" has no padding

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2538]
**[Affected Versions]:**
- Firefox Reality version 8-33550026 (933fcd51)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The app's language is set in "Spanish".

**[Steps to reproduce]:**
1. Click the Settings button.
2. Observe the name of the "Sign Into Account" card.

**[Expected results]:**
- The name is correctly displayed inside the card.

**[Actual results]:**
- The name has no padding.

**[Additional Notes]:**
- I was only able to encounter this issue with the "ES" and "FR" locales.
- Attached is a screenshot of the issue:
![Untitled](https://user-images.githubusercontent.com/40061643/71371832-32d2a880-25bb-11ea-95f3-f73ec71223a9.png)

**Comment by jvonitter** [comment]
related to #2539 and #2537

**Comment by heres-maria** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9-40240151 (7e03c944) build. The card now has enough padding.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
