### ISSUE TITLE
Back button not consistent between regular and focus mode

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#254]
**Hardware**: All

**Steps to Reproduce**:
- Enter Focus mode
- Browse to any web site
- Go back using the controller's back button

**Actual Behavior**: You exit focus mode

**Expected Behavior**: You go back in history unless there is no history, in that case you exit focus mode. That's how the regular mode or private mode work so that would be more consistent.

**Recommendation**: Back button always should go back in history unless:
- There is no history, in that case we should exit the app or go back to regular mode.
- We are in a site were you have requested fullscreen mode (ie. Youtube video, WebGL experience, etc), in that case we should exit the fullscreen mode and go back to the mode we were in.

**Comment by thenadj** [comment]
Focus mode was originally intended for movie watching. We are still awaiting usability report results but are already starting the process of designing a 'movie mode' and changing 'focus mode' into 'resize mode' in the default browser window. Adding @avrignaud  in case he wants to comment.

**Comment by avrignaud** [comment]
Yep, Focus mode is likely going away, and all videos will likely be viewed in a new Movie mode. Have a meeting next week to discuss if you'd like to join?

**Comment by keianhzo** [comment]
@avrignaud @thenadj So I hold this until we make a decision about focus mode?

**Comment by thenadj** [comment]
Yes, focus mode will go away and just become resize mode, so no need to fix this. Focus mode button will turn into resize button in default mode.
