### ISSUE TITLE
The "History" option from the Youtube sidebar is cut off on 1x size windows while the privacy banner is displayed

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2543]
**[Affected Versions]:**
- Firefox Reality version 8-33580132 (83024a6).

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The Youtube privacy banner is displayed at the top of the page.

**[Steps to reproduce]:**
1. Navigate to Youtube website
2. Observe the "History" option from the left sidebar.

**[Expected results]:**
- The option is correctly displayed.

**[Actual results]:**
- The option is cut off, only it's icon is visible.

**[Notes]:**
- Needed by #1760.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1cvVWN2xUokl0SLf9V6UEQzPeO1EBb-ls).

**Comment by jvonitter** [comment]
I can't repro this one with a build from 1/6/20. Now, the whole sidebar disappears when shown in smaller sizes. Instead, it's visible when the user selects the hamburger menu in the upper left. Seems like YouTube is being smart and responsive to screen sizes.

**Comment by Softvision-RemusDranca** [comment]
@jvonitter I was still able to reproduce this issue on 1x size windows with the latest Firefox Reality version 8-40062127 (8a91dcb). The "History" button is cut off and the "History" string is not in view and that section is not scrollable.
Maybe the video that I uploaded is confusing because it also captures other window sizes where I tried to show the UI of the button when is not cut off and rendered correctly.
I will reopen this issue and also attach a screenshot with the UI of the button on a 1x size window.

![HistoryYoutube1x](https://user-images.githubusercontent.com/40061643/71905785-80314700-3171-11ea-8e91-87f65c8d2977.jpg)

**Comment by jvonitter** [comment]
Does it only happen when that privacy banner is at the top? If you dismiss that, does it resolve?

**Comment by Softvision-RemusDranca** [comment]
Thanks for pointing out this behavior. Indeed, dismissing the privacy banner solves the problem. 
I will update the issue accordingly since it's only reproducible while the privacy banner is displayed and also lower it's severity.

**Comment by jvonitter** [comment]
I don't think there's much we can do here, since it's an issue with the page. Won't fix.
