### ISSUE TITLE
The play/pause button remains displayed under inactive windows when a page on the same website is open

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2545]
**[Affected Versions]:**
- Firefox Reality version 8-33580833 (777a0ae00)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is open.

**[Steps to reproduce]:**                                        
1. Go to a video page and play the video.
2. Click on a link that leads to a page on the same website.
3. Open a new window from the tray.
4. Observe the initial window.

**[Expected results]:**
-  The play/pause button is not displayed under the window if it does not contain active videos.

**[Actual results]:**
- The play/pause button remains displayed for pages on the same website.

**[Notes]:**
- Navigating to another website or refreshing the page causes the button to disappear.
- While the button is actionable, it doesn’t affect anything.
- This issue is also reproducible after using the “Back” and “Forward” buttons.
- Attached is a recording of the [issue](https://drive.google.com/file/d/1hdzaQgpIuUKFUD4oxCttRUpq8j6_5RxS/view?usp=sharing).

**Comment by keianhzo** [comment]
Closed by https://github.com/MozillaReality/FirefoxReality/pull/2705

**Comment by heres-maria** [comment]
I have verified this issue and it is still reproducible with the latest Firefox Reality version 9-40341450 (ade4895e) build on websites like **Instagram**, **Twitch** and **Twitter**.
The issue is no longer reproducible on YouTube and Vimeo. It is also not reproducible on other websites like The Internet Archive or Facebook.
This behavior can be observed on the Oculus Go (Android 7.1.2), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2) devices, but not on the Oculus Quest (Android 7.1.1).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10-141121728 (0068d595) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the play/pause button does not remain displayed under inactive windows when a page on the same website is open, I’ve tested this on YouTube, Twitch, Twitter, Facebook and Instagram.
