### ISSUE TITLE
The Youtube website takes longer to load after the latest changes

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2546]
**[Affected Versions]:**
- Firefox Reality version 8-33580833 (777a0ae00).

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to Youtube website.
2. Observe the time that the website needs to load.

**[Expected results]:**
- The website is quickly loaded.

**[Actual results]:**
- The website takes a few seconds to load.

**[Notes]:**
- Needed by #1760.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1NNc0uueKc0_OaT8RRp3wo67ydGnm080D).

**Comment by jvonitter** [comment]
It would be good to pull some telemetry to monitor page load times for youtube specifically. I'm not sure we can do a lot about this particular issue, but it would be great if we could have a query to show actual times.

**Comment by keianhzo** [comment]
@Softvision-RemusDranca Is this still happening? Youtube load times look normal to me now.

**Comment by Softvision-RemusDranca** [comment]
I have retested this issue using Firefox Reality version 11-141402320 (eda7d95). The load time looks normal now.
Tested on HTC Vive Focus (Android 7.1.2) and Oculus Quest (Android 7.1.1).

Considering this I will close this issue as verified-fixed.
