### ISSUE TITLE
The "Share" button from Youtube website is not actionable while in theater mode

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2547]
**[Affected Versions]:**
- Firefox Reality version 8-33580833 (777a0ae00).

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to Youtube website.
2. Play a normal video in theater mode.
3. Click the "Share" button from the top right corner.
4. Observe the behavior.

**[Expected results]:**
- The social media buttons are displayed.

**[Actual results]:**
- Nothing happens.

**[Notes]:**
- Needed by #1760.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1yx2toc2b-ybENByhbxIQthlP8qNMiTgq).

**Comment by jvonitter** [comment]
@MortimerGoro any ideas?

**Comment by MortimerGoro** [comment]
@jvonitter Oculus Browser has the same problem, it looks like a User Agent issue. Is it ok if we hide it or do you want to try to find a workaround?

**Comment by jvonitter** [comment]
Hiding it would be fine, if that's not too hard. Users can still share if they leave theater mode, so I think it's ok.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and is no longer reproducible with the latest Firefox Reality version 8-40081245 (34c12f5) build. The "Share" button is no longer displayed while in theater mode.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
