### ISSUE TITLE
The normal videos played from Youtube do not fit the window's view at "1x" or smaller sizes

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2549]
**[Affected Versions]:**
- Firefox Reality version 8-33580833 (777a0ae00).

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The window is set to a 1x size or smaller.

**[Steps to reproduce]:**
1. Navigate to the Youtube website.
2. Open a normal video.
3. Observe if the video fits the window's view.

**[Expected results]:**
- The video fits the window's view.

**[Actual results]:**
- The video doesn't fit the window's view.

**[Notes]:**
- This issue is also reproducible if the page is scrolled down or up.
- Needed by #1760.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1B-OoUKgmxdxFR1gBH6dQo0vCuUoBqEmB).

**Comment by jvonitter** [comment]
I think this might be because of the prompt at the top of the page again, similar to #2543

**Comment by Softvision-RemusDranca** [comment]
Yes, the privacy banner is the cause of this issue as well. Dismissing it will make the videos fit the view.
I will update the issue accordingly and also lower it's severity. You can then decide if it's a wontfix as for related issue #2543. Thanks!

**Comment by MortimerGoro** [comment]
We could hide the privacy banner but I don't think is legal, so won't fix. There isn't much we can do here
