### ISSUE TITLE
The Youtube page can't be scrolled from the "Queue" list area on windows having the "1x" or smaller

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2550]
**[Affected Versions]:**
- Firefox Reality version 8-33580833 (777a0ae00).

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The window is set to a 1x size or smaller.

**[Steps to reproduce]:**
1. Navigate to the Youtube website.
2. Add 2 or more videos to "Queue" list.
3. Go to the "Queue" list area.
4. Scroll the page up or down while in the "Queue" list area.

**[Expected results]:**
- The page is successfully scrolled.

**[Actual results]:**
- The videos from the list are moved and the page can't be scrolled from that area.

**[Notes]:**
- The page can be scrolled from the left and right side of the list.
- This issue is not reproducible on windows larger then "1x". The "Queue" list is displayed as on desktop, on the right side of the video. 
- Needed by #1760.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1WXfOhaCby0C4a70j0lZdEBgGcDMqLME4).

**Comment by jvonitter** [comment]
@MortimerGoro thoughts on this one?

**Comment by MortimerGoro** [comment]
@Softvision-RemusDranca Do you mean scrolling with the joystick or clicking and dragging? The UI allows for the rows to be moved so clicking an dragging scrolling is not possible in that area. I checked the behavior in Oculus Browser and the difference is that they always show the scrollbar, so a user can scroll dragging it. I'd try to make it visible.

The inner scroll behavior (using the joystick) is a bit different between FxR and Oculus Browser. I created a testpage: 
[index.html.zip](https://github.com/MozillaReality/FirefoxReality/files/4041264/index.html.zip)

**Comment by Softvision-RemusDranca** [comment]
@MortimerGoro I was referring to clicking and dragging. I think that having a scrollbar for this list could help users to navigate easily. The list covers most of the view while in 1x size and to scroll past it the small area outside the list has to be focused.

**Comment by MortimerGoro** [comment]
I've been trying "inner scrolling" in FxR and Oculus Browser using the attached index.html demo and the behaviour in OB seems more consistent. In OB I can hover on the desired container and moving the joystick scrolls the expected container. In FxR I had to select or place the cursor on the inner container to scroll it
For example in FxR you can select the green container, then scroll down using click& drag until the green container is not visible and using the joystick after that still keeps scrolling the green container even if not visible (edited).

We are waiting for some support from APZ team. If works in Firefox desktop so there might be a pref we can set to get the desired behavior.
