### ISSUE TITLE
Allow use without Oculus Guardian enabled

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#2551]
**Is your feature request related to a problem? Please describe.**
Sometimes people like to watch videos in a dark room, where the guardian cannot be enabled due to lack of light and the Oculus Quest will be in Stationary/Seated mode. Firefox Reality currently requires the guardian enabled.

**Describe the solution you'd like**
Allow launching in a go-like 3dof mode.

**Additional context**
We had several requests for this in the Oculus issue tracker over the holidays.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this enhancement with the latest Firefox Reality version 8-40100049 (1500ba50) installed on the Oculus Quest headsets.
Now, the app can be used with head tracking/guardian disabled.

**Comment by larsbergstrom** [comment]
Awesome news! Thanks for the work @bluemarvin and the verification @Softvision-GeluHaiduc!
