### ISSUE TITLE
The "Miniplayer" list from the Youtube website is not scrollable 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2552]
**[Notes]:**
- This issue is also reproducible on windows having the 1x size or smaller if the "Miniplayer" is expanded on full screen.

**[Affected Versions]:**
- Firefox Reality version 8-33580833 (777a0ae00).

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to the Youtube website.
2. Add at least 5 videos to "Queue" list.
3. Click the "Down" arrow are from the "Miniplayer" list.
4. Observe the list.

**[Expected results]:**
- A vertical scrollbar is displayed on the right side of the list.

**[Actual results]:**
- No scrollbar is displayed and the list is not scrollable.

**[Additional Notes]:**
- Needed by #1760.
- This issue is also tracked in the Webcompat repo: https://github.com/webcompat/web-bugs/issues/46266
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1k1q5X_HTsUALgSR-3tAbKQcC0dlX12XG)

**Comment by jvonitter** [comment]
@MortimerGoro thoughts on this one? possibly related to #2550 ?

**Comment by MortimerGoro** [comment]
I don't think they are related. As it also happens in Firefox desktop desktop I'd wait for the webcompat issue being fixed: https://github.com/webcompat/web-bugs/issues/46266

**Comment by daron-walters** [comment]
I have been researching this ticket for a few days and I think there are multiple problems

1. isues with flexbox and firefox in general (placing the overflow-y)  on the correct flexbox element may show a scrollbar that doesnt function

2.  I think the bigger problem is that the whole miniplayer element is the height of the page (a page that dynamically grows) so researching making the miniplayer height fixed/absolute.

**Comment by daron-walters** [comment]
[Here](https://drive.google.com/open?id=1VCdBQR5BvjYDETv98YzPeYJWvx6yKsHH) is a link to my fix on local.  I have some follow up usability questions.

1. The scrollbar only shows when there are more items than space AND where user clicks on the playlist/playlist items.  It is not obvious to user that items are scrollable
2 The size of the scrollbar. It seems pretty thin Do we need to see if this can be fixed via css?

**Comment by bluemarvin** [comment]
> [Here](https://drive.google.com/open?id=1VCdBQR5BvjYDETv98YzPeYJWvx6yKsHH) is a link to my fix on local. I have some a follow up question
> 
> 1 The size of the scrollbar. It seems pretty thin Do we need to see if this can be fixed via css?

The scroll bars in GeckoView are visual and not interactive currently (see https://github.com/MozillaReality/FirefoxReality/issues/317). This is an artifact of GeckoView being intended for mobile phones.

**Comment by daron-walters** [comment]
thanks for the comment @bluemarvin read through tie issue you included. It actually answered some other ui questions I had.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using Firefox Reality 11-141551002 (8f4de9a). Now, the "Miniplayer" list from the Youtube website is scrollable.

Tested on HTC Vive Focus (Android 7.1.2), Oculus Quest (Android 7.1.1), and Pico Neo 2 (Android - 8.1.0) devices.
