### ISSUE TITLE
The "Miniplayer" from the Youtube website is to large for windows with a "0.5x" size 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2554]
**[Affected Versions]:**
- Firefox Reality version 8-33580833 (777a0ae00).

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The window is set to a "0.5x" size.

**[Steps to reproduce]:**
1. Navigate to the Youtube website.
2. Add a video to "Queue".
3. Observe the "Miniplayer" displayed.

**[Expected results]:**
- The "Miniplayer" fits the window's view and all other elements of the website are visible.

**[Actual results]:**
- The video is to large for the window's "0.5x" size and covers other elements of the website.

**[Additional Notes]:**
- As a side effect of this issue the website's menu bar is overlapped and other videos can't be added to "Queue" or added to be watched later.
- Needed by #1760.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1PkEY1dMRx4VykQZWDMOaVzg0d_XGllu-).

**Comment by MortimerGoro** [comment]
This is a Youtube code issue, their code is not well prepared for such small windows. I don't think it will be a common scenario to use both Youtube and the miniplayer at the same time in 0.5x
