### ISSUE TITLE
The video's view is cut off or not displayed if the Youtube's "Miniplayer" list is expanded in windows having the "1x" size or smaller

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2555]
**[Affected Versions]:**
- Firefox Reality version 8-33580833 (777a0ae00).

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The window is set to a 1x size or smaller.

**[Steps to reproduce]:**
1. Navigate to the Youtube website.
2. Add a video to "Queue".
3. Click the "Down" arrow are from the "Miniplayer" list.
4. Observe the video playing in the "Miniplayer".

**[Expected results]:**
- The video's view is correctly displayed.

**[Actual results]:**
- The video's view is cut off.

**[Additional Notes]:**
- On windows having the 0.5x size, the video is no longer visible after expanding the "Miniplayer" list.
- Needed by #1760.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1uE8YMLgzJwcjoAJqzjGCk-NdG8fkDeNd).

**Comment by MortimerGoro** [comment]
We can't do anything about this, it's a Youtube code issue. Same behavior in Oculus Browser.
