### ISSUE TITLE
The YouTube layout changes after closing and reopening/restarting the app

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2557]
**[Affected Versions]:**

- Firefox Reality version 8-33611921 (67403bf2)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is open.

**[Steps to reproduce]:**                                       
1. Go to YouTube.
2. Open the “Language” card from Settings.
3. Change the “Display Language for App” and choose the “Restart Now” option.
4. Observe the YouTube layout.

**[Expected results]:**
-  The layout remains the same after restarting.

**[Actual results]:**
- The layout completely changes after restarting.

**[Notes]:**
- Trying to use the website in the new layout will return an “Invalid response received” error.
- The issue is also reproducible when closing the app and subsequently using the “force-stop” adb command before reopening it.
- This issue is reproducible when multiple windows are open as well as when using different window sizes.
- Needed by #1760.
- Attached are a recording of the [issue](https://drive.google.com/file/d/10OOJsPFhbkPMod-3nPxcJ-rIL8P8KURN/view?usp=sharing) and screenshots:
![Mon12-30-2019_10-42-28 32](https://user-images.githubusercontent.com/53752296/71576342-02c66080-2af9-11ea-871b-ed463fe01ab1.png)
![Mon12-30-2019_10-33-15 42](https://user-images.githubusercontent.com/53752296/71576343-0528ba80-2af9-11ea-83b2-639c251986f9.png)
![Mon12-30-2019_10-31-48 97](https://user-images.githubusercontent.com/53752296/71576348-0823ab00-2af9-11ea-8773-0a4f96eaa2cd.png)

**Comment by MortimerGoro** [comment]
Fixed in #2596

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 8-40101959 (3c2a71e2). Now, the same layout is displayed after the app is reopened.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
