### ISSUE TITLE
The play/pause button is not always functional for live videos

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2559]
**[Affected Versions]:**

- Firefox Reality version 8-33611921 (67403bf2)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is open.

**[Steps to reproduce]:**                                        
1. Go to [Twitch](https://www.twitch.tv/).
2. Play a live video.
3. Open a new window from the tray.
4. From under the initial window, click the play/pause button a few times.

**[Expected results]:**
-  The play/pause button is functional each time.

**[Actual results]:**
- The play/pause button is not always functional.

**[Notes]:**
- This issue is also reproducible on live videos from YouTube, though intermittently.
- This issue affects both paused and playing states on YouTube.
- This issue is not reproducible on live videos from Periscope or normal videos from Twitch or YouTube.
- Attached is a recording of the [issue](https://drive.google.com/file/d/1WohDvvNQH73lkKWDI_1RnAIrdTNH6zT6/view?usp=sharing).

**Comment by jvonitter** [comment]
If it's not possible for the button to work (because the video isnt able to be paused for whatever reason), I would be ok hiding the button.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10-141121728 (0068d595) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the play/pause button was always functional for live videos tested on YouTube and Twitch.
