### ISSUE TITLE
English Keyboard input improvement suggestions for FxR

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#256]
Hardware: All
Steps to Reproduce: N/A
Actual Behavior: N/A
Expected Behavior:
1. Expected to have "/" key available on main panel for easy URL entry
2. Expected to have ".com" button available to speed entry
3. Expected previously entered URL text to remain (so it is possible to add to it), and not have it erased
Recommendation:
1. / Key on main keyboard
2. .com button on main keyboard
3. URL text remains when selected unless backspace is selected (this presumes text is already selected)

**Comment by thenadj** [comment]
Adding forward slash to keyboard improvements in Trello. 
Keeping URL text is a good idea. 
We are also adding a URL history UI to easily pick previously typed URL.

**Comment by MortimerGoro** [comment]
Another user requested this: https://github.com/MozillaReality/FirefoxReality/issues/84

**Comment by avrignaud** [comment]
All sounds good - and I also like the idea of a shift key on both sides of keyboard.  Apologies for missing the .com button!

**Comment by cvan** [comment]
btw, filed issue #288 for Caps Lock/Shift issues

**Comment by thenadj** [comment]
Just FYI - This is currently #6 on our design priority list.

**Comment by MortimerGoro** [comment]
Have we considered using a split keyboard like Oculus/Chrome does (e.g numbers on a side of the keyboard, instead of a keyboard layout switch). 

Maybe you mentioned it a design review meeting but don't remember now.

**Comment by thenadj** [comment]
@MortimerGoro Yes we have but we will not make changes for v1. It's on or list for v1.1 to explore split keyboard.

**Comment by thenadj** [comment]
Updated keyboard design is complete. 
[UIS-6 Keyboard_011.pdf](https://github.com/MozillaReality/FirefoxReality/files/2308545/UIS-6.Keyboard_011.pdf)

**Comment by MortimerGoro** [comment]
> URL text remains when selected unless backspace is selected (this presumes text is already selected

Can you give more details about this issue? I think that clearing the selected text after typing is a common behavior on browsers.

**Comment by avrignaud** [comment]
@MortimerGoro Issue is that automatically clearing the text makes it impossible to edit a URL. So if I make a typo and the URL fails, user can't just insert a character and try again - it literally clears all of that text and user is forced to enter the entire URL again which is painful in VR. So, the recommendation based on user feedback is to highlight the entire string - then user has two choices. One is to hit Delete which will clear all of it. Second is user can point and insert cursor into text at appropriate location.

**Comment by MortimerGoro** [comment]
@avrignaud I still don't get the issue. Users can already point and place the cursor into text to edit a URL. This is how it currently works. When the user clicks the URL the entire string is highlighted. Then they have two options:
- With another click users can point and insert cursor into text at appropriate location.

**Comment by MortimerGoro** [comment]
the problem may be that sometimes when users click on the URL the text is still selected because the touch is nor processed.  This may be caused because of https://github.com/MozillaReality/FirefoxReality/issues/377

**Comment by keianhzo** [comment]
@thenadj Couple of questions:
- The microphone button has disappeared from all the keyboards, is that right?
- The symbols keyboard has the two shift buttons, do we want shifts in the symbols keyboard?
- The "!" symbol is gone from the qwerty keyboard but is also not available in the symbols one, is that an error?

**Comment by keianhzo** [comment]
@thenadj Also there is no button for switching to the secondary symbols keyboard, are the shifts to do that or is the secondary symbols keyboard removed from the version?

**Comment by thenadj** [comment]
That's a mistake! I'll take a look and will fix it today.
