### ISSUE TITLE
[Keyboard] The keyboard is not switched back to lowercases when clicking the "Å" key

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2562]
**[Affected Versions]:**
- Firefox Reality version 8-33611921 (67403bf2)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is open.
- The keyboard's language is set to Danish.

**[Steps to reproduce]:**                                        
1. Focus the Awesomebar.
2. Click once on the uppercase arrow from the keyboard.
3. Click the "Å" key and observe the keyboard.

**[Expected results]:**
- The keyboard switches back to lowercase.

**[Actual results]:**
- The keyboard remains on uppercase.

**[Notes]:**
- This issue is reproducible on all languages where the "å" character is available (Polish, Norwegian, Swedish).
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=13n5KlV4pg2dEFOSxiH_5bXzGAuNA_X7L).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9-40430119 (abd4f531) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the keyboard is switched back to lowercases after clicking the "Å" key.
