### ISSUE TITLE
[Keyboard][Danish] The special character menu for "y" wrongly opens on the left

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2563]
**[Affected Versions]:**
- Firefox Reality version 8-33611921 (67403bf2)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is open.
- The keyboard's language is set to Danish.

**[Steps to reproduce]:**                                        
1. Focus the Awesomebar.
2. Long click on the "y" character.
3. Observe the position of the special character menu.

**[Expected results]:**
- The menu is displayed to the right side.

**[Actual results]:**
- The menu is displayed to the left side.

**[Notes]:**
- Danish Keyboard trello card: https://trello.com/c/K0cfGN5a/438-de-68-danish-keyboard
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1kkCx2d9Myfj8vcoNQOarupJmlUwWveOL).

**Comment by jvonitter** [comment]
this is ok
