### ISSUE TITLE
The “New Tab Added!” notification is displayed above where the menu tray would be when in theater mode

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2564]
**[Affected Versions]:**
- Firefox Reality version 8-33641447 (16c9df55)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is open.

**[Steps to reproduce]:**                                        
1. Go to a video (e.g. https://youtu.be/_T8cn2J13-4) 
2. Enter theater mode by clicking the Full Screen button.
3. Long click on a link while in theater mode.
4. Click “Open in a new tab”.
5. Observe the area below the window.

**[Expected results]:**
- When displaying notifications, the UI takes into account that the menu tray is not displayed in theater mode.

**[Actual results]:**
- The “New Tab Added!” notification is displayed above where the menu tray would be.

**[Notes]:**
- This issue is reproducible on websites other than YouTube as well (e.g. Twitch).
- Related to #2375.
- Attached is a recording of the [issue](https://drive.google.com/file/d/1jpQVBqm4eexjTL8-TlL_kDzW4Im9XvJ-/view?usp=sharing).

**Comment by jvonitter** [comment]
@thenadj what would you want to happen here?

**Comment by jvonitter** [comment]
Talked to @thenadj - let's move the notification to be centered below the transport controls when the tray is not visible. Also remove the pointy part that sticks out of the bubble (so it doesn't point anywhere).

**Comment by heres-maria** [comment]
I have verified this issue and it is no longer reproducible with the latest Firefox Reality version 9-40371914 (083b65c0) build. The notification is now displayed under the window, centered.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
