### ISSUE TITLE
[Keyboard] The keys from the left side are wrongly actionable from outside their borders

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2565]
**[Affected Versions]:**
- Firefox Reality version 8-33611921 (67403bf2)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is open.

**[Steps to reproduce]:**                                        
1. Focus the Awesomebar.
2. Click on the left side of the keyboard, outside the keys borders.
3. Observe the behavior.

**[Expected results]:**
- Nothing happens.

**[Actual results]:**
- The keys from the left side are actionable.

**[Notes]:**
- This issue is reproducible on all keyboard languages.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1K3S22Bu651iRe_S03poW7MTxQYAkC8tl).

**Comment by jvonitter** [comment]
This also happens on the left side of the number pad.

**Comment by Softvision-RemusDranca** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9-40240151 (7e03c94) build. 
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
