### ISSUE TITLE
[Keyboard][Swedish] The special character menu for "u" wrongly opens to the left

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2567]
**[Affected Versions]:**
- Firefox Reality version 8-33611921 (67403bf2)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is open.
- The keyboard's language is set to Swedish.

**[Steps to reproduce]:**                                        
1. Focus the Awesomebar.
2. Long click on the "u" key.
3. Observe the position of the special character menu.

**[Expected results]:**
- The menu is displayed to the right side.

**[Actual results]:**
- The menu is displayed to the left side.

**[Notes]:**
- Swedish Keyboard Trello card: https://trello.com/c/ANHF3mV1/434-de-62-swedish-keyboard
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1nRouzrSWmklNHtd-6M5FAi4W9ee6HYMn).

**Comment by jvonitter** [comment]
This is ok
