### ISSUE TITLE
[Keyboard] The "ï" character overlaps with other characters when inserted in the Awesomebar or other input fields

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2569]
**[Affected Versions]:**
- Firefox Reality version 8-33611921 (67403bf2)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is open.

**[Steps to reproduce]:**                                        
1. Focus the Awesomebar and and click the "i" character or another uppercase character.
2. Long click on the "i" character.
3. Select the "ï" character from the special character menu.
4. Observe the Awesomebar.

**[Expected results]:**
- The "ï" character is correctly displayed in the Awesomebar.

**[Actual results]:**
- The "ï" character overlaps with the other inserted characters.

**[Notes]:**
- This issue is also reproducible with the uppercase "ï" character.
- This issue is reproducible on all languages where the "ï" character is available.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1iEcWoqfBx0GMjzwaxfVA4opdh5_pkSET).

**Comment by jvonitter** [comment]
i think we can live with this
