### ISSUE TITLE
The app crashes if the “Send Tab to Device” option is clicked while the login process started from the same option is underway

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2571]
**[Affected Versions]:**
- Firefox Reality version 8-33641447 (16c9df55)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is open.
- Have a valid FxA account.
- You are not logged into an FxA account.

**[Steps to reproduce]:**                                        
1. Click the "Send Tab to Device" option from the hamburger button menu.
2. Click the “Sign In” button.
3. Sign in using valid credentials.
4. While the process of signing in is underway, click the “Send Tab to Device” button again.
5. Click any of the two prompts that are displayed and observe the behavior.

**[Expected results]:**
Step 4: The “Sign in to send tabs” and the “Send tab to Device” prompts do not overlap.
Step 5: The app does not crash.

**[Actual results]:**
Step 4: The “Sign in to send tabs” and the “Send tab to Device” prompts are alternatively displayed. 
Step 5: After interacting with the prompts, the app crashes.

**[Notes]:**
- The issue is also reproducible from Tabs View.
- While the app does not crash if the initial sign in was executed using “Sign into Account” from Settings or the “Sign In” button from the First Explainer Page, the prompts are still both displayed and the sign in is not finalized properly.
- Attached is a recording of the [issue](https://drive.google.com/file/d/1VIv7VMxMF_eSpemlwQbGVe5Cd4usK7QK/view?usp=sharing).

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and is no longer reproducible with the latest Firefox Reality version 8-40081245 (34c12f5) build. Now, only the "Send Tab to Device" prompt remains displayed and the app doesn't crash.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
