### ISSUE TITLE
Buttons and toggles on YouTube retain their focused states after being clicked

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2576]
**[Affected Versions]:**
- Firefox Reality version 8-40030225 (e6f4ddab)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is open.

**[Steps to reproduce]:**                                        
1. Go to [YouTube](https://www.youtube.com/).
2. Open a video.
3. Click on the “Autoplay” toggle button.

**[Expected results]:**
- The focused state does not remain active after the toggle animation stops.

**[Actual results]:**
- The focused state remains active until clicking on something else.  

**[Notes]:**
- The issue is reproducible for all buttons (e.g. hamburger button or three dot buttons).
- Needed by #1760.
- Attached is a recording of the [issue](https://drive.google.com/file/d/1Se-LqkrRy8m-e9V28kb-1hQvlWEXNI0e/view?usp=sharing).

**Comment by MortimerGoro** [comment]
Closing this becaise it's a issue in Youtube code. Oculus Browser has the same problem.
