### ISSUE TITLE
The titles of the suggested videos displayed after a YouTube video ends are cut off

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2577]
**[Affected Versions]:**
- Firefox Reality version 8-40030225 (e6f4ddab)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is open.

**[Steps to reproduce]:**                                        
1. Go to [YouTube](https://www.youtube.com/).
2. Open a video.
3. Wait for the video to end or skip to the end.
4. Observe the titles of the suggested videos. 

**[Expected results]:**
- The titles are displayed correctly.

**[Actual results]:**
- The titles of the videos are horizontally cut off.

**[Notes]:**
- Needed by #1760.
- Attached is a recording of the [issue](https://drive.google.com/file/d/1o-adPNyQU6_pCnKfEPe3ZRYdlx_rig_r/view?usp=sharing).

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 8-40101959 (3c2a71e2). Now, the titles of the suggested videos are no longer cut off.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
