### ISSUE TITLE
Menu buttons stop responding during VR.

### ISSUE THREAD

**Issue by ghost** [MozillaReality/FirefoxReality#2585]
## Configuration

Firefox Reality version: 7(Release Version)
Firefox Reality build ID: unknown

Hardware: Oculus Quest

## Steps to Reproduce

1. Open the page with the text  input form and the VR display button.
2. Press the text input form to display the cursor.
3. With the cursor displayed, press the VR display button.
4. After switching to VR, press the menu button.

## Current Behavior

Menu button does not respond.
I have to press the Oculus Button to return to the Quest home screen.

## Expected Behavior

Press the menu button to return to the web page.

## Context

When coding A-Frame with Glitch on Firefox Reality,
It happened when coding and previewing in one window.
However, I always do the coding and previewing in separate windows, so no inconvenience has occurred.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by jvonitter** [comment]
Thanks for reporting this!
