### ISSUE TITLE
Videos are not automatically played when the “Autoplay Media” setting is turned on

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2600]
**[Affected Versions]:**
- Firefox Reality version 8 alpha channel (8f44962d)
- Firefox Reality version 8-40062127 (8a91dcb6)
- Firefox Reality version 7.1-40080314 (dd5419a2)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- The “Autoplay Media” setting is turned on.

**[Steps to reproduce]:**
1. Navigate to any video on YouTube.
2. Observe the behaviour.

**[Expected results]:**
- The video automatically starts playing.

**[Actual results]:**
- The video doesn’t automatically start playing.

**[Notes]:**
- The issue is also reproducible on Vimeo.
- The issue is not reproducible with Twitch.
- The issue is not reproducible with the production version 7.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1swINy6LSoSpxJ2p8obxg6SASiNpcr_iJ).

**Comment by MortimerGoro** [comment]
Blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1607883

**Comment by heres-maria** [comment]
I have verified this issue and it is no longer reproducible with the latest Firefox Reality version 8 RC1 build (7a444d0). 
The videos on YouTube and Vimeo automatically start playing with "Autoplay Media” enabled.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
