### ISSUE TITLE
In-VR Devtools panel

### ISSUE THREAD

**Issue by RangerMauve** [MozillaReality/FirefoxReality#2602]
**Is your feature request related to a problem? Please describe.**

I've been trying to do more development from within VR on Oculus Quest and Google Daydream, and even though I can get pretty far with in-page tools / SSHing into VMs that hold code, it's been really hard to debug JS errors without connecting a laptop and having to jump out of VR.

**Describe the solution you'd like**

It'd be cool if there was an "open dev tools" button on tabs that'd launch a local Firefox Devtools page in a new window. This'd be a boon for developers and could potentially onboard a new generation of web devs that are specifically interested in WebXR. Dev tools were super important to my journey in learning to code, and I'm sure a lot of new folks could start on that journey with this functionality too.

**Describe alternatives you've considered**

- Running a local copy of the dev tools HTML/JS and proxying to the websocket connection started by Firefox Reality
- Weird stuff with ADB on a raspberry PI attached to the headset

**Additional context**

**Comment by jvonitter** [comment]
Thanks for this request, @RangerMauve. I'm putting it in the backlog for now while we investigate what it would take to do this and when it might be possible.
