### ISSUE TITLE
After changing skybox to void, skybox reverts on exiting theatre mode.

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#2605]
## Configuration

Firefox Reality version: 8
Firefox Reality build ID: from master 34c12f5bd4001e8985ac9b76a16d100ff5267d4a

Hardware: All supported

## Steps to Reproduce
1. Select a skybox other than void.
2. Switch skybox to void.
3. Enter theatre mode and then choose an immersive projection
4. Exit immersive theatre mode.

## Current Behavior
Previous non-void skybox is visible.

## Expected Behavior
"void" remains selected, i.e. no skybox is visible.

## Possible Solution
Currently, in BrowserWorld, if changing to "void" and a skybox has previously been loaded, the previous skybox is just hidden, rather than removed from the scene graph, making other uses of show/hide skybox produce undesired behaviour. Better to remove and delete the skybox. Fixed by #2606.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 8-40101959 (3c2a71e2) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the skybox does not revert on exiting theatre mode after a void environment is selected.
