### ISSUE TITLE
I'd like to use the menu and grip controller buttons

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#2608]
**Is your feature request related to a problem? Please describe.**
At the moment we are only using the menu and  grip (where available) inside immersive mode. I think we could find more uses for them inside the app.

**Describe the solution you'd like**
The first use I can think of is opening the settings panel for the menu button and opening acontext menu for the grip button when the window is focused (a desktop style right-click menu)

**Comment by jvonitter** [comment]
@keianhzo can you make an apk with your suggested changes for us to play with? i think this could be a good idea, but want to see if we get a lot of mistaken activation of the grip button.

**Comment by jvonitter** [comment]
cc @thenadj
