### ISSUE TITLE
A-blast doesn't work

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#261]
Hardware: All 
Steps to Reproduce: Goto https://aframe.io/a-blast/
Actual Behavior: Blank page
Expected Behavior: WebGL scene with a EnterVR button

We need to research why the page is blank first

**Comment by MortimerGoro** [comment]
I thought it was something related to custom elements https://github.com/MozillaReality/FirefoxReality/pull/450 but no. Anyway that PR could help to improve perf.

I also checked to load A-blast on Oculus broser and Samsung Internet. Also blank page on both.

Changing priority to P2 since this doesn't seem like a Firefox Reality issue as we though.

**Comment by MortimerGoro** [comment]
Assigning this to @fernandojsg because it's a content issue

**Comment by larsbergstrom** [comment]
Confirmed this is still an issue, but moving to backlog.

**Comment by philip-lamb** [comment]
Closing as appears to be a page issue. Doesn't work in FxR 1.3 or Oculus Browser.
