### ISSUE TITLE
The item from the Youtube "Queue" list remains selected while the Context menu is displayed

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2611]
**[Affected Versions]:**
- Firefox Reality version 8-33641447 (16c9df5)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to the Youtube website.
2. Add multiple videos to "Queue" list.
3. Go to the "Queue" list area.
4. Long click on an item.
5. Move the controller while the Context menu is displayed.
6. Observe the long clicked item.

**[Expected results]:**
- The item is no longer selected.

**[Actual results]:**
- The item remains selected and draggable.

**[Notes]:**
- The item from the list remains selected even after clicking on an option from the Context menu.
- Needed by #1760.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1s712bOch1NM5XwHEtrwxc9M-DGxnzxcK).

**Comment by jvonitter** [comment]
anything we can do about this, @MortimerGoro ?

**Comment by MortimerGoro** [comment]
we should be able to fix this. With the #2612 fix the consecuences of this are less important so it can wait for v9

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using Firefox Reality version 11-141402320 (eda7d95). Now, the item from the Youtube "Queue" list no longer remains selected if the Context menu is displayed.

Tested on HTC Vive Focus (Android 7.1.2) and Oculus Quest (Android 7.1.1).
