### ISSUE TITLE
The items from the Youtube "Queue" list can wrongly be drag outside the list's border affecting the UI

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2612]
**[Affected Versions]:**
- Firefox Reality version 8-33641447 (16c9df5)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to the Youtube website.
2. Add multiple videos to "Queue" list.
3. Go to the "Queue" list area.
4. Click>hold and drag an item outside the list's border.
5. Observe the behavior.

**[Expected results]:**
- The item can't be dragged outside the list's border.

**[Actual results]:**
- The item is dragged outside the list border affecting the UI of the page.

**[Notes]:**
- The UI of the page is restored after releasing the item from the list.
- Needed by #1760.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1eA52vv-1S_avSgq-8xD5wgE31XRWJQs9).

**Comment by jvonitter** [comment]
related to #2611 
@MortimerGoro is this the page's problem or something we're doing?

**Comment by MortimerGoro** [comment]
@jvonitter it's something we can fix

**Comment by MortimerGoro** [comment]
@jvonitter I'm changing this to v8 because while doing the research I found the fix

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 8-40101959 (3c2a71e2). The UI is no longer affected after dragging items outside the borders list.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
