### ISSUE TITLE
Make it possible to load web pages into Firefox Reality

### ISSUE THREAD

**Issue by blairmacintyre** [MozillaReality/FirefoxReality#2621]
**Is your feature request related to a problem? Please describe.**
It is sometimes desirable to run VR demos/apps without reliable network connectivity:
- conferences when demoing or giving talks
- outside, away from wifi
- enterprise/corparate customers may not want to rely on the network
- when visiting locations (schools, etc) with firewalls that might prevent content

**Describe the solution you'd like**
I would like to be able to load a web directory into the application, and then access it via a well-defined URL.

In the WebXR Viewer, we made a compile time option to embed a webserver in the app that responded to `localhost:8080`, and then load the contents of a directory in the source tree containing the web content.  I used this when giving talks and demos on my phone, since I was often showing the demos in places with little or no network access.  It was incredibly useful, especially since I had lots of videos and models in my apps, I kept > 1GB of content inside the app.

In one version of Argon, we made it possible for end users to load zip files from the web, and the contents of those would be accessible via "url of zip file" + "path inside the zip".  We discussed being able to load up zip's explicitly, and then access them via "localhost:" (e.g., "load foo.zip as demo1" -> "https://localhost:8080/demo1/...."

In FxR, it would be nice to have a UI that lets you do the latter, in addition to history and bookmarks:   
- load zip files and give them a name
- access them via an embedded web server, as https://localhost:someport/name/....

The nice thing about this is that as long as the web directory is self contained and only uses relative URLs, the app can run with no access to the internet.  But, if there are links off to external resources, they would be downloaded as normal.  So, apps could be written that store much of their content locally, but fetch some data over the web.  Thus, this feature is useful even if network access is available, because the apps will just load faster.

**Describe alternatives you've considered**
See above.  There is no good alternative to this, aside from running a server on a second machine with a network connection, that the headset connects to.  This is awkward, and requires a user to have and set up such a system.

**Comment by jvonitter** [comment]
thanks @blairmacintyre! i'm putting this in the backlog for now as we investigate offline mode generally.

**Comment by blairmacintyre** [comment]
Great!  @larsbergstrom and I were chatting today and he suggested I submit this.  It was so amazingly useful to have reliable access to a set of content, without relying on the web cache.

**Comment by bluemarvin** [comment]
It is possible to put HTML files on the devices `/sdcard` and open them with `file:///sdcard/some-file-name.html`. Note that `/sdcard` is actually the devices internal storage. I tested this by tarring some html files and pushing them to the device. For exampe:
```
% tar cvf file.tar files
% adb push file.tar /sdcard
% adb shell
monterey:/ $ cd /sdcard
monterey:/ $ tar xvf file.tar
```
