### ISSUE TITLE
The tray is no longer displayed and the UI from the Awesomebar is broken after closing the active window

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2623]
**[Affected Versions]:**
- Firefox Reality version 8-40101959 (3c2a71e2)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Click the New Window button.
2. Close the active window and observe the behavior.

**[Expected results]:**
- The inactive window becomes active and the tray moves in front of this window.

**[Actual results]:**
- The inactive window doesn't became active, the tray is no longer displayed and the URL from the closed window overlaps with the URL from the second window.

**[Notes]:**
- The issue is no longer visible after focusing the remaining window.
- The Pause/Play button also remains displayed after closing the active window, overlapping with the Awesomebar.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1vqegsBvwNZMNH5jhT5sSzAo8F17vgt57).

**Comment by bluemarvin** [comment]
Giving the window seems to fix the UI. But this is pretty bad.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 8 RC1 (7a444d0). 
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
