### ISSUE TITLE
Investigate poor immersive mode performance on Pico devices

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#2629]

**Comment by bluemarvin** [comment]
This may only be an issue with Hubs on the Pico devices. Other WebVR pages seems to work as expected.

**Comment by bluemarvin** [comment]
We have found the following issues:

1) Rendering at full resolution degrades performance. A temporary work around was implemented in #2939 
2) The PicoVR API does not allow for heading prediction so we can not render WebGL frames in parallel with the VR Compositor
