### ISSUE TITLE
Permission dialog interrupts browsing experience

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#264]
If you go to any random website that request the geolocation permission (probably just for internal analytics or a not important reason), the permission prompt is so big that it interrupts the browsing experience. It feels almost like an insterstitial ad.

On desktop browsing such permissions are not very annoying because they are shown in a small notification space.

**Comment by MortimerGoro** [comment]
This happens everytime you visit the site.

We can cache the user decision in future devs, but we need a settings UI to show all the granted permissions so the user can still change them anytime

**Comment by cvan** [comment]
I am not sure if it is implied in the comments above, but it would be ideal if we leverage the Permissions API.

**Comment by avrignaud** [comment]
@thenadj will need to update the permission prompt UI to allow user option to select "Remember my choice". However, this is P2 - not for 1.0.

**Comment by avrignaud** [comment]
@thenadj Do we have a design for updating the permissions dialog? Note this is not critical for 1.1, but something we'll want to get done for 1.2.

**Comment by thenadj** [comment]
@avrignaud Yes! 

Here is the permissions dialogs for Speech/Voice Input:
[UIS-60 Speech&Voice Input Permissions_002.pdf](https://github.com/MozillaReality/FirefoxReality/files/2539834/UIS-60.Speech.Voice.Input.Permissions_002.pdf)

And here is a doc with all dialogs. The bottom row has the redesign with more consistent spacing and new color scheme incl blue button for suggested action that @keianhzo is updating. 
[DE-31 Dialogs_002.pdf](https://github.com/MozillaReality/FirefoxReality/files/2539840/DE-31.Dialogs_002.pdf)

**Comment by cvan** [comment]
great!

a few questions:

1. when a prompt (any prompt) is opened, the opacity of the browser + environment should be dimmed, correct?
2. what happens if (or can) a user click outside of the FxR permission prompt? should that decision be reported back as "canceled" or "denied"?
3. should there be an `Always allow`/`Always deny`/`Remember this choice` option?
4. what happens if I'm in Immersive Mode and a permission is requested? will the user be popped out of WebVR and into the standard 2D browser context, or will the user remain in VR?

**Comment by thenadj** [comment]
@cvan 
> 1. when a prompt (any prompt) is opened, the opacity of the browser + environment should be dimmed, correct?
Ideally, yes but the browser window cannot be darkened at this point. Not sure when that code will be written. 

> 2. what happens if (or can) a user click outside of the FxR permission prompt? should that decision be reported back as "canceled" or "denied"?
Clicking outside will do nothing. The user has to close the prompt first before interacting with the app again. Modal dialog behavior. 

> 3. should there be an `Always allow`/`Always deny`/`Remember this choice` option?
For which prompts? Might make sense for some!

> 4. what happens if I'm in Immersive Mode and a permission is requested? will the user be popped out of WebVR and into the standard 2D browser context, or will the user remain in VR?
That's a good question and might have security implications. Ideally the user would be able to remain in immersive mode and be presented with a prompt. See UF-4 #500 (from back in December)

[UF-4 Firefox 2D - Immersive - Permissions 001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2540429/UF-4.Firefox.2D.-.Immersive.-.Permissions.001.pdf)

**Comment by cvan** [comment]
> > 2. what happens if (or can) a user click outside of the FxR permission prompt? should that decision be reported back as "canceled" or "denied"?
> 
> Clicking outside will do nothing. The user has to close the prompt first before interacting with the app again. Modal dialog behavior. 

does that mean that the cursor from the controller disappears when the user tries to point outside? clicking outside of modals, doorhangers, and windows is a common occurrence.

can we add a close/ignore button?

is there a design spec for removing/fixing these Permissions? often times in desktop and mobile browsers, users accidentally deny Permissions and then a site doesn't work, and they have no obvious way to remove the stored denial and grant the Permission instead.

> > 3. should there be an `Always allow`/`Always deny`/`Remember this choice` option?
> 
> For which prompts? Might make sense for some!

unless I'm forgetting any, I think for all. this site https://permission.site/ is super useful for testing the various browser-level Permissions.

> 4. what happens if I'm in Immersive Mode and a permission is requested? will the user be popped out of WebVR and into the standard 2D browser context, or will the user remain in VR?
> 
> That's a good question and might have security implications. Ideally the user would be able to remain in immersive mode and be presented with a prompt. See UF-4 #500 (from back in December)

@MozillaReality/fxr-eng can correct me if I'm wrong, but I believe some permissions (e.g., File `file:///` read access) require taking the user out of the experience into the void of Android system-level permissions. point being that the user's immersion is broken here anyway. something to keep in mind.

I agree that's an ideal user experience to not have to drop out of VR. There are a few attack vectors that it could possibly enable. Two that come to mind:

1. **Faux Permissions:** A sneaky developer could create and display a Permission prompt in WebGL/WebVR that resembles or looks identical to the FxR browser-level Permission prompts, tricking the user into doing unnecessary actions so as to confuse the user. Likely, the user would get "Permission-Prompt Fatigue" and ignore future, real FxR browser-level Permission prompts.
2. **Clickjacking:** A sneaky developer could request for a Permisson (e.g., Geolocation), and knowing the coordinates of where the user is looking, the developer could carefully place some dangerous links below that do something they did not intend to do. So when the user clicks `Allow` or `Don't Allow`, and the Permission prompt gets dismissed, if the user clicked the primary button more than once (which is likely, with the finicky Oculus Go and VIVE Focus controllers), the user may have inadvertently clicked on the dangerous links.

we should probably consult the Firefox Security folks now about this. @larsbergstrom: do you know whom are point of contacts would be about the Permissions API and browser chrome?

**Comment by larsbergstrom** [comment]
Thanks for diving in on this, @cvan!

@avadacatavra is leading up the efforts around permissions and browsers in the VR/AR space for the team (working with @blairmacintyre).

**Comment by cvan** [comment]
Are there actionable steps we can take here today in FxR? CC @avadacatavra

**Comment by avadacatavra** [comment]
@cvan I'm planning on working on permissions as my next project--we can set up a time to chat when I return from Japan

**Comment by blairmacintyre** [comment]
Whatever we do here will be relevant to the ongoing discussions of navigation, and other such permissions, I think.

FWIW, I do not find the current permission dialogs too bad:  I find them less invasive than desktop because they happen in the center so they are less awkward to handle then drop downs in the upper corner of the 2D windows

**Comment by philip-lamb** [comment]
P5 and Icebox until we have actionable steps.

**Comment by philip-lamb** [comment]
Closing in favour of #613 and with followup based on WebXR specs in that issue.
