### ISSUE TITLE
The controls from the right side of the Youtube videos are not displayed for all videos on windows having the 0.5x size

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2641]
**[Affected Versions]:**
- Firefox Reality version 8-40131058 (dd3477c).

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The 0.5x size is set for the window.

**[Steps to reproduce]:**
1. Navigate to the Youtube website.
2. Play for example the following video: https://www.youtube.com/watch?v=8CdcCD5V-d8.
3. Observe the controls from the right side of the video.

**[Expected results]:**
- The "Settings", "Miniplayer", "Theater Mode", "Play on TV"and "Full Screen" buttons are displayed.

**[Actual results]:**
- The "Settings", "Miniplayer", "Theater Mode" , "Play on TV" and "Full Screen" buttons are NOT displayed.

**[Notes]:**
- Needed by #1760.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1Z51qZD7ObDAhYKRrX-LwwNfgvuzxHVmI).

**Comment by bluemarvin** [comment]
This appears to be an issue with youtube. When I tested in the Oculus Native browser, they seem to work around the issue by not allowing the youtube viewport to not go below a certain threshold so that the page is horizontally scrollable if the window becomes too narrow.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 11-141492311 (a9b58ee6) installed on the Oculus Go, Pico Neo2 and Pico G2 4K headsets.
Unfortunately, the issue is still reproducible on videos with more control buttons on the right side or if the video time is longer than 1 hour. Because of this I will reopen the issue.
