### ISSUE TITLE
Oculus App Deep Linking [Feature Request]

### ISSUE THREAD

**Issue by Devriak** [MozillaReality/FirefoxReality#2647]
## Hardware
Oculus Go, Oculus Quest, FireFox Reality as of 1/14/2020

https://developer.oculus.com/documentation/platform/latest/concepts/dg-deeplinking/?locale=en_US

As per the Oculus App Deeplinking page, can support be added to allow deeplinking into firefox reality via url? 

At the moment we only really have to pass the url to deeplink to the Oculus Browser, but given that the Oculus Browser is not yet supported on the quest it would be great to be able to deeplink into firefox reality in a similar fashion.

Or if this is already supported documentation about it would be enough.

```
```

**Comment by bluemarvin** [comment]
It looks fairly easy to support. What options would you want FxR to support beyond the obvious URL to open?

**Comment by Devriak** [comment]
Nothing really beyond that at the moment. We just regularly have clients that would like to be able to deeplink out to a given url to visit their sites, or other applications. Applications we already handle. But the ability to open firefox direct to a url would be a big benefit.

**Comment by bluemarvin** [comment]
Would you find it unreasonable to use JSON for the option string? I would probably only support opening a single URL but want to have the option to add more parameters without breaking compatibility.

**Comment by Devriak** [comment]
Not at all, I generally pass JSON around, so doesn't bother me in the least, and makes total sense.

**Comment by bluemarvin** [comment]
Will be included in v10. To open link in FxR:
```
ovrApplicationOptionsHandle options = ovr_ApplicationOptions_Create();
ovrID id = 2180252408763702;
ovr_ApplicationOptions_SetDeeplinkMessage(options, "https://www.mozilla.org");
ovr_Application_LaunchOtherApp(id, options);
```

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this feature with multiple builds installed on the Oculus Go and Oculus Quest headsets also using the testing app, when the trigger button is pressed the user is redirected to FxR and the mozilla.org website is opened.
