### ISSUE TITLE
[meta] Make Vimeo better

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#2648]

**Comment by keianhzo** [comment]
@emstanley I don't find concrete opened issues related to this meta. Are there still any?

**Comment by bluemarvin** [comment]
https://github.com/MozillaReality/FirefoxReality/issues/3520

**Comment by bluemarvin** [comment]
I think the idea was that the Vimeo web extension need the same re-write that the youtube one received. It never worked quite right. But I do not believe there was anything specific previously filed.
