### ISSUE TITLE
Safe Browsing does not appear to work.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#265]
Hardware: All
Steps to Reproduce: Go to a blocked page
Actual Behavior: No error page is shown.
Expected Behavior: An error page should be shown.
Recommendation: This appears to be a GeckoView bug. We are going to repurpose:

https://bugzilla.mozilla.org/show_bug.cgi?id=1462000

to include fixing Safe Browsing. It will get re-triaged in the next GV triage meeting.

**Comment by bluemarvin** [comment]
We should be able to have better error pages once 

https://bugzilla.mozilla.org/show_bug.cgi?id=1451476

lands.

There is still the question of if the block list is being downloaded and who is responsible for that. I'm still investigating.

**Comment by keianhzo** [comment]
onLoadError API is already implemented in FxR. 

Waiting for the SafeBrowsing API to land, GV team is currently working on it.

**Comment by keianhzo** [comment]
@larsbergstrom all the design/implementation has already been done when we added the new onLoadError API and internal pages localization. At the moment we are using the same template for all error pages so unless we want to customize the safe browsing pages I think it's ok. 

I'm just going to do a minor fix for they try button positioning in the template.

For testing purposes you can use: https://testsafebrowsing.appspot.com/
