### ISSUE TITLE
[L10n][French] The "Sync Now" button's name from the "Manage Account" prompt is cut off

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2652]
**[Affected Versions]:**
- Firefox Reality version 8-33550026 (933fcd51)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The app's language is set in "Francais".
- You are logged into an FxA account and the account is synced.

**[Steps to reproduce]:**
1. Click the Settings button.
2. Click the "Manage Account" card.
3. Observe the "Sync Now" button.

**[Expected results]:**
- The button is correctly displayed.

**[Actual results]:**
- The name of the button is cut off.

**[Additional Notes]:**
- Attached is a screenshot of the issue: 
![French](https://user-images.githubusercontent.com/40061643/72449764-e21d2c80-37c1-11ea-95f8-68c38537fe17.jpg)

**Comment by keianhzo** [comment]
@Delphine Any chance of finding a shorter version for this?

**Comment by keianhzo** [comment]
@Delphine Any chance of having a shorter version of this?

**Comment by Delphine** [comment]
Hi, and sorry for the lag - I just came back to work on Monday and was off until then!
I don't really see how one can make this shorter, but flagging the French locale manager just in case, and so he can pitch in.
Thank you!
CC @TheoChevalier

**Comment by TheoChevalier** [comment]
Hi, as mentioned here https://github.com/MozillaReality/FirefoxReality/issues/2532#issuecomment-617157070 I’m happy to drop the "Now" part, just let me know if that’s acceptable

**Comment by TheoChevalier** [comment]
Actually, I went for it, let me know if that’s not okay https://github.com/mozilla-l10n/android-l10n/commit/0e858d068147efdffd0bc6a7660e909e64f453d1
Thanks!

**Comment by keianhzo** [comment]
@Softvision-RemusDranca Closing as this has been fixed that the commit above that has already been uplifter. Thanks @TheoChevalier!

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using Firefox Reality 11-141740850 (77deb30). Now, only the "Synchroniser" string is displayed and it fits the button's boundaries.

Tested on HTC Vive Focus (Android 7.1.2), Oculus Quest (Android 7.1.1), and Pico Neo 2 (Android - 8.1.0) devices.
