### ISSUE TITLE
[Intermittent] Some videos can be played at the same time

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2654]
**[Affected Versions]:**
- Firefox Reality version 8 RC1 (7a444d0c)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to the YouTube homepage select a video and play it.
2. Click the “+” in the menu tray.
3. In the new window navigate to the YouTube homepage select a video and play it.
4. Observe the behavior of the video from step 1.

**[Expected results]:**
- The video from step 1 is paused when the other video is played.

**[Actual results]:**
- The video from step 1 continues to play at the same time with the other video.

**[Notes]:**
- Sometimes the other video needs to be played again.
- The issue is also reproducible with Vimeo videos. 
- The issue is not reproducible with videos from the FxR homepage or videos that are restored after a restart.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=17S2DWyYsdOYve48T7TDESw87Fw5uVXr6).

**Comment by bluemarvin** [comment]
This functionality is handled by the media layer in Gecko. It isn't clear to me what the correct behavior should be. For example, on desktop it is possible to play two youtube videos at the same time.

**Comment by keianhzo** [comment]
I've been testing for a while and I don't really see consistency in GV's behavior on media sessions pausing/resuming. Sometimes I've got videos playing at the same time, others the active media session is paused when another one is played. It's not really consistent though, happens randomly.

Might be related to
