### ISSUE TITLE
The Tabs dialog scrollbar disappears after entering/exiting Select mode

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2656]
**[Affected Versions]:**
- Firefox Reality version 8 RC1 (7a444d0c)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Make sure to have 14 tabs created.

**[Steps to reproduce]:**
1. Click the "View Tabs" button in the menu tray.
2. Click the "Select" button in the tab dialog.
3. Observe the scrollbar.

**[Expected results]:**
- The scrollbar remains displayed after entering Select mode in the Tabs dialog.

**[Actual results]:**
- The scrollbar disappears after entering Select mode in the Tabs dialog.

**[Notes]:**
- After a tab is hovered the scrollbar reappears.
- As a side effect after the Tabs view is scrolled the scrollbar resizes, but only on the HTC device.
- The issue is also reproducible on exiting Select mode.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1prbuQC0mWj7dpve8wiHmDKr7fcgb7qfg).

**Comment by bluemarvin** [comment]
Scroll bars on android are difficult. I think we need to re-evaluate our usage and implementation of them.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10-40720037 (dbb8ed3a) installed on the Oculus Go, Quest, HTC Vive Focus, HTC Vive Focus Plus and Pico Neo2 headsets.
Now, the Tabs dialog scrollbar doesn’t disappear after entering/exiting Select mode.
