### ISSUE TITLE
Theater mode is displayed in flat or curved mode depending on how many windows are opened

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2660]
**[Affected Versions]:**
- Firefox Reality version 8 RC1 (7a444d0c)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to a normal video on YouTube and enter theater/full screen mode.
2. Observe the displayed window.
3. Exit theater (full screen) mode and click the “+” button in the menu tray.
4. Enter theater/full screen mode again.
5. Observe the displayed window.

**[Expected results]:**
- The window is displayed flat while in theater/fullscreen mode.
OR
- The window is displayed curved while in theater/fullscreen mode.

**[Actual results]:**
- Depending on if there is one window or multiple windows opened the theater/fullscreen mode display is flat or curved.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1UHzlG44w6sEoVoP0DO5pD-vY4a7aznJy).

**Comment by bluemarvin** [comment]
This has been an issue since we added multi-window support.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 9-40290101 (854287c0) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the view is displayed flat regardless of how many windows there are opened, except for when the curved display setting is on. 
However the theater mode menu tray is still displayed in flat or curved mode depending on the number of windows, the issue is more visible when the projection or brightness menu are opened, the behaviour can be seen in [this video](https://drive.google.com/open?id=1UOxQwz9xwZe2a5D3WUfE0HSRk4t2PEyD).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10 RC5 (e84d3c92) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the theater mode is displayed correctly.
