### ISSUE TITLE
Changing the two Sync Settings can not be done at the same time

### ISSUE THREAD

**Issue by heres-maria-sv-inactive** [MozillaReality/FirefoxReality#2661]
**[Affected Versions]:**
- Firefox Reality version 8 rc1 (7a444d0c)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is open.
- You are signed into an FxA account.

**[Steps to reproduce]:**                                        
1. Open the “Manage Account” card from Settings.
2. Click on the “Bookmarks” button from “Sync Settings”.
3. Immediately click on the “History” button.
4. Observe the two buttons when the sync is finalized.

**[Expected results]:**
- Both settings remain in the chosen states.

**[Actual results]:**
- The second setting changed will return to its initial state when the sync process ends.

**[Notes]:**
- This issue was predicted in [this comment](https://github.com/MozillaReality/FirefoxReality/issues/2409#issuecomment-573676669) of issue #2409.
- This issue is also reproducible on Firefox Preview.
- Attached is a recording of the [issue](https://drive.google.com/file/d/1YINbau97_cfGizvHbH3WhFM1jHNf8AFd/view?usp=sharing).

**Comment by keianhzo** [comment]
We have decided to mimic Fenix's behavior when syncing as the workarounds that we implemented to fix this had other side effects, so this is the expected behavior now.

**Comment by Softvision-RemusDranca** [comment]
@keianhzo I was thinking on a different approach for this issue. More exactly, to reopen it and reduce the severity since it could still affect the end user. We could even add a label to tie it as a FxA depending issue.
From what I know this issue is also tracked in the application-services repo in issue https://github.com/mozilla/application-services/issues/2161 and when a fix is available we can verify it on FxR as well.
Is this approach acceptable to you or are there any other concerns why we should keep it closed?

**Comment by keianhzo** [comment]
@Softvision-RemusDranca that sounds great to make.

**Comment by Softvision-RemusDranca** [comment]
@keianhzo awesome, I will reopen it and change its severity to normal.
Also, we will think on some suitable labels to link the issue to FxA so we can also use it for future related issues, if they may come. 
Thanks for your input and I'll follow up with the label names ASAP.

**Comment by bluemarvin** [comment]
I'm not seeing any movement on the application-services bug. If it is important we should try getting it escalated.

**Comment by keianhzo** [comment]
@bluemarvin I've pinged Grisha about this.

**Comment by keianhzo** [comment]
Per Emily's feedback this is still being discussed, not happening for v10. We should push to v11.

**Comment by keianhzo** [comment]
I see activity in AC/AS but is not yet ready.
