### ISSUE TITLE
The menu tray and awesomebar from normal browsing are displayed in PB

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2662]
**[Affected Versions]:**
- Firefox Reality version 8 RC1 (7a444d0c)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Click the “+” button in the menu tray.
2. From the left window click the PB button from the menu tray.
3. In PB click the PB button from the menu tray to exit.
4. Click the PB button from the menu tray.
5. Observe the menu tray and awesomebar.

**[Expected results]:**
- The menu tray and awesomebar are positioned centered below the active window.

**[Actual results]:**
- The menu tray and awesomebar from normal browsing are displayed and positioned to the far left.

**[Notes]:**
- The issue is also reproducible using the right window and the tray will be positioned to the far right.
- The issue is not reproducible using the middle window.
- As a side effect of this issue if an URL is entered in the awesomebar the page opens in normal browsing.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1acpeTRbldfObUi3WqXSF8Nts0CohA5t5).

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Realty 8 RC2 (4ff1f59). Now, the menu tray and Awesomebar from normal browsing are only briefly displayed when entering in PB. I opened issue #2683 documenting this behavior and with a lower severity.

Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
