### ISSUE TITLE
[Intermittent] The app crashes after resume if it was previously used for a long period of time

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2663]
**[Affected Versions]:**
- Firefox Reality version 8 RC1 (7a444d0).

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate on the browser and "stress" the app for approximately 15 minutes.
2. Click the Oculus/Vive button from the controller.
3. Click the "Home/Quit" button.
4. Reopen the app and observe the behavior.

**[Expected results]:**
- The app is correctly opened.

**[Actual results]:**
- The crash dialog box is displayed.

**[Notes]:**
- In some attempts on the HTC devices a black screen is displayed after resuming the app and remains in that state.
- Attached is the Crash Report: [link](https://crash-stats.mozilla.com/report/index/bp-e91abe31-8500-44b9-a7ab-db1920200116).

**Comment by Softvision-GeluHaiduc** [comment]
During testing of the V8 RC2 build I encountered this issue on the HTC Vive Focus Plus, it seems that the app crashes more frequently now when using the app for a longer period of time and resuming the app, the device also went to sleep for ~1 hour and then used again.

**Comment by Softvision-RemusDranca** [comment]
Retesting this issue with the latest V8 RC3 (eb9a1ec) build, seems to result in an even more frequent crash, especially after resuming the app while first playing a video in immersive mode.
Also, in some attempts the app is closed when trying to open it, on the HTC devices.
 I've attached the logcat , video and crashes received:
- Logcat - [link](https://drive.google.com/open?id=1sjle228MChCyuABxTjGSjB2cBbYiu7uG).
- Video - [link](https://drive.google.com/open?id=1_HgVpaHmeEdsVR8zc1OeWg3yG2p4fP-E).
- Crash report on HTC - [link](https://crash-stats.mozilla.com/report/index/bp-7a50df6e-5501-4695-b185-22c5f0200121).
- Crash report on Oculus - [link](https://crash-stats.mozilla.com/report/index/8462ad08-06cc-4e34-82ee-f70520200121).

**Comment by bluemarvin** [comment]
Some of the HTC issues may have been helped by https://github.com/MozillaReality/FirefoxReality/pull/2743 
I would guess the Oculus issues may also be in part related to the surface texture leak. At this point there isn't anything actionable for us to address unfortunately as both stack traces show the crash occurring in threads created by the system and not under the control of FxR.
