### ISSUE TITLE
The Clear History dialog isn’t dismissed after clearing the history

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2664]
**[Affected Versions]:**
- Firefox Reality version 8 RC1 (7a444d0c)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Make sure to have a longer history feed.

**[Steps to reproduce]:**
1. Click the History button in the menu tray.
2. Click the “Clear History” button.
3. Select any option from the list and click the “Clear Now” button.
4. Observe the Clear History dialog.

**[Expected results]:**
- The Clear History dialog is dismissed.

**[Actual results]:**
- The Clear History dialog is not dismissed.

**[Notes]:**
- The issue is reproducible with any option from the Clear History dialog.
- No FxA account was logged in.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1pK__c33Z3zftsf4qrQQ9Q_Dh2UeZDQ2o).

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Realty 8 RC2 (4ff1f59). Now,  Clear History dialog is dismissed after clicking the "Clear Now" button.

Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
