### ISSUE TITLE
The last selected Clear History options remains highlighted after reentering the Clear History dialog

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2665]
**[Affected Versions]:**
- Firefox Reality version 8 RC1 (7a444d0c)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Click the History button in the menu tray.
2. Click the “Clear History” button.
3. Select a diferent option from the list and dismiss the dialog.
4. Click the “Clear History” button.
5. Observe the selected option.

**[Expected results]:**
- The option switches back to the default one (Today).

**[Actual results]:**
- The last selected option remains highlighted.

**[Notes]:**
- The issue is reproducible with any option from the Clear History dialog.
- No FxA account was logged in.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1tqRjDDiWq4VIDfHjFguzjPon7IZTnCZm).

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Realty 8 RC2 (4ff1f59). Now, the "Today" default option is selected after reopening the Clear History dialog.

Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
