### ISSUE TITLE
Entering Private Mode does not display Private Mode details page

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#267]
Hardware: All
Steps to Reproduce: Enter private mode
Actual Behavior: Does not show private mode detail page
Expected Behavior: Should see new page with private mode details, same as in Firefox Desktop and in design doc
Recommendation: implement private mode page per design

**Comment by bluemarvin** [comment]
Make sure the page is designed to work with issue #269 so that it may be localized.

**Comment by keianhzo** [comment]
@thenadj I guess we could start with the design process for the Private Mode page while Gecko onLoadError API lands.

**Comment by avrignaud** [comment]
@keianhzo Let me add @fernandojsg to this. Fernando, both this bug and https://github.com/MozillaReality/FirefoxReality/issues/269 need some html code work in order to be implemented. Is this something @caseyyee or @cvan might be able to help with? Think @MortimerGoro and @keianhzo will need to do some work after these pages are done to use strings.xml to create localized versions as well.

**Comment by caseyyee** [comment]
@keianhzo Just a html page like the neterror.html? Let me know, can help throw that together.

**Comment by keianhzo** [comment]
@caseyyee Yes, something like the Private Mode landing page for the Firefox Private mode, not sure what @thenadj has in mind for that. 

As soon as Gecko onLoadError lands this page will be localized. The initial localization approach was to load all the  strings from the android strings.xml file but I wonder if it's a more HTML natural way of dealing with localization instead of sending all the page strings as parameters when loading the URL. @caseyyee @cvan @bluemarvin 

Or do we prefer to centralize all the localization in the strings.xml?

**Comment by avrignaud** [comment]
Adding @fernandojsg . I believe he's asked Casey to help here. Goal is to get strings into strings.xml for easier localization.

**Comment by thenadj** [comment]
For now we are using the exact same page design/content/colors as Firefox has for Private Browsing.

**Comment by bluemarvin** [comment]
This has nothing to do with the linked GV bug.

**Comment by nancyhang** [comment]
I deleted it.

**Comment by cvan** [comment]
Request: could we add a purple border to the window and the (X) close button to help better indicate the user is in Private Browsing?

**Comment by keianhzo** [comment]
@avrignaud @ferjm @caseyyee What's the status on the HTML/CSS for the PB homepage?

**Comment by caseyyee** [comment]
Alright, will make a PR into the same spot as the error pages, @keianhzo.  Will flag @thenadj for design review.

**Comment by keianhzo** [comment]
Closing this as it's been merged in #337
