### ISSUE TITLE
The next video is wrongly played or the recommended videos are displayed after a video was played in immersive mode

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2673]
**[Affected Versions]:**
- Firefox Reality version 8 RC1 (7a444d0).

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Play a 360 video in immersive mode.
2. Wait until the video finises playing.
3. Observe the behavior.

**[Expected results]:**
- The video is exited from immersive mode if the next video is not compatible.
OR
- An option to replay the video is displayed.

**[Actual results]:**
- Autoplay ON: The next video is played even if it is not compatible.
- Autoplay OFF: The window with the suggested videos is displayed in immersive mode and it's not actionable.

**[Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1FwbfXer49PAsZNIfhK34fPqmBFnWRXRm).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 11-141492311 (a9b58ee6) installed on the Oculus Go, Pico Neo2 and Pico G2 4K headsets.
Now, if autoplay is ON the next video is played even if it is not compatible and if autoplay is OFF the layer with the suggested videos is NOT displayed in immersive mode.
