### ISSUE TITLE
Refactor strings.xml to better support l10n

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#268]
Some strings in string.xml are combined to make a single sentence. It is easier to localize if each sentence is its own string even if there is some duplication.

**Comment by Pike** [comment]
If we're talking about

https://github.com/MozillaReality/FirefoxReality/blob/d065d663bcda4e6af58da34be3bdf5da887581a5/app/src/main/res/values/strings.xml#L8-L12

that's branding that's passed in, right? If so, that's OK.

We should have a comment explaining that for each string individually, though.

CC @delphine
