### ISSUE TITLE
Websites can not be scrolled if navigated to from an allowed pop-up blocked page

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2684]
**[Affected Versions]:**
- Firefox Reality version 8 RC2 (4ff1f591)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- Change the device language to another one.
- The "Block Pop-Up Windows" option is disabled.

**[Steps to reproduce]:**
1. Navigate to the following website: "http://popuptest.com/” and click on a pop-up technique.
2. In the same window navigate to any website. (e.g. FxR Homepage)
3. Try to scroll the page and observe the behaviour.

**[Expected results]:**
- The page can be scrolled.

**[Actual results]:**
- The page can not be scrolled.

**[Notes]:**
- The issue persists on all websites that are navigated on that window.
- The issue is not present in a new window created.
- The issue is also reproducible if the "Block Pop-Up Windows" option is enabled and a pop-up technique is allowed.
- The issue is not reproducible in the production version 7.1
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1qGahITVbiQhP46-tN3Jh5QOW-KtIiVf1).

**Comment by keianhzo** [comment]
This should have been closed by https://github.com/MozillaReality/FirefoxReality/pull/2687 I forgot to reference the issue int he PR body.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 8 RC4 (f9c92a23) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the websites can be scrolled if navigated to from an allowed pop-up blocked page.
