### ISSUE TITLE
The time needed to long press the controller button to trigger the Paste menu is too long

### ISSUE THREAD

**Issue by heres-maria-sv-inactive** [MozillaReality/FirefoxReality#2686]
**[Affected Versions]:**
- Firefox Reality version 8 RC2 (4ff1f591)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is open.

**[Steps to reproduce]:**                                        
1. Go to https://en.wikipedia.org/wiki/Main_Page.
2. Using the controller long press the trigger button on a word.
3. Click the "Copy" button.
4. Focus the empty search field of the page.
5. Long press the controller trigger button and observe the time needed for the Paste menu to be displayed.

**[Expected results]:**
- The time needed is equal to the time needed for the Copy menu, for example.

**[Actual results]:**
-  The time needed is uncomfortably longer.

**Comment by keianhzo** [comment]
I seem what the the issue means but I'm not sure if there is anything we can do about it, we show the popup as soon as GV sends the callback which seems to take a bit longer for text fields.

@bluemarvin Is this worth to escalate to GV?
