### ISSUE TITLE
Firefox Reality app for Google Daydream is not found on the Google Play store.

### ISSUE THREAD

**Issue by flagstone78** [MozillaReality/FirefoxReality#2708]
## Configuration

Firefox Reality version:  N/A
Firefox Reality build ID:  N/A

Hardware: Daydream View / any phone

## Steps to Reproduce

1.  Go to https://mixedreality.mozilla.org/firefox-reality/
2.  Click "get it for google daydream"

## Current Behavior

Google Play presents the following: "We're sorry, the requested URL was not found on this server"

## Expected Behavior

Google Play should open a firefox reality app page.

```
```

</details>

**Comment by bluemarvin** [comment]
Firefox Reality is no longer supported in the Google Play store. It is currently only available for side loading. I have filed https://github.com/MozillaReality/vr-mozilla-org/issues/79
