### ISSUE TITLE
Display density does not work as expected when user agent mode is desktop

### ISSUE THREAD

**Issue by crh0716** [MozillaReality/FirefoxReality#2709]
## Configuration

Firefox Reality version: 7.1
Firefox Reality build ID: 

Hardware:  Oculus Quest

## Steps to Reproduce

1. Launch Firefox Reality.
2. Go to display settings. Set user agent mode to desktop and display density to any value other than 1.
3. Browse any web sites.

## Current Behavior

The window (window.innerWidth, window.innerHeight) size remains the same as display density is 1.

## Expected Behavior

The window size should be adjusted based on display density. 

## Context

I was trying to enlarge the displaying size of the web pages but couldn't find the zoom control. Ideally there should be a zoom control like any other desktop browser to enlarge the content without the need of tweaking display density.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
The display density setting should be removed and a zoom controller should be added as documented in #379.
