### ISSUE TITLE
[Oculus] The background doesn't gain an overlay after long clicking on a link inside theater mode

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2710]
**[Affected Versions]:**
- Firefox Reality version 9-40290101 (854287c0)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to a normal video on YouTube and enter theater/full screen mode.
2. Scroll down and long click on a link.
3. Observe the behaviour.

**[Expected results]:**
- The background gains an overlay and the context menu appears centered in the window.

**[Actual results]:**
- The background doesn't gain an overlay and the context menu appears centered in the window.

**[Notes]:**
- The issue is not reproducible on the HTC devices.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1mfwum64__BzRxSne618_IEGiCoDlDWwI).

**Comment by bluemarvin** [comment]
@MortimerGoro Is this caused by the asynchronous layer not having the tint set?

**Comment by keianhzo** [comment]
@Softvision-GeluHaiduc This should have been fixed by the async layers tint fix. Can you please check?

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10-40720037 (dbb8ed3a) installed on the Oculus Go and Oculus Quest headsets.
Now, the background does gain an overlay after long clicking on a link inside theater mode.
