### ISSUE TITLE
The video page is not rendered correctly after navigating back to it from a link opened in theater mode

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2712]
**[Affected Versions]:**
- Firefox Reality version 9-40290101 (854287c0)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to a normal video on YouTube and enter theater/full screen mode.
2. Scroll down and click on a link.
3. Exit theater mode and click the “Back” button from the navigation bar.
4. Observe the page.

**[Expected results]:**
- The video page is rendered in the YouTube default view.

**[Actual results]:**
- The video page is rendered in the YouTube theater mode.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1v_hfnnHGc2B1W3fsWgSsvJTlXd0rAGiH).

**Comment by Softvision-GeluHaiduc** [comment]
I would also like to add a question.
What is the desired behavior here when clicking a link inside theater mode, is the link supposed to be opened in theater mode or should theater mode be exited and the link opened?

**Comment by keianhzo** [comment]
@Softvision-GeluHaiduc I don't think I can reproduce this anymore with latest master. Could you please check and see if this is still an issue?

**Comment by Softvision-GeluHaiduc** [comment]
Using the latest RC, Firefox Reality version 9 RC1 (33f6c4d8), I couldn’t reproduce this issue.

**Comment by keianhzo** [comment]
@Softvision-GeluHaiduc I'll close this then, you can reopen if you see again.
