### ISSUE TITLE
[Keyboard] The TLD are wrongly inserted in uppercase if the shift key is in caps lock mode

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2713]
**[Affected Versions]:**
- Firefox Reality version 9-40290101 (854287c0)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Focus the Awesomebar.
2. Double click on the shift key to lock.
3. Click the ".com" key and select one of the domain.
4. Observe the Awesomebar.

**[Expected results]:**
- The domain is inserted in lowercase.

**[Actual results]:**
- The domain is inserted in uppercase.

**[Notes]:**
- The issue is not reproducible on mobile Android.
- This issue is not reproducible in the 7.1 production version of the app.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=18drKF2gwF69o9vN2HgqEDXsL98D8XdLZ).

**Comment by keianhzo** [comment]
I'd say that this is the right behavior, if the caps are locked you are supposed to uppercase any character that's added, right?

**Comment by Softvision-RemusDranca** [comment]
@keianhzo I am not sure what the expected behavior is in Firefox Reality. I compared this behavior with the mobile (Android) and with Oculus Browser keyboards where the Domain is inserted in lowercase even if the shift key is in caps lock mode.

Also, the menu of the TLD is displayed in lowercase when opened while the shift key is in caps lock mode. If we decide that the behavior mentioned in the issue is the correct one, then this behavior will result in a issue.

**Comment by keianhzo** [comment]
I'm pretty sure we are going to switch this for a long press popup menu (which makes more sense IMHO) and was already brought up in the past, so I suggest we push this to v10 and we decide then. The way it is now (a modal popup) it's slow and is not aligned with how mobile works.

What do you think @emstanley ?

**Comment by thenadj** [comment]
The Oculus browser always uses lower case for the domain, even if the keyboard is locked to UPPER CASE. Let's follow that behavior for FxR.

**Comment by keianhzo** [comment]
ok,let's just do that then.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the Firefox Reality version 10-40720037 (dbb8ed3a). The TLD are displayed in lowercases even when the shift key is in caps lock mode.

Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2), HTC Vive Focus (Android 7.1.2) and Pico Neo 2 (Android 8.1.0).
