### ISSUE TITLE
[Keyboard][zh-TW] The string for the Space key exits the keys boundaries

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2714]
**[Affected Versions]:**
- Firefox Reality version 9-40290101 (854287c0)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Focus the Awesomebar.
2. Click the Language select key (globe).
3. Select the third language from the top left from the sub-menu displayed.
4. Observe the string displayed in the Space key.

**[Expected results]:**
- The string is correctly displayed.

**[Actual results]:**
- The string exits the key's boundaries.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1Rjv26adFZlRx8dS0STjYABipOi1E27RS).

**Comment by keianhzo** [comment]
We show the language in the space bar for a couple of seconds  when there is a language switch but the space bar is too short in this keyboard and the text doesn't fit. I guess we will need a redesign for this. 

@Delphine @daoshengmu Based on current Andorid/iOS Zhuyin keyboards I've drafted a proposal with a bigger space bar size, let me know if it seems reasonable:

![org mozilla vrbrowser dev-20200217-154259](https://user-images.githubusercontent.com/837184/74663860-e52e8280-519c-11ea-97f0-11f49664a9f9.jpg)

**Comment by daoshengmu** [comment]
@keianhzo Sorry about that, your proposal looks odd to me. The layout you provide is not a familiar one for most users. We should provide the same offset as we have in US-Eng. keyboard on each layers.

The image below is Transitional Chinese IME in iOS, I don't have an Android phone in my hand.
![IMG_8858](https://user-images.githubusercontent.com/1263177/74765545-a64e0a80-5238-11ea-9a4b-9e7eabf4d454.PNG)

Let me do some adjustment today. Btw, do we need to go through design review?

**Comment by keianhzo** [comment]
@daoshengmu I've a branch with basically the same layout. I've answered in your PR thread. Let see what Erica says.

**Comment by keianhzo** [comment]
@thenadj Dis you have a chance to take a look at the APK? Any suggestions about what to do in this case?

**Comment by cjyjae35** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BUG-40 Zhuyin Keyboard](https://trello.com/c/fFVzVV7y/521-bug-40-zhuyin-keyboard)

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality 10-140840311 staging-master-signed.apk latest build (8142076). Now, the name of the language is no longer displayed in the space bar key.

Tested on HTC Vive Plus (Android 7.1.2), Pico Neo 2 (Android - 8.1.0) and Oculus Quest (Android 7.1.1) devices.
