### ISSUE TITLE
The opened card wrongly remains in a click state if it's opened while the log into an FxA process is almost complete

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2715]
**[Affected Versions]:**
- Firefox Reality version 9-40290101 (854287c0)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Have a valid FxA account.

**[Steps to reproduce]:**
1. Log into the FxA account.
2. While in the login process click the Settings button and open a card.
3. Dismiss the automatically opened "Manage Accout" prompt.
4. Observe the previous opened card displayed in the Settings menu.

**[Expected results]:**
- The card is correctly displayed.

**[Actual results]:**
- The card is in a click state and remains that way until is clicked.

**[Notes]:**
- This issue occurs in a certain moment, only when the login process is almost complete.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=16Zj6l5xt5WBG6D40O4RR7kJABdSiy8aL).

**Comment by keianhzo** [comment]
I can't reproduce this issue anymore, could you confirm @Softvision-RemusDranca ?

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue using V9 RC2 (37ac4cb) build and I was no longer able reproducible in 10 attempts. Tested on Oculus Quest, HTC Vive Focus Plus and Pico Neo 2 devices.

Considering this I will close this issue as verified-fixed and will log a new one if it's encountered in the future.
