### ISSUE TITLE
The Voice Search button is not displayed after navigating to a webpage

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2728]
**[Affected Versions]:**
- Firefox Reality version 9-40311840 (85032800)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
 - HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is open.

**[Steps to reproduce]:**                                        
1. Navigate to a webpage that is not the FxR homepage.
2. Observe the awesomebar.

**[Expected results]:**
- The Voice Search button is displayed.

**[Actual results]:**
- The Voice Search button is not displayed.

**[Notes]:**
- The button is displayed after focusing the awesomebar and then unfocusing it.
- The button is no longer displayed when navigating to another webpage or unfocusing and refocusing the window.
- Attached is a [recording](https://drive.google.com/file/d/1mo1sogwCBMFzPkG-ngpI7uf7MuPQWSM9/view?usp=sharing) of the issue.

**Comment by larsbergstrom** [comment]
Awesome catch - thanks for finding this, @heres-maria!

**Comment by heres-maria** [comment]
I have verified this issue and it is no longer reproducible with the latest Firefox Reality version 9-40341450 (ade4895e) build. The Voice Search button is displayed even after changing the webpage or unfocusing and refocusing the window.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
