### ISSUE TITLE
Crash on veer.tv site

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#273]
Hardware: Go
Steps to Reproduce:
1) Go to veer.tv
2) select a video and play
3) press the arrow button at the top left of the video window
Actual Behavior: FxR crashes
Expected Behavior: FxR goes back previous page where the video was selected
Recommendation: This only happens on the Go. The crash looks like it could be a release assert in Gecko:

07-27 16:33:17.942  4141  4161 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 4161 (Gecko)

But there is no stack trace. Attempting to run in the debugger also fails due to the false crash every time a controller button is pressed on the Go.

**Comment by MortimerGoro** [comment]
> 1. 07-27 16:33:17.942 4141 4161 F libc : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 4161 (Gecko)

I did a try and didn't see a crash

> But there is no stack trace. Attempting to run in the debugger also fails due to the false crash every time a controller button is pressed on the Go.

I added a debugging tip to the readme to fix that issue. Check this:

`On some platforms such as Oculus Go the native debugger stops on each input event. You can set this LLDB post attach command in Android Studio to fix the problem: pro hand -p true -s false SIGILL`

**Comment by bluemarvin** [comment]
I can't reproduce this crash either and can't find the original video that was causing the problem.

**Comment by bluemarvin** [comment]
I'll reopen if I can reproduce later.
