### ISSUE TITLE
Support multiple UA strings including mobile, desktop, and a new VR type.

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#274]
Hardware: All
Steps to Reproduce: Try to load website with both desktop and mobile page offerings (amazon.com)
Actual Behavior: Mobile site loads
Expected Behavior: Desktop site loads
Recommendation: Implement ability to request and display High DPI Desktop version of websites. 

Notes: user research is showing that the majority of users expect desktop-like functionality when using FxR due to large screen. In addition, significant usability challenges appear when users attempt to navigate mobile versions of sites, including confusing controls, misidentified/unseen hit targets, and lack of responsive site functionality - especially text remaining same size when window size scaled. This last issue may be part of the reason we are seeing users believe window is moving closer/further away from user when scaled - text size gets larger and smaller.

**Comment by cvan** [comment]
Is the recommendation here to change the User-Agent to be Firefox desktop's? Also I noticed that `meta[name=viewport]` seems to scrunch the sites a bit too much, since the 2D viewport in FxR is quite large. Perhaps I should file a separate issues for both.

**Comment by avrignaud** [comment]
I just set P0 on this, need to get some discussion going on what the right path forward is. I am sure there will be a different set of issues that come up with a desktop site being served to users, and we need to test/experiment. I think a good start would be to have an alternate Desktop UA string served up by default, with a pref to select. 

Users actually liked the 2D viewport - they want to take advantage of the larger "monitor" in space. But they get frustrated when the mobile site fixes text large, the site isn't responsive, or functionality they expect (like on Amazon's mobile site) doesn't work because from their perspective they are on a huge desktop.

**Comment by avrignaud** [comment]
@thenadj The ability to toggle between requesting Desktop or Mobile websites is likely another setting we want to add to the Developer Settings panel.

**Comment by avrignaud** [comment]
We'll talk more about this today, but from the user perspective, our goal is to explore being able to serve up a desktop site in the window while retaining performance, and visual fidelity/high quality text rendering. @kearwood thought supersampling might be a start, though @bluemarvin was concerned that perf might be an issue with desktop. At the end of the day, we need to experiment here and see if we can make it work - if we can, we'd have a significant differentiator from every other browser (and one that potentially allows us to double down on ad-blocking/tracking story as well - with bonus of being able to point to perf as an additional reason to enable in as robust a fashion as possible by default).

**Comment by avrignaud** [comment]
Based on meeting, we have the following tasks required to explore the viability of this feature:

- [ ] Adjust CSS Pixel Ratio (GV issue) (@bluemarvin please enter GH and Bugzilla issues)

- [ ] Design and implement scroll bars for desktop website view (https://github.com/MozillaReality/FirefoxReality/issues/317)

- [ ] Dev Options: Toggle between mouse/touch events, toggle between desktop/mobile site rendering, set pixel ratio for window (added to https://github.com/MozillaReality/FirefoxReality/issues/283)

- [ ] Implement way for webcompat to test different UA strings easily (@larsbergstrom please enter issue)

- [ ] Fix window resizing to display fixed pixel ratio, and not scale (@bluemarvin please enter GH issue)

- [ ] Implement cylindrical rendering for main window to improve display quality, especially fonts (@kearwood please enter GH issue)

**Comment by larsbergstrom** [comment]
Per @bluemarvin, "rbarker [4:02 PM] Okay, I got web compat set up with a build where they can set the UA."

**Comment by thenadj** [comment]
We'll add the desktop/mobile options into the dev options dialog.

**Comment by bluemarvin** [comment]
There will be three options: VR, Mobile, and Desktop. VR should be the default. This setting is per-session so when we have multiple windows it will be possible to request the page in any of the three types.

**Comment by thenadj** [comment]
Got it, thanks for the clarification. For v1 since we only have one window, it will just apply to all. Post v1 we'll figure out a way to choose per session, probably not in the dev options dialog at that point.

**Comment by bluemarvin** [comment]
Work in progress. This is what I believe the UA for VR should look like?

`Mozilla/5.0 (VR; rv:63.0) Gecko/63.0 Firefox/63.0`

![screenshot_20180816_122755](https://user-images.githubusercontent.com/3066/44230618-72c88680-a150-11e8-821b-9797a4553ec6.jpg)

**Comment by bluemarvin** [comment]
GeckoView bug for changing the UA:

https://bugzilla.mozilla.org/show_bug.cgi?id=1483596

**Comment by keianhzo** [comment]
Assigning to myself as this is part of #391

**Comment by keianhzo** [comment]
Closed per #391
