### ISSUE TITLE
The allowed popup list is blank after adding a page to the allowed list.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#2774]
## Configuration

Firefox Reality version: 9
Firefox Reality build ID: fef9ed28c2dee372672682aa8db10824d58ec895

Hardware: Go

## Steps to Reproduce

1. Go to a page that causes pop-ups.
2. Add page to allowed list
3. Go to the settings page that contains the allow list.

## Current Behavior

Allow list is blank
![org mozilla vrbrowser-20200210-140011](https://user-images.githubusercontent.com/3066/74194496-36bf9600-4c0e-11ea-9512-22dccb09ff66.jpg)

## Expected Behavior

Allow list should show the URL of the allowed page.

## Note
This isn't an issue of the page not being in the list as the allow list works, The allow list isn't displayed in the settings. Clearing the setting show the correct empty list for the panel:
![org mozilla vrbrowser-20200210-140025](https://user-images.githubusercontent.com/3066/74194585-67073480-4c0e-11ea-8f69-c0339dbaf05f.jpg)

**Comment by bluemarvin** [comment]
If it isn't obvious from the screen shots, this was on my Go. My Quest battery died so I couldn't test there.

**Comment by heres-maria** [comment]
I have verified this issue and it is no longer reproducible with the latest Firefox Reality 9 RC1 (33f6c4d8) build.
The list now displays the websites added to the exception list.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
