### ISSUE TITLE
A crash occurs when creating a new tab from the View Tabs menu 

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2775]
**[Affected Versions]:**
- Firefox Reality version 9-40412247 (3949e4c1)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on, the browser is installed and open.

**[Steps to reproduce]:**                                        
1. Click the “View Tabs” button from the tray.
2. Click the Add New Tab button.

**[Expected results]:**
- A new tab is created.

**[Actual results]:**
- The app crashes.

**[Notes]:**
- This issue is not reproducible when opening a new window, receiving a tab from another device or opening a new tab using the Context Menu.
- Attached is a [recording](https://drive.google.com/file/d/1qWl6UiP0nLP6lVcwVPihOL7SmQ5ulSTW/view?usp=sharing) of the issue.
- Attached is a [crash report](https://crash-stats.mozilla.com/report/index/bp-a8fa929e-ee7d-4412-9478-8a9590200211) of the issue.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9-40430119 (abd4f531) installed on the Oculus Go, Quest, HTC Vive Focus and Focus Plus headsets.
Now, the app doesn’t crash when a tab is created in the “View Tabs” dialog.
