### ISSUE TITLE
[Desktop Mode] A crash occurs when navigating on certain pages containing vr content

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2814]
**[Affected Versions]:**
- Firefox Reality 9 RC 2 (37ac4cbd)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2
- Pico Neo 2 - Android - 8.1.0

**[Prerequisites]:**
- The headset is turned on, the browser is installed and open.

**[Steps to reproduce]:**                                        
1. Open https://www.facebook.com/360Photos360Videos/.
2. Change to Desktop Mode from the Hamburger Menu. 
3. Navigate for a while and observe the behavior.

**[Expected results]:**
- You can navigate on the page successfully.

**[Actual results]:**
- FxR crashes.

**[Notes]:**
- This issue is also reproducible on other pages with similar vr video formats (e.g. Instagram).
- Attached is a [crash report](https://crash-stats.mozilla.com/report/index/8237e8f0-e8d8-4071-a28f-d7ff40200220) of the issue.
- Attached is a [recording](https://drive.google.com/file/d/1r2EUyPo6JkHX_y_UBn_h6-WFz-n_6V8Y/view?usp=sharing) of the issue.

**Comment by bluemarvin** [comment]
Turning on e10s seems to fix the issue.

**Comment by MortimerGoro** [comment]
I researched the problem, I added some details into the bugzilla ticked: https://bugzilla.mozilla.org/show_bug.cgi?id=1617751

**Comment by heres-maria** [comment]
The verification of this issue is currently blocked by #2885.

**Comment by heres-maria** [comment]
I have verified this issue and it is no longer reproducible in the v9 RC5 (3e30ba6e) build. 
The app no longer crashes when navigating on pages containing vr content in desktop mode.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
