### ISSUE TITLE
[Pico] The preinstalled device browser overwrites the FxR app when focusing the input fields from Display card settings

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2821]
**[Affected Versions]:**
- Firefox Reality 9 RC 2 (37ac4cbd)

**[Affected Platforms]:**
- Pico Neo 2 - Android - 8.1.0

**[Prerequisites]:**
- The headset is turned on, the browser is installed and open.

**[Steps to reproduce]:**										
1. Open the Display card from Settings.
2. Click the "Edit" button from the "Homepage" option.
3. Click inside the input field displayed.
4. Observe the behavior.

**[Expected results]:**
- The FxR keyboard is displayed.

**[Actual results]:**
- The preinstalled device browser overwrites the FxR app.

**[Notes]:**
- This issue is also reproducible with the "Display Density" and "Display DPI" input fields.
- Attached is screen recording of the issue: [link](https://drive.google.com/open?id=1zA5DibKtdryVv6It08B8VKVdBAkRbKhH).

**Comment by bluemarvin** [comment]
This looks like a pico system bug to me. This is the android system keyboard popping up on input focus. Pico should be suppressing it.

**Comment by keianhzo** [comment]
I could reproduce it once but cannot anymore so there must be something System or FxR level triggering that behavior. Specific STRs would help to discard that it's us and report. I'll keep on trying, in the meantime I will flag as `blocked` until we find better STRs.

**Comment by keianhzo** [comment]
STRs seem to be:
- Open Settings
- Open Display card
- Click twice on the homepage input field

It doesn't happen in any GV input fields or the URL bar.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 9 RC3 (18aba8b) build.

Tested on Pico Neo 2 (Android - 8.1.0), Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2) devices.
