### ISSUE TITLE
[Pico][Intermittent] The app crashes when trying to take a screenshot or record a video using the device functionality while in immersive mode 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2827]
**[Affected Versions]:**
- Firefox Reality 9 RC 2 (37ac4cbd)

**[Affected Platforms]:**
- Pico Neo 2 - Android - 8.1.0

**[Prerequisites]:**
- The headset is turned on, the browser is installed and open.

**[Steps to reproduce]:**										
1. Open a 360 video and play it in immersive mode.
2. Double press the device Home button.
3. Select the "Take a Screenshot" or "Record a Video" option from the device menu.
4. Observe the behavior.

**[Expected results]:**
- The FxR browser is redisplayed.

**[Actual results]:**
- The app crashes.

**[Notes]:**
- Attached are a screen recording along with the logcat and crash report of the issue:
	- Screen recording: [link](https://drive.google.com/open?id=1bXlWbj6k5Uo7L4rRSXsxIqNawHbKYcWg).
	- Crash report: [link](https://crash-stats.mozilla.com/report/index/1171235d-81d8-4b5f-adeb-9d8f20200221).
	- Logcat: [link](https://drive.google.com/open?id=1cVebQ5XfyGeM9sAs_7f4AH13YTkDfQ3f).

**Comment by emstanley** [comment]
@Softvision-RemusDranca Are you still able to reproduce this?

**Comment by Softvision-RemusDranca** [comment]
@emstanley I've retested this issue and I was not able to reproduce it in multiple attempts with the latest Firefox Reality 10-140840311 staging-master-signed.apk latest build (8142076). I think that is safe to close it for now and just open a new one if we encounter it in the future since is intermittent.
Tested on Pico Neo 2 - Android - 8.1.0.
