### ISSUE TITLE
The “Pop-Up Blocked” notification wrongly remains displayed in the Bookmark/History View

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2829]
**[Affected Versions]:**
- Firefox Reality version 9 RC2 (37ac4cbd)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to the following website: "http://popuptest.com/”
2. Click on a pop-up technique.
3. After the “Pop-Up Blocked” notification appears, click the Bookmark/History button in the menu tray.
4. Observe the “Pop-Up Blocked” notification.

**[Expected results]:**
- The “Pop-Up Blocked” notification is dismissed.

**[Actual results]:**
- The “Pop-Up Blocked” notification remains displayed.

**[Notes]:**
- The issue is not reproducible in production, FxR V8.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1hwwYUM9Wi1CcC0uxrTidBy0zlD5V2k6O).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 9 RC3 (18aba8be) installed on the Oculus Go, Quest, HTC Vive Focus, Focus Plus and Pico Neo2 headsets.
Now, the “Pop-Up Blocked” notification doesn’t remain displayed in the Bookmark/History View.
However, if the notification appears after the Bookmark/History View is displayed, using the timed pop-up, then the notification remains displayed. Giving this I will reopen this issue.

**Comment by bluemarvin** [comment]
@keianhzo If the notification does not stay permanently displayed, please move to milestone 10.

**Comment by keianhzo** [comment]
@Softvision-GeluHaiduc  This should have been fixed by 22c8c9c2c2c0325e0da078d571743d94fdb56f44. I can't reproduce in current master.

**Comment by Softvision-GeluHaiduc** [comment]
@keianhzo I tried it on the Quest with the latest master installed, Firefox Reality 9-40571049 (36644826). Using the original STR the issue is not reproducible. 
However, if the notification appears after the Bookmark/History View is displayed, using the timed pop-up or clicking the button just before the notification is displayed, then the notification remains displayed. 
If you want I can log a separate issue for this behavior and we can close this one.

**Comment by keianhzo** [comment]
@Softvision-GeluHaiduc Sorry, but I can't reproduce it following the latest STRs. I open the timed popup page, open the history before the popup is shown and I can see the popup notification appear and disappear, it doesn't remain displayed.
I think maybe we should close this one, open a new one with the exact new STRs and we can probably leave it for v10.

**Comment by Softvision-GeluHaiduc** [comment]
I verified the issue again in the latest RC, Firefox Reality version 9 RC4 (c64365e3), the original issue is no longer reproducible and I logged issue #2882 for the timed popup behaviour.
