### ISSUE TITLE
Implement a developer options panel

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#283]
We need some panel in FxR to toggle some develoepr options (e.g. show JS console logs, enable remote debugging, enable environment override for designers,  etc)

**Comment by avrignaud** [comment]
Right. But I'm not clear if this needs to be designed and explictly user facing? Ie, couldn't we do this in about:config or about:devtools or something else? Also trying to understand if there are other dev-facing toggles that we should be considering?

**Comment by bluemarvin** [comment]
We don't have the ability to set prefs from custom about: pages. It needs to be done from the app via the GeckoView API. I've verified we only need on/off switches for both right now.

**Comment by avrignaud** [comment]
Dug into this a bit more, and understand. That said, we are under a ton of UI/UX stress right now for 1.0. So, for 1.0 we'll implement a single "Enable Developer Options" option in Settings, and we can revisit something more granular for 1.1 or beyond. @bluemarvin Can you please list exactly which two options we are looking for the ability to toggle for 1.0? 

@thenadj I'll work with you to prioritize. But at the highest level, we need a way to enable two developer options in the settings. One option is to have a single "Enable all Developer Options" switch (and we turn on appropriate settings, and have a link to a SUMO page detailing what we do). Another option is to try and fit the two separate options on a single button/hex. But note that this is just a first step - we will likely have to find a way to allow users to access more developer options in 1.1. (For context, you can look at the Web Developer selections in Desktop Firefox settings.)

**Comment by MortimerGoro** [comment]
I'd use UI that makes easy to add more items for this (e.g. a List of items with scroll). We may have 2 options now but 10 in a future release. This will be a panel for developers. Example:

![image](https://user-images.githubusercontent.com/1070794/43536284-84c52cd4-95bc-11e8-8e25-83aeafb59067.png)


Some options that we can add now:

- Enable Remote Debugger
- Enable JS Console Output
- Enable Environment Override

**Comment by bluemarvin** [comment]
The three options @MortimerGoro list look good to me. We probably want a note in there some place that Firefox 63 is the minimum version required for developer tools (currently nightly).

GeckoView does not support WiFi Developer Tools and that is probably for the best since it requires a QR code reader on the device. So on/off for developer tools is more than adequate for now.

**Comment by bluemarvin** [comment]
To make things easier for automation, we need to make sure that Dev Tools and GeckoConsole are ON for Debug builds and OFF for Release builds. This isn't a UI issue but something we need to account for when implementing the feature in FxR.

**Comment by cvan** [comment]
To pile on feature requests for the design exploration:

- It would be nice to expose the buildID by double-clicking on the version timestamp.
- It would be nice to add an auto-update mechanism for automatically checking, downloading, and installing the latest APK for the installed flavour. (This is quite a bit of work to add, so I have filed issue #295 for that.)

**Comment by nancyhang** [comment]
@thenadj

**Comment by thenadj** [comment]
We're on it!

**Comment by avrignaud** [comment]
Additional fields required for Desktop site functionality testing:

- [ ] Dev Options: Toggle between mouse/touch events, toggle between desktop/mobile site rendering, set pixel ratio for window (added to https://github.com/MozillaReality/FirefoxReality/issues/283)

**Comment by cvan** [comment]
> - [ ] Dev Options: Toggle between mouse/touch events, toggle between desktop/mobile site rendering, set pixel ratio for window

@avrignaud: Gecko should be already synthesising `click` events from `touch*` events. Is something amiss here?

**Comment by cvan** [comment]
> toggle between desktop/mobile site rendering

:+1: @larsbergstrom filed this as issue #19

> set pixel ratio for window

:+1: @bluemarvin filed this as issue #318

<hr>

@thenadj - these designs look *splendid*! nice work, everyone. excited to play with this wand in action :+1:

**Comment by avrignaud** [comment]
Working on clarifying developer options. Please review the list below and give feedback. Thanks!

**Enable Remote Debugging** (toggle box)
**Show JS Console Logs** (toggle box)
**Enable Environment Override** (toggle box)
**Request Desktop Version of web pages** (toggle box)
**Select Mouse or Touch Events** (toggle between "Mouse"/"Touch" values - Default Touch to start)
**Set Display Density** (enter in value greater than 1 - 1.0, 1.5. 2, etc) - RESTART REQUIRED, so will need prompt to confirm or cancel
**Set Window Size** (enter in desired resolution value - 1024x768)

**Comment by cvan** [comment]
what does `Show JS Console Logs` do? redirect `console` logs to `adb logcat`?

Remote Debugging enables a lot of this: logging JS, debugging JS, inspecting network requests, etc. so that's great to have.

which of these are enabled by default - and for the non-boolean fields, what are the text defaults or field placeholder text?

**Comment by thenadj** [comment]
We got a design and it's attached. Please note that the settings dialog has an an entry button into the dev options dialog. Also the settings dialog can scale and we took it out of it's container. @keianhzo Slack me if you have specific questions, happy to go over any details with you. 
[UIS-39 Developer Options Panel_002.pdf](https://github.com/MozillaReality/FirefoxReality/files/2285333/UIS-39.Developer.Options.Panel_002.pdf)

**Comment by thenadj** [comment]
Updates to settings UIS which is related to this. 
[UIS-16 Settings_011.pdf](https://github.com/MozillaReality/FirefoxReality/files/2285337/UIS-16.Settings_011.pdf)
@nancy Not sure if Settings needs a separate ticket. They are related and should be addressed at the same time.

**Comment by keianhzo** [comment]
@thenadj I'll need SVGs for the radio button (selected/not selected) and the developer options settings icon.

**Comment by nancyhang** [comment]
@thenadj The settings panel was completed sprints ago, https://mozillaresearch.atlassian.net/browse/CXB-179?jql=text%20~%20%22settings%20panel%22

What specific changes are being made to the settings panel?

**Comment by keianhzo** [comment]
@nancyhang There is a new button to open the Developer options panel.

**Comment by nancyhang** [comment]
Ok, lets leave that in this ticket. @keianhzo @thenadj

**Comment by thenadj** [comment]
@keianhzo Attached are the SVGs for the design. 
[SVGs.zip](https://github.com/MozillaReality/FirefoxReality/files/2288014/SVGs.zip)

**Comment by thenadj** [comment]
@keianhzo 
During our last design review we learned that we can't darken the browser window in v1 as per our last settings dialog design. So here is a new design with an alpha channel background behind the settings dialog buttons. 
[UIS-16 Settings_012.pdf](https://github.com/MozillaReality/FirefoxReality/files/2299859/UIS-16.Settings_012.pdf)
