### ISSUE TITLE
[Pico] The order of the buttons from the Hamburger menu differentiates from the other devices

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2837]
**[Affected Versions]:**
- Firefox Reality 9 RC 2 (37ac4cbd)

**[Affected Platforms]:**
- Pico Neo 2 - Android - 8.1.0

**[Prerequisites]:**
- The headset is turned on.

**[Steps to reproduce]:**										
1. Open the app.
2. Click the Hamburger button.
3. Observe the order of the buttons from the Hamburger menu.

**[Expected results]:**
- The same order is displayed for all devices.

**[Actual results]:**
- The "Send Tab to Device" button is at the top on the Pico device and the "Resize Window" on the other devices.

**[Notes]:**
- Attached is a screenshot with the differences:
![Untitled](https://user-images.githubusercontent.com/40061643/75051945-72dcdb80-54d7-11ea-9b2e-5990ac5720b3.png)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9 RC4 (c64365e3) installed on the Pico Neo2 headsets.
Now, the buttons from the Hamburger menu are in the correct order.
