### ISSUE TITLE
When playing streaming videos on https://video.friday.tw , FxR (user-agent mode: desktop) displays the green/black/Mosaic screen after 2~5 seconds playback. 

### ISSUE THREAD

**Issue by kaipinglee** [MozillaReality/FirefoxReality#2844]
## Configuration

Firefox Reality version: v8.1
Firefox Reality build ID: 

Hardware: Vive Focus plus

## Steps to Reproduce

1. Switch FxR to user-agent mode: desktop.
2. Visit https://video.friday.tw.
3. Sign-in an account for testing (Test account: kaiping.li@gmail.com, password:fetfet87)
4. Visit https://video.friday.tw/movie/detail/26292 then play the video.
5. After playing the video 2~5 seconds, the green/black/Mosaic screen displayed in the HTML5 player.
Refer to the attached video: https://drive.google.com/open?id=1wDLafmOCxDyhBPmX6zpN0U0IUGwb5bXw

## Current Behavior

The user can't watch the video after the screen changes to green/black/Mosaic.

## Expected Behavior

The user is able to watch the video normally.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by MortimerGoro** [comment]
I'm getting this error after log in and trying to play the video:

影片授權僅限於台灣地區播放

`Video authorization is limited to Taiwan`

Any workaround to bypass this limitation?

**Comment by kaipinglee** [comment]
That means the video is available in Taiwan region only.
Suggest using VPN App on a mobile phone, connect to a Taiwan server and hotspot the WIFI to HMD.
FlyVPN is free to trial, download here: https://www.flyvpn.com/en/download

**Comment by kaipinglee** [comment]
I can communicate with Friday video to grant static IP access for Mozilla as well.

**Comment by MortimerGoro** [comment]
I was able to reproduce the issue using a VPN.

I think it's a Gecko bug because it happens on different devices. I created this bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1617929

**Comment by kaipinglee** [comment]
This issue does not exist in Firefox Reality 1.3.2 according to the latest test from HTC.
https://github.com/MozillaReality/FirefoxReality/releases/tag/1.3.2%2Bwavevr

**Comment by bluemarvin** [comment]
@MortimerGoro The Bugzilla issue has been closed. Can you retest with the latest version of GeckoView?

**Comment by MortimerGoro** [comment]
I just tested it and the issue has been fixed
