### ISSUE TITLE
1.	FxR displays the stereo rendering screen instead of the normal screen when Mirascast from HDM.

### ISSUE THREAD

**Issue by kaipinglee** [MozillaReality/FirefoxReality#2845]
## Configuration

Firefox Reality version:  v8.1
Firefox Reality build ID: 

Hardware: Vive Focus plus

## Steps to Reproduce

1. Open the Miracast feature on Vive Focus plus.
2. Project HMD screen to a TV/LCD monitor.
3. Launch FxR
4. Check the projected FxR screen on the TV/LCD monitor.

## Current Behavior

FxR displays the stereo rendering screen on the TV/LCD monitor.
Refer to the attached screen: https://drive.google.com/open?id=1Ss2qZGJmltN8O5VPfZ8MvSECs_VActXP

## Expected Behavior

FxR displays the normal screen on the TV/LCD monitor as the early version FxR v1.3.3.
Refer to the attached screen: https://drive.google.com/open?id=1MxxvXX2pAIzHyP6q-s_-ehlFcNCZU1Ao

## Error Logs and Stack Traces

https://drive.google.com/open?id=1AowCevzTH3qimtHXzZHoLUkdsQkPOB_i
<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
Is there an API that has been added? We don’t do anything special to support miracast. So if something changed, it is on the system side.

**Comment by kaipinglee** [comment]
HTC got consumer complaints about FxR Miracast issue recently on Vive Focus and iQiyi headsets.
HTC engineering team suggested removing the duplicate virtual display added to fix thisMiracast issue. (Refer to below error log)

05-26 02:09:09.607  1377  1392 I DisplayManagerService: Display device added: DisplayDeviceInfo{"OffscreenViews": uniqueId="virtual:org.mozilla.vrbrowser,10009,OffscreenViews,0", 16 x 16, modeId 3, defaultModeId 3, supportedModes [{id=3, width=16, height=16, fps=60.0}], colorMode 0, supportedColorModes [0], HdrCapabilities null, density 560, 560.0 x 560.0 dpi, appVsyncOff 0, presDeadline 16666666, touch NONE, rotation 0, type VIRTUAL, state ON, owner org.mozilla.vrbrowser (uid 10009), FLAG_PRIVATE, FLAG_NEVER_BLANK, FLAG_OWN_CONTENT_ONLY}

**Comment by bluemarvin** [comment]
FxR uses the virtual display to render UI. We have already made the changes previously requested here: https://github.com/MozillaReality/FirefoxReality/issues/1356
Completely removing the virtual display is not possible.
