### ISSUE TITLE
[Tabs] A white flickering line is displayed at the top and bottom borders of the thumbnails

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2849]
**[Notes]:**
- The white line is more visible when the thumbnails are selected and scrolled but they are slightly visible in normal view also, cutting the borders of the thumbnails.

**[Affected Versions]:**
- Firefox Reality 9 RC3 (18aba8b).

**[Affected Platforms]:**
- Pico Neo 2 - Android - 8.1.0
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the app is opened.
- Have multiple tabs opened.

**[Steps to reproduce]:**										
1. Click the View Tabs button.
2. Click the "Select" button.
3. Click the "Select All" button.
4. Scroll the page and observe the thumbnails.

**[Expected results]:**
- They are displayed correctly.

**[Actual results]:**
- A white flickering line is displayed at the top and bottom borders.

**[Additional Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1N5gbBFPqkISJXkcposUOpj_-a1mhvW37).

**Comment by bluemarvin** [comment]
@daron-walters Will you have a PR ready for code freeze next week or should we move this to v12?

**Comment by daron-walters** [comment]
move to v12
