### ISSUE TITLE
Refactor FxR use of VRExternalShmem for Immersive Mode

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#285]
From @kearwood 

- Do not assume that there are any layers.  Always check that VRLayerState.type is equal to LayerType_Stereo_Immersive before accessing VRLayerState.layer_2d_content
- I’d suggest always doing the same thing when pushing and pulling state from the browser, and avoiding any logic in the PullBrowserState function that does anything other than update the struct.  (eg, the code that un-pauses the compositor is in the PullBrowserState function)
- Don’t assume that only one action will need to be taken in response to an updated browser state.  If you are blocking until a new frame is submitted, you will likely miss other signals, such as the user stopping VR presentation or navigating to another page.  This can lead to deadlocks.
- Using condition variables is a good idea, but perhaps we should be broadcasting (pthread_cond_broadcast rather than pthread_cond_signal).
- I’d suggest always using a condition variable when pushing and pulling state between Gecko and FxR, not just in some calls.  It should be up to the code that pulls the state to check the updated state for all changes that need to be acted on, and not just the particular condition it was waiting for.
- The VRBrowserState and VRSystemState structs should not be memcpy’ed from the shmem unless the mutex is actually locked.

**Comment by MortimerGoro** [comment]
Closed via #328
