### ISSUE TITLE
FxR constantly pop-up error reporting dialog when browsing web-sites.

### ISSUE THREAD

**Issue by kaipinglee** [MozillaReality/FirefoxReality#2851]
## Configuration

Firefox Reality version:  v8.1
Firefox Reality build ID: 

Hardware: Vive Focus plus

## Steps to Reproduce

1. Visit websites with FxR
2. https://racetravel.glhc.site/ctsp_web/ and https://www.youtube.com/ in this case.
3. Sometimes FxR pop-up error reporting dialog during browsing.

## Current Behavior

FxR pop-up error reporting dialog for the user to report issues.
refer to attached screenshots:
https://drive.google.com/open?id=1A-DtMQC3wIq2PzD-KFouhIOnnDAT0Sov 
https://drive.google.com/open?id=1G9AvR3bWIwRBgapqEfYZoft-Mi7uGFx3

## Expected Behavior

User is able to visit websites normally.

## Error Logs and Stack Traces

https://drive.google.com/open?id=1moQ__BO9cL2OgMCJ7HfWhqjq7R04Rz1h 
https://drive.google.com/open?id=1Vxou5_lHW2AhdXqkbMRUjVGxilwSUF3g
<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
Those are crash reports. If you submit them, the URL to view them is included in the logcat. It would be most helpful if the link to the crash report was included. If you are seeing them while browsing that would imply that multiprocessing has been turned on. Multiprocessing should not be enabled by default in FxR currently as there are known issues we are still trying to reslove.

**Comment by bluemarvin** [comment]
Please provide step to reproduce. I have visited both listed sites with v8.1 on a Focus Plus and have not been able to reproduce any crashes.

**Comment by bluemarvin** [comment]
Additionally, including submitted crash reports would help in diagnosing any issues.

**Comment by bluemarvin** [comment]
Close since no actionable information has been provided.
