### ISSUE TITLE
Firefox window does not keep at the front but at the back after suspend resume HMD.

### ISSUE THREAD

**Issue by kaipinglee** [MozillaReality/FirefoxReality#2852]
## Configuration

Firefox Reality version: v8.1
Firefox Reality build ID: 

Hardware: Vive Focus plus

## Steps to Reproduce

1. Launch FxR.
2. Take off the HMD to suspend.
3. Put-on HMD to resume.
4. Sometimes FxR main window does not keep at the front.

## Current Behavior

FxR main window does not keep at the front after suspend resume HMD.
refer to the attached screen:
https://drive.google.com/open?id=1cmoTHoi6OgExWAr14VqRDT7ckEENkFo7

## Expected Behavior

FxR main window keep at the front after suspend resume HMD.

## Error Logs and Stack Traces

https://drive.google.com/open?id=1XA8e8x9uc25vc_RsYPZLerAv8vm1XLwX
<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
Long pressing the button on the grip will reset the windows. So far I have not been able to reproduce this issue in v8.1

**Comment by bluemarvin** [comment]
Closing due to lack of actionable information.
