### ISSUE TITLE
The app crashes after clicking the History or Bookmarks buttons if the app was closed while the library menus where open

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2854]
**[Notes]:**
- I was also able to reproduce this crash with the same ID once on Oculus Go and Pico Neo 2, while dismissing the libraries when verifying issue #2794, but I don't have the exact STR and it's hardly reproducible.

**[Affected Versions]:**
- Firefox Reality 9 RC3 (18aba8b)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**										
1. Click the History button from the menu tray.
2. Hold the Vive button until the app is forced closed.
3. Reopen the app.
4. Click the History button 2 times.
5. Observe the behavior.

**[Expected results]:**
- The History library is closed and reopened.

**[Actual results]:**
- The app crashes.

**[Additional Notes]:**
- This issue is also reproducible with the Bookmarks library.
- I was not able to reproduce this issue using the steps above on Oculus and Pico devices.
- Attached are a screen recording, the logcat an the crash report of the issue: 
	- Screen Recording: [link](https://drive.google.com/open?id=1UADHn5J4RR4aB7JtPS99FTFGCIHWO4sH).
	- Crash Report: [link](https://crash-stats.mozilla.com/report/index/0169d1cd-54cf-4b76-96b5-02ca50200225).
	- Logcat: [link](https://drive.google.com/open?id=1YbW2dlkaqxNpI7ZRdBeQ_YSl7iDDzynU).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9 RC4 (c64365e3) installed on the Oculus Go, Quest, HTC Vive Focus, Focus Plus and Pico Neo2 headsets.
Now, the app doesn’t crash after clicking the History or Bookmarks buttons if the app was closed while the library menus were open.
