### ISSUE TITLE
[Private Browsing] The hover and pressed states of the awesomebar ”Clear”, “Bookmark this page” and “Voice Search” buttons use the normal browsing color scheme

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2856]
**[Affected Versions]:**
- Firefox Reality 9 RC 3 (18aba8be)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- Pico Neo 2 - Android - 8.1.0

**[Prerequisites]:**
- The headset is turned on, the browser is installed and open.

**[Steps to reproduce]:**                                        
1. Click the PB button from the menu tray.
2. Hover the Bookmarks awesomebar button and observe it.
3. Long click the same button and observe its click state.

**[Expected results]:**
- The color scheme of the button is the one of the Private Browsing mode.

**[Actual results]:**
- The color scheme of the button is the one of the normal mode.

**[Notes]:**
- Related to issue #2508.
- This is reproducible for the “Clear” and “Voice Search” (only hover state) buttons as well.
- The Pop-up Blocked button uses the normal browsing scheme as well.
- Attached is a screenshot of the issue.
![pb ui 2](https://user-images.githubusercontent.com/53752296/75249932-e6386300-57df-11ea-9845-b39d1c64ef56.png)

**Comment by heres-maria** [comment]
This issue is partially fixed in the Firefox Reality version 9 RC4 build. 
While the "Pop-Up Blocked" notification is displayed, the color scheme of the awesomebar button for pop-ups retains the normal browsing color scheme.
![image](https://user-images.githubusercontent.com/53752296/75431504-99769880-5955-11ea-8c98-46de96417358.png)
Tested on Pico Neo 2 (Android - 8.1.0), Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).

**Comment by keianhzo** [comment]
@heres-maria I see the correct colors in the popup button, the same as the microphne and clear. What's exactly wrong in the color scheme?

**Comment by heres-maria** [comment]
@keianhzo The color scheme for the pop-up button uses black for the lines in the hover state, but only while the blue pop-up notification is on screen. The button has the correct color scheme otherwise.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 11-141770117 - 68128fbe installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the Private Browsing hover and pressed states of the awesomebar buttons use the correct color scheme.
