### ISSUE TITLE
[Intermittent] Youtube ads are wrongly played in immersive mode

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2857]
**[Notes]:**
- As a side effect of this issue the video takes longer to be displayed correctly in immersive mode and goes trough some UI rendering problems in the process.

**[Affected Versions]:**
- Firefox Reality 9 RC3 (18aba8b)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Quest - Android 7.1.1
- Pico Neo 2 - Android - 8.1.0

**[Prerequisites]:**
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**										
1. Open a 360 video on the Youtube website.
2. Click the video while the ad is displayed.
3. Observe the behavior.

**[Expected results]:**
- The video is not played in immersive mode until the add is dismissed.

**[Actual results]:**
- The video is played in immersive mode displaying the add.

**[Additional Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1_o1aTUxg4bgUP09bTW-gdQDmYor19ZlT).

**Comment by bluemarvin** [comment]
We don't currently have a mechanism to detect if youtube is playing an ad or content.

**Comment by MortimerGoro** [comment]
The new Gecko MediaSessionAPI is going to contain a `skipAd` method. I'd hold on researching this issue until that API is ready
