### ISSUE TITLE
Come up with a better repository description than "Simple VR Browser"

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#286]
The current repository description is left over from when it was called VRBrowser and was only a demo to show how to integrate GeckoView into a 3D environment. We probably need a better description now.

**Comment by cvan** [comment]
> A fast and secure browser for standalone virtual-reality and augmented-reality headsets.

?

**Comment by bluemarvin** [comment]
Okay, I'll update it with this. If there are objection we can alway change it again.
