### ISSUE TITLE
[Pico] The Foeviation Level (app) option is not available in the Display card

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2860]
**[Affected Versions]:**
- Firefox Reality 9 RC3 (18aba8b)

**[Affected Platforms]:**
- Pico Neo 2 - Android - 8.1.0

**[Prerequisites]:**
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**										
1. Open the Display card from Settings.
2. Observe if the Foeviation Level (app) option is display under the "Homepage" option.

**[Expected results]:**
- The option is displayed.

**[Actual results]:**
- The option is NOT displayed.

**[Notes]:**
- Attached is a screen shot of the issue:
![Tue02-25-2020_17-03-43 15](https://user-images.githubusercontent.com/40061643/75259858-5c919100-57f1-11ea-99b7-b5ed3f6d5665.png)

**Comment by bluemarvin** [comment]
Foeviation Is not supported on pico devices yet.
