### ISSUE TITLE
Lighting fails to be restored after closing history or bookmarks.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#2868]
## Configuration

Firefox Reality version: v9
Firefox Reality build ID: 73113ea36c1a3f5917bae9f135f9c7631b0941fa

Hardware: All

## Steps to Reproduce

1. Open history or bookmarks.
2. Close history or bookmarks.

## Current Behavior

Environment stays dimmed.

## Expected Behavior

Environment should return to default lighting levels.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9 RC4 (c64365e3) installed on the Oculus Go, Quest, HTC Vive Focus, Focus Plus and Pico Neo2 headsets.
Now, the lighting is restored after closing the Bookmark or History Views.
