### ISSUE TITLE
[HTC] The three foveation levels cause visible visual effects in the field of vision

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2873]
**[Affected Versions]:**
- Firefox Reality 9 RC 3 (18aba8be)
- Firefox Reality 8.1 (a0fcc8a3)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on, the browser is installed and open.
- You have three windows open.

**[Steps to reproduce]:**                                        
1. Open the “Display” card from Settings.
2. Change the “Foveation Level (App)” to “3”.
3. Observe the behavior.

**[Expected results]:**
- The visible field of vision is not observably affected by the foveation levels.

**[Actual results]:**
- The low quality of the periphery of the visible field of vision is observable.

**[Notes]:**
- While this issue is not very observable when only one window is open, it becomes disruptive when two or three windows are open.
- This issue is reproducible for all three foveation levels, increasingly observable with the increase of the level.
- This issue is reproducible in production.
- This issue is not reproducible on the Oculus Go or Oculus Quest.
- Attached is a [recording](https://drive.google.com/file/d/1jctaRZybG5i7ThIE4wOSUgOVqOKzPftg/view?usp=sharing) of the issue.

**Comment by MortimerGoro** [comment]
@heres-maria we have deciced we are going to remote foveation level from FxR, we don't really need it. And we don't need the extra effort of testing all the cases.

Can you make sure that foveation level testcases are removed from QA too?

**Comment by Softvision-RemusDranca** [comment]
@MortimerGoro Maria has shift to Ecosystem QA team's tasks. I'll make sure that the test cases related to foveation level are removed. Thanks!

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the Firefox Reality version 10-40720037 (dbb8ed3a). The Foveation level option is now removed from Settings.

Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2), HTC Vive Focus (Android 7.1.2) and Pico Neo 2 (Android 8.1.0).
