### ISSUE TITLE
Crash when pausing the activity with suggestions bar visible

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#2875]
https://crash-stats.mozilla.com/report/index/90c31fdc-75ae-4604-a2be-0e01d0200226

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9 RC4 (c64365e3) installed on the Oculus Go, Quest, HTC Vive Focus, Focus Plus and Pico Neo2 headsets.
Now, the pausing the activity with the awesomebar suggestions visible does not crash the app.
