### ISSUE TITLE
Crash on HTC after pause resume.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#2877]
## Configuration

Firefox Reality version: c64365e3783a6124cbe49ce3eb8661653669a980
Firefox Reality build ID: v9

Hardware: HTC

## Steps to Reproduce

1. TBD
2.
3.

## Current Behavior

crash after resume:
https://crash-stats.mozilla.com/report/index/4393ba14-da4c-41f6-a003-96c300200225
## Expected Behavior

FxR should not crash on resume.

**Comment by MortimerGoro** [comment]
Fixed via #2884
