### ISSUE TITLE
Scrolling offset is applied to all page loads in a session

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#2878]
## Configuration

Firefox Reality version: v9
Firefox Reality build ID: c64365e3783a6124cbe49ce3eb8661653669a980

Hardware: All

## Steps to Reproduce

1. Scroll page.
2. Pause FxR
3. Kill FxR
4. Relaunch FxR
5. Click home button.

## Current Behavior

Home page is scrolled the same as the restored page. Any new page visited will also be scrolled by this amount.

## Expected Behavior

New page loads should not be affected by previous pages state.

## Notes
Caused by c494e335e5ad41a44dfd9fdd51c86eeb8e19a8a0
Blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1618265

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9 RC6 (abe931f6) installed on the Oculus Go, Quest, HTC Vive Focus, HTC Vive Focus Plus and Pico Neo2 headsets.
Now, the scrolling offset is not applied to all page loads in a session.
