### ISSUE TITLE
"Caps Lock" key should behave like a "Shift" key does

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#288]
## Hardware
VR Browser: Firefox Reality
VR Device: Oculus Go
Build ID: OTBk7afrRu2nW81w0kOyBA
Build Date: 2018-07-31

## Steps to Reproduce
1. Load a 2D site that requires text input (e.g., `input[type=text]`, `input[type=password]`, `textarea`, etc.), such as https://google.com, https://facebook.com, https://sso.mozilla.com, etc.
2. Once you've clicked on or been focussed into an editable field, start typing text. For example, start by writing a English sentence, with an uppercased letter.
3. Notice you have to press the Shift/Caps-Lock key to capitalise the first letter and then again to lowercase the next letter you type.

## Actual Behavior
The keyboard's Shift/Caps-Lock key functions as just Caps Lock only.

![Shift Key in Firefox Reality](https://user-images.githubusercontent.com/203725/43494960-4d5119fc-94ea-11e8-9624-16e9b0e3b7e8.gif)

## Expected Behavior
The keyboard's Shift/Caps-Lock key should function as just Shift only.

## Recommendation
I tested the behaviour in Oculus Browser, and Oculus has only a Shift key, no Caps-Lock key.

![Shift key in Oculus Browser](https://user-images.githubusercontent.com/203725/43494861-b9ca7868-94e9-11e8-8380-947e2560f3a5.gif)

I'd recommend that we do the same: **have the Shift/Caps-Lock key function as a Shift key**.

**Comment by thenadj** [comment]
Single click of shift key should change characters to upper case for just one letter entry, then return back to lower case. On double click of shift key (we could also add long hold), capitol letters get locked in until shift key is pressed again to release lock. Icon for shift key should change to up arrow with single line below arrow to indicate cap letter lock.

**Comment by thenadj** [comment]
Caplock icon attached.
[icon-keyboard-shift-caplock.svg.zip](https://github.com/MozillaReality/FirefoxReality/files/2247591/icon-keyboard-shift-caplock.svg.zip)
