### ISSUE TITLE
Crash on pause/resume on HTC

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#2881]
## Configuration

Firefox Reality version: c64365e3783a6124cbe49ce3eb8661653669a980
Firefox Reality build ID: v9

Hardware: HTC

## Steps to Reproduce

1. Launch FxR
2. Pause
3. Resume
4. Goto 2.

## Current Behavior

FxR will eventually fail to launch and only shows a blank screen. Eventually it will crash with the following stack trace:
https://crash-stats.mozilla.com/report/index/d63799c9-dcf7-46c4-b46b-616930200227

## Expected Behavior

FxR should not crash.

## Notes
I have been able to reproduce this in v8.1. It seems to happen quicker when you run other applications between pausing and resuming FxR. I used FxR 1.3.2 and would play videos in it between pausing and resuming.

**Comment by Softvision-RemusDranca** [comment]
I've retested this issue and it's still reproducible with the Firefox Reality 9 rc6 (abe931f) build. I've reproduced the issue in multiple attempts, by force stopping the app by using the Vive button and also by resuming the app after exiting it. Here is a [link](https://crash-stats.mozilla.com/report/index/e9a5b097-ddea-4614-b8c1-ba8ad0200302) to the crash report reproduced today on HTC Vive Focus device.  

Considering this I will reopen this issue.

**Comment by MortimerGoro** [comment]
@Softvision-RemusDranca can you test if this issue happens with UI hard acceleration disabled? (Settings-> Dev Options)

If turning of hardware ui fixes the issue we'll create a new RC with that enabled by default.

**Comment by Softvision-RemusDranca** [comment]
@MortimerGoro I've retested this scenario with the UI hard acceleration disabled and here are the results:
- HTC devices - The app did not crash after resuming the app the only issue encountered is the one where the app is frozen, issue #2880.
- Oculus devices - The app crashes after Quit/Resume while in immersive mode. Here is a [link](https://crash-stats.mozilla.com/report/index/f9cbd737-2dce-4192-b564-36a960200302).

Please take in consideration that I only had time to test this behavior for ~ 30 minutes, and there could be other issues that could occur, while having UI hard acceleration disabled.

**Comment by Softvision-RemusDranca** [comment]
@MortimerGoro I've retested this scenario with the UI hard acceleration disabled and here are the results:
- HTC devices - The app did not crash after resuming the app the only issue encountered is the one where the app is frozen, issue #2880.
- Oculus devices - The app crashes after Quit/Resume while in immersive mode. Here is a [link](https://crash-stats.mozilla.com/report/index/f9cbd737-2dce-4192-b564-36a960200302).

Please take in consideration that I only had time to test this behavior for ~ 30 minutes, and there could be other issues that could occur, while having UI hard acceleration disabled.

**Comment by bluemarvin** [comment]
The Oculus crash is a new crash in Gecko and is probably not related to the Hardware UI issue. Please file it separately.

**Comment by bluemarvin** [comment]
@Softvision-RemusDranca Does the whole application crash or is it just the content process. That's what it looks like in the crash report.

**Comment by Softvision-RemusDranca** [comment]
@bluemarvin I think that the content process crashes because the same session is restored after resuming the app. The crash prompt is displayed over the affected window and no data is lost. The app works as expected after dismissing it.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the Firefox Reality version 9 rc7 (b68f946). The app didn't crash after multiple attempts of pausing and resuming the app.

Tested on HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
