### ISSUE TITLE
The YouTube layout changes after closing and reopening/restarting the app

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2883]
**[Affected Versions]:**
- Firefox Reality version 9 RC4 (c64365e3)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- Pico Neo 2 - Android 8.1.0

**[Prerequisites]:**
- The headset is turned on and the browser is open.

**[Steps to reproduce]:**
1. Go to YouTube.
2. Change a setting that causes a restart prompt (e.g. Display -> DPI).
3. Choose the “Restart Now” option.
4. Observe the YouTube layout.

**[Expected results]:**
- The layout remains the same after restarting.

**[Actual results]:**
- The layout completely changes after restarting.

[Notes]:
- Trying to use the website in the new layout will return an “Invalid response received” error.
- The issue is also reproducible when closing the app and subsequently using the “force-stop” adb command before reopening it.
- Reloading the page fixes this issue.
- Related to #2557.
- Attached is a [recording ](https://drive.google.com/file/d/1Dqe4J0rI2c-w6bDo-Lbtc-Ms38J1z950/view?usp=sharing)of the issue.

**Comment by bluemarvin** [comment]
You can't change the DPI and not affect the layout. If I switch between multi processing on and off which requires a restart, I don't see this issue.

**Comment by bluemarvin** [comment]
We should remove most of the display settings as users should not be changing them.

**Comment by heres-maria** [comment]
@bluemarvin I looked into this a bit more and it seems this bug is not reproducible with Multiprocess turned on. 

With "Enable Multiprocess" turned off this bug is reproducible for the developer settings that require a restart ("Enable Debug Logging" and "Enable UI Harware Acceleration") as well.

With this setting on, none of the setting restarts, nor closing the app as described in the second note of the original report, led to the faulty behavior.

Switching from one state of the setting to the other (starting with multiprocess off) will not reproduce the issue (though the site will display a blue message twice about being redirected to the desktop site). 
But starting with "Enable Multiprocess" on and then turning it off will cause this behavior for the first time, after which the bug is not reproducible due to turning the setting on.

**Comment by bluemarvin** [comment]
If this is only reproducible when multiprocess is turned off then I don't know that it will get fixed. The multiprocess option will be removed in v10 as disabling multiprocess is just not being supported in GeckoView.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using Firefox Reality version 11-141402320 (eda7d95). Now, the same layout is displayed for the YouTube website after closing and reopening/restarting the app.

Tested on HTC Vive Focus (Android 7.1.2) and Oculus Quest (Android 7.1.1).
