### ISSUE TITLE
[Oculus Quest] The app freezes when opening an existing tab or switching tabs when the libraries are opened

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2890]
**[Notes]:**
- If the app is closed and reopen a black screen is displayed, the device menu is broken, until the device message is display informing that the Firefox Reality is unresponsive (this could take up to 5 minutes).

**[Affected Versions]:**
- Firefox Reality 9 RC 4 (c64365e3)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on, the browser is installed and open.
- Have 2 windows opened, and multiple tabs.

**[Steps to reproduce]:**                                        
1. Click the "History" button.
2. Click the "Tabs View" button.
3. Select a different tab than the one opened.
4. Observe the behavior.

**[Expected results]:**
- The tab is correctly displayed.

**[Actual results]:**
- The app freezes and nothing is actionable.

**[Additional Notes]:**
- After the app can finally be opened, all open tabs/windows in the previous session are lost.
- Attached are screen recordings of the issue:
	- Open existing tab: [link](https://drive.google.com/open?id=1CwL_mpMpB_e5P66ZoPhb6at4eO2yjVUp).
	- Switch tabs active window: [link](https://drive.google.com/open?id=1P7-8RZqYomaGViJIXL_ruWmT65-gtffV).

**Comment by bluemarvin** [comment]
Fixed by #2891

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the v9 RC5 (3e30ba6) build. The app no longer freezes when opening an existing tab or switching tabs while the libraries are opened.
However, the wrong URL is displayed in the affected window when switching tabs while a library is opened. This behavior is added as a note in issue #2889.
Tested on Oculus Quest.
