### ISSUE TITLE
Support files downloading

### ISSUE THREAD

**Issue by Papooch** [MozillaReality/FirefoxReality#2892]
The only thing that is stopping me from using FxR as my main browser on the Oculus Quest is the inability to download files. When I go to a file URL, nothing happens, idk if it's a bug or it is not supported, as I haven't found any information on it.

The Oculus built in browser doesn't support copy/paste, so that makes downloading files even trickier.

I would love to see this feature implemented in Firefox Reality.

**Comment by bluemarvin** [comment]
We haven't added this yet but it is something we hope to support it.

https://github.com/MozillaReality/FirefoxReality/issues/672
