### ISSUE TITLE
[Intermittent] Websites can not be scrolled if navigated to from an allowed pop-up blocked page

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2897]
**[Note]:**
- The same issue as #2789, rereported due to change in the default state of "Enable Multiprocess".
- This issue was not reproducible in 100% of cases on www.popuptest.com. The Mouseover Popup seems to be the one for which it is the most reproducible.

**[Affected Versions]:**
- Firefox Reality 9 RC 1 (33f6c4d)
…
- Firefox Reality 9 RC 5 (3e30ba6e)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2
- Pico Neo 2 - Android - 8.1.0

**[Prerequisites]:**
- The headset is turned on, the browser is installed and open.
- The "Block Pop-Up Windows" option is disabled.

**[Steps to reproduce]:**
1. Open a page that uses pop-ups.
2. Trigger the pop-up or wait for it to be triggered.
3. In the same tab as the pop-up, navigate to a website.
4. Try to scroll the page and observe the behavior.

**[Expected results]:**
- The page can be scrolled.

**[Actual results]:**
- The page can not be scrolled.

**[Additional Notes]:**
- The issue is also reproducible if the "Block Pop-Up Windows" option is enabled and a pop-up technique is allowed.
- Attached is a [recording ](https://drive.google.com/file/d/1MNkFWartTfse0QjVM2xn8kc5WhDYvbA3/view?usp=sharing)of the issue.

**Comment by bluemarvin** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1616063

So far we have not been able to get this issue escalated in Gecko.

**Comment by keianhzo** [comment]
Will be fixed for v10 after https://bugzilla.mozilla.org/show_bug.cgi?id=1616063 is available.

**Comment by bluemarvin** [comment]
Per the comment on bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1610338#c6 this behavior is actually the expected behavior. If a window is opened via a pop up as not scrollable as is done by popuptest.com then nothing maybe scrolled that is opened in that window.

**Comment by bluemarvin** [comment]
I've opened https://bugzilla.mozilla.org/show_bug.cgi?id=1620085

If we know what the window features are, we can adjust the UI to accommodate.

**Comment by Softvision-GeluHaiduc** [comment]
So popuptest.com is opening only some windows as not scrollable and that makes it intermittent, right?

**Comment by bluemarvin** [comment]
Right, it depends on what window traits are used to open the window. popuptests is sometimes setting scrollbars=no which makes the window not scrollable. So unfortunately the popups are working as designed. If we were provided with the window state we could adjust the UI but there isn't a priority to fix this currently in GeckoView.
