### ISSUE TITLE
[Oculus][Intermittent] The crash prompt is displayed when quitting and resuming the app while in immersive mode

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2905]
**[Notes]:**
- The app works as expected after dismissing the prompt, the video can be replayed.
- The issue is reproducible with the UI hard acceleration option disabled OR enabled (please see [comment](https://github.com/MozillaReality/FirefoxReality/issues/2881#issuecomment-593481439)) .

**[Affected Versions]:**
- Firefox Reality version 9 rc7 (b68f946)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to a 360 video and play it in immersive mode.
2. Press the Oculus button.
3. Click the Quit button.
4. Reopen the app and observe the behavior.

**[Expected results]:**
- The app is reopened correctly.

**[Actual results]:**
- The crash prompt is displayed.

**[Notes]:**
- I could only reproduce this issue after multiple attempts.
- Attached is the crash report of the issue: [link](https://crash-stats.mozilla.com/report/index/a62938cc-a457-4a22-a252-9e8770200303).

**Comment by bluemarvin** [comment]
Can this still be reproduce? It was supposedly fixed in gecko 75: https://bugzilla.mozilla.org/show_bug.cgi?id=1615832
All of our crash reports for this issue are in 75 as well.

**Comment by Softvision-RemusDranca** [comment]
@bluemarvin I've retested this issue and the crash prompt is still displayed after resuming the app with the same steps.
However. they have different IDs from the one in the past and also between devices:
    - On Oculus Quest: [crash](https://crash-stats.mozilla.com/report/index/8cdff594-1194-43d2-a3c7-eccde0200401).
    - On Oculus Go: [crash](https://crash-stats.mozilla.com/report/index/588b74ae-59bf-4dc8-aa56-953ee0200401).
Should I open a new issue or one for each device since there are different IDs and close this one or should keep this one opened?

**Comment by bluemarvin** [comment]
Yes, those are different crashes. Please file each crash as it's own bug. Thanks.

**Comment by Softvision-RemusDranca** [comment]
I've retested this with the Firefox Reality version 10-140922050 (de88941) build. Only the crash report received was the one mentioned in the above comment on the Oculus Quest device, and I was also able to reproduce the issue on the HTC devices after force stop.
Considering this I will close this issue and mark it as verified fixed and I also logged issue #3092 ,for tracking purpose.
