### ISSUE TITLE
Remove unsupported platforms.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#2911]
The following platforms are no longer supported and should be removed from FxR:  GoogleVR, SVR, and 32bit builds.

**Comment by philip-lamb** [comment]
We need to verify with our WaveVR partners that none of them are still using 32-bit before eliminating Wave 32-bit builds.

**Comment by keianhzo** [comment]
Waiting for HTC's response

**Comment by keianhzo** [comment]
unblocked, 32bits can be removed from all platforms
