### ISSUE TITLE
Remove Multiprocess switch from Developer panel.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#2912]
**Is your feature request related to a problem? Please describe.**
GeckoView is dropping support for non-e10s mode. Since we are now switched to e10s, the option to turn e10s off needs to be removed from FxR.

**Describe the solution you'd like**
Remove the switch from the developer panel.

**Comment by Softvision-RemusDranca** [comment]
I have verified this task on Firefox Reality version 10-40720037 (dbb8ed3a) and the Multiprocess option is correctly removed from the Developer panel. Also, the UI of the other options is not affected.

Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2), HTC Vive Focus (Android 7.1.2) and Pico Neo 2 (Android 8.1.0).
