### ISSUE TITLE
The content feed is grayed out in Oculus after pause/resume

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#2918]
1. Load the content feed (I couldn't reproduce it with other websites)
2. Click the Oculus power button to dim the screen
3. Click the Oculus power button to resume
4. The content feed background is greyed out until you point with the controller again

![screen](https://user-images.githubusercontent.com/1070794/75893438-18c30b00-5e33-11ea-9247-340812399bdf.png)

vs

![screen2](https://user-images.githubusercontent.com/1070794/75893451-1c569200-5e33-11ea-989a-14177f7de8cb.png)

**Comment by MortimerGoro** [comment]
I can't reproduce this in Oculus Browser so not sure yet if it's GV bug or a new content feed compat issue

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the Firefox Reality version 10-40720037 (dbb8ed3a). The content feed background is no longer grayed out after pause/resume.

Tested on Oculus Go (Android 7.1.2) and Oculus Quest (Android 7.1.1)
