### ISSUE TITLE
Allow users to change default search engine from Settings

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#292]
Google may not be a user's desired default.

**Comment by avrignaud** [comment]
Agree, but 1.0 we have to hardcode a default which will be Google. We are hoping to allow user selection of search engine in 1.1.

**Comment by cvan** [comment]
> Agree, but 1.0 we have to hardcode a default which will be Google.

Just to inform my design of the Content Feed and the designers' & implementers' work for the placeholder text for the URL bar (#358), I wanted to clarify whether we'll always be searching for Google.

I could be wrong in my interpretation of @larsbergstrom's [comment here](https://github.com/MozillaReality/FirefoxReality/issues/248#issuecomment-412278211); it sounds like we'll be following suit of Firefox's using different search providers based on the region.

> We are hoping to allow user selection of search engine in 1.1.

Assuming we do use the correct search provider based on the region, that makes sense and is fair to tackle in 1.1.

**Comment by cvan** [comment]
@keianhzo answered my question with his [`search_code` branch](https://github.com/MozillaReality/FirefoxReality/compare/search_code). please ignore my question above.

**Comment by cvan** [comment]
FYI: Samsung Internet Browser supports changing from a radio list (though not a custom URL obviously, à la OpenSearch).

**Comment by philip-lamb** [comment]
Needed for any deployment in China.
