### ISSUE TITLE
The FxA account is not connected if previously the email was added then quitting the app and entering the password after resume

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2933]
**[Affected Versions]:**
- Firefox Reality version 9 rc8 (9350b40).

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Quest - Android 7.1.1
- Pico Neo 2 - Android - 8.1.0

**[Prerequisites]:**
- The headset is turned on, the browser is installed and open.
- Have a valid FxA account.

**[Steps to reproduce]:**                                        
1. Click the "Sign Into Account" card from Settings.
2. Insert the FxA account email and click the Continue button.
3. Quit the app and reopen it.
4. Insert the FxA password and click Sign in button.
5. Observe if the account is connected.

**[Expected results]:**
- The account is connected.

**[Actual results]:**
- The account is not connected on the device even if the FxA page says that is connected.

**[Additional Notes]:**
- On the HTC and Pico Neo2 devices, the issue is reproducible only after force stopping the app.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1a6mrf1uIQ92LSTeoAkbenGMFBzSJx-hf).

**Comment by keianhzo** [comment]
A challenge is generated every time an authentication URL is created. Quitting the app makes the accounts service to lose track of that challenge and we get no authentication callbacks although the page is redirected to the success page. I guess we should at least get an error callback. I've asked the FxA team.

**Comment by Softvision-RemusDranca** [comment]
@keianhzo I observed that even the sessions that are opened in other windows are closed when reopening the app, not just the FxA login session. Is this intendeed?

**Comment by bluemarvin** [comment]
> @keianhzo I observed that even the sessions that are opened in other windows are closed when reopening the app, not just the FxA login session. Is this intendeed?

I think this should be fixed by #3205

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 10-141130836 (d3f3c9b). The FxA login session is now dismissed after resuming the app.

Tested on HTC Vive Focus (Android 7.1.2), Oculus Quest (Android 7.1.1) and Pico Neo 2 (Android - 8.1.0) devices.
