### ISSUE TITLE
Single quote symbol is placed in symbol keyboards duplicately.

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#2934]
## Configuration

Firefox Reality version: 10
Firefox Reality build ID: 

Hardware: Oculus Go, I think all other devices have the same issues.

## Steps to Reproduce

1. Switch to symbol keyboards, insert " ' " and " ` " from keyboards, you can see both of them will show " ' " in the text field.
2. Open `keyboard_symbols.xml`, `keyboard_symbols_xxx.xml`, we can see ASCII code 39 (single quote) is shown up at least two times, even though the `keyLabel` is not " ' " actually.

## Current Behavior

Keycode 39 (single quote) is shown up at least two times in every `keyboard_symbols_xxx.xml`, I believe the other one should be " ` " with ASCII code 96. For Russian and German symbol keyboards, I even see ASCII code 39 is shown up three times. We also get confused with " ' " (39) and " ´ " (239). The keyLabel is " ´ ", but its KeyCode is 39. I think we should unify KeyLabel to be " ' ".

## Expected Behavior

 We should unify KeyLabel " ´ " to be " ' ",  and its KeyCode is 39. Besides,  KeyLabel " ` " is ASCII code 96.

## Possible Solution

We might need to double-check with our design team to make sure if KeyLabel " ´ " on keyboards should to be " ' ".

## Context

Typing with wrong symbols is so awkwarding.

```
```

</details>

**Comment by daoshengmu** [comment]
@thenadj  Please help provide the UTF-8 code of 
<img width="44" alt="Screen Shot 2020-03-12 at 5 38 41 PM" src="https://user-images.githubusercontent.com/1263177/76579308-ee073100-6488-11ea-941a-570f6f28b213.png">

I saw this key from [UIS-63_Russian_Keyboard_009.pdf](https://github.com/MozillaReality/FirefoxReality/files/4327264/UIS-63_Russian_Keyboard_009.pdf) but I have no idea what the UTF-8 code of it.

**Comment by cjyjae35** [comment]
@daoshengmu The Unicode for that Russian keyboard symbol is U+2116 (https://www.fileformat.info/info/unicode/char/2116/index.htm).

Also, thank you for pointing out the single quote symbol issue. Have you made any changes to it yet? if you haven't yet, I will take a look at the keyboards and readdress the symbols.

**Comment by daoshengmu** [comment]
> @daoshengmu The Unicode for that Russian keyboard symbol is U+2116 (https://www.fileformat.info/info/unicode/char/2116/index.htm).
> 
> Also, thank you for pointing out the single quote symbol issue. Have you made any changes to it yet? if you haven't yet, I will take a look at the keyboards and readdress the symbols.

I have done some changes and given a PR at #2967. If you wanna readdress other issues that might not be found by me. That will be awesome. Please let me know if I need to give you a build.

**Comment by cjyjae35** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BUG-41 Keyboard Single Quote Symbols](https://trello.com/c/QvylwzDC/529-bug-41-keyboard-single-quote-symbols)

**Comment by daoshengmu** [comment]
> ![](https://camo.githubusercontent.com/193766a3b9959c5f4ed5cd8cf3251d015e839d51/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [BUG-41 Keyboard Single Quote Symbols](https://trello.com/c/QvylwzDC/529-bug-41-keyboard-single-quote-symbols)
> 
> @daoshengmu I created this document to specify the Unicode of every single quote & lookalike symbols. Please take a look and let me know if you have any questions.

@cjyjae35  There are two things I wanna confirm.
- The comma symbol in Zhuyin symbol keyboard, it looks like a full-width one (，). If so, its unicode should be 0xff0c instead of 0x002c.
- Please give an explanation of JPN symbol keyboard because I see you use Zhuyin to describe it.

Others are the same with our current master branch. We are good :)

**Comment by cjyjae35** [comment]
@daoshengmu Thank you for catching those :0 I updated the document based on your feedback for any future needs!

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10-140780019 (93eff892) installed on the Oculus Go, HTC Vive Focus Plus and Pico Neo2 headsets.
Now, the correct symbol is inserted when clicking the " ' " and " ` " symbols from the keyboard on all languages.
