### ISSUE TITLE
Remove temporary code to fix the GV Media request issue

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#2938]
This is already fixed in the current main with a temporary fix. When https://bugzilla.mozilla.org/show_bug.cgi?id=1621380 gets fixed we should remove that temporary patch.

Related to: https://github.com/MozillaReality/FirefoxReality/issues/2935

## Configuration

Firefox Reality version: 9
Firefox Reality build ID: d659400ae39ae827fff3b2eb7375309e729d4988

Hardware: HTC, Pico

## Steps to Reproduce

1. Navigate to a website that needs to access your camera permissions (ex: https://www.onlinemictest.com/webcam-test/).
2. Click the "Allow" button from the permissions prompt.
3. Observe the behavior.

## Current Behavior

The app crashes.

## Expected Behavior

An error message is displayed that the camera can't be accessed.

## Context

This is already fixed in the current main with a temporary fix. When https://bugzilla.mozilla.org/show_bug.cgi?id=1621380 gets fixed we should remove that temporary patch.

## Error Logs and Stack Traces

https://crash-stats.mozilla.com/report/index/582ec40e-d1b1-4f34-85b7-986290200310
<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
From the looks of the bugzilla report, we can remove the temporary code now?

**Comment by keianhzo** [comment]
it seems that this has regressed in v79, it's crashing again. I'll reopen the Bugzilla issue.
