### ISSUE TITLE
The last letters of the selected language options are not bolded in “Language Settings”

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2945]
**[Affected Versions]:**
- Firefox Reality version 10-40720037 (dbb8ed3a)
- Firefox Reality version 9 RC10 (324719fe)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Quest - Android 7.1.1
- Pico Neo 2 - Android - 8.1.0

**[Prerequisites]:**
- The headset is turned on, the browser is installed and open.
- Have “Language Settings” set to the default state.

**[Steps to reproduce]:**                                        
1. Open the “Language Settings” dialog from Settings.
2. Observe the last letter of the “Follow device language” strings.

**[Expected results]:**
- The last letters are bolded.

**[Actual results]:**
- The last letters are not bolded.

**[Notes]:**
- The issue is reproducible for “Voice Search Language” and “Display Language for App” for all the other languages except "English (US)".
- There is one case when this issue is reproducible for the “Voice Search Language” ("Italiano") option only when another language is selected for “Display Language for App” (e.g "Français"). 
- This issue seems to not be reproducible for the other “Preferred Language for Displaying Websites” options.
- This issue is not reproducible in production.
- Attached are a few screenshots of this issue:
![Screenshot_org mozilla vrbrowser_2020 03 12-15 19 03 1](https://user-images.githubusercontent.com/53752296/76528052-e2137300-6478-11ea-9cc1-9b2ef1ce5d1f.jpg)
![Screenshot_org mozilla vrbrowser_2020 03 12-15 25 37 1](https://user-images.githubusercontent.com/53752296/76527908-a5477c00-6478-11ea-98f7-79ebfa233b74.jpg)
![Screenshot_org mozilla vrbrowser_2020 03 12-15 43 00 2](https://user-images.githubusercontent.com/53752296/76528191-15560200-6479-11ea-9c40-95bb5a9d1739.jpg)

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 10-141010017 (5497036) build. The letters are now bolded.

Tested on Oculus Quest (Android 7.1.1), HTC Vive Focus (Android 7.1.2) and Pico Neo 2 (Android 8.1.0).

**Comment by daron-walters** [comment]
![org mozilla vrbrowser dev-20200409-121517](https://user-images.githubusercontent.com/1936826/78951939-dcbe3e00-7aa1-11ea-9e81-17eb5996ea19.jpg)
