### ISSUE TITLE
[Youtube] The video wrongly skips forward/backwards when double clicking the video's controls 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2947]
**[Affected Versions]:**
- Firefox Reality version 10-40720037 (dbb8ed3a)
- Firefox Reality version 9 rc10 (324719f).

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Quest - Android 7.1.1
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to Youtube.com and play a normal video.
2. Double click on the "Play" button.
3. Observe the behavior.

**[Expected results]:**
- The video is paused/played.

**[Actual results]:**
- The video skips back 10 seconds.

**[Notes]:**
- If the buttons from the right side of the video are double clicked the video skips forward with 10 seconds.
- This issue is also reproducible in theater mode.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1rcQJekufHSohvEVGPURVNXlTOK-xLw47).

**Comment by Softvision-RemusDranca** [comment]
I have retested this issue using Firefox Reality version 11-141402320 (eda7d95) and I can still reproduce the issue by double clicking the "Settings", "Play on TV" "CC" buttons, and also with the "Play/Pause" button if clicked in the upper-right corner of the icon.
This issue seems to be reproducible on the second attempt of double-clicking the buttons mentioned.
Tested on HTC Vive Focus (Android 7.1.2) and Oculus Quest (Android 7.1.1).

Considering this I will reopen this issue.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 11-141492311 (a9b58ee6) installed on the Oculus Go, Pico Neo2 and Pico G2 4K headsets.
Now, the video doesn’t skip forward or backward when double-clicking the video's controls.
