### ISSUE TITLE
How should major/minor/security updates for release/prod versions work?

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#296]
This is more of a question I am curious about. Can this be handled automatically by the app stores? I am not familiar yet with the various standalone VR app-store submission and update flows.

**Comment by bluemarvin** [comment]
All of the VR app stores appear to work like a standard mobile app store where updates are pushed to the device unless the user has disabled it. I don't know there is anything we need to do beyond publish an update to each store.

As for side loaded APKs, we probably don't want to have to support updates. If a user side loads, its going to have to be on them.

**Comment by larsbergstrom** [comment]
I agree. Even any preload scenarios would be updated via the VR app stores on those devices.
