### ISSUE TITLE
The three dot menu from History is wrongly displayed over the "Clear History" button when only two or one feeds are available

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2960]
**[Affected Versions]:**
- Firefox Reality version 10-40730015 (b958efb)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Quest - Android 7.1.1
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Have only 2 history feeds available in the History library.

**[Steps to reproduce]:**
1. Click the History button from the tray.
2. Hover over a history feed and click the three dot button.
3. Observe the position of the menu.

**[Expected results]:**
- The menu is displayed on the bottom side of the feed.

**[Actual results]:**
- The menu is displayed at the top of the feed, covering the "Clear History" button.

**[Notes]:**
- This issue is not reproducible if more than 2 feeds are available in History.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1dzyC5Lh9ZWZqvAjcpeD1V3IWUGcTOFTL).

**Comment by daron-walters** [comment]
The problem is that when there are 2 feed items the code was treating the first item as if it were the last item.  Updated code to fix this [here](https://drive.google.com/open?id=1WQgYCZopYHmqfmTRhiBHeJXzjPz0adha) is the link to the fix on my local.  Tested on oculus quest and pico neo2

**Comment by Softvision-RemusDranca** [comment]
I have retested this issue and it's partially fixed. The three dot menu from History is no longer displayed over the "Clear History" or over the button when triggered from the first feed displayed at the top.
However, the menu is displayed over the button if it's triggered from the second feed.
Also, this issue is now affecting the Downloads library as well (it was implemented after the issue was logged). Here, the menu is displayed over the "Sort By", and "Delete" buttons even when triggered from the 3rd position from the list.
Tested on Oculus Quest - Android 7.1.1, Pico Neo2 - Android 8.1.0 and HTC Vive Focus Plus - Android 7.1.2.

Considering this I will reopen this issue.

**Comment by daron-walters** [comment]
Hello I fix the issue in the downloads but I didnt understand the other issue "However, the menu is displayed over the button if it's triggered from the second feed."  Can you provide a video of this issue so that I can troubleshoot

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using Firefox Reality 11-141672019 (418d959). The three dot menu is no longer displayed over the "Clear History",  "Delete" and "Sort By" buttons.

Tested on HTC Vive Focus (Android 7.1.2), Oculus Quest (Android 7.1.1), and Pico Neo 2 (Android - 8.1.0) devices.
