### ISSUE TITLE
Implement add-ons support

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#299]
## Hardware
Oculus Go

## Steps to Reproduce
1. Try to install a WebExtension from https://addons.mozilla.org
2. Notice the installation fails.

## Actual Behavior
The extension is not installed.

The [**WebExtension APIs**](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions) are not yet supported on Firefox Reality.

## Expected Behavior
The extension should be installed.

## Recommendation
1. Identify [**which WebExtension APIs**](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions#JavaScript_APIs) are appropriate to expose in GeckoView and FxR.
2. Implement and expose the WebExtension APIs from GeckoView. (Tracked by platform [**bug 1468844**](https://bugzilla.mozilla.org/show_bug.cgi?id=1468844).)
3. Ensure extension installation works as expected (i.e., [`InstallTrigger.install`](https://developer.mozilla.org/en-US/docs/Web/API/InstallTrigger/install)).

When simple WebExtensions are initially support (e.g., content scripts work), then we'll want to make UX and UI affordances for managing `browserAction`s, `pageAction`s, etc. That will require some design work (see Firefox on desktop and Android for prior art).

**Comment by avrignaud** [comment]
We'll likely start with password managers here, but definitely on the list for future.

**Comment by larsbergstrom** [comment]
This will also be dependent upon GeckoView work to enable WebExtensions.

**Comment by cvan** [comment]
I've updated (with clarified info. and additional links) my original comment above in this issue: https://github.com/MozillaReality/FirefoxReality/issues/299#issue-346771728

The progress of WebExtension API support in GeckoView can be monitored from [this list of dependent bugs](https://bugzilla.mozilla.org/showdependencytree.cgi?id=1468844&hide_resolved=0) from **[Bug 1468844](https://bugzilla.mozilla.org/show_bug.cgi?id=1468844): `[meta] Add GeckoView support for WebExtensions`**

**Comment by philip-lamb** [comment]
Repurposing this issue for user-installable addons support.
