### ISSUE TITLE
Window resize drag handles are sometimes not responsive.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#2990]
## Configuration

Firefox Reality version: 10
Firefox Reality build ID: 399e57063cc667e01bd52a57e481a93f54e55387

Hardware: Headsets with two controllers.

## Steps to Reproduce

1, Place left controller on table so it isn't moving
2. Click window resize from hamburger menu
3. Try to use drag handle to resize window.

## Current Behavior

Drag handles are non-responsive.

## Expected Behavior

Window should be resizable.

## Notes
Seems to be caused by 685f2cf56fa9d6168b519504156a9e9f9034c38c

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 10-141042250 (207f86b) build. The window can be resized using the drag handles. Verified with 10 attempts.

Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2), HTC Vive Focus (Android 7.1.2) and Pico Neo 2 (Android 8.1.0).
