### ISSUE TITLE
The webpages are reloaded in the same position even if the “Reload” button is long-clicked

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3003]
**[Affected Versions]:**
- Firefox Reality version 10-140780019 (93eff892)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to the following website: http://wallpaperswide.com/ 
2. Scroll down to the bottom of the page.
3. Using the controller short-click the "Reload" button.
4. Using the controller long-click the "Reload" button.

**[Expected results]:**
Step 3. The webpage is reloaded in the same position from step2.
Step 4. The webpage is reloaded bypassing the cash and reloading from the server, the webpage is displayed at the top of the page.

**[Actual results]:**
Step 3. The webpage is reloaded in the same position from step2.
Step 4. The webpage is reloaded in the same position from step2.

**[Notes]:**
- If the "Enable Cache Bypass On Reload" setting is set to ON the cache bypass still doesn’t work.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1o1bHE0lQPdkYWPc_dBhvm_i4M55p9U_a).

**Comment by bluemarvin** [comment]
This is a GeckoView bug https://bugzilla.mozilla.org/show_bug.cgi?id=1623712
I have a work around that uses loadUri().

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10-140822127 (fb72e3a8) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 headsets.
Now, the webpages are reloaded at the top of the page if the “Reload” button is long-clicked.
