### ISSUE TITLE
The History page is empty and no new history feeds are added

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3013]
**[Affected Versions]:**
- Firefox Reality version 10-140800017 staging-master-signed.apk (b484284).

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Plus - Android 7.1.2
- Pico Neo 2 - Android - 8.1.0
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**                                        
1. Navigate to a website.
3. Click the History button from the tray.
4. Observe the page.

**[Expected results]:**
- All history feeds are displayed.

**[Actual results]:**
- No feeds are displayed, old or new.

**[Additional Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=14wm5yHfs8ZBmkGUw6GxJ4LFF31FBhs0l).

**Comment by keianhzo** [comment]
@Softvision-RemusDranca I can't reproduce this issue with the latest master. Can you confirm if you still see it and if you do add more detail? Was a fresh install or an app update? Was there any previous state that may affect?

**Comment by Softvision-RemusDranca** [comment]
@keianhzo I can still reproduce this issue even after an update, fresh install or after clearing all settings on the Firefox Reality 10-140831034  staging-master-signed.apk latest build (e318b30).
However, testing this issue with the `debug` version of the build is not reproducible.

Can you please confirm if this is the reason we have different results? We always use `staging-master-signed.apk` when testing builds from master.

**Comment by bluemarvin** [comment]
@keianhzo Sounds like an R8 issue.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 10-140842123 staging-master-signed.apk (28cd676) build. Now, the history feeds are displayed.

Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2), HTC Vive Focus (Android 7.1.2) and Pico Neo 2 (Android 8.1.0).
