### ISSUE TITLE
[FxA] The login process through the "Sign Into Account" card is not working

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3015]
**[Affected Versions]:**
- Firefox Reality version 10-140800017 staging-master-signed.apk (b484284).

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Plus - Android 7.1.2
- Pico Neo 2 - Android - 8.1.0
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the app is opened.
- No FxA account is logged in.

**[Steps to reproduce]:**                                        
1. Click the Settings button from the tray.
2. Click the "Sign Into Account" card.
3. Observe the behavior.

**[Expected results]:**
- The "Enter your email" page is displayed in the active window.

**[Actual results]:**
- A gray page is displayed in the active window.

**[Additional Notes]:**
- The log in process can be performed through the "Send Tab to Device" options or trough the First Explainer prompt.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1a4izlMFyniPdf1O-hTurc9aR9K5bsCU6).

**Comment by keianhzo** [comment]
@Softvision-RemusDranca I can't reproduce this issue with the latest master. Can you confirm if you still see it and if you do add more detail? Was a fresh install or an app update? Was there any previous state that may affect?

**Comment by Softvision-RemusDranca** [comment]
I've tested this issue and I was not able to reproduce it using the latest Firefox Reality 10-140831034 staging-master-signed.apk latest build (e318b30)  on the HTC Vive Plus (Android 7.1.2), Pico Neo 2 (Android - 8.1.0) and Oculus Quest (Android 7.1.1). devices,

I'll test the issue on the other available devices, tomorrow, and do a follow up comment with the results.

**Comment by Softvision-RemusDranca** [comment]
@keianhzo Unfortunately this issue is again reproducible with the today's build  10-140840311 staging-master-signed.apk build (8142076).

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 10-140842123 staging-master-signed.apk (28cd676) build. Now, the login process can be performed.

Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2), HTC Vive Focus (Android 7.1.2) and Pico Neo 2 (Android 8.1.0).
