### ISSUE TITLE
[Pico] The app crashes after pressing the confirm button on the headset

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3016]
**[Affected Versions]:**
- Firefox Reality version 10-140800017 (b4842842) 

**[Affected Platforms]:**
- Pico Neo2 - Android 8.1.0
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Make sure that the controller/controllers are not connected to the headset.

**[Steps to reproduce]:**
1. Move the pointer to the “New Window” button.
2. Press the confirm button on the headset.
3. Observe the behavior.

**[Expected results]:**
- A new window is created.

**[Actual results]:**
- The app crashes.

**[Notes]:**
- The issue is also reproducible when the controller/controllers are active.
- The issue is not reproducible with the Pico or Back button on the headset.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1N_ATEFLDXFnu6a8ELjr7x-WYEn7pbyfE).
- Attached the logcat file of the issue [here](https://drive.google.com/open?id=1iF6XebEncJj1BtuBK-ne3mvhMGPEAPGq).

**Comment by bluemarvin** [comment]
Is there a crash report for this?

**Comment by bluemarvin** [comment]
We had some controller related crashes that we landed fixes for yesterday. Would you retest as I believe this has already been fixed.

**Comment by bluemarvin** [comment]
Possibly fixed by #3010

**Comment by bluemarvin** [comment]
I have verified the version tested did not contain #3010

**Comment by Softvision-GeluHaiduc** [comment]
Regarding the crash report, I don't know why it doesn't appear in the logcat, the message that the crash report failed to be submitted doesn't appear either.

**Comment by Softvision-GeluHaiduc** [comment]
I will try and reproduce the issue with the latest master and see if it's fixed

**Comment by bluemarvin** [comment]
> Regarding the crash report, I don't know why it doesn't appear in the logcat, the message that the crash report failed to be submitted doesn't appear either.

It's because clicking the crash submit button was crashing too. I'm certain it is the same issue we fixed in #3010.

**Comment by Softvision-GeluHaiduc** [comment]
I just installed Firefox Reality version 10-140801344 (1915c2de) on the Pico G2 4K and the issue is not reproducible anymore.

**Comment by bluemarvin** [comment]
Closing as fixed by #3010

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10-140822127 (fb72e3a8) installed on the Pico Neo2 and Pico G2 headsets.
Now, the app doesn’t crash after pressing the confirm button on the headset.
