### ISSUE TITLE
Using cache bypass to reload page adds to history

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#3018]
## Configuration

Firefox Reality version: 10
Firefox Reality build ID: a6ae172ffab06beb037f7497e20b5cd07ee235c3

Hardware: All

## Steps to Reproduce

1. Long press reload button
2. Press back button

## Current Behavior

Same page is loaded

## Expected Behavior

The previous page in history is loaded

## Possible Solution
Blocked by:
https://bugzilla.mozilla.org/show_bug.cgi?id=1623712
https://bugzilla.mozilla.org/show_bug.cgi?id=1618664

**Comment by bluemarvin** [comment]
This seems to be working now.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10-140862313 (3db73db9) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 headsets.
Now, using cache bypass to reload a page does not add to the history.
