### ISSUE TITLE
[Pico][Intermittent] The pointer in gaze mode is positioned far under the point of view in 360 video mode after a recenter

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3029]
**[Affected Versions]:**
- Firefox Reality version 10-140822127 (fb72e3a8)

**[Affected Platforms]:**
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Make sure that the controller/controllers are not connected to the headset.

**[Steps to reproduce]:**
1. Recenter the view by long-pressing the Pico button on the headset.
2. Navigate to a 360 video on YouTube and enter immersive mode.
3. Press the confirm button on the headset.
4. Observe the position of the pointer.

**[Expected results]:**
- The position of the pointer is in front of the view.

**[Actual results]:**
- The position of the pointer is far under the point of view.

**[Notes]:**
- I was not able to reproduce this issue on the Pico G2 4K.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1q-13aHuKW6q6REDvyBRRuxByOkqymX9e/view?usp=sharing).

**Comment by bluemarvin** [comment]
I'm having trouble reproducing this issue.

**Comment by keianhzo** [comment]
@Softvision-GeluHaiduc I can't reproduce this either using the current master. Could you verify if still happens and provide better STRs?

**Comment by Softvision-GeluHaiduc** [comment]
@keianhzo I didn’t manage to reproduce the issue with the latest Firefox Reality version 10-141042250 (207f86b5) installed on the Pico Neo2.
Considering this I will close this issue as verified-fixed.
