### ISSUE TITLE
Clicking the VR icon in the URL bar does not close the popup message.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#3034]
## Configuration

Firefox Reality version: 10
Firefox Reality build ID: 41a5df31002954242cf97c035b0edc62c0da04cc

Hardware: All

## Steps to Reproduce

1. Visit a page with cases the VR icon to show in the URL bar
2. Click icon to show pop up.
3. Click icon again

## Current Behavior

Pop up menu flashes

## Expected Behavior

Pop up menu should be hidden.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10-140852325 (25447532) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 headsets.
Now, the VR icon in the URL bar does close the popup message when clicked.
