### ISSUE TITLE
Oculus optimization: Render straight to an Android SurfaceTexture based texture swap chain

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#304]
The new Oculus SDK includes and API to create an Android SurfaceTexture based texture swap chain (`vrapi_CreateAndroidSurfaceSwapChain`). We could optimize the render path in the future to render WebVR straight to the swap chain and remove some texture copys.

**Comment by MortimerGoro** [comment]
Hopefully other SDKs will allow this in the future too

**Comment by philip-lamb** [comment]
@MortimerGoro I believe this is already implemented at https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp#L291 Please close if so.

**Comment by philip-lamb** [comment]
/remind @MortimerGoro in 1 day Check status and close or update.

**Comment by MortimerGoro** [comment]
@philip-lamb We have implemented this for the browser chrome. We also could try to implement it in WebVR (currently we receive a WebGL texture from Gecko, which creates it's own surface). We can create another issue for that or make this one more explicit about WebVR, whichever you prefer.

**Comment by philip-lamb** [comment]
Tracking activity on this in https://bugzilla.mozilla.org/show_bug.cgi?id=1537961
