### ISSUE TITLE
[Oculus][krpano][Intermittent] The app is not responding after resuming the app while in immersive mode

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3046]
**[Affected Versions]:**
- Firefox Reality version 10-140842123 staging-master-signed.apk (28cd676).

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**                                        
1. Play an example from "krpano" website in immersive mode ([Example](https://krpano.com/releases/1.20.5/viewer/krpano.html?xml=examples/demotour-apartment/tour.xml)).
2. Click the Oculus button.
3. Click the "Resume" button.
4. Observe the behaviour.

**[Expected results]:**
- The app is correctly resumed.

**[Actual results]:**
- A black screen is displayed until the "App is not responding" prompt is displayed.

**[Additional Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1cUDvfika2d4SFJ46EdEp3WD-ajb0xRIV).

**Comment by bluemarvin** [comment]
Possibly related to frame-ahead feature.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the Firefox Reality version 10-140862313 (3db73db) build. The app is now resumed.
Tested on Oculus Quest (Android 7.1.1) and  Oculus Go (Android 7.1.2) devices.
