### ISSUE TITLE
Shift key is invisible on symbol keyboards when launching at the first time

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#3050]
## Configuration

Firefox Reality version: version 10
Firefox Reality build ID: 

Hardware: 
All devices.

## Steps to Reproduce

1. Launch FxR and choose Eng keyboard.
2. Switch to symbol keyboard, you will see there is no shift keys at the third row.
3. Switch to any other keyboards, then changing to symbol keyboard, the shift key is shown up although it is disabled.
4. Go back to Eng's symbol keyboard, we can see the shift key as well.

## Current Behavior

The shift key is gone at the beginning. (https://drive.google.com/file/d/1n_mGtWUE10W8BsQLWFEJ7FDu2Rr46_Vt/view?usp=sharing)

## Expected Behavior

We should follow other symbol keyboards' behavior, show the shift key as a disable one.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10-140862313 (3db73db9) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 headsets.
Now, the shift key is not invisible on symbol keyboards when launching it the first time.
