### ISSUE TITLE
[Oculus Quest] Nothing happens when pressing the B or Y controller buttons after exiting immersive mode

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3052]
**[Affected Versions]:**
- Firefox Reality version 10-140852325 staging-master-signed.apk (25447532).

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**                                        
1. Navigate to Youtube website and play a video in immersive mode.
2. Exit immersive mode.
3. Press the on the B or Y button from the controller.
4. Observe the behavior.

**[Expected results]:**
- The previous page is displayed.

**[Actual results]:**
- Nothing happens.

**[Additional Notes]:**
- This issue is affecting all existing and new windows even after navigating on different websites.
- The opened prompts and libraries are dismissed after pressing the B or Y controller buttons even after exiting immersive mode.
- The window controls are not affected by this issue.
- The issue is no longer reproducible after the app is quited and resumed.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1JUkYWn4vi63JsPBEPcPp_ZnFtP-UHmBR).

**Comment by bluemarvin** [comment]
@keianhzo Looking into this:

https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java#L807
Is getting called twice when going into immersive video which causes:
https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java#L709
To get called twice and the back handler is registered twice.

There are two issue combining here, one is that the isFullscreen is getting called twice, but also this:
https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java#L710
Is returning false both times even though it should be true after the first call. I'm not sure how to fix either issue. Any ideas?

**Comment by bluemarvin** [comment]
Removing it twice fixes the issue but that obviously isn't the correct solution.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the Firefox Reality version 10-140872228 (96e0fa0). Now, the B and Y buttons are actionable after exiting immersive mode.
Tested on Oculus Quest - Android 7.1.1.
