### ISSUE TITLE
Nothing happens when clicking the Allow/Block button from the WebXR pop-up

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3061]
**[Affected Versions]:**
- Firefox Reality version 10-140862313  (3db73db).

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Plus - Android 7.1.2
- Pico Neo 2 - Android - 8.1.0
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**                                        
1. Navigate to a website with WebXR content (ex: https://vimeo.com/channels/360vr)
2. Click the WebXR button from the Awesomebar.
3. Click the Allow/Block button from the pop up.
4. Observed the behavior.

**[Expected results]:**
- The access to WebXR API is allowed/blocked.

**[Actual results]:**
- Nothing happens.

**[Additional Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1P7KIz4XukJZ_63j4n2vZZ9oB_Db8Helo).

**Comment by bluemarvin** [comment]
Fixed by #3070

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 10-140912301 (2796172) build. Now, the access to WebXR API is allowed/blocked.

Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2), HTC Vive Focus (Android 7.1.2) and Pico Neo 2 (Android 8.1.0).
