### ISSUE TITLE
[Private Browsing] Tracking Protection can't be disabled from the shield icon button

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3062]
**[Affected Versions]:**
- Firefox Reality version 10-140862313 (3db73db).

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Plus - Android 7.1.2
- Pico Neo 2 - Android - 8.1.0
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**                                        
1. Click the Private browsing button from the tray.
2. Navigate to a website.
3. Click the shield icon from the Awesomebar
4. Click the "Disable" button from the pop-up and observe the behavior.

**[Expected results]:**
- The Tracking Protection is disabled and the shield icon is strikethrough.

**[Actual results]:**
- The Tracking Protection is not disabled and the shield icon is only briefly strikethrough.

**[Additional Notes]:**
- The websites are NOT added in the Exceptions list.
- This issue is not reproducible in normal browsing.
- I compared this behavior with the ones on Fenix and Desktop, where the Tracking Protection can't be disabled from the shield icon in PB.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1sQtrD5xEkOv0M3nYUu0eSnrOkzSBRgp-).

**Comment by keianhzo** [comment]
Depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1627185

**Comment by bluemarvin** [comment]
Depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1631514

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the Firefox Reality version 10 RC1 (6db2f60a). Now, the Tracking Protection can be disabled from the shield icon while in Private Browsing.

Tested on HTC Vive Focus (Android 7.1.2), Oculus Quest (Android 7.1.1), Oculus Go (Android 7.1.2), Pico G2 4K (Android 8.1.0) and Pico Neo 2 (Android - 8.1.0) devices.
