### ISSUE TITLE
The audio from normal browsing continues to be played after entering PB mode

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3063]
**[Affected Versions]:**
- Firefox Reality version 10-140862313 (3db73db).

**[Affected Platforms]:**
- HTC Vive Plus - Android 7.1.2
- Pico Neo 2 - Android - 8.1.0
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on and the app is opened.
- The volume is up.

**[Steps to reproduce]:**                                        
1. Play a video with audio in normal browsing.
2. Click the Private Browsing button from the tray.
3. Observe if the audio from the video continues playing.

**[Expected results]:**
- No audio is playing.

**[Actual results]:**
- The audio continues to play in PM.

**[Additional Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1J11CNvb6GRBGRMCymv0aiYesF7XVvAo7).

**Comment by bluemarvin** [comment]
This might be a recent GeckoView regression.

**Comment by bluemarvin** [comment]
Filed GeckoView issue https://bugzilla.mozilla.org/show_bug.cgi?id=1625615

**Comment by bluemarvin** [comment]
This is still waiting for a fix in Gecko.

**Comment by bluemarvin** [comment]
Fixed by #2521

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the Firefox Reality version 10 RC1 (6db2f60a). Now, the video is  stopped when the application is paused or when entering/exiting Private Browsing.

Tested on HTC Vive Focus (Android 7.1.2), Oculus Quest (Android 7.1.1), and Pico Neo 2 (Android - 8.1.0) devices.
