### ISSUE TITLE
Hubs audio only plays immediately after volume adjusted

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#3073]
## Configuration

Firefox Reality version: 10-p1
Firefox Reality build ID: ac25341f

Hardware: Pico Neo 2

## Steps to Reproduce

1. Enter a Hubs room with a youtube video playing
2. Listen for the audio
3. Adjust volume

## Current Behavior

You can hear what's in the room, but only for 1 second immediately following volume adjustment

## Expected Behavior

Audio remains playing

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
Is there a room with an example?

**Comment by bluemarvin** [comment]
I can reproduce it here https://hubs.mozilla.com/SxkhBbN/audio-test

**Comment by bluemarvin** [comment]
Looks like it is this: https://github.com/MozillaReality/FirefoxReality/issues/2620

**Comment by bluemarvin** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1626081

I can reproduce the issue in GeckoViewExample.

**Comment by bluemarvin** [comment]
There has been no action on this bug in Gecko.

**Comment by keianhzo** [comment]
@bluemarvin I can't reproduce this with your example using the latest master. Any change that this has been fixed in GV without the patch?
