### ISSUE TITLE
Fullscreen UI fails to go away when dropping out of fullscreen mode from browser UI

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#3081]
## Configuration

Firefox Reality version: 10
Firefox Reality build ID: 2796172e0b4287d2d035e6dd4cdc6ce1476af476

Hardware: 

## Steps to Reproduce

1. Go to youtube.com and play a non-immersive video in fullscreen
2. Press the in window UI to exit fullscreen (not the FxR UI bellow the window

## Current Behavior

The FxR fullscreen UI is still visible instead of the navigation URL bar. After that, the UI can't be hidden.

## Expected Behavior

The UI should be hidden.

![org mozilla vrbrowser-20200331-172235](https://user-images.githubusercontent.com/3066/78086964-5b193280-7374-11ea-9545-cacdf3b41724.jpg)

**Comment by Softvision-GeluHaiduc** [comment]
I tried to verify the issue using the latest master build, Firefox Reality version 10-140941948 (b5394107), and encountered issue #3114 which blocks me from verifying the issue in PB mode.
Also encountered a regression #3113.
