### ISSUE TITLE
The app crashes when the backslash key is clicked on the Chinese keyboard

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3085]
**[Affected Versions]:**
- Firefox Reality version 10-140912300 (989a29e5)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico Neo2 - Android 8.1.0
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Click inside the awesomebar.
2. Change the keyboard language to Chinese (China).
3. Switch to the symbol keyboard and click the backslash “\” key.
4. Observe the behavior.

**[Expected results]:**
- The backslash “\” key is imputed in the awesomebar.

**[Actual results]:**
- The app crashes.

**[Notes]:**
- The issue is not reproducible with the other languages.
- On the Danish, Polish, Norwegian, Swedish, Finnish languages the backslash “\” symbol is imputed as a colon “:”.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=19Lnaz6r7IfZnGAZMj3cusnNtS7QPKooy).
- Attached the logcat file of the issue [here](https://drive.google.com/open?id=1NMgIiWGdrb5oLQZmbOdXCysnAUvOupsMDtG7SF-nVWk).
- The crash report can be found [here](https://crash-stats.mozilla.com/report/index/0bac03c5-2b0e-4f89-b5da-e66f10200401).

**Comment by daoshengmu** [comment]
Well, it was resolved by #3056 (2796172e0b), you are just behind my commits :)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10-140922050 (de889418) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 headsets.
Now, the app doesn’t crash when the backslash key is clicked on the Chinese (China) keyboard.
