### ISSUE TITLE
The language of the keyboard is redisplayed after a key is clicked

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3086]
**[Affected Versions]:**
- Firefox Reality version 10-140912300 (989a29e5)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico Neo2 - Android 8.1.0
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Click inside the awesomebar.
2. Change the keyboard language to a different one.
3. After more than 3 seconds click a key on the keyboard.
4. Observe the spacebar.

**[Expected results]:**
- The selected language is not displayed on the spacebar.

**[Actual results]:**
- The selected language is displayed on the spacebar again.

**[Notes]:**
- The issue is reproducible with all the languages.
- For some languages a different word is shown after a key is pressed.
- For the Chinese (Taiwan) keyboard the initial language is not shown at all.
- The design document that was used as a reference is [here](https://trello-attachments.s3.amazonaws.com/5a260c5d480978f87ffad6aa/5a94a051a70bcf7bc7ccea89/f128572db4311f4eb5e82cc89e9fdd18/UIS-6_Keyboard_025.pdf) section 400b.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1_oRVGCHWQaeNqofwqwEB-JQHSpbEdJgl).

**Comment by daoshengmu** [comment]
Taiwan keyboard will not be shown at all, and I think that not be shown after 3 secs should be proper behavior.

**Comment by daoshengmu** [comment]
Regression by #2801

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10-140922050 (de889418) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 headsets.
Now, the language of the keyboard is not redisplayed after a key is clicked, except for the  Chinese (Taiwan) keyboard which doesn’t display it at all.
