### ISSUE TITLE
Notification / message of the day page

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#309]
Consider having the browser call back, providing its version number, to get a message of the day. In that message, we could notify about such things as:
- You should really update even if you've frozen updates due to a security bug
- There are new features / functionality to be aware of

**Comment by thenadj** [comment]
Where does that page show up? How does the user get to it?

**Comment by larsbergstrom** [comment]
@thenadj I think that this is a low priority for now (possibly even a 2019 feature). Today in Firefox, the notifications like this can show up as:
- A "doorhanger" that floats above the relevant UI elements to point out the new feature
- A sort of footnote-bar in the new tab page with less relevant information
- For very high priority items, as a leading bar above the top of the page that passes on information "Upgrade Firefox Nightly now!"

**Comment by cvan** [comment]
FYI: Samsung Internet Browser shows a toast/bubble notification when you bookmark a site. I imagine we would implement something similar.

**Comment by avrignaud** [comment]
Also added as an issue for 1.1. Feel free to enter suggestions like this as
suggestions and tag next version. Right now that 1.1 tag is our backlog
that we will review before finalizing 1.1 features.
-- 
Andre Vrignaud — Head of Mixed Reality Platform Strategy | Emerging
Technologies | Mozilla
avrignaud@mozilla.com | +1 (206) 245-6067 <%2B1.206.245.6067> | Skype:
andrevrignaud

**Comment by jvonitter** [comment]
related to #759
