### ISSUE TITLE
Update FxR icon back ground to match other assets?

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#311]
@thenadj currently the background for the various FxR icons is white. Should it be change to the same purple being used for the app store assets?

**Comment by thenadj** [comment]
@bluemarvin Can you attach a screenshot so I can see what they currently look like? Where do they show up?

**Comment by bluemarvin** [comment]
It's the icons from this issue: https://github.com/MozillaReality/FirefoxReality/issues/197#issuecomment-406461528

They all have white back grounds currently. I can take screen shots from devices tomorrow.

**Comment by thenadj** [comment]
Where do they show up? If they are app icons on hardware devices, then I'd probably keep the background white. I'd have to see them in their final place to make the right decision.

**Comment by bluemarvin** [comment]
@thenadj These are all small but hopefully you can see well enough.

I captured it in both Daydream and VIVEPort. Additionally, there is one showing it in the library, and one showing it in recently run for both platforms.

One thing I notice is that for some reason our icon is smaller than other app icons in VIVEPort so I'll create an issue to investigate that.

VIVEPort Library:
![screen1](https://user-images.githubusercontent.com/3066/43668112-1d207af0-9730-11e8-8a0c-3b84a78164ae.png)
VIVEPort recently run:
![screen2](https://user-images.githubusercontent.com/3066/43668114-1d3d27ae-9730-11e8-8caa-bd66555c54b5.png)
Daydream Library:
![screen4](https://user-images.githubusercontent.com/3066/43668116-1d705b9c-9730-11e8-8c70-a41d83da4977.png)
Daydream recently run:
![screen3](https://user-images.githubusercontent.com/3066/43668115-1d55ce4e-9730-11e8-8378-309b35956acf.png)

**Comment by thenadj** [comment]
@bluemarvin Use hex 25003E for background color. And adjust icon size to match other icons. Note that in top attached image icon is too small and in bottom attached image icon is too large.

**Comment by keianhzo** [comment]
Icon background color change is something that we can do using the Android assets manager. Regarding the sizes, all the icons are also generated by the assets manager so maybe there is some setting that is affecting the size on those devices.

**Comment by bluemarvin** [comment]
![fxandroid](https://user-images.githubusercontent.com/3066/43922949-20e50c92-9bd5-11e8-9c22-b3726da34eb7.png)

Looks like they changed the size of the Fx logo. We should probably match that size when changing the background.

**Comment by thenadj** [comment]
Yes, please match the size and placement for brand consistency.
