### ISSUE TITLE
[YouTube] Not all the YouTube video controls are displayed in theater mode while in Private Browsing

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3114]
**[Affected Versions]:**
- Firefox Reality version 10-140941948 (b5394107)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Click the Private Browsing button in the menu tray.
2. Navigate to a normal video on YouTube and enter theater/full screen mode.
3. Observe the video controls on the right side.

**[Expected results]:**
- All the video controls are displayed.

**[Actual results]:**
- The last few buttons from the video controls are not displayed.

**[Notes]:**
- The issue is not reproducible in normal browsing.
- The right side of the video also seems to be cut off.
- The issue becomes more visible as you resize the theater mode in larger sizes.
- The video, and video controls, are much smaller when resized to 0.5x size in theater mode.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1eeW8Pir84EVwBMKhNdGRR-OSlYkyIZ7F/view?usp=sharing).

**Comment by keianhzo** [comment]
@Softvision-GeluHaiduc I can't reproduce this anymore, Can you confirm it still happens and that the STRs are still valid?

**Comment by Softvision-GeluHaiduc** [comment]
@keianhzo I have verified that this issue is no longer reproducible with the latest Firefox Reality version 11-141351718 (9d848c46) installed on the Oculus Go, HTC Vive Focus Plus and Pico G2 4K headsets.
Now, all the YouTube video controls are displayed in theater mode while in Private Browsing.
As it is no longer reproducible I will close the issue.
