### ISSUE TITLE
[YouTube] The YouTube layout is different in Private Browsing from normal browsing

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3115]
**[Affected Versions]:**
- Firefox Reality version 10-140941948 (b5394107)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Click the Private Browsing button in the menu tray.
2. Navigate to YouTube homepage: https://www.youtube.com/
3. Observe the layout of the homepage.

**[Expected results]:**
- The layout of the YouTube homepage is the same as in normal browsing.

**[Actual results]:**
- The layout of the YouTube homepage is different from normal browsing.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1qXG_PpGkS2IuROZb3iNe9bByQUj1ZUqK/view?usp=sharing).

**Comment by bluemarvin** [comment]
I see a completely different layout than the video and it is consistent between private browsing and regular browsing.
![Screenshot_org mozilla vrbrowser_2020 04 06-13 39 06](https://user-images.githubusercontent.com/3066/78588155-fa19b080-77f2-11ea-9b04-2ed67dea91ab.png)
![Screenshot_org mozilla vrbrowser_2020 04 06-13 39 19](https://user-images.githubusercontent.com/3066/78588166-fdad3780-77f2-11ea-89fb-a49463f224ac.png)

**Comment by Softvision-GeluHaiduc** [comment]
I checked again today and this is what I see:
![Screenshot_org mozilla vrbrowser_2020 04 07-10 57 55](https://user-images.githubusercontent.com/51400741/78645543-5d254900-78c0-11ea-8716-c8a18a69291a.png)

![Screenshot_org mozilla vrbrowser_2020 04 07-10 58 08](https://user-images.githubusercontent.com/51400741/78645560-61516680-78c0-11ea-97a6-5e403fc11642.png)

maybe it's something regional from youtube?

**Comment by keianhzo** [comment]
@Softvision-GeluHaiduc Can't seem to be able to reproduce this either. Can you provide other STRs?

**Comment by Softvision-GeluHaiduc** [comment]
@keianhzo I have tried to reproduce the issue using the latest Firefox Reality version 11-141420209 (fe9d2ece) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
I wasn't able to reproduce the issue, giving this I will close the issue.
