### ISSUE TITLE
[Pico Neo2] The spinner from the Voice Search prompt is not animated

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3123]
**[Affected Versions]:**
- Firefox Reality version 10-140982354 (bce60f9).

**[Affected Platforms]:**
- Pico Neo 2 - Android - 8.1.0

**[Prerequisites]:**
- The headset is turned on and the app is opened.
- The Voice search permissions are granted.

**[Steps to reproduce]:**                                        
1. Click the Microphone button from the Awesomebar.
2. Perform a voice search and observe the spinner from the prompt.

**[Expected results]:**
- The spinner is animated.

**[Actual results]:**
- The spinner is not animated.

**[Additional Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=12HcXb3WqgIj8Pyrgw-joxqKtE0rSNBK3).

**Comment by Softvision-RemusDranca** [comment]
I have retested this issue with the latest Firefox Reality version 10-140982354 (bce60f9) build and it's seems to be reproducible only on the Pico Neo2 device where the spinner is not animated on any language.  

Considering this I will update this issue to reflect the current behavior.

**Comment by bluemarvin** [comment]
This appears to be a bug with developer mode on the neo2. If you disable developer mode, the animations should work. Additionally, if you then re-enable developer mode, the animations should continue to work.

**Comment by keianhzo** [comment]
I Added a fix to the WebXR interstitial PR that fixes this.

**Comment by Softvision-RemusDranca** [comment]
I've retested this issue and it's still reproducible with the latest Firefox Reality version 10-141111916 (d9a7eec) on Pico Neo 2 - Android - 8.1.0 device.
Considering this, I will reopen this issue.

**Comment by bluemarvin** [comment]
> I've retested this issue and it's still reproducible with the latest Firefox Reality version [10-141111916](tel:10-141111916) ([d9a7eec](https://github.com/MozillaReality/FirefoxReality/commit/d9a7eec56de15aa8d348cb85dedc8457be3eb404)) on Pico Neo 2 - Android - 8.1.0 device.
> Considering this, I will reopen this issue.

Did you test with developer mode turned off as suggested?

**Comment by Softvision-RemusDranca** [comment]
@bluemarvin It's no longer reproducible after turning developer mode off/on. I was under the impression that with the fix that closed this issue the steps to turn on/off developer mode was no longer necessary. Sorry for this confusion. 

I was concerned that the user might have to do the same steps not to reproduce this issue and I was not sure if this is a scenario only encounter by us, while having the developer mode turned on.

If this isn't a scenario that could affect the end user we can close it as verified fixed.

**Comment by bluemarvin** [comment]
The user would need to turn developer mode on. But this is a Pico system bug which we have told them about. There isn't much else we can do at this point to fix the Neo 2 with out help from Pico.

**Comment by bluemarvin** [comment]
We aren't going to be able to do anything else to address this for v10. Moving to v11.

**Comment by bluemarvin** [comment]
This seems to be fixed. Closing.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with Firefox Reality version 11 RC2 (5fd1bfd). The spinner is now animated when performing voice searches.

Tested on Pico Neo2 (Android - 8.1.0).
