### ISSUE TITLE
Distribution channel name in metrics is null after Glean updates.

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#3129]
## Configuration

Firefox Reality version: v.10
Firefox Reality build ID: 

Hardware: 
All devices

## Steps to Reproduce

1. Watch the telemetry query from https://sql.telemetry.mozilla.org/queries/69899/source#176133,
we can see the `distribution_channel_name` in metrics would be null sometimes.

## Current Behavior

After FxR v.9, the `distribution_channel_name` would be null from some situations. I think it causes by the recent Glean updates.

## Expected Behavior

`distribution_channel_name` should be according to `BuildConfig.FLAVOR_platform`.

## Possible Solution

After discussion with Glean team, they suggest us setting metrics after `Glean.Initialize()`. Otherwise, those pings and operations will be deleted in some cases.

```
```

</details>

**Comment by daoshengmu** [comment]
It needs to update GV for the newest version of Glean. Let's move it to v.11

**Comment by bluemarvin** [comment]
@daoshengmu Is this fixed in v11 or should it be moved to v12?

**Comment by daoshengmu** [comment]
Fixed by #3384
