### ISSUE TITLE
[Oculus] The app crashes when quitting and resuming the app while in immersive mode with multiple windows created

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3131]
**[Affected Versions]:**
- Firefox Reality version 10-140982354 (bce60f9d)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Click the “+” button in the menu tray.
2. Navigate to a 360 video on YouTube and enter immersive mode.
3. Press the Oculus button on the controller and quit the app.
4. Reopen the app and observe the behaviour.

**[Expected results]:**
- The app is reopened and the 2 windows are displayed.

**[Actual results]:**
- The app crashes on reopening.

**[Notes]:**
- The issue is not reproducible with only one window open.
- The issue is not reproducible if the app is quitted from normal browsing.
- Might be a related to #3109.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1uWwqF-M1YEemmzpxkeYx48UDWkqciSrx/view?usp=sharing).
- Attached the logcat file of the issue [here](https://docs.google.com/document/d/1_UV6AAkqdyyOqmMb-rcR5n3nKmyMYjQyKNuvEBYdgdM/edit?usp=sharing).
- The crash report can be found [here](https://crash-stats.mozilla.com/report/index/0a339a21-cbc3-44ea-ae80-90f4d0200408).

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 10-141042250 (207f86b) build. The app is correctly resumed.

Tested on Oculus Go (Android 7.1.2) and Oculus Quest (Android 7.1.1) devices.
