### ISSUE TITLE
Some websites are duplicated in the ETP exception list

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3133]
**[Affected Versions]:**
- Firefox Reality version 10-140982354 (bce60f9d)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Make sure to have more than 8 websites in the ETP exception list.

**[Steps to reproduce]:**
1. Open the "Privacy & Security" card from Settings.
2. Click the “Exceptions” button from the "Enhanced Tracking Protection" setting.
3. Observe the websites in the list.

**[Expected results]:**
- All the websites from the ETP exception list are displayed.

**[Actual results]:**
- Some of the websites are duplicated in the list.

**[Notes]:**
- The issue is not reproducible if the list has fewer websites.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1yD-WQOF08Gj0bshyVZkDqT_5bRN514LC/view?usp=sharing).
- Also attached a screenshot:
![Wed04-08-2020_11-44-55 09](https://user-images.githubusercontent.com/51400741/78784245-aa331900-79ad-11ea-80b2-3bcae1ffd122.png)

**Comment by bluemarvin** [comment]
@keianhzo Has this been addressed by recent fixes to ETP exception list?

**Comment by keianhzo** [comment]
yes, that was the same issue, we were not providing stable Ids

**Comment by bluemarvin** [comment]
Fixed by  #3286

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10 RC4 (29991298) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, websites are no longer duplicated in the ETP exception list.
