### ISSUE TITLE
Missing clear button in URL bar

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#314]
# Hardware: 
All
# Steps to Reproduce:
- Click on the URL bar
- Start typing
# Actual Behavior:
- You don't have any button to delete the whole URL bar text
# Expected Behavior:
- We should show a button so you can instantly delete all the text from the URL bar.
# Recommendation:
We should add a button by the voice input button to delete all text.

Fennec shows both he voice input button and the clear button at the same time at the end of the URL bar.

Other apps replace the voice input button for a clear button once there is any text in the text input. If all the text is deleted you get back the voice input button. 

The voice input button will always be visible in the keyboard anyway.

**Comment by cvan** [comment]
Could there be a way to clear by holding down the Backspace key à la iOS' keyboard?

**Comment by keianhzo** [comment]
Yes, we could also implement that additionally.

**Comment by thenadj** [comment]
Sounds good to me as an additional way to clear.

**Comment by keianhzo** [comment]
@thenadj We will need design for that clear button in the navigation bar.

**Comment by thenadj** [comment]
@keianhzo Working on the design today. Will let you know when UIS-21 is updated.

**Comment by thenadj** [comment]
@keianhzo The updated spec with (x) in URL bar interaction is in Trello. See Done column 'UIS-21 Window w/ Controls Below & Thumbnails'. Please note that several sections in UIS-21 have been updated to reflect changes.
