### ISSUE TITLE
[Intermittent] The app crashes when manually resizing the window

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3147]
**[Notes]:**
- In some attempts the drag handles were not actionable.
- In one attempt the window was resized but I could not save the setting.

**[Affected Versions]:**
- Firefox Reality version 10-141010017 (5497036).

**[Affected Platforms]:**
- HTC Vive Plus - Android 7.1.2
- Pico Neo 2 - Android - 8.1.0
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**                                        
1. Click the Hamburger button.
2. Click the "Resize Window" button from the hamburger menu.
3. Click and hold the right drag handle.
4. Drag the handle to the right and observe the behavior.

**[Expected results]:**
- The handle is correctly dragged and the window is resized accordingly.

**[Actual results]:**
- The app crashes or the handles are not actionable or the resize can't be saved.

**[Additional Notes]:**
- I was not able to reproduce this issue when resizing the window using the predefined sizes.
- I was able to reproduce this issue mostly on Oculus Quest.
- Attached are a screen recording, crash report and the logcat of the issue: 
	- Screen recording: [link](https://drive.google.com/open?id=1hu378pnpamzcUy_3PAEhaDTOJEaxmkV1).
	- Crash Report: [link](https://crash-stats.mozilla.com/report/index/14ed871b-10e4-45c4-a682-341a00200410).
	- Logcat: [link](https://drive.google.com/open?id=1OYDnxhAbg1Ky6052GkU0qvHvwnF-yG3v).

**Comment by bluemarvin** [comment]
The crash is new but:

-  In some attempts the drag handles were not actionable.
-  In one attempt the window was resized but I could not save the setting.

Are both dupes of: https://github.com/MozillaReality/FirefoxReality/issues/2990 and https://github.com/MozillaReality/FirefoxReality/issues/2862

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 10-141042250 (207f86b) build. The app doesn't crash when manually resizing the window.

Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2), HTC Vive Focus (Android 7.1.2) and Pico Neo 2 (Android 8.1.0).
