### ISSUE TITLE
[Oculus] The UI has glitches and the browser hangs while the libraries are opened in large window sizes

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3148]
**[Notes]:**
- The issue is more damaging starting from a 2x size and going up.

**[Affected Versions]:**
- Firefox Reality version 10-141010017 (5497036).

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**       
1. Click the Bookmarks/History button from the tray.                                 
2. Click the Hamburger button.
3. Click the "Resize Window" button from the hamburger menu.
4. Select the 2x size or higher.
4. Observe the behaviour.

**[Expected results]:**
- The window is resized and the UI is correctly displayed.

**[Actual results]:**
- UI glitches are displayed and the browser is hard to navigate.

**[Additional Notes]:**
- I was not able to verify this issue on Oculus Go, but I will follow up with a comment on Tuesday.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1eqGfsSHoRALy_GCziuUZRq8ocG46Vw5g).

**Comment by Softvision-RemusDranca** [comment]
The issue is also reproducible on Oculus Go with the latest Firefox Reality version 10-141042250 (207f86b) build. 
This comment is a follow up as mentioned in the issue notes.

**Comment by bluemarvin** [comment]
The history window seems to be particularly bad. This look like we are overloading the GPU and causing jank.

**Comment by bluemarvin** [comment]
Bisecting shows https://github.com/MozillaReality/FirefoxReality/pull/3108 caused the regression.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 10-141070817 (c20caf2) build. The UI and performance of the app are no longer affected when the libraries are opened.

Tested on Oculus Quest (Android 7.1.1) and Oculus Go (Android 7.1.2).
