### ISSUE TITLE
After exiting an resuming the app from an immersive video the UI is broken for that window

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3154]
**[Affected Versions]:**
- Firefox Reality version 10-141042250 (207f86b5)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Click the “+” button in the menu tray.
2. Navigate to a 360 video on YouTube and enter immersive mode.
3. Press the trigger button on the controller to have the on screen controls displayed.
4. Press the Vive/Pico button on the controller.
5. Navigate to a different folder. (e.g. Settings, Accounts)
6. Reopen the app and observe the behaviour.

**[Expected results]:**
- Immersive mode is exited and the 2 windows are displayed.

**[Actual results]:**
- Immersive mode is not exited and the UI is broken after exiting immersive mode for that window.

**[Notes]:**
- The issue is not reproducible on the Oculus devices.
- The issue is also intermittently reproducible without the on screen controls displayed.
- The issue is also intermittently reproducible with only one window open.
- The window controls are not displayed for the window with the video and can not be dismissed.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1v5YJhNQuIgW2H1VCe6-in5qguGn776Xl/view?usp=sharing).

**Comment by bluemarvin** [comment]
From the video, it looks like the browser window is missing a call to drop out of full screen. However, I have repeatedly tried on both G2 4k and Focus Plus following the steps shown in the video (even using the same video) and have not been able to reproduce this issue. @Softvision-GeluHaiduc easy was this for you to reproduce?

**Comment by Softvision-GeluHaiduc** [comment]
I tried to reproduce the issue and I observed a few differences from the last time I tested this. I tried reproducing the issue after an update of the app and after a clean install.
Here are the differences:
- The issue is intermittently reproducible now, I couldn’t identify any more reliable STR then the ones in the bug. [Here](https://drive.google.com/file/d/1rp_sHSaX4QjZ86bd8dWKZGggiytY1xP0/view?usp=sharing) is a video recording of the issue on the G2 and [here](https://drive.google.com/file/d/1y-8w31UUbfzMuBlXo6ZT5STobUN59tOT/view?usp=sharing) is one for the Neo2.
- I didn’t manage to reproduce the issue on the HTC device anymore.
- Something else I noticed is that when the audio is still playing when reopening the app the issue is not reproducible, but when the audio is not playing any more and you reenter the app the issue is intermittently reproducible. Sometimes the audio continues playing for longer sometimes it stops right after entering another folder on the OS.

**Comment by bluemarvin** [comment]
Okay, I think I know what is going on here. The content process is getting killed while we are in the background so when it gets restored, it is no longer in fullscreen mode but we never take FxR out of fullscreen mode. I'll see if we can handle it in the GeckoSession.onKill callback.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10-141111916 (d9a7eec5) installed on the HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, after exiting and resuming the app from an immersive video the UI is not broken anymore.
