### ISSUE TITLE
Tabs are not correctly restored

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#3157]
## Configuration

Firefox Reality version: 10-141042250
Firefox Reality build ID: 207f86b

Hardware: 

## Steps to Reproduce

1. Go to any website
2. Long click on a link
3. Open the link in a new tab
4. Open the Tabs window
5. Click on the recently opened tab

## Current Behavior

When switching to  the new tab the page is not loaded

## Expected Behavior

The tab uri should be loaded when the tab is selected.

## Possible Solution

We load the session Uri after a non opened tab is selected. Not after opening the session and loading the uri, we get a load request for the uri but we get a pageStart callback for `about:blank`. This behavior has been recently introduced in GV . It worked in `76.0.20200324093140 `and stopped working in `76.0.20200330094747`.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10-141060720 (fa882ff2) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the tabs are loaded when opened.
