### ISSUE TITLE
Draggable scrollbars

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#317]
Hardware: All
Steps to Reproduce: NA
Actual Behavior: No scroll bars show when in site
Expected Behavior: Scroll bar and selectable/draggable handle appear
Recommendation: Implement scroll bar and selectable/draggable handle for use when rendering desktop websites

@thenadj believe we will need design for scroll bar and handle for 1.0.

**Comment by bluemarvin** [comment]
Blocked by:

https://bugzilla.mozilla.org/show_bug.cgi?id=1480906

**Comment by thenadj** [comment]
It's currently #4 on our priority list.

**Comment by thenadj** [comment]
Design for drag handles are added to UIS-21.

[UIS-21 Window w Controls Below & Thumbnails_010.pdf](https://github.com/MozillaReality/FirefoxReality/files/2285344/UIS-21.Window.w.Controls.Below.Thumbnails_010.pdf)

**Comment by bluemarvin** [comment]
Have not had time to investigate this yet. May take as longer than a week to get all patches through on GeckoView side. I personally don't feel this should be a ship blocker.

**Comment by cvan** [comment]
@bluemarvin: do you think that is an expectation from users to have? I am likely missing something, but is there prior art here for VR browsers?

**Comment by cvan** [comment]
Interesting. What was the sample size of users who requested that?

We have not visible scrollbars on mobile for 11 years. I would assume scrolling faster on the gamepads alleviates that.

If someone has a test site or video they can share of the problem, hopefully I will better understand this.

Thanks for the helpful responses.

**Comment by thenadj** [comment]
@cvan I can ask Blink to give us more insights on that. It came up during the usability test. The thing to remember is that VR, even though it uses mobile technology, feels very different than mobile. In the user's mind the order is: phone, tablet, desktop, extremely large monitor and then VR. So we have to design that perception while using mobile technology. Somehow we have to bridge the gap.

**Comment by avrignaud** [comment]
Another place this appears is in the developer panel - I find myself instinctively wanting to select the scrollbar and drag it up and down to move through the window. Instead I can only click on the window itself and drag it, which then causes the scrollbar to seem to move in the reverse of what I'm expecting. Short form, I expect to be able to click and drag the scroll bar in the dev settings window as well.

**Comment by jvonitter** [comment]
This requires a GeckoView change so it is still blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1480906 but the designs are done.
