### ISSUE TITLE
Allow virtual pixel ratio to be set for browser window

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#318]
Hardware: All
Actual Behavior: Browser page uses device reported DPI
Expected Behavior: Should be able to override device DPI so is consistent across platforms
Recommendation:

Blocked by: https://bugzilla.mozilla.org/show_bug.cgi?id=1477837

Once this is implemented it should be possible to set a virtual DPI for the browser window.

**Comment by nancyhang** [comment]
#274

**Comment by nancyhang** [comment]
#274

**Comment by nancyhang** [comment]
This is linked to #274

**Comment by bluemarvin** [comment]
I have a patch up for review: https://bugzilla.mozilla.org/show_bug.cgi?id=1477837

Once that lands, we can add a setting in preferences to override the default display density.

**Comment by bluemarvin** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1477837 Has landed. We now need UI so it can be changed. Please note that FxR needs to be restarted since the value needs to be set before GeckoView has started.

**Comment by nancyhang** [comment]
@thenadj

**Comment by avrignaud** [comment]
@bluemarvin is this one of the settings in #283 - the developer option where a user can enter in a pixel ratio like 1024x768, and upon submitting UI appears to warn user that this change requires a restart? If so, it will be done as part of #283 design work as soon as possible.

**Comment by keianhzo** [comment]
Closed per #391
