### ISSUE TITLE
If the content process crashes or is killed while in fullscreen and or immersive mode, the windows are left in a bad state.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#3183]
## Configuration

Firefox Reality version: 10
Firefox Reality build ID: 58ba8ea588b19d9295eb245f92d8e6e91eec5c2c

Hardware: All

## Steps to Reproduce

1. Open 360 video and enter immersive mode.
2. Use adb to kill the content process 

## Current Behavior

The WindowWidgets still behave as if they are in fullscreen mode while the recreated GeckoSession is not.

## Expected Behavior

All the windows are restored to their default mode (not in fullscreen or immersive mode).

**Comment by bluemarvin** [comment]
@MortimerGoro && @keianhzo We are going to need to fix this before we ship v10. I'm going to need some help figuring out the best way to address this.

**Comment by Softvision-GeluHaiduc** [comment]
@bluemarvin Could you please add the adb command used to kill the content process.
Using `adb shell am force-stop org.mozilla.vrbrowser` kills the entire app and sometimes the windows are not restored when the app is reopened.

**Comment by MortimerGoro** [comment]
@Softvision-GeluHaiduc try this command:

`adb shell ps | grep vrbrowser:tab | awk '{ print $2 }' | xargs adb shell run-as org.mozilla.vrbrowser. kill`

**Comment by Softvision-GeluHaiduc** [comment]
I tried the command but unfortunately, it doesn't work on windows.

**Comment by keianhzo** [comment]
@Softvision-GeluHaiduc This should be the Windows equivalent:
`
adb shell ps | Select-String -Pattern "vrbrowser:tab" | %{($_ -split "\s+")[1]} | %{(adb shell run-as org.mozilla.vrbrowserkill $_)}`
