### ISSUE TITLE
Show `connect: BufferQueue has been abandoned` when using Quest

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#3184]
## Configuration

Firefox Reality version:  v.10
Firefox Reality build ID: 

Hardware: 
It only happens in Oculus Quest, probably Go? Focus Plus doesn't have this issue.

## Steps to Reproduce

1. Click one of the links from Bookmark or History.
2. See Logcat in AS. You can see `E/BufferQueueProducer: [SurfaceTexture-xxx-xxxx-xx] connect: BufferQueue has been abandoned`

## Current Behavior

It will show `BufferQueue has been abandoned` logs when visiting bookmark or history every time.  I would guess it is because SurfaceTexture doesn't be disposed before deleting it. However, when using Oculus Browser, I didn't see this log.

## Expected Behavior

We should avoid this error logs. It might bring the possibility of memory leak.

```
```

</details>

**Comment by bluemarvin** [comment]
Is this still an issue?
