### ISSUE TITLE
Move string.xml html to CDATA

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#3185]
**Is your feature request related to a problem? Please describe.**
Per @flodolo's [comment ](https://github.com/MozillaReality/FirefoxReality/pull/3174#pullrequestreview-394627416) seem like using CDATA plays better with the localization flow that using encoded xml entities. We should look into migrating those.

**Describe the solution you'd like**
Migrate XML entities containing strings like:
https://github.com/MozillaReality/FirefoxReality/blob/f914e0d8dbb2f2369378b72fb15fa31e75177eb7/app/src/main/res/values/strings.xml#L619

 to CDATA based:
https://github.com/MozillaReality/FirefoxReality/blob/f914e0d8dbb2f2369378b72fb15fa31e75177eb7/app/src/main/res/values/strings.xml#L1318-L1328

**Comment by flodolo** [comment]
@Pike
In this case, it would be great to manually fix the existing translations if possible. Would that create any issue with the automation, besides the risk of conflicts?

**Comment by Pike** [comment]
I think that should be OK. Note, if Pontoon saved those entities, it'd also update the CDATA formatting, so maybe that's the route of least trouble.

**Comment by flodolo** [comment]
> Note, if Pontoon saved those entities, it'd also update the CDATA formatting, so maybe that's the route of least trouble.

Can you clarify this part? I wouldn't expect the source string to match the previous version, unless the CDATA is ignored by Pontoon.

Also, can this be actually tested in some ways? I'd prefer not to rely on a "maybe", because it bit us in the past ;-)

**Comment by Pike** [comment]
I expect the source string in Pontoon to be exactly the same, the translations, too. This is all done in parser magic, https://github.com/Pike/compare-locales/blob/b48ca021edf5b0b8a7f8837ad104c540b4024b0a/compare_locales/parser/android.py#L155-L167 effectively.

Sadly to use Pontoon, we'd need to fake `ChangedEntity`, I guess. Using compare-locales' serializer directly with new values being old values should do the same trick.

All untested, just theory.

**Comment by keianhzo** [comment]
@flodolo My plan was to migrate all the encoded XML entieies to CDATA and update the strings keys. Is that the way to go? I'm confused after your conversation above.

**Comment by flodolo** [comment]
I think that's more a question for @Pike at this point, and we potentially need to involve @mathjazz

**Comment by keianhzo** [comment]
@Pike @mathjazz Any updates?

**Comment by Pike** [comment]
There shouldn't be key changes as long as it's just the encoding and CDATA.
