### ISSUE TITLE
[Pico]Stereo pano video from Video play with incorrect mapping

### ISSUE THREAD

**Issue by picoxr** [MozillaReality/FirefoxReality#3194]
## Configuration

Firefox Reality version: Firefox Reality version 10-141060720
Firefox Reality build ID: 9b36c14

Hardware: 
Pico G2 4K - Android - 8.1.0

## Steps to Reproduce

1. Open this video [link ](https://youtu.be/LNYjyE-NAWk?t=54)from Youtube
2. Click play button and select "360 stereo" mode.
3.

## Current Behavior

This is an up-and-down stereo video which should map upper half to left eye and lower half to right eye. Current behavior is upper half has been mapped to right eye. 

## Expected Behavior

Would hope to improve predicting algorithm to allow upper half mapped to the left side.

## Context

Oculus 9.1 seems to behave similarly.
Tip: On Pico devices, you can press "Confirm" and "Volume Up" buttons together to switch between VR mode and 2D mode. This might help if you want to test this on your side

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
Need design for UI/UX that allows eyes to be swapped. Unfortunately there isn't a good way to detect right vs left eye. The user will need to initiate the swap.

**Comment by karlcow** [comment]
Probably a duplicate https://github.com/webcompat/web-bugs/issues/50567
