### ISSUE TITLE
Korean input doesn't recognize complete characters

### ISSUE THREAD

**Issue by picoxr** [MozillaReality/FirefoxReality#3195]
## Configuration

Firefox Reality version: Firefox Reality version 9
Firefox Reality build ID: 

Hardware: 
Pico G2 4K - Android - 8.1.0

## Steps to Reproduce

1. Enter website youtube.com, select input bar and the keyboard prompt
2. Select Korea input
3. Input "ㄷㅐㅎㅏㄴㅁㅣㄴ구ㄱ"

## Current Behavior

Display "ㄷㅐㅎㅏㄴㅁㅣㄴ구ㄱ"

## Expected Behavior

Display "대한민국"

## Possible Solution

Check if later version has fixed this issue

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
Are there additional step to reproduce the issue? I tested on a Pico G2 4K running PUI 3.6.0 and was not able to reproduce the issue in the latest build of FxR:
![Screenshot_org mozilla vrbrowser_2020 04 21-18 54 08](https://user-images.githubusercontent.com/3066/79922372-b032ec00-83e8-11ea-8e01-f8b471d7bc7a.png)

**Comment by daoshengmu** [comment]
I had difficulty to type `구ㄱ` on my Quest. On my iOS keyboard, it is too. If I wanna get `국`, I need to type `ㄱㅜㄱ`.

**Comment by picoxr** [comment]
v10 - preview 2

**Comment by picoxr** [comment]
Fixed in Pico v10-preview2 build.

**Comment by picoxr** [comment]
This issue only happens in input field of some websites, e.g. baidu.com, youtube.com etc. 

Video illustration here: [https://drive.google.com/file/d/1wrWbN3JLEMX-h6oPXhCMBj57iT3TLGJO/view?usp=sharing](url)

**Comment by daoshengmu** [comment]
I have an another try. Unfortunately, I can't reproduce it in FxR 12 dev build.
