### ISSUE TITLE
The application icon on Wave in Vive Port is smaller than other application icons.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#320]
Hardware: Wave VR
Steps to Reproduce: View the FxR application in Vive Port
Actual Behavior: Application icon is smaller than other application icons.
Expected Behavior: Our icon should be the same shape and size as the other applications.
Recommendation: Need to investigate if there is a manifest flag or icon size that should be provided so the FxR application icon looks the same size and shape as other applications on the platform.

![waveicon](https://user-images.githubusercontent.com/3066/43670782-f631cace-9744-11e8-92be-db3f7c1204ec.png)

**Comment by keianhzo** [comment]
Don't know why this wasn't closed when referenced from #338 @bluemarvin are you ok with closing this one?
