### ISSUE TITLE
Investigate cylindrical layers on Oculus Mobile

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#321]
Hardware: Oculus mobile

Oculus Mobile VrApi provides a layer system that allows textures to be submitted the VR compositor and projected on to various shapes such as cylinders and cubes. This allows the textures to bypass a render pass which helps improve clarity of the texture's content. This can help improve text legibility. This system comes with limitations. The layers are submitted to the VR compositor sequentially and are rendered in order with no depth data. In order to prevent layers from rendering on top of each other, each layer either needs to occupy a different z depth range or if two layers share similar z depth, the layer rendered second must leave a hole where the preceding layer was rendered to prevent it being covered.

There are a number of technical challenges that would need to be worked out.

1) rendering the pointer on the curved surface. The current point is designed to work with flat surfaces.
2) blitting the browser surface texture to the cylinder swap chain.
3) creating an appropriate environment or seeding the scene depth with the curved window shape.
4) hit testing on a curved surface.
5) probably stuff I haven thought of yet.

**Comment by sigmaxipi** [comment]
The Daydream API also provides similar functionality. Chrome VR uses this. You can open a text-heavy site in Chrome VR and FxR and note the different is apparent resolution.

https://developers.google.com/vr/reference/gvr-ndk-rendering#using_multiple_buffer_viewports has more information and https://github.com/googlevr/gvr-android-sdk/blob/master/samples/ndk-hellovr/src/main/jni/hello_vr_app.cc#L347 has an example where the reticle is rendered independently from the rest of the scene.

**Comment by MortimerGoro** [comment]
Implemented in https://github.com/MozillaReality/FirefoxReality/pull/930
