### ISSUE TITLE
Pressing "o" button on Oculus Go controller on first run causes application exit.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#322]
Hardware: Go
Steps to Reproduce:
1) Uninstall FxR
2) Install FxR
3) Run FxR
4) Long press "o" button on controller
Actual Behavior: Application exits back to home environment.
Expected Behavior: Controller should be re-calibrated.
Recommendation: This is similar to the previous bug that was fixed by SDK 1.15 expect it is only the "o" button that is affected. Will probably need Oculus support since it is only reproducible on first run.

**Comment by cvan** [comment]
Curious: What is the expected way for users to switch apps / exit to the lobby? (Asking for the Go.)

**Comment by bluemarvin** [comment]
Pressing 'o' button should bring up exit menu. Long-pressing the 'o' should re-calibrate the controller. Neither should just quit the application.

**Comment by bluemarvin** [comment]
Not sure why this was closed.

**Comment by cvan** [comment]
my bad, I referenced the wrong issue (#312). totally didn't notice that.

this is in fact an issue - and thanks for the clarification. that explains my confusion in using FxR on the Go.

**Comment by bluemarvin** [comment]
It looks likes pressing the volume button on the Go headset also causes the application to exit on first run.

**Comment by cvan** [comment]
When FxR crashes on some immersive content, the user's gaze is frozen at the last frame. And both the cursor and all buttons on the Oculus Go controller become unresponsive.

I can't take a screenshot or video to demonstrate this unfortunately. Once it gets in that state, I have to do a force-restart by holding on the Power button for several seconds.

Should I file that in a separate issue or would this one cover that too?

**Comment by bluemarvin** [comment]
This probably isn't a crash but is the system getting deadlocked. There are patches working their way through gecko that should fix most of the deadlock issues.

**Comment by bluemarvin** [comment]
This is blocked waiting for feedback from Oculus.
