### ISSUE TITLE
Tracking protection is wrongly enabled in Private Browsing when disabling/enabling it in normal browsing from the pop-up

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3229]
**[Affected Versions]:**
- Firefox Reality version 10 RC1 (6db2f60a)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Open a Private Browsing session and navigate to a website.
2. Click the TP shield icon an disable Tracking Protection.
3. Exit Private Browsing and open a website in Normal Browsing.
4. Click the TP shield icon an disable Tracking Protection.
5. Enter in Private Browsing again and observe the Tracking Protection shield icon.

**[Expected results]:**
- The icon is strikethrough, the Tracking Protection is disabled.

**[Actual results]:**
- The icon is not strikethrough, the Tracking Protection is enabled.

**[Notes]:**
- Attached a screen recording of the issue: [link](https://drive.google.com/open?id=1IKTt3fkrrOnQyLjY4wAshLc3SBUQZsuT).

**Comment by bluemarvin** [comment]
This is cause by clearing and restoring exceptions every time one is added here:
https://github.com/MozillaReality/FirefoxReality/blob/5ea74c86b9a12bed6f4f07c9259e9ec8bdf951b6/app/src/common/shared/org/mozilla/vrbrowser/browser/content/TrackingProtectionStore.java#L118

We need to only restore the exceptions at start up and then only use add/remove after that.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10 RC2 (17a313b4) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, tracking protection is not wrongly enabled in PB when disabling/enabling it in normal browsing.
