### ISSUE TITLE
About:Config can't be opened in the fire fox reality browser

### ISSUE THREAD

**Issue by TheoSanden** [MozillaReality/FirefoxReality#3231]
## Hardware

Oculus quest 
Version 12.0.0.226.469.188362039
Runtime version 12.0.0.226.469.188362025

## Steps to Reproduce

Type about:config into the search bar.

## Current Behavior

A blank screen pops up with the error message:

"Cannot complete request. Additional information about this problem or error is currently unavaliable"

## Expected Behavior

As with the desktop version i expect the config page to pop up. 

## Context

I'm currently developing a Mozilla WebXR/Unity project for oculus quest. However, i don't have access to a server so i thought i could open the file locally (file:///sdcard/Builds/index.html) but the firefox browser ,due to security reasons, doesn't allow local files to be opened so i get the error message "it seems your browser does not support running unity webgl content from file:// urls".
In the desktop fire fox browser this can be circumventet by setting the "privacy.file_unique_origin" flag to false in the about:config page but, as the issue states, it seems like it can't be accessed in the fire fox reality browser.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by keianhzo** [comment]
Support for `about:config` has been added in v10. It will be available in the next store update. If you want to try it before it's available in the stores you can try any of the v10 RCs: https://github.com/MozillaReality/FirefoxReality/releases

**Comment by bluemarvin** [comment]
`about:config` is only available in debug builds. You can side load debug builds from taskcluster. You can also use adb port forwarding to make a web server on a host machine look like a local port in FxR.
