### ISSUE TITLE
The "Learn more" links for DRM and Tracking Protection are redirecting to Desktop support pages

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3233]
**[Affected Versions]:**
- Firefox Reality version 10 RC1 (6db2f60a)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to a website.
2. Click the Tracking Protection shield icon.
3. Click the "Learn More" string from the pop-up displayed.
4. Observe the informations available.

**[Expected results]:**
- Information on how to use Tracking Protection in Firefox Reality are available

**[Actual results]:**
- Information on how to use Tracking Protection in Firefox Desktop are available.

**[Notes]:**
- This issue is also reproducible with the links provided for DRM and the "Learn More" links available in Settings, prompts.
- Attached a screen recording of the issue: [link](https://drive.google.com/open?id=1DiYEowgiLtcjT9c5hb73QmkDZdln1fpF).

**Comment by keianhzo** [comment]
@emstanley Can we get someone from SUMO involved to get FxR specific pages for all our SUMO pages? 

This is what we currently link from SUMO:

https://github.com/MozillaReality/FirefoxReality/blob/5ea74c86b9a12bed6f4f07c9259e9ec8bdf951b6/app/src/main/res/values/non_L10n.xml#L61-L66
