### ISSUE TITLE
The WebXR icon from the Awesomebar is not displayed for certain pages when first opened

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3235]
**[Affected Versions]:**
- Firefox Reality version 10 RC1 (6db2f60a)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Play the "Hello WebXR" card from Homepage.
2. Observe if the WebXR icon from the Awesomebar is displayed

**[Expected results]:**
- The icon is displayed.

**[Actual results]:**
- The icon is not displayed.

**[Notes]:**
- The icon is displayed after entering and exiting immersive mode.
- I was also able to reproduce this issue with the "Jumpy Balls" page.
- I did not reproduce this issue with pages from krpano website and "Spider-Man WebXR" pages.
- Attached a screen recording of the issue: [link](https://drive.google.com/open?id=1IAO4mZCNg0MyBQ9ACc6VQdcqUDkWo1_1).

**Comment by keianhzo** [comment]
This is the expected behavior for WebXR vs WebVR. Now that the WebXR support has been added we won't show the WebXR icon until it starts using the API so we can't show the icon before entering.
You can see the difference trying the WebVR vs WebXR samples:
https://webvr.info/samples/
https://immersive-web.github.io/webxr-samples/

**Comment by Softvision-RemusDranca** [comment]
@keianhzo I took a look over the samples. A concern that I have is in the situation when WebXR is off for a web page. It seems like there are to many steps to be able to play it again using WebXR:
1. First the user has to try and open the page.
2. Then the WebXR icon is displayed in the Awesomebar.
3. Click the icon and allow WebXR.
4. The page is refreshed and only now the page can be played.

Also, not sure if it's user friendly to give the option to disable WebXR only after they enter in that experience and only seeing it after exiting immersive mode.
