### ISSUE TITLE
The libraries icons from the tray buttons are slightly enlarged when clicking certain tray buttons

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3236]
**[Affected Versions]:**
- Firefox Reality version 10 RC1 (6db2f60a)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Click the Private Browsing button from the tray.
2. Observe the library buttons.

**[Expected results]:**
- No UI changes are displayed for this buttons.

**[Actual results]:**
- The libraries icons are slightly enlarged.

**[Notes]:**
- This issue is mainly reproducible when clicking the New Window and Private Browsing buttons.
- This issue is also reproducible when clicking the libraries buttons while a library is opened and the other ones are clicked.
- The issue is not reproducible when the Settings and View Tabs buttons are clicked.
- Attached a screen recording of the issue: [link](https://drive.google.com/open?id=1EK5AK2rRZyl-ufifEsZN1WTLtIOGgymd).

**Comment by Softvision-GeluHaiduc** [comment]
The issue is also reproducible when switching between multimple windows.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the Firefox Reality version 10 RC5 (e84d3c9). The library buttons are no longer enlarged when clicking other tray buttons or when focusing other windows.

Tested on HTC Vive Focus (Android 7.1.2), Oculus Quest (Android 7.1.1),  and Pico Neo 2 (Android - 8.1.0) devices.
