### ISSUE TITLE
Replace `DEFAULT_URL` with a remotely hosted, updatable page

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#324]
FYI: **https://mixedreality.mozilla.org/fxr/feed** is currently just a placeholder.

First question, with GeckoView: if the protocol of the URL is `about:` or `resource://`, do we get more "chrome" privileges?

I'd like to have the start page that automatically updates. Easy hack that would work today:

```html
<iframe width="100%" height="100%" src="https://mixedreality.mozilla.org/fxr/feed/?flavor=%FLAVOR%>
```

I've been working on the frontend and backend architecture the past few days (super simple):

- https://github.com/MozillaReality/ContentFeed/issues/8#issuecomment-410030975
- https://github.com/MozillaReality/ContentFeed/issues/9
- https://github.com/MozillaReality/ContentFeed/milestone/2

And the week prior I worked on some design sketches, wireframes, and three visual options:
- https://github.com/MozillaReality/ContentFeed/issues/6#issuecomment-409829270

Anyway, ignore the placeholder design.

- https://mixedreality.mozilla.org/fxr/feed/?flavor=googlevr
- https://mixedreality.mozilla.org/fxr/feed/?flavor=noapi
- https://mixedreality.mozilla.org/fxr/feed/?flavor=oculusvr
- https://mixedreality.mozilla.org/fxr/feed/?flavor=svr
- https://mixedreality.mozilla.org/fxr/feed/?flavor=wavevr

FYI: I'll later want to change the URL to something else like https://mixedreality.mozilla.org/fxr/home/. Hope that's okay.

Wanted to kick off this conversation to determine the technical feasibility, best practices, and .

I worked on the Firefox Marketplace, and updating the "packaged app" via an `<iframe>` and local caching was something that wasn't anticipated when the project began. Anyway, the technology has improved a lot. And we can use Service Workers for offline capabilities, syncing clients with new content, and prefetching or even allowing download of content, images, videos, etc.

I have a lot of ideas here, but let's keep it simple for the MVP.

Opinions, concerns about replacing the `resource://android/assets/html/index.html`? I know currently the URL bar is blank now when you're on `index.html` page (thank you for that! :smile:). Anyway, should this landing page be called or be different from `about:home`? `about:xr`?

**Comment by cvan** [comment]
I have to test the latest Service Worker API support in Fennec/Gecko View, but I could include a basic Service Worker script for caching and rendering a skeleton of the content, etc. for the first version.

**Comment by cvan** [comment]
Also, feel free to change the priority, the title, or simplify the scope of my request here. I've marked this issue as `question` to solicit feedback. Let me know your thoughts. Thanks in advance!

**Comment by kearwood** [comment]
Perhaps Service Workers could be part of the solution, to allow downloading and caching for offline access?  Service Workers are possibly not functional yet with GeckoView.

**Comment by cvan** [comment]
@keianhzo: feel free to assign this to me. I have a page I can point this to. and it will use IndexedDB and Service Workers for caching and offline/network resilience.
