### ISSUE TITLE
[Pico]Support for UtoVR

### ISSUE THREAD

**Issue by picoxr** [MozillaReality/FirefoxReality#3244]
## Configuration

Firefox Reality version: Firefox Reality version 10-141060720
Firefox Reality build ID: 9b36c14

Hardware: 
Pico Neo2 - Android - 8.1.0
Pico G2 4K - Android - 8.1.0

## Steps to Reproduce

1. Open link http://en.utovr.com/video/212204643224.html from Firefox Reality
2. Observe player panel and see if VR goggles' icon appear at bottom-right side
3.

## Current Behavior

No VR goggles' icon can be found so can't be viewed in VR.

## Expected Behavior

It would be good to have UtoVR VR videos supported on Pico devices.

## Context

UtoVR VR http://en.utovr.com/ is a popular VR video platform in China.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by Softvision-GeluHaiduc** [comment]
I managed to reproduce the issue using the laster RC build Firefox Reality version 10 RC2 (17a313b4) installed on the Pico G2 4K headset.
[Here](https://drive.google.com/file/d/1wHzSC5K-WIvHHXptkTMu8DfW2IICc9kK/view?usp=sharing) is a video of the issue, at first when the page is being loaded the VR goggles, and the other 2 buttons on the right side of the video controls, appear and then they disappear if you resize the window horizontally to the max value part of the buttons can be seen again on the far right side of the video controls.

**Comment by MortimerGoro** [comment]
There are some more webcompat issues:
- The fullscreen icon is only visible in desktop mode (happens on both FxR and Oculus Browser)
- They are not using a video element so the media controls don't work (happens on both FxR and Oculus Browser)
- Even when enabling VR mode clicking on the VR googles, the resulting video is not equirectangular, you can move the video using the pointer. So none of the VR projections will match correctly until we can get the real equirectangular format (happens on both FxR and Oculus Browser)

We need address the webcompat issues with them
