### ISSUE TITLE
[Pico]Support for Realsee VR real-estate touring

### ISSUE THREAD

**Issue by picoxr** [MozillaReality/FirefoxReality#3245]
## Configuration

Firefox Reality version: Firefox Reality version 10-141060720
Firefox Reality build ID: 9b36c14

Hardware: 
Pico G2 4K - Android - 8.1.0
Pico Neo2 - Android - 8.1.0

## Steps to Reproduce

1. Open up link from Firefox Reality: [Realsee VR estate browsing](https://realsee.com/ke/1aGKl9JlL6R3Xx8d/gM86e42cYhqeYw5Kxd5rSaT3YGeClLDZ/#lianjia)
2. Find goggle icon
3. Click goggle icon to enter VR mode

## Current Behavior

Scene is displayed in stereo and landscape view

## Expected Behavior

It would be good to have Realsee VR real-estate touring supported on Pico devices.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
Looks like this doesn't support mobile VR devices. I see the same behavior in the Oculus Browser. I think they would need to add support for their pages to work.
