### ISSUE TITLE
The app crashes when disabling Pop-UP Blocking for a website

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3247]
**[Affected Versions]:**
- Firefox Reality version 10 RC2 (17a313b)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to a website with pop-ups ex: http://www.popuptest.com/popuptest1.html.
2. Click the Pop-UP Blocked icon from the Awesomebar.
3. Click the radio button to turn off Pop-UP Blocking.
4. Observe the behavior.

**[Expected results]:**
- The pop-up window is opened.

**[Actual results]:**
- The app crashes.

**[Notes]:**
- Attached are the screen recording, crash report along with the logcat for the issue:
	- Screen recording: [link](https://drive.google.com/open?id=1N4T1OhJpCm4vV5I4o8pxofU7Zs-y8HmD).
	- Crash Report: [link](https://crash-stats.mozilla.org/report/index/9e2dbfeb-f06a-4465-b2e6-40a6e0200426).
	- Logcat: [link](https://drive.google.com/open?id=1Lwpekiv0dUfLwcJy5YFAbRhAFTGqswrl).

**Comment by MortimerGoro** [comment]
Fixed via https://github.com/MozillaReality/FirefoxReality/pull/3251

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the Firefox Reality version 10 RC3 (5b346b6). The app no longer crashes when disabling Pop-UP Blocking for a website.

Tested on HTC Vive Focus (Android 7.1.2), HTC Vive Focus Plus (Android 7.1.2), Oculus Quest (Android 7.1.1), Oculus Go (Android 7.1.2), Pico G2 4K (Android 8.1.0) and Pico Neo 2 (Android - 8.1.0) devices.
