### ISSUE TITLE
move to `non_l10n.xml` URL constants: `DEFAULT_URL`, `ERROR_URL`

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#325]
now thanks to @keianhzo's awesome addition of [**`non_l10n.xml`**](https://github.com/MozillaReality/FirefoxReality/blob/69399df/app/src/main/res/values/non_I10n.xml#L9), we have a new place we could store the `resource://…` URLs constants, [`DEFAULT_URL` and `ERROR_URL` instead of in **`SessionStore.java`**](https://github.com/mozillareality/firefoxreality/blob/69399d/app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java#L45-L46).

**Comment by MortimerGoro** [comment]
This is already done
