### ISSUE TITLE
The window placeholder is wrongly displayed when trying to open a unsupported downloaded file in a New Tab/Window

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3252]
**[Affected Versions]:**
- Firefox Reality version 10-141060720 (fa882ff).

**[Affected Platforms]:**
- HTC Vive Plus - Android 7.1.2
- Pico Neo 2 - Android - 8.1.0
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on and the app is opened.
- Have an unsupported file downloaded ex: .zip 

**[Steps to reproduce]:**
1. Click the Downloads button from the tray.
2. Hover over a the file  from prerequisites and click the 3 dot menu button.
2. Click the "Open in a Tab" button.
3. Dismiss the prompt displayed.
4. Observe the window.

**[Expected results]:**
- No changes are visible since the unsupported file can't be opened.

**[Actual results]:**
- A new tab is created displaying only the window's gray placeholder.

**[Additional Notes]:**
- This issue is also reproducible when opening the unsupported file in a New Window using the 3 dot menu. A new window is created displaying only the window's gray placeholder.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1tLmjGBkg5mXc0vldubdhuPnewoPEeT7V).

**Comment by bluemarvin** [comment]
The gray window is actually `about:blank` and gets created when ever something is opened. I'm pretty sure desktop had the same behavior until very recently and I think they are actively closing the about:blank page when it is a file that can't be opened.

**Comment by daoshengmu** [comment]
It looks right to me. When opening a new tab for this zip file, the `about:blank` realizes this file type can't be supported, so it keeps showing a blank page. This behavior looks the same with FF 77 Mac OS.

**Comment by keianhzo** [comment]
We can close the tab if we want to, but the current behavior is more aligned with what Desktop does.

**Comment by bluemarvin** [comment]
> We can close the tab if we want to, but the current behavior is more aligned with what Desktop does.

Desktop closes the tab for me. I think it is fairly recent.
