### ISSUE TITLE
The downloaded file is still opened in a new tab if the app's permissions to access the external storage is denied

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3257]
**[Affected Versions]:**
- Firefox Reality version 10 RC2 (17a313b).

**[Affected Platforms]:**
- Pico Neo 2 - Android - 8.1.0
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on and the app is opened.
- Have an available file in the Downloads library.
- The Permissions to access External Storage is disabled.

**[Steps to reproduce]:**
1. Click the Downloads button from the tray.
2. Hover over a file and click the 3 dot menu button.
3. Click the "Open in a Tab" button.
4. Deny the permissions from the prompt displayed.
5. Observe the behavior.

**[Expected results]:**
- The file is not opened.

**[Actual results]:**
- The file is opened even if the access was denied.

**[Additional Notes]:**
- If the file is opened New Window using the 3 dot menu, the file is not displayed when denning permissions to access the external storage, but a new window is still created and the placeholder is displayed.
- On the HTC devices the "File location not found" page is displayed in the new tab when opening the file in a new tab.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1bWoVba4OMDpIdvuhrX7J0lzOhKGpsGJI).

**Comment by daoshengmu** [comment]
This is because we try to restore our sessions even the file opening permission is not allowed yet. We need to check if it gets the permission before loading this file. https://github.com/MozillaReality/FirefoxReality/blob/bab93d3948f311dfb0e6ee37d776a84e9188d271/app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java#L474

However, after doing this, the tab is still opened and jump to the default page.

```
 if ("file".equalsIgnoreCase(uri.getScheme())) {
                permission = mContext.checkSelfPermission(android.Manifest.permission.READ_EXTERNAL_STORAGE) == PackageManager.PERMISSION_GRANTED;
            }
```

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the Firefox Reality version 10 RC3 (5b346b6). The files are no longer opened in a new tab if permissions are denied.

Tested on HTC Vive Focus (Android 7.1.2), Oculus Quest (Android 7.1.1), and Pico Neo 2 (Android - 8.1.0) devices.
