### ISSUE TITLE
The description from the DRM prompt wrongly implies that DRM content is allowed only for that site

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3266]
**[Affected Versions]:**
- Firefox Reality version 10 RC2 (17a313b).

**[Affected Platforms]:**
- HTC Vive Focus - Android 7.1.2
- Oculus Quest - Android 7.1.1
- Pico Neo 2 - Android - 8.1.0

**[Prerequisites]:**
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**                                        
1. Play a video with DRM content (ex: https://www.ezdrm.com/html/drm-demos.asp).
2. Observe the description of the prompt displayed.

**[Expected results]:**
- It describes that allowing DRM content the setting is set for all websites.

**[Actual results]:**
- It describes that allowing DRM content the setting is set only for this website.

**[Notes]:**
- The description follows the current design, but by removing the "Enable DRM for all sites" checkbox, the description provided no longer applies since the setting is set globally. 
- Attached is a screen shots of the prompt:
![DescriptionGlobal](https://user-images.githubusercontent.com/40061643/80483188-440f3580-895e-11ea-8598-4ebe4d7ce002.jpg)

**Comment by keianhzo** [comment]
@emstanley I guess we could replace "permits this site" by "permits sites"?

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the Firefox Reality version 10 RC5 (e84d3c9). The "sites" string is now displayed instead of "this site".

Tested on HTC Vive Focus (Android 7.1.2) and Oculus Quest (Android 7.1.1).
