### ISSUE TITLE
The on screen controls in immersive mode do not have tooltips

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3269]
**[Affected Versions]:**
- Firefox Reality version 10 RC2 (17a313b4)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to a 360 video on YouTube and enter immersive mode.
2. Press the trigger button on the controller to have the on screen controls displayed.
3. Using the controller hover the pointer for more than ~1 second over each button.
4. Observe the tooltips.

**[Expected results]:**
- The tooltip for each button is displayed.

**[Actual results]:**
- The tooltip for the buttons are not displayed.

**[Notes]:**
- This [trello card](https://trello.com/c/DN6fXAmz/153-uis-40-tooltips) was used as reference.

**Comment by bluemarvin** [comment]
@keianhzo Is this a regression or did we never add tool tips for the media controls?

**Comment by keianhzo** [comment]
They never did. I guess we should go over all the UI elements and add the missing ones. That could be task for any of the upcoming polishing sprints.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 11-141770117 - 68128fbe installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the on screen controls in immersive video have tooltips.
I also encountered 2 new issues that are tracked in #3555 and #3556.
