### ISSUE TITLE
FxR is not reopened in immersive mode after a pause/resume

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3270]
**[Affected Versions]:**
- Firefox Reality version 10 RC2 (17a313b4)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to a 360 video on YouTube and enter immersive mode.
2. Press the Pico/Vive/Oculus button on the controller. (for HTC click the Home button)
3. Reopen the FxR app. (for Oculus click the resume button)
4. Observe the behaviour.

**[Expected results]:**
- The app is reopened in immersive mode.

**[Actual results]:**
- The app is reopened in normal browsing.

**[Notes]:**
- The issue is not reproducible in production, immersive mode is entered after reopening the app.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1ECM1go0ldV4klEvEUZ_eeSrYx13jkVKs/view?usp=sharing).

**Comment by bluemarvin** [comment]
This was done intentionally. Leaving FxR in fullscreen or immersive mode while paused caused all sorts of problems when the content process gets killed. It is now consistent with Immersive mode for WebVR/WebXR

**Comment by Softvision-GeluHaiduc** [comment]
Closing based on the last comment.
