### ISSUE TITLE
Sending the wrong google search code

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#3276]
## Configuration

Firefox Reality version: v10
Firefox Reality build ID: 2020-04-24

Hardware: Oculus Quest

## Steps to Reproduce

1. Perform a voice search
2. Look at the URL bar
3.

## Current Behavior
The search code sent is `firefox-b-1-m`

## Expected Behavior

Should have `firefox-b-1-o`

See also https://github.com/MozillaReality/FirefoxReality/issues/885

**Comment by mconnormoz** [comment]
https://github.com/mozilla-mobile/firefox-tv/issues/2462 might be the same underlying issue.
