### ISSUE TITLE
Errors occur when trying to play other videos if a DRM content video is playing 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3285]
**[Notes]:**
- In one attempt the content crashed: [link](https://crash-stats.mozilla.org/report/index/0b2f2c7f-b539-44da-b60d-b788a0200429).
- This issue is also reproducible if normal videos are already playing and then a DRM content video is played.

**[Affected Versions]:**
- Firefox Reality version 10 RC3 (5b346b6).

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the app is opened.
- DRM is enabled.

**[Steps to reproduce]:**
1. Play a video with DRM content (ex: https://www.ezdrm.com/html/drm-demos.asp).
2. Open a new window and navigate to Youtube.
3. Play a video and observe the behavior.

**[Expected results]:**
- The video is played.

**[Actual results]:**
- An error is displayed.

**[Additional Notes]:**
- In some attempts the issue is reproducible even after closing the window that is playing the video with DRM content.
- I managed to reproduce this issue on other websites besides Youtube, for example Twitter.
- I reproduced this issue also when playing a video with DRM content from Amazon Prime (on Desktop Mode), and trying to play other normal videos.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1ywNaNbTuJvi6lK3MhMr_rA6SbPZIGWG5).

**Comment by bluemarvin** [comment]
This reproduce in GVE. I'll file a bug with gecko media. Probably will not get fixed for v10 release.

**Comment by bluemarvin** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1634170

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the Firefox Reality version 10 RC5 (e84d3c9). Playing a DRM Video no longer breaks non-DRM video sites (verified on Youtube, Internet Archive, and downloaded videos).

Tested on HTC Vive Focus (Android 7.1.2), HTC Vive Focus Plus (Android 7.1.2), Oculus Quest (Android 7.1.1) and Oculus Go (Android 7.1.2).
