### ISSUE TITLE
The image for VR videos from CNN is not displayed

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3296]
**[Affected Versions]:**
- Firefox Reality version 10 RC3 (5b346b6).

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo 2 - Android - 8.1.0

**[Prerequisites]:**
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**
1. Navigate on https://edition.cnn.com/ and play a VR video (ex: [link](https://edition.cnn.com/2018/11/09/vr/wwi-anniversary-planes-vr/index.html)).
2. Observe the behavior.

**[Expected results]:**
- The video and sound are correctly played.

**[Actual results]:**
- The video is not displayed, just the sound is played.

**[Notes]:**
- This issue is reproducible in immersive and normal browsing.
- This issue is also reproducible if WebXR is disabled.
- This issue is not reproducible on Oculus browser.
- This issue is not reproducible with normal videos.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1hssrxYOL63AOpZA45mjYXF7kyobeR6m3).

**Comment by Softvision-RemusDranca** [comment]
One more thing that I think is worth mentioning for the CNN website is that the WebXR icon is always displayed in the Awesomebar when navigating it. 
Should I open a new issue for this behaviour or is it expected?

**Comment by bluemarvin** [comment]
CNN is probably still using WebVR. In that case the Icon will be visible much earlier.

**Comment by bluemarvin** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1634578
