### ISSUE TITLE
loading a page crashes the app if not connected to wifi

### ISSUE THREAD

**Issue by joshmarinacci** [MozillaReality/FirefoxReality#33]
I just installed the new build on my Go and it crashed as soon as I clicked on one of the starting links. I realized I didn't have wifi on. Instead it should tell me that I need to connect to the internet.

**Comment by bluemarvin** [comment]
This only happens on Oculus Go and looks like it may be an Android bug specific to the Go version of Android. Will probably need to engage with Oculus to resolve.

**Comment by MortimerGoro** [comment]
Error pages already available
