### ISSUE TITLE
Improve video and control playback support for video sites (flat)

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#330]
Hardware: All
Steps to Reproduce: Try to use video sites
Actual Behavior: Laggy controls, missed clicks, confusing interaction, no support for 180/360 videos
Expected Behavior: Site offered controls work intuitively for user, whether from Desktop or Mobile pages
Recommendation: Test video controls on following sites, select to serve Desktop or Mobile page as appropriate for best experience. Open site specific bug as needed, link to list below.

Video Sites:
- Within - https://www.with.in/
- YouTube - https://www.youtube.com/
- YouTube VR (180/360) - https://www.youtube.com/channel/UCzuqhhs6NWbgTzMuM09WKDQ
- Vimeo - https://vimeo.com/channels/staffpicks
- Vimeo VR (180/360) - https://vimeo.com/channels/360vr
- 360cities - https://www.360cities.net/
- NYT 360 Video - https://www.nytimes.com/video/360-video
- CNN VR - https://www.cnn.com/vr

@thenadj - list of 360 video sites to test with.

**Comment by nancyhang** [comment]
Dependent on https://github.com/MozillaReality/FirefoxReality/issues/274

**Comment by larsbergstrom** [comment]
@avrignaud this is looking pretty good now. Can we close?

**Comment by avrignaud** [comment]
Tentatively yes... the combo of UA and viewport changes seem to be helping. But we should keep eye out for different variants of video playback issues as we polish that for 1.1.

**Comment by thenadj** [comment]
Never mind. We found a new one. Using this for design updates:
https://github.com/MozillaReality/FirefoxReality/issues/344
