### ISSUE TITLE
WebXR Interstitial shows Focus Plus controller image when using Focus headset.

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#3306]
## Configuration

Firefox Reality version: v.10
Firefox Reality build ID: 

Hardware: 
Focus

## Steps to Reproduce

1. Using Focus headset and enter the immersive mode from a [WebXR sample](https://immersive-web.github.io/webxr-samples/input-profiles.html) at the first time of the application launches.
2. You should be able to see a Focus Plus controller image.

## Current Behavior

Showing a Focus Plus controller image instead of a Focus controller.

## Expected Behavior

Showing a Focus controller image.

## Possible Solution

Add an image for Focus ?

```
```

</details>

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using Firefox Reality RC6 (140fb70). The Focus Plus controller image is now displayed for WebXR Interstitial.
However, it seems that the arrow pointing to the "Exit WebXR" button is not displayed right on the button. @daoshengmu is this intended?
![FocusInterstitial](https://user-images.githubusercontent.com/40061643/82235180-1012a900-993b-11ea-92a1-9188d3068d8a.png)

**Comment by daoshengmu** [comment]
Yes. that's what can do right now. Because the arrow color is so similar to the controller's. If we put it too close to the `back` button of a controller, users can't recognize it.

**Comment by Softvision-RemusDranca** [comment]
I see. Yes, that is what I was referring to. Thanks for explaining it!
