### ISSUE TITLE
G2 4k shows up as "Pico Pico G2 4k" in send to device

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#3307]
## Configuration

Firefox Reality version: 10
Firefox Reality build ID: p3

Hardware: Pico G2 4k

## Steps to Reproduce

1. Sign up with a firefox account on the g2 in firefox reality
2. Attempt to send to device from another instance of firefox

## Current Behavior

Shows up as "Pico Pico G2 4k"

## Expected Behavior

Shows up as "Pico G2 4k"

**Comment by larsbergstrom** [comment]
![Screen Shot 2020-05-01 at 5 09 57 PM](https://user-images.githubusercontent.com/475847/80845412-c0a84b00-8bce-11ea-8506-d4c1eac9e4aa.png)

**Comment by bluemarvin** [comment]
That's how it reports it self unfortunately. The Neo 2 is `Pico Pico Neo 2`. It's the manufacturer `Pico` + device name `Pico Neo 2`. It's the same in Android Studio:
![image](https://user-images.githubusercontent.com/3066/80846994-f2b3b000-8bc2-11ea-8aa5-7dbbd106ca11.png)

**Comment by philip-lamb** [comment]
One potential solution would be to examine the device string and if the manufacturer string is repeated as the first word of the device string, to left-trim the device string to the second word onwards.

**Comment by bluemarvin** [comment]
FxR doesn't generate the string. An issue can be filed against Firefox Accounts. There is currently no API for overriding the device name used by FxA.

**Comment by bluemarvin** [comment]
See https://github.com/MozillaReality/FirefoxReality/issues/2494

**Comment by larsbergstrom** [comment]
Makes sense - thanks, @bluemarvin!
