### ISSUE TITLE
Add Exit Button to Mini Tray

### ISSUE THREAD

**Issue by nancyhang** [MozillaReality/FirefoxReality#331]

**Comment by MortimerGoro** [comment]
What does that exit button do?

**Comment by nancyhang** [comment]
@avrignaud

**Comment by avrignaud** [comment]
It exits Firefox gracefully, returning the user to the headset launcher/home environment. Right now the only way a user can quit is by force killing the process - there's no "Quit"

**Comment by thenadj** [comment]
[UIS-26 Mini Tray_004.pdf](https://github.com/MozillaReality/FirefoxReality/files/2276653/UIS-26.Mini.Tray_004.pdf)
[icon-tray-exit.svg.zip](https://github.com/MozillaReality/FirefoxReality/files/2276657/icon-tray-exit.svg.zip)

Attached is the spec for the mini tray with the exit button and the SVG for the icon.

**Comment by thenadj** [comment]
[button-tray-all.svg.zip](https://github.com/MozillaReality/FirefoxReality/files/2276663/button-tray-all.svg.zip)
And the tray buttons (all in one).

**Comment by MortimerGoro** [comment]
Some feedback about the exit button:

- I confuse that icon with a Share icon. iPhone uses a similar one  for sharing.
- We need some confirmation dialog. Users may hit that button without knowing what it does or my mistake. 
- Something we need to check, is the exit action compliant with all the platform guidelines? Some platform reviewers may obligate to use their universal way to exit from the apps and reject this.

**Comment by keianhzo** [comment]
I thought about the confirmation dialog too but oculus has another confirmation dialog when you exit the app and thought that might be annoying for the user to say yes to two dialogs to close the app. But I don't know if other platforms have that dialog too.

**Comment by MortimerGoro** [comment]
yes, on oculus we should use the native dialog. It's already working via the back button. I think that it should work with long back press too? without doing all the backs to clean the navigation stack.

On other platforms (e.g. Vive) we don´t have that dialog

**Comment by keianhzo** [comment]
@thenadj I'll need the dialog spec for user's confirmation after clicking on the exit button.

**Comment by thenadj** [comment]
@keianhzo  @MortimerGoro Ok, didn't know that other platforms don't have that confirm dialog. We'll create one! And I know about the possible confusion with the exit icon (similar to share) but it's the standard exit icon if you google it. X would imply closing tray, not whole app and it's a bit overused in the app. We might change it in the future but let's see if this works for now.

**Comment by nancyhang** [comment]
@keianhzo @MortimerGoro please hold off from executing this. @avrignaud is reviewing this and this may not make it to v1.0

**Comment by avrignaud** [comment]
Looks like there's been a bit of confusion here on multiple levels. At the end of the day, the fact that Android doesn't require an "Exit" button, and the system handles it for us suggests we do not need to implement ourselves. So for now, let's *not* do this for 1.0, and we can revisit as a possible 1.1 feature if needed.

**Comment by cvan** [comment]
I know @avrignaud has already commented on this thread (thanks!), but it appears there are some ergonomics issues/UX confusion: https://www.reddit.com/r/OculusGo/comments/9gunfv/firefox_reality_10_now_available_in_store/e67ndx7/

**Comment by philip-lamb** [comment]
Closing as the Android model is that its up to the system to terminate the app. Currently, all platforms provide a system home button which is the preferred exit method.
