### ISSUE TITLE
Add initial launch splash Image

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#332]
We need to add a splash image with the FxR logo for the initial launch.

This will help to to hide the environment loading popping. After the loading time optimizations (< 2 sec to show the meadow) we can have a nice transition after showing the splash.

**Comment by MortimerGoro** [comment]
@thenadj @avrignaud Is the design ready for this? Should we use the FxR logo?

**Comment by cvan** [comment]
After the design is ready, I can implement this in the new tab/launch page for the first-run experience.

I have a mock I did, but I could use @thenadj's input on the gradient and transitions:

![](https://user-images.githubusercontent.com/203725/43567042-24aae516-95f6-11e8-9a78-e0cdf124d33b.png)

**Comment by thenadj** [comment]
[Splash Screen.png.zip](https://github.com/MozillaReality/FirefoxReality/files/2276744/Splash.Screen.png.zip)
@cvan Use this. I am also emailing you the Oculus store assets so that you have the background for future reference.

**Comment by MortimerGoro** [comment]
@thenadj How should I blend the image with the background color while showing the splash? Because of the gradient the image will look like a rectangle when I set a solid color with the VR background. Is it possible to get a image that finishes in a solid color on all the edges or a transparent one? Check what Oculus and Vive do.

Also another question, when showing this image should it be in a static position (only visible if the user looks at the initial position) or should it follow the user orientation (aka always visible)?

**Comment by thenadj** [comment]
@MortimerGoro Please use the attached version. It's just the logo on a transparent background. That way you can put it on top of any background. And I think positioning so it follows the user would be good, that way the user will always see it and not miss it if they look in the opposite direction. 
But I reserve the right to change my mind once I see it in the build. ;) 

[FxR_Logo_Lockup_Transparent.png.zip](https://github.com/MozillaReality/FirefoxReality/files/2281166/FxR_Logo_Lockup_Transparent.png.zip)
