### ISSUE TITLE
Some pages opened in a new tab fail to render

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#3336]
## Configuration

Firefox Reality version: 10 
Firefox Reality build ID: 

Hardware: All

## Steps to Reproduce

1. Visit https://playcanvas.com/explore and open one of the example such as `Orbital Survival`

## Current Behavior

A new tab is created but the gray default window is never replace with the newly opened page.
## Expected Behavior

The new tab is opened and the game is playable.

## Possible Solution

This is an issue in Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1635597
The `GeckoSession.ContentDelegate.onFirstContentfulPaint()` fails to be called if the parent page contains no content as is the case with these demos. FxR either needs a different event to know when the page has painted some content or the call back needs to support child iframe pages as well. Another possible solution is for the Gecko compositor to render a place holder until content is actually painted.

**Comment by bluemarvin** [comment]
Fixed in latest nightly https://bugzilla.mozilla.org/show_bug.cgi?id=1635597#c10

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 11-141760226 - 71aabd05 installed on the HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, a new tab is opened and the games are playable.
