### ISSUE TITLE
music.amazon.com - Next song throws an error and no longer plays

### ISSUE THREAD

**Issue by karlcow** [MozillaReality/FirefoxReality#3338]
## Configuration

Firefox Reality version: Firefox Reality 9 (2020-03-10)
Firefox Reality build ID: 
Browser / Version: 
Operating System: 

Hardware: Oculus Go

## Steps to Reproduce

1. go https://music.amazon.com/
2. play song
3.

## Current Behavior

After the first audio played, the next audio thrown an error.

## Expected Behavior

audio is playing

## Context

VPN active poiting to USA
Note:

    In VR - Firefox Reality browser - Desktop mode must be enabled in order to access Amazon music. Also sign in required.
    The issue is not reproducible on Firefox Nightly Desktop.
    Even after dismissing the error the audio no longer plays and in order to play a song the page needs to be refreshed.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
I tested this in v10 on both Go and Quest and was not able to reproduce. v10 is expected to be released May 15 (Friday).

**Comment by karlcow** [comment]
thanks.

**Comment by bluemarvin** [comment]
Closed since I couldn't reproduce. Please re-open if still reproducible.
