### ISSUE TITLE
Use Gecko as HTTP client for Glean

### ISSUE THREAD

**Issue by pocmo** [MozillaReality/FirefoxReality#3339]
I saw that we are initializing Glean with the default client - which means it will be using `HttpUrlConnection`.

In AC we have an adapter that wraps GeckoView and will use Gecko instead of `HttpUrlConnection`. This is what Fenix is using as well. I assume that is something Firefox Reality would want too.

There are two options:
* Use the `Client` implementation from AC. However since Firefox Reality and AC are not synchronized on GeckoView versions this could cause breakage if the API in GeckoView changes in a breaking way.
* Add a simple `Client` implementation wrapping GeckoView directly to Firefox Reality. Even in AC the code is minimal: https://github.com/mozilla-mobile/android-components/blob/master/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt

**Comment by pocmo** [comment]
If you agree that this is worthwhile then I can try writing a patch for this. :)

**Comment by pocmo** [comment]
Just saw that there's already a `GeckoViewFetchClient` in the repo. So we could just use that!

https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/common/shared/org/mozilla/vrbrowser/browser/engine/GeckoViewFetchClient.kt

**Comment by keianhzo** [comment]
Thanks @pocmo! Yes, we are already using the `GeckoWebExecutor` everywhere, I think this was missing because the default Glean configuration used `HttpUrlConnection`. This should be addressed by #3498 as we migrate to AC 44 there and it forced us to do so.

**Comment by pocmo** [comment]
Yeah, afaik in the lastest AC version we will require you to explicitly pass in a client.
