### ISSUE TITLE
Remove `dom.vr.require-gesture: false` on release

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/FirefoxReality#3348]
## Configuration

Firefox Reality version: 10 (master)
Firefox Reality build ID: ea7a9e07

Hardware: Oculus Quest

## Steps to Reproduce

1. Visit https://autoenter-xr.glitch.me
2. It will "auto-enter" XR

## Current Behavior
It successfully trigger the XR interstitial to enter XR without requiring user gesture

## Expected Behavior
You should not be able to start a XR session without triggering an user gesture (Unless you have the `dom.vr.require-gesture` set to false.

## Possible Solution
Set `dom.vr.require-gesture` set to true by default on releases.

**Comment by bluemarvin** [comment]
Something must have changed in Gecko because we only set it if it is in the extras of the intent.

**Comment by fernandojsg** [comment]
I believe @MortimerGoro could have more info on that

**Comment by bluemarvin** [comment]
We can't ship with this enabled, I'll look into today.
