### ISSUE TITLE
Replace magic numbers with named constants 

### ISSUE THREAD

**Issue by TrevorFSmith** [MozillaReality/FirefoxReality#335]
Hardware:
All

Steps to Reproduce:
Read the source code.

Actual Behavior:
There are magic numbers in several places in the code.

Expected Behavior:
Named constants and DRY

Recommendation:
Change out magic numbers for named constants.

**Comment by nancyhang** [comment]
@TrevorFSmith Can you please provide some examples?

**Comment by TrevorFSmith** [comment]
If the devs can't find the then I can't really help them.

**Comment by TrevorFSmith** [comment]
Ha! I think I found the "problem" which is that AndroidStudio displays the values of resource defined numbers in place of the resource names. So I was looking at the code and wondering why in the world there were magic numbers all over the place when in fact the IDE was simply displaying the values of the resources. 😂
