### ISSUE TITLE
Add an option to clear history (and cache, cookies, etc.)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#336]
It would be nice if there was an option to clear history. It is not a problem currently, as there are not multiple tabs/windows. But a link could be inferred as `:visited` or an active session (e.g., Google, Facebook, YouTube) could be active when a user closes the browser or leaves it unattended and returns.

**Comment by avrignaud** [comment]
Yep, good catch! Will put on list for 1.1 consideration.

**Comment by cvan** [comment]
For v1.1 this seems quite important - possibly P1?

**Comment by avrignaud** [comment]
Agree! Just note we're only assigning priorities to 1.0 bugs right now. Everything marked 1.1 will be re-triaged after we launch.

**Comment by cvan** [comment]
do we have a design spec for this?

**Comment by avrignaud** [comment]
@bluemarvin Can GV clear history if we have the option/button in settings?

**Comment by cvan** [comment]
Not yet but it will. GeckoView's History API is actively being developed but not finished yet. See https://bugzilla.mozilla.org/show_bug.cgi?id=1494713, the platform bug.

Issue #614 tracks the FxR implementation of using the GeckoView android-components API.

**Comment by avrignaud** [comment]
Moving to backlog - won't make 1.1

**Comment by cvan** [comment]
> Moving to backlog - won't make 1.1

Moving History to 1.1 or a "Clear All" button? Last time I checked, unbookmarking items from History and removing items from  History were in the design specs. If we introduce History in 1.1, users need the ability to remove items from their History.

**Comment by avrignaud** [comment]
I don't think bookmarking and history is on track for 1.1 - but asked @keianhzo for a quick update.

**Comment by cvan** [comment]
> I don't think bookmarking and history is on track for 1.1 - but asked @keianhzo for a quick update.

is there a Doc or a list I can refer to for 1.1?

**Comment by avrignaud** [comment]
@cvan Unfortunately, not. The most up to date status is in the GH issues, but we are working on triaging and getting better at making the current project board for 1.1 reflect reality. Going forward, the goal is to have a complete view of current version in the "#.# Project Board" and then a second Product Planning board with features spread out over the next few versions.

**Comment by jvonitter** [comment]
needed by #1243

**Comment by ScottWitte** [comment]
I'll add my vote for the need to add cache clearing (separate from history clearing). As a developer, I need to be certain that the changes I make in code and upload are indeed being used when viewing in FxR. If a change doesn't work, is it because I didn't really fix it or the old code is stuck in cache?

BTW, I really hate Safari wiping out everything when I just want a clean cache. Please don't do THAT.

**Comment by jvonitter** [comment]
@ScottWitte we can look at adding the ability to clear cache separately from history as a developer option. I'll make a new ticket for that, since this is going to just cover history.

**Comment by jvonitter** [comment]
User flow for seeing history, clearing history and changing history settings: https://trello.com/c/VUiURGJ1/337-uf-62-history

**Comment by jvonitter** [comment]
Spec is complete! https://trello.com/c/CPyXxcZp/371-uis-78-history

**Comment by jvonitter** [comment]
Spec has been updated with additional options. see https://trello.com/c/NcTaLGB6/412-uf-76-clear-cache-setting

**Comment by keianhzo** [comment]
Closing as this has been merged as part of https://github.com/MozillaReality/FirefoxReality/pull/1517

There is not API in GV at the moment to get the size of the cache so we had to strip that part of the spec.
