### ISSUE TITLE
[Intermittent] The app freezes when playing krpano examples and WebXR content one after another

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3363]
**[Affected Versions]:**
- Firefox Reality version 10 RC5 (e84d3c92)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- Pico Neo2 - Android 8.1.0
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Play the "Hello WebXR" card from Interactive Experience.
2. Exit Hello WebXR and navigate to krpano website.
3. Enter in VR in one of the examples available (example: [link](https://krpano.com/releases/1.20.6/viewer/krpano.html?xml=examples/demotour-apartment/tour.xml)).
4. Navigate the page while in immersive mode and observe the behavior.

**[Expected results]:**
- The VR environment can be navigated.

**[Actual results]:**
- The app freezes, UI glitches are displayed and nothing happens while pressing the controller buttons.

**[Notes]:**
- In some attempts on the HTC Vive Focus Plus device the content crashed after pressing the Back button on the controller [link](https://crash-stats.mozilla.org/report/index/c200075d-bd6a-4549-9834-99b880200512) for the crash report.
- I reproduced this issue in 8 attempts out of 10.
- In some attempts the app froze when exiting immersive mode.
- I was able to reproduce this issue even after disabling WebXR option from settings while having the two pages opened..
- Attached are the screen recording and the logcat of the issue:
	- Screen Recording: [link](https://drive.google.com/open?id=1BbKLG1cRDqjkn3eTjaUqT1xNWA3yKrbi).
	- Logcat: [link](https://drive.google.com/open?id=127zzl4ZQHyV01ZLQFNEWY-NLIrkylqlv).

**Comment by daoshengmu** [comment]
I can't reproduce it on my Quest, Focus Plus, and Focus after trying more ten times.

**Comment by bluemarvin** [comment]
The crash looks like it is https://bugzilla.mozilla.org/show_bug.cgi?id=1634259

**Comment by bluemarvin** [comment]
The freezing is cause by `GeckoDisplay.surfaceChanged(surface, left, top, width, height);` never returning.

**Comment by MortimerGoro** [comment]
The freeze is fixed by #3382

The glitches are a different issue, I created this GV ticket:
https://bugzilla.mozilla.org/show_bug.cgi?id=1638414

**Comment by Softvision-RemusDranca** [comment]
I've retested this issue and I was still able to reproduce it using Firefox Reality RC6 (140fb70) but only after quitting and resuming the app and then trying to navigate the krpano example.
	- In most of the cases I had to quit and reopen the app 2 times.
	- I reproduced the issue consistently on Oculus Go and Oculus Quest, and once on Pico Neo2 device.
	- While testing without quiting and resuming the app, the krpano website only displayed glitches, but the app didn't freeze.
	- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1jq0Vkb2B0nzaUY6EmEGgdOSu2g-IxR8a).
	
**Note:** I had to cut the video short because after the app is completely frozen the device is not responding when trying to save the screen recording, I get this error: "adb: error: failed to get feature set: no devices/emulators found".

**Comment by bluemarvin** [comment]
There were memory leaks in v10 that should be fixed now. Is it possible to retest this?

**Comment by Softvision-RemusDranca** [comment]
I was still able to reproduce this issue using Firefox Reality version 10.2 RC3 (7523a32d), but only in the scenarios mentioned in the above [comment](https://github.com/MozillaReality/FirefoxReality/issues/3363#issuecomment-630263056) and after multiple attempts and more easily if there are 3 windows opened with webxr content. 
I think that the content of the other webxr pages while they are in a loading state is highly affecting this issue, especially when I change the scenes in the krpano examples.  Could this be an issue related to GPU janking?
