### ISSUE TITLE
Add missing supported languages to the Display Language list

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#3368]
**Is your feature request related to a problem? Please describe.**
We have translations for more languages that we are exposing in the language display list. We are currently missing:
- Spanish from Spain (es-ES)
- Norwegian Nynorsk (nn-rNO)
- English UK (en-GB)

**Describe the solution you'd like**
We just need to add those to the Display and Voice language lists.

**Describe alternatives you've considered**

**Additional context**

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 11-141402320 (eda7d955) installed on the Oculus Go, HTC Vive Focus Plus and Pico G2 4K headsets.
Now, the English (UK), Spanish (Spain), Norwegian (Nynorsk) languages appear in the Voice and Display language lists.
