### ISSUE TITLE
MSE Support For Firefox Reality

### ISSUE THREAD

**Issue by fyuvb** [MozillaReality/FirefoxReality#3371]
**Is your feature request related to a problem? Please describe.**
Currently Firefox Reality could directly play a m3u8 link but it seemed not support MSE ( Media Source Extension ). This would block certain use cases related to video texture in WebVR like fine control of video source for video texture.

**Describe the solution you'd like**
Support MSE in Firefox Reality.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bluemarvin** [comment]
Firefox Reality does support MSE. If you have a specific example of content that does not work please provide a link.

**Comment by fyuvb** [comment]
Thank you for your quick response. Sry it was a false alarm. We did verified carefully and it should be a problem in our side. Many thanks!
