### ISSUE TITLE
[Desktop Mode] The other Google searches can no longer be opened after navigating back from a opened one

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3374]
**[Affected Versions]:**
- Firefox Reality version 10 RC5 (e84d3c92)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- Pico Neo2 - Android 8.1.0
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Click the hamburger menu and select the "Desktop Mode" option.
2. Focus the Awesomebar and perform a Google search.
3. Open a one of the search results.
4. Click the "Back" navigation button.
5. Click on the other available searches and observe the behavior.

**[Expected results]:**
- The websites are opened.

**[Actual results]:**
- Nothing happens.

**[Notes]:**
- The other pages with other searches cannot be opened as well.
- The issue is reproducible if the same Google search is performed in the same or other window that has Desktop Mode on, even without having to navigate back from a opened search result.
- In a few attempts some of the searches results could be opened. 
- I a few attempts the issue was only reproducible after opening 2 searches and navigating back to the google search results page.
- The issue is not reproducible if the same search result is opened.
- The issue is not reproducible in the production version of the app (v9).
- Attached is a screen recording and a logcat of the issue:
	- Screen Recording: [link](https://drive.google.com/open?id=1K1xvlATm_P55CkLWJTDhkP7CQC4v2u3U).
	- Logcat: [link](https://drive.google.com/open?id=1N4oXsnX5B_hUlXvcj33X7kAhhx5fNoUf).

**Comment by bluemarvin** [comment]
Looks like this is https://bugzilla.mozilla.org/show_bug.cgi?id=1637113

Moving to latest GeckoView nightly seems to fix the issue.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using Firefox Reality RC6 (140fb70). The Google searches can now be opened after navigating back from a opened one, while in Desktop Mode.

Tested on HTC Vive Focus (Android 7.1.2), Oculus Quest (Android 7.1.1), and Pico Neo 2 (Android - 8.1.0) devices.
