### ISSUE TITLE
IInactive window and nfinite WebXR spinner after showing the Oculus menu in multiwindow

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#3375]
STR:
- Open https://webvr.info/samples/03-vr-presentation.html in two different windows
- Enter VR in one of them
- Show the Oculus menu and press continue
- The other vr sample is not resumed, if you click enter VR you get a infinite spinner

**Comment by Softvision-RemusDranca** [comment]
I've retested this issue and I was not able to reproduce it on Oculus Quest.
On Oculus Go I can not enter immersive mode while https://webvr.info/samples/03-vr-presentation.html is opened in 2 different windows.  The infinite WebXR spinner is displayed when trying to enter VR even without showing the Oculus menu, screen recording of the issue: [link](https://drive.google.com/open?id=1pUsyRk9ry3UsSGqdYMUG6RHYqqByvNwb).
However, I was not able to reproduce this issue on other pages, on Oculus Go.
@MortimerGoro should I log a new issue for this behaviour, for this specific page?
