### ISSUE TITLE
Less intrusive browser events notifications

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#3379]
**Is your feature request related to a problem? Please describe.**
The only way we currently have of notifying the user of browser events is showing a modal alert that takes over the focus. This might be a good use case for things that require the user to take immediate action (ie. the page requests a geolocation permission or it shows a confirm dialog) but it doesn't work as well when we just want to inform the user of an event that doesn't require immediate interaction (ie. there was an error loading an extension)

**Describe the solution you'd like**
A less intrusive way of notifying users of browser events would be to show a bottom-up sliding panel at the bottom of the browser window that: 
- Disappears after a few seconds if it's just an informative event 
- Can be manually dismissed using a close button (ie. "x" icon) 
- Stays visible until the user either closes it or executes the requested action if it requires use interaction.

This would cover most of the notification scenarios (permission requests, popups, session crash, slow script loading, jank detection, etc) that we currently have in a less intrusive way.

**Comment by MortimerGoro** [comment]
+1 for this, I mentioned similar concerns a long time ago, I don't rememeber If we had an issue for this already or it was a comment.
