### ISSUE TITLE
Use GeckoWebExecutor instead of AndroidDownloadManager

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#3396]
**Is your feature request related to a problem? Please describe.**
FxR currently uses the android download manager. It should be using the GeckoWebExecutor. In an ideal world, FxR would only use the Gecko network stack for all network operations.

Ensure https://github.com/MozillaReality/FirefoxReality/issues/3465 is fixed as part of this work which means supporting `blob:https://url` downloads.

**Comment by keianhzo** [comment]
AC has a [FetchDownloadManager](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/FetchDownloadManager.kt) that supports using a `GeckoWebExecutor `based Http client. We are currently blocked by the lack of support for dowloads management (get/remove) and downloads persistance. It's currently just in memory (ie. if you reboot/app process stops, the download is not resumed).

**Comment by bluemarvin** [comment]
@keianhzo Can you file issues against it for what we would need to use it when you have the time?

**Comment by keianhzo** [comment]
https://github.com/mozilla-mobile/android-components/issues/7227
