### ISSUE TITLE
[Enhancement] The user should have the possibility of picking different colors for the pointer

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3397]
**[Affected Versions]:**
- Firefox Reality version 11-141402320 (eda7d955)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Open the "Controller Options” card from Settings.
2. Observe the color available in the “Pointer Colour” section.

**[Expected results]:**
- The user should have more color options for the pointer or have a color picker to choose a color.

**[Actual results]:**
- There are 2 options available: “White” and “Purple”.

**[Notes]:**
![org mozilla vrbrowser-20200520-150843](https://user-images.githubusercontent.com/51400741/82445323-440ddb80-9aad-11ea-96b0-1152c308338f.jpg)

**Comment by feiss** [comment]
Color controls alternatives:

![style1](https://user-images.githubusercontent.com/359872/89291311-9f864900-d65a-11ea-82c8-23243745993b.png)
![style2](https://user-images.githubusercontent.com/359872/89291317-a0b77600-d65a-11ea-9e72-455d4b843c7a.png)
![style3](https://user-images.githubusercontent.com/359872/89291324-a1500c80-d65a-11ea-9cec-de75e28850a6.png)

I vote for the second. The actual pointer color should change as soon as the user changes the color controls

**Comment by keianhzo** [comment]
For it's simplicity I'd say I like the first one the best.

**Comment by Softvision-GeluHaiduc** [comment]
+1 for the first one, but there should also be an option for black and white on the color bar

**Comment by feiss** [comment]
👍 

![style1](https://user-images.githubusercontent.com/359872/89299480-014cb000-d667-11ea-9808-5096f3fcf445.png)

**Comment by feiss** [comment]
@keianhzo @bluemarvin how you plan to make the color ramp? I can make a SVG, but maybe you want to render it by code.

**Comment by keianhzo** [comment]
I think is probably better to create an specific widget to draw the color ramp and the caret.
