### ISSUE TITLE
[Pico] Controller display laser of both controller instead of one

### ISSUE THREAD

**Issue by picoxr** [MozillaReality/FirefoxReality#3404]
## Configuration

Firefox Reality version: 10-rc7
Firefox Reality build ID: bda5ecf

Hardware: 
Pico Neo2 - Android 8.1.0 - PUI 3.11.3

## Steps to Reproduce

1. Connect both controllers
2. Launch Firefox Reality
3. Observe controller model in main scene.

## Current Behavior

White laser column appear on both controllers' tips.

## Expected Behavior

White laser column appear on current active controller's side.

## Context

Is this mechanism by design? Oculus v10 is behaving the same.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
Both controllers are active in FxR. This is to support two hand typing.
