### ISSUE TITLE
[Pico] Guardian can't be re-created when walking out of current boundary

### ISSUE THREAD

**Issue by picoxr** [MozillaReality/FirefoxReality#3405]
## Configuration

Firefox Reality version: 10-rc7
Firefox Reality build ID: bda5ecf

Hardware: 
Pico Neo2 - Android 8.1.0 - PUI 3.11.3

## Steps to Reproduce

1. Launch Firefox Reality
2. Walk out of current boundary and see warning prompt "You have Left Your Play Boundary"
3. Click "Confirm" button

## Current Behavior

Guardian setting menu doesn't show up after clicking "Confirm"

## Expected Behavior

Guardian setting menu show up after clicking "Confirm" so user can click boundary

## Possible Solution

Please confirm if current Pico Android Java SDK is ver 1.3.3 b35 (Firefox preview version), latest online SDK is ver 1.3.3 b39. This might be an issue with SDK preview version b35.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
I don't see any way to tell b35 from b39. We are using the SDK downloaded from the website. The file is called `PicoVRNativeSDK_1.3.3.zip`

**Comment by zec37** [comment]
Version from website is b39. It can be verified by checking folder name inside the zip file as "1.3.3＃39-2004031000", where "1.3.3＃39" indicates build code following #.

**Comment by bluemarvin** [comment]
I have verified we are using `1.3.3#39-2004031000` for our release builds.

**Comment by picoxr** [comment]
We found Confirm Button is blocked in dispatchKeyEvent. This should be the cause of this issue.
`    @Override
    public boolean dispatchKeyEvent(KeyEvent event) {
        if (event.getKeyCode() == CONFIRM_BUTTON) {
            int buttons = 0;
            buttons |= event.getAction() == KeyEvent.ACTION_DOWN ? BUTTON_TRIGGER : 0;
            nativeUpdateControllerState(GAZE_INDEX, true, buttons, 0, 0, 0, false);
            return true;
        }

        return super.dispatchKeyEvent(event);
    }`

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 11-141551002 (8f4de9a4) installed on the Pico Neo2 headset.
Now, the guardian can be re-created when walking out of the current boundary.
