### ISSUE TITLE
Please update manifests for APK build per feedback from Oculus Store checker

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#341]
## Hardware
Oculus Go

## Steps to Reproduce
Upload oculusvr-release-signed apk from TC group ID `EAl9SPtYTTevknbQ9zgg5A` to store.

## Current Behavior
Errors generated during APK validation (see details below). 

## Expected Behavior
No errors in APK validation

## Possible Solution
@bluemarvin Do you have some time to make these changes to the manifest for the Oculus builds? I'm happy to do it otherwise. Would like to do this so we can test out Alpha channel builds.

## Error Logs and Stack Traces

<details open>
APK install location should be auto (android:installLocation in AndroidManifest.xml). See documentation at: https://developer.oculus.com/documentation/publish/latest/concepts/publish-mobile-manifest/

Exclude from Recents (android:excludeFromRecents in AndroidManifest.xml) must be set to true.

APK launch mode is singleInstance, but must be singleTask (android:launchMode in AndroidManifest.xml).

APK main activity intent filter set to android.intent.category.LAUNCHER, but must be android.intent.category.INFO. Your app must only appear in Oculus Home. It must not appear in the phone’s launcher.

APK main activity intent filter set to android.intent.category.MULTIWINDOW_LAUNCHER, but must be android.intent.category.INFO. Your app must only appear in Oculus Home. It must not appear in the phone’s launcher.

APK main activity intent filter set to android.intent.category.APP_BROWSER, but must be android.intent.category.INFO. Your app must only appear in Oculus Home. It must not appear in the phone’s launcher.

APK main activity intent filter set to android.intent.category.DEFAULT, but must be android.intent.category.INFO. Your app must only appear in Oculus Home. It must not appear in the phone’s launcher.

</details>

**Comment by bluemarvin** [comment]
So following these guidelines totally breaks the application in AndroidStudio. You basically can't run it from AndroidStudio and it will no longer show up in the "Unknown Sources" list on the Go. I'll try submitting it to se what happens, but we will need to figure out how to fix it for debug builds.

**Comment by bluemarvin** [comment]
Most are set in:
 https://github.com/MozillaReality/FirefoxReality/blob/oculus-store/app/src/oculusvr/AndroidManifest.xml

And android:theme="@android:style/Theme.Black.NoTitleBar.Fullscreen" is set in:
https://github.com/MozillaReality/FirefoxReality/blob/oculus-store/app/src/main/res/values/styles.xml#L109

They weren't set and their pre-check caught them.

**Comment by bluemarvin** [comment]
This is blocked waiting for feedback from Oculus.

**Comment by bluemarvin** [comment]
All that remains is to use a different AndroidManifest.xml for debug vs release builds. Probably less than a days worth of work.
