### ISSUE TITLE
Warning: attempting to write 50548 bytes to preference extensions.webextensions.uuids

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#3410]
I've seen this in console on Oculus Quest

`
GeckoConsole: Warning: attempting to write 50548 bytes to preference extensions.webextensions.uuids. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.`

**Comment by bluemarvin** [comment]
This is a known issue with the web extensions implementation in Gecko.

**Comment by MortimerGoro** [comment]
Already fixed in https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/common/shared/org/mozilla/vrbrowser/browser/engine/EngineProvider.kt#L67

**Comment by bluemarvin** [comment]
After further investigation, this is not a know issue!

**Comment by agi90** [comment]
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1639978

**Comment by MortimerGoro** [comment]
This has been already fixed in FxR, we are not using random keys anymore, so the pref doesn't grow after each restart
