### ISSUE TITLE
WebXR 'viewer' reference space not working correctly

### ISSUE THREAD

**Issue by BlurrySplodge** [MozillaReality/FirefoxReality#3412]
The 'viewer' XRReferenceSpace does not seem to be working correctly (i.e. as described in [Spatial Tracking explainer](https://github.com/immersive-web/webxr/blob/master/spatial-tracking-explainer.md#viewer-reference-space)). For example, the document states that 

> … calling getViewerPose() with a viewer reference space gives the appearance of having no tracking at all.

which is not the case in FR 10.1, as demonstrated by this fiddle:
- [without polyfill](https://jsfiddle.net/szk13pcL/3/)
- [with WebXR polyfill](https://jsfiddle.net/szk13pcL/4/)

The fiddle tries to get viewer pose relative to the viewer reference space, which should be zero. Therefore, you should **NOT** be able to look around in the scene; you should be seeing a static image.

It seems that when determining a pose in relation to the viewer reference space, the viewer's position is applied correctly (because the user is not able to walk through the scene in the fiddle even when using a 6DOF device), but its rotation is ignored (allowing the user to look around).

The viewer reference space behaves as expected on Oculus Browser 9.1.0 (Chromium 81), as well as Firefox Reality 9 using WebXR polyfill.

_Note: I created the not-very-practical fiddle just for the sake of simplicity to demonstrate the problem; I am actually using the viewer reference space to place the controllers relative to the user's head, which does not work either._

**Comment by MortimerGoro** [comment]
@BlurrySplodge  Thanks for the report and the fiddle code. It was really helpful to research the issue.

Fix here: https://phabricator.services.mozilla.com/D77283
