### ISSUE TITLE
makeXRCompatible not recognized

### ISSUE THREAD

**Issue by RaananW** [MozillaReality/FirefoxReality#3420]
## Configuration

Firefox Reality version:  10.1
Firefox Reality build ID: 54b1018b

Hardware: Oculus Quest

## Steps to Reproduce

1. Create a canvas
2. Make the context xr compatible using `makeXRCompatible()`
3. Wait for the promise to fulfill.
4. start a session
5. Create a new XR Layer using the session and ths created context

## Current Behavior
The XRLayer's creation fails, stating `XRWebGLLayer constructor: Can not create an XRWebGLLayer without first calling makeXRCompatible on the WebGLRenderingContext or WebGL2RenderingContext.`.

## Expected Behavior
XR Layer should be created without an exception thrown

## Possible Solution

The only current solution is to make the context xrCompatible using the glAttributes. However even as the exception states, makeXRCompatible should work. 

## Context

Babylon JS is initializing the XR Layer when entering the session, calling makeXRCompatible to avoid adding unneeded options to the context-creation process. 

A different issue will prevent you from entering XR using babylon.js that is unrelated to this (user gesture is not passed through chained promises), but when fixing it locally, this exception is thrown.  It is thrown at this line - https://github.com/BabylonJS/Babylon.js/blob/master/src/XR/webXRManagedOutputCanvas.ts#L99 . The promise fulfills without an issue. 

I also tried calling makeXRCompatible at an earlier time (at the moment I am calling it right before creating the XR Layer) which didn't help as well.

<details open>

```
```

</details>

**Comment by MortimerGoro** [comment]
@RaananW thanks for the bug report!

I posted a fix in the Gecko source code: https://bugzilla.mozilla.org/show_bug.cgi?id=1640912

We'll close this issue when we bump the GV version containing the fix
