### ISSUE TITLE
[Meta] WebXR Post Release Bugs

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#3423]
WebXR bugs reported after release in v10

- makeXRCompatible not recognized #3420 
- WebXR 'viewer' reference space not working correctly #3412 
- Failure to enter immersive mode in DelightVR player #3301
- local-floor reference space provides incorrect pose #3429
- WebXR freezes #3481 #3472
- Different results using local viewerpose between FxR and Oculus #3435
- Some pages opened in a new tab fail to render #3336

**Comment by MortimerGoro** [comment]
- Different results using local viewerpose between FxR and Oculus #3435

**Comment by bluemarvin** [comment]
Closing now that #3534 has landed.
