### ISSUE TITLE
local-floor reference space provides incorrect pose

### ISSUE THREAD

**Issue by RaananW** [MozillaReality/FirefoxReality#3429]
## Configuration

Firefox Reality version: 10.1
Firefox Reality build ID: 54b1018

Hardware: Oculus Quest

## Steps to Reproduce
1. Init an XR session
2. set reference space to local-floor
3. check next frame's pose's position.y (user height)

A demo scene (simplified version of Babylon.js's XR init process) - https://playground.babylonjs.com/debug.html#NT2UCM#13 . line 67 outputs the height received from the pose, unmodified. Clicking on the canvas will enter XR, another click (in the emulator) or exiting the session using the controller's button will stop the xr session.
View will not be updated, so the headset will be dark.

## Current Behavior

Pose's y axis is close to 0

## Expected Behavior

Pose's y axis should be the user's current distance from the floor (just like in the emulator)

## Context

Babylon.js's scene render incorrectly on Firefox reality, but working correctly on firefox with the webxr emulator, desktop chrome with oculus rift, and the oculus quest's default browser.
There are a few issues with rendering quality as well, but this is the most prominent issue ATM

```
```

</details>

**Comment by MortimerGoro** [comment]
@RaananW thanks for the report and the code sample. It was really helpful to research the prioblem. 

Fix here: https://phabricator.services.mozilla.com/D77284

**Comment by bluemarvin** [comment]
@MortimerGoro This does not appear to be fixed in latest GV. When I enter VR now, all I see is a black screen and then exiting VR locks up the browser.
