### ISSUE TITLE
[Pico] Cannot send url when launch browser activity if FxR is not running

### ISSUE THREAD

**Issue by picoxr** [MozillaReality/FirefoxReality#3431]
## Configuration

Firefox Reality version: 10-rc7
Firefox Reality build ID: bda5ecf

Hardware: Pico Neo2 - Android 8.1.0 - PUI 3.11.3

## Steps to Reproduce

1. Kill Firefox Reality application to make sure it's not running on background
2. Use adb command: ``adb shell am start -a android.intent.action.VIEW -d "https://aframe.io/" org.mozilla.vrbrowser/org.mozilla.vrbrowser.VRBrowserActivity`` to launch Firefox Reality and send url meanwhile
3. Observe the behavior.

## Current Behavior

Firefox Reality launches with success but it couldn't direct to the url specified in adb command

## Expected Behavior

Firefox Reality launches and direct to the specified url meanwhile.

## Context

1. The use case is to open up a link in Firefox Reality from another app. 
2. Oculus version seems to behave the same way.
3. Url can be sent correctly if FxR is running on background.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
Regressed by #3364

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 11-141551002 (8f4de9a4) installed on the Oculus Go, Oculus Quest, HTC Vive Focus, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
When using a Pico or Oculus device the URL can be sent while FxR is not running.
When using a HTC device the device remains stuck on the vive loading screen and can not be force-killed using an adb command, the only way to exit this loading screen is by pressing the Vive button for more than 20 sec. or by restarting the device.
The adb command to open the URL works as expected if FxR is opened.

@bluemarvin Should I open a different issue for the HTC devices?

**Comment by bluemarvin** [comment]
@Softvision-GeluHaiduc I'm not able to reproduce this issue. When I run the following on the Focus Plus:
```
adb shell am force-stop org.mozilla.vrbrowser.internal
adb shell am start -a android.intent.action.VIEW -d "youtube.com" org.mozilla.vrbrowser.internal/org.mozilla.vrbrowser.VRBrowserActivity
```
FxR launches and then opens the specified URL.

**Comment by Softvision-GeluHaiduc** [comment]
I was using this command 
`adb shell am start -a android.intent.action.VIEW -d https://www.youtube.com/ -t application/browser -n org.mozilla.vrbrowser.internal/org.mozilla.vrbrowser.VRBrowserActivity`

Using the command from the above comment the issue is not reproducing.
