### ISSUE TITLE
[HTC] The app is not opened after updating/installing the latest master build

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3440]
**[Affected Versions]:**
- Firefox Reality version 11-141492311 (a9b58ee6)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**

**[Steps to reproduce]:**
1. Install/update FxR to the latest master build (a9b58ee6).
2. Open the Firefox Reality browser.
3. Observe the behaviour.

**[Expected results]:**
- The latest master build is open.

**[Actual results]:**
- After the loading screen is briefly shown the dashboard is redisplayed. (the FxR logo is not displayed)

**[Notes]:**
- The issue is not reproducible on the other devices. (Oculus Go, Pico G2 4K and Pico Neo2)
- The debug version can be installed and opened.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1lKw_cesCskSBI7BV9Y6yTkUkPJsYYEO3/view?usp=sharing).
- Attached the logcat file of the issue [here](https://github.com/MozillaReality/FirefoxReality/files/4700384/log_Fri05-29-2020_10-32-31.txt).

**Comment by bluemarvin** [comment]
I'm not sure what is wrong with that specific build but all staging builds created after that one work fine for me. Only that one build for HTC seems to have problems. Please try a newer staging build.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 11-141532306 (3c70b993) installed on the HTC Vive Focus headset and now the staging builds are opened after an install/update. 
Giving this I will close this issue.
