### ISSUE TITLE
[Pico] Bluetooth settings not persisting after device restart.

### ISSUE THREAD

**Issue by plwt** [MozillaReality/FirefoxReality#3446]
## Configuration

(This is not a bug with FxR, but with Pico Android 8.1)

## Hardware: 

Pico Neo 2

## Steps to Reproduce

1. Turn on device
2. Turn off Bluetooth
3. Use device
4. Turn off device
5. Turn on device

## Current Behavior

Bluetooth is now active, using battery power.

## Expected Behavior

Bluetooth stays inactive, saving battery power.

## Context

Normally with Android, the Bluetooth status persists after a device shutdown.  The Pico variant turns Bluetooth back on, even though the user has turned it off previously.  This risks the battery reducing faster than expected, reducing browsing time, and impacting the overall user experience with FxR.

```
```

</details>

**Comment by bluemarvin** [comment]
I'm not sure this is a bug. The controller uses bluetooth. I think they are re-enabling it for controller discover on startup.

**Comment by SeburoSUMO** [comment]
That is a fair point.  I checked this morning using one of the motion controllers and my laptop, and they do appear to be using Bluetooth to do the initial link to the headset at startup.

But once the headset has linked to the motion controllers, does the Bluetooth need to stay on?  Given that Bluetooth can be manually turned off and the motion controllers still work, it suggests that Bluetooth could be turned off automatically once the link to the controllers is established.

**Comment by bluemarvin** [comment]
When I disable bluetooth on my G2 the controller stops working. I'm pretty sure the controller uses bluetooth for not just initialization but also communication.

**Comment by SeburoSUMO** [comment]
That is interesting. On the Neo2, when Bluetooth is disabled, the motion controllers continue to work.

**Comment by bluemarvin** [comment]
The Neo 2 controllers do indeed continue to work after disabling bluetooth. We can inform Pico but bluetooth is so low powered I doubt it is accounting for much battery drain.
