### ISSUE TITLE
The Play/Pause button from an inactive window disappear after navigating back to it from another website

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3449]
**[Affected Versions]:**
- Firefox Reality version 11-141532306 (3c70b993)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Make sure to have 2 windows created.

**[Steps to reproduce]:**
1. Navigate to the following website: https://mdn.github.io/learning-area/html/multimedia-and-embedding/video-and-audio-content/multiple-audio-formats.html
2. In the same window navigate to a different website. (e.g. facebook.com)
3. Click the “Back” navigation button.
4. Click on the other window and observe the inactive window play/pause button.

**[Expected results]:**
- The play/pause button is displayed.

**[Actual results]:**
- The play/pause button is not redisplayed.

**[Notes]:**
- The issue is reproducible only with audio files. (e.g. https://file-examples.com/index.php/sample-audio-files/)
- The issue is not reproducible with videos. (e.g. YouTube, Vimeo) 
- The buttons reappear after the page is refreshed.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1Tefdxf8K7g8i_TH2SkZRYNKrnidZ_IGI/view?usp=sharing)

**Comment by keianhzo** [comment]
For some reason when navigating back from Facebook to the audio page we don't get the `mediaAdd` callback or any playback callbacks, which should be the case, it just resumes the audio playback. It works as expected in similar pages like: https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_audio_all

Also works as expected in Fenix with the same GV version.
