### ISSUE TITLE
Performance issues on "BassoonTracker"

### ISSUE THREAD

**Issue by denschub** [MozillaReality/FirefoxReality#3462]
## Configuration

Firefox Reality version: 10.1
Firefox Reality build ID: 2020-05-20 (54b1018b)

Hardware: Oculus Quest

## Steps to Reproduce

1. Navigate to https://www.stef.be/bassoontracker/?file=https%3A%2F%2Fapi.modarchive.org%2Fdownloads.php%3Fmoduleid%3D144399%23crappy_meal.xm
2. Click the play button
3. Wait a couple of seconds

## Current Behavior

Audio starts stuttering.

## Expected Behavior

Audio plays without issues.

## Context

We have received this report [as a WebCompat issue](https://github.com/webcompat/web-bugs/issues/50220), and the tracker works fine in the Oculus default browser. It also works fine in Fenix.

This probably is a performance issue inside android-components, but because it is playing fine in Fenix on an emulator with little resources, I'm not 100% confident. I can't easily profile/debug FxR, and it's probably a lot easier if you have a look at that. :)

**Comment by bluemarvin** [comment]
From the screen shot in the web compat issue this was filed from a Go which uses the 821 chipset. This is actually a gecko issue on low end hardware coupled with the fact that Oculus heavily throttles us. From my quick testing I can see from top the tab process on a Pixel 1 is at 140% CPU utilization (meaning it is using more than one core). On a Pixel 2 it is closer to 90% CPU utilization. I have run it in Fenix nightly on a Pixel 2 and as it runs longer performance does degrade and CPU usage increases (up to 130%). This is a Gecko issue and not an FxR issue.

**Comment by denschub** [comment]
JFTR, I did my testing on a Oculus Quest, with same results. I'll do some profiling on a non-VR build though, thanks.

**Comment by bluemarvin** [comment]
As I said, we have the additional issue on oculus where they throttle us.

**Comment by bluemarvin** [comment]
Latest release of FxR is here: https://github.com/MozillaReality/FirefoxReality/releases/tag/release%2F10.2

The NoAPI version maybe installed on a standard Android Phone and the x86_64 may be run in the android emulator. The page works there just as well as it does in Fenix Nightly. There is nothing we can do about the throttling on Oculus, we've tried.

**Comment by bluemarvin** [comment]
Since you have a Quest, you can go into the FxR developer panel under settings and enable remote debugging. You can then do remote debugging and profiling just like any other android base gecko application.

**Comment by bluemarvin** [comment]
When I tested it on the Quest it didn't seem any worse than Fenix on a Pixel 2 which has the same chip set. I also test on a Pico G2 4k which also uses the same chip set and seemed to work just as well as Fenix. There is some audio popping but I hear that in Fenix nightly too.
