### ISSUE TITLE
Download on beatsaver.com fails

### ISSUE THREAD

**Issue by denschub** [MozillaReality/FirefoxReality#3465]
## Configuration

Firefox Reality version: 10.1
Firefox Reality build ID: 2020-05-20 (54b1018)

Hardware: Oculus Quest

## Steps to Reproduce

1. Navigate to https://beatsaver.com/search?q=reality%20check%20through%20the%20skull
2. Download any song

## Current Behavior

It looks like nothing happens. The download isn't visible in the download panel, but there is also no error message.

## Expected Behavior

Downloaded file appears in the download panel. 

## Error Logs and Stack Traces

There is nothing relevant in the JS console, but I could observer a "Widget n not found" error in the logcat, where n increases every time I start a new download. There doesn't seem to be any other information in the logcat, though.

**Comment by bluemarvin** [comment]
This is caused from using the android downloads manager instead of the Gecko WebExecutor. This should be fixed by https://github.com/MozillaReality/FirefoxReality/issues/3396

**Comment by bluemarvin** [comment]
To add context, the download URLs are of the format `blob:https://url` which is not handled by the android download manager.
