### ISSUE TITLE
The frames are not rendered quick enough when moving the headset around

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3470]
**[Affected Versions]:**
- Firefox Reality version 10.2 RC (699262e)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Play the "Hello WebXR" card from Interactive Experience.
2. Move the headset from left to right quickly.
3. Observe the behavior.

**[Expected results]:**
- The frames are rendered correctly.

**[Actual results]:**
- The frames are not rendered fast enough and some black margins can be seen.

**[Notes]:**
- Depending on the headset used the issue is more or less visible.
- The issue is more visible on the HTC Vive Focus Plus and the Pico G2 4K.
- The issue is less visible on the Pico Neo2 and Oculus Quest.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1Lu46wQprQiqAgR2P5oFIgn7rEZFch4Ka/view?usp=sharing).

**Comment by bluemarvin** [comment]
I'm not sure I understand this bug report. I don't see any difference in performance between v10.1 and v10.2. On devices that do not support frame ahead rendering (non-oculus devices) I see about 45Hz while on the Quest I see 72Hz for Hello WebXR immersive mode. The black area is what you will see if you exceed what timewarp can handle which will be more pronounced the lower the frame rate goes bellow the screen refresh rate.

**Comment by Softvision-GeluHaiduc** [comment]
I've retested this behavior using this [website](https://webvr.info/samples/03-vr-presentation.html) and it seems that on HTC Vive Focus Plus and Pico Neo2 the fps were the same both in normal browsing and in immersive mode.
However, only on the Pico G2 device, the fps dropped to around 45 while in immersive mode, as you mentioned in the above comment.
This behaviour seems a bit odd and I’m not sure if this is expected or not.

**Comment by bluemarvin** [comment]
The Neo2 has a more powerful CPU/GPU than the G2 while supporting the same screen resolution so the Neo2 should be able to maintain a higher framerate than the G2.

**Comment by Softvision-GeluHaiduc** [comment]
I will close this as a limitaiton of the hardware.
