### ISSUE TITLE
[Delight XR] The crash prompt is displayed after exiting immersive mode and clicking inside the video

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3471]
**[Affected Versions]:**
- Firefox Reality version RC 10.2 (699262e).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to https://delight-vr.com/video-player-module/
2. Play a video near bottom of page ex: "Get barreled in Tahiti".
3. Exit immersive mode and click inside the video content.
4. Observe the behavior.

**[Expected results]:**
- The video starts/stops playing.

**[Actual results]:**
- The crash prompt is displayed.

**[Notes]:**
- After exiting immersive mode only a black screen is displayed.
- Attached are screen recordings of the issue with different behaviors:
	- Screen Recording: [link](https://drive.google.com/file/d/1DuRpjRSfBd3DsjAjhMz_rXe1Q0VTvZEV/view?usp=sharing).
	- Crash Report: [link](https://crash-stats.mozilla.org/report/index/a9ab6d6f-37f5-49cb-a875-9e6990200605).
	- Logcat: [link](https://drive.google.com/file/d/1ZpBU9kRo3KmDxhYlXa8Ckj5b6KbgPMQs/view?usp=sharing).

**Comment by bluemarvin** [comment]
Fixed by #3553

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with Firefox Reality version 11 RC2 (5fd1bfd). Now, the video is reopened in immersive mode.

Tested on  Oculus Quest (Android 7.1.1), HTC Vive Focus (Android 7.1.2) and Pico Neo2 (Android - 8.1.0).
