### ISSUE TITLE
[Pico] krpano webvr website doesn't enter immersive mode

### ISSUE THREAD

**Issue by picoxr** [MozillaReality/FirefoxReality#3478]
## Configuration

Firefox Reality version: 10-rc7
Firefox Reality build ID: bda5ecf

Hardware: 

## Steps to Reproduce

1. Open 75511studio.com.
2. Click the menu button in the bottom right corner, switch the browser to mobile mode.
3. Click the Goggle icon.
4. Click “back”, swith the browser to desktop mode.
5. Click the Goggle icon.

## Current Behavior

In mobile mode, after clicking the goggle icon, VR mode can not be entered. The view is only displayed in the browser window.
In desktop mode, after clicking the goggle icon, binocular screen is opened.

## Expected Behavior

WebVR mode can be launched by clicking the goggle icon in mobile mode.

## Context

We are seeing the same issue on Oculus FxR build and Oculus built-in browser. Pico built-in browser can launch WebVR mode successfully.
p.s. Any info needs from Pico, feel free to reach out.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
This page uses HTTP. WebVR and WebXR require content be served over HTTPS. If you visit krpano.com, you will notice the demos there work and are all served over HTTPS.

**Comment by bluemarvin** [comment]
Closing since this seems to be working as expected.
