### ISSUE TITLE
[Pico] Web Wechat contact list doesn't slide using controller

### ISSUE THREAD

**Issue by picoxr** [MozillaReality/FirefoxReality#3479]
## Configuration

Firefox Reality version: 10-p1
Firefox Reality build ID: ac25341f

Hardware: Pico Neo2 - Android 8.1.0

## Steps to Reproduce

1. Open weixin.qq.com.
2. Switch the browser to desktop mode.
3. In the upper right corner, log in to Web WeChat.

## Current Behavior

The user bar on the left won’t slide.

## Expected Behavior

The user bar on the left can be slid up and down to see the full content.

## Context

Hope to know if any specific kind of desktop web component is not supported.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by daoshengmu** [comment]
I gave a try, and it looks like WeChat gives constraints for users who want use WeChat web version from overseas. For example, you have to use your mobile app to scan a QR code at WeChat login page. Even though passing the QR code scan, your account also need to be registered before 2017. Unfortunately, my account is not old enough.
