### ISSUE TITLE
[XRDinosaurus] The browser is frozen after opening the page in immersive mode a few times in different windows

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3481]
**[Affected Versions]:**
- Firefox Reality version RC 10.2 (699262e).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to https://www.xrdinosaurs.com/
2. Click the "Visit our Dinosaurs in Virtual Reality" button.
3. Visit a few "dinos" and close this window.
4. Redo the steps above in a new window (redo this step more then once if necessary).
5. Observe the behavior.

**[Expected results]:**
- The page is rendered correctly each time.

**[Actual results]:**
- The browser is eventually frozen.

**[Notes]:**
- This issue is also reproducible if the page is opened in immersive mode in multiple windows opened at a time.
- In some attempts, only some of the fumctioanlaties of the browser are effected, before hitting the freeze state.
- I could not save the videos where the app is frozen on Oculus Quest, the device is not responding after reproducing the issue.
- Attached are screen recordings of the issue:
	- Screen Recording (Quest): [link](https://drive.google.com/file/d/1Yl4psyG4mUhVUN83S_uM-_-ovuT802f2/view?usp=sharing).
	- Screen Recording (Neo2- hard navigation): [link](https://drive.google.com/file/d/1AGaaJTI2cFsL1ZTZyBC91ABVn9lfUQyj/view?usp=sharing).
	- Screen Recording (Neo2- freeze - new install): [link](https://drive.google.com/file/d/1Wyk7iBsxQ-WXrnipz-Fy6m17g3_hvCAm/view?usp=sharing).

**Comment by MortimerGoro** [comment]
This is probably related to #3472. I'll check if the workaround I'm testing on the other also fixes this one

**Comment by MortimerGoro** [comment]
This is caused by Out of Memory. Loading each dinosaur adds between 70-120 MB to memory which doesn't seem the be freed even after destroying the Gecko Session. It seems a WebGL issue, it will require some more research.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using Firefox Reality version RC 10.2 (23cd7b6). The windows did not freeze in the multiple attempts executed.

Tested on HTC Vive Focus (Android 7.1.2), Oculus Quest (Android 7.1.1), and Pico Neo 2 (Android - 8.1.0) devices.
