### ISSUE TITLE
WebXR controller haptics feedback

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#3486]
**Is your feature request related to a problem? Please describe.**
We would hope we can support haptics feedback in WebXR like what did in WebVR. Oculus Browser is also doing haptics feedback experiments currently.

**Describe the solution you'd like**
XRInputSource allows us accessing the gamepad object that is connected with its gamepad states from or VR delegate devices. The potential issues is our WebXR Gamepad doesn't go through GamepadManager.

**Describe alternatives you've considered**
This work would happen in Gecko. FxR should already have based on the previous work for WebVR.

**Additional context**
For detailed, please take a look at [Bug 1637015](https://bugzilla.mozilla.org/show_bug.cgi?id=1637015).

**Comment by MortimerGoro** [comment]
+1 for this one

**Comment by daoshengmu** [comment]
After running Gamepad haptic feedback [example](https://artyom17.github.io/webxr-samples/controller-state.html), I saw we already support it. I think I added this functionality when I integrated Gamepad into XRInputSource. That was happened in FF 77 and should be around FxR v.10.

**Comment by daoshengmu** [comment]
Confirmed it with v.11. It is supported already.
