### ISSUE TITLE
UR Finding: Users wanted browser customization options

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#349]
UR Finding: Users wanted browser customization options, including: browser colors, typefaces, text size, dimensions, and window opacity.

**Comment by cvan** [comment]
there are Design Explorations being done for a Settings / Preferences screen. probably will be related to this issue.

**Comment by larsbergstrom** [comment]
Thanks! This is being designed and implemented as part of https://github.com/MozillaReality/FirefoxReality/issues/638
