### ISSUE TITLE
[Keyboard-zh-CN] The browser freezes and crashes when first clicking the "u","i" or "v" keys and then the ",", "。" "!", or "?" keys

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3490]
**[Affected Versions]:**
- Firefox Reality version 11-141621406 (c7dd36c).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- The keyboard language is set to zh-CN.

**[Steps to reproduce]:**
1. Focus the Awesomebar so that the keyboard is displayed.
2. Click the "u" key so that an empty bar is displayed at the top of the keyboard.
3. Click one of the keys displayed between the "space-bar" key and the ".com" key. 
4. Observe the behavior.

**[Expected results]:**
- The second clicked key is inserted.

**[Actual results]:**
- The browser is frozen and after a quit and resume the crash prompt is displayed.

**[Notes]:**
- I only reproduced this issue while using the keys mentioned in the title, and it seems that it is affected only when the bar displayed over the keyboard is empty.
- After resuming the app on Oculus Quest, there is a black screen displayed, and it takes more than a minute for the crash prompt to be displayed.
- I haven't caught the crash part on video, because it takes to long for the app to resume.
- It could be related to issue #3417, but I received a different crash report and I decided to log this issue.
- Attached are screen recordings, the crash report and a logcat:
	- Screen Recording Vive: [link](https://drive.google.com/file/d/1ttI5unD42hc8lk4Ooq6prF3OIAfT1dk2/view?usp=sharing).
	- Screen Recording Quest: [link](https://drive.google.com/file/d/14hKPLSE0DqGyuYrZ5IOEsq-ndWOOjjhc/view?usp=sharing).
	- Crash Report: [link](https://crash-stats.mozilla.org/report/index/202e9fab-386a-46ef-9565-426270200611).
	- Logcat: [link](https://drive.google.com/file/d/1MM7Iai0aIy4ObST79DdvZL4MucRm98ZI/view?usp=sharing).

**Comment by daoshengmu** [comment]
According to the screen recording, it is happened in zh-CN keyboard instead of zh-TW.

**Comment by Softvision-RemusDranca** [comment]
Thanks for pointing this out, I will update the issue accordingly.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using Firefox Reality 11-141670446 (6b20069). The browser no longer freezes when using the mentioned combination of keys.

Tested on HTC Vive Focus (Android 7.1.2), Oculus Quest (Android 7.1.1), and Pico Neo 2 (Android - 8.1.0) devices.
