### ISSUE TITLE
UR Finding: Users wanted personalized homepage

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#350]
UR Finding: Users wanted personalized homepage - which included seeing their own Favorites.

**Comment by larsbergstrom** [comment]
Also hearing from businesses for demos.

**Comment by cvan** [comment]
we could allow a custom pref to add the `Settings > Developer Options`: `Custom Homepage URL`

(after 1.1…) @keianhzo thoughts?

**Comment by keianhzo** [comment]
I think that would be the most standard way of doing it, people would expect that to be there I like it.
