### ISSUE TITLE
[Oculus Go] No touchpad axes data

### ISSUE THREAD

**Issue by evdem** [MozillaReality/FirefoxReality#3502]
## Configuration
Firefox Reality version: 10.1 for Oculus Go
Hardware: Oculus Go

## Steps to Reproduce
1. https://www.ibiblio.org/e-notes/webxr/lis/fire0.htm    no touchpad controls
2. https://www.ibiblio.org/e-notes/webxr/lis/fire.htm    controls work if console.log() is added

    let source = xrSession.inputSources[0];
    let gp = source.gamepad;
    if(gp){
      let a0 = gp.axes[0];
      angle = a0*(.2 + Math.abs(a0))*deltaAngle;
      let a1 = gp.axes[1];
      transl = a1*(.2 + Math.abs(a1))*deltaTransl;
//console.log(a0+" "+a1);
    }

This script works in the Oculus browser.

## Error Logs and Stack Traces
What shall I send you from remote debugger?

<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
@daoshengmu can you take a look at this?

**Comment by evdem** [comment]
Sorry, all work in a while after reload.
