### ISSUE TITLE
[Keyboard: zh-TW] The bar displayed at the top of the keyboard is auto dismissed when inserting special characters in search fields

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3506]
**[Affected Versions]:**
- Firefox Reality version 11-141670446 (6b20069).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- The keyboard language is set to zh-TW.

**[Steps to reproduce]:**
1. Navigate to a website that has a search bar (Ex Youtube).
2. Focus the search bar so that the keyboard is displayed.
3. Set the keyboard to display special characters.
4. Click the keys and observe the bar displayed at the top of the keyboard.

**[Expected results]:**
- The bar is displayed and remains displayed.
OR
- The bar is not displayed at all.

**[Actual results]:**
- The bar is briefly displayed an then auto dismissed.

**[Notes]:**
- The issue is not reproducible with the Awesomebar.
- When clicking some of the keys, the bar is dismissed very quickly and it's not caught on video.
- Attached is a screen recording of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/11EdkKzWZsTFeCa5ENX4g6t__4Ry5IPNK/view?usp=sharing).

**Comment by daoshengmu** [comment]
I am going to refine our candidate displays when selecting symbols from JPN, Zh-CN, and Zh-TW keyboards. They have inconsistent behaviors when showing symbols. I think the `CandidatesResult` should be `AUTO_COMPOSE` instead of `SHOW_CANDIDATES `.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using Firefox Reality 11-141740850 (77deb30). The bar is no longer displayed above the keyboard when clicking the keys from the special character keyboard.

Tested on HTC Vive Focus (Android 7.1.2), Oculus Quest (Android 7.1.1), and Pico Neo 2 (Android - 8.1.0) devices.
