### ISSUE TITLE
[WaveVR] Crash on Android 10 headset/device

### ISSUE THREAD

**Issue by ted730820** [MozillaReality/FirefoxReality#3510]
## Configuration

Firefox Reality version: 10
Firefox Reality build ID: bda5ecfa

Hardware: Wave VR headset (Android 10)

## Steps to Reproduce

Open Firefox Reality application on Wave VR headset w/ Android 10 platform

## Current Behavior

Application crash. However, it can be launched successfully after setting SELinux to permissive mode.

## Expected Behavior

Application can work normally (without setting SELinux to permissive mode)

## Possible Solution

- Hidden field access might be related to https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces
-  Crash symptom might be caused by SELinux policy change on Android 10

## Error Logs and Stack Traces

<details open>

**Hidden field access related log messages**

> ...
> 06-04 08:03:17.009 12634 12674 W zilla.vrbrowse: Accessing hidden field Ljava/lang/Boolean;->value:Z (greylist-max-p, JNI, denied)
> 06-04 08:03:17.009 12634 12674 W zilla.vrbrowse: Accessing hidden field Ljava/lang/Integer;->value:I (greylist-max-p, JNI, denied)
> 06-04 08:03:17.009 12634 12674 W zilla.vrbrowse: Accessing hidden field Ljava/lang/Double;->value:D (greylist-max-p, JNI, denied)
> …
> 06-04 08:03:17.030 12634 12634 W zilla.vrbrowse: Accessing hidden field Landroid/inputmethodservice/Keyboard;->mShiftKeyIndices:[I (greylist-max-o, reflection, denied)
> 06-04 08:03:17.030 12634 12634 W zilla.vrbrowse: Accessing hidden field Landroid/inputmethodservice/Keyboard;->mShiftKeyIndices:[I (greylist-max-o, reflection, denied)

**SELinux Permission related logs**

> 06-01 03:29:42.177 14475 14738 E VRCORE  : ashmem_create_region error: (13) Permission denied
> 06-01 03:29:42.195 14475 14742 E VRCORE  : ashmem_create_region error: (13) Permission denied
> 06-01 03:29:42.195 14739 14739 E VRCORE  : execve error: (13) Permission denied
> 06-01 03:29:42.205 14744 14744 E VRCORE  : execve error: (13) Permission denied

```
```

</details>

**Comment by bluemarvin** [comment]
The team currently does not have access to any wavevr headsets running Android 10. I have two other devices running android 10 and neither one exhibit this problem. We are aware of the hidden field issue and plan to resolve it once we officially support android 10.
