### ISSUE TITLE
[HTC] The permission prompts are no longer displayed if the app is quited and resumed while they are displayed

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3511]
**[Affected Versions]:**
- Firefox Reality version 11-141672019 (418d959).

**[Affected Platforms]:** 
- HTC Vive Focus - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is open.
- No permissions are granted.

**[Steps to reproduce]:**
1. Click the Microphone button from the Awesomebar.
2. While the device permission prompt is displayed quit and resume the app.
3. Click again on the Microphone button.
4. Observe if the voice permissions prompt is redisplayed.

**[Expected results]:**
- The prompt is redisplayed.

**[Actual results]:**
- Only the voice search prompt is displayed.

**[Notes]:**
- This issue is also reproducible with the Location and Storage permission prompts.
- If the issue is reproduced with one of the prompts, it will also affect the other ones.
- The issue is dismissed after force stopping the app.
- Attached is a screen recording of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1CYNSsi1J2iEQJmLPckYkbPQyjq4JcNVv/view?usp=sharing).

**Comment by bluemarvin** [comment]
Looks like that is a bug in the HTC system. FxR is not responsible for showing the prompt or managing its state. Restarting FxR or rebooting the device seems to fix it. There isn't much FxR can do to fix this.

**Comment by emstanley** [comment]
Erica to mention to HTC for Phil's next meeting.
