### ISSUE TITLE
[Intermittent] The search suggestions are not opened at first click after exiting sleep mode

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3513]
**[Affected Versions]:**
- Firefox Reality version 11-141672019 (418d959).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to a website, for example https://www.xrdinosaurs.com/
2. Let the device to enter sleep mode by taking off.
3. Exit sleep mode by putting the headset back on.
4. Open a new window and type the first letters for the navigated website in step 1.
5. Click on the search suggestion provided for that website.
6. Observe the behavior.

**[Expected results]:**
- The website is opened on first click.

**[Actual results]:**
- The website is opened after multiple clicks.

**[Notes]:**
- I was not able to reproduce this issue on the other devices, but this could be affected by the reason that it's highly intermittent.
- Attached is a screen recording of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/10q6b5D2aTDUH_m90t3SCkxcLwMXWcB36/view?usp=sharing).

**Comment by bluemarvin** [comment]
I've spent some time looking into this. I have found you don't need to put the device to sleep. You just need to visit `xrdinosaurs.com` once so it is in history. After that, typing `webxr din` will bring up a search suggestion box that can not be clicked. I put logging in the `SuggestionsWidget` and even though hover seems to work, we do not get the call back for the Click Listener or the Long Click Listener. @keianhzo Any ideas what might cause the click listeners to not fire?
