### ISSUE TITLE
[mathis-biabiany.fr] UI glitches are displayed while this page is opened

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3518]
**[Affected Versions]:**
- Firefox Reality version 11-141672019 (418d959).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to this [page](http://mathis-biabiany.fr/) available on https://threejs.org/ website.
2. Click the animation from the page.
3. Observe the behavior.

**[Expected results]:**
- The UI is correctly displayed.

**[Actual results]:**
- UI glitches are displayed.

**[Notes]:**
- The glitches are more visible when interacting with the page.
- The video doesn't capture the exact display of the issue, the glitches are more visible in a real experience.
- The WebXR icon is displayed for this page, but I don't see a button so I can enter immersive mode (maybe it's just a page limitation), but I thought that it's worth mentioning.
- This issue is not reproducible on the Pico Neo2 device.
- Attached is a screen recording of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1l-TwUkesGKL-hktYAE53wfIqIGa78a-d/view?usp=sharing).

**Comment by bluemarvin** [comment]
This is caused by the webpage's usage of WebGL overloading the GPU. Same thing happens in the Oculus Browser.
