### ISSUE TITLE
The “What’s New” icon from the navigation bar disappears after changing the display language

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3528]
**[Affected Versions]:**
- Firefox Reality version 11-141740850 (77deb30a)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Make sure the What’s New button was not pressed before.

**[Steps to reproduce]:**
1. Open the "Language" card from Settings and click the “Edit” button from the “Display Language for App:” option.
2. Change the display language to something else. (e.g. French)
3. Dismiss the settings menu and observe the navigation bar. 

**[Expected results]:**
- The “What’s New” icon from the navigation bar remains displayed.

**[Actual results]:**
- The “What’s New” icon from the navigation bar disappears.

**[Notes]:**
- After entering and exiting Private Browsing the button reappears.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/17mEIYTHenLFZc1sdo8UQyjPvb_GNKpn2/view?usp=sharing).

**Comment by bluemarvin** [comment]
Restarting the app restores the what's new button if it hasn't been clicked.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 11-141770117 - 68128fbe installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the “What’s New” icon from the navigation bar remains displayed after changing the display language.
