### ISSUE TITLE
The previous session is not restored after changing the device language

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3530]
**[Affected Versions]:**
- Firefox Reality version 11-141740850 (77deb30).

**[Affected Platforms]:** 
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to a website.
2. Exit the app and change the device language.
3. Reopen the app and observe the behavior.

**[Expected results]:**
- The previous navigated website is displayed.

**[Actual results]:**
- The Homepage is displayed.

**[Notes]:**
- The Homepage is displayed after each quit and resume, until the device is restarted.
- I was not able to reproduce the issue on the Oculus devices, I presume that this is because the device needs to be restarter for the language settings to be applied.
- Attached is the screen recording of this issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1KDbgOKoQ8u_BloEWr07QgHBYwoN1FhTI/view?usp=sharing).

**Comment by bluemarvin** [comment]
I tested this on the Neo2 and was not able to reproduce the issue.

**Comment by bluemarvin** [comment]
I can now reproduce the issue. The window can not be restored for this issue to be reproduced. Clearing browser data before launch makes it 100% reproducible:

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 11 RC2 (5fd1bfd0) installed on the HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the previous session is restored after changing the device language.
