### ISSUE TITLE
UR Finding: Users wanted to use hand gestures to navigate browser

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#354]
UR Finding: Users wanted to use hand gestures to navigate browser.

**Comment by philip-lamb** [comment]
@avrignaud Did this refer to hand-tracking, or gestures with the controller?

**Comment by cvan** [comment]
I assume the latter. Using a 3DoF controller to gesture left or right to navigate backward or forward - or to scrub a video a few seconds backward or forward (for reference prior art: play a video in YouTube's iOS app, fullscreen a video, and double-tap on the left or right region to scrub backward or forward).
