### ISSUE TITLE
[Babylon XR] [Pico G2] A void environment is displayed when entering immersive mode a second time

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3541]
**[Affected Versions]:**
- Firefox Reality version 11-141760226 - 71aabd05 (AC 44.0.0)

**[Affected Platforms]:**
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to https://doc.babylonjs.com/how_to/webxr_demos_and_examples   
2. Play a WebXR example in immersive mode.
3. Exit immersive mode.
4. Open it again in immersive mode and observe the behavior.

**[Expected results]:**
- The example is correctly opened in immersive mode.

**[Actual results]:**
- A void environment is displayed.

**[Notes]:**
- After the page is refreshed immersive mode can be entered again.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1XNJ_TM1KEJwUamYTAV5OLWEeDAKOQay2/view?usp=sharing).

**Comment by bluemarvin** [comment]
@Softvision-GeluHaiduc I tested all three of the WebXR demos multiple times in FxR v11.2 on the Pico G2 4k and was not able to reproduce the issue.

**Comment by Softvision-GeluHaiduc** [comment]
I also tried reproducing the issue using the latest main installed on the Pico G2 4K with no success.
We can close this issue and open a new one if the behavior reappears.
