### ISSUE TITLE
[Jumpy Balls] The sound is broken when playing the game

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3554]
**[Affected Versions]:**
- Firefox Reality version RC 10.2 (23cd7b6).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Make sure that the device audio is on.

**[Steps to reproduce]:**
1. Open the https://mixedreality.mozilla.org/jumpy-balls/ page in immersive mode.
2. Click the start button to play the game.
3. Listen to the audio of the game.

**[Expected results]:**
- The audio is correctly played.

**[Actual results]:**
- The audio is broken.

**[Notes]:**
- The issue is reproducible even with low volume.
- The issue is also reproducible in the production version of the app (v10).
- This issue is not reproducible with the Oculus Browser.
- I was not able to reproduce this issue with other pages.
- At first it gave me the impression that the headset speakers are broken.
- Attached is a screen recording of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1du56MQh1EIlf8CGf-IHs1EfbzfvSWlko/view?usp=sharing).

**Comment by bluemarvin** [comment]
@fernandojsg i noticed this yesterday on the pico devices. For me it was the cannon fire effect that was coming out distorted. The music and bounce sounds seemed to be okay.

**Comment by fernandojsg** [comment]
I'll check it as I upgraded to the latest three.js so maybe it's related

**Comment by bluemarvin** [comment]
@fernandojsg Did you ever get a chance to look into this?

**Comment by fernandojsg** [comment]
@bluemarvin I didn't have time yet to look at it, I'll try to book some time and look into it
