### ISSUE TITLE
[Babylon XR] Navigation is blocked after exiting immersive mode

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3563]
**[Affected Versions]:**
- Firefox Reality version 10.2 RC3 (7523a32d)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to https://doc.babylonjs.com/how_to/webxr_demos_and_examples 
2. Play a WebXR example in immersive mode.
3. Exit immersive mode.
4. Click the navigate “Back” button. (or any other button from the navigation bar)
5. Observe the behavior.

**[Expected results]:**
- The page is navigated back.

**[Actual results]:**
- Nothing happens.

**[Notes]:**
- The issue is not reproducible in the latest version of FxR.
- The issue is reproducible with “Forward”, “Refresh”, “Home” buttons as well.
- If an URL is typed the page is not loaded.
- Sometimes the content on the page is also frozen after pressing a button.
- Immersive mode can be entered again.
- A new window can be created and the affected window can be closed.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/18LNWPCWseCcEToeUWDvnyC-z-JUDzvSH/view?usp=sharing).

**Comment by MortimerGoro** [comment]
This is related to to a missing commint in the RC branch, the "beforeunload" prompt

**Comment by MortimerGoro** [comment]
Already merged into RC branch

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 10.2 RC4 (6adc5cc8) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, navigation is not blocked after exiting immersive mode on babylonjs.com.
