### ISSUE TITLE
[A-Frame] The app freezes or is exited when reopening and playing the "A Saturday Night" example in immersive mode

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3567]
**[Notes]:**
- On the other devices the only issue is that the view is positioned higher and higher each time the example is opened.

**[Affected Versions]:**
- Firefox Reality version 10.2 RC3 (7523a32d)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Open the https://aframe.io/examples/showcase/a-saturday-night/ page in immersive mode.
2. Chose a character and exit immersive mode.
3. Reenter immersive mode and observe the behavior.

**[Expected results]:**
- The page is correctly opened.

**[Actual results]:**
- The app freezes or exited and sometimes is just blocked in immersive mode for a while.

**[Additional Notes]:**
- In some attempts I needed to reopen the example in immersive mode 3 times.
- This issue is also reproducible in the production version of the app (v10.1).
- I could not save the recording where the app was frozen/exited because the device was not responding to the adb commands.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1bLwPlAaM-jVLaZVFbps0jfpztEWK1TTg/view?usp=sharing).

**Comment by MortimerGoro** [comment]
Some of the glitches are caused due to compiling and linking shaders: https://share.firefox.dev/31jCdCt
