### ISSUE TITLE
Users would like to upload / change their own environments

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#3569]
Users enjoy switching environments in Firefox Reality. We've heard from @SeburoSUMO that it would be great to have more end user customization - being able to find skyboxes online and switch to them.

Today, they have to use either dev mode with wiki stuff:
https://github.com/MozillaReality/FirefoxReality/wiki/Environments

Or SideQuestVR, which has customized FxR environments to choose from.

**Comment by bluemarvin** [comment]
We are adding support for remotely hosted environments in PR https://github.com/MozillaReality/FirefoxReality/pull/3561
The next logical step is allow users to point to their own hosted environments.

**Comment by larsbergstrom** [comment]
Awesome! That looks amazing - I'm excited to see it coming and can't wait to try it.
