### ISSUE TITLE
UR Finding: Users wanted higher quality font rendering

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#357]
UR Finding: Users wanted higher quality font rendering to make it easier to read text on pages.

**Comment by cvan** [comment]
I assume the suggestion here is to use SDF for font rendering, if we aren't already. Is there a Gecko or GeckoView platform bug to track here, or are there actionable items that can be done in FxR to achieve this?

**Comment by larsbergstrom** [comment]
This is related to #630. Moving to backlog.
