### ISSUE TITLE
Privacy Notice

### ISSUE THREAD

**Issue by SeburoSUMO** [MozillaReality/FirefoxReality#3571]
## Configuration

Firefox Reality version: 10
Firefox Reality build ID: bda5ecfa

Hardware: Pico Neo 2

## Steps to Reproduce

1. Open Firefox Reality
2. Select the mic icon to do a voice search
3. Select the privacy notice on the splash screen

## Current Behavior

The user is taken to https://www.mozilla.org/en-US/privacy/firefox/

## Expected Behavior

The user is taken to https://www.mozilla.org/en-US/privacy/firefox-reality/

## Possible Solution

Correct the URL

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by SeburoSUMO** [comment]
The same change needs to be made in the Settings, Privacy & Security panel.

**Comment by SeburoSUMO** [comment]
The same change needs to be made on the FxR "top sites" screen.

**Comment by bluemarvin** [comment]
> The same change needs to be made on the FxR "top sites" screen.

The content feed is a different project. I'll file it with them since it is a private repo for some reason.

**Comment by bluemarvin** [comment]
Although the content feed can be viewed in any browser (see [https://webxr.today](https://webxr.today)) So I don't know that the FxR privacy statement is correct either.

**Comment by SeburoSUMO** [comment]
I did not know that and I stand corrected.  Using the broader Fx statement would be more appropriate in that instance.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 12 RC2 (195415f0) installed on Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the user is taken to the Firefox Reality privacy notice.
