### ISSUE TITLE
Resetting privacy options does not reset first run privacy message for voice search

### ISSUE THREAD

**Issue by SeburoSUMO** [MozillaReality/FirefoxReality#3572]
## Configuration

Firefox Reality version: 10
Firefox Reality build ID: bda5ecf

Hardware: Pico Neo 2

## Steps to Reproduce

1. Open Firefox Reality
2. Perform a voice search, the privacy splash screen appears
3. Select Settings
4. Select Privacy & Security
5. Reset privacy options

## Current Behavior

Even though the user has reset the privacy options, a new voice search does not trigger the splash screen. 

## Expected Behavior

The privacy splash screen for voice search appears.

## Context

The users has made the decision to reset their privacy settings, so they should be presented with the "first run" privacy notice.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 12 RC2 (195415f0) installed on Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, resetting the privacy options does reset the first run privacy message for voice searches.

**Comment by Softvision-GeluHaiduc** [comment]
Sorry I might have unassigned Randall when adding the label.
I will add him back as the assignee. Sorry for the spam.
