### ISSUE TITLE
Change/remove the "report an issue" tile in Settings

### ISSUE THREAD

**Issue by SeburoSUMO** [MozillaReality/FirefoxReality#3573]
At present, the "report an issue" tile takes the user to WebCompat.  Reporting an issue sounds more like a support request, but also (while I do appreciate their work) the WebCompat process is not a quick and easy thing for a user to do.  They will need to install another MR browser and switch between them to file the report - not a great user journey.

I recommend removing this tile.  There is already a "help" tile that takes the user to the SUMO KB and forums where should a WebCompat issue be identified it can be filed by a SUMO contributor.

The only concern I have is the balance of icons on Settings screen would be a bit unbalanced.  There might be another setting that could be promoted to tile status to balance this out.

**Comment by daron-walters** [comment]
_Here is the look with the tile removed.  Let me know if this is acceptable before I do a pull request_

![org mozilla vrbrowser dev-20200714-125729](https://user-images.githubusercontent.com/1936826/87454406-ea6bee00-c5d1-11ea-97cf-b10c677e2431.jpg)

**Comment by SeburoSUMO** [comment]
I am not the sign-off on this, but it looks really good.  One question:- where does the "What's New" tile go to?

**Comment by daron-walters** [comment]
Did you mean "Whats New" or "Report An Issue"? the "Whats New" is the bottom right

**Comment by SeburoSUMO** [comment]
Apologies, I should have been clearer.  If a user selects the new "Whats New" tile, what do they see, where are they taken to?

**Comment by feiss** [comment]
looks good to me!

**Comment by bluemarvin** [comment]
Will be covered in the add-ons PR  #3756

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 12 RC2 (195415f0) installed on Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the “Report an Issue” card is removed from the Settings menu.
