### ISSUE TITLE
Change from using Clear Data for Clear Cache

### ISSUE THREAD

**Issue by plwt** [MozillaReality/FirefoxReality#3574]
In the Privacy & Security settings in FxR, there are two controls:

Cookies and Site data
Cached Web Content

The first of these has a button "Clear Data", but the second also uses a button labeled "Clear Data".

I believe it would be better to follow the Android norm of having a "Clear Data" and a "Clear Cache".  Although the context is slightly different (Clear Data in Privacy & Security does not take FxR back to first run state), it would better differiantiate the controls in the Privacy & Security settings panel.

**Comment by emstanley** [comment]
Verify that we're consistent with other firefox products.
