### ISSUE TITLE
Syncing open tabs

### ISSUE THREAD

**Issue by plwt** [MozillaReality/FirefoxReality#3575]
At present, I can use Firefox Sync to sync open tabs between laptop and Fenix.  This gives me a "browse anywhere" experience.

It would be good to have the implementation of Firefox Sync in FxR also handle sync open tabs to extend the "browse anywhere" experience to headsets.

**Comment by bluemarvin** [comment]
I think we are wait for the FxA library to support this. @keianhzo Do you know what the status of this feature in FxA is?

**Comment by keianhzo** [comment]
@bluemarvin This is already available in FxA, we can add in to FxR anytime.
