### ISSUE TITLE
Compositor Crash on Oculus Go

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#3586]
## Configuration

Firefox Reality version: 10.2
Firefox Reality build ID: 6adc5cc8

Hardware: Oculus Go

## Crash Report
https://crash-stats.mozilla.org/report/index/d8751ecf-9bb5-4b77-ad90-6ce100200630

## Notes
This is currently the top crash for v10.2

**Comment by MortimerGoro** [comment]
I have not been able to reproduce this

**Comment by bluemarvin** [comment]
Maybe we need to add some error checking [here](https://searchfox.org/mozilla-central/rev/31d8600b73dc85b4cdbabf45ac3f1a9c11700d8e/gfx/gl/GLContextProviderEGL.cpp#225-230)? Could also be OOM maybe?

**Comment by MortimerGoro** [comment]
I created this patch that I think it will help: https://phabricator.services.mozilla.com/D81990

**Comment by MortimerGoro** [comment]
I found realiable STR:
- Open History panel
- Load website from history (I use WebVR samples)

New patch: https://phabricator.services.mozilla.com/D82369

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 11 RC7 (45f818a9) installed on Oculus Go headset performing the steps outlined above by @MortimerGoro.
Now, the app doesn’t crash.
