### ISSUE TITLE
Steam VR support ever going to happen? "1 year late" already

### ISSUE THREAD

**Issue by Baldrickk** [MozillaReality/FirefoxReality#3588]
In https://blog.mozvr.com/firefox-reality-coming-to-steamvr/ (April 2019) it was stated that "We are excited to collaborate with Valve and release Firefox for SteamVR this summer."

What has happened to this? It does not appear to be present in the roadmap, and has not released.  There has been no news or blog posts regarding this, nor any tickets or issues.

**Comment by bluemarvin** [comment]
The Steam version is a separate project. This repository is for the android version of Firefox Reality.

**Comment by Baldrickk** [comment]
This does indeed appear to be the only visable "FirefoxReality" repo.   And yes, it was obvious that it only targets android, because the releases are only APK files.

Any information about where one could go to find out about Desktop Firefox Reality?

**Comment by Atemu** [comment]
For reference, here is the [repo for the PC version](https://github.com/MozillaReality/FirefoxRealityPC/issues/204) and the [corresponding issue](https://github.com/MozillaReality/FirefoxRealityPC/issues/204).
