### ISSUE TITLE
UR Finding: Users wanted ability to change accounts (or have Guest account) to enable multiuser use of device

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#359]
UR Finding: Users wanted ability to change accounts (or have Guest account) to enable multiuser use of device.

**Comment by avrignaud** [comment]
Another user suggested "Netflix like account selection" option.

**Comment by cvan** [comment]
Samsung Internet Browser has a non-default preference to require PIN entry for its Private Browsing. Could be interesting to allow Netflix-like profiles with a similar entry mechanism.

**Comment by avrignaud** [comment]
Yep, I think we are going to investigate something similar for profile selection/protection and private mode. Nadja also thought it was an interesting idea - be good to talk through when we start designing!

**Comment by cvan** [comment]
From https://github.com/MozillaReality/FirefoxReality/issues/380#issuecomment-419311818:

> Samsung Internet allows a PIN requirement for opening its Private Browsing mode, something I pitched a while back and excited to see in production. I have a few other ideas here. I would love to have a conversation here with interested folks.

**Comment by philip-lamb** [comment]
Into backlog until we have initial accounts implementation.
