### ISSUE TITLE
The language of the on screen controls tooltips wrongly remain in the same language after changing the display language

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3591]
**[Affected Versions]:**
- Firefox Reality version 11 RC2 (5fd1bfd0)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Open the "Language" card from Settings and click the “Edit” button from the “Display Language for App:” option.
2. Change the display language to something else. (e.g. French, German)
3. Dismiss the settings menu and navigate to a 360 video on YouTube and enter immersive mode.
4. Press the trigger button on the controller to have the on screen controls displayed.
5. Using the controller hover the pointer for more than ~1 second over each button.
6. Observe the language of the tooltips.

**[Expected results]:**
- The language of the tooltips changed to the selected display language.

**[Actual results]:**
- The language of the tooltips remained in the same language.

**[Notes]:**
- If the app is closed and reopened then the tooltips are displayed in the correct language.
- The issue affects only the tooltips for the on screen controls.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1v-4QtUyIKAox9bTbwKeYnZSVHTrNtUvQ/view?usp=sharing).

**Comment by bluemarvin** [comment]
@keianhzo Looks like a recent regression. I know I tested this not very long ago.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 11 RC4 (c28ddb2e) installed on the Oculus Go, Pico Neo2 and Pico G2 4K headsets.
Now, the language of the on screen controls tooltips are changed according to the display language selected.

The issue could not be verified on HTC devices because of #3638.

**Comment by Softvision-GeluHaiduc** [comment]
I also verified the issue on HTC Vive Focus Plus using Firefox Reality version 11 RC5 (4ca1220b).
