### ISSUE TITLE
[Keyboard: Thai] It switches back to normal after inserting the first special character

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3592]
**[Affected Versions]:**
- Firefox Reality version 11 RC2 (5fd1bfd).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- The keyboard language is set to Thai.

**[Steps to reproduce]:**
1. Click inside the Awesomebar so that the keyboard is displayed.
2. Switch the keyboard to display only special characters.
3. Click one of the keys and observe the behavior.

**[Expected results]:**
- The keyboard remains in the special characters format.

**[Actual results]:**
- The keyboard switches back to normal.

**[Notes]:**
- This issue is reproducible even when clicking keys from the numeric keyboard.
- Attached is a screen recording of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/180mz_nipFuXQnoeMVd1wCF8RQ1D13CqW/view?usp=sharing).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 11 RC4 (c28ddb2e) installed on the Oculus Go, Pico Neo2 and Pico G2 4K headsets.
Now, the keyboard does not switch back to default after inserting the first symbol.

The issue could not be verified on HTC devices because of #3638.

**Comment by Softvision-GeluHaiduc** [comment]
I also verified the issue on HTC Vive Focus Plus using Firefox Reality version 11 RC5 (4ca1220b).
