### ISSUE TITLE
[Keyboard: Thai] The "Go" string switches to "Enter" when clicking the Shift key (uppercase)

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3593]
**[Affected Versions]:**
- Firefox Reality version 11 RC2 (5fd1bfd).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- The keyboard language is set to Thai.

**[Steps to reproduce]:**
1. Click inside the Awesomebar so that the keyboard is displayed.
2. Click the Shift key and observe the Enter key.

**[Expected results]:**
- The string displayed for the key is "Go".

**[Actual results]:**
- The string switches to "Enter".

**[Notes]:**
- The key switches back to "Go" when clicking again on the Shift key.
- Attached is a screen recording of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1dgs3xwOIC8D2vQ8zAZ3w6SO1YUVLL1Ft/view?usp=sharing).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 11 RC4 (c28ddb2e) installed on the Oculus Go, Pico Neo2 and Pico G2 4K headsets.
Now, the "Go" string does not switch to "Enter" when clicking the Shift key.

The issue could not be verified on HTC devices because of #3638.

**Comment by Softvision-GeluHaiduc** [comment]
I also verified the issue on HTC Vive Focus Plus using Firefox Reality version 11 RC5 (4ca1220b).
