### ISSUE TITLE
[Keyboard: Thai] The keyboard is not changed to special character format if caps lock mode is on

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3594]
**[Affected Versions]:**
- Firefox Reality version 11 RC2 (5fd1bfd).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- The keyboard language is set to Thai.

**[Steps to reproduce]:**
1. Click inside the Awesomebar so that the keyboard is displayed.
2. Click the Shift so that the keyboard changes to uppercase.
3. Click the key to display the special characters.
4. Observe the behavior.

**[Expected results]:**
- The keyboard switches to special characters display.

**[Actual results]:**
- The caps look mode is dismissed.

**[Notes]:**
- This issue is also reproducible if the caps look is locked in this mode. The key to display the special characters has to be clicked 3 times for the special characters to be displayed.
- Attached is a screen recording of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1aUgTAGqZmspFcV5ri3hFCz7dLbkiYhCO/view?usp=sharing).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 11 RC4 (c28ddb2e) installed on the Oculus Go, Pico Neo2 and Pico G2 4K headsets.
Now, the symbol keyboard can be accessed through the caps lock mode keyboard.

The issue could not be verified on HTC devices because of #3638.

**Comment by Softvision-GeluHaiduc** [comment]
I also verified the issue on HTC Vive Focus Plus using Firefox Reality version 11 RC5 (4ca1220b).
