### ISSUE TITLE
[Keyboard: Thai] The special menu for the .com key is displayed under the keyboard's boundary while in special characters display

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3595]
**[Affected Versions]:**
- Firefox Reality version 11 RC2 (5fd1bfd).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- The keyboard language is set to Thai.

**[Steps to reproduce]:**
1. Click inside the Awesomebar so that the keyboard is displayed.
2. Click the key to display the special characters.
3. Long click the ".com" key.
4. Observe the position of the special menu displayed.

**[Expected results]:**
- The menu is displayed inside the keyboard's boundary.

**[Actual results]:**
- The menu exceeds the lower boundary of the keyboard.

**[Notes]:**
- A shadow effect is also displayed for the bottom part of the keyboard when reproducing this issue.
- This issue is not reproducible when the keyboard is in normal display.
- Attached is a screen recording of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1D9bc8hMVldCuhrUJeDA7FlFCZPCjthEh/view?usp=sharing).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 11 RC4 (c28ddb2e) installed on the Oculus Go, Pico Neo2 and Pico G2 4K headsets.
Now, the special menu for the .com key is displayed correctly.

The issue could not be verified on HTC devices because of #3638.

**Comment by Softvision-GeluHaiduc** [comment]
I also verified the issue on HTC Vive Focus Plus using Firefox Reality version 11 RC5 (4ca1220b).
