### ISSUE TITLE
[Keyboard: Thai] The Space key has no click state effect

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3596]
**[Affected Versions]:**
- Firefox Reality version 11 RC2 (5fd1bfd).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- The keyboard language is set to Thai.

**[Steps to reproduce]:**
1. Click inside the Awesomebar so that the keyboard is displayed.
2. Click the Space key. 
3. Observe if the key has a click state.

**[Expected results]:**
- The key has a dark click state.

**[Actual results]:**
- The key has the same state as before it was clicked/hovered.

**[Notes]:**
- This issue is not reproducible with the other keys available.
- Attached is a screen recording of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1zZR05r9uKs_jFb51rh2WP3aLRy8-xHb4/view?usp=sharing).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 11 RC4 (c28ddb2e) installed on the Oculus Go, Pico Neo2 and Pico G2 4K headsets.
Now, the space key has a click effect.

The issue could not be verified on HTC devices because of #3638.

**Comment by Softvision-GeluHaiduc** [comment]
I also verified the issue on HTC Vive Focus Plus using Firefox Reality version 11 RC5 (4ca1220b).
