### ISSUE TITLE
[Keyboard: Thai] Spaces are not continuously inserted when the Space key is clicked and hold

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3597]
**[Affected Versions]:**
- Firefox Reality version 11 RC2 (5fd1bfd).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- The keyboard language is set to Thai.

**[Steps to reproduce]:**
1. Click inside the Awesomebar so that the keyboard is displayed.
2. Click and hold the Space key. 
3. Observe the Awesomebar.

**[Expected results]:**
- Spaces are continuously inserted.

**[Actual results]:**
- Only one space is inserted.

**[Notes]:**
- This issue is not reproducible with the "Delete" key.
- Attached is a screen recording of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1DM6KFyust5VfDP2UzcQKMLilZwgL-b6g/view?usp=sharing).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 11 RC4 (c28ddb2e) installed on the Oculus Go, Pico Neo2 and Pico G2 4K headsets.
Now, the spaces are continuously inserted when the space key is clicked and held.

The issue could not be verified on HTC devices because of #3638.

**Comment by Softvision-GeluHaiduc** [comment]
I also verified the issue on HTC Vive Focus Plus using Firefox Reality version 11 RC5 (4ca1220b).
