### ISSUE TITLE
[Keyboard: Thai] The backslash is also available in the forwardslash special menu even if it has a dedicated key

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3598]
**[Affected Versions]:**
- Firefox Reality version 11 RC2 (5fd1bfd).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- The keyboard language is set to Thai.

**[Steps to reproduce]:**
1. Click inside the Awesomebar so that the keyboard is displayed.
2. Click and hold the Forwardslash key. 
3. Observe if the backslash is displayed in the special menu..

**[Expected results]:**
- The backslash is not displayed.

**[Actual results]:**
- The backslash is displayed even if a dedicated key is available above the .com key.

**[Notes]:**
- Attached is a screen recording of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1vv-542idnDXgzK4iv-Gpsc6bduxSSTM2/view?usp=sharing).

**Comment by daoshengmu** [comment]
That is designed according to the document. I have no strong option to remove it.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 11 RC4 (c28ddb2e) installed on the Oculus Go, Pico Neo2 and Pico G2 4K headsets.
Now, the backslash is available only through ist own dedicated key.

The issue could not be verified on HTC devices because of #3638.

**Comment by Softvision-GeluHaiduc** [comment]
I also verified the issue on HTC Vive Focus Plus using Firefox Reality version 11 RC5 (4ca1220b).
