### ISSUE TITLE
UR Finding: Users wanted ability to have multiple "tabs" or browser windows arrayed in space around them

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#360]
UR Finding: Users wanted ability to have multiple "tabs" or browser windows arrayed in space around them. This is different than carousel (which allows user to rotate through open windows).

**Comment by avrignaud** [comment]
From collated notes:
User wants to have multiple windows open simultaneously to compare and contrast content and to have YouTube (or MLB “Sports”) playing in the background.
→ Design a way to have ‘x’ more windows open and simultaneously visible (outside of carousel) in addition to main browser window. Ask devs how many of them can be active simultaneously. Maybe design a way to differentiate between active and inactive open windows. 
→ A way to place and arrange additional browser windows.
→ A way to group and save additional browser window clusters.

**Comment by fortinmike** [comment]
I was looking for this feature; it would be great. What's more, the current "scale windows freely" UI would be a great fit for manipulating and scaling windows.

**Comment by avrignaud** [comment]
Early design underway, but need input from team. Will set meeting. Also, note that this is a P2 - unlikely to make 1.1.

**Comment by thenadj** [comment]
@avrignaud Looks like we won't have multiple windows for v1.1. Can you move this card out of the
'Needs Design' column?

**Comment by avrignaud** [comment]
@nancyhang How do we move this card from the project to the backlog? I removed the 1.1 label and added Backlog tag... want to make sure it's in the right place to be considered for 1.2 and beyond.

**Comment by avrignaud** [comment]
@thenadj Just highlighting that the "tab tiles" concept is worth considering when we work on this as well. Seems to address many of the UR findings earlier in this bug.

**Comment by caseyyee** [comment]
Should track with https://github.com/MozillaReality/FirefoxReality/issues/480

**Comment by caseyyee** [comment]
Closing in favor of https://github.com/MozillaReality/FirefoxReality/issues/635
Identify the issues, track solutions together.
