### ISSUE TITLE
[FxA] The Log In pages are negatively affected if entering PB mode right before the login process is complete

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3605]
**[Affected Versions]:**
- Firefox Reality version 11 RC2 (5fd1bfd).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Have a valid FxA account.

**[Steps to reproduce]:**
1. Start the login process in the FxA account.
2. When the process is almost complete enter in PB mode and observe the login page.
3. Return to normal browsing and observe the login page.

**[Expected results]:**
- Step 2: The "Firefox Account connected' page is displayed.
- Step 3: The "Firefox Account connected' page is displayed.

**[Actual results]:**
- Step 2: The "Sign In" page is displayed with the message "Email Verified".
- Step 3: The "Log In" page stays in a working state.

**[Notes]:**
- If the account is disconnected and the "Log In" page that is in the "working" state is refreshed and then logging back in from the same page the crash mentioned in issue #3604 will be encountered.
- Attached is a screen recording of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1N3qMYOnYixJUYf8zC27Rb6l5rA12-CaG/view?usp=sharing).

**Comment by Softvision-RemusDranca** [comment]
@keianhzo regarding the note from the issue where performing some additional steps, the app crashes that is also related to the issue when I relogin using the Login page from history. It seems that it can also result in the same crash if I copy the URL of the login page before loging in  and than use it to relogin.
This are edge cases, but I wanted to point it out in case there is a fix for them since the #3612 PR only fixed the issue related to history, by hiding the login URLs.

**Comment by keianhzo** [comment]
@Softvision-RemusDranca Unfortunately there isn't much else that we can do, I've already brought up this issue with the AS team https://github.com/mozilla/application-services/issues/3320 Hopefully we can get a fix soon.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with Firefox Reality version 11 RC6 (e4f476e). Now, the Log in page is no longer affected by this behavior and it's not displayed in PB.

Tested on Oculus Quest (Android 7.1.1), HTC Vive Focus (Android 7.1.2), and Pico Neo2 (Android - 8.1.0).
