### ISSUE TITLE
The keyboard is not dismissed when clicking the "What's New" button

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3606]
**[Affected Versions]:**
- Firefox Reality version 11 RC2 (5fd1bfd).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Click inside the Awesomebar so that the keyboard is displayed.
2. Click the "What's New" button. 
3. Observe the keyboard.

**[Expected results]:**
- The keyboard is dismissed.

**[Actual results]:**
- The keyboard remains displayed and the Awesomebar focused.

**[Notes]:**
- Attached is a screen recording of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/15F0uIlm78sR3w1W_O3TDCBlRCkyxPOcu/view?usp=sharing).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 11 RC4 (c28ddb2e) installed on the Oculus Go, Pico Neo2 and Pico G2 4K headsets.
Now, the keyboard is dismissed when the "What's New" button is clicked.

The issue could not be verified on HTC devices because of #3638.

**Comment by Softvision-GeluHaiduc** [comment]
I also verified the issue on HTC Vive Focus Plus using Firefox Reality version 11 RC5 (4ca1220b).
