### ISSUE TITLE
UR Finding: Users would like ability to co-browse web content, including videos

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#361]
UR Finding: Users would like ability to co-browse web content, including videos.

**Comment by avrignaud** [comment]
Received additional feedback on this:

_A friend and I built a web browser plugin allowing people on a webpage at the same time to connect and travel the internet together. If we had the browser extension active on espn.com at the same time (for example), we could connect with one another, start a conversation and share a web surfing experience together. 

I thought that this would have a perfect use case for the VR world because webVR will be all about shared digital experiences._

**Comment by philip-lamb** [comment]
/remind me on April 1 bring to design team attention "co-browse in 3D".
