### ISSUE TITLE
[Pico G2 4K] WebXR content can wrongly be recentered in any position

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3615]
**[Affected Versions]:**
- Firefox Reality version 11 RC3 (f6453025)

**[Affected Platforms]:**
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Play the "Hello WebXR" card from Interactive Experience.
2. Enter immersive mode and move the headset in a different position vertically.
3. Press and hold the Pico button on the controller to recenter the view.
4. Observe the behavior.

**[Expected results]:**
- The view is not recentered vertically.

**[Actual results]:**
- The view is recentered vertically.

**[Notes]:**
- The issue is not reproducible on the other devices.
- The issue is reproducible while using the headset button as well.
- The issue is reproducible in the latest main as well.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1z4sCXb2Z1jD5gOBetINpfHq_DFqSynDE/view?usp=sharing).

**Comment by bluemarvin** [comment]
This is working as expected. The Pico G2 is responsible for doing the recenter and this is all internal to their system. We reported this to them but have not followed up. There is no way for FxR to work around this. We can only draw what the device tells us is up.
