### ISSUE TITLE
[Private Browsing] The "Cannot Complete Request" error is displayed after refreshing the description page

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3617]
**[Affected Versions]:**
- Firefox Reality version 11 RC3 (f645302).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Click the PB button from the tray.
2. Click the Refresh button to refresh the description page.
3. Observe the behavior.

**[Expected results]:**
- The description page is refreshed.

**[Actual results]:**
- The "Cannot Complete Request" error is displayed.

**[Notes]:**
- The page is still not displayed if the "Try Again" button is clicked from the page displayed.
- This issue is not reproducible if the page is navigated back using the navigation buttons.
- Attached is a screen recording of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1B0lsXpXq1-ZWgdx3ncTwO2vDWQkY_pSg/view?usp=sharing).

**Comment by keianhzo** [comment]
I suspect this might be a GV regression.

**Comment by bluemarvin** [comment]
> I suspect this might be a GV regression.

@keianhzo Maybe we can block the reload button for this page and also file a GV issue at the same time?

**Comment by keianhzo** [comment]
ok, I wanted to confirm that was a GV issue first. I've posted the fix, I'll open the GV issue when I research a bit more.

**Comment by keianhzo** [comment]
Related GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1650814

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with Firefox Reality version 11 RC5 (c28ddb2). Now the Refresh button is grayed out for the PB description page.

Tested on Oculus Quest (Android 7.1.1), HTC Vive Focus (Android 7.1.2), and Pico Neo2 (Android - 8.1.0).
