### ISSUE TITLE
UR Finding: Users would like to position window closer or further away (Z-Axis)

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#362]
UR Finding: Users would like to position window closer or further away (Z-Axis). 

Things to explore:
- how does window size relate to user need when viewing videos? (IMAX big screen for theater mode?)
- how does window size relate when keeping text size same (larger viewing window but font doesn't change in size)

Depends on #480

**Comment by cvan** [comment]
This has been handled in issue #471 and PR #463. Though it was not intuively obvious to me, when I figured it out, it worked well in my testing of PR #463 on my Oculus Go.

When PR #463 gets merged, I think we can close this issue.

**Comment by avrignaud** [comment]
Moved to backlog.

**Comment by philip-lamb** [comment]
Added a dependency to #480.

**Comment by cvan** [comment]
This seems very similar to #480. Can we dupe one of them?

**Comment by avrignaud** [comment]
@cvan I think this bug is specifically about being able to move the window closer or further from viewpoint (Z axis), and was UX finding from the blink study. It appeared to be an attempt to address window sizing for those users who weren't happy with the mobile website being served. They wanted to see more of the page on the screen when it was made larger - similar to what they are used to on desktop.

While we may have addressed this with recent window sizing changes. we still need to be able to move a window in Z space as well as find ways to pin them for AR devices. So suggest keeping, unless we want to capture elsewhere?

**Comment by philip-lamb** [comment]
I'm in favor of keeping it as a dependency. For 3dof devices, this is basically about the amount of stereopsis users are comfortable with, but for 6dof devices it has to be rolled into the ability to actually place the window in the environment.
