### ISSUE TITLE
[Keyboard: Thai] The "Go" string is not displayed in the keyboard language selected

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3626]
**[Affected Versions]:**
- Firefox Reality version 11 RC3 (f6453025)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Click inside the awesomebar.
2. Change the keyboard language to Thai.
3. Observe the Enter/Go key.

**[Expected results]:**
- The "Go" string is displayed in the keyboard language.

**[Actual results]:**
- The "Go" string is not displayed in the keyboard language.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1z7b8jqv2WXKgqxkOpLX4jUWrlM9LHkj-/view?usp=sharing).

**Comment by keianhzo** [comment]
Duplicate of #3625
