### ISSUE TITLE
[ziare.com] The content crashes when opening a certain news feed from this website

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3628]
**[Affected Versions]:**
- Firefox Reality version 11 RC3 (f645302).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to this [page](https://ziare.com/facebook/utilizatori/toata-lumea-poate-posta-pe-facebook-fotografii-la-360-de-grade-iata-cum-functioneaza-foto-video-1425088) .
2. Observe the behavior.

**[Expected results]:**
- The page is correctly loaded.

**[Actual results]:**
- The content crashes.

**[Notes]:**
- I set the severity of the issue to "Major" because we can be certain that the route cause of the issue does not affect other websites, until further investigations.
- Attached is a screen recording, logcat and the crash report of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1RpwSfHSwjRG38Jj22HMPXsuKCTVR1YeI/view?usp=sharing).
	- Crash Report: [link](https://crash-stats.mozilla.org/report/index/7c55aea0-f82d-4acc-b8b6-1c4230200706).
	- Logcat: [link](https://drive.google.com/file/d/1-5dEPsKpw53JYdafJZmEwJRiCBX_pnD1/view?usp=sharing).

**Comment by bluemarvin** [comment]
Gecko issue on bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1642994

**Comment by MortimerGoro** [comment]
The original URL is not reliable to reproduce the issue. I think is caused by and ad that is not always present.

The problem is related to using a WebGL canvas with a CSS filter.

I created a better URL to reproduce the issue: https://mortimergoro.github.io/webvr.info/samples/filter.html

**Comment by MortimerGoro** [comment]
I posted a gecko patch to fix the issue: https://phabricator.services.mozilla.com/D82944

**Comment by Softvision-GeluHaiduc** [comment]
We encountered a different scenario as well witch gives the same crash report but only on the HTC Vive Focus Plus device.
STR
- go to [delightvr](https://delight-vr.com/video-player-module/) and play a video
- click the VR goggles (the video does not enter immersive mode and the vr goggeld can be clicked)

[Crash report](https://crash-stats.mozilla.org/report/index/9d8c8c38-a3f1-4b0b-b023-b29830200710)

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 11 RC8 (076802af) installed on Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the content doesn’t crash on certain news feed from ziare.com and also it doesn’t crash when accessing https://mortimergoro.github.io/webvr.info/samples/filter.html
