### ISSUE TITLE
[XRDinosaurus] The dinosaurus are no longer displayed when entering immersive mode

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3632]
**[Affected Versions]:**
- Firefox Reality version 11 RC3 (f6453025)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Open the https://www.xrdinosaurs.com/ page.
2. Enter immersive mode on the XRDinosaurus.
3. Observe the behaviour.

**[Expected results]:**
- Immersive mode can be entered and navigated, dinosaurs can be selected. 

**[Actual results]:**
- Immersive mode is broken and can not be navigated, controllers are not rendered. 

**[Notes]:**
- The issue is also reproducible in the latest main build.
- The immersive environment is completely different from before.
- The issue is not reproducible on the oculus browser.
- The website is broken after exiting immersive mode.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1qHwTM9EBb5rnNLFzBX-gN05HT0hgIzj3/view?usp=sharing).

**Comment by fernandojsg** [comment]
This is a bug related to our `ImageBitmap` implementation (see bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1367251)

Three.js just recently started using `ImageBitmap` for faster decoding of textures, but as it's broken in gecko, they needed to include a browser sniffing to avoid using it when running in Firefox: https://github.com/mrdoob/three.js/commit/70aed3c8092392b73083e1d403ab9a90e4caa975

Brandon was updating xrdino demo to use `ImageBitmap`, but without the sniffing workaround so it was breaking in all our browsers:
```
TypeError: Window.createImageBitmap: 2 is not a valid argument count for any overload.
    load https://www.xrdinosaurs.com/js/third-party/three.js/build/three.module.js:42405
    promise callback*load https://www.xrdinosaurs.com/js/third-party/three.js/build/three.module.js:42403
    loadTexture https://www.xrdinosaurs.com/js/third-party/three.js/examples/jsm/loaders/GLTFLoader.js:2091
```

I submitted a PR (https://github.com/toji/xr-dinosaurs/pull/3) to fix it, including the same workaround they did in three.js, and I tested it both in Firefox and Firefox Reality and it works as expected
![image](https://user-images.githubusercontent.com/782511/86852052-53280780-c0b4-11ea-866e-e2e02417cf82.png)

In the meantime you can test that PR merged into my fork: https://fernandojsg.github.io/xr-dinosaurs

**Comment by fernandojsg** [comment]
It's merged already https://github.com/toji/xr-dinosaurs/pull/3#event-3526126233 so it should be fine now

**Comment by MortimerGoro** [comment]
Thanks for helping with this one @fernandojsg!

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 11 RC6 (e4f476ee) installed on Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the dinosaurs are displayed when entering immersive mode and can be interacted with.
