### ISSUE TITLE
[Keyboard] The app crashes when clicking the Shift key

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3637]
**[Affected Versions]:**
- Firefox Reality version 11 RC4 (c28ddb2).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Focus the Awesomebar to display the keyboard.
2. Click the Shift key from the keyboard
3. Observe the behavior.

**[Expected results]:**
- The keyboard switches to uppercase.

**[Actual results]:**
- The app crashes.

**[Notes]:**
- This issue is reproducible with all keyboards (where Shift key is available) except the Thai keyboard.
- I was not able to verify this issue on the HTC devices because RC4 build can't be opened after installing/updating.
- Attached is a screen recording, logcat and the crash report of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1VOj0Ucx1bPDwMVfcD8-bVU2J4UrF3nTF/view?usp=sharing).
	- Crash Report: [link](https://crash-stats.mozilla.org/report/index/f660c27d-0002-480a-a596-a37570200707).
	- Logcat: [link](https://drive.google.com/file/d/1VSFB_YjRhl4r2icGIRtx4mIPv9c2FEpl/view?usp=sharing).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 11 RC5 (4ca1220b) installed on Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the app doesn’t crash when clicking the shift key on the keyboard.
