### ISSUE TITLE
[HTC] The app can't be opened after updating/installing to/the v11 RC4 build

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3638]
**[Affected Versions]:**
- Firefox Reality version 11 RC4 (c28ddb2).

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Steps to reproduce]:**
1. Install or update FxR to v11 RC4.
2. Open the Firefox Reality browser.
3. Observe the behavior.

**[Expected results]:**
- The app is opened.

**[Actual results]:**
- The app can't be opened.

**[Notes]:**
- This issue is currently blocking us from testing on the HTC devices.
- This issue is not reproducible on the Oculus and Pico devices.
- Attached is a screen recording of the issue:
	- Screen recording: [link](https://drive.google.com/file/d/1Y-SC8vokvxiwCZvJw7Yt5nPtSpgn7cVM/view?usp=sharing)

**Comment by bluemarvin** [comment]
Looks like maybe a bad build. There was a previous v11 rc4 that can be downloaded here: https://community-tc.services.mozilla.com/api/queue/v1/task/MTrF4rqzRwaYL_4G_g-X-w/runs/0/artifacts/public/FirefoxReality-11-141882028-wavevrStore-arm64-release-signed.apk that might work until we can create an rc5.

**Comment by bluemarvin** [comment]
It isn't clear why this APK fails to launch but I have tested the rc5 build on the Focus Plus and it launches an runs as expected. Taskcluster may have generated a bad build for wavevr.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 11 RC5 (4ca1220b) installed on the HTC Vive Focus and HTC Vive Focus Plus headsets.
Now, the app can be opened after updating/installing to/the RC5 build.
Based on this and the above comment I will close the issue.
