### ISSUE TITLE
Possible to add a telemetry probe for when a search is performed?

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#364]
Is it possible for us to add a telemetry counter for when a search is performed? We'd love to know, in general, what volume of searches are coming from Firefox Reality across our various search partners.

**Comment by larsbergstrom** [comment]
We'd like to know:
1) How many searches have we performed, especially as sent to our default search providers?
2) How many voice translations did we do for searches?

**Comment by daoshengmu** [comment]
1. Regarding to the searches for our search providers, the telemetry component already has it. We just need to see how to activate it.
2. I am not sure if voice translations search is ready for the telemetry component. I will talk to @pocmo .

**Comment by pocmo** [comment]
We do multiple search related things in our apps:

* Send a UI event if a search was performed: Useful to know when a search was done (e.g. correlate with other events).
* The [core ping ](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/data/core-ping.html) contains a count of searches done (including the search engine identifier)
* We report some settings (including default search engine) in the core ping.
* We send various UI events related to search suggestions

**Comment by liuche** [comment]
Thanks @pocmo! I filed #398 to go over data review process.
