### ISSUE TITLE
[Keyboard: Thai] The keyboard is cut off at the bottom when reopening the keyboard after dismissing the symbol keyboard

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3640]
**[Affected Versions]:**
- Firefox Reality version 11 RC4 (c28ddb2e)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Pico G2 4K - Android 8.1.0
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Make sure the Thai keyboard is selected.

**[Steps to reproduce]:**
1. Click inside the awesomebar.
2. Switch to the symbol keyboard.
3. Dismiss the keyboard.
4. Click inside the awesomebar and observe the keyboard.

**[Expected results]:**
- The Thai keyboard is displayed correctly.

**[Actual results]:**
- The Thai keyboard is cut off at the bottom of the keyboard.

**[Notes]:**
- The keyboard remains cut off until the language is changed.
- Changing the keyboard is difficult by the fact that only a small portion of the button is visible.
- The issue could not be verified on HTC devices because of #3638.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1jJvlteRbcYFNtjndA1AwbWNkinWcbJGB/view?usp=sharing).

**Comment by bluemarvin** [comment]
Accidentally closed by wrong PR.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 11 RC5 (4ca1220b) installed on Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the keyboard is no longer cut off at the bottom when reopening the keyboard after dismissing the thai symbol keyboard.
