### ISSUE TITLE
Spaces are not continuously inserted when the Space key is clicked and hold

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3641]
**[Affected Versions]:**
- Firefox Reality version 11 RC4 (c28ddb2e)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Pico G2 4K - Android 8.1.0
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Make sure any language beside Thai is selected.

**[Steps to reproduce]:**
1. Click inside the awesomebar so that the keyboard is displayed.
2. Click and hold the space key.
3. Observe the awesomebar.

**[Expected results]:**
- Spaces are continuously inserted.

**[Actual results]:**
- Only one space is inserted.

**[Notes]:**
- This issue is not reproducible with the "Delete" key.
- The issue is reproducible with any language except for Thai.
- The issue could not be verified on HTC devices because of #3638.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1l9tS8sWjamh1V5UNr6QqqLUR1puadmxr/view?usp=sharing).

**Comment by bluemarvin** [comment]
Fixed by #3649

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 11 RC5 (4ca1220b) installed on Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, spaces are continuously inserted when the space key is clicked and held.
