### ISSUE TITLE
[Oculus Quest] The app keeps crashing in the background after the latest Oculus update

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3643]
**[Affected Platforms]:** 
- Firefox Reality version 11 RC4 (c28ddb2).

**[Prerequisites]:**
- The Firefox Reality app is installed.

**[Steps to reproduce]:**
1. Open the FxR browser.
2. Click the Oculus button and Quit the app.
3. Wait for ~ 5 seconds and observe the behavior.

**[Expected results]:**
- The new device menu is displayed and nothing happens if no actions are made.

**[Actual results]:**
- The "Firefox Reality keeps stopping" prompt is displayed.

**[Notes]:**
- The prompt is displayed multiple times while navigating the device menu.
- This issue could also affect the production version but I'll follow up with a comment given the urgency of this issue.
- Attached is a screen recording of the issue:
	- Screen recording: [link](https://drive.google.com/file/d/1r_trjPgYLu2U1A_UEkivUb-jZszBgVhU/view?usp=sharing).
	- Logcat: [link](https://drive.google.com/file/d/1Etk1lHdMlJoX2Vq3EsvrYMeZ6xsZNka8/view?usp=sharing).

**Comment by Softvision-RemusDranca** [comment]
I was not able to reproduce the issue using 10.2, production version of the app, using my Oculus Quest, but I think that an additional check on a second device could help make sure that this is not affecting production.

**Comment by bluemarvin** [comment]
@keianhzo says it is a new issue with telemetry only affecting v11.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with Firefox Reality version 11 RC5 (c28ddb2). The "Firefox Reality keeps stopping" prompt is no longer displayed after Quiting the app.

Tested on Oculus Quest (Android 7.1.1).
