### ISSUE TITLE
[Oculus Quest] The app thumbnail is grayed out in the Apps menu shortcut when the Wi-Fi is off

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3647]
**[Affected Platforms]:** 
- Firefox Reality version 11 RC4 (c28ddb2).

**[Prerequisites]:**
- The Firefox Reality app is installed.

**[Steps to reproduce]:**
1. Navigate to the device settings and turn off the Wi-Fi.
2. Return to the universal menu (Apps).
3. Observe the Firefox Reality thumbnail.

**[Expected results]:**
- The thumbnail is not grayed out.

**[Actual results]:**
- The thumbnail is grayed out.

**[Notes]:**
- If the thumbnail is clicked the Wi-Fi settings prompt is displayed.
- This issue is not reproducible with the thumbnail available in the device "Home" section. The app is directly opened from this section.
- Attached is a screen recording of the issue:
	- Screen recording: [link](https://drive.google.com/file/d/1-YVBc0-C42VerctUsBXG4_Aaxq9mw7HX/view?usp=sharing).

**Comment by Softvision-RemusDranca** [comment]
After further investigation it seems that the thumbnail is displayed in the "Home" section only if it was one of the recent 4 apps opened, so this workaround could not always be available.
I'll change the severity of this issue to "Major" because we think that it can block users that want to view downloaded content, without having an Internet connection.

**Comment by bluemarvin** [comment]
This looks like a setting in the app store. I can investigate changing it. I don't want to just enable it as there may be other requirements we need to meet.

**Comment by bluemarvin** [comment]
For some reason I'm still stuck on the old Quest UI and everything works as expected there. This may be an issue with the new UI they are rolling out.

**Comment by bluemarvin** [comment]
I have verified that it is the new UI that restricts app when no network is available. I've updated the information in the store but I do not know how long it will take to propagate or even if I did it correctly.

**Comment by bluemarvin** [comment]
The changes in the app store seem to have propagated and I am now able to launch FxR from the new Universal UI library panel and it is no longer grayed out.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with Firefox Reality version 11 RC7 (45f818a). The app is no longer grayed out and can be opened if there is no internet connection.

Tested on Oculus Quest (Android 7.1.1).
