### ISSUE TITLE
WebXR Content crash 

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#3648]
https://crash-stats.mozilla.org/signature/?product=Fenix&product=ReferenceBrowser&product=Focus&product=FirefoxReality&signature=mozilla%3A%3Adom%3A%3AXRWebGLLayer%3A%3AEndAnimationFrame&date=%3E%3D2020-06-30T14%3A17%3A00.000Z&date=%3C2020-07-07T14%3A17%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#reports

Over 900 crashes in 7 days

**Comment by MortimerGoro** [comment]
I posted a Gecko fix here: https://phabricator.services.mozilla.com/D82547

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with Firefox Reality version 11 RC7 (45f818a). I was not able to reproduce the crash while playing/exiting/resuming the examples from Delight XR.

Tested on Oculus Quest (Android 7.1.1), HTC Vive Focus (Android 7.1.2), and Pico Neo2 (Android - 8.1.0).
