### ISSUE TITLE
[360 cities] The immersive content is frozen after changing the “VR Setup” of the immersive content

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3656]
**[Affected Versions]:**
- Firefox Reality version 11 RC5 (4ca1220b)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to https://www.360cities.net/  
2. Click on the VR goggles and “Enter VR”
3. Look down and click the “VR Setup” button.
4. Change the “Oversampling:” setting to a higher value. (1.4 on G2 or 4.0 on GO)
5. Observe the behavior.

**[Expected results]:**
- The immersive content can still be viewed and moves according to the headset movement.

**[Actual results]:**
- The immersive content is frozen and doesn't move according to the headset movement.

**[Notes]:**
- The issue is not reproducible on HTC Vive Focus Plus and Pico Neo2 because the “VR Setup” button is not present on these devices.
- If you exit the frozen content the window is frozen when trying to reenter VR. (this behavior can be seen in the attached video)
- Sometimes the app is exited completely when trying to exit the frozen immersive content.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1tlHBc3la0wWoyxpiCzKQT56mZDqskbFp/view?usp=sharing).

**Comment by bluemarvin** [comment]
This is a case of the page overloading the GPU by allocating too large of a buffer. There isn't much we can to to prevent this.
