### ISSUE TITLE
[Intermittent] The keyboard is not dismissed when clicking a google search suggestion

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3657]
**[Affected Versions]:**
- Firefox Reality version 11 RC6 (e4f476ee)

**[Affected Platforms]:**
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Perform a partial web search using the awesomebar.  
2. Click inside the google search field and add a few characters.
3. Select one of the search suggestions from google.
4. Observe the keyboard.

**[Expected results]:**
- The keyboard is dismissed.

**[Actual results]:**
- The keyboard remains displayed until it is manually closed.

**[Notes]:**
- The issue is not reproducible if the google search is started from the google homepage.
- The issue is not reproducible on HTC Vive Focus Plus, Oculus Go and Pico G2 4K. 
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1YvM2My1maoOV7Icq7VxZrcYSy_4ygVRo/view?usp=sharing).

**Comment by daoshengmu** [comment]
it's hard to reproduce. If it only happens in Neo 2, I would guess there is something different from the OS level.
