### ISSUE TITLE
[HTC] The app crashes when reopening the app after clearing the cache

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3662]
**[Affected Versions]:**
- Firefox Reality version 11 RC6 (e4f476ee)

**[Affected Platforms]:**
- HTC Vive Focus - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Press the Vive button and exit the app.
2. In the device settings clear the cache of the FxR app.
3. Navigate back to the FxR app and open it.
4. Observe the behavior.

**[Expected results]:**
- The app opens up and works as expected.

**[Actual results]:**
- The app crashes.

**[Notes]:**
- The issue is not reproducible on Pico devices.
- The issue is not reproducible on Oculus devices as there is no way to clear the cache from device settings.
- There were several crash reports generated in the logcat file from just one crash.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1JDAAZs20rcVzd1dmRuNjQmh7NPueoy-u/view?usp=sharing).
- Attached the logcat file of the issue [log_10-07-2020_9-57-19.11.txt](https://github.com/MozillaReality/FirefoxReality/files/4901965/log_10-07-2020_9-57-19.11.txt)
- The crash report can be found [here](https://crash-stats.mozilla.org/report/index/8a80fd39-49b1-4901-95e0-e1fb70200710).

**Comment by keianhzo** [comment]
@philip-lamb I've been taking a look at this and it seems to be crashing on the SDK (libvrcore.so). We seem to quit and resume the app fine as long as the cache is cleared. Any change we can escalate this to HTC?

**Comment by keianhzo** [comment]
@Softvision-GeluHaiduc I think we might need to reconsider the severity of this:
- It only happens if the user clears the cache (which happens not very often) while the app is running
- It's very unprobable that we get a fix before v11 is released
