### ISSUE TITLE
[Delight XR] The crash prompt is displayed when pressing the Y or B buttons while in immersive mode

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3665]
**[Affected Versions]:**
- Firefox Reality version 11 RC6 (e4f476e).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to https://delight-vr.com/video-player-module/
2. Play a video near the bottom of page in immersive mode.
3. Press the Back button on the controller ("B" or "Y").
4. Observe the behavior.

**[Expected results]:**
- The video is exited from immersive mode or nothing happens.

**[Actual results]:**
- The crash prompt is displayed.

**[Notes]:**
- I was not able to reproduce this issue on Pico Neo2, nothing happens when pressing the "B" or "Y" buttons.
- I was not able to verify this behavior on HTC Vive Focus Plus, there seem to be other issues for this device. Gelu is investigating and will log a separate issue.
- Attached is a screen recording, crash report and the logcat of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1MCFE0z6Ds_wiLPrlySBosk95cuZyVxAr/view?usp=sharing).
	- Crash Report: [link](https://crash-stats.mozilla.org/report/index/e457d4ab-2eb4-405b-85f8-a58bf0200710).
	- Logcat: [link](https://drive.google.com/file/d/1tTsllKnjtg9SdOYfqyxy1Cx7trcR3Ql1/view?usp=sharing).

**Comment by MortimerGoro** [comment]
This is a duplicate from https://github.com/MozillaReality/FirefoxReality/issues/3648

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with Firefox Reality version 11 RC7 (45f818a). I was not able to reproduce the crash when pressing the Y or B buttons while in immersive mode.

Tested on Oculus Quest (Android 7.1.1), HTC Vive Focus (Android 7.1.2), and Pico Neo2 (Android - 8.1.0).
