### ISSUE TITLE
Black flicker happens when showing a widget

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#367]
## Hardware
Oculus Go

## Steps to Reproduce
1. Open the settings panel from tray

## Current Behavior
During a split second a black flicker can be seen covering the whole widget surface texture. After that the widget is rendered fine.

## Expected Behavior
A black flickering shouldn't happen. Opening the settings panel is a common task an the flickering is quite noticeable for the end user.

## Context

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/837184/44230358-39693880-a19b-11e8-8851-e6b2ae3e1bf7.gif)

**Comment by bluemarvin** [comment]
Investigated and we just need to delay showing a surface texture a few frames so that it has content before it is rendered.
