### ISSUE TITLE
[FxA] The Log In page is displayed in a loading state when trying to login

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3671]
**[Affected Versions]:**
- Firefox Reality version 11 RC7 (45f818a).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- No FxA account is logged in.

**[Steps to reproduce]:**
1. Open the Settings menu.
2. Click the "Sign Into Account" card.
3. Observe the behavior.

**[Expected results]:**
- The FxA Log In page is correctly displayed.

**[Actual results]:**
- The FxA Log In page is displayed in a loading state.

**[Notes]:**
- The issue is also reproducible if trying to log in from the "Send Tab" buttons.
- The account remains logged in after updating the app. The issue is only reproducible when trying to log in.
- Attached is a screen recording of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1u4Pt8C_trXvXb0cmZV96hhvKpgiflvb3/view?usp=sharing).

**Comment by keianhzo** [comment]
Regression from https://github.com/MozillaReality/FirefoxReality/pull/3668
Will be fixed by: https://github.com/MozillaReality/FirefoxReality/pull/3669

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with Firefox Reality version 11 RC8 (076802a). The login process can now be completed.

Tested on Oculus Quest (Android 7.1.1), HTC Vive Focus (Android 7.1.2) and Pico Neo2 - Android 8.1.0.
