### ISSUE TITLE
[DRM] Videos that use DRM can't be played and the related pop-up/prompt is not displayed

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3674]
**[Affected Versions]:**
- Firefox Reality version 11 RC7 (45f818a).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to https://www.ezdrm.com/html/drm-demos.asp
2. Play the demo from the page.
3. Observe the behavior.

**[Expected results]:**
- The video is played and DRM content is recognized on the page.

**[Actual results]:**
- The video is not played and the DRM related pop-up/prompt is not displayed.

**[Notes]:**
- The issue is also reproducible in the Firefox Nightly on mobile devices.
- This issue is not reproducible with the latest build from main (FirefoxReality-12-141931810-oculusvr-arm64-staging-main-signed.apk).
- Attached is a screen recording of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1Jo9leSyyaQl-yrYvzTeUP47sF-eTutss/view?usp=sharing).

**Comment by bluemarvin** [comment]
Should be fixed in v11 rc8

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with Firefox Reality version 11 RC8 (076802a). The DRM content can now be played.

Tested on Oculus Quest (Android 7.1.1) and HTC Vive Focus (Android 7.1.2).

Considering this, I will close this issue as verified fixed.
