### ISSUE TITLE
[Private Browsing] The "Cannot Complete Request" error is displayed after switching the user agent on the description page

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3675]
**[Affected Versions]:**
- Firefox Reality version 11 RC7 (45f818a9)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Click the PB button from the tray.
2. Click the hamburger menu and select the “Desktop Mode” option.
3. Observe the behavior.

**[Expected results]:**
- The description page is displayed in Desktop Mode.

**[Actual results]:**
- The "Cannot Complete Request" error is displayed.

**[Notes]:**
- The page is still not displayed if the "Try Again" button is clicked from the page displayed.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/17g6TUyufPqXhjDhg31V7A7fqSPrgIkZt/view?usp=sharing).

**Comment by keianhzo** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1650814
