### ISSUE TITLE
[Pico] WebXR 3D model viewer (SketchFab) not tracking head movement

### ISSUE THREAD

**Issue by picoxr** [MozillaReality/FirefoxReality#3680]
## Configuration

Firefox Reality version: release/10.2-rc4
Firefox Reality build ID: 6adc5cc

Hardware: Pico-G2 Pico-Neo2 Oculus-Quest

## Steps to Reproduce

1. Enter website https://sketchfab.com/
2. Select a 3D model to open 3D viewer
3. Click the VR goggle button to enter WebXR mode

## Current Behavior

WebXR scene shake violently and always stays right in front of user eyes

## Expected Behavior

Scene can track head movement and render the correct view in a stable way

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by MortimerGoro** [comment]
Already fixed in #3673
