### ISSUE TITLE
[A-Frame] Performance issues occur when having "A-blast" example opened

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3684]
**[Affected Versions]:**
- Firefox Reality version 11 RC8 (076802a).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Open the https://aframe.io/examples/showcase/a-blast/ example.
2. Enter and play the game for a few seconds.
4. Exit immersive mode.
3. Interact with the window and observe the behavior.

**[Expected results]:**
- The window is easily navigated.

**[Actual results]:**
- The window is hardly navigated and new windows are hardly loading.

**[Notes]:**
- If I close the window with the example, the audio is still playing for a few seconds.
- This issue is also influenced by the time that the device was used before reproducing this issue. The video captured is recorded after a device restart.
- The most affected device seems to be Oculus Quest and the less affected Pico Neo2, but this could also be influenced by the condition mentioned in the second note.
- The issue seems to be dismissed after a few seconds after closing the example.
- Attached is a screen recordings of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1NQW-wYUpIaUns-CrTZFqTDND01_RB8Kr/view?usp=sharing).

**Comment by bluemarvin** [comment]
@fernandojsg Who should we pester for WebVR/XR profiling now? I would guess a-blast is doing something bad when exiting immersive mode.
