### ISSUE TITLE
Hamburger icon is too generic and abstract

### ISSUE THREAD

**Issue by feiss** [MozillaReality/FirefoxReality#3685]
**Is your feature request related to a problem? Please describe.**

<img width="299" alt="Screenshot 2020-07-16 at 01 31 34" src="https://user-images.githubusercontent.com/359872/87609905-1dae9a00-c704-11ea-82e7-5dc743675476.png">
Tab "hamburger" menu icon is too generic. It could be more descriptive, suggesting it contains options related to the current session/tab.

**Describe the solution you'd like**
Explore alternatives

**Comment by feiss** [comment]
![#3685 hamburguer menu icon](https://user-images.githubusercontent.com/359872/87815542-10a9bc00-c866-11ea-8800-528ad93d1a4f.jpg)

**Comment by MortimerGoro** [comment]
My favorite one is the icon with 3 dots

**Comment by bluemarvin** [comment]
Switching from Hamburger to Kabob feels like a side step, but I do like that it is at least consistent with the other menus for indicating there is more.

**Comment by Softvision-GeluHaiduc** [comment]
+1 for the 3dot menu, as @bluemarvin said id would be more consistent with the other menus and with desktop.

**Comment by bluemarvin** [comment]
@feiss Has this been finalized?

**Comment by feiss** [comment]
If we agree the 3 dot menu is what we want, it's done yup.
