### ISSUE TITLE
[Keyboard: Thai] The keyboard is not redisplayed in uppercase after exiting the special character keyboard view

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3687]
**[Affected Versions]:**
- Firefox Reality version 11 RC9 (7e8fa9e).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- The keyboard language is set to Thai.

**[Steps to reproduce]:**
1. Click inside the Awesomebar so that the keyboard is displayed.
2. Double click the Shift key so that the keyboard changes to uppercase.
3. Click the key to display the special characters.
4. Click again on the same key to redisplay the normal keyboard.
5. Observe the behavior.

**[Expected results]:**
- The keyboard is displayed in uppercase.

**[Actual results]:**
- The keyboard is displayed in lowercase.

**[Notes]:**
- This issue is not reproducible with the others keyboards.
- Attached is a screen recording of the issue that also includes a scene with the behavior on the other keyboards:
	- Screen Recording: [link](https://drive.google.com/file/d/1jgNQtXhjjHVp5gDl7-6HKTco4MniqI_K/view?usp=sharing).

**Comment by daoshengmu** [comment]
Honestly, iOS and Android Thai keyboard are doing the same ways as our current Thai keyboard. I can see if it can be consistent to our other keyboard inputs. When I was trying last time, we need add some workarounds that are specific for  Thai keyboard will cause other issues.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 12 RC2 (if07516f) installed on Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the keyboard is redisplayed in uppercase after exiting the special character keyboard view for the Thai keyboard.
