### ISSUE TITLE
[HTC] The app is not opened after updating/installing the latest RC build

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3692]
**[Affected Versions]:**
- Firefox Reality version 11 RC10 (4a832421)

**[Affected Platforms]:**
- HTC Vive Focus - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2

**[Steps to reproduce]:**
1. Install/update FxR to the latest RC build (4a832421).
2. Open the Firefox Reality browser.
3. Observe the behavior.

**[Expected results]:**
- The build is opened.

**[Actual results]:**
- After the loading screen is briefly shown the dashboard is redisplayed. (the FxR logo is not displayed)

**[Notes]:**
- The issue is not reproducible on the other devices. (Oculus Go, Pico G2 4K and Pico Neo2)
- If the store version of the app is also installed after the loading screen is displayed that version of the app is opened.
- The issue is also reproducible on the latest main build as well.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1NWSNkirw-N7OQudfRMFkKIDKy6JZGq3V/view?usp=sharing).
- Attached the logcat file of the issue [log_Fri07-17-2020_11-36-34.01.txt](https://github.com/MozillaReality/FirefoxReality/files/4936679/log_Fri07-17-2020_11-36-34.01.txt).

**Comment by emstanley** [comment]
@bluemarvin let me know if this is an issue we should get Phil to review with the HTC engineering team on Monday.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 11 RC11 (cd336231) installed on HTC Vive Focus Plus and HTC Vive Focus headsets.
Now, the app is opened after updating/installing the latest RC build.
