### ISSUE TITLE
Add UI sounds

### ISSUE THREAD

**Issue by feiss** [MozillaReality/FirefoxReality#3697]
**Is your feature request related to a problem? Please describe.**
there are not sounds

**Describe the solution you'd like**
Small, short, subtle sounds on clicks and other actions would improve the experience and give more feedback to the user.

**Comment by MortimerGoro** [comment]
This one is related to https://github.com/MozillaReality/FirefoxReality/issues/353 (e.g. use Haptic feedback for hover)
