### ISSUE TITLE
Firefox shuts down when trying to view content from Sketchfab.com

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#370]
## Hardware
Oculus Go

## Steps to Reproduce
1. Visit Sketchfab.com or https://sketchfab.com/models/618ea0209b1045e89b2c6d2b74d0956e

## Current Behavior
Boom!

## Expected Behavior
View 3D models

Cvan shared following log file:

<details open>

```

08-17 15:43:23.849  3998  4018 I GeckoConsole: Found a VR display
08-17 15:43:23.850  3998  3998 D AndroidRuntime: Shutting down VM
08-17 15:43:23.851  3998  3998 E AndroidRuntime: FATAL EXCEPTION: main
08-17 15:43:23.851  3998  3998 E AndroidRuntime: Process: org.mozilla.vrbrowser, PID: 3998
08-17 15:43:23.851  3998  3998 E AndroidRuntime: java.lang.IllegalArgumentException: Unknown permission request: autoplay-media
08-17 15:43:23.851  3998  3998 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSession$6.handleMessage(GeckoSession.java:493)
08-17 15:43:23.851  3998  3998 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSession$6.handleMessage(GeckoSession.java:470)
08-17 15:43:23.851  3998  3998 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:79)
08-17 15:43:23.851  3998  3998 E AndroidRuntime: 	at org.mozilla.gecko.EventDispatcher$2.run(EventDispatcher.java:344)
08-17 15:43:23.851  3998  3998 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
08-17 15:43:23.851  3998  3998 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-17 15:43:23.851  3998  3998 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
08-17 15:43:23.851  3998  3998 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
08-17 15:43:23.851  3998  3998 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-17 15:43:23.851  3998  3998 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
08-17 15:43:23.851  3998  3998 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
08-17 15:43:23.855   983  1291 W ActivityManager:   Force finishing activity org.mozilla.vrbrowser/.VRBrowserActivity
08-17 15:43:23.867   983  1291 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
08-17 15:43:23.880  1262  1290 E SettingsProxyService: Failed to get crash reports setting
08-17 15:43:23.880  1262  1290 E SettingsProxyService: android.provider.Settings$SettingNotFoundException: crash_reports_enabled
08-17 15:43:23.880  1262  1290 E SettingsProxyService: 	at android.provider.Settings$Secure.getIntForUser(Settings.java:4425)
08-17 15:43:23.880  1262  1290 E SettingsProxyService: 	at android.provider.Settings$Secure.getInt(Settings.java:4410)
08-17 15:43:23.880  1262  1290 E SettingsProxyService: 	at com.oculus.os.SettingsProxyService$ServiceInterface.getCrashReportsEnabled(SettingsProxyService.java:50)
08-17 15:43:23.880  1262  1290 E SettingsProxyService: 	at oculus.internal.ISettingsProxy$Stub.onTransact(ISettingsProxy.java:48)
08-17 15:43:23.880  1262  1290 E SettingsProxyService: 	at android.os.Binder.execTransact(Binder.java:565)
```

</details>

**Comment by bluemarvin** [comment]
This is cause by geckoview bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1484374

**Comment by avrignaud** [comment]
Randall, any update on when this fix lands? Also, what is experience without UI? Is this required for 1.0, or a "really nice to have". Thanks!

**Comment by bluemarvin** [comment]
The fix should have landed in GeckoView over the weekend. There are three options for what we can do on the FxR side. We can either accept all requests which would allow autoplay video with audio (Which is how it was working until this feature landed in Gecko), we could reject all requests which would probably break a number of video sites, or provide a permission prompt. We probably need to be careful with so as not to annoy the user however. I would probably recommend just accepting all requests for 1.0 and push a prompt off for 1.1?

**Comment by avrignaud** [comment]
Thanks, that makes sense. Considering we don't even have a concept of multiple windows/tabs yet, I'm less worried about autoplaying video/audio at this point than we might in future. Let's accept all requests for 1.0, and we can revisit prompts in future based on user feedback/testing. 

if the patch is in GV now, is it also in FxR builds on Taskcluster? I'd like to test Sketchfab some more... :)

**Comment by bluemarvin** [comment]
There hasn't been anything pushed to FxR/master to trigger a build. I'll add the code that accepts and push it, that will trigger a new build.

**Comment by avrignaud** [comment]
Pulled new build. First time I ran it and went to sketchfab.com, browser closed out. Launched it again, and the second time I was able to get to the site and see the 3D mech model load. Lots of issues, will open a separate issue for that but we should look into that crash.

**Comment by bluemarvin** [comment]
Are you sure you didn't just hit this:  https://github.com/MozillaReality/FirefoxReality/issues/322

**Comment by avrignaud** [comment]
Can't be sure... will try to verify!

**Comment by bluemarvin** [comment]
Please close once you have verified.

**Comment by cvan** [comment]
This seems to been fixed, although Sketchfab is still working on fixing support for FxR on the Oculus Go. Closing. See related issue #374 re: perf.
