### ISSUE TITLE
[Pico G2] The controller is not displayed after sending a website using adb commands while the app is closed

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3705]
**[Affected Versions]:**
- Firefox Reality version 11 RC11 (cd336231)

**[Affected Platforms]:**
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is closed.

**[Steps to reproduce]:**
1. Using an adb command send a website to the device.
2. Observe the controller.

**[Expected results]:**
- The controller is displayed.

**[Actual results]:**
- The controller is not displayed.

**[Notes]:**
- The issue is only reproducible using the Pico G2 4K headset.
- The headset buttons can be used.
- The Pico button on the controller still works.
- After closing and reopening the FxR app the controller is displayed.
- The issue is not reproducible if the app is already opened before sending the website.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1QSDwsno24yfX5Ct8Ztf5sJyjRhxY4YlP/view?usp=sharing).

**Comment by bluemarvin** [comment]
I can't reproduce this. If the controller falls asleep before launching I see the gaze pointer. However long pressing the home button on the controller wakes it up and it becomes visible.

**Comment by Softvision-GeluHaiduc** [comment]
@bluemarvin  I tried to reproduce the issue using the latest main and it behaved as you described above, maybe I had some preconditions I wasn't aware of.
However I did manage to reproduce the issue at startup but with a different outcome.
STR:
- Power on the device
- Without putting on the headset send an adb command that opens a webpage` (e.g. adb shell am start -a android.intent.action.VIEW -d https://mixedreality.mozilla.org/hello-webxr/ -n org.mozilla.vrbrowser.internal/org.mozilla.vrbrowser.VRBrowserActivity)`
- Put on the headset

The controller is not connected and does not connect when the Pico button is pressed, you have to go in settings to connect the controller using the headset buttons.

This only happens when the headset is powered on and an adb command is sent without putting the headset on and paring the controller first. I think this is an edge case and I don’t know how many users will encounter it.
