### ISSUE TITLE
[Vimeo] A black screen is displayed when opening any type of videos

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3717]
**[Affected Versions]:**
- Firefox Reality version 12-142041820 (b9666ce).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate for example to https://vimeo.com/channels/360vr section.
2. Open a video and observe the behavior.

**[Expected results]:**
- The video preview is displayed.

**[Actual results]:**
- A black screen is displayed instead of the video's preview.

**[Notes]:**
- This issue is reproducible with all type of videos available on the website.
- This issue is also reproducible in the v11 and v10 app versions. Presumably, something changed on their end that is now in conflict with FxR browser.
- After a quit/resume the video already opened can be played but when opening another one the issue is again reproducible.
- This issue is not reproducible with Oculus browser.
- Attached is a screen recording of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1SiD2kwGYDSwadAcXeuoH9WJ77Wln-JN4/view?usp=sharing).

**Comment by MortimerGoro** [comment]
It seems that the `canvas=1` parameter is not supported anymore by vimeo so it doesn't get a valid video from the server.

We'd need to contact Vimeo to find the right way to get a equirect video or find another workaround/hack

Until we have a proper solution I think the best solution is to disable the vimeo extension.

**Comment by bluemarvin** [comment]
For reference: https://github.com/MozillaReality/FirefoxReality/issues/841#issuecomment-466289169

**Comment by bluemarvin** [comment]
It seems they support WebVR, maybe we just need to figure out what browser UA they do support and just spoof that in FxR?

**Comment by bluemarvin** [comment]
Oculus browser doesn't have an immersive mode for vimeo either.

**Comment by emstanley** [comment]
Find out who on WebCompat has the contact at Vimeo and discuss how we can reenable the canvas parameter value.

**Comment by bluemarvin** [comment]
The failure to play vimeo videos should have been fixed by #3720 and #3723. However we are no longer able to support immersive video on the Vimeo site. I have created a new issue to track re-enabling immersive mode for Vimeo: https://github.com/MozillaReality/FirefoxReality/issues/3750
