### ISSUE TITLE
[DelightXR] A black screen is displayed when opening the examples in immersive mode

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3726]
**[Affected Versions]:**
- Firefox Reality version 12-142052346 (063f0dc).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to https://delight-vr.com/video-player-module/.
2. Play the examples from the bottom of the page in immersive mode.
3. Observe the behavior.

**[Expected results]:**
- The examples are correctly played.

**[Actual results]:**
- A black screen is displayed.

**[Notes]:**
- If the trigger button is pressed while in immersive mode the videos control menu is displayed.
- The audio continues to play.
- Attachments for the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1IRhc-rtUHWzkt9EKSyMASyqlQgND0txo/view?usp=sharing).

**Comment by keianhzo** [comment]
@Softvision-RemusDranca This also seems to be fixes in RC5

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using the Firefox Reality v12 RC5 (864a696). The examples are now correctly displayed in and out of immersive mode.

Tested on Oculus Quest (Android 7.1.1), HTC Vive Focus (Android 7.1.2) and Pico Neo2 (Android 8.1.0).
