### ISSUE TITLE
[three.js] A black screen is displayed when opening the vr / video example in and out of immersive mode

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3727]
**[Affected Versions]:**
- Firefox Reality version 12-142052346 (063f0dc).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to https://threejs.org/examples/?q=webxr#webxr_vr_video
2. Play the example in immersive mode.
3. Observe the behavior.

**[Expected results]:**
- The example is correctly played.

**[Actual results]:**
- A black screen is displayed before and after entering immersive mode.

**[Notes]:**
- Attachments for the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1HqBd5A4wkasrhga4qI3EsyZwIuNElB36/view?usp=sharing).

**Comment by keianhzo** [comment]
@Softvision-RemusDranca This seems to be fixed in RC5

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using the Firefox Reality v12 RC5 (864a696). The example is now correctly displayed in and out of immersive mode.

Tested on Oculus Quest (Android 7.1.1), HTC Vive Focus (Android 7.1.2) and Pico Neo2 (Android 8.1.0).
