### ISSUE TITLE
Improve legibility of the Privacy settings panel

### ISSUE THREAD

**Issue by feiss** [MozillaReality/FirefoxReality#3737]
**Is your feature request related to a problem? Please describe.**
The Privacy panel in settings is hard to read, everything looks mixed up and appears scrambled (although it is not).

**Describe the solution you'd like**
Tweak the layout to improve legibility and make stuff easier to find.

**Describe alternatives you've considered**
Ways to improve it:
- Bolder headers
- More separation or adding elements to separate sections
- Add subsections/tabs/pagination

**Additional context**
Current state:
<img width="319" alt="Screenshot 2020-07-29 at 00 39 03" src="https://user-images.githubusercontent.com/359872/88729432-31aac080-d134-11ea-9d0a-8adac19ad9b4.png">

**Comment by bluemarvin** [comment]
I think we should just remove the `Permissions (Allow Firefox to Access)` as they are actually android app permissions and they can not be turned off once they have been turned on making the switch misleading. The proper way to toggle those permission is the app setting UI that is part of the system.

**Comment by keianhzo** [comment]
Related https://github.com/MozillaReality/FirefoxReality/issues/1758

**Comment by bluemarvin** [comment]
We should also overhaul the Display menu. There are some settings in there users should not be changing.

**Comment by feiss** [comment]
👍 
Could you specify which ones we remove?

Also, we could add a "show status bar on tray" toggle

**Comment by bluemarvin** [comment]
![Display-UI](https://user-images.githubusercontent.com/3066/89075060-31781400-d332-11ea-84f4-66efa9ed6b36.png)

**Comment by bluemarvin** [comment]
![p_and_s](https://user-images.githubusercontent.com/3066/89075239-9895c880-d332-11ea-86f9-a8da37b265d2.png)
