### ISSUE TITLE
The DRM controlled content is not recognized

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3744]
**[Affected Versions]:**
- Firefox Reality version 12-142112200 (acf8dec).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to https://www.ezdrm.com/html/drm-demos.asp
2. Play the demo from the page.
3. Observe the behavior.

**[Expected results]:**
- The video is played and DRM content is recognized on the page.

**[Actual results]:**
- The video is not played and the DRM related pop-up/prompt are not displayed.

**[Notes]:**
- Attached is a screen recording of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1Jo9leSyyaQl-yrYvzTeUP47sF-eTutss/view?usp=sharing).

**Comment by bluemarvin** [comment]
We might just need to use a newer version of GV.

**Comment by bluemarvin** [comment]
It's not GV version related. Someone turned it off in Gecko by default.

**Comment by bluemarvin** [comment]
I'll use the v11 work around until https://bugzilla.mozilla.org/show_bug.cgi?id=1656289 lands in m-c.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 12-142181700 (bb0249e9) installed on Oculus Go and HTC Vive Focus Plus headsets.
Now, DRM controlled content is recognized.
