### ISSUE TITLE
Allow browser window repositioning on the vertical axis

### ISSUE THREAD

**Issue by Colonel-Izzi** [MozillaReality/FirefoxReality#375]
Users of mobile/standalone headsets (Gear VR, Go, Daydream etc) typically value the ability to reposition content on the vertical axis so they can watch a video, or surf the net, while laying down.  Thankfully your 3DOF controller mechanics are already conducive to this so we just need a mechanic for actually repositioning the window.

**Comment by larsbergstrom** [comment]
Love the idea and thanks for opening a bug on this! We won't be able to do some experiments on this for our initial V1 release, but will look into this as part of our planning for the next release.

**Comment by avrignaud** [comment]
@MortimerGoro @thenadj Is this captured in the window positioning/resizing bugs? And likely to happen for 1.1? Trying to reduce duped bugs and scope for 1.1.

**Comment by MortimerGoro** [comment]
This is the lie down mode, which we already landed in v1.0.1. We can close this.
