### ISSUE TITLE
Slow URL changes when loading a slow URL

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#376]
## Steps to Reproduce

1. Load a slow loading URL https://sketchfab.com/models/e1a6856037c54d0d9019aedf61315569
2. Try to navigate to a different website while loading
3. The navigation takes a long time, it seems that the old URL load is not stopped quickly.

## Current Behavior

The navigation takes a long time, it seems that the old URL load is not stopped quickly.

## Expected Behavior

The navigation to the new URL should be faster.

## Possible Solution

Are we stopping the old session when loading a new URL?

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by nancyhang** [comment]
@bluemarvin is looking to see if this is a GV bug.

**Comment by philip-lamb** [comment]
Closing as forward duplicate of #682.
