### ISSUE TITLE
Keyboard placement blocks URL bar

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#377]
## Hardware

Oculus Go

## Steps to Reproduce

1. Open the keyboard
2. Try to set the cursor or select characters in the URL bar

## Current Behavior

Touch conflicts with the keyboard and the URL bar

## Expected Behavior

No touch conflicts

## Possible Solution

Quick: Move the keyboard a bit
Best solution: Better placement solution for the keyboard

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by avrignaud** [comment]
Keyboard is very close to URL bar, and aiming to select a character is very tricky. Explore moving keyboard away from URL bar. @thenadj

**Comment by MortimerGoro** [comment]
Fixed via https://github.com/MozillaReality/FirefoxReality/pull/426
