### ISSUE TITLE
Password autofill does not work in private browsing.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#3772]
## Configuration

Firefox Reality version: 12 rc1
Firefox Reality build ID: cc3eab033783edaece13dcb3b6ce88f7a823066a

Hardware: all

## Steps to Reproduce

1. Log in to FxA
2. switch to private browsing
3. visit a page that has a saved login

## Current Behavior

Password is not autofilled.

## Expected Behavior

Password is autofilled.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 12 RC2 (if07516f) installed on Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the password autofill does work in PB as well.
