### ISSUE TITLE
Content continues playing in the background after clicking on an addon

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3776]
**[Affected Versions]:**
- Firefox Reality version 12 RC1 (cc3eab03)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Make sure the uBlock addon is installed.

**[Steps to reproduce]:**
1. Navigate to a normal video on YouTube and play it.
2. Click on the hamburger menu.
3. Click the uBlock addon.
4. Observe the behavior.

**[Expected results]:**
- The addons page is opened.

**[Actual results]:**
- The addons page is opened and the content continues playing in the background.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/15uUS4FDYmgIloXKL3YxwHwaFSRmJjDzs/view?usp=sharing).

**Comment by keianhzo** [comment]
Addons require that the target session remain active to work so we explcitly keep the session you opened the addon popup for active. This is the expected behaviour. It shouldn't happen in other cases though.
