### ISSUE TITLE
[Addons] The app crashes when clicking certain elements from websites while using the "Search by Image" addon

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3777]
**[Affected Versions]:**
- Firefox Reality version 12 RC1 (cc3eab03)

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Have the "Search by Image" addon installed.

**[Steps to reproduce]:**
1. Navigate for example to the Youtube website.
2. Click the "Search by Image" button from the 3 dot menu.
3. Select a Search engine from the list displayed.
4. Click for example the 3 dot menu available for a video.
5. Observe the behavior.

**[Expected results]:**
- A menu of the video is displayed.

**[Actual results]:**
- The app crashes.

**[Notes]:**
- I was not able to reproduce the issue when selecting images.
- This issue is also reproducible with the Firefox mobile version of the app.
- Attachments for the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1OjrQOMl3tRzc9VeXtgQA9yUzANH2nD7-/view?usp=sharing).
	- Crash Report: [link](https://crash-stats.mozilla.org/report/index/9a7b9ce6-2fc9-49a2-b822-ff90f0200811).
	- Logcat: [link](https://drive.google.com/file/d/1aMSOp_-oopBWz8sFAcLNkm6RsCIeU7Sp/view?usp=sharing).

**Comment by keianhzo** [comment]
Crash in `GetDisplaySpec` in libxul. I don't think we have support for native Android Alerts in VR devices. Most probably we will need to remove the addon from the release AMO list.

**Comment by keianhzo** [comment]
After taking a deeper look, it also happens in Fenix, it is something that we should be handling in GV and at least not crash there.

**Comment by keianhzo** [comment]
Bugzilla GV bug: https://crash-stats.mozilla.org/report/index/9a7b9ce6-2fc9-49a2-b822-ff90f0200811

**Comment by keianhzo** [comment]
This has been fixed in the latest GV version but unfortunately other things break and we don't have any more bandwidth to address this before v12 so I'll just remove the add-on from the list.

**Comment by keianhzo** [comment]
Removed from the add-ons list in v12 RC6
