### ISSUE TITLE
[Desktop Mode] The UI is broken when playing 360/180 videos in immersive mode

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3778]
**[Affected Versions]:**
- Firefox Reality version 12 RC1 (cc3eab03)

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Desktop mode is enabled for the current window.

**[Steps to reproduce]:**
1. Navigate to the Youtube website.
2. Play a 360 video in immersive mode.
3. Observe the behavior.

**[Expected results]:**
- The video is correctly played.

**[Actual results]:**
- A white screen is mostly visible and the video is played in a small window in an upper back view.

**[Notes]:**
- The audio of the video is not affected by this issue.
- Attachments for the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/11sZkiJVdn8ueMPMJP02d_3ZO_EVOP7PI/view?usp=sharing).

**Comment by keianhzo** [comment]
Seems to happen when the video is started by clicking on the fullscreen icon instead of the play one.

**Comment by Softvision-RemusDranca** [comment]
I've retested this issue and it's still reproducible using the Firefox Reality v12 RC5 (864a696). The white screen is still displayed and also the video is played in a small window in the upper back view while in Desktop Mode.

Tested on Oculus Quest (Android 7.1.1), HTC Vive Focus (Android 7.1.2) and Pico Neo2 (Android 8.1.0).

Considering this I will reopen this issue.

**Comment by keianhzo** [comment]
@Softvision-RemusDranca I can't reproduce this with RC5, can you share specific STRs?

**Comment by Softvision-RemusDranca** [comment]
@keianhzo I still can reproduce this issue when entering immersive mode while in Desktop Mode. I can reproduce it even after a fresh install when using videos from content feed or directly from Youtube. I've tried to enter immersive by clicking directly in the video area and by clicking the Full Screen button and it is reproducible in both cases.
Here is a [video](https://drive.google.com/file/d/1PoFnheldSP0KTCNipeMsBsZzwESWo2vG/view?usp=sharing) (it has all the actions performed while reproducing the issue after a fresh install).
The steps, that can also be seen in the video are:
1. Select "Desktop Mode" from the 3 dot menu.
2. Open a 360 video from Youtube.
3. Play it in immersive by clicking inside the video or by clicking the Full Screen button.

An observation that I make is that the first video was autoplayed after an add has finished, I clicked inside the video and while it was paused and in immersive mode it looked like it was displayed correctly, but after clicking the play button from the On Screen Controls and dismissing them, the UI was again affected.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using the Firefox Reality v12 RC6 (f10805c). The 360/180 videos tested on Youtube are now correctly played in immersive while in Desktop Mode.
However, it seems that this issue is still affecting 360/180 videos that need to be played in immersive mode by entering first in full screen mode and then selecting a projection option from the projection menu. I opened issue #3873 for this behavior since it needs more steps.

Tested on Oculus Quest (Android 7.1.1), HTC Vive Focus (Android 7.1.2) and Pico Neo2 (Android 8.1.0).

**Comment by amcgowan93** [comment]
I'm getting this problem on a set of Lenovo Mirage VR S3 devices. They have just been updated to version 12.2 of Firefox Reality and we can't watch videos on 360 anymore from the YouTube desktop site (youtube.com). They will play from m.youtube.com, but they are distorted and stretched from the mobile site and miss most of the video.

![Screenshot_org mozilla vrbrowser_2021 11 23-13 49 17](https://user-images.githubusercontent.com/94883935/142969019-5da649a9-1677-489e-a772-ea07299e9988.jpeg)
![Screenshot_org mozilla vrbrowser_2021 11 23-13 52 20](https://user-images.githubusercontent.com/94883935/142969029-5224647a-1933-4790-a5c6-6ae703dc7b61.jpeg)
![Screenshot_org mozilla vrbrowser_2021 11 23-13 48 26](https://user-images.githubusercontent.com/94883935/142969030-ce798acd-b450-43c8-81f1-598e59cdb747.jpeg)

Videos used to play perfectly from the desktop site prior to updating Firefox Reality.
