### ISSUE TITLE
Keyboard placement not comfortable for the wrist

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#378]
## Problem

I have to bend the wrist a lot to use the keyboard, which is not very comfortable. Tried the placement on other browsers and it's more comfortable because it's centered and I don't need to bend the wrist

## Possible Solution

Better position placement algorithm, we can detect the input position and place the keyboard more on the center of the screen.

**Comment by nancyhang** [comment]
@thenadj any thoughts on the design?

**Comment by thenadj** [comment]
We will look into better placement for keyboard after v1.

**Comment by fernandojsg** [comment]
I agree, after using intensively in the last weeks I find it quite uncomfortable for my wrist too. Even sitting on my desk, not to say when I'm laying down on the sofa :\

**Comment by caseyyee** [comment]
The keyboard ergonomics are pretty bad. My hands hurt just thinking about it. Especially doing development work where there is a lot of keyboard use, it really is unpleasant to use.

I notice the entire browser view + url bar are really low, just simply moving it up a few degrees would help - no smart positioning necessary.

**Comment by thenadj** [comment]
Attached are updated keyboard designs for positioning and also a text field for URL bar entry. 
This is ready for review. 
[DE-28 Keyboard Positioning_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2515868/DE-28.Keyboard.Positioning_001.pdf)
[DE-12 Keyboard_008.pdf](https://github.com/MozillaReality/FirefoxReality/files/2515869/DE-12.Keyboard_008.pdf)

**Comment by thenadj** [comment]
@MortimerGoro Yes, please close it.
