### ISSUE TITLE
The password and username of a saved login revert back after being edited to empty

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3781]
**[Affected Versions]:**
- Firefox Reality version 12 RC1 (cc3eab03)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Make sure to have the settings menu open.

**[Steps to reproduce]:**
1. Click the "Saved logins..." button from the "Logins And Passwords" card.
2. Click on one of the entries from the list.
3. Edit the username and password to be empty.
4. Click the "Save" button and go back to the list of saved logins.
5. Click on the entry previously edited.
6. Observe the username and password.

**[Expected results]:**
- The username and password fields are empty.

**[Actual results]:**
- The username and password fields revert back to their original value.

**[Notes]:**
- If only the username field is empty the value does not revert back.
- If only the password field is empty the value reverts back.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/17oh8TiziEE4sqg0UZ9pO9Onn5IePBQ_W/view?usp=sharing).

**Comment by keianhzo** [comment]
The password is a required field, cannot be empty. You can leave the username empty but not the password. We should show a warning that it's required, that would be the nice thing to do.

**Comment by Softvision-RemusDranca** [comment]
@keianhzo I think that an error/warning message will be great to have in this case to exclude any user confusion. Will this be implemented for this release?

**Comment by keianhzo** [comment]
I've added a warning message when the password field is left empty.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using the Firefox Reality v12 RC5 (864a696). Now, the "Password cannot be empty" warning is displayed when trying to save changes with no password.

Tested on Oculus Quest (Android 7.1.1), HTC Vive Focus (Android 7.1.2) and Pico Neo2 (Android 8.1.0).
