### ISSUE TITLE
The scrollbar of the saved logins popup is the same color as the hovered entry in the list

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3786]
**[Affected Versions]:**
- Firefox Reality version 12 RC1 (cc3eab03)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Make sure to not be logged in.
- Make sure to have more than 3 accounts saved for the website used.

**[Steps to reproduce]:**
1. Navigate to https://twitter.com/login 
2. Using the controller hover the pointer over one of the entries in the list.
3. Observe the scrollbar.

**[Expected results]:**
- The scrollbar is visible.

**[Actual results]:**
- The scrollbar has the same color as the hovered entry in the list.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1Gr3f213wvzN3xow8fPAaFt84aCfM9iJb/view?usp=sharing).

**Comment by keianhzo** [comment]
This is by design and is also the case in other lists like Bookmarks/History/Downloads. I've added some padding to the list so the scrollbar and the items don't overlap.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using the Firefox Reality v12 RC4 (9fd870c). Now there is a padding between the list and the scrollbar and the items don't overlap so the same color is no longer creating an issue.

Tested on Oculus Quest (Android 7.1.1), HTC Vive Focus (Android 7.1.2) and Pico Neo2 (Android 8.1.0).
