### ISSUE TITLE
[Addons] The download process is not always canceled when clicking the "Cancel" button

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3788]
**[Affected Versions]:**
- Firefox Reality version 12 RC1 (cc3eab03)

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Open the Addons page in the Library.
2. Click the "+" button from one of the addons.
3. Click the "Add" button from the prompt displayed.
4. Click the "Cancel" button from the Download in progress prompt.
5. Observe the behavior.

**[Expected results]:**
- The prompt is dismissed and the download process is stopped.

**[Actual results]:**
- The prompt is dismissed but the download process is not always stopped.

**[Notes]:**
- This issue seems to be affected by the size of the addon and the time when the "Cancel" button is clicked while the addon is downloading..
- Attachments for the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1v5MgieJPxHKK6W0HYu1ygOmiad9IHwTP/view?usp=sharing).

**Comment by keianhzo** [comment]
This will depend on how far on the install process you have gone when clicking the cancel button. There might be chances that the process is already finished when the cancel button is clicked. Not sure if there is much that we can do about it.

**Comment by keianhzo** [comment]
I don't see much we can do here and it's also kind of a corner case so I think it's safe to close it.
