### ISSUE TITLE
The settings menu or tabs view is wrongly dismissed when the saved logins popup appears

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3790]
**[Affected Versions]:**
- Firefox Reality version 12 RC1 (cc3eab03)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Make sure to not be logged in.
- Make sure to have more than 3 accounts saved for the website used.

**[Steps to reproduce]:**
1. Navigate to https://twitter.com/login 
2. While the website is loading click the Settings button from the menu tray.
3. Observe the behavior.

**[Expected results]:**
- The settings menu can be navigated.

**[Actual results]:**
- The settings menu is dismissed when the saved logins popup appears.

**[Notes]:**
- The issue is also reproducible with Tabs View.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1L5oldUMpvwzws29rFTfqwzJ8B51NIIni/view?usp=sharing).

**Comment by keianhzo** [comment]
This would actually happen with any dialog that content shows sync. I guess we could add a flag to block other popups for certain dialogs to avoid this cases.
