### ISSUE TITLE
The saved logins popup wrongly reappears when the password or username fields are empty after selectin a saved login

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3791]
**[Affected Versions]:**
- Firefox Reality version 12 RC1 (cc3eab03)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Make sure to not be logged in.
- Make sure to have more than 3 accounts saved for the website used.

**[Steps to reproduce]:**
1. Navigate to https://twitter.com/login 
2. Dismiss the saved logins popup.
3. Delete the password.
4. Observe the behaviour.

**[Expected results]:**
- The password can be deleted and a new password can be typed.

**[Actual results]:**
- When the password is completely deleted the saved logins popup reappears.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1v-CKyl19NIPWcCOscPvrY3jscN6iAWtd/view?usp=sharing).

**Comment by Softvision-GeluHaiduc** [comment]
After further investigation, the issue is also reproducible with the username field, [here](https://drive.google.com/file/d/1UKNMO-Qs0dkBDKUzYRfS4KTUBUfmIHLK/view?usp=sharing) is a video recording of this behavior. This behavior also obstructs the user from logging in with a different account.
Also on some websites when you try to create a new account the saved logins popup is displayed if there are any users saved from before. 
Giving all these behaviors observed I will update the title and the severity of the issue.

**Comment by keianhzo** [comment]
I don't see much we can do about this with the current GV version, GV prompts use anytime it considers a login selection should be prompted.
