### ISSUE TITLE
Incomplete tooltips are displayed for controllers and headset battery levels

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3792]
**[Affected Versions]:**
- Firefox Reality version 12 RC1 (cc3eab03)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Using the controller, hover the pointer over the controller/headset icon.
2. Observe the tooltip.

**[Expected results]:**
- The following text is displayed in the tooltip:
     - "Left Controller: xx%"
     - "Right Controller: xx%"
     - "Headset: xx%"

**[Actual results]:**
- The following text is displayed in the tooltip:
     - "xx%"
     - "xx%"
     - "xx%"

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1hGc2s97IynECFaSDn3Tabj7LX_8Jrxvt/view?usp=sharing).

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using the Firefox Reality v12 RC5 (864a696). The "Left Controller: xx%", "Right Controller: xx%", "Headset: xx%" tooltips are now displayed.

Tested on Oculus Quest (Android 7.1.1), HTC Vive Focus (Android 7.1.2) and Pico Neo2 (Android 8.1.0).
