### ISSUE TITLE
[Addons] The "Youtube HD" addon overrides some of the app controlled functionalities over Youtube affecting the overall experience

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3794]
**[Affected Versions]:**
- Firefox Reality version 12 RC1 (cc3eab03)

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- The Youtube Hight Definition addon is installed.

**[Steps to reproduce]:**
1. Navigate to the Youtube website.
2. Play for example a 360 video having a 8k resolution available.
3. Observe the behavior.

**[Expected results]:**
- The video is correctly played.

**[Actual results]:**
- The video can't be played having an 8k resolution.

**[Notes]:**
- Depending on the settings set for the addon the UI changes and can sometimes make the website hard to navigate. 
- In some attempts while trying to reproduce this issue the app was exited.
- Attachments for the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/10PG9kfSvZZ7FrIWprmaEOai2hgsmPnw2/view?usp=sharing).

**Comment by keianhzo** [comment]
Given that we already have our own implementation we should disable this one.

**Comment by keianhzo** [comment]
Removed from the add-ons list in v12 RC6
