### ISSUE TITLE
[Addons][Decentraleyes] The Settings page is not displayed and the window is frozen when clicking the "Settings" button from the custom web page

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3797]
**[Affected Versions]:**
- Firefox Reality version 12 RC1 (cc3eab03)

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- The Decentraleyes addon is installed.

**[Steps to reproduce]:**
1. Click the Decentraleyes button from the 3 dot Menu.
2. Click the Settings (wheel) button from the custom web page displayed.
3. Observe the behavior.

**[Expected results]:**
- The addon's Settings page is displayed.

**[Actual results]:**
- The current page is dismissed and the window remains frozen.

**[Notes]:**
- The Back navigation button is actionable.
- This issue is not reproducible when opening Settings from the Manage add-on page (Library).
- This issue is not reproducible on Firefox mobile.
- Attachments for the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1ZpLnTabPBI8rCMlZW5KLzNOX8puRITlN/view?usp=sharing).

**Comment by keianhzo** [comment]
Probably this addon will need to be removed from the list.

**Comment by keianhzo** [comment]
Removed from the add-ons list in v12 RC6
