### ISSUE TITLE
The search fields are missing for the saved logins and exception lists

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3799]
**[Affected Versions]:**
- Firefox Reality version 12 RC1 (cc3eab03)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Make sure to have at least 10 websites in the saved logins list.
- Make sure to have the settings menu open.

**[Steps to reproduce]:**
1. Click the "Saved logins..." button from the "Logins And Passwords" card.
2. Observe the UI.

**[Expected results]:**
- The "Saved logins" list has a search field.

**[Actual results]:**
- The "Saved logins" list does not have a search field.

**[Notes]:**
- The search field is also missing for the exceptions list.
The “Sort by” button is also missing from the "Saved logins" list. 
- Attached a screenshot of the issue bellow.
![Tue08-11-2020_11-50-31 82](https://user-images.githubusercontent.com/51400741/90120317-48235f80-dd63-11ea-8d0b-3c8b3e2bf8de.png)

**Comment by keianhzo** [comment]
We left the search fields out of these dialogs because of time constraints.
