### ISSUE TITLE
Improve URL detection on the URLBar

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#38]
CXB-22 Currently you need to add the protocol to detect a URL, and it does a google search if you don't add it.

Check what other browsers do in order to detect when to automatically load a URL instead of a search.

**Comment by bluemarvin** [comment]
There are two issues here I think. One we need to detect when the protocol is missing from the url. Awesome bar looks for '.' separated with no white space. GeckoView doing a search is actually a bug in GV. All search needs to be external to GV. I expect soon, GV will error out if the url can't be resolved.
