### ISSUE TITLE
UR Finding: Users would like ability to select different accounts within browser

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#380]
UR Finding: Users would like ability to select different accounts within browser (not device).

User would like different user accounts so search terms/history/private mode are different per user in same household. Netflix solution of allowing user to log in by selecting profile was highlighted. 

Consider using PIN to protect access?

**Comment by cvan** [comment]
Samsung Internet allows a PIN requirement for opening its Private Browsing mode, something I pitched a while back and excited to see in production. I have a few other ideas here. I would love to have a conversation here with interested folks.

**Comment by avrignaud** [comment]
+1 - definitely love to have your input when we explore private mode/profiles in 1.1!

**Comment by philip-lamb** [comment]
Duplicates #359
