### ISSUE TITLE
The wrong kind of delete button is shown for the exceptions list entries

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3801]
**[Affected Versions]:**
- Firefox Reality version 12 RC1 (cc3eab03)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Make sure to have at least one website in the exceptions list for saving logins.
- Make sure to have the settings menu open.

**[Steps to reproduce]:**
1. Click the "Exceptions..." button from the "Logins And Passwords" card.
2. Hover the pointer over one of the entries in the list.
3. Observe the UI.

**[Expected results]:**
- When the entry is hovered a trash can icon appears in the far right side of the entry.

**[Actual results]:**
- When the entry is hovered an “X” icon appears at the beginning of the entry in the far left side.

**[Notes]:**
- The function remains the same, it deletes the entry.
- Attached a screenshot of the issue bellow.
![Tue08-11-2020_11-52-34 64](https://user-images.githubusercontent.com/51400741/90133695-9c850a00-dd78-11ea-876a-2af65505518c.png)

**Comment by keianhzo** [comment]
We decided to go with the same list structure as for the other exceptions list to keep the consistency.

As a rule for this release I'd say, don't consider design disparities as a bug only functionality issues.
