### ISSUE TITLE
[Add-ons] The add-on Manage page is dismissed when clicking the toggle switch buttons if its custom web page is opened in the background

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3804]
**[Affected Versions]:**
- Firefox Reality version 12 RC1 (cc3eab03)

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Have an add-on installed.

**[Steps to reproduce]:**
1. Click the installed add-on button from the 3 dot menu to display it's custom web page.
2. Click on the installed add-on card from prerequisites.
3. Click one of the toggle switch buttons available on the add-on's Manage page.
4. Observe the behavior.

**[Expected results]:**
- The button is switched an the Manage page remains displayed.

**[Actual results]:**
- The button is switched but the Manage page is dismiss along with the add-on custom web page.

**[Notes]:**
- This issue is not reproducible if a normal web page is opened in the background.
- Attachments for the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1hNgBwpsvHkUjpvfsCa2bOyDgfs9eT2lF/view?usp=sharing).

**Comment by keianhzo** [comment]
This is the expected behavior, the add-on request closing the add-on popup when the configuration changes.

**Comment by Softvision-RemusDranca** [comment]
@keianhzo I've retested this behavior using Firefox Reality 12 RC2 (195415f). It seems that the current behavior while following the steps above is now the Expected result mentioned in the issue, the Manage page remains displayed.

However, you mentioned in the above comment that the Actual result should be the expected behavior. Should I open a new issue or did something change and the current behavior where the Manage page remains displayed, is now the expected one?

**Comment by keianhzo** [comment]
The add-on pop up should be closed but I managed to fix the Library being dismissed so the one in this issue should be the expected behavior and this can remain closed.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue using Firefox Reality 12 RC2 (195415f) and the current behaviours as mentioned in the above comment are the ones reproducible and expected. I will mark this issue as verified-fixed.

Tested on Oculus Quest (Android 7.1.1), HTC Vive Focus (Android 7.1.2) and Pico Neo2 (Android 8.1.0).
