### ISSUE TITLE
Easter Egg: Mountaineer appears occasionally on top of mountain peak with flag. Flag is set to flag of user language setting.

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#381]
Easter Egg: Mountaineer appears occasionally on top of mountain peak with flag. Flag is set to flag of user language setting.

**Comment by larsbergstrom** [comment]
Not for 1.1. Also, this is a total geopolitical nightmare in some scenarios and should require careful review if done.

**Comment by avrignaud** [comment]
Yep, really good point. And feels like the effort to figure out the logic for showing/not showing quickly moves this from "fun easter egg" to "lots of work for no particularly good reason". I'm going to close for now.
