### ISSUE TITLE
[Add-ons] The "Settings" button from the Manage add-on page is grayed out after enabling the add-on

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3810]
**[Affected Versions]:**
- Firefox Reality version 12 RC1 (cc3eab03)

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Have an add-on installed and enabled.

**[Steps to reproduce]:**
1. Open the Add-ons page from Library.
2. Click on the installed add-on card from prerequisites.
3. Click the toggle switch button available to disable the add-on.
4. Navigate away from the page and reopen the Manage add-on page.
5. Click the toggle switch button available to enable the add-on.
6. Observe the "Settings" button.

**[Expected results]:**
- The button is actionable and it's displayed in a normal state.

**[Actual results]:**
- The button is grayed out.

**[Notes]:**
- This issue is not reproducible if the add-on is enabled right after disabling it.
- Attachments for the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1-NDMx7Xbuz8M_1G4mgBGF7esbswsi2IA/view?usp=sharing).

**Comment by keianhzo** [comment]
This should already been fixed in RC2

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using Firefox Reality 12 RC2 (195415f). The "Settings" button is no longer grayed out.

Tested on Oculus Quest (Android 7.1.1), HTC Vive Focus (Android 7.1.2) and Pico Neo2 (Android 8.1.0).
