### ISSUE TITLE
Cannot run about:config and set security.fileuri.strict_origin_policy property to false on Firefox Reality

### ISSUE THREAD

**Issue by dragongyke** [MozillaReality/FirefoxReality#3815]
## Configuration

Firefox Reality version: 10
Firefox Reality build ID: bda5ecf

Hardware: Pico Neo 2

## Steps to Reproduce

1. Connect the HMD to Laptop
2. Copy local html files (krpano) to HMD
2. Open Windows Command line window.
3. Use adb command **adb shell am start -a android.intent.action.VIEW -d "file:///storage/emulated/0/miekowo_www/index.html" org.mozilla.vrbrowser/org.mozilla.vrbrowser.VRBrowserActivity** to launch Firefox with specified local html file.

## Current Behavior

The page shows "ERROR: 
Loading local files from file:// urls is not possible due browser security restrictions!
Either change the browser settings to allow local-file-access,
or use a localhost server like the krpano Testing Server.
"
Client on "[browser settings](https://krpano.com/docu/localusage/#changebrowsersettings)", there is the Firefox related setting suggestion. 
Input about:config in Firefox Reality and it shows "Cannot Complete Request"

## Expected Behavior

Same behavior as running about:config on Firefox for PC

## Possible Solution

Or other possible methods to allow user to access local html files (krpano)

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by dragongyke** [comment]
Anyone have the same issue?

**Comment by pt1997** [comment]
you need to sideload the developer (debug) version from https://community-tc.services.mozilla.com/tasks/index/project.firefoxreality/main (as mentioned in the README.md) in that version you are able to open the about:config page. Please update this issue and share the result.
