### ISSUE TITLE
The app crashes when changing the Display language for the app

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3816]
**[Affected Versions]:**
- Firefox Reality version 12 RC1 (cc3eab03)

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Open the Language card from Settings.
2. Click the Edit button for the Display language for App option.
3. Select a language available and observe the behaviour.

**[Expected results]:**
- The display language is changed into the one selected.

**[Actual results]:**
- The app crashes.

**[Notes]:**
- The issue is also reproducible if the Reset button is clicked.
- After the app is reopened from crash, the selected language is set as default.
- Attachments for the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/14h84UYYBlOBQ0S0HWmwZevD-6ShB7qL4/view?usp=sharing).
	- Crash Report: [link](https://crash-stats.mozilla.org/report/index/30c577f3-2cff-4bfd-8742-e65510200817).
	- Logcat: [link](https://drive.google.com/file/d/1ct4gvhzz8X2JJyPfZfMJAwTPYDVQlzi3/view?usp=sharing).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 12 RC2 (195415f0) installed on Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the app does not crash when changing the Display language for the app.
