### ISSUE TITLE
The 3 dot menu is wrongly displayed when focusing the other windows

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3820]
**[Affected Versions]:**
- Firefox Reality version 12 RC2 (1f07516)

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Open a new window using the tray "+" button.
2. Click the 3 dot button from the right side of the Awesomebar.
3. Focus the other window.
4. Observe if the 3 dot menu is displayed for this window.

**[Expected results]:**
- The menu is not displayed.

**[Actual results]:**
- The menu is displayed.

**[Notes]:**
- This issue is not reproducible if the 3 Dot Menu is not displayed in the first window, before focusing the second one.
- Attachments for the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1A7KPM9XH1SgbLoUVWpYoMU_vc_foS8gc/view?usp=sharing).

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with Firefox Reality version 12 RC2 (195415f0) installed on Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the 3dot menu is not displayed when focusing on other windows.
