### ISSUE TITLE
WebXR 'getOffsetReferenceSpace' not accounting correctly for rotation

### ISSUE THREAD

**Issue by BlurrySplodge** [MozillaReality/FirefoxReality#3824]
## Configuration

Version:
Firefox Reality 11, 11.2, 12 rc1

Hardware: 
Pico Neo, Oculus Go

## Steps to Reproduce
1. Go to https://immersive-web.github.io/webxr-samples/tests/ref-space-invert.html and enter VR.
2. Hold down the 'select' button.
3. Look around.

## Current Behavior
The view is moving.

## Expected Behavior
The view should remain static, because the viewer pose relative to the offset reference space should be constant, which is the point of that particular sample/test.

## Context
The sample/test seem to be working correctly with Oculus Browser.

**Comment by parseccentric** [comment]
Confirming the same behavior on Oculus Quest 1 with Link, Firefox Reality 0.90 on Viveport (SteamVR).

Specifically, when holding down either trigger (index finger) button, the camera does not rotate as it should, but instead continues looking in the same direction. Yawing my head results in the camera strafing forwards and backwards, but it should be stationary.
