### ISSUE TITLE
White margins are wrongly visible on the top and right of the saved logins pop-up when scrolling the list

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3827]
**[Affected Versions]:**
- Firefox Reality 12 RC2 (195415f).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Have more than 3 logins saved for the tested website.

**[Steps to reproduce]:**
1. Navigate to the login page of the tested website (I used https://www.facebook.com/).
2. Focus one of the login input field to display the logins pop-up.
3. Scroll the list and observe the top and right side of the list UI.

**[Expected results]:**
- No white lines are visible.

**[Actual results]:**
- White lines are visible.

**[Notes]:**
- The white line visible at the top is not displayed on all devices.
- Attachments for the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1aH3fAsiSTxW3VrxRViHI2SpVOd2oczaX/view?usp=sharing).

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's partially fixed using the Firefox Reality v12 RC4 (9fd870c). The right side glitch is no longer visible on any of the tested devices when scrolling the pop-up's list.
However, the glitch displayed at the top is still visible on Oculus Quest, when the list from the pop-up is scrolled.

Tested on Oculus Quest (Android 7.1.1), HTC Vive Focus (Android 7.1.2) and Pico Neo2 (Android 8.1.0).

Considering this I will reopen the issue.

**Comment by keianhzo** [comment]
I don't see this anymore in RC5, maybe there are some specific STRs?

**Comment by Softvision-RemusDranca** [comment]
@keianhzo I still can reproduce it only on Oculus Quest and only when scrolling the list from the pop-up, there is a white line at the top of the list, [here](https://drive.google.com/file/d/1sUWhSOrm9OUIrJLt1dLgRrOc9Ux7fjlv/view?usp=sharing) is a video. There are no other steps performed than the ones mentioned in the issue.
