### ISSUE TITLE
UR Finding: Users expected higher fidelity rendering of environments

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#383]
UR Finding: Users expected higher fidelity rendering of environments. Found Oculus Go home screen and expressed wanting environments more similar to that. 

Explore alternative renderers for 1.1, including Filament and Kraken.

**Comment by MortimerGoro** [comment]
Oculus go home environment is just a skybox.

We can already do that.

**Comment by philip-lamb** [comment]
Moving all remaining environment related items out of v1.2.
