### ISSUE TITLE
[Intermittent] The way that time is displayed in the status bar changes when the display language is changed

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3832]
**[Affected Versions]:**
- Firefox Reality version 12 RC2 (195415f0)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Open the "Language" card from Settings and click the “Edit” button from the “Display Language for App:” option.
2. Change the display language to something else multiple times.
3. Observe the time in the status bar.

**[Expected results]:**
- Nothing changed in the status bar.

**[Actual results]:**
- The way that time is displayed changes.

**[Notes]:**
- Sometimes “AM” or “PM” disappear or “:” changes to ”.”
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1E5qK0KqMdd10MmA1QvBbupQV_TPOvufO/view?usp=sharing).

**Comment by Softvision-RemusDranca** [comment]
I've retested this issue and it's still reproducible using the Firefox Reality v12 RC4 (9fd870c). I've encountered all the behaviors mentioned in the issue's notes while changing the app language to several different ones.
Also, on HTC Vive Focus device the "AM" and "PM" strings are not displayed at all. Maybe this behavior was there to begin with but it was just not verified on this device.

Tested on Oculus Quest (Android 7.1.1), HTC Vive Focus (Android 7.1.2) and Pico Neo2 (Android 8.1.0).

Considering this, I will reopen this issue.

**Comment by keianhzo** [comment]
@Softvision-RemusDranca I see AM/PM disappearing in those locales that use the 24 hour format but that's the expected behavior. If that's the case this shouldn't be considered as an issue as we are using the system provided time format for that locale.

**Comment by Softvision-RemusDranca** [comment]
@keianhzo I took another look over this behavior and I also think that AM/PM disappearing in those locales that use the 24 hour format is expected.
The main concern is for the HTC Vive Focus device, where it seems that the 24 hour format is applied even for the languages that use a 12 hour format (English-US). 
A second concern is for the "Dansk" and "Suomi" app languages where only a dot "." separates the hour from minutes (17.23 for example). To be honest I'm not really sure if this is expected, but the same format is displayed on Oculus Quest when changing the device language.

**Comment by keianhzo** [comment]
For what I see all the platforms keep the 24 hour format regardless of the locale so I guess we should do that.

**Comment by keianhzo** [comment]
Given my comment above I'll close this issue.
