### ISSUE TITLE
The wrong time is displayed in the app if the headset time was changed while the app was opened

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3835]
**[Affected Versions]:**
- Firefox Reality version 12 RC2 (195415f0)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Exit the app and change the time of the headset.
2. Reopen the app.
3. Observe the time in the status bar.

**[Expected results]:**
- Nothing changed in the status bar.

**[Actual results]:**
- The old time is displayed.

**[Notes]:**
- After a few minutes, the time changes to the correct time.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1Jd7bKveEn1iKesUQBQ-1-jE_io3Qv5Vn/view?usp=sharing).

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using the Firefox Reality v12 RC4 (9fd870c). Now, the app displays the same time as the device.

Tested on HTC Vive Focus (Android 7.1.2) and Pico Neo2 (Android 8.1.0).
