### ISSUE TITLE
UR Finding: Users would like to able to use 360 photo as environment

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#385]
UR Finding: Users would like to able to use 360 photo as environment. This includes ability to import their own 360 photo, as well as being able to save a 360 photo found on web and set as their background environment (similar to "Set as Desktop Background" option in Windows).

**Comment by cvan** [comment]
See https://github.com/MozillaReality/FirefoxReality/issues/386#issuecomment-419311538
