### ISSUE TITLE
The user credentials are not autofilled in PB when only one login is saved

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3850]
**[Affected Versions]:**
- Firefox Reality version 12 RC3 (f2e4a1c4)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Make sure to not be logged in.
- Make sure to have only one account saved for the website used.

**[Steps to reproduce]:**
1. Click the PB button in the menu tray.
2. Navigate to a website that requires a login.
3. Observe the username/email and password fields.

**[Expected results]:**
- The username/email and password fields are automatically filled in.

**[Actual results]:**
- The username/email and password fields are NOT automatically filled in.

**[Notes]:**
- If more than one user is saved the saved logins popup appears.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1PhB5OxNN6YA7ayI01ZMxxoRRmpyhnQsl/view?usp=sharing).

**Comment by keianhzo** [comment]
I just confirmed with the GV team that this is intentional. So we are going to keep it as in AC where in doesn't auto-fill but you can select if you have more than one login.

**Comment by Softvision-RemusDranca** [comment]
I will mark this issue as invalid since this is the expected behaviour in PB ,  as mentioned in the above comment.
