### ISSUE TITLE
The user credentials are not saved when the autofill setting is off

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3851]
**[Affected Versions]:**
- Firefox Reality version 12 RC3 (f2e4a1c4)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Make sure the “Autofill” option from the "Logins And Passwords" card is set to off.
- Make sure the "Saved logins and passwords" option from the "Logins And Passwords" card is set to on.
- Make sure to not be logged in.

**[Steps to reproduce]:**
1. Navigate to a website that requires a login.
2. Log in using a never before used user.
3. Observe the behaviour.

**[Expected results]:**
- The popup to save the new login is displayed.

**[Actual results]:**
- The popup to save the new login is NOT displayed.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1i8rncPLPKh4-Lhtn4AupGwYSLL86ZHNk/view?usp=sharing).

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible using the Firefox Reality v12 RC4 (9fd870c). The popup to save the new login is now displayed even if the "Autofill" option is disabled.

Tested on Oculus Quest (Android 7.1.1), HTC Vive Focus (Android 7.1.2) and Pico Neo2 (Android 8.1.0).
