### ISSUE TITLE
UR Finding: Users would like to be able to select from different themes and graphic styles to personalize their browser

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#386]
UR Finding: Users would like to be able to select from different themes and graphic styles to personalize their browser. Was described in similar way to Firefox Desktop options to select background and themes.

**Comment by cvan** [comment]
See Samsung Internet Browser. They do a pretty good job of environment customisation. See my comment here: https://github.com/MozillaReality/FirefoxReality/issues/390#issuecomment-419311414
