### ISSUE TITLE
[Pico G2 4k] Tabs not present in remote debugger window. 

### ISSUE THREAD

**Issue by BennettWerner** [MozillaReality/FirefoxReality#3860]
## Configuration

Firefox Reality version: 77.0a1
Firefox Reality build ID: Pico Store 10-p2

Hardware: Pico  G2 4k via usb to Windows 10 PC (Firefox (79.0))

## Steps to Reproduce

1. Connect Pico G2 4k to Remote Dubugging 
2. Open Device Debugging windows of Pico G2
3. In Reality Browser open tabs

## Current Behavior

The device is connected, but tabs open in Reality Browser on G2 are not shown in the remote debugger. 

## Expected Behavior

Tabs open on the pico are present in the remote debugger and inspectable 

## Possible Solution

Investigate the connection to the remote debugger. Or advise on strategy for debugging page content on the Pico G2 4k.
## Context

I am trying to view the console.js output of a tab/page. I do not see the tabs in the remote debugger. I do see several workers and a main process with logic related to geckoview remote debugging the pico and reality browser. 
## Error Logs and Stack Traces

<details open>
Debugger is working on build 10-p1 with G2 4k 

```
```

</details>

**Comment by keianhzo** [comment]
I see the remote debugger correctly working on 10-p2 in Pico, I can see the tabs and attach to them with Firefox Desktop v79. Not sure what might be the issue. Is in working with the latest RC? https://github.com/MozillaReality/FirefoxReality/releases/tag/release%2F12-rc5

**Comment by BennettWerner** [comment]
@keianhzo thanks for looking into it. We've gone ahead and built a more up-to-date version 11+ of the FxR Apk. We found the logic to toggle on the console output in the code-base (setConsoleLogsEnabled to True and a few others). I'm now getting the console via remote debugger/usb that I was not getting via store build. Works great for dev builds.
