### ISSUE TITLE
Allow users to select Doodle for use as home environment

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#387]
Allow users to select Doodle for use as home environment. Should probably be integrated into #214 (allow user to select 3D environment) design work in future.

**Comment by philip-lamb** [comment]
@avrignaud I assume this is referring to https://www.doodle3d.com/ ?

**Comment by cvan** [comment]
@philip-lamb Doodles refer to https://trello.com/c/DwwCJLUY/164-uis-46-doodles-island-hopping and https://trello.com/c/hZVnRidO/120-2018-07-19-design-review-deck

**Comment by avrignaud** [comment]
Thanks Chris, missed this originally! Yes, correct. These are also the docs
I was referring to yesterday when we were discussing 6DOF environments and
history there.
-- 
Andre Vrignaud — Head of Mixed Reality Platform Strategy | Emerging
Technologies | Mozilla
avrignaud@mozilla.com | +1 (206) 245-6067 <%2B1.206.245.6067> | Skype:
andrevrignaud
