### ISSUE TITLE
[Desktop Mode] The 360/180 videos that are played in immersive mode by selecting a projection option while in fullscreen mode are wrongly immersed

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3873]
**[Affected Versions]:**
- Firefox Reality v12 RC6 (f10805c).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Desktop mode is enabled for the current window.

**[Steps to reproduce]:**
1. Navigate for example to https://vimeo.com/channels/360vr.
2. Open a video and click the full screen button.
3. Press the trigger button to display the window controls.
3. Click the projection button and select the corespondent projection option.
3. Observe the behavior.

**[Expected results]:**
- The video is correctly played and immersed.

**[Actual results]:**
- The video is played in the back in a small window and the rest of the UI is white.

**[Notes]:**
- This issue is also reproducible for videos that use Youtube links, but they are not directly opened on the Youtube website (ex vuze.com).
- This issue is not reproducible for 360/180 videos on the Youtube website.
- Attachments for the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1LYOern16MZjM3Ybbo6bA46Hn270eyslB/view?usp=sharing).

**Comment by amcgowan93** [comment]
I am having this issue on the Lenovo Mirage VR S3 devices after updating Firefox Reality. Can replicate on 20 headsets all updated.
https://github.com/MozillaReality/FirefoxReality/issues/3778#issuecomment-976149159
