### ISSUE TITLE
[Content Feed] The pop-ups available on the left side of the Awesomebar have the same background color as the navigation bar

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3884]
**[Affected Versions]:**
- Firefox Reality v12 RC6 (f10805c).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to the new content feed page.
2. Click the "Tracking Protection" button from the Awesomebar.
3. Observe the content feed navigation bar and the TP pop-up.

**[Expected results]:**
- They have a different background color.

**[Actual results]:**
- They have the same background color.

**[Notes]:**
- The issue is also reproducible with the "DRM", "WebXR", and "Block Pop-up" pop-ups.
- Attachments for the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/1Y0wwGajWTaXIpgJwOrVGwfY0oGbtJN51/view?usp=sharing).

**Comment by BajiraoXD** [comment]
I would like to solve this issue please assign this to me
