### ISSUE TITLE
Does Firefox Reality support widevine DRM L1 on HTC VIVE Focus? 

### ISSUE THREAD

**Issue by hankuan** [MozillaReality/FirefoxReality#3888]
**Hardware**
HTC VIVE Focus

**Current Behavior**
Playback of Digital Rights Management (Widevine L1) content via the Android Play Movies on Firefox Reality (v11), it only shows Widevine L3 content. (Vysor can capture and view the L3 low resolution content)

**Expected Behavior**
Playback of Digital Rights Management (Widevine L1) content on Firefox Reality v11

thanks
Hankuan

**Comment by hankuan** [comment]
Anyone has information about this? I can't find CDM module on github, does it mean Firefox Reality doesn't support L1?
thanks

**Comment by keianhzo** [comment]
@hankuan Widevine level support doesn't depend on the app but on the system support and the HTC Vive Focus doesn't support Widevine L1.
