### ISSUE TITLE
UR Finding: User would like a way to dim environment background to their own preference in default mode

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#390]
UR Finding: User would like a way to dim environment background to their own preference in default mode. Should probably save setting for future as well.

**Comment by cvan** [comment]
Adding a pitch-black background as the default environment could help here. This comes up *a lot* on the OculusGo sub-Reddit. Samsung Internet allows custom environments and has a curated selection from 360Cities.net.

Back to the original issue: agreed; the contrast issues and possible distractions from browser background environments come up a lot in the user comments I have read.
