### ISSUE TITLE
Firefox reality can not support in VIVE PRO EYE

### ISSUE THREAD

**Issue by leejinxi** [MozillaReality/FirefoxReality#3904]
hello,

we are doing the experiment to play the 360° video through DASH  in Firefox, and now we want play it in VIVE PRO EYE, when we open the software "Firefox reality" in the viveport, it turns into crash, we failed everytime. We are sure that the link between VR device and the computer is sucessful. We also tried some other ways, such as config the firefox nightly and so on, but it still not work either.

would you please solve this problem that make the Firefox reality run on viveport, in device VIVE PRO EYE, or show us another way to play the web video in VIVE PRO EYE ? 

thank you very much.

**Comment by keianhzo** [comment]
Hi @leejinxi What device are you using. Could you share a logcat of the crash? Thanks!
