### ISSUE TITLE
PDF support

### ISSUE THREAD

**Issue by alfiedotwtf** [MozillaReality/FirefoxReality#3931]
I'm used to Firefox on the desktop being able to view PDFs

I would like to read PDFs within Firefox Reality on Oculus Quest 2

Currently, the only way I've been able to read PDFs is by connecting to my PC via a virtual desktop, and reading the PDF through the virtual monitor. Sure, it works... but native PDF support within Firefox Reality would be a huge win for me

**Comment by jstrieb** [comment]
@alfiedotwtf for what it's worth, it is possible to open PDF files in Mozilla Reality using `PDF.js`, which I believe is also used in Desktop Firefox for viewing PDFs. I wrote up a quick tutorial explaining how to do that here (along with some other musings about using Mozilla Reality):
<https://jstrieb.github.io/posts/vr-programming/>

Hopefully this helps!

**Comment by alfiedotwtf** [comment]
Wow, that was super helpful! Thank you so much for that!
