### ISSUE TITLE
Voice search not completing

### ISSUE THREAD

**Issue by plwt** [MozillaReality/FirefoxReality#3935]
## Configuration

Firefox Reality version: 12.2
Firefox Reality build ID: 5f700c82 (AC 51.0.0)

Hardware: Pico Neo 2

## Steps to Reproduce

1. Select the microphone in the address bar
2. Speak a search term
3.

## Current Behavior

Waveform graphic moves, but search term is not found

## Expected Behavior

Waveform graphic moves, the search term is identified and the user is taken to search result.

## Context

Identified from https://support.mozilla.org/en-US/questions/1335517

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by prsmahajan** [comment]
Hi, I would like to work on this issue, can anyone suggest me ways to get started?

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1358274

**Comment by archiewood** [comment]
Also experiencing this issue. Would like to help if i can!
