### ISSUE TITLE
webxr.today showing cloudflare 520: Web server is returning an unknown error

### ISSUE THREAD

**Issue by giannic** [MozillaReality/FirefoxReality#3936]
## Configuration

Firefox Reality version: 12.2
Firefox Reality build ID:  5f700c82 (AC 51.0.0)

Hardware: Oculus Quest 2

## Steps to Reproduce
1. Open firefox reality
2. Observe that the homepage is trying to load webxr.today but shows cloudflare 520 error
520: Web server is returning an unknown error

## Current Behavior
webxr.today homepage shows cloudflare 520 error

## Expected Behavior
webxr.today loads correctly on homepage

## Possible Solution
Not sure

## Context
Any VR environment does not load thru firefoxreality as far as I can tell (but I'm pretty new)

## Error Logs and Stack Traces
I don't have the right tools to retreive logs

```
```

</details>

**Comment by giannic** [comment]
For example: opening https://immersive-web.github.io/webxr-samples/immersive-vr-session.html makes the VR session stuck and unable to back out

**Comment by nigeljw-unity** [comment]
I have the same error on my Oculus Quest and there is nothing I can do to get around it. I have not been able to use any webxr content. It freezes on the first frame and I have to kill the app.

**Comment by nigeljw3** [comment]
I have had the same problem for over a week on my Oculus Quest. This issue is completely breaking webxr. Only the first frame is rendered and then I have to kill the app.

**Comment by zec37** [comment]
We had the same issue on Pico devices as well.

**Comment by PhilipGullberg** [comment]
Still having this issue on Pico Neo 2, any solutions yet?

**Comment by GuillemEspejo** [comment]
I'm having the same problem with my Oculus Quest 2, haven't been able to play any VR content since this bug came out :\

**Comment by nigeljw3** [comment]
@keianhzo not sure who to ping about this, but Firefox reality has lost its primary function for over a month on most platforms.

**Comment by nigeljw-unity** [comment]
@bluemarvin or @MortimerGoro do either of you know who we should ping about this issue?

**Comment by ZemGit** [comment]
Or...@keianhzo ?

**Comment by jaredhirsch** [comment]
Hey all! 👋 Sorry for the lack of movement here. I'm looking into this.

**Comment by jaredhirsch** [comment]
Hey again, we're making progress on debugging this. Hope to have the cloudflare config fixed soon. Thanks and sorry 🙏

**Comment by jaredhirsch** [comment]
OK, this is now fixed. DNS should propagate out in 24-48 hours. (I'll have to find someone with the right permissions to close this bug.) Thanks all!
