### ISSUE TITLE
Downloaded apk file can't be opened by package installer

### ISSUE THREAD

**Issue by zec37** [MozillaReality/FirefoxReality#3937]
## Configuration

Firefox Reality version: 12.2
Firefox Reality build ID: 5f700c8

Hardware: Oculus Quest 1, Pico Neo 2, Pico Neo 3.

## Steps to Reproduce

1. Download .apk file from website. 
2. Navigate to "Open Library" - "Download" and find the downloaded apk file.
3. Click the apk file.
4. From the prompt select "Open"
5. Observe the behavior.

## Current Behavior

Oculus Quest: the screen went black and no response. User has to force reboot the device.
Pico Neo 2 / Pico Neo 3: The screen flash and back to Firefox Reality, package installer doesn't response.

## Error Logs and Stack Traces

<details open>

Log [link](https://drive.google.com/file/d/12reQGN2V7ZzeawL42bhqhhJUc5nyPsE2/view?usp=sharing)

```
```

</details>

**Comment by keianhzo** [comment]
Fixed by https://github.com/MozillaReality/FirefoxReality/pull/3938
