### ISSUE TITLE
UR Finding: User would like to drag 2D object from a webpage into 3D space around browser window, and have a resulting 3D model of that content to interact with.

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#394]
UR Finding: User would like to drag 2D object from a webpage into 3D space around browser window, and have a resulting 3D model of that content to interact with.

User wants to drag a 2D object from a webpage into 3D space around browser window. User wants to play in 3D in VR.
→ A way to drag a 2D image from a webpage and converting it 3D to place and examine it in the environment. 3D object can then be viewed, resized and rotated in space. 
→ A way to zoom in and out of object using trackpad
→ explore doing a demo of this using 2D Firefox Reality logo and 3D Firefox Reality animation/model

Implies metadata informing browser when 3D model/content parallel to the 2D content is available.

**Comment by larsbergstrom** [comment]
Not happening for 1.1.
