### ISSUE TITLE
WebVR experience displays controller ray which shouldn't appear

### ISSUE THREAD

**Issue by zec37** [MozillaReality/FirefoxReality#3942]
## Configuration

Firefox Reality version: 12.2
Firefox Reality build ID: 5f700c8

Hardware: Pico G2

## Steps to Reproduce

1. Keep headset connect to controller
2. Open up WebVR experience [https://webxr-matching.netlify.app/tripping_merged.html?roomId=bkcTgov6S08pnQxqAroI&isHost=true&staticVideoLink=https://dtunco401b35r.cloudfront.net/bkcTgov6S08pnQxqAroI_test_4K_from_8K.mp4](https://webxr-matching.netlify.app/tripping_merged.html?roomId=bkcTgov6S08pnQxqAroI&isHost=true&staticVideoLink=https://dtunco401b35r.cloudfront.net/bkcTgov6S08pnQxqAroI_test_4K_from_8K.mp4)
3. Observe the controller appearing on the right side of the view. Sample image: [https://drive.google.com/file/d/1TrKCYJslPTtupGLUZGIxO_xugeccHPx-/view?usp=sharing](https://drive.google.com/file/d/1TrKCYJslPTtupGLUZGIxO_xugeccHPx-/view?usp=sharing)

## Expected Behavior

Only display one controller model as Pico G2 is 3Dof device with one controller.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by keianhzo** [comment]
After taking a deeper look into this, it seems to be related to the way the app handles the input. I've checked and FxR is detecting the input profile correctly, you can test it here: https://immersive-web.github.io/webxr-samples/input-profiles.html, so it might be related to how the app is initializing the input device in A-Frame.

In case it helps you can take a look at how we are doing it in Hub where the G2 controller is correctly detected:

https://github.com/mozilla/hubs/blob/066f4c221c35dd006369be0f84ed9454946a12dd/src/systems/userinput/userinput.js#L361-L387
