### ISSUE TITLE
WebXR incorrect IPD/FOV on Quest 2

### ISSUE THREAD

**Issue by enovikov11** [MozillaReality/FirefoxReality#3948]
## Configuration

Firefox Reality version: 12.2 (2020-12-15)
Firefox Reality build ID: 5f700c82 (AC 51.0.0)
this is freshest version available in oculus store

Hardware: Oculus Quest 2 firmware 30.1.0.61.350.300158191

## Steps to Reproduce

1. move lens from centered position to wide ([change IPD](https://support.oculus.com/articles/getting-started/getting-started-with-quest-2/ipd-quest-2/))
2. open https://immersive-web.github.io/webxr-samples/inline-session.html or any other webxr site
2. click enter VR
3. rotate your head

it reproduces in both sitting and standing positions

## Current Behavior
image is distorted: 3d in static position is ok, center point is ok, but while rotating head there is effect like image is moving faster than you. If change to middle IPD, all ok. Opening in built-in oculus browser is ok with any IPD

## Expected Behavior
image will be not distorted

## Possible Solution
fix rendering engine to correctly set eyes positions. Maybe there is outdated oculus's ovr_mobile VrApi. Maybe there is bad [modeParams](https://github.com/MozillaReality/FirefoxReality/blob/0432da7fbaa5a0cbc6a157f49bf94f49871f3e16/app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp#L1368) of m.ovr while entering VR, maybe there is bug with [other transforms](https://github.com/MozillaReality/FirefoxReality/blob/0432da7fbaa5a0cbc6a157f49bf94f49871f3e16/app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp#L1013)

## Context
I cant use WebXR in Mozilla Reality, solution now is to use oculus browser. I also made some [research](https://github.com/immersive-web/webxr-samples/compare/main...enovikov11:main) by debugging IPD and this value is changing, but comparing with [WebXR API Emulator](https://addons.mozilla.org/en/firefox/addon/webxr-api-emulator/) extension there is not only dx component, but also dy and dz.

## Error Logs and Stack Traces
no logs

<details open>

```
```

</details>

**Comment by yinchy** [comment]
Would like to add that moving lens from center IPD position ("2") to narrow position ("1") on the Quest 2 does also produce a distortion. But the effect is a widened image (so objects look flattened)
The effect when going to wide position ("3") is a narrowed image (so objects look too skinny)
