### ISSUE TITLE
UR Finding: Users would like to be able to collect content on phone during day, and then "cast" to headset in evening

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#397]
UR Finding: Users would like to be able to collect content on phone during day, and then "cast" to headset in evening. Apparently this is a significant use case in China at the moment.

Related to #373 - headset could just be another display target, but this bug implies an easy way to collect and share a set of content to different screen for viewing (versus real-time display)

**Comment by philip-lamb** [comment]
Candidate for implementation of Pocket support via Android Components. See https://github.com/mozilla-mobile/android-components/tree/master/components/service/pocket
