### ISSUE TITLE
Major WebGL texture upload performance regression - links to likely duplicate Firefox Core issues

### ISSUE THREAD

**Issue by dustinkerstein** [MozillaReality/FirefoxReality#3973]
Looks like there's been a major WebGL texture upload performance regression in the past 6 months or so, but it doesn't seem like there's been much investigation. Here is a pure WebGL replication with a 4k 60fps video - https://jsfiddle.net/Lmy0b3xt

This plays back in latest Chrome at 60fps, and ~5fps in Firefox 93

Here are what are likely just duplicates:

https://github.com/MozillaReality/FirefoxReality/issues/3930
https://github.com/MozillaReality/FirefoxReality/issues/3952
https://bugzilla.mozilla.org/show_bug.cgi?id=1709726
https://bugzilla.mozilla.org/show_bug.cgi?id=1719154
https://bugzilla.mozilla.org/show_bug.cgi?id=1736923
https://bugzilla.mozilla.org/show_bug.cgi?id=1708006
https://bugzilla.mozilla.org/show_bug.cgi?id=1708491

**Comment by eproasim** [comment]
Commenting to add that the last build of Firefox that did not have this performance issue with RGB textures was Version 85.0.2 (64-bit)
