### ISSUE TITLE
(Quest 2) - Downloading a new environment (Space)  continually loops never ending repeating downloading space.zip

### ISSUE THREAD

**Issue by jolyonralph** [MozillaReality/FirefoxReality#3990]
## Configuration

Firefox Reality version:   12.2 
Firefox Reality build ID:  AC 51.0.0

Hardware:  Oculus Quest 2

## Steps to Reproduce

1. Change environment to space
2. Check in downloads
3. Space.zip continually downloads in a never-ending loop.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by m-gizzi** [comment]
Same happens for me. It'll queue space.zip to download, get as far as 1% complete and then a split second later it'll delete itself from the download queue, and repeat this endlessly. I had to uninstall and reinstall Firefox to get it to stop.

**Comment by hardly07** [comment]
I'm having the same issue.

**Comment by issacclee** [comment]
same here, we are using PicoNeo3

**Comment by aslebedev** [comment]
Oculus Quest 2 the same problem

**Comment by issacclee** [comment]
Seems like Firefox Reality has been abandoned with no active maintainers.

**Comment by CreativeTransmissions** [comment]
Im also experiencing this on the Quest 2

**Comment by CmdCrypto** [comment]
FF Reality will not be developed any further obviously. 

https://blog.mozilla.org/mozilla/update-on-firefox-reality/
