### ISSUE TITLE
Please provide nightly builds

### ISSUE THREAD

**Issue by woodholly** [MozillaReality/FirefoxReality#3992]
**Is your feature request related to a problem? Please describe.**
Last release 12.2 was almost 2 years ago... I think it is better to take into account fixed browser vulnerabilities (if any).

**Describe the solution you'd like**
Please provide active nightly builds for testing.

**Describe alternatives you've considered**
I have successfully built 13.0 from source, but this was painful ..

**Comment by issacclee** [comment]
would be great if FirefoxReality team can provide nightly builds, but it seems like they aren't being too active recently.

**Comment by hb0nd** [comment]
firefox reality is no longer being worked on: https://blog.mozilla.org/en/mozilla/news/update-on-firefox-reality/

try this fork, which is continuing development: https://github.com/Igalia/wolvic
