### ISSUE TITLE
Hand Tracking In The Works?

### ISSUE THREAD

**Issue by Vacant-Eyes** [MozillaReality/FirefoxReality#3998]
Haven't seen any recent requests for hand tracking, so here's this one.

Quest controllers being 99% plastic and unable to handle rapid cube-killing movement without gradually breaking down is what brings me to this inquiry.

First feature request, hope it's in the right place.

**Comment by cadeyrn** [comment]
> First feature request, hope it's in the right place.

Firefox Reality is no longer being developed. The inofficial successor is Wolvic (https://github.com/Igalia/wolvic). You should file feature requests there.
