### ISSUE TITLE
Hololens 2 version/release

### ISSUE THREAD

**Issue by predictcare** [MozillaReality/FirefoxReality#4000]
Hi, this is not properly a feature or maybe it is :

We'd like to have the Hololens 2 build of Firefox Reality, is there a way to compile on our own ? The store doesn't allow to download anymore and needs some "redeem code".

We understood that in some way or another, the project is discontinued, but we just want to install the latest "stable" versione (also a nightly will be fine ;-) )

Thanks in advance.

Victor

**Comment by zak919150** [comment]
@predictcare 
I also would like to try to install the latest version of firefox on hololens 2, edge has some problems with WebXR especially in immersive-AR mode

**Comment by svillar** [comment]
FxR is discontinued. Check [Wolvic](https://github.com/Igalia/wolvic) for the continuation of the project
