### ISSUE TITLE
FxR controller and display names should match the native browser's names.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#401]
## Hardware

All

## Current Behavior

We use the same names on all platforms and do not match any existing platforms.

## Possible Solution

We should examine what names are used in each native browser and emulate them. A lot of code is already sniffing for specific platform names and it would be easier to just emulate than try and get existing websites to update their code to look for FxR specific strings.

## Context

The FxR controller doesn't work on sketchfab.com because they are looking for specific controller names in their code.

**Comment by cvan** [comment]
Good catch. Removing `Gamepad#id` (the "display name") has come up quite a bit in spec discussions:

- https://github.com/w3c/gamepad/issues/73
- https://github.com/w3c/gamepad/issues/65
- https://github.com/w3c/gamepad/issues/9
- https://github.com/w3c/gamepad/issues/12

I understand that the main reason for the `Gamepad#id` sniffing is to ensure the `buttons` and `axes` are mapped correctly (or re-mapped for particular browser/OS/gamepad configurations, which I myself had to do quite a bit in making HTML5 games).

If there's not already enough information with the current properties, a dictionary of capabilities (per w3c/gamepad#12) could be added so developers don't need to sniff for the name.

**Comment by MortimerGoro** [comment]
`We use the same names on all platforms and do not match any existing platforms.`

Actually we have already set different names for each display, so it should report different names on each. But yep, it's good to check we are using names that apps are checking correctly.

For the controllers we set the ones used in AFrame (e.g "Gear VR Remote Controller")

**Comment by avrignaud** [comment]
@larsbergstrom and I will figure out webcompat loop.

**Comment by cvan** [comment]
Whichever we choose, we should make sure they are supported by those defined in this popular library used with three.js: https://github.com/stewdio/THREE.VRController/blob/master/VRController.js. (And obviously make PRs when appropriate.) Oculus Go Controller has been recently added, FYI.

**Comment by philip-lamb** [comment]
See also #812

**Comment by cvan** [comment]
I've commented on https://github.com/w3c/gamepad/issues/73#issuecomment-469517729. Will update as I do some research on the actual sites possibly impacted by `Gamepad#id` sniffing.

**Comment by cvan** [comment]
Is there more to be done here? Oculus Go + VIVE Focus `Gamepad#id` strings were changed in issue #812 / PR #981.

**Comment by philip-lamb** [comment]
Closing as resolved.
