### ISSUE TITLE
Implement Voice Search in FxR for 1.0

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#405]
## Hardware

All

## Steps to Reproduce

1. NA

## Current Behavior

Selecting microphone button in URL bar does nothing.

## Expected Behavior

Selecting microphone should allow user to do a voice search that results in a Google search results page. (Note: V1.0 of browser search defaults to Google only, we will implement search engine personalization in 1.1+)

User Flow attached, please ping @thenadj for questions.
[UF-17 Voice Command_002.pdf](https://github.com/MozillaReality/FirefoxReality/files/2315231/UF-17.Voice.Command_002.pdf)

```
```

</details>

**Comment by thenadj** [comment]
@keianhzo We decided in our meeting last Friday that this animation will be created in code, not as animated art assets. Attached is an incomplete UIS for voice to get you started. We will add more to this tomorrow and re-upload once it's done. 
[UIS-29 Voice Command_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2326145/UIS-29.Voice.Command_001.pdf)

**Comment by MortimerGoro** [comment]
@thenadj The animation looks very nice but we don't have a lot of time for V1.0 and a lot of open tasks. Probably we'll need  a simpler animation and implement the cool one in 1.1

Is it possible to create a simpler one (e.g. the volume fills a set of horizontal/vertical rects or the volume fills the microhpne icon? Example of the one used in mac
<img width="417" alt="captura de pantalla 2018-08-28 a las 20 31 47" src="https://user-images.githubusercontent.com/1070794/44743000-8e913c80-ab01-11e8-882d-d637652a483a.png">

**Comment by MortimerGoro** [comment]
@keianhzo I'm assuming that the animation needs to be tied to the volume

**Comment by thenadj** [comment]
@MortimerGoro Sure, we can do that. Can we just create a visual for this and you will implement it? Is there anything specific we need to know before we create this? Just a series of shapes in a vertical alignment with different colors? Can we use different sized shapes, i.e. see attached...
![voice-animation-static](https://user-images.githubusercontent.com/13240857/44744177-58c86580-aab9-11e8-885d-50c7b5f9962d.jpg)

**Comment by MortimerGoro** [comment]
@thenadj yes, that kind of animation seems easier to implement. We can have shapes of different size as in the image. What's the idea for the animation? fill the shapes based on the volume? 

@andrenatal How should we get the microphone input volume to implement this animation? Does your SDK have some callback or we need to query it from Android API somehow?

**Comment by thenadj** [comment]
@MortimerGoro Could we change the size of the shapes AND the colors based on volume or should we keep the shapes the same size and only change colors?

**Comment by MortimerGoro** [comment]
@thenadj I think it will be easier just to change the colors and keep the shapes the same size

**Comment by thenadj** [comment]
Ok, we're on it.

**Comment by andrenatal** [comment]
@MortimerGoro yes, the SDK has everything we need including the decibels from every frame. We can capture it here: https://github.com/MozillaReality/FirefoxReality/pull/437/commits/dfdbbc0b7f2cd0dc0115bbbd11163e4e4b6df5ab#diff-81b8c286a4e871dad3171dd3fe2a30a4R290

**Comment by thenadj** [comment]
@MortimerGoro Attached is the updated UIS for voice with the new simplified animation pattern. There are two animations, one for listening with two states and one for searching. 

The listening animation has two art assets, one with all dots and one which is just one dot that will have to be manually placed multiple times based on the layout of the spec. 

The searching animation should just be rotated counter-clockwise and preferably use the colored art asset. There is a version with an SVG that uses just one color for the second animation if the first one cannot be achieved. 

[UIS-29 Voice Command_002.pdf](https://github.com/MozillaReality/FirefoxReality/files/2330243/UIS-29.Voice.Command_002.pdf)

[UIS-29_Voice_Command_Assets.zip](https://github.com/MozillaReality/FirefoxReality/files/2330254/UIS-29_Voice_Command_Assets.zip)

**Comment by thenadj** [comment]
I think I mistakenly @ replied to the wrong Imanol. I meant @keianhzo

**Comment by andrenatal** [comment]
So the PR containing the framework integration is here: https://github.com/MozillaReality/FirefoxReality/pull/437

And a (very) rough explanation of its usage is here: https://github.com/mozilla/androidspeech

That encapsulates the whole backend, so we only need to worry regarding the frontend now.

**Comment by andrenatal** [comment]
So the PR containing the framework integration is here: #437

And an explanation of its usage is here: https://github.com/mozilla/androidspeech

That encapsulates the whole backend, so we only need to worry regarding the frontend now.

**Comment by keianhzo** [comment]
@thenadj I'll fix the X button color. The issue with the searching animation is that it has alpha in the gradients so it blends with the dark dialog color. If you can send me another SVG without alpha in the gradient I think that'll make it look better.

**Comment by jennihoang** [comment]
@keianhzo Please see new Hex colors on UIS-29! I've also updated the orbital to reflect more saturated colors.
<img width="346" alt="screen shot 2018-09-05 at 12 02 23 pm" src="https://user-images.githubusercontent.com/28326869/45115279-390dee80-b104-11e8-9255-f438d757d537.png">

[UIS-29 Voice Command_003.pdf](https://github.com/MozillaReality/FirefoxReality/files/2354218/UIS-29.Voice.Command_003.pdf)
[icon-voicecommand-searching-color.svg.zip](https://github.com/MozillaReality/FirefoxReality/files/2354221/icon-voicecommand-searching-color.svg.zip)
