### ISSUE TITLE
Update tools/taskcluster/sign_apk.py to user correct signing version based on apk type

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#406]
## Hardware

All

## Current Behavior

All APKs are signed with V1.
## Expected Behavior

 We should be using V2 for most APKs.
## Possible Solution

Update tools/taskcluster/sign_apk.py to detect which APKs need V1 and downgrade for those.
## Context

The Oculus App Store doesn't support V2 signing so all uploaded APKs need to use V1 signing.

**Comment by larsbergstrom** [comment]
Closed with changes related to https://github.com/MozillaReality/FirefoxReality/pull/468
