### ISSUE TITLE
Officially sign Firefox Reality builds with a Mozilla Android key

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#408]
## Hardware
All

## Current Behavior
Release APKs are signed with a test key.

## Expected Behavior
Sign with an official Mozilla Android key. This is required to ship in stores.

## Possible Solution
1. Request an Autograph services edge key
2. Add signing steps to the taskcluster builds referencing that secret edge key

**Comment by larsbergstrom** [comment]
Bugzilla request here: https://bugzilla.mozilla.org/show_bug.cgi?id=1485748

**Comment by larsbergstrom** [comment]
Steps were copied from: https://wiki.mozilla.org/Release_Management/Adding_a_new_app_on_Google_play#Automation

**Comment by larsbergstrom** [comment]
Simple signing steps we could put into tools/taskcluster/sign (assuming there isn't something better built in already):
https://github.com/mozilla/notes/blob/ce9c0f2fa0f012d2fcdea204e4ea61f171db97f2/circle.yml#L81-L86

**Comment by larsbergstrom** [comment]
Blocked waiting on key to use: https://bugzilla.mozilla.org/show_bug.cgi?id=1485748

**Comment by bluemarvin** [comment]
Builds are now using either staging key or release key now as of commit https://github.com/MozillaReality/FirefoxReality/commit/3f8a2ed62b41294528b11c0148810c85ed5b1807
