### ISSUE TITLE
Update Home URI when region (`country_code`) changes from Geolocation API calls (for search engine)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#409]
## Hardware
Any

## Steps to Reproduce

1. Launch FxR with PR #402
2. Notice the new New-Tab/Home page correctly loads, but because the Geolocation API call hasn't yet finished for the search-engine code (added in issue #248), we don't include `/?region=<region>` in the Home URI
initially empty (i.e., https://webxr.today)

## Current Behavior
- Upon first load, there is no region in the Home URI: https://webxr.today
- If you click the Home button, you'll be taken to the appropriate Home URI with a region: https://webxr.today/?region=us

## Expected Behavior
- Upon first load, the Home URI contains the user's region: https://webxr.today https://webxr.today/?region=us

## Possible Solution
Whenever the region changes (in the search code), we should use some mechanism, such as `postMessage` to communicate the new region to the Home URI (https://webxr.today), so the page can dynamically update the region from within the content page.

**Comment by keianhzo** [comment]
@cvan If you expose a region update method in the page we can easily inject the new region using:

`session.loadUri("javascript:setRegion('" + mRegion + "');");`

Let me know when the method is available and I can make the fix.

**Comment by keianhzo** [comment]
@cvan It seems that javascript injection is not available so we will need to do this as a page reload passing the new region as parameter.

**Comment by cvan** [comment]
> @cvan It seems that javascript injection is not available so we will need to do this as a page reload passing the new region as parameter.

if you can append `#{"region": "<mRegion>"}`, that'd work too.

(see this similar approach I was considering for bookmarks: https://github.com/MozillaReality/FirefoxReality/issues/442#issuecomment-417102825)
