### ISSUE TITLE
Difficult to click on buttons

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#412]
## Hardware
Oculus Go

## Steps to Reproduce
1. Browse to https://hub.link
2. Attempt to click on numbers

## Current Behavior
Very difficult to click numbers unless holding the controller still

## Expected Behavior
More forgiving of clicking on buttons

**Comment by larsbergstrom** [comment]
@bluemarvin Gave me an awesome build Friday with a proposed fix that is 👍 perfect and huge improvement in usability!

**Comment by bluemarvin** [comment]
I put up a PR with the fix: https://github.com/MozillaReality/FirefoxReality/pull/416

**Comment by bluemarvin** [comment]
PR #416 has landed so closing this out.
