### ISSUE TITLE
predictive letter/word/text results offered when entering text

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#413]
UR Finding: Users would like predictive letter/word/text results offered when entering text. "Swype"-like support also specifically mentioned.

**Comment by jvonitter** [comment]
UI for autocomplete spec here: https://drive.google.com/open?id=1GVx58e7sYBLlK1WegWzpha-MX1xSJqt6

**Comment by bluemarvin** [comment]
Without OS level support this is a very difficult feature. We would need to bundle a database for each language we want to support. This won't make v10 and probably won't make v11.

**Comment by keianhzo** [comment]
This task can be a bit expensive as we need to add support for wordlists/dictionaries. A good starting point might be the AOSP Dictionary implementation https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+/refs/heads/master/java/src/com/android/inputmethod/dictionarypack/ and available wordlists https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+/refs/heads/master/dictionaries/
