### ISSUE TITLE
UR Finding: Users would like auto-suggestions for content when searching content - similar to Netflix viewing suggestions

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#414]
UR Finding: Users would like auto-suggestions for content when searching content - similar to Netflix viewing suggestions.

Perhaps when searching content feed in future (when we have sufficient volume)?

**Comment by thenadj** [comment]
@cvan UIS-21 has lots of URL bar interactions. This spec is ready for implementation.

**Comment by thenadj** [comment]
@avrignaud Do you want us to add this to the v1.1 priority list and get started on the design?
See UIS-21 for early thinking. Needs to be redesigned if we want it ready for implementations for v1.1.

**Comment by avrignaud** [comment]
@thenadj To differentiate, we should add the "Firefox Awesome Bar" autocomplete/suggestions to the UI spec for bookmarks/history (the discussion this AM). I think this bug is about having suggestions made when users are searching the FxR content feed. Also valuable, but I don't think that's a 1.1 feature.

**Comment by philip-lamb** [comment]
Possible use-case for Pocket's suggestion engine?
