### ISSUE TITLE
Transition to skyboxes for environments

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#417]
After discussions with @thenadj, @avrignaud, @bluemarvin, @MortimerGoro, and @keianhzo, we have  decided to transition from the use of modeled environments back to a skybox. This will allow us to address some rendering issues (e.g., #171 providing additional control over the environment) and reduce the engineering work to continue to tweak and optimize the model loader and renderer through the end of this calendar year (2018).

It will also afford us with some great places to experiment with end-user customization, speed up the workflow for designers to iterate with new designs (just push a skybox over via adb!), and for web content to make customizations available (see https://github.com/immersive-web/proposals/issues/23).

**Comment by MortimerGoro** [comment]
Blocked until we get the skybox assets from designers

**Comment by bluemarvin** [comment]
Or just switch back to space box until we get assets. 😬

**Comment by nancyhang** [comment]
@thenadj

**Comment by keianhzo** [comment]
Got the skyboxes, will do this together with #464
