### ISSUE TITLE
Daydream controller is not detected by Soundboxing

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#421]
## Hardware

Daydream

## Steps to Reproduce

1. Go to sound boxing page and start a game
2. Enter immersive mode

## Current Behavior

No controller is visible.

## Expected Behavior

Controller should be visible and game should be playable.

## Possible Solution

Investigate what gamepad#id we are using for the Daydream.

**Comment by avrignaud** [comment]
@fernandojsg will reconcile.

**Comment by fernandojsg** [comment]
Closed by https://github.com/MozillaReality/FirefoxReality/pull/441
