### ISSUE TITLE
Toggle switch in settings panel need text label denoting state

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#423]
## Hardware

All

## Steps to Reproduce

1. Open setting panel
2. Look at a toggle switch.

## Current Behavior

The toggle switch only uses red and green colors to denote state. People who are color blind may not be able to easily determine the state of the button.

## Expected Behavior

Toggle switches should use something in addition to color do denote state.

## Possible Solution

Put a text label to the left of the switch denoting state (on/off).

**Comment by nancyhang** [comment]
@thenadj

**Comment by thenadj** [comment]
Let's show ON/OFF label below toggle control on hover. See bottom sections of attached UIS-16 for Settings dialog and UIS-39 for Dev Options panel. If there is no time to implement hover, add persistent label below each button for v1 but fix for v1.1. 

[UIS-16 Settings_012.pdf](https://github.com/MozillaReality/FirefoxReality/files/2329428/UIS-16.Settings_012.pdf)
[UIS-39 Developer Options Panel_003.pdf](https://github.com/MozillaReality/FirefoxReality/files/2329429/UIS-39.Developer.Options.Panel_003.pdf)
