### ISSUE TITLE
Add 3D spinner for Link Traversal

### ISSUE THREAD

**Issue by nancyhang** [MozillaReality/FirefoxReality#431]
How should we animate the model? rotation in what angles?

The 3D model is heavy: 50K faces and three 2048K textures. Please attach a lower poly.  

@keianhzo if you can help with the blender export

**Comment by thenadj** [comment]
[3D_Spinner.zip](https://github.com/MozillaReality/FirefoxReality/files/2326104/3D_Spinner.zip)
Attached is the heavy version. I'll start an email string with David to get a lower poly version in but he is on vacation this week and won't be able to get to it until next week.

**Comment by thenadj** [comment]
@MortimerGoro
For animation I'd start with vertical axis animation at medium speed. We might add a twist into the animation to make it look more interesting, any way you could add a couple of animations and share so we can pick?

**Comment by MortimerGoro** [comment]
@thenadj I did some tests and the best animation seems rotate around the vertical axis. We'll send you a build today so you can test it.
