### ISSUE TITLE
Research stale frames on WebVR

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#433]
Some demos such as  360 panorama have about ~20 stale frames per second. Staled frames should be 0 in such a simple demo.

A potential cause: I saw that intermittently some WebGL RAF frames took more time than needed. We need to know why that happens.

**Comment by MortimerGoro** [comment]
@daoshengmu is researching this issue

**Comment by daoshengmu** [comment]
I don't see there is any delay in the IPC channel. The avg. time only takes 0.7 ms. Beside,  it utilizes SharedTextureEGL to forward textures from WebGL to the VR module. I am wondering if we use incorrect APIs from the Oculus part.

```
08-29 17:35:03.820 27235 27258 I vrsubmit: SendSubmitFrame, type 7, frame id 3576, timestamp 11431896.116117
08-29 17:35:03.821 27235 27392 I vrsubmit: RecvSubmitFrame, frame id 3576, timestamp 11431896.401273
08-29 17:35:03.821 27235 27391 I vrsubmit: VRDisplayExternal::SubmitFrame frame id 3576
08-29 17:35:03.841 27235 27258 I vrsubmit: SubmitFrame type: 9
08-29 17:35:03.841 27235 27258 I vrsubmit: SendSubmitFrame, type 7, frame id 3577, timestamp 11431916.667733
08-29 17:35:03.842 27235 27392 I vrsubmit: RecvSubmitFrame, frame id 3577, timestamp 11431917.484296
08-29 17:35:03.842 27235 27391 I vrsubmit: VRDisplayExternal::SubmitFrame frame id 3577
08-29 17:35:03.861 27235 27258 I vrsubmit: SubmitFrame type: 9
08-29 17:35:03.861 27235 27258 I vrsubmit: SendSubmitFrame, type 7, frame id 3578, timestamp 11431936.914715
08-29 17:35:03.862 27235 27392 I vrsubmit: RecvSubmitFrame, frame id 3578, timestamp 11431937.339090
08-29 17:35:03.862 27235 27391 I vrsubmit: VRDisplayExternal::SubmitFrame frame id 3578
08-29 17:35:03.877 27235 27258 I vrsubmit: SubmitFrame type: 9
08-29 17:35:03.877 27235 27258 I vrsubmit: SendSubmitFrame, type 7, frame id 3579, timestamp 11431952.738935
08-29 17:35:03.879 27235 27392 I vrsubmit: RecvSubmitFrame, frame id 3579, timestamp 11431953.583102
08-29 17:35:03.880 27235 27391 I vrsubmit: VRDisplayExternal::SubmitFrame frame id 3579
08-29 17:35:03.900 27235 27258 I vrsubmit: SubmitFrame type: 9
08-29 17:35:03.900 27235 27258 I vrsubmit: SendSubmitFrame, type 7, frame id 3580, timestamp 11431976.300291
08-29 17:35:03.901 27235 27392 I vrsubmit: RecvSubmitFrame, frame id 3580, timestamp 11431976.513729
````

**Comment by MortimerGoro** [comment]
`I am wondering if we use incorrect APIs from the Oculus part.`
I don't think so because we have 0 stale frames in the 2D browsing mode and we are using the same calls for WebVR

**Comment by MortimerGoro** [comment]
Could you do more detailed benchmark of the WebLG RAF calls? Measure a list of frames with the total run time (ideally also cost per substep/WebGL call)

**Comment by daoshengmu** [comment]
I am investigating a simple panorama demo, https://my.panomoments.com/u/dustinkerstein/m/kids-jumping-into-the-water.

I aware `VRManagerChild::RunFrameRequestCallbacks` is very often to take more than 30 ms per frame. In the non-immersive mode, it would be more often to take much time but there is no stale frames. After entering the immersive mode. we always have stale frames when it takes more than 20 ms, and rAF callback, `callback.mCallback->Call(timeStamp);`, it usually takes more than 8 ms per call.

My next step would think about measure all related functions' elapsed time by devTool or writing a simple measure tool by my own.

**Comment by daoshengmu** [comment]
I aware we mostly have stale frames when running 360 video demos, the asset from https://my.panomoments.com/u/dustinkerstein/m/kids-jumping-into-the-water, is a mp4 file,
https://data.panomoments.com/processed/5849a51bc26d08000b62f9f8/594034259456f0000ba62f29/hd_dashinit.mp4.

We also can check another aframe video example, https://aframe.io/examples/showcase/videosphere/.

I notice if we enable ATW, sale frames would be decrease a lot. When we are watching video without moving the headset, the stale frames would be decrease from 25 to 8. ATW can't help us when moving the headset, because it seems to be forced to sync frames. We still need to take more time to realize how to improve video playback performance.

**Comment by larsbergstrom** [comment]
@daoshengmu @MortimerGoro Are we going to continue to look at this for 1.1, or shoudl we move it to the backlog?

**Comment by philip-lamb** [comment]
Per discussion with @daoshengmu we'll drop this approach and focus on other specific performance-related cases elsewhere.
