### ISSUE TITLE
Hand controller doesn't work in Three.js VR demos

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#434]
## Steps to Reproduce
Try Three.js VR examples

## Current Behavior
The hand controller doesn't work (it works on Oculus Browser)

## Expected Behavior
Hand controller should work

**Comment by takahirox** [comment]
https://threejs.org/examples/#webvr_dragging
https://threejs.org/examples/#webvr_ballshooter

**Comment by avrignaud** [comment]
@fernandojsg can comment how we'll approach in general, but in short term we should focus on reaching out to Soundboxing and doing a webcompat pass. Will work with @larsbergstrom to build a loop for reporting webcompat.

**Comment by fernandojsg** [comment]
Currently we're returning `Gear VR Remote controller` as the gamepad ID, and three.js is checking for `Gear VR Controller` and A-Frame for `Gear VR`.
Oculus browser is returning `Oculus Go Controller` which seems more convenient.

**Comment by MortimerGoro** [comment]
@fernandojsg so using "Oculus Go Controller" is the recommended solution? will it work in both aframe and three.js?

**Comment by fernandojsg** [comment]
@MortimerGoro yep It will work both on A-Frame and three.js until we will fix a-frame to start using `Oculus Go Controller` (three.js already check for that too).
