### ISSUE TITLE
Implement UI for browser-level `alert`/`prompt`/`confirm`

### ISSUE THREAD

**Issue by nancyhang** [MozillaReality/FirefoxReality#435]
Hardware: All
Steps to Reproduce:

    Go to: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select
    Scroll to Examples.
    Click on selection drop down list.

Actual Behavior:
Nothing happens.

Expected Behavior:
A selection list is presented and the user may select an item in the list.

Recommendation:
FxR need to implement UI for the various selection types a web page may present.

**Comment by nancyhang** [comment]
Linked to #234

**Comment by cvan** [comment]
Sounds good – thank you! Let's leave issue #234 for implementing the UI for `<select>`. I've changed the title for `alert`/`prompt`/confirm`. This week I'll file follow-up issues for the various other fields that need design and engineering work (e.g., some of the `<input>` fields do not focus at all, which is crucial to fix).

**Comment by cvan** [comment]
Anyone feel free to disagree, but I vote for this to be a P0 for v1.1. alert/confirm/prompt and Basic-Auth Portal prompts are quite common on web pages. And not supporting them could prevent web pages from being accessed (i.e., password-protected pages), getting user input to properly function (e.g., confirm/prompt), or errors thrown as alerts get swallowed (e.g., all Unity WebGL- or WebVR-exported applications).

**Comment by keianhzo** [comment]
Those three should be pretty simple to implement +1 for v1.0.

**Comment by nancyhang** [comment]
This will remain as v1.1 until we get the other high priority P0 completed.

**Comment by cvan** [comment]
test cases: **https://webxr.sh/dialogues** (https://webxr.sh/d)

**Comment by cvan** [comment]
we can use the same UI provided in https://github.com/MozillaReality/FirefoxReality/issues/234#issuecomment-419275266
