### ISSUE TITLE
gamepad.pose is returning incorrect values for hasPosition and hasOrientation on 3dof

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/FirefoxReality#438]
## Hardware
Mirage Solo

## Steps to Reproduce
1. When presenting, query the available gamepads (`navigator.getGamepads`) and check the `pose`.

## Current Behavior
On the daydream 3dof controller, it's returning:
```
hasPosition: true,
hasOrientation: false
```
![image](https://user-images.githubusercontent.com/782511/44759342-ec417b00-ab39-11e8-9297-d216db1e6e38.png)

## Expected Behavior
The opposite:
```
hasPosition: false,
hasOrientation: true
```
<details open>

```
```

</details>

**Comment by MortimerGoro** [comment]
Pushed this Gecko PR to fix this https://phabricator.services.mozilla.com/D4534

**Comment by fernandojsg** [comment]
Closed by https://phabricator.services.mozilla.com/D4534
