### ISSUE TITLE
Expose bookmarks on the Content Feed

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/FirefoxReality#442]
As exposed on https://github.com/MozillaReality/FirefoxReality/issues/347#issuecomment-417038748

TL;DR The idea is to be able to bookmark content from the FxR UI and show it on a specific category for that on the Content Feed.
Even so it could be an MVP before we have some proper UI/UX for the bookmarks on the FxR chrome, they both could coexist as they do right now on the new tab on Firefox Desktop.
The content feed should be able to remove bookmarks, although a two-ways API is encouraged for MVP we could just add them to a filter list on the localstorage for the page and just filter them from the list provided by the browser.

**Comment by bluemarvin** [comment]
I'm asking about JavaScript injection and if/when it will be added to GeckoView.

**Comment by cvan** [comment]
thanks!

see my comments elsewhere:

- https://github.com/MozillaReality/FirefoxReality/issues/347#issuecomment-417101714
- https://github.com/MozillaReality/ContentFeed/issues/50#issuecomment-417101452

it may be easier to just use Gecko's Bookmarks engine directly. or the [`browser.bookmarks` WebExtension API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks#Functions).

but, yeah JavaScript could be injected or we could pass the bookmarks as the Home URL on browser load/click of the Home icon, like so:

https://webxr.today/?region=us#{"bookmarks":[{"url":"http://example.com","color":"#ccc"},{"url":"http://instagram.com","color":"#ffa500"}]}

**Comment by bluemarvin** [comment]
GeckoView doesn't support the Gecko Bookmarks engine, that is desktop only.

**Comment by cvan** [comment]
gotcha. which persistent data-storage API or structure would you suggest I consider using to create an MVP?   https://github.com/MozillaReality/FirefoxReality/compare/master...cvan:bookmarks

**Comment by nancyhang** [comment]
@bluemarvin Is there a GV API for this?

**Comment by bluemarvin** [comment]
GV does not have a bookmark API, it is the responsibility of the embedding application to support bookmarks. The android-components project may have a bookmark component.

**Comment by keianhzo** [comment]
A bookmarks implementation is coming to Android Components. Opened a placeholder ticket for that.

**Comment by larsbergstrom** [comment]
I am assuming that we are now done with this issue, since we've chosen a different way to implement it.

**Comment by cvan** [comment]
Let's keep this open, since there is still discussion of exposing the Bookmarks in the Feed in future  designs. Thanks for checking on this one.

**Comment by jvonitter** [comment]
tracking this in #759
