### ISSUE TITLE
Migrate the Search Engine implementation to android-components

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#452]
## Hardware
All

## Current Behavior
We have our own tiny implementation of SearchEngines to get the right engine for a specific locale.

## Expected Behavior
Migrate the Search engines to android-components [browser-search] so we reuse code and also keep always up to date.

## Possible Solution
Migrate to android-components [browser-search]

## Error Logs and Stack Traces
<details open>

```
```

</details>

**Comment by keianhzo** [comment]
Initial implementation, waiting for browser and android components to converge.

**Comment by philip-lamb** [comment]
Android Components module Search is ready for prime time. https://github.com/mozilla-mobile/android-components/tree/master/components/browser/search

**Comment by MortimerGoro** [comment]
@philip-lamb this was already implemented in https://github.com/MozillaReality/FirefoxReality/pull/724/files
