### ISSUE TITLE
Add a parameter to allow entering VR without user gesture

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/FirefoxReality#456]
When doing automatic testing we should have a way to launch FxR disabling the user gesture need to enter VR, otherwise we can't really automate the process when testing WebXR content, as otherwise the user should click to start each demo.

**Comment by MortimerGoro** [comment]
We can use `dom.vr.require-gesture` preference to disable the mandatory user gesture

**Comment by cvan** [comment]
Yeah, good idea. Could we add this as an option to the Developer Panel? I believe a Restart is required for the option to take effect, but we already have the code in place for that.

FYI: Automatic presentation is already blocked in Chrome/Chromium today (and no flag is exposed for developers). A user-activation event is explicitly required in WebVR 1.1 and [WebXR](https://github.com/immersive-web/webxr/blob/master/explainer.md). Last I checked, Oculus Browser allows it, but that behaviour may have changed. And not sure about Samsung Internet Browser.

**Comment by MortimerGoro** [comment]
already landed
