### ISSUE TITLE
Looking jaggy in VR mode (Anti-Aliasing doesn't work?)

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/FirefoxReality#466]
Let me know if this is a known issue.

## Hardware

Oculus Go

## Steps to Reproduce

1. Go to Three.js example https://threejs.org/examples/#webvr_ballshooter
2. Enter VR mode
3. See view looks a bit jaggy, especially you can confirm well if you compare with the one on Oculus Browser

On FxR (Zoom the pic and see the slash lines)
![firefoxreality_three](https://user-images.githubusercontent.com/7637832/45044085-07683980-b0aa-11e8-9ecb-7f37337f1d6b.jpg)

On Oculus Browser
![oculus_three](https://user-images.githubusercontent.com/7637832/45044104-14852880-b0aa-11e8-8968-828776a038b4.jpg)

## Current Behavior

Looks a bit jaggy in VR mode

## Expected Behavior

Looks non-jaggy.

## Possible Solution

Seems like Anti-Alias doesn't work? It's turned off by FxR WebGL?

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by nancyhang** [comment]
This will be in v1.1. Takihiro will investigate with Jeff.

**Comment by daoshengmu** [comment]
I can help investigate it from the Gecko side, it would be very quick. IIRC, Android Firefox didn't have anti-aliasing in WebGL for a while.

**Comment by takahirox** [comment]
Cool. First I wanna know if this behavior is intentional or not. Anyone knows? Should I ask to Jeff?

**Comment by daoshengmu** [comment]
Well, I have done the investigation from the Gecko side. That is not made by WebGL issue. That is because someone makes `gfxPrefs::MSAALevel()` to be 0, (https://dxr.mozilla.org/mozilla-central/rev/c2e3be6a1dd352b969a45f0b85e87674e24ad284/dom/canvas/WebGLContext.cpp#409). 

It seems like GeckoView force to disable MSAA level. @bluemarvin Do you think it makes sense to disable MSAA in GeckoView? Or instead, we should consider to ignore the `gfxPrefs::MSAALevel()` preference for WebGL AA?

**Comment by MortimerGoro** [comment]
Could you try with multiprocess enabled? IIRC WebGL MSAA worked with multiprocess enabled

**Comment by takahirox** [comment]
@MortimerGoro Tried MultiProcessing enabled but still looking jaggy.

**Comment by bluemarvin** [comment]
MSAA is disabled on mobile builds because:

https://bugzilla.mozilla.org/show_bug.cgi?id=925530

**Comment by daoshengmu** [comment]
Ok. I think the easiest way is making `gl.msaa-level;true` for FxR build.

**Comment by Novezeil** [comment]
Suggestion - could we make it into a toggle in developer settings?

**Comment by Novezeil** [comment]
@daoshengmu since `about:config` is not modifiable, guess `gl.msaa-level` has to be changed from gecko perspective? any possibility to produce an developer toggle for AA?

**Comment by daoshengmu** [comment]
@Novezeil @bluemarvin I think we should consider to add `gl.msaa-level;true` here, https://github.com/MozillaReality/FirefoxReality/blob/2adf4e9b7da45c4a0a367885af9899b41ae3194f/app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java#L568.

**Comment by Novezeil** [comment]
Thanks @daoshengmu, I've done following and AA is now working. Performance drop is acceptable also.

>*./app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java*
```
out.write("pref(\"gl.msaa-level\", 2);\n".getBytes());
out.write("pref(\"webgl.msaa-force\", true);\n".getBytes());
```

**Comment by daoshengmu** [comment]
@Novezeil I think we shouldn't add `webgl.msaa-force` to be true. We need to respect the parameter from WebGL content to choose if enabling msaa.

**Comment by Novezeil** [comment]
@daoshengmu thanks for the clarification, the force tag was only applied to my fork for testing purpose and no PR will be passed.

**Comment by MortimerGoro** [comment]
This can be closed, MSAA support already landed
