### ISSUE TITLE
Add support for switching input between Touch and Mouse

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#467]
## Hardware
All

## Possible Solution
Add support for switching between Mouse and Touch input and wire it up from the Developer Panel option.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by nancyhang** [comment]
Let's remove the option dev settings panel. Will address problem in v1.1

**Comment by philip-lamb** [comment]
Putting this on ice until we have a fully developed use case for it.

**Comment by philip-lamb** [comment]
No use case forthcoming. Sorry.
