### ISSUE TITLE
Compilation Error with WaveSDK

### ISSUE THREAD

**Issue by Novezeil** [MozillaReality/FirefoxReality#470]
## Hardware
* Windows 10
* Android Studio 3.1.4
* NDK r12b
* Gradle 4.4
* WaveSDK 2.1.0 (2018-08-14)

## Double Checked
1. Git submodules are correctly initiated
2. `./third_party/wavesdk` with `build.gradle` from `./extra/wavesdk` and `wvr_client.aar` from WaveSDK 2.1.0 
3. Build variant is set to `wavevrDebug`
4. Other setting remain untouched

## Current Behavior
Sync passed (with also refreshed linked C++) with build variant `wavevrDebug` but failed with build APK (see [fxr_wavevr_20180905.log](https://github.com/MozillaReality/FirefoxReality/files/2353152/fxr_wavevr_20180905.log)). 

My first guess is there's something wrong with either min/target SDK, build tools or NDK version. Could someone please advise?

**Comment by bluemarvin** [comment]
Try a newer NDK than r12b, I am using r17b. However I don't know that any one on the team uses windows to build so that may also be an issue.

**Comment by keianhzo** [comment]
I'm using also Windows 10 and had the same error. Update to r17b as @bluemarvin says and it'll fix it.

**Comment by Novezeil** [comment]
Thanks all, problem resolved.
