### ISSUE TITLE
Handle the change between error/cancel and listening states on Voice search

### ISSUE THREAD

**Issue by andrenatal** [MozillaReality/FirefoxReality#472]
## Hardware
All devices

## Steps to Reproduce

1. Start a recognition hitting the mic
2. Cancel it
3. Start the recognition again

## Current Behavior
The error message appears in the dialog box 

## Expected Behavior
The message that should appear was the listening one

## Possible Solution
Fix the state transition

## Context
That confuses the uses.

```
```

</details>

**Comment by cvan** [comment]
> 2. Cancel it

what's the expected way for a user to cancel a search? by clicking the mic in the URL bar or by pressing the × (close button) at the top of the Voice Search modal?

**Comment by cvan** [comment]
in particular, where in these screenshots?

![image](https://user-images.githubusercontent.com/203725/45123485-ea6c4e80-b11b-11e8-8331-8802017a4e04.png)

![image](https://user-images.githubusercontent.com/203725/45123463-d45e8e00-b11b-11e8-9031-c6a5fc80095b.png)

**Comment by andrenatal** [comment]
Hi Chris. To cancel you need to press the X at the top.

**Comment by andrenatal** [comment]
Exactly!

**Comment by philip-lamb** [comment]
Can't reproduce on current version. We can reopen if we can identify new steps to reproduce.
