### ISSUE TITLE
@ Sign on Keyboard enters comma (instead of @) when entering password on Google Auth

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#479]
## Hardware

Oculus Go

## Steps to Reproduce

1. Try to log into YouTube site using Google account
2. When entering password, "@" sign keyboard button enters a comma

## Current Behavior
1. Try to log into YouTube site using Google account
2. When entering password, "@" sign keyboard button enters a comma

## Expected Behavior
@ sign button should input an @ sign on any text field when pressed.

```
```

</details>

**Comment by bluemarvin** [comment]
I can't reproduce this. Please make sure you are using a recent build.

**Comment by keianhzo** [comment]
Can't reproduce it either with the latest build.

**Comment by larsbergstrom** [comment]
I believe this only occurs on the current Oculus Store build (I can reproduce it there). It's been fixed since then, I assume?

**Comment by avrignaud** [comment]
I've been told that no one else can reproduce anymore, so yes let's close it for now. I will try again next time I am by headset.
