### ISSUE TITLE
[meta] UR Finding: Users would like to be able to position windows, tray, and keyboard to preferred locations

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#480]
UR Finding: Users would like to be able to position windows, tray, and keyboard to preferred locations.

This includes ability to move window and keyboard upward by some personalized amount to help with arm and eye strain.

**Comment by cvan** [comment]
FYI: the ability to adjust the keyboard position was filed in #415. Shall we close and forward-dupe to this issue? Or keep a separate issue for each?

FWIW, FxR's keyboard is appropriately sized and distanced, compared to Samsung Internet Browser's. Oculus Browser's keyboard is a pleasure to use with its centred keyboard, dual panels (with a numeric pad that does not have to be toggled with a button), and as-you-type search suggestions.

**Comment by avrignaud** [comment]
This is already a 1.1 issue, so we'll revisit when we do our triage/planning for that. But yes, we had different indications of this ask for personalization. Some people wanted to be able to move the keyboard/screen higher to reduce strain when typing, some just wanted to be able to move items independently.

It may make sense to add a new bug with keyboard improvements to consider in 1.1.  I agree that sizing of KB in FxR seems good (also got that feedback from users), but number pad and auto-complete suggestions would be good to capture.

**Comment by uhrheber** [comment]
Just a hint:
The Oculus Go app "VirtualBookViewer"  (https://www.oculus.com/experiences/go/2341468065880359/) has a very unique and (so I think) good way of positioning pages.

You can use the Oculus Go controller to move and tilt pages in a very creative way, that I haven't seen anywhere else so far, and it is the only app that offers a usable way to read high resolution documents and graphics, despite the (too) low resolution of the display.

I'd really like to see this features included in Firefox.

**Comment by avrignaud** [comment]
@thenadj let's take a look at VirtualBookViewer next time we meet (see above).

**Comment by thenadj** [comment]
Please take a look at DE-30 and let me know which direction resonates for browser positioning.

[DE-30 Browser Positioning_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2485491/DE-30.Browser.Positioning_001.pdf)

**Comment by keianhzo** [comment]
@thenadj After today's meeting I guess the main concern is if this conflicts with the cylindrical projection. Also a couple more questions: 
- What happens with the tray when a window is moved?
- How is it going to move around, spherical? planar? any limits?

We are not going to support multiple windows for 1.1 so as for what @avrignaud mentions above this is mainly for people to move the window higher so I'd recommend to do planar for the moment as it's going to be faster and we are going to redo this when cylindrical arrives.

**Comment by MortimerGoro** [comment]
- I don't like that having to separate the move and scaling UIs. Can they be combined? We can use the current resize mode button to show both the scaling buttons on the corners and the move button on the center.
- If we use planar movement the tray could dissapear on the floor when dragging window to the bottom
- Are we also going to allow moving window on the z plane?

**Comment by MortimerGoro** [comment]
@thenadj 

I think we can unify all the edit mode options in the same video/mode, accessing to it as we do now for the resize mode (click on the "edit" button on the navigation bar). 

Some advantages of doing this:
- Quicker layout configurations: Users can scale, move and zoom at the same time, with less clicks, without having to change modes. 
- Unified reset: If you want do go back to a default position or cancel your changes you don't need to go to `scale mode` then reset, `move mode` then reset, `zoom mode` then reset.
- Less work. Creating all the different mode UI interactions, state changes, back and forth between different modes is a lot of work.

How can it be done? We just need to mimic what Operating Systems do for Windows Management (e.g. Mac, Windows)
- You can scale the window through the handles in the corners.
- You can move the window on XY axes by just clicking inside the window and dragging.
- If we also want to allow movement on the Z axis we can do this way: While the user is moving a window with the method mentioned in the previous point they can use the trackpad in the controller to move the window in Z.
- We can add the widely used `zoom-in` and `zoom out` magnifying glass icons to allow zooming inside the content window. When we have 2 controllers we also can implement zooming using pinch gestures.  
- On the bottom of the window we can add the presets, check to save changes, or a back to cancel changes.

Example: I opened the design review PDF using the Preview app on Mac. You can scale the window from the corners, move the window by  clicking inside and dragging, and zoom-in or zoom-out using the buttons. All in the same mode.

<img width="1339" alt="captura de pantalla 2018-10-25 a las 22 49 51" src="https://user-images.githubusercontent.com/1070794/47529587-827aee80-d8a8-11e8-89af-f3e0b831a5ee.png">

**Comment by MortimerGoro** [comment]
@thenadj 
We could even get rid of resize mode and do a "live edit mode":
- Change the controller "white dot" to "resize" when the user points the controller to a corner of a window
- Change the controller "white dot" to a move handle" when it points it to the  top of the window or an empty area in the navigation bar
- Add the ZoomIn/ZoomOut icons to the tray/settings or use pinch gestures for zooming. 

Either way I think the way to go is offer a unified way of doing the layout changes.

**Comment by thenadj** [comment]
Thank you @MortimerGoro We updated the design to combine all the interactions. I recommend for the time being we put the user into a resize/reposition mode rather than allowing all actions to happen straight from the default view. VR is still very new and when we observed users during usability testing, even simple things seemed foreign to them so the expectations are not yet there to interact with UI the same way as on desktop and I am concerned about discoverability. 

Please take a look and let us know if there is any more feedback. Once we're good on a direction we'll create the UI specs so it can be implemented.

[UF-28 Browser Positioning_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2517032/UF-28.Browser.Positioning_001.pdf)

**Comment by cvan** [comment]
@thenadj: thanks to you and Jenni for putting this one together. looking good. per my question earlier, how would the Tabs sidebar look upon resizing the browser  window? I assume the resizable region would encompass both?

also, the Tray: do we have recommendations or specs we can follow for how the Tray would be moved during and after a Resize?

**Comment by thenadj** [comment]
@cvan We'll address resizing tabs pane next. Most likely the blue resize frame would be around everything, the pane and the window combined. 

As for the tray, that should be hidden during resize/reposition mode and reappear once the user commits to the new size, position.

**Comment by cvan** [comment]
> @cvan We'll address resizing tabs pane next. Most likely the blue resize frame would be around everything, the pane and the window combined.

Sounds good, let us know.

> As for the tray, that should be hidden during resize/reposition mode and reappear once the user commits to the new size, position.

In the first comment:

> UR Finding: Users would like to be able to position windows, tray, and keyboard to preferred locations.

**Comment by MortimerGoro** [comment]
Thanks @thenadj! I think the new spec is the good direction. I like the `+` and `-` icons for zooming on the top middle of the window. One question I have is: do the `1x` presets also reset the zooming and the position? If not, how we can reset the position?

**Comment by MortimerGoro** [comment]
Another question:
- Should the window movement be spherical on X and Y Axes? (it changes the angle to always face the user)

**Comment by thenadj** [comment]
Should the window movement be spherical on X and Y Axes? (it changes the angle to always face the user)

yes!!

**Comment by thenadj** [comment]
One question I have is: do the 1x presets also reset the zooming and the position? If not, how we can reset the position?

--> Good question. Maybe a global reset button would be in order here to get back to default for everything. Could also be in settings but I prefer putting it where and when the user needs it.

**Comment by jenniferhoang** [comment]
@MortimerGoro Please see attached. A global reset button is now placed above the browser.

[UF-28 Browser Positioning_002.pdf](https://github.com/MozillaReality/FirefoxReality/files/2531264/UF-28.Browser.Positioning_002.pdf)

**Comment by bluemarvin** [comment]
@jenniferhoang and @thenadj Can we just include the zoom % in the same element that has the `-` and `+` buttons. Also, it would be easier to implement if all of the button groups were actually part of the same UI element. With the above design we would need to have three different UI elements in the scene while if they were all part of the same UI element it would only be one. Rather than putting them at the top and bottom, couldn't they all be combined into a single line with groupings and then placed just bellow the `HELLO` arrow? In fact that `HELLO` arrow could also be part of the same UI element.

**Comment by thenadj** [comment]
@bluemarvin Thanks for your feedback. We'll take a look at it and make some updates to simplify things even more.

**Comment by thenadj** [comment]
@bluemarvin 

RESET ALL BUTTON:
The reason why the RESET ALL button is at the top is because it applies to EVERYTHING. We originally tried to combine it with the other UI elements at to bottom but because that content changes contextually it looked as if they user was only resetting that specific functionality rather than everything. That's why it's in a separate area. We feel pretty strong keeping it detached from the main functionality below. 

+/- and Zoom %:
We will go ahead and combine +, - and the zoom level percentage, so that there is only one container for all of that functionality/information. 

COMBINING ALL INTO ONE:
The reason why +/- (zoom) and 3x, 2x, 1x... are in different containers is because they are different features that could very easily be confused if visualized in a way that they relate. In the future with 6dof devices that have two controllers we can get rid of some of the UI and use controllers to zoom in and out but for now we need a bit more UI to help the 3dof one controller devices... namely Oculus Go.

**Comment by jenniferhoang** [comment]
@bluemarvin please see attached. The zoom level % has been added into the same UI as the zoom buttons.

[UF-28 Browser Positioning_003.pdf](https://github.com/MozillaReality/FirefoxReality/files/2532181/UF-28.Browser.Positioning_003.pdf)

<img width="278" alt="screen shot 2018-10-30 at 5 35 01 pm" src="https://user-images.githubusercontent.com/41343760/47758862-2c23fc00-dc6a-11e8-8fb3-791222ff64f5.png">

**Comment by cvan** [comment]
Thanks for this.

Though looking at this, I am unclear what the Reset All, the resize points along the edges and corners, the Zoom, and the bottom Resize options do.

Can we add labels? Seeing percentages in one spot and `x` fractional numbers in another spot confuses me.

What are the key functionalities we are trying to introduce and convey here?

**Comment by thenadj** [comment]
@cvan It doesn't come across very well in a static image, but the +/- is for zooming in/out of the page content. I don't think we need to add a label. If we do, let's start without it and add one if it's still unclear. The % and x fractional numbers are contextual and should make sense when interacting with it. I'd like to close on this design soon, we have incorporated lots of different feedback and it's time to try it in VR before we continue tweaking it.

**Comment by cvan** [comment]
Thanks for the pointers. It still does not make sense to me. Perhaps others can chime in. If it is not obvious here, having read the comments above in this thread, it will likely not be any more intuitive to users in a VR implementation. Can we simplify this by removing the modalities or options (e.g., the checkmark for the resizing options, the resize points, the Zoom vs. Resize).

What is the difference between Zoom and Resize? And when would I know when I need to use either or both?

**Comment by thenadj** [comment]
@cvan All of these were requirements we had to build into one design. Originally we had multiple modes but eventually based on feedback put everything into one. Having it all in one makes it easier to access but blurs the line between subtleties of features. At this point we've addressed everything and came up with two different designs that we both feel work. If we need to change anything then I'd recommend we remove features to simplify things.

**Comment by avrignaud** [comment]
We need to make some calls for 1.1 to ship. For now, let's leave as is (keep the zoom), but I'd like to watch for user feedback around possible confusion, as well as test it explicitly with next round of UX testing. Note that multiple windows/tabs are right around the corner (could be 1.2), so we have a chance to revisit very soon anyway.

**Comment by thenadj** [comment]
@avrignaud @cvan Attached is a design exploration to illustrate some more options. Should we schedule a breakout session next week to come to a conclusion on final direction or do you want to pick one and give us the green light? The three options have multiple variables that can be combined in different ways. Option C is a simplified version where the resize presets (3x, 2x, 1x...) are removed all together. Personally, I don't like removing them as users seemed to like them in the usability study. 

[DE-30 Browser Positioning_005.pdf](https://github.com/MozillaReality/FirefoxReality/files/2540407/DE-30.Browser.Positioning_005.pdf)

**Comment by avrignaud** [comment]
I actually like B a lot - teach the user with the modal instructions, but then have those dismissed and not bother the user. I'm also fine with A, but lean toward B. 

In the spirit of trying to keep things moving ahead with asynch discussion, I'd suggest we do B, and see how users react. Remember, we will be doing more UX testing early next year, and this can be a focus. Sound good?

**Comment by thenadj** [comment]
The size control in resizing looks off. See attached for what it is supposed to look like. Also in UIS-41.
[UIS-41 Resize Mode_002.pdf](https://github.com/MozillaReality/FirefoxReality/files/2586651/UIS-41.Resize.Mode_002.pdf)

![image](https://user-images.githubusercontent.com/13240857/48575021-a1780980-e8c5-11e8-976c-11bb088483d3.png)

**Comment by caseyyee** [comment]
@thenadj that's a bug, fixed in https://github.com/MozillaReality/FirefoxReality/pull/829 fyi.

**Comment by jvonitter** [comment]
Can we re-scope this ticket to only apply to the keyboard? Or maybe create new ones for 1)movable keyboard, 2)movable windows, 3)movable trays.

**Comment by philip-lamb** [comment]
> Can we re-scope this ticket to only apply to the keyboard? Or maybe create new ones for 1)movable keyboard, 2)movable windows, 3)movable trays.

Good call. I've created issues to track implementation, and we can keep this issue as a master to track design and UX aspects.

**Comment by cvan** [comment]
> Good call. I've created issues to track implementation, and we can keep this issue as a master to track design and UX aspects.

:+1: and, can we rename this to `[meta] …` so it's searchable like the other tracking bugs?

**Comment by jvonitter** [comment]
We've implemented movable keyboard and window placement customization. Closing this, but if we get additional feedback about customizing positions we will make new issues.
