### ISSUE TITLE
Pointer/Cursor updates

### ISSUE THREAD

**Issue by thenadj** [MozillaReality/FirefoxReality#481]
Two updates to the pointer:
1. Cursor dot at end of pointer: Outline color is too dark (black?). Use color asphalt: #3D3D3D instead.
2. Add option to change pointer laser beam color in dev options panel. Remove orange color all together and only allow switching between white and purple. White should be default with option to change to purple from dev options dialog. Disable pointer color change when clicking outside of UI (this was only for testing). 

@avrignaud Can we get those changes done in v1?

**Comment by avrignaud** [comment]
@nancyhang can we check with engineers and see if we can do this for 1.0? All three changes (including disabling pointed color change when clicking outside of UI) seem easy enough.
