### ISSUE TITLE
Loading icon should not be headlocked

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#487]
## Hardware
Oculus Go

## Steps to Reproduce
1. Launch Firefox Reality from the library

## Current Behavior
The loading icon is headlocked (moves with your head).

## Expected Behavior
The loading icon is in a fixed position.

## Details
This is a ship blocker / will result in app rejection if we don't fix it.

**Comment by larsbergstrom** [comment]
cc @bluemarvin @keianhzo Is this straightforward to fix? Thanks!

**Comment by MortimerGoro** [comment]
We only need to remove a matrix multiplication: https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/main/cpp/SplashAnimation.cpp#L76

**Comment by bluemarvin** [comment]
I'll try and get to it today.
