### ISSUE TITLE
Implement UA string site override list functionality 

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#488]
We will want to implement an override list for 1.1 that allows us to send a different UA string on a per URL basis for compatibility reasons. We may also want to implement the ability to select Servo as a rendering engine on a per URL basis for use in rendering experiments and testing new web platform features.

**Comment by caseyyee** [comment]
Setting `general.useragent.override`  with String set to UA works.

Testing with updated UA does yield better Youtube quality stream and proper un-wrapped projection for the VR 360/180 modes.

Additional usage note from @bluemarvin:

> `general.useragent.override` is a foot gun, once it's set, it can't be unset unless you nuke your install.`

**Comment by cvan** [comment]
by `general.useragent.override`, do you mean [`general.useragent.site_specific_overrides`](https://dxr.mozilla.org/mozilla-central/search?q=site_specific_overrides&redirect=false)?

or something different?

**Comment by cvan** [comment]
ah, I found `general.useragent.override` here: https://searchfox.org/mozilla-central/search?q=useragent.override&path=
