### ISSUE TITLE
Ensure all WaveVR SDK properties set properly in manifest and startup

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#493]
## Hardware
HTC Wave OS

## Steps to Reproduce
Look at instructions & feedback at:
https://developer.viveport.com/documents/sdk-wave/en/VRActivity.html

## Current Behavior
There are a few missing/different settings, e.g., the required `android:theme` and a few other settings. We will probably get more feedback during initial submission, but HTC pointed us to this to make sure we're checking / settings these things at submission.

**Comment by philip-lamb** [comment]
Updated reqs are at https://hub.vive.com/storage/app/doc/en-us/ConfigureAppCapabilities.html. I have checked against all these as of WaveVR SDK 3.0.2 and we've got everything required. As regards the style, we define FxR.Dark which has Theme.Black.NoTitleBar.Fullscreen as its parent.
