### ISSUE TITLE
Connect the "i" button to a help article

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#495]
## Hardware
Oculus go
## Steps to Reproduce
1. Click the "i" button in the tray

## Current Behavior
Does nothing

## Expected Behavior
Per the designs (cc @thenadj) load a help page in the browser. Maybe load the SUMO page once https://bugzilla.mozilla.org/show_bug.cgi?id=1473969#c11 is done and we have a final URL?

**Comment by avrignaud** [comment]
Yes, this is the intended design - but we seem to be having challenges getting links to the final SUMO help page. Meeting on Tuesday to hopefully resolve!

**Comment by larsbergstrom** [comment]
This URL is:
https://support.mozilla.org/en-US/products/firefox-reality

Thanks, @nancyhang!
