### ISSUE TITLE
Keyboard: a letter will be deleted when entering to the captive mode.

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#499]
## Hardware

Oculus Go
## Steps to Reproduce
1. Go to URL bar, make Keyboard be shown.
2. Try to type `goo.gl/EKhDZW`. When typing uppercase letters, double clicking the `Shift`[Up Arrow] button to make it as an `underline Shift`.

## Current Behavior
It will remove the last letter first, then starting to let user type uppercase letters.

## Expected Behavior
It should not remove any letters.

## Context
It makes users have trouble in typing the word which has continuous letters, we should fix it.

```
```

</details>

**Comment by avrignaud** [comment]
@bluemarvin Hoping this isn't a GV problem? Can we check?

**Comment by bluemarvin** [comment]
@avrignaud I don't think it is a GV bug. I think it is this line:

https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/common/shared/org/mozilla/vrbrowser/ui/CustomKeyboardView.java#L928
