### ISSUE TITLE
App should display a menu with an option to quit when at the toplevel

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#503]
## Hardware
Oculus Go

## Steps to Reproduce
1. From the home screen, press the back button

## Current Behavior
Nothing happens

## Expected Behavior
The application should display a menu with an option to quit the app.

## Possible Solution
The application to display a menu with an option to quit the app.

@thenadj @bluemarvin @keianhzo Can you please look into this ASAP? This is a blocker from shipping in the Oculus store. Thanks!

**Comment by larsbergstrom** [comment]
Official test: https://developer.oculus.com/distribute/latest/concepts/vrc-mobile-input-3/

**Comment by thenadj** [comment]
It appears that this is an Oculus dialog and not a native dialog we need to design and implement as all apps use the same one.

**Comment by keianhzo** [comment]
Fixed in https://github.com/MozillaReality/FirefoxReality/pull/482/commits/f6ded28a9b2e43f417592aea8fb8183c6f1a83de

Refreshing the region using #region= was adding an entry to the session history and causing an infinite loop while going back.
