### ISSUE TITLE
objects with sphericalEnvMap property do not get presented in FxR

### ISSUE THREAD

**Issue by nbackous** [MozillaReality/FirefoxReality#506]
## Hardware
Oculus Go

## Steps to Reproduce
test with A-Frame doodle here: https://sphere.glitch.me
1. with FxR load above URL
2. with Oculus Browser load above URL
3. notice difference in assets presented
4. edit source and remove the sphericalEnvMap property and repeat steps 1&2

## Current Behavior
Sphere object with sphericalEnvMap property is not displayed but the sphere _does_ still cast a shadow if a sphericalEnvMap property is employed. This problem is *not* occurring with the Oculus browser.

## Expected Behavior
objects using the sphericalEnvMap should be presented properly

## Possible Solution

![firefox_reality_browser](https://user-images.githubusercontent.com/40135245/45319993-39d4c500-b4f6-11e8-887c-2659305008e2.jpg)

![oculus_browser](https://user-images.githubusercontent.com/40135245/45319994-39d4c500-b4f6-11e8-9967-5e20996a942a.jpg)

Hey @slightlyoffbeat, I briefly chatted with you about this issue at the XOXR meetup. I've further diagnosed the issue and provided details above.

<details open>

```
```

</details>

**Comment by nancyhang** [comment]
Related to #461

**Comment by nancyhang** [comment]
@fernandojsg  Since #461 is resolved, does the fix apply to this issue?

**Comment by philip-lamb** [comment]
Cannot reproduce with FxR v1.1.2, works as intended. Will close.
