### ISSUE TITLE
FxR is slower than Oculus Browser on this test page

### ISSUE THREAD

**Issue by joshmarinacci** [MozillaReality/FirefoxReality#510]
https://green360.glitch.me/

## Hardware

Oculus Go

## Steps to Reproduce

1. Load the URL above in the Oculus Go browser
2. Load the URL above in FxR

## Current Behavior

FxR renders significantly slower

## Expected Behavior

They should render at the same speed, if not faster.
<details open>

```
```

</details>

**Comment by philip-lamb** [comment]
Closing as duplicate of https://github.com/MozillaReality/FirefoxReality/issues/878
