### ISSUE TITLE
Fix minor typo on Private Browsing splash page (`about:privatebrowsing`)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#511]
## Hardware
All

## Steps to Reproduce
1. Click the Private Browsing icon.
2. Notice there should not be a period before "Firefox Reality" in the first sentence.

## Current Behavior
![image](https://user-images.githubusercontent.com/203725/45398232-417c9280-b5f8-11e8-852b-12ed6462f264.png)

## Expected Behavior
There's no period.

## Possible Solution
Remove the period.

**Comment by keianhzo** [comment]
@cvan As this is already been addressed in https://github.com/MozillaReality/FirefoxReality/pull/512/commits/50aba3defacaa7fb72ccbb693bddc07a82dc4974 I guess this one can be closed.

**Comment by keianhzo** [comment]
@cvan Close this one as this has already been addressed in 50aba3d
