### ISSUE TITLE
Render the current document's `<title>` in the browser UI/chrome

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#519]
## Hardware
All

## Steps to Reproduce
1. Load in Firefox Reality a page with a `<title>`.
2. Notice that the `<title>`/`document.title` is not rendered anywhere in the UI/browser chrome.

## Current Behavior
The document title is not visible in the UI/browser chrome.

![image](https://user-images.githubusercontent.com/203725/45463387-d0ed7880-b6c0-11e8-9cde-a7bfc0469358.png)

## Expected Behavior
The document title is visible somewhere in the UI/browser chrome.

## Possible Solution
This will likely need a design spec. I am not sure where it should appear, but the document title could appear above the browser window, for example. I don't have any good recommendations that come to mind at the moment.

**Comment by thenadj** [comment]
@cvan Will this be solved once we have tabs?

**Comment by cvan** [comment]
> @cvan Will this be solved once we have tabs?

I hadn't thought of that. but you make a very good point - it will :smile:

**Comment by jvonitter** [comment]
Final design is here https://trello.com/c/woRPXarr/375-uis-69-window-title
