### ISSUE TITLE
The `x` buttons shows even when the URL bar does not have focus.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#524]
## Hardware

All

## Steps to Reproduce

1. Do a voice search

## Current Behavior

The `x` button is shown in the URL bar.

## Expected Behavior

The microphone button should be visible.

## Possible Solution

I think the `x` should only be visible if the URL text edit field has focus and it contains text.

**Comment by bluemarvin** [comment]
I'm not sure putting the microphone button in the URL bar is great UX, but we definitely want people to see it and use it so for now I think we only want to show the clear `x` button when the text field has focus?

**Comment by keianhzo** [comment]
Yes, this behavior feels more natural that the previous one, going to change it.
