### ISSUE TITLE
Revisit resizing window options in the default view

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#526]
## Hardware
All

## Steps to Reproduce

1.Window does not have handles on lower edges - due to occulusion challenges discussed in #463 (closed for 1.0). 

## Current Behavior

Window does not have handles on lower edges - due to occlusion challenges discussed in #463 (closed for 1.0). 

## Expected Behavior

Allow user to resize window from all sides.

## Possible Solution

Allow user to resize window from all sides.

```
```

</details>

**Comment by larsbergstrom** [comment]
I believe this is completed; please open a specific issue if you feel something has not been addressed.

**Comment by bluemarvin** [comment]
This issue actually describes the current state and still needs to be addressed.

**Comment by avrignaud** [comment]
Closing - dupe of #628 . Will add handles on lower edges feedback to 628.
