### ISSUE TITLE
Firefox Reality on Daydream

### ISSUE THREAD

**Issue by madorian** [MozillaReality/FirefoxReality#529]
Not sure where to ask, but is this coming to Daydream?

**Comment by avrignaud** [comment]
Hi madorian, thank you for your interest! We haven't announced details yet, but I think your question will be answered in the very near future. :)

**Comment by avrignaud** [comment]
And here you go! :) https://play.google.com/store/apps/details?id=org.mozilla.vrbrowser

**Comment by madorian** [comment]
Oh, great, wow. Thanks alot;) Playtime
