### ISSUE TITLE
[WebCompat] Konterball does enter VR mode anymore because of User-Agent/browser sniffing

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#535]
## Hardware
Tested on latest build (`VLuY7aI-TVaYdsPxaimq2Q - 2018-09-18`) on the Oculus Go.

## Steps to Reproduce
1. Launch https://konterball.com/.
2. Proceed through the screens and start a new game (the choice on the left).
3. Try to enter VR.
4. Notice that the audio is playing, but the screen is black.

## Current Behavior
The audio plays but the screen is black. When you "exit" VR mode, you can see there's a Cardboard-looking VR icon in the bottom-right corner. Clicking on it seems to engage Cardboard-esque gaze controls.

## Expected Behavior
Entering VR on Konterball should work like it did when FxR had its previous desktop-looking `User-Agent` string.

## Possible Solution
[File an issue](https://github.com/madebywild/konterball/issues/new) in the [GitHub repo](https://github.com/madebywild/konterball).

## Context
This was likely caused from switching from the desktop to mobile/VR UA (see #478). It could be related to googlevr/webvr-ui#8. I'm not sure. Haven't digged in enough.

## Error Logs and Stack Traces
Haven't checked yet. Will post them at a later time.

**Comment by philip-lamb** [comment]
@cvan Please test with current build.

**Comment by cvan** [comment]
Thanks, tested, and [_Konterball_](https://konterball.com/) does not work with neither Firefox Reality nor Oculus Browser.

As of September 18, 2018, the code was changed to not work with WebVR, in preparation for an update to work with WebXR. Now when attempting to start a game, this explicit message is shown:

> We're updating WebVR to WebXR. In the meantime, check <u>out this experiment in 360</u>.

https://airtable.com/tbl5KsyUIhi2XDcWp/viwITwiXrL29b3DJv/rec6jGLwfbnxuIGTi

![2019-03-05_05 36 06](https://user-images.githubusercontent.com/203725/53809308-48ca8c00-3f09-11e9-9749-4898354e4468.png)
![2019-03-05_05 36 01](https://user-images.githubusercontent.com/203725/53809309-48ca8c00-3f09-11e9-933f-ca644db11e57.png)
![2019-03-05_05 35 38](https://user-images.githubusercontent.com/203725/53809310-48ca8c00-3f09-11e9-8ba7-f110d1c528d5.png)
![2019-03-05_05 35 31](https://user-images.githubusercontent.com/203725/53809311-48ca8c00-3f09-11e9-8e32-3b2f8942d4f4.png)
![2019-03-05_05 35 20](https://user-images.githubusercontent.com/203725/53809312-49632280-3f09-11e9-93ae-5428cdd4b214.png)
![2019-03-05_05 35 07](https://user-images.githubusercontent.com/203725/53809313-49632280-3f09-11e9-9eff-6197da8a4c43.png)
![2019-03-05_05 34 21](https://user-images.githubusercontent.com/203725/53809314-49632280-3f09-11e9-8e0d-eab59eb38b6a.png)
![2019-03-05_05 33 43](https://user-images.githubusercontent.com/203725/53809317-49632280-3f09-11e9-88f4-1baa9fbd5084.png)
![2019-03-05_05 33 13](https://user-images.githubusercontent.com/203725/53809318-49632280-3f09-11e9-8df3-2412139d0cd2.png)

**Comment by philip-lamb** [comment]
OK, putting this one in the Icebox and we can pull it out later.

**Comment by philip-lamb** [comment]
Closing as a content issue. We can reopen if we have actionable steps later.
