### ISSUE TITLE
goBack doesn't work first time when opening a Youtube video from Google search

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#536]
## Hardware
All

## Steps to Reproduce
1. Search for videos in Google
2. Click on a search result video tile
3. Let the video start to play
4. Click on the back button

## Current Behavior
Nothing happens

## Expected Behavior
You should go back to the Google search

## Possible Solution
Related GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1492094

## Error Logs and Stack Traces
<details open>

```
```

</details>

**Comment by cvan** [comment]
is this the same as #494 or related?

**Comment by keianhzo** [comment]
I think it's a duplicate.

**Comment by nancyhang** [comment]
Following up with GV on fix.

**Comment by cvan** [comment]
This seems fixed now. @keianhzo can you reproduce?

**Comment by keianhzo** [comment]
@cvan I have checked and it doesn't seem to be happening now. Should we close?
