### ISSUE TITLE
promote links to the Content Feed submission page (Airtable form)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#537]
for the Content Feed, we're using this: https://airtable.com/shrHKZrLcGJhXNVuH

it'd be nice to get a section added to our support.mozilla.org pages, so folks 
can find it from here: https://support.mozilla.org/en-US/products/firefox-reality/get-started

like this from the MR Site refresh:

![image](https://user-images.githubusercontent.com/203725/45681892-853d3380-baf3-11e8-9baf-561edd75114d.png)

also, we should probably add a big section at the top of this project's README too. I'm sure the question will come up often.

and perhaps maybe we should even have a tiny URL. https://mzl.la/fxr-submit?

**Comment by avrignaud** [comment]
These all sound like great ideas! Only thing I'd suggest is a quick chat with @thenadj  about how/where we might fit on next version of content feed. I think she has some early thoughts she was planning to get your thoughts on - might integrate there nicely.

**Comment by caseyyee** [comment]
Just an idea to extend on this idea, but it would be nice to feature information about content creation for WebVR right in the feed.  Given limited content, it would make sense to encourage users to create for the platform right where they consume it as well as making it clear how to submit content.

**Comment by thenadj** [comment]
@caseyyee What types of user generated content do you have in mind?

**Comment by joshmarinacci** [comment]
Do you mean having a link on the feed that says: Get your content here.

**Comment by caseyyee** [comment]
@thenadj It could be anything, but just making it evident that it's open for content creators to get their stuff featured is a good start.  @joshmarinacci you gotit!

**Comment by larsbergstrom** [comment]
It looks like there are two issues here?
1) We should contact SUMO and ask to have another page added
2) We might want to add something into the content feed itself

Is that correct?

**Comment by jvonitter** [comment]
This work will live in the Content Feed repo if/when it happens
cc @joshmarinacci
