### ISSUE TITLE
Feature request: Open in new tab

### ISSUE THREAD

**Issue by hippocratical** [MozillaReality/FirefoxReality#539]
## Hardware

OculusGo

## Feature Request  

A long press to display "Open in New Tab" would be awesome. Currently no OculusGo browsers allow open in new tab, even thought the default browser does have tabs.  

Having to browse using on the Back button is giving me 90's flashbacks. It's terrible.

```
```

</details>

**Comment by avrignaud** [comment]
Thank you for the suggestion! We'll be working on new tab/multi-window support in the near future. @thenadj JFYI.

**Comment by philip-lamb** [comment]
Related to #635

**Comment by philip-lamb** [comment]
Closing as this work will be covered under #635.
