### ISSUE TITLE
Allow website to define custom environment/background

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#543]
UR Feedback: Allow website to define custom environment/background. This could include a glTF model, 3D scene, or 360 image/video. Should also consider allowing user to save as default environment, similar to "Save as Desktop" on Windows.

**Comment by larsbergstrom** [comment]
This is related to:
https://github.com/immersive-web/proposals/issues/23

**Comment by cvan** [comment]
also related to https://github.com/immersive-web/proposals/issues/22#issuecomment-416749744

good ideas

**Comment by jvonitter** [comment]
Carmack mentioned this in his OC6 keynote
