### ISSUE TITLE
Hubs needs a way to detect if we should skip the initial mode selection screen

### ISSUE THREAD

**Issue by gfodor** [MozillaReality/FirefoxReality#546]
In Hubs, we give the user the choice on the landing page of what mode of entry they want to use (2D, VR, link to standalone, etc.) In in-VR browsers, we can skip this step since we know they want to go into direct immersive mode. We are doing UA sniffing of Oculus Browser to do so. Please advise on the proper way to do this for Firefox Reality. Thanks!

**Comment by avrignaud** [comment]
@bluemarvin @larsbergstrom Any recommendations? 

Can we set the mobile VR UA string when FxR visits hubs.com? In general, Hubs has a lot of opportunities for FxR integration and we need to find ways to make the experience seamless. :)

**Comment by larsbergstrom** [comment]
@gfodor @brianpeiris Does this work better, now that we have the VR UA string?

**Comment by cvan** [comment]
Let us know against `master` APKs. The UA has `Mobile VR` in the place of `Mobile`.

That should suffice for the immediate short term.

**Comment by brianpeiris** [comment]
Thanks for the update. We'll change Hubs to use this, the current workaround has been flakey in the past. I'll call this closed.
