### ISSUE TITLE
Mi VR Standalone

### ISSUE THREAD

**Issue by geokon-gh** [MozillaReality/FirefoxReality#548]
Are there instructions of getting this on the Xiaomi Mi VR Standalone？ It's the same hardware as the Oculus GO but the software is a bit different. 

http://vr.mi.com/developer/

Seems that the Oculus Mobile SDK works fine, but the Oculus Platform/Avatar SDKs will not b/c they require connecting to Facebook owned servers (which are blocked in China). It's unclear from the README if those SDKs are required for FirefoxReality or not

**Comment by jiaming233** [comment]
Hi. I try to build and install the APK on Mi VR Standalone. It seems that Oculus Platform/Avatar SDKs are not necessary for FirefoxReality. However, when I run the app, I get error message that "Oculus Update Required. To learn how to update your Oculus app, visit http://support.oculus.com".

Did you have the same issue? Any solution to fix it？

**Comment by jiaming233** [comment]
> Hi. I try to build and install the APK on Mi VR Standalone. It seems that Oculus Platform/Avatar SDKs are not necessary for FirefoxReality. However, when I run the app, I get error message that "Oculus Update Required. To learn how to update your Oculus app, visit http://support.oculus.com".
> 
> Did you have the same issue? Any solution to fix it？

Previously I used Oculus Mobile SDK v1.20 and got error.
FirefoxReality with v1.19 works well cuz the vrapi version of my Mi VR Standalone is 1.19.0.

**Comment by geokon-gh** [comment]
is there any particular reason this hasn't been release I'm the xiaomi app store? @philip-lamb

**Comment by philip-lamb** [comment]
The Xiaomi Developer Agreement has some terms which are roadblockers for Mozilla at present. We're in discussions, but there is no timeline for when amended terms might be available. In the meantime, the usual methods for loading directly onto the device should work: https://github.com/MozillaReality/FirefoxReality/wiki/Sideload

**Comment by geokon-gh** [comment]
Thanks for the details and the update. I'm going to give it a try in the near future. The side loading situation on the MiVR seems more complicated than the oculus version from what I remember. You need to create a developed account and sign all sidloaded apps.. if I don't misremember

**Comment by philip-lamb** [comment]
Unfortunately, Mi VR is no longer available.

**Comment by geokon-gh** [comment]
@philip-lamb could you elaborate?

**Comment by philip-lamb** [comment]
https://skarredghost.com/2019/08/05/xiaomi-lay-offs-mi-vr-oculus-go/

**Comment by geokon-gh** [comment]
That's from two months ago, but doesn't it go to show that the Mi VR is still available?

In the article you link Xiaomi confirmed officially they will keep selling the Mi VR
Furthermore the Xiaomi VR is still sold on their website: https://www.mi.com/mivr-1o

The rest (about future development of their SDK) is a rumor? I'm not sure how it's related
