### ISSUE TITLE
Feature request: Firefox Sync

### ISSUE THREAD

**Issue by Tomires** [MozillaReality/FirefoxReality#549]
## Hardware
Oculus Go

## Feature Request
As a user of both the desktop and mobile version of FF, I would also appreciate an implementation of the Sync feature (hope I got the name right, it's the one that allows the user to send tabs across devices), which could help alleviate the terrible typing experience on 3DOF headsets.

```
```

</details>

**Comment by philip-lamb** [comment]
This work will be implemented as part of Firefox Accounts. Closing as duplicate of #717
