### ISSUE TITLE
Ensure back button behaves correctly when in fullscreen mode.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#55]
Need to make sure and catch when gecko view is in fullscreen mode so that clicking the back button on the controller takes gecko view out of fullscreen mode instead of actually going back in history.

**Comment by keianhzo** [comment]
This is working fine after te focus mode has been implemented, the back handler is always added when GeckoSession.ContentDelegate,onFullScreen is called.
