### ISSUE TITLE
Shadertoy displays in a very low resolution

### ISSUE THREAD

**Issue by andybak** [MozillaReality/FirefoxReality#551]
## Hardware
Lenovo Mirage on Android 8.0.0

## Steps to Reproduce
1. Visit any Shadertoy shader that supports VR. For example: https://www.shadertoy.com/view/4sX3Rn
2. Click the goggles icon to enter VR mode

## Current Behavior
The shader displays in VR but at an extremely low resolution

## Expected Behavior
Better resolution should be possible.

## Possible Solution
It should be possible to change the default resolution some how to get the shader to display at a higher resolution. I understand the defaults are probably a good balance of framerate vs quality for typical VR scenes but they are inadequate for full-screen shaders. Maybe there could be a setting to override the defaults (ideally per domain?)

## Context
Although many shaders will be too demanding to run on current mobile devices this will change. Furthermore some shaders are easily within current device capabilities at a reasonable resolution.

## Error Logs and Stack Traces
n/a
<details open>

```
```

</details>

**Comment by caseyyee** [comment]
Unfortunately, this looks to be a problem with Shadertoy. It looks like they are not setting the Canvas to the proper viewport size.  See: https://developer.mozilla.org/en-US/docs/Web/API/VREyeParameters/renderWidth for details and an example of how this works.

I also checked Oculus browser, and desktop WebVR with a VIVE and see the same issue.

**Comment by nancyhang** [comment]
We looked into this, this is an issue with Shadertoy.
