### ISSUE TITLE
Support MixedReality headsets

### ISSUE THREAD

**Issue by benbucksch** [MozillaReality/FirefoxReality#553]
## Hardware
HP VR 1000
Windows MixedReality

## Steps to Reproduce
Go to Firefox Reality website

## Current Behavior
No compatible binaries. No compatible store. Cannot install.

## Expected Behavior
Supports MixedReality headsets.
Available in Steam store (see #552) and possibly optionally in Microsoft store.

## Possible Solution
Use OpenVR API. It supports both Vive and MixedReality.

Firefox WebVR already supports MixedReality. I have used VR in Firefox for Windows with this headset.

## Context
Similar headsets affected are:
* HP VR 1000
* Lenovo Explorer
* Dell Visor
* Samsung Odyssey
* Asus
* Medion

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by nancyhang** [comment]
This is a feature request for Firefox browser, not Firefox Reality.

**Comment by benbucksch** [comment]
no, it's not. I want "Firefox Reality" to work on MixedReality headsets. Firefox for Windows already does work with them, as i wrote.

Am 25. September 2018 19:15:13 MESZ schrieb Nancy Hang <notifications@github.com>:
>This is a feature request for Firefox browser, not Firefox Reality. 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MozillaReality/FirefoxReality/issues/553#issuecomment-424425544

-- 
Sent from my phone. Please excuse the brevity.

**Comment by nancyhang** [comment]
Firefox Reality is currently targeting standalone VR headsets only. WebVR currently is supported on Windows Mixed Reality via using Firefox and SteamVR.

**Comment by benbucksch** [comment]
Firefox Reality is launched on desktop now: https://blog.mozilla.org/blog/2019/01/08/mozilla-announces-deal-to-bring-firefox-reality-to-htc-vive-devices/

It would be nice to use an API that supports all headsets. Almost all games on Steam work fine with the Windows MixedReality headsets, even if the game developers do not specifically support them.

**Comment by ronnelson** [comment]
Firefox Reality is in the Microsoft Windows store, but locked to WindowsAR headsets, no WindowsMR:

https://www.microsoft.com/en-us/p/firefox-reality/9npq78m7nb0r

What's the blocker?
