### ISSUE TITLE
Oculus Go: Please increase framerate to 72Hz

### ISSUE THREAD

**Issue by uhrheber** [MozillaReality/FirefoxReality#555]
Oculus Go:
By default, the Oculus Go renders at 60fps, which leads to visible flicker.
The frame rate can be increased to 72Hz, to avoid this.
Oculus provides a detailed description here: https://developer.oculus.com/documentation/mobilesdk/latest/concepts/mobile-72hz/
Please increase the default frame rate to 72Hz, or, if this causes performance issues, provide an option to enable and disable 72Hz.

**Comment by cvan** [comment]
see https://www.reddit.com/comments/94d2wm for [/r/oculusgo](https://www.reddit.com/r/OculusGo/) discussion

**Comment by kearwood** [comment]
IIUC, it can be possible to run the Gecko compositor at a higher refresh rate with some pref flips, but more work if the refresh rate needs to change at runtime.  When working on the CSS-Transform based early WebVR experiments, we bumped the browser FPS to 90.  OFC, beware of dragons -- there may be some untested things that assume 60fps.  Things to watch out for would be desync'ed video/audio, CSS animation correctness, smooth scrolling / scroll snap glitches, and any web content that doesn't expect > 60fps (RAF callbacks would also occur more frequently without further modification).

**Comment by bluemarvin** [comment]
The Quest already runs at 72Hz and the Focus runs at 75Hz. We just need to set a pref for the Go to run at 72Hz instead of 60Hz. Gecko is completely decoupled from the VR rendering frame rate.

**Comment by jvonitter** [comment]
Note that we might someday want to make this a user setting (not now, though)
