### ISSUE TITLE
Add additional languages to voice search

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#559]
Likely Japanese and Mandarin first. But we'll want to track FxR  and content feed localization bugs and work to be in parallel as much as possible. Current draft list is: EFIGS, Mandarin, Japanese, Korean, [Other] but will change. Prioritized list to follow.

**Comment by larsbergstrom** [comment]
@andrenatal Has added support for a ton of languages to the speech backend: https://github.com/mozilla/speech-proxy/blob/master/languages.json
 
Let's use them!

**Comment by larsbergstrom** [comment]
This has been completed!
