### ISSUE TITLE
Firefox Reality does not start on Samsung GearVR

### ISSUE THREAD

**Issue by Idorobots** [MozillaReality/FirefoxReality#562]
## Hardware
Samsung GearVR running on a Samsung S7.
Android version: 8.0.0
Oculus app version: 3.47.0.5.4714

## Steps to Reproduce
1. Download the oculusvr version of the .apk from https://tools.taskcluster.net/groups/ZXYhrQL-R--B9rRYMU5Yag/tasks/ZXYhrQL-R--B9rRYMU5Yag/runs/0/artifacts
2. Install it via ADB

## Current Behavior
App icon does not appear in the apps nor can it be opened in any way.

## Expected Behavior
App icon appears in apps and Firefox Reality can be started.

## Context

Perhaps it's not officially supported... Yet?

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by Idorobots** [comment]
Worth noting: I was trying to install the release .apk. The debug version does appear in the apps menu, but crashes in the Oculus app.

**Comment by bluemarvin** [comment]
It is not possible to side load on to GearVR with out building the APK yourself. See: [OSIG Generator](https://dashboard.oculus.com/tools/osig-generator/)

**Comment by Idorobots** [comment]
Is there a time line on official Oculus Gear VR release though?

**Comment by bluemarvin** [comment]
I was able to install from the Oculus Store on my S8. But there are no current plans to officially support clip-in VR head sets at this point.

**Comment by Idorobots** [comment]
Weird. It does not appear on the store for me. Are you sure you are not talking about installing a version for the Oculus Go?

**Comment by bluemarvin** [comment]
The same APK runs on both the Go and GearVR. But some one may have blocked clip-ins now on the store since they are not officially supported.
