### ISSUE TITLE
FxR freeze on back button press after clean install

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#564]
## Hardware

Go
## Steps to Reproduce

1. Do a clean install of FxR
2. Press back button on controller

## Current Behavior

FxR freezes in a call to `AInputQueue_preDispatchEvent()`

## Expected Behavior

The back button should bring up the exit/continue system menu.
## Solutions
It might be possible to optionally have the Gecko crash reporter not register for the SIGILL signal on Oculus systems.
## Context

The issue appears to be be a race condition between Gecko and Oculus runtime for registering signal handlers. This is related to the back button crashes we were seeing on first run previously. The issue is as follows, If Gecko registers its crash reporting signal handler first and then Oculus registers their signal handler for the back button and home button, everything works as expected. However, if Oculus registers their signal handler first and Gecko register the crash reporter signal handler second, the render loop hangs in the android call AInputQueue_preDispatchEvent(). Under normal conditions Gecko registers first and every thing works. The reason this is triggered on first run (or anytime libxul.so gets updated more specifically) has to do with how GeckoView packages libxul.so.

The Gecko libraries such as libxul.so and its dependancies are stored in the APK and on launch, some glue code looks in the APKs assets directory for libxul.so and compares it to the one zipped into the APK. If they are different, the glue code unzips the libxul,so into the assets directory. This unzipping of libxul.so delays the registration of the crash reporter signal handler long enough that it happens after Oculus has registered their signal handler.

What isn’t known is who is actually at fault. The problem could be with Gecko’s signal handler or it could be with Oculus. At present we do not have a solution for this problem.

The previous cause of this crash on first run was caused by the GeckoProfile registering a signal handler. If it registered first, every thing worked. If it was second, we got the crash. I worked around it by disabling the signal handler in the GeckoProfile on oculus. We obviously don’t have that option this time.

**Comment by MortimerGoro** [comment]
Already fixed
