### ISSUE TITLE
Finding browser window after exiting Immersive mode can be difficult.

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/FirefoxReality#565]
## Hardware
Oculus Go

## Steps to Reproduce
1. Enter immersive mode on any WebVR site.
2. Turn around to look behind (180deg), hit back button to return back to browser window.

## Current Behavior
After looking at immersive content, looking around, and exiting back to the browser at a different orientation than I started at, I have to "find" my way back to the browser window. Especially using the Void background environment.

## Possible Solutions
- Have browser window "meet" me at my current gaze direction when exiting immersive mode. 
- Guide me back to browser window. Could be some arrows or indicators in the environment or on controller to point me back.
- Provide some kind of gesture that allows the user to easily rotate the world back towards a desired forward orientation.

## Context
I was viewing panos and often found myself looking for the browser window. You can get lost in those things and easily lose your sense of direction!

**Comment by MortimerGoro** [comment]
I think the easiest way is do a reset pose when the user exits VR

`Provide some kind of gesture that allows the user to easily rotate the world back towards a desired forward orientation.`

You can already do that holding the `recenter` button on the remote controller.

**Comment by caseyyee** [comment]
Ah yes, good tip @MortimerGoro.  Doesn't occur to me in the moment though.

**Comment by cvan** [comment]
Samsung Browser shows text after a few seconds of staring at the top:

![image](https://user-images.githubusercontent.com/203725/46850254-111b4600-cda8-11e8-9bd9-8a49d3590de7.png)

Or the bottom:

![image](https://user-images.githubusercontent.com/203725/46850259-18425400-cda8-11e8-90e6-5416624fb159.png)

**Comment by philip-lamb** [comment]
needed-by #635

**Comment by larsbergstrom** [comment]
@gfodor Mentioned that this is one of the biggest things he & the Hubs team would like to see addressed.

**Comment by MortimerGoro** [comment]
I created a PR that resets the pose when the user exits immersive mode #1342. Oculus browser implements the same behavior.

**Comment by jvonitter** [comment]
QA- can you check if this is fixed?

**Comment by Softvision-GeluHaiduc** [comment]
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.4-32352315 installed on the Oculus Go and Quest headset.
Now, when exiting immersive mode the browser window is shown in front of the user.
