### ISSUE TITLE
Prompt users if they want to quit on back button press

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#568]
## Hardware

WaveVR and Daydream
## Steps to Reproduce

1. Launch FxR
2. Press back button on controller

## Current Behavior

FxR exits to device home environment.

## Expected Behavior

FxR should prompt user if they want to exit FxR

## Possible Solution

On the Go, when the user pushed the back button with no more history, it will trigger a system UI asking if the user wants to exit or continue. On the Daydream and WaveVR the user is dumped back into the home env with out prompting which can be annoying when mashing the back button one too many times.

**Comment by keianhzo** [comment]
@nancyhang @thenadj will need design for this

**Comment by philip-lamb** [comment]
On WaveVR and Daydream we should trap and discard any back button presses that would otherwise exit the app, as the UI standard on these platforms is to require the use of the system menu to exit applications.
