### ISSUE TITLE
Google poly doesn't work

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/FirefoxReality#572]
## Hardware
Oculus Go

## Steps to Reproduce
1. Load any Google Poly sketch and click on Goggles.  https://poly.google.com/

## Current Behavior
Nothing is displayed.

## Error Logs and Stack Traces
It works in Oculus Browser, just not in FXR

![image](https://user-images.githubusercontent.com/1560884/46034332-3b38ec80-c0b5-11e8-8f55-fa79cecd1bd4.png)

Nothing of note in the console (AFAIK)

![image](https://user-images.githubusercontent.com/1560884/46034608-e649a600-c0b5-11e8-92ea-4783538c2d1d.png)

**Comment by MortimerGoro** [comment]
Pushed this GV patch to fix this issue: https://phabricator.services.mozilla.com/D6921

**Comment by MortimerGoro** [comment]
BTW found https://github.com/MozillaReality/FirefoxReality/issues/582 while trying Poly on FxR in the go

**Comment by MortimerGoro** [comment]
Gecko PR already merged
