### ISSUE TITLE
Controller touchpad too sensitive

### ISSUE THREAD

**Issue by shang-huang** [MozillaReality/FirefoxReality#576]
## Hardware
HTC Vive Focus

## Steps to Reproduce
Touching / Scrolling on any scrollable web page. 

## Current Behavior
By just put thumb on touchpad will scroll up/down the web page unintentionally.

## Expected Behavior
Scrolling web page from touchpad should be smooth and stable experience.

## Error Logs and Stack Traces
<details open>

```
```

</details>

**Comment by cvan** [comment]
Thanks for filing! Agreed that the scrolling is a bit too sensitive. This was reported in issue #213, and a work-in-progress pull request #428 has been opened. @MortimerGoro: is PR #428 is ready to be merged, or were there issues that were encountered?

**Comment by philip-lamb** [comment]
It looks like the fix in https://github.com/MozillaReality/FirefoxReality/pull/1109 addresses this issue. @cvan Do you concur? If so, let's mark this as fixed.

**Comment by cvan** [comment]
I think this now feels fine with both 3DoF-trackpad/trigger-button- and 6DoF-joystick scrolling. Can we close? Or do we think we need to handle this for 3DoF (Oculus Go) scrolling?

**Comment by philip-lamb** [comment]
#1109 is platform-agnostic, so no other platform-specific work required. I'll close now.

**Comment by cvan** [comment]
This was technically for the touchpad not joysticks, but in testing w/ the Oculus Go controller now, scrolling feels much better.

@shang-huang: could you retry w/ the [latest version of Firefox Reality](https://github.com/mozillareality/firefoxreality#bleeding-edge-developer-apks)? (Or wait until we do a new release to the Oculus Store?) Thanks!

**Comment by shang-huang** [comment]
Tested on HTC Vive Focus, I suppose the scrolling is pretty good now.

As I don't currently have other devices with me now, you may check [video](https://youtu.be/0Gl2W19K5zI) to see if its comparable to other platform(s).
