### ISSUE TITLE
Error with build - Wave VR

### ISSUE THREAD

**Issue by huggzer** [MozillaReality/FirefoxReality#58]
I want to install the build on HTC Focus but I meet some errors when I built irt with Android Studio.
First the function onCrash() must be override in three classes in the project but it was easy to fix.
My main problem was with an error relative to the compilator I think. The error file is joined here.
I was really enthusiastic to use this app and I'm a beginner in android development so I hope it's an obvious beginner error.
[ErrorBuildAndroidFocus.txt](https://github.com/MozillaReality/FirefoxReality/files/2098309/ErrorBuildAndroidFocus.txt)

**Comment by bluemarvin** [comment]
The onCrash() problem was a breaking change to the gecko view library. We should have a fix uploaded soon. For building for Wave, it looks like you do not have the WaveVR SDK properly installed. Did you follow the directions in the README for "If you want to build FirefoxReality for WaveVR SDK"?

**Comment by huggzer** [comment]
Yes of course I copied with the cmd prompt wvr_client.aar and build.gradle in folder third_party/wavesdk that I created first. Now in this folder I have lots more files in. After reading error message I wonder if it's concerned the CMake and maybe a wrong version of it.
For information I use WaveVR SDK 2.0.37 and CMake 3.6.41.

**Comment by bluemarvin** [comment]
Versions seem correct. I noticed you are building on Windows. I don't have a windows machine and don't believe we have ever tried building with that platform. What I find strange is it is finding the header wvr_types.h where things like WVR_EventType_OutOfWall are defined but not resolving all of the enums defined in that header.

**Comment by bluemarvin** [comment]
Okay, I noticed you are using, 2.0.37, we are using 2.0.32 Wave SDK. That is probably the issue. I'll update SDK soon.

**Comment by huggzer** [comment]
Ok ! I want to use FirefoxReality soon and I didn't find the old version 2.0.32 of Wave SDK on the web, it's possible to share me your develop version of the SDK ?

**Comment by bluemarvin** [comment]
I have pushed the update to use 2.0.37 Wave SDK. Please give that a try.

**Comment by huggzer** [comment]
Thanks for all, it's works with your update !
