### ISSUE TITLE
Different WebVR size in Google poly on first EnterVR

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#582]
## Steps to Reproduce

1. Go to https://poly.google.com/view/2oXBHPiAaeg
2. Enter VR 
3. WebVR is blurry
4. Exit and Enter VR
5. Much better quality

## Error Logs and Stack Traces
Printed Gecko::WebGLContext setDimension calls, it looks like the correct 2048x1024 size is changed by some reason. On the next EnterVR the final size is the correct one: 2048x1024

```
SetDimensions 0x976e9400: 300 150
SetDimensions 0x976e9400: 800 150
SetDimensions 0x976e9400: 800 450
SetDimensions 0x976e9400: 2048 450
SetDimensions 0x976e9400: 2048 1024
SetDimensions 0x976e9400: 2048 1024
SetDimensions 0x976e9400: 2048 1024
SetDimensions 0x976e9400: 800 1024
SetDimensions 0x976e9400: 800 450
```

I don't think that this happens on all the pages but we should check

**Comment by philip-lamb** [comment]
Possible interaction with #955.

**Comment by bluemarvin** [comment]
#955 is a UI bug and probably has no relation to this issue.

**Comment by bluemarvin** [comment]
It looks like Poly doesn't support WebVR/WebXR any more.
