### ISSUE TITLE
Listing not showing up in Daydream immersive store

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#583]
<img width="999" alt="360" src="https://user-images.githubusercontent.com/475847/46103691-174dd780-c197-11e8-96ec-4f775e0a4635.png">

It looks like we need to add a 360 pano to our store list and request for a listing *beyond* just the Google Play Store listing we already have.

https://developers.google.com/vr/distribute/daydream/

**Comment by keianhzo** [comment]
@larsbergstrom BTW, if we are going to finally support clip-in (We are currently available in the Playstore for clip-ins) we should handle the permission requests properly: 
> When making the transition to 2D, your app must do the following:
> 
> Prompt the user to remove their phone.
> Detect the orientation change to portrait to switch over to 2D.
> Return the user to nearly the same state in VR that they were in before they removed their phone.

https://developers.google.com/vr/distribute/daydream/design-requirements#UX-D9

**Comment by cvan** [comment]
Comments (as expected) about FxR in Daydream Google Play store: https://www.reddit.com/r/daydream/comments/9umqw7/mirage_solo_as_a_webbrowsing_device/

**Comment by philip-lamb** [comment]
@brianpeiris contributed photospheres here. Waiting on @larsbergstrom to note whether store listing has been updated.

**Comment by larsbergstrom** [comment]
Next step (per internal thread) was to reach out to the release management team contact I mentioned to see if the panosphere worked with the Google Store, since we do not have access and cannot test ourselves. Let me know if you need help with pushing on that!

**Comment by philip-lamb** [comment]
Need to recapture with updated branding.

**Comment by jvonitter** [comment]
Will ask @slightlyoffbeat to help with branding too

**Comment by brianpeiris** [comment]
For future reference, here's the method I used. The capture part is an ugly hack though, so I'm not sure I'd recommend it, unless someone who actually knows how to write C++ and Java code implements a better version of it.
1. I hacked in some code to capture cubemap faces directly from FxR: https://github.com/brianpeiris/FirefoxReality/commit/52c22caef79004d53bc58bfe091f7e31ff531a10 This code is outdated now.
2. I built and ran that on a Galaxy Tab S3 tablet (this was the only way I could figure out to render FxR properly, and at the required resolution)
3. I took the resulting cubemap face images and ran them through [a script](https://github.com/brianpeiris/FirefoxReality/blob/52c22caef79004d53bc58bfe091f7e31ff531a10/process-360.ps1) with ImageMagick and this cubemap-to-equirectangular tool https://github.com/PaulMakesStuff/Cubemaps-to-Equirectangular

This capture method might be worth it if the goal is to generate a stereoscopic capture, but if you're only interested in a monoscopic panorama, you might be better off faking it by photoshopping the FxR UI on top of a cube map face and then generating a panorama. There are probably also other professional art tools to help composite and generate panoramas like this. Photoshop could have that ability built-in for all I know.

**Comment by slightlyoffbeat** [comment]
@brianpeiris want to try running that script again with the attached photo? Let me know if it doesn't work.

![negz](https://user-images.githubusercontent.com/2030656/58834824-27ad3080-8609-11e9-81f5-e6bc7ae9cfd1.jpg)

**Comment by brianpeiris** [comment]
here you go
top/bottom:
![final](https://user-images.githubusercontent.com/79419/58835656-6643ea80-860b-11e9-9a7b-d42afab74cdc.png)
monoscopic:
![pythonOutput](https://user-images.githubusercontent.com/79419/58835658-6643ea80-860b-11e9-912a-87d30f308bb5.png)

**Comment by brianpeiris** [comment]
Those are in PNG format by the way. You may want to convert them into optimized JPGs if that matters.

**Comment by jvonitter** [comment]
This was the image we needed to add:
![offworld2](https://user-images.githubusercontent.com/48839872/62169314-c63dd100-b2dc-11e9-81e9-cc90aa110eac.png)

Also updated the app icon with new branding. All assets can be found here: https://drive.google.com/open?id=1QFEtKkx0U00jrxtDh_neGaM37WHQHmPc
