### ISSUE TITLE
Can't use browser on Oculus Go without Oculus touch controller present

### ISSUE THREAD

**Issue by jdm** [MozillaReality/FirefoxReality#584]
## Hardware
Oculus Go

## Steps to Reproduce
1. Make the Oculus Go controller unavailable
2. Pair an Xbox One controller with the Go
3. Use the Xbox One controller to successfully interact with the stock Oculus browser
4. Try to use the Xbox One controller to interact with Firefox Reality

## Current Behavior
The gaze tracking cursor disappears when entering FxR. 

## Expected Behavior
The gaze tracking cursor appears in FxR and pressing buttons on the gamepad causes interactions to occur with the browser.

## Possible Solution
DeviceDelagateOculusVR::UpdateControllerID explicitly disregards any enumerated controller that is not ovrControllerType_TrackedRemote.

## Context
I'm trying to experiment with FxR but I forgot to bring the controller with me while travelling. The replacement gamepad is not allowing me to continue experimenting with the browser.

```
```

</details>

**Comment by nancyhang** [comment]
We will support the accessibility controllers, but not gazing support

**Comment by bluemarvin** [comment]
@emstanley I think we can close this. We will probably never support this configuration especially now that the Go has been discontinued.
