### ISSUE TITLE
Add an unhandled exception handler.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#592]
## Hardware

All

## Current Behavior

Any unhandled java exception will crash the application.
## Expected Behavior

FxR should have an unhandled exception handler to report these issue.

## Context

The current crash reporter in GeckoView no longer handles Java crashes from unhandled exceptions. FxR needs to catch these unhandled exceptions and report them back to mozilla so that the defects causing the exceptions may be fixed.

**Comment by cvan** [comment]
I'm sure you've seen these already:

- https://github.com/mozilla-mobile/focus-android/wiki/Crash-Reporting-with-Sentry
- https://wiki.mozilla.org/Firefox/BrowserErrorCollection#Access_to_Collected_Errors

we have a `Social Mixed Reality` team on Mozilla's self-hosted Sentry instance, which is currently used for Hubs and the Unity WebVR Assets projects. we should probably [request](https://wiki.mozilla.org/Firefox/BrowserErrorCollection#Access_to_Collected_Errors) a new, separate team for `Firefox Reality`.

**Comment by bluemarvin** [comment]
The plan is to look into adding Sentry in addition to the current crash reporting. However this will require taskcluster integration and a lot of testing. So I've pushed it off until the 1.1 cycle. The goal is to get some coverage now and fill in the holes before 1.1 ships.
