### ISSUE TITLE
FxR is unable to load locally stored files

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#594]
## Hardware

All
## Steps to Reproduce

1. Upload an HTML file to `/sdcard`
2. Attempt to open file in FxR with the path `file:///sdcard/somefile.html`

## Current Behavior

FxR reports access denied.
## Expected Behavior

FxR should prompt the user for permission then open the file.
## Possible Solution

FxR needs the user to grant permission to access local files. Currently FxR doesn't not prompt the user and requires that they grant permission from the system UI. Just like the microphone prompt, users should be prompted for this permission.

**Comment by keianhzo** [comment]
@bluemarvin This is GeckoView issue, it should send PermissionDelegate request so the app can handle the permission grant but it's just returning an error page. I've filed a GeckoView bug to track this: https://bugzilla.mozilla.org/show_bug.cgi?id=1495688

**Comment by bluemarvin** [comment]
I spoke with @snorp before I filed and he wasn't sure if it was a GeckoView issue. His though was we would watch the onLoadUri() for file:/// and prompt the use for the permission since it isn't a web permission but something that should be up to the app? I don't know that he had a strong feeling one way or the other. @keianhzo Do you feel it should be a GeckoView feature? Also READ_EXTERNAL_STORAGE is part of the manifest already. If you go into the app settings and give FxR storage permissions, FxR can load file:/// url right now. It just requires you to manually flip the switch out side of the app.

**Comment by keianhzo** [comment]
@bluemarvin ok, I see the permission in the merged manifest, it's coming from the Google SDK Base. I get what @snorp says and it makes sense, it's not a permissions required by the page itself but by the request. I'm happy to implement this in FxR directly.

**Comment by bluemarvin** [comment]
I think implementing locally in FxR is the right call for now.

**Comment by keianhzo** [comment]
Gecko requires a sync response for LoadRequest but user prompting (permission explanation dialog) is a sync flow so the user sees the default Gecko response (error page) while still granting the permission. If Gecko handled this permission through the PermissionDelegate the load request could be hold until the user grants/rejects the permission. 

Another option is to grant permission upon uri load but that has another implications like having permissions handling code around SessionStore and duplicated permissions related code in loadUri and reload.

I've made two PRs for this so we can choose the best approach but I really think the best way would be to GeckoView to handle this. Any thoughts @snorp ?

**Comment by snorp** [comment]
> Gecko requires a sync response for LoadRequest but user prompting (permission explanation dialog) is a sync flow so the user sees the default Gecko response (error page) while still granting the permission.

`onLoadRequest` is an asynchronous API. You have to return a `GeckoResult<Boolean>` immediately, but it does not have to be completed until later. See the docs for `GeckoResult` here: https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoResult.html

> If Gecko handled this permission through the PermissionDelegate the load request could be hold until the user grants/rejects the permission.

We can't really do this any better than the app can, unfortunately. The benefit I see to leaving the permission prompt to the app is that it knows exactly *why* it's prompting the user. If GV sends a request to the `PermissionDelegate` itself, the app loses that context.

**Comment by keianhzo** [comment]
@snorp Thanks that's helpful
