### ISSUE TITLE
Consider removing clip-in support from Daydream store?

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#598]
Just wanted to test the waters here - we'd only accidentally enabled clip-in support in the Daydream store, and I'd like to propose removing it. Reasons:
- There are very few users
- Is totally untested for product usage and has a ton of one-off bugs
- Does not have a smooth user workflow for enabling the device

The backup here is that people can use the Sideload instructions on the wiki if they are developers (who are the main people I'm concerned about leaving behind with this change).

Note that it would still be available for use on the Lenovo Mirage AIO, as was originally intended.

Thoughts? 

cc @bluemarvin @avrignaud @MortimerGoro @keianhzo

**Comment by larsbergstrom** [comment]
Related issue to the prompts:
https://github.com/MozillaReality/FirefoxReality/issues/583#issuecomment-426299847

**Comment by avrignaud** [comment]
I'd agree - we prioritized and tested standalone headsets, and aren't seeing many users (at all) on the clip-ins. Also, the Pixel1 isn't a suitable device due to perf, which is causing some additional confusion in market.

**Comment by nancyhang** [comment]
Will reach out to Ritu to turn the clip-ins support off. We will support standalone Daydream

**Comment by larsbergstrom** [comment]
This is done. Thanks, @nancyhang!

**Comment by RangerMauve** [comment]
Hi, I think it would be useful to have this mentioned somewhere in the README so that people won't be as confused when they can't install it on their Android phones.

Would a PR for the README update be welcome?

**Comment by avrignaud** [comment]
Please, feel free! Thank you!
-- 
Andre Vrignaud — Head of Mixed Reality Platform Strategy | Emerging
Technologies | Mozilla
avrignaud@mozilla.com | +1 (206) 245-6067 <%2B1.206.245.6067> | Skype:
andrevrignaud
