### ISSUE TITLE
Set the correct text for the keyboard enter button

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#60]
Set the correct text for the keyboard enter button based on the IME type of the textbox (done, go, search, etc.)

**Comment by keianhzo** [comment]
Is there any reason why we haven't used the standard Android Keycodes for the custom keyboard? Like Enter being -4 instead of the Android standard 66.

**Comment by MortimerGoro** [comment]
We are using the one defined in Keyboard.KEYCODE_DONE.

I think that the key is more DONE instead of enter. Example: when you are filling a form on each item the DONE key should do a next, but the enter key sends the form even if you have not completed all items.

**Comment by keianhzo** [comment]
Waiting for https://bugzilla.mozilla.org/show_bug.cgi?id=1474902 to be fixed in Gecko.

**Comment by keianhzo** [comment]
Asked GV team for when is this going to be addressed.

**Comment by larsbergstrom** [comment]
I believe that we will not address this for V1, but can live with it until V1.1.

**Comment by keianhzo** [comment]
@larsbergstrom yep, doesn't look like the GV has prioritized it yet. @bluemarvin do you think that we could have that one triaged at some point?

**Comment by avrignaud** [comment]
@bluemarvin Do we have any update on whether GV has been able to unblock this? Thanks!

**Comment by bluemarvin** [comment]
I'll have to ask.

**Comment by nancyhang** [comment]
Following up on this.

**Comment by cvan** [comment]
It sounds like we can wait until after v1.1. When the new internationalised keyboards land, this will be more important.

**Comment by philip-lamb** [comment]
This is now fixed in the GV we already have in-tree. @MortimerGoro Is it worth trying to land this before we freeze v1.2?

**Comment by MortimerGoro** [comment]
@philip-lamb I'll do a quick test. There should be a few lines of code.

**Comment by philip-lamb** [comment]
Fixed in #1175
