### ISSUE TITLE
Browser window fails to update after recovering from a child process crash when e10s is enabled

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#610]
## Hardware

All
## Steps to Reproduce

1. enable e10s
2. open `about:crashcontent`

## Current Behavior

Session is restarted but the browser window no longer updates.

## Expected Behavior

Browser window should be updated.

## Possible Solution

It isn't clear if this is an FxR bug or a GeckoView Bug. Recovering from a content process crash seems to work with the GV example application but the usage is a little different.

blocked by #451

**Comment by larsbergstrom** [comment]
Unless we get e10s enabled (https://github.com/MozillaReality/FirefoxReality/issues/680) this bug will need to remain in the backlog.

**Comment by philip-lamb** [comment]
No longer reproducible with FxR v1.2.3. Will close.
