### ISSUE TITLE
Add support for modal dialogs

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#611]
## Hardware
All

## Steps to Reproduce
1. Go to Settings
2. Open Developer Options
3. Click on Reset button at the list bottom
4. The Restart dialog shows
5. Click outside the Developer Panel

## Current Behavior
The restart dialog dissapears

## Expected Behavior
The restart dialog should be modal and only close if a decision is made by the user

## Possible Solution
Add support for modal dialogs and dim the background when a modal dialog is shown.

## Error Logs and Stack Traces
<details open>

```
```

</details>

**Comment by MortimerGoro** [comment]
I agree that when we want a dialog it should be modal, but for permissions I'm concerned about the practical usage of using modality

When I visit some pages normally I don't care about the localization permission unless it's a map or something very specific. The modal permission dialog sometimes interrupts the browsing experience. If you see the permission prompt in Oculus Go, it's just a small box that doesn't interrupt the browsing and I think that it even autohides if you don't click on it.

IMO doing something like that would be more practical

**Comment by keianhzo** [comment]
@MortimerGoro yep, that makes sense, I've updated the description to refer to the Restart dialog

**Comment by jvonitter** [comment]
@keianhzo do we still need this? Close if not
