### ISSUE TITLE
Review UI widgets popup handling while in Immersive mode

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#613]
## Hardware
All

## Steps to Reproduce
1. Open an immersive site that requests a permission

## Current Behavior
N/A

## Expected Behavior
Immersive mode should be paused a dialog should be shown and the user should go back to immersive mode after allowing/rejecting.

## Error Logs and Stack Traces
<details open>

```
```

</details>

**Comment by larsbergstrom** [comment]
@keianhzo Are you planning to work on this for 1.1, or should we punt to 1.2? Thanks!

**Comment by keianhzo** [comment]
@larsbergstrom This is definitely a v1.2

**Comment by philip-lamb** [comment]
Duplicates #264.

**Comment by philip-lamb** [comment]
@keianhzo Did you have a test site which displays this issue?

**Comment by keianhzo** [comment]
@philip-lamb @mortimer You can test it with this page: https://codepen.io/keianhzo/project/full/XvgYNr (just click to trigger an alert). At the moment when a dialog is shown during immersive mode it takes the user out of immersive mode but the immersive mode doens't exit correctly and keeps on freezing from that moment on. 

This issue happens with any dialog that is shown during an immersive session (all prompts and permissions ATM), not only the permission ones. Short term action could be to exit immersive mode correctly and show the dialog and let the users decide if they want to go back to immersive. 

This might not be a critical bug for prompt dialogs as I don't think they are that common in XR experiences but it might affect sites that request permissions.

**Comment by keianhzo** [comment]
@philip-lamb After further research it seems that this is related to a Gecko bug https://bugzilla.mozilla.org/show_bug.cgi?id=1565268 It seems that Gecko doesn't exit immmersive mode correctly after the JS execution has been paused ie. triggering any prompt dialog like an alert.

**Comment by jvonitter** [comment]
punting this until we have a real world use case

**Comment by philip-lamb** [comment]
Hey, actually we're going to need to fix this for correct WebXR implementation, since with WebXR we are required to correctly support mid-session permission prompts, and based on this report, these are currently broken. Target will be 1.5.x. It's blocked on the Gecko bug, but fixing that bug will have to be high on  Kip's list on his return.

**Comment by jvonitter** [comment]
needed by #690
