### ISSUE TITLE
Controller does not have linearAcceleration or angularVelocity in pose.

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/FirefoxReality#615]
## Hardware
Oculus Go

## Steps to Reproduce
1. Navigate to https://github.com/toji/webvr.info/blob/master/samples/XX-vr-controllers.html

## Current Behavior
No linearAcceleration or angularVelocity in pose present.

**Comment by philip-lamb** [comment]
Verified that these quantities are present in Oculus Browser and absent in FxR v1.1.2.
