### ISSUE TITLE
English keyboard redesign

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/FirefoxReality#620]
## Hardware
Go

## Steps to Reproduce
1. Click URL bar
2. Enter a IP address

## Current Behavior
It takes way more key presses than should be required. 
We need to solve for the constant shifting and cursoring needed to entering common url's and strings.
`# _ - = ! ? / + @ % :` are all very commonly used and should be available. Some of these require shifting twice to get to.

## Possible Solution
Add a numeric keys to the top row so you don't have to shift the keyboard between letters and numbers to enter addresses and strings. Also add commonly used symbols, at most 1 shift away, but ideally none. We are not limited by screen real-estate in VR. We should use this to our benefit.

**Comment by keianhzo** [comment]
Another alternative is to add specific keyboard layouts for different input types. We currently have assigned symbols1 for numeric and the standard qwerty for the rest. We could add more keyboard variants for other input types like URL, Phone, Email, etc.

**Comment by larsbergstrom** [comment]
@keianhzo Do we need to look at this for 1.1?

**Comment by keianhzo** [comment]
@larsbergstrom This would require a new keyboard spec, not sure we have design & dev room for this in 1.1, I'd just keep it backlogged for 1.2.

**Comment by caseyyee** [comment]
@thenadj Thanks!  Also another one is the "-", which we come across a lot in URL's.  eg: 
"eff.com/spot-the-surveillance" is a recent one that frustrated me recently.

Given that we have so much "screen" real estate (unlike mobile), I don't see why we need to _shift_ out the keyboard when we have the space to work with.

**Comment by thenadj** [comment]
@caseyyee Yep, '-' is already on our radar for top level symbols. And we agree on number layout in three rows rather than top level row. Thx for your feedback!! We are in the final steps of putting recommendations together and I'll share them with the team soon.

**Comment by philip-lamb** [comment]
https://trello.com/c/VLsCI8iC/35-uis-6-english-keyboard
