### ISSUE TITLE
Zoom-in effect when waking FXR from headset sleep

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/FirefoxReality#621]
## Hardware
Oculus Go

## Steps to Reproduce
1. Open FXR
2. Take headset off
3. Return to headset back into FXR

## Current Behavior
Seconds after re-entering headset with FXR, I get a zoom-in effect. Very uncomfortable. Unsure if this is a Oculus or FXR issue.

## Expected Behavior
Gently bring user back into FXR, avoid the zoom-in effect.

## Possible Solution
Paint a black frame on sleep, fade back into FXR nicely when returning to headset.

**Comment by jdm** [comment]
I've seen this frequently and it's quite uncomfortable.

**Comment by joshmarinacci** [comment]
Lots of people on the /r/OculusGo have complained about this in all apps. I think it's a bug that Oculus introduced in the latest firmware update, not an FxR specific thing.

**Comment by nancyhang** [comment]
It's a bug on Oculus. Nothing we can do on our end.

**Comment by avrignaud** [comment]
Closing since it's an Oculus issue.
