### ISSUE TITLE
Strings need localization comments

### ISSUE THREAD

**Issue by Delphine** [MozillaReality/FirefoxReality#625]
We need to kick-off localization work this week in order to meet the desired timeline for launching Firefox Reality in a number of locales.
Something we will need in order to kick-off this work, is getting localization comments for strings here (preferably avoiding technical jargon): 
* https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/main/res/values/strings.xml)
* https://github.com/mozilla-mobile/android-components/blob/master/components/browser/errorpages/src/main/res/values/strings.xml
(let me know if there are other strings elsewhere that are needed that I may not be aware of)

Here are guidelines for writing localization notes: https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices#Add_localization_notes

I would be great to get comments in for each string. I can review that once it's done. let me know if you have any questions about this.

In the meantime, I'll be going through each string and checking for any specific issues that would need to be fixed.
(also, CC @Pike)

**Comment by bluemarvin** [comment]
I'll take a first pass at this to get it going.

**Comment by Delphine** [comment]
Thanks!
Heads-up that for android components strings needed, I filed an issue here: https://github.com/mozilla-mobile/android-components/issues/1057

**Comment by bluemarvin** [comment]
We are currently only using the telemetry android-component which is not user facing so I don't know that we are block by them yet.

**Comment by Delphine** [comment]
Are we sure you don't need those for v1.1? Manuel Martin mentioned that they were needed to Pike the other day on Slack, so want to make extra sure.

**Comment by bluemarvin** [comment]
That may be true. @keianhzo Do you know what android components we are planning to use for 1.1 that are user facing and will require l10n?

**Comment by Delphine** [comment]
In the meantime, I've gone through the strings and here are some comments that may be helpful:
* There are a few instances where "Firefox Reality" appears as a variable (%1$s) in the string, and others when it's actually spelled out
* "Web" is spelled with a capital "W" in one place and with a lower case in the other
* [Straight quote here]([https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/main/res/values/strings.xml#L68]) should be curly quote, like it is in the other occurrence

**Comment by bluemarvin** [comment]
I created a PR with what has been created so far (It's slow going). I will continue adding more notes tomorrow. @Delphine if you could look at what I have so far and let me know if I'm on the right track that would be helpful as I've never created LOCALIZATION NOTEs before. Thanks.

**Comment by Delphine** [comment]
@bluemarvin Seems like our messages crossed :) 
Sure thing, I can take a stab at this a bit now.

**Comment by bluemarvin** [comment]
@Delphine We are not currently using the android-components error pages. But we do have our own and I believe the strings can be found in this file: https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/main/res/values/localpages.xml

@cvan and @keianhzo please correct me if I'm wrong.

**Comment by cpeterso** [comment]
We might be able copy some of existing localized strings from Fennec in the Errorpages component. Here are Fennec's string IDs:

https://searchfox.org/mozilla-central/source/mobile/locales/en-US/overrides/appstrings.properties

**Comment by cvan** [comment]
@bluemarvin that is correct

**Comment by jonalmeida** [comment]
> Delphine We are not currently using the android-components error pages. But we do have our own and I believe the strings can be found in this file: https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/main/res/values/localpages.xml
> 
> cvan and keianhzo please correct me if I'm wrong.

@bluemarvin I see where we got our [`strings.xml`][0] for error pages from now. :) @keianhzo had already added these for us into A-C which was released in version 0.26, and we're hoping to get those strings localized soon so we can add them into the next release. We could also potentially release a minor version of a-c mid-sprint if we get our localized strings sooner.

Hope that provides some context.

See https://github.com/mozilla-mobile/android-components/pull/1071 as well.

[0]: https://github.com/mozilla-mobile/android-components/blob/master/components/browser/errorpages/src/main/res/values/strings.xml

**Comment by keianhzo** [comment]
@jonalmeida that's right, I just commented on that on another issue #642. I have a local branch waiting for the URI patch to be released to be merged in FxR but I'm going to land it and update A-C in a follow up for the URI patch.
