### ISSUE TITLE
Reduce aliasing in lines/borders in the UI

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#629]
This was reported from twitter:
https://twitter.com/VRDesktop/status/1050276301578223616

@bluemarvin Pointed out that the aliasing/jaggies in the UI in the headset may be less about the underlying surface and more about the thickness of some of the lines.

## Hardware
Oculus Go

## Steps to Reproduce
1. Load the browser
2. Look at the thin white lines/borders

## Current Behavior
A bit jaggy/aliased.

## Expected Behavior
Not jaggie/aliased

## Possible Solution
Thicken a bit?

**Comment by thenadj** [comment]
@bluemarvin We're aware of this issue. Is there a recommended line thickness we should use? Or should we get rid of the lines all together. The reason we added the lines was for better visibility across different background colors.

**Comment by thenadj** [comment]
We're working on a design where we remove all white outlines in the chrome. It will be in UIS-21. Working on it later this week or early next week.

**Comment by thenadj** [comment]
We ended up removing the 1px white outline which was only there in the first place for AR. But we actually have a completely different color scheme for AR now. This is ready for review. 

[UIS-21 Window w Controls Below & Thumbnails_012.pdf](https://github.com/MozillaReality/FirefoxReality/files/2515872/UIS-21.Window.w.Controls.Below.Thumbnails_012.pdf)

**Comment by thenadj** [comment]
@keianhzo 
[UIS-21 Window w Controls Below & Thumbnails_013.pdf](https://github.com/MozillaReality/FirefoxReality/files/2536977/UIS-21.Window.w.Controls.Below.Thumbnails_013.pdf)
Adding UIS-21 for 'Suggestions Bar' UI specs.

**Comment by larsbergstrom** [comment]
Fixed in https://github.com/MozillaReality/FirefoxReality/pull/703
