### ISSUE TITLE
Selecting language for voice input

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#634]
We have some design choices around voice input for multiple languages, the initial backend implementation of which is landing in: #633 

The question is: can the user change the language? I could imagine a few choices:
1) Only allow voice input/search against the current OS language used by the device
2) Change the keyboard/microphone input UX/UI to allow selecting the language (as one might select a different language keyboard for input)
3) Provide some affordance in settings for changing the overall UX/UI language for Firefox Reality

Opinons/feedback? The first option seems easiest, but I assume this (especially the third) might also intersect with other work we are doing.

**Comment by bluemarvin** [comment]
Since both Oculus and Wave are custom android builds, we need to verify that Android even returns the correct region. Once we have a way to select region/language how do we test this? It would seem that we would need some level testing and verification for the languages we want to support in FxR.

**Comment by larsbergstrom** [comment]
Good point! And based on @andrenatal's comment (https://github.com/MozillaReality/FirefoxReality/pull/633#issuecomment-430342927), it sounds like we'll basically need to dump all the locales for *each* platform and then map to the codes in the voice backend regardless (almost like we had to do for search codes). Fun...

**Comment by keianhzo** [comment]
Oculus seems to get the Locale configuration of the phone is linked to but only when it's setup after a factory reset otherwise you can't seem to change it. 

I agree with @andrenatal that sometimes even your device is in a language you'd like to voice search in a different one. In Android phones there is a Google setting that let's you choose which languages are going to be used for voice search. I guess we can't do that right @andrenatal? I'd add a setting and would also make it accessible from a voice search panel setting button for faster language switch.

**Comment by larsbergstrom** [comment]
@keianhzo Do we need some design work for this feature? Totally agree that we should probably make this available as a feature.

Also, do we have a sense for which languages we will support here? Just all of them that we support under the hood?

Thanks!

**Comment by larsbergstrom** [comment]
I looked at the Oculus Go, btw, and couldn't figure out how to change the system language without a factory reset :-/

**Comment by thenadj** [comment]
We'll add this to settings and a way to scale for however many languages we support. Design is in progress now.

**Comment by keianhzo** [comment]
@larsbergstrom I need to check with @andrenatal which languages are currently supported as his latest commit was only en_US, not sure if that has changed. Will ping him.

**Comment by thenadj** [comment]
[DE-10 Settings_005.pdf](https://github.com/MozillaReality/FirefoxReality/files/2516659/DE-10.Settings_005.pdf)

Take a look at the updated diagram in DE-10. The idea is to give users a lot of control to independently choose voice search language, FxR system language and keyboard. 

The diagram shows a list of sample languages based on they keyboards we have currently queued up but that list is not final. Who will be able to give us a final list?

Also, is multiple language support for voice search possible? I could see a use case for users who speak multiple languages but not a must have. 

Please take a look and send feedback.

**Comment by andrenatal** [comment]
Hey @keianhzo. You can see all the languages we support here:

https://github.com/mozilla/speech-proxy/blob/master/languages.json

**Comment by keianhzo** [comment]
@thenadj @larsbergstrom It seems that we have a bunch of languages available. The API only provides a single language method so I guess it's only one atm. @andrenatal can you confirm that?

**Comment by andrenatal** [comment]
Hi @keianhzo 

The API contains a method called setLanguage() which receives a language code [1] as a parameter.  You can pass any of the codes listed in the json [2]. If you pass something different, it will return an error. If you pass nothing, it will default to English. 

We'll work out on documentation for the next versions.  


[1] https://github.com/MozillaReality/FirefoxReality/pull/633/files#diff-c67859727feb619c98a0f682bb897281R213

[2] https://github.com/mozilla/speech-proxy/blob/master/languages.json

**Comment by thenadj** [comment]
Here is the updated version of the diagram. Languages list is not complete. Can someone please share a complete list with me for Voice Search and FxR Languages?
[DE-10 Settings_005.pdf](https://github.com/MozillaReality/FirefoxReality/files/2520139/DE-10.Settings_005.pdf)

**Comment by larsbergstrom** [comment]
With UI languages, we will support:
Korean
Japanese
Spanish
German
Italian
French
Chinese (Mandarin/Traditional) [Taiwan, though don't use that word in UX/UI]
Chinese (Mandarin/Simplified)

and of course
English

The JSON file above lists _additional_ languages that we could support in voice, but I think that the above list will be sufficient for now. Unless there's some pushback from others that we should support *all* the speech proxy languages in the UI, too, right now? It feels (to me) like a nice 2019 feature to add, along with pointing to community opportunities to help localize the app for languages we're not currently going to contract out for commercial localization.

**Comment by andrenatal** [comment]
Just out of curiosity: what is reasoning behind the choice of these
languages?

I can help localizing the UI for portuguese. That would be another 200
million. It's a bummer to not have the app you work on localized to your
own mother tongue.

**Comment by larsbergstrom** [comment]
@andrenatal I am 💯 totally open to and want more languages! The only reasoning for the choice of the initial ones is that it's a contractual minimum bar we need to have in place for some business-related stuff and so these are the ones we're explicitly contracting for translation.

If you can help with Portuguese, I'd love to see it there! Lemme connect with you Monday with our localization team for instructions on what needs to be done. I *think* it's literally just one file of strings that has to be translated and put in the right spot (and all of the normal locale selection, etc.).

**Comment by keianhzo** [comment]
@thenadj @larsbergstrom How are the "Voice Search Language" and "FxR Language" settings going to work? We default to the system locale language by default and let the user override it?

**Comment by thenadj** [comment]
@keianhzo Starting with system defaults seems like the simplest user experience and then giving the user control by changing things in settings empowers them to customize the languages.
