### ISSUE TITLE
Zhuyin Keyboard for Taiwan

### ISSUE THREAD

**Issue by thenadj** [MozillaReality/FirefoxReality#640]
We need a Zhuyin keyboard for users in Taiwan.

**Comment by thenadj** [comment]
Attached are the files from Nick, our Taiwanese UX designer. We need a native speaker to review this and send feedback to Nick this week if possible. @daoshengmu

**Comment by thenadj** [comment]
[UIS-52 Zhuyin Keyboard-1_Nick.pdf](https://github.com/MozillaReality/FirefoxReality/files/2485464/UIS-52.Zhuyin.Keyboard-1_Nick.pdf)
[Uploading UIS-52 Zhuyin Keyboard-2_Nick.pdf…]()

**Comment by daoshengmu** [comment]
@thenadj I only can open the file, `UIS-52 Zhuyin Keyboard-1_Nick.pdf`. It looks ok. I just have some questions as below:

1. We should make the mic icon be fixed to a position for all different keyboard layouts. Voice input will take its important role in FxR, we need make users know where it is intuitively.
2. I am not sure if it is possible to use VR controllers to do handwriting in a VR scene. The design is good, I am just concerned its availability. We can consider to start this work later.
3. Regarding to the `universe icon`, users usually use it to choose input type. It seems like we let users use this key to switch from `Full-Key`, `Dynamic`, `Hand Writing`? Furthermore, we can consider merging `英文` and `注音` two keys to be a key as a switch.
4. I don't know why we have an `emoji` key at the bottom line. Is it just one key or it would switch to another keyboard layout? It seems like this key is replaceable.
5. I also aware we have no universe key when using dynamic keyboard that will make users get trouble in getting back.
6. I also interested in how to show the expand view and its position. If we give it a big rectangle it will cover the background and our 2D browser. Probably, a strip style would be a considerable solution.

**Comment by daoshengmu** [comment]
Regarding to UIS-52 Zhuyin Keyboard-2_Nick.pdf, we need to adjust the the second layout of **Dynamic mode**. The space key should be `一聲`, and the bottom key should be `二 三 四聲` instead of `三 四 二聲`

**Comment by thenadj** [comment]
Attached is the updated Zhuyin Keyboard with all latest feedback incorporated. 

[UIS-52 Zhuyin Keyboard_Nick_1023-1.pdf](https://github.com/MozillaReality/FirefoxReality/files/2515847/UIS-52.Zhuyin.Keyboard_Nick_1023-1.pdf)
[UIS-52 Zhuyin Keyboard_Nick_1023-2.pdf](https://github.com/MozillaReality/FirefoxReality/files/2515848/UIS-52.Zhuyin.Keyboard_Nick_1023-2.pdf)

**Comment by keianhzo** [comment]
I've been taking a look at the Oculus Browser and Samsung Internet and Samsung doesn't provide Chinese keyboards and Oculus provides a Cangjie keyboard. Cangjie seems to compose an ideograph based on different parts that you type in a reduced symbols keboard and after several symbols have been introduced they are replaced by the resulting ideograph. It seems the simpler (to implement) Chinese input method what's makes sense in a browser as you are usually going to type only a few words not a full text and you can fit all the required symbols in the same layout as a qwerty.
I think they might be using their own dictionary for Cangjie autocompletion as the system input type is en_US by default and you can't change it (edited)

**Comment by daoshengmu** [comment]
@keianhzo I am curious how you enable the Cangjie keyboard. I was trying to switch my Oculus Go language setting to Chinese but didn't see any changes about the input type.

**Comment by keianhzo** [comment]
The only way of changing the Oculus Go language is changing your linked device language and performing a Factory Reset in the Go, otherwise you are stuck with the last language.

In the Oculus browser you can use the Cangjie keyboard doing:

![keyboard1](https://user-images.githubusercontent.com/837184/48028761-3c702700-e101-11e8-9a1b-62a360c9835d.png)
![keyboard2](https://user-images.githubusercontent.com/837184/48028767-3f6b1780-e101-11e8-8c4d-9f844cf5bcfe.png)
![keyboard3](https://user-images.githubusercontent.com/837184/48028770-409c4480-e101-11e8-9046-9b9e11328196.png)

But correct me if I'm wrong, I can be easily wrong.

**Comment by daoshengmu** [comment]
@keianhzo  The one you choose is Korean, I have confirmed it with a Korean nearby. It seems like you don't need to change the system language setting, you also can see the Korean input type in Oculus browser's keyboard. Oculus Go's Android is customized, so I am not sure if it provides other input methods. Vive Focus does already provide Simplified Chinese language with Pinyin input method, we can find in their browser.

**Comment by keianhzo** [comment]
@daoshengmu but even in the case it's Korean do you have any idea of how they manage to to ideograph completion? Even if I don't change the system locale they are completing the Korean ideographs as you type but I didn't seem to make that work in FxR.

As you said Oculus Go Android is customized and you can't do Android standard things as changing the input type you are stuck with whatever keyboards the app provides so there must be some way they are providing ideograph autocompletion, maybe some external library. 

For Samsung Internet they don't even provide Asian keyboards.

**Comment by cvan** [comment]
:+1: solid work. done in PR #1161. see @daosheng's open follow-up PR #1173. if there are any additional enhancements, please file. thanks!
