### ISSUE TITLE
Speech/Voice Input Permissions 

### ISSUE THREAD

**Issue by thenadj** [MozillaReality/FirefoxReality#641]
We need to add a dialog to ask users for permission to collect speech/voice data. 

From Andre:
"Mozilla would like (with user permission) to collect and process anonymous user voice samples to improve our voice recognition models. In order to do so we need to implement UI to explain to users what we will do with their voice, and allow them to opt in (and opt-out later if they change their mind).

Possible UI needs include:

    A button in settings that turns on/off sending voice data to Mozilla (default off)
    a way to prompt user the first time they try the voice icon to agree to sending voice data to Mozilla to improve our services - and explain that they can continue to use voice search even if they do not wish to share data with us"

**Comment by thenadj** [comment]
Please review design and implement if ok. 
[UIS-60 Speech&Voice Input Permissions_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2485479/UIS-60.Speech.Voice.Input.Permissions_001.pdf)

**Comment by MortimerGoro** [comment]
- Do we need to point to some "Terms of conditions" or "Privacy" URLs if they want to get more info?

**Comment by keianhzo** [comment]
Should it be possible for the user to revert that setting via the settings dialog somehow same as we are doing for crash reporting?

**Comment by keianhzo** [comment]
@thenadj @avrignaud Regarding @MortimerGoro's question: Do we need add links to "Terms of conditions" or "Privacy" URLs to this dialog in case the user wants to get more info? 

Also we might need design for the "Report Speech Data" panel from here: https://github.com/MozillaReality/FirefoxReality/files/2516659/DE-10.Settings_005.pdf

**Comment by avrignaud** [comment]
No, I do not think so - that's covered in the overall FxR privacy policy.

**Comment by thenadj** [comment]
Attached is the updated UI spec with new the new and more consistent visual style. 
[UIS-60 Speech&Voice Input Permissions_002.pdf](https://github.com/MozillaReality/FirefoxReality/files/2535559/UIS-60.Speech.Voice.Input.Permissions_002.pdf)

**Comment by jvonitter** [comment]
The design for this is done! See https://trello.com/c/EzXFnuvg/219-uis-60-speech-voice-input-permissions

**Comment by jvonitter** [comment]
closed this by mistake. repoening

**Comment by jvonitter** [comment]
Design is ready to review and implement: https://trello.com/c/U4TNMHWf/364-uf-67-speech-permissions
We're not doing a UIS / spec for this since it uses only standard dialogs.
I'm following up with legal to get the correct text for the dialogs. Use the placeholder text in the document for now.

**Comment by jvonitter** [comment]
Final spec is done! https://trello.com/c/U4TNMHWf/364-uf-67-speech-permissions

**Comment by jvonitter** [comment]
@keianhzo One thing we didnt discuss previously - we should make it so we dont keep collecting data during private browsing (even if they have the setting turned on). I'll follow up on getting the language updated to reflect that too.

(cc: @larsbergstrom )

**Comment by keianhzo** [comment]
@jvonitter This is under review now, let me know when the text is ready to update it.

**Comment by jvonitter** [comment]
The text might take a little while. Go ahead and use what's in the spec and I'll make a new issue if we need to change anything

**Comment by keianhzo** [comment]
@jvonitter ok, we can update that in a follow-up.

**Comment by jvonitter** [comment]
@andrenatal heads up!

**Comment by andrenatal** [comment]
Code looks good! I'll test this Thursday with @jvo to see if the samples are arriving properly to the server

**Comment by jvonitter** [comment]
Voice data review attn @harraton 
[datareview-voice.txt](https://github.com/MozillaReality/FirefoxReality/files/3580054/datareview-voice.txt)
