### ISSUE TITLE
Make Error pages localizable

### ISSUE THREAD

**Issue by Delphine** [MozillaReality/FirefoxReality#642]
So I've had a few conversations with a number of people, and I get different information on what needs to be localized for error pages.

Seems like you guys have Error pages here: 
* https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/main/res/values/localpages.xml
but then there's also Android-Components here:
* https://github.com/mozilla-mobile/android-components/blob/master/components/browser/errorpages/src/main/res/values/strings.xml

The Android-Components ErrorPages need to be localized no matter what, so since that's the first info I got (ie., that it was also needed for Reality), we started working on making it localizable. The work is, I believe, basically done (they fixed strings and added localization comments).

My question is: since these strings are basically the same, could you backport this work here? Isn't the plan to use a-c across mobile products as much as possible anyways?
If we can't do that, I'll open another issue and the same work will have to be done on the localpages.xml

also CC @pike

**Comment by Delphine** [comment]
> So I've had a few conversations with a number of people, and I get different information on what needs to be localized for error pages.
> 
> Seems like you guys have Error pages here:
> 
>     * https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/main/res/values/localpages.xml
>       but then there's also Android-Components here:
> 
>     * https://github.com/mozilla-mobile/android-components/blob/master/components/browser/errorpages/src/main/res/values/strings.xml
> 
> 
> The Android-Components ErrorPages need to be localized no matter what, so since that's the first info I got (ie., that it was also needed for Reality), we started working on making it localizable. The work is, I believe, basically done (they fixed strings and added localization comments).
> 
> My question is: since these strings are basically the same, could you backport this work here? Isn't the plan to use a-c across mobile products as much as possible anyways?
> 
> also CC @Pike

**Comment by keianhzo** [comment]
@cvan The current error pages strings in a-c browser-errorpages is  coming from a PR that I made a few weeks ago committing the work I did for FxR error pages so the strings.xml in a-c is basically the same as in FxR.

I made another PR to fix a required URI parameter that has already landed in a-c and I have a local branch with the error pages migration to a-c waiting for a new a-c version to be released so we can move all the error pages code to a-c. Still we'll need to keep the html/css code as the a-c base html is different than the ones @caseyyee did for FxR

So until the new a-c release is ready the string.xml fixes need to go both to localpages.xml and  to https://github.com/mozilla-mobile/android-components/blob/master/components/browser/errorpages/src/main/res/values/strings.xml
components/browser/errorpages/src/main/res/values/strings.xml

The private browsing code+ strings refactor to a-c was cut from my original PR so we still need to keep that in FxR (localpages.xml + InternalPages.java)
