### ISSUE TITLE
Google Play listing localizations

### ISSUE THREAD

**Issue by Delphine** [MozillaReality/FirefoxReality#645]
Checking-in if you will be needing to localize the [Google Play listing](https://play.google.com/store/apps/details?id=org.mozilla.vrbrowser&hl=en_US) for Firefox Reality, in view of its localized launch for 1.1.
A few questions/comments:
* what's the priority for this work to be localized for v1.1?
* by what date would you need this back by?
* we typically don't update the What's New message on GP for mobile projects, since it takes time and doesn't really scale at this point (also, not many apps localize it). It's also not something users tend to look at. I would like to suggest if we do localize the Google Play listing, that the What's New message be a generic one (what we currently do for Focus Android, Focus iOS, and Fennec for example)
Let me know!
(also CC @gueroJeff since he'll be covering up for me Monday)

**Comment by jvonitter** [comment]
Hi @Delphine! Yes, we would like to localize the store listing. I agree we should make the text generic so that it doesn't need frequent updates. Timing is flexible, but before 7/1 is ideal.

**Comment by Delphine** [comment]
Hi Janice! Thanks for reaching out.
Since the time that I opened this bug, we have changed the way we handle these requests. To give you a summary:
Since 2019, Stores (iOS/Android) localization requests don't go through community anymore. You can check out [our localization SLA mana doc](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=66651657) for more info on how we manage localization requests. For some quick background, we created this SLA in order to better streamline and standardize the localization requests we receive throughout the org.
If you wish to proceed with this translation work, we can have it translated through an agency. Someone will then have to manually upload it to the store. This is what we've done with the Lockwise project recently, for example.
Just a heads-up that the budget comes out of your department for these kind of requests.
Also, please provide a list of languages.
Thanks!

**Comment by bluemarvin** [comment]
Closing since we are no longer in the Google Play Store.
