### ISSUE TITLE
Creating localized test builds

### ISSUE THREAD

**Issue by Delphine** [MozillaReality/FirefoxReality#647]
Once localization work is completed for v1.1, testing phase will roll-out and will require localized builds to test on.
I'm thinking the best option would be that once localizations are back in your repo, that these builds get automatically updated on a daily basis (so, "Nightly builds") - so that every time we make a correction, we can verify it the next day (fwiw this is what we have for other mobile projects as well).
The agency needs to test localizations on device, so providing builds via APK will be the easiest, I believe.
We started talking about this with @bluemarvin and @nancyhang via email thread, but probably easier to track and prioritize this via GitHub issue :)
EDIT: something I forgot to mention is that testers will no have headsets, so will have to be testing in 2D mode

(also CC @pike and @gueroJeff)

**Comment by philip-lamb** [comment]
Given that we currently have binaries from each build of master, this might be just a matter of making them easier to find.

**Comment by Pike** [comment]
Yeah, I agree.

**Comment by philip-lamb** [comment]
Fixed in #1172
