### ISSUE TITLE
STRs for testing strings

### ISSUE THREAD

**Issue by Delphine** [MozillaReality/FirefoxReality#648]
The agency asks for STRs in order to be able to pull up strings - and so they can properly test the localization work they provide. I've been speaking about this with @keianhzo and @nancyhang over the week, so here's an issue to make this official, as well as more easily discoverable. 
(also, CC @pike and @gueroJeff)

**Comment by cvan** [comment]
For reference:

The notes for each L10n string now live on the Wiki: https://github.com/MozillaReality/FirefoxReality/wiki/L10n#stringsxml

**Comment by Delphine** [comment]
Thank you so much! :)
