### ISSUE TITLE
Infinite restart loop on startup crashes

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#651]
## Steps to Reproduce
- Easy to test by creating a startup crash  (e.g. a error in `navigation_bar.xml`)

## Current Behavior
- Infinite restart loop

## Expected Behavior
- Try some times but not forever

## Possible Solution
- Detect the number of consecutive crashes and stop restarting the app after some threshold.

**Comment by cvan** [comment]
@MortimerGoro opened PR #1202. per @bluemarvin the code change is blocked on https://github.com/MozillaReality/FirefoxReality/pull/1202#issuecomment-492024166.

**Comment by MortimerGoro** [comment]
Already fixed in #1202
