### ISSUE TITLE
The latest download apk file?

### ISSUE THREAD

**Issue by psiba** [MozillaReality/FirefoxReality#655]
Is the latest version of the apk this
'public/FirefoxReality-1.0.1-22960936-noapi-arm-debug.apk'
thanks in advance

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by nancyhang** [comment]
@psiba Are you referring to the staging or release build?

**Comment by nancyhang** [comment]
The latest release build is on the readme. 

We just released 1.01 and it's on the Google Playstore, Oculus and Viveport, for standalone devices only.
