### ISSUE TITLE
URL bar hover

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#67]
Set the right hover styles and text selection colors for the URL bar

**Comment by keianhzo** [comment]
Same as #140

**Comment by thenadj** [comment]
I am not sure how this is related to 140? This issue is about adding interaction states to the URL bar. See attached PDF. 

[Bug-7 URL Bar Interaction_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2212135/Bug-7.URL.Bar.Interaction_001.pdf)

**Comment by keianhzo** [comment]
Sorry @thenadj I pointed to the wrong issue, fixed it. it was #223
