### ISSUE TITLE
Tray doesn't indicate private icon on when restoring a private mode session

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#671]
Also the background is not dimmed. It seems that the tray didn't receive the listener in that case.

## Steps to Reproduce
1. Open FxR and switch to private mode
2. Click back and exit the browser
3. Reopen it again from the Oculus Library

## Current Behavior
- Private session correctly restored
- Tray icon not enabled
- Background not dimmed

## Expected Behavior
- Tray private mode icon enabled
- Background dimmed

**Comment by cvan** [comment]
A few comments to add about the status here:

- There are several issues around Private Browsing state. The key goal: **make it more obvious that the user is in a Private-Browsing session**. (Keep in mind that when Tabs are added after v1.1, there will be more elegant ways to address this.)
- If you test entering Fullscreen from a YouTube video, you can see a bug with the opacity (it gets lighter than the dim of Private Browsing).
- There's a PDF of the design spec for this in issue #774: https://github.com/MozillaReality/FirefoxReality/issues/774#issue-381784473
- To whomever works on these issues: Feel free to do the work in #774 and/or #671. Or if there are follow-up issues to be filed, we can do that as well.

Thank you in advance for all the polish here! :+1:
