### ISSUE TITLE
Browser window is missing for ~5 seconds (upon browser launch on fresh install)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#673]
## Hardware
Oculus Go

## Steps to Reproduce
1. Run `adb uninstall org.mozilla.vrbrowser`
2. Clone `master`
3. Open the project in Android Studio
4. Run `Build`
5. Run `Run`
6. Watch as Firefox Reality loads

## Current Behavior
[**Watch Video**
![screenshot of missing window](https://user-images.githubusercontent.com/203725/47541465-2c994d00-d88e-11e8-84fc-1dc317f4f88b.png)](https://drive.google.com/file/d/1Z3j57fCc_0Hov-bEAvsUIZl5dOjrn9y4/view?usp=sharing)

<hr>

(Let me know if I should file three separate issues if these items are unrelated. Apologies in advance.)

1. Upon a fresh install, the browser window has gone missing, but it reappears when the document is ready.
2. The back + forward buttons in the chrome are delayed until the document is ready. That confused me. And I thought the browser was laggy/broken.

## Expected Behavior
1. Upon a fresh install, the window appears even before the document is ready.
2. The back + forward buttons in the chrome should respond immediately to a user's click instead of waiting for the document/navigation state to finish change.

**Comment by MortimerGoro** [comment]
This also happens to me in some local compilations. 

I think it's because GeckoView the first time unzips and copies some assets (e.g. libxul.so)

**Comment by cvan** [comment]
This appears fixed now. I can't repro anymore as of yesterday with recent local builds (or release, signed versions from the Oculus Store.

**Comment by cvan** [comment]
Seeing this again on Taskcluster dev builds.

**Comment by keianhzo** [comment]
This got fixed recently in GV and shouldn't happen anymore.

**Comment by cvan** [comment]
I have not seen it in the past few days. If I do not see it by EOD, I will close. Thanks for the update!

**Comment by cvan** [comment]
Verified fixed. Thank you all!

**Comment by avrignaud** [comment]
I saw this just yesterday afternoon, after having to manually delete FxR using ADB for some reason.  Downloaded new build from store, and it occurred.

**Comment by bluemarvin** [comment]
That's because the store build still has the issue.

**Comment by cvan** [comment]
> Downloaded new build from store, and it occurred.

It is reproducible in 1.1 (the version in the store) but not on master. So two days: f4868c7be5d0c9da750405814dce09de34674ced

**Comment by avrignaud** [comment]
Ah, of course - that makes sense. Awesome!
