### ISSUE TITLE
Fading between skybox textures

### ISSUE THREAD

**Issue by nancyhang** [MozillaReality/FirefoxReality#678]
Backlogged from JIRA.

**Comment by cvan** [comment]
Is this for when custom environments or changed? Or something else?

**Comment by keianhzo** [comment]
I think this was for when we wanted to transition between day and night skyboxes when going into Private Browsing mode but we finally decided to just dim.

**Comment by nancyhang** [comment]
@thenadj  Will there be another design for fading between skybox textures? Or is the dimming the final design?

**Comment by thenadj** [comment]
@nancyhang For the time being it will just be dimming. In the future when we have more time we can explore nicer transitions.
