### ISSUE TITLE
Video canvas can not be used as a texture in WebGL on Android with e10s enabled

### ISSUE THREAD

**Issue by nancyhang** [MozillaReality/FirefoxReality#680]
Reported by @bluemarvin 

Web sites like https://www.panomoments.com/ that use a video canvas as a texture source in WebGL fail to render and display as black when e10s is enabled. This is likely causes by the fact that SurfaceTextures can only be consumed by a single OpenGL context. This probably works in the non-e10s case because the SurfaceTexture is attached to the WebGL context first.

https://bugzilla.mozilla.org/show_bug.cgi?id=1486659

**Comment by philip-lamb** [comment]
Fixed in Geckoview currently in our tree. Performance implications of this being handled elsewhere.
