### ISSUE TITLE
Fix jit-tests on Android ARM64: Jit1-Jit10

### ISSUE THREAD

**Issue by nancyhang** [MozillaReality/FirefoxReality#681]
Reported by @cpeterson:
Bob is standing up testing on real Android devices. One of the test suites he have running is the jit test on Pixel 2 devices running Android 8.0 using 64bit builds as a Tier 3 job.

These are running as Tier 3 on mozilla-central, mozilla-inbound, autoland and try. Before we can begin to promote these tests to Tier 2 or Tier 1, we must get them to pass.

https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&filter-searchStr=jit&filter-tier=1&filter-tier=2&filter-tier=3

3 chunks perma fail: Jit5, Jit6 and Jit10

https://bugzilla.mozilla.org/show_bug.cgi?id=1475648

**Comment by philip-lamb** [comment]
ARM64 ION JIT meta bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1187093

**Comment by philip-lamb** [comment]
Closing as duplicate as JS performance issues tracked elsewhere.
