### ISSUE TITLE
Media API proposal for GeckoView

### ISSUE THREAD

**Issue by nancyhang** [MozillaReality/FirefoxReality#684]
Reported by @MortimerGoro 

I created this bug to discuss the Media API we want to include in GeckoView.

Some context: On Firefox Reality we need a way to control playing media in addition to know some media events and metadata. This is required because a lot of 360/180 video websites (or just a raw video) do not have a WebVR player. Browsers are getting around this by allowing the user to map the video onto a sphere or half sphere and while the video is playing the controls are warped as well. So to allow the user to still control the video, they are given an external controller with play/pause/stop/volume setter and a playback seek bar. Standalone Oculus, Chrome and Samsung browsers have this capability.

Attached you can find a proposal for the GeckoView Media API.

https://bugzilla.mozilla.org/show_bug.cgi?id=1498246

**Comment by larsbergstrom** [comment]
This is in progress and @MortimerGoro is working on this tracking issue.

**Comment by MortimerGoro** [comment]
Already landed
