### ISSUE TITLE
Show directory listing at file:///sdcard/

### ISSUE THREAD

**Issue by nancyhang** [MozillaReality/FirefoxReality#685]
Reported by @keianhzo 

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.54 Safari/537.36

Steps to reproduce:

- Grant READ_EXTERNAL_STORAGE permission
- Load the URI: file:///sdcard/

Actual results:

There are onPageStart and onPageStop callbacks but no web content is loaded.

Expected results:

a) Show a directory listing for the directory (Fennec behavior)
b) Return a ERROR_FILE_NOT_FOUND error

https://bugzilla.mozilla.org/show_bug.cgi?id=1498270

**Comment by caseyyee** [comment]
Talked to @snorp. This is a GeckoView bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1498270
