### ISSUE TITLE
Add an API for enabling draggable scrollbars

### ISSUE THREAD

**Issue by nancyhang** [MozillaReality/FirefoxReality#687]
Reported by @bluemarvin 

In user testing for FxR, a top complaint was that scroll bars were not drag able. It would be useful to have a setting that enabled desktop style scrollbars in GeckoView.

https://bugzilla.mozilla.org/show_bug.cgi?id=1480906

**Comment by caseyyee** [comment]
Closing for https://github.com/MozillaReality/FirefoxReality/issues/317
