### ISSUE TITLE
Enable WebXR 1.0 by default in release

### ISSUE THREAD

**Issue by nancyhang** [MozillaReality/FirefoxReality#689]
Reported by @kearwood 

Once the WebXR 1.0 spec has stabilized and our implementation is ready (tracked in meta bug 1419190), we should flip the flag to enable this by default.

https://bugzilla.mozilla.org/show_bug.cgi?id=1419206

Github meta issue: https://github.com/MozillaReality/FirefoxReality/issues/690

**Comment by kearwood** [comment]
We are ready to turn this on for FxR 10 on Android.

We need to flip the dom.vr.webxr.enabled flag to true.

**Comment by bluemarvin** [comment]
Fixed by #2521
