### ISSUE TITLE
[meta] Implement WebXR 1.0

### ISSUE THREAD

**Issue by nancyhang** [MozillaReality/FirefoxReality#690]
Reported by @kearwood 

This is a meta bug to track implementation of the "WebXR 1.0" API.  Please set this as a dependency for any bugs that relate to the implementation, testing, and shipping of WebXR 1.0.

The next generation Web API for VR, AR, and MR devices to supersede WebVR has been tentatively named "WebXR 1.0".  This was previously referred to as "WebVR 2.0".

New features should be added to the WebXR API; however, the existing WebVR API will continue to be supported for existing content.

The WebXR API will be first implemented behind a pref, which will be disabled by default.  Disabling or enabling this pref will not affect the functionality of the existing WebVR 1.1 API which will continue to be supported.

Until the spec has been finalized, it will remain disabled by default and breaking changes are expected to land.

https://bugzilla.mozilla.org/show_bug.cgi?id=1419190

needs #689

**Comment by philip-lamb** [comment]
Parent of #689

**Comment by jvonitter** [comment]
needs #2062

**Comment by philip-lamb** [comment]
needs #2095

**Comment by kearwood** [comment]
Needs #2237

**Comment by daoshengmu** [comment]
Needs #2389

**Comment by MortimerGoro** [comment]
#2458 would be nice to fix

**Comment by bluemarvin** [comment]
@kearwood  I think we can close this?

**Comment by bluemarvin** [comment]
@kearwood I'm closing this since we shipped WebXR in v10.
