### ISSUE TITLE
gfxVRExternal needs to record telemetry for FxR

### ISSUE THREAD

**Issue by nancyhang** [MozillaReality/FirefoxReality#691]
Reported by @kearwood 

The Firefox Reality browser (FxR / Crow) will use gfx/vr/gfxVRExternal to enable the interfaces to the hardware to be implemented within the android project, outside of mozilla-central.

The various headsets implemented outside mozilla-central will need to be tracked separately in telemetry.

https://bugzilla.mozilla.org/show_bug.cgi?id=1462712

**Comment by philip-lamb** [comment]
This is implemented in our current telemetry since v1.0.
