### ISSUE TITLE
Refactor crash service to A-C lib-crash component

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#692]
## Hardware
All

## Current Behavior
We have a custom implementation for the native crash handling service and global exception handler. 

## Possible Solution
Now it exists and Android Component providing this functionality. We should migrate to it so all Mozilla products use the same crash handling implementation and consolidate all the crash handling code in that component.

## Context
We are currently using Socorro for both Native and Java crashes, lib-crash uses a multiple service approach currently supporting both Socorro (Native only) and Sentry (Native and Java) crash reporting services.

We still will need to contribute a main update: Add an option to always give the app a chance to handle the crash for all fatal and non-fatal so FxR has a change to show a crash reporting dialog. The current android standard activity based show prompt implementation is not an option in FxR.

## Error Logs and Stack Traces
<details open>

```
```

</details>

**Comment by philip-lamb** [comment]
https://github.com/mozilla-mobile/android-components/blob/master/components/lib/crash/README.md

**Comment by bluemarvin** [comment]
@keianhzo Do we still want to do this?

**Comment by keianhzo** [comment]
I'd say so. The lib-crash service already has support for several crash reporting service including Socorro.
