### ISSUE TITLE
Infinite redirect opening Youtube video with the Desktop UA

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#693]
STR:
- Select desktop UA
- Open Video: "https://www.youtube.com/watch?v=sPyAQQklc1s"
- Infinite redirect

video:

[redirect.mp4.zip](https://github.com/MozillaReality/FirefoxReality/files/2531585/redirect.mp4.zip)

**Comment by cvan** [comment]
This is no longer an issue with the UA Override (issue #488).
