### ISSUE TITLE
Bad youtube quality

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#694]
Youtube only provides a `640x360 `quality on FxR using the default UA. I tested with https://www.youtube.com/watch?v=sPyAQQklc1s which supports much better qualities on desktop. This is a **blocker for 360** videos because `640x360` is really bad.

Youtube doesn't show a quality selector on FxR but it does on Oculus Browser.

Oculus Browser uses a mobile VR too (tested via https://whatsmyua.info/). I wonder if they automatically switch to desktop on Youtube pages to get the quality selector and support for the maximum qualities. Another possibility is that YouTube is UA sniffing and  sending better pages to Chrome UA. Native Android Webview doesn't show the quality selector though.

**Comment by caseyyee** [comment]
OK, so did some sleuthing around. Here's what I found.

It seems like the video quality is possibly held down to a low resolution based on window size being returned: 

With Oculus browser:
![image](https://user-images.githubusercontent.com/1560884/48149645-7eb87600-e271-11e8-848f-6c98695588ac.png)

In standard windowed mode, `window.innerHeight` returns 450, fullscreen mode: 585 and when running in 360 projection, it returns 1440.

This makes sense to me that Youtube will run to the maximum window size if the connection speed supports this. This is also reflected by the fact that the video quality setting is set to HD1440.  Additionally, you can see that it takes 30 or 40 seconds for Youtube to improve its stream quality when entering the 360 modes.

For FXR:
![image](https://user-images.githubusercontent.com/1560884/48149830-f8e8fa80-e271-11e8-9327-e43c5dfba656.png)

Standard window mode: 450, window resized to as large as i could get it: 900, but remains 450 in fullscreen.

Also checked `window.devicePixelRatio` and both browsers returned 1.

Based on this, I would try to adjust window sizing to a higher resolution and see if Youtube will appropriately adjust the resolution and quality.

Below is some screen shots of the video Debug info that is available on the Youtube player in FXR. (top right > 3 dot icon > Copy Debug Info) Interestingly, i can't seem to find the UI for it in Oculus browser or desktop for that matter.  The only interesting tidbit is the `optimal_format; 360p` which is the quality we are getting back from Youtube player.

![youtube](https://user-images.githubusercontent.com/1560884/48150318-25e9dd00-e273-11e8-9a6c-9261e5458d4e.png)

**Comment by MortimerGoro** [comment]
I tried a bigger window size (1080p IIRC) and it didn't make any effect. But it's worth it to test again because we have a different UA now. 

`optimal_format; 360p` seem usefull, I'll send that info to webcompat

**Comment by caseyyee** [comment]
Tried to edit window size but couldn't in developer settings.  See https://github.com/MozillaReality/FirefoxReality/issues/734

**Comment by caseyyee** [comment]
We have been experimenting with a modified UA as per https://github.com/MozillaReality/FirefoxReality/issues/488 and have confirmed that we can get nicer 1080p+ playback in 360 using it. The other important part to this is that we do need to increase the window size when in 360 mode as well.

See comment in https://github.com/MozillaReality/FirefoxReality/issues/748#issuecomment-438471813 for details on window sizing.

**Comment by caseyyee** [comment]
Fixed with https://github.com/MozillaReality/FirefoxReality/pull/777
