### ISSUE TITLE
updateCursorAnchorInfo callbacks not received after requestCursorUpdates

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#699]
We need the cursor updates callback to be able to position the keyboard at an specific location on screen based on the currently focused text field.

https://bugzilla.mozilla.org/show_bug.cgi?id=1500059

**Comment by philip-lamb** [comment]
@bluemarvin  bugzilla bug is currently unassigned but possible  we'll need this for keyboard positioning (#636) for v1.2.

**Comment by MortimerGoro** [comment]
@philip-lamb I think we can remove this from v1.2. It will only be needed when we want to move it in  relation to text field. @jvonitter mentioned to start with a fixed location for now and validate & refine later https://github.com/MozillaReality/FirefoxReality/issues/636

**Comment by jvonitter** [comment]
we not going to move in relation to the text field
