### ISSUE TITLE
Change Error and Private Browsing Pages from XHTML to HTML5, add `<meta charset="utf-8">`

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#700]
https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/main/res/raw/error_pages.html and https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/main/res/raw/private_mode.html can be converted from XHTML documents to HTML5 documents.

and add a `<meta charset="utf-8">` to both.

(historically, these came from [`aboutNetError.xhtml`](https://dxr.mozilla.org/mozilla-central/source/browser/base/content/aboutNetError.xhtml), which uses an XHTML document that references external Document Type Definitions (DTDs) for localisation (L10n) strings.)

**Comment by caseyyee** [comment]
Appears fixed https://github.com/MozillaReality/FirefoxReality/pull/710
