### ISSUE TITLE
Allow swappable Y-Axis option for touch pad scrolling

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#705]
## Hardware

Oculus Go

## Steps to Reproduce
Scrolling on touch pad can feel "reversed" to different users depending on their Y-Axis preference. 

## Expected Behavior

User should have option to swap Y-Axis for touch pad scrolling.

## Possible Solution

User should have option to swap Y-Axis for touch pad scrolling.

```
```

</details>

**Comment by cvan** [comment]
Good catch! Good feature request to address. Though vertical scrolling is most common on web pages, I'd expect the scrolling to apply the same for the X-axis. That's what Operating Systems do (the user prefer to reverse the scrolling direction applies for both).

**Comment by cvan** [comment]
I'm suggesting that we don't make a difference between the X or Y axis. We say simply `scrolling direction`.

![image](https://user-images.githubusercontent.com/203725/47945012-4f45ea00-debc-11e8-9bd9-4c4c7722ea1b.png)

**Comment by avrignaud** [comment]
With the context that I'm an oldschool video game guy (including flight sims), I've always found having the two options to be more helpful for me personally? Apple's example works because they have additional context (animation showing it affects vertical scroll - don't think it affects horizontal?) I suspect users would be confused with just a "scrolling direction" option that doesn't give additional context? @thenadj love your thoughts too (but this isn't high priority for 1.1, to be clear).

**Comment by caseyyee** [comment]
Also should have the ability to disable altogether.  I generally use the click-to-drag and the touchpad interferes with scrolling the page sometimes.

**Comment by cvan** [comment]
> Also should have the ability to disable altogether. I generally use the click-to-drag and the touchpad interferes with scrolling the page sometimes.

Heh, I'm very impressed! I'm curious of what percentage of VR users avoid the touchpad as you do with their 3DoF controllers when browsing webpages in their VR browser. (Perhaps we should ask on https://www.reddit.com/r/OculusGo?)

**Comment by MortimerGoro** [comment]
This have been implemented in this PR: https://github.com/MozillaReality/FirefoxReality/pull/984
