### ISSUE TITLE
Firefox Reality latest staging build just flashes start screen over and over

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#708]
## Hardware
Oculus Go

## Steps to Reproduce
1. Install build from https://queue.taskcluster.net/v1/task/VXQARgDYTyqlgBLJcDNDww/runs/0/artifacts/public/FirefoxReality-1.1-23061008-oculusvr-arm-staging-signed-aligned.apk
2. Launch product

## Current Behavior
Loading screen just flashes over and over

## Expected Behavior
Firefox Reality loads.

## Error Logs and Stack Traces
Currently a GeckoView bug; @bluemarvin investigating.

**Comment by joshmarinacci** [comment]
I can confirm that this happens with the signed build but not the debug build.

**Comment by bluemarvin** [comment]
It looks like an autograph issue. We are trying to get a fix ASAP.

**Comment by jvehent** [comment]
We deployed a new version of autograph-edge with a fix. Could you retry signing?

**Comment by bluemarvin** [comment]
Latest staging builds are able to run.
