### ISSUE TITLE
Enable software mp3 decoding in Geckoview.

### ISSUE THREAD

**Issue by joshmarinacci** [MozillaReality/FirefoxReality#709]
## Hardware

Oculus Go

## Steps to Reproduce

1. Load My VR game with music disabled and click play. The game will run ~30fps. https://vr.josh.earth/webxr-experiments/halloween/v2.html
2. Load My VR game with music enabled and click play. The game will run at ~1fps. https://vr.josh.earth/webxr-experiments/halloween/v2_music.html

## Current Behavior

The game is super slow with music turned on. Even if I disable playing the music, the act of loading MP3s into Three.Audio() seems to trigger the bug.

## Expected Behavior

The game should run at the same speed with and without audio.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by larsbergstrom** [comment]
I recall @snorp mentioning this issue, too, back when we were first trying to A-Blast working even in 2D on an android phone. All of the related bugzilla bugs around WebAudio performance have either been resolved or closed as invalid, though, so it's probably worth taking a perf trace (especially if this repros in 2D in normal geckoview on android) and opening a bug.

**Comment by snorp** [comment]
It seems to run fine here on my phone (not in VR). Can you grab a profile? There are some instructions here: https://perf-html.io/docs/#/./guide-remote-profiling

I'm not sure how to enable the devtools from FxR, but maybe @larsbergstrom or @bluemarvin can help with that. I think it's in the settings?

**Comment by cvan** [comment]
Settings > Remote Debugging turn On. Thanks for the profiling instructions!

**Comment by joshmarinacci** [comment]
The WebIDE doesn't have a performance section anymore like in the screenshots, but the connected console view does. I'm assuming it just moved (I'm using Nightly on desktop). I took a profile though it never ended when I pressed the end button. Still I was able to save it. Attached JSON file. (zipped because Github won't let you paste in JSON files).

I can confirm that disabling all audio greatly reduces the initial slowdown. 


[profile.json.zip](https://github.com/MozillaReality/FirefoxReality/files/2700800/profile.json.zip)

**Comment by bluemarvin** [comment]
You should be able to share the perf.io link that has the profile data.

**Comment by joshmarinacci** [comment]
Oh, was this supposed to record and send it to a website? No, it didn't do that.

**Comment by joshmarinacci** [comment]
Perhaps I'm recording it wrong. Here is the demo with audio on

https://vr.josh.earth/webxr-experiments/physics/player.html?AUDIO=true

and with it turned off

https://vr.josh.earth/webxr-experiments/physics/player.html?AUDIO=false

**Comment by joshmarinacci** [comment]
I modified the halloween game to show the problem. https://vr.josh.earth/webxr-experiments/halloween/v2_linear.html

Now it loads the MP3s one at a time.  It actually makes the problem worse. Inside the handlers for each MP3 is a console.log that looks like ‘=== 1’, ‘=== 2’, etc. It takes about 2 minutes for four MP3s to be loaded and ready to play. if you load the page look at the ‘how to play’ button. It will change to ‘done’ when the mp3s are done loading. during the load time the Oculus Go feels sluggish.  So the real question is: what is involved with loading an MP3 on Android / Oculus Go.  I’m assuming we have to decompress the whole file into a buffer before it’s ready to play, but why is that so rough? These aren’t long MP3s. Shouldn't take 2 min.

**Comment by joshmarinacci** [comment]
I modified the halloween game to show the problem. https://vr.josh.earth/webxr-experiments/halloween/v2_linear.html

Now it loads the MP3s one at a time.  It actually makes the problem worse. Inside the handlers for each MP3 is a console.log that looks like ‘=== 1’, ‘=== 2’, etc. It takes about 2 minutes for four MP3s to be loaded and ready to play. if you load the page look at the ‘how to play’ button. It will change to ‘done’ when the mp3s are done loading. during the load time the Oculus Go feels sluggish.  So the real question is: what is involved with loading an MP3 on Android / Oculus Go.  I’m assuming we have to decompress the whole file into a buffer before it’s ready to play, but why is that so rough? These aren’t long MP3s. Shouldn't take 2 min.

**Comment by philip-lamb** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1528341

**Comment by philip-lamb** [comment]
Media team has now enabled ffmpeg's mp3 decoder. Last piece of that work (disabling the Android HW decoder) is tracked in bug https://bugzilla.mozilla.org/show_bug.cgi?id=1583997

**Comment by philip-lamb** [comment]
@joshmarinacci When this work lands, I'll get you to test against Jingle Smash.

**Comment by MortimerGoro** [comment]
@joshmarinacci ready for testing on feature/v6 branch

**Comment by joshmarinacci** [comment]
Is this branch built on taskcluster?

**Comment by joshmarinacci** [comment]
It looks like only master is being built on taskcluster. how do I get branch builds?
https://tools.taskcluster.net/groups/HZXKx5tlQvqg17tCUqx-Qg

**Comment by MortimerGoro** [comment]
Did you click on the green checkmark icon on the commit?

I see the builds from the commit here: https://tools.taskcluster.net/groups/IxLuQeC5SdOcFRW4E4QHng/tasks/IxLuQeC5SdOcFRW4E4QHng/runs/0/artifacts

**Comment by joshmarinacci** [comment]
The performance is better now. Thank you.
