### ISSUE TITLE
investigate Firefox Accounts support

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#717]
Add support for Firefox Account login/pairing

needed-by #549, needed-by #359

**Comment by philip-lamb** [comment]
@cvan Do you know the bugzilla tracking bug for FxA support in GV?

**Comment by philip-lamb** [comment]
Blocks #549

**Comment by cvan** [comment]
@philip-lamb this is now supported in Gecko View and available in `android-components`. see **Accounts** here: https://github.com/mozilla-mobile/android-components/#feature

**Comment by grigoryk** [comment]
`services-firefox-accounts` component is a good starting point:
https://github.com/mozilla-mobile/android-components/tree/master/components/service/firefox-accounts

**Comment by jvonitter** [comment]
Now covered by FxA Project
