### ISSUE TITLE
Support Web Extensions

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#720]

**Comment by Colonel-Izzi** [comment]
#299

**Comment by cvan** [comment]
@Colonel-Izzi: Thank you for pointing that out. Closing this issue as a dupe. And we can continue the discussion in #299, and the progress of WebExtension API support in GeckoView can be monitored from [this list of dependent bugs](https://bugzilla.mozilla.org/showdependencytree.cgi?id=1468844&hide_resolved=0).
