### ISSUE TITLE
investigate send content to device

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#721]
needs #397

**Comment by caseyyee** [comment]
Would love to hear what sort of use cases you're thinking of for this. You mean like a screen cast, or something more basic like link sharing like https://github.com/MozillaReality/FirefoxReality/issues/677?

**Comment by cvan** [comment]
similar issues:
- #373 
- #397

**Comment by philip-lamb** [comment]
Parent of #397.

**Comment by jvonitter** [comment]
Needs user stories, etc

**Comment by jvonitter** [comment]
This is now covered by the FxA project
