### ISSUE TITLE
Support reader mode

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#722]

**Comment by cvan** [comment]
@larsbergstrom by "reader mode," do you mean Firefox Reader View/[_Readability_](https://github.com/mozilla/readability) or a "screen-reader mode"?

**Comment by larsbergstrom** [comment]
@cvan Yes, the former! I specifically meant something like Safari Reader Mode / Firefox Readability for this item.

**Comment by philip-lamb** [comment]
See also https://github.com/mozilla-mobile/focus-android/issues/802

**Comment by cvan** [comment]
🎉 a few weeks ago "Reader Mode" landed in `android-components`:

- https://github.com/mozilla-mobile/android-components/pull/2273/files
- https://github.com/mozilla-mobile/android-components/issues/1346

(discovered this while doing WebCompat work w/ our Web Extension content script.)
