### ISSUE TITLE
Media broken in latest GeckoView (Youtube, Vimeo)

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#726]
STR on Oculus Go:

- Launch FxR, the contend feed shows.
- Type `youtube`on the URL bar so it does a Google search
- Open the youtube page and open any video
- The video doesn't play (also happens in Vimeo)

However, if you **directly open** a youtube URL video (I changed the HOME_URL in code to test it) the video plays correctly

**Comment by larsbergstrom** [comment]
Working now, with the latest build!

**Comment by MortimerGoro** [comment]
Weird, I tried again (after a uninstall) and it works now. Maybe it was an Android Studio problem or something. I'll open it again if we can reproduce it again
