### ISSUE TITLE
Localization of Target Locales

### ISSUE THREAD

**Issue by nancyhang** [MozillaReality/FirefoxReality#729]
Localization of the following target locales:
Simplified Chinese (zh-CN), Traditional Chinese (zh-TW), French (fr), Italian (it), German (de), Spanish (es-ES), Japanese (ja), Korean (ko)

Target locales strings: https://drive.google.com/drive/folders/1_wWZvljcIKS7HyU1s69GU0OpZw1GZkKP?usp=sharing

@keianhzo Can you please help put each of the files in the correct directory?

Once this is done, we will need localized builds for testing.

**Comment by cvan** [comment]
hope this list is helpful:

| Language (English)                            | Language (Native) | Locales matched
|-----------------------------------------------|-------------------|-----------------
| `English`                                     | `English`         | `en-*`
| `Korean`                                      | `한국어 (대한민국)`   | `ko-KR`
| `Japanese`                                    | `日本語（日本）`    | `ja-JP`
| `Spanish`                                     | `Español`         | `es-*`
| `German`                                      | `Deutsch`         | `de-DE`
| `Italian`                                     | `Italiano`        | `it-IT`
| `French`                                      | `Français`        | `fr-*`
| `Chinese, Mandarin (Traditional, Taiwan)`     | `國語 (台灣)`      | `cmn-Hant-TW`
| `Chinese, Cantonese (Traditional, Hong Kong)` | `廣東話 (香港)`     | `yue-Hant-HK`
| `Chinese, Mandarin (Simplified, Hong Kong)`   | `普通話 (香港)`     | `cmn-Hans-HK`
| `Chinese, Mandarin (Simplified, China)`       | `普通话 (中国大陆)`  | `cmn-Hans-CN`

**Comment by Pike** [comment]
I've included the localizations under the following locale codes:

de
es
fr
it
jp <-- that's probably broken
ko
zh-CN
zh-TW
