### ISSUE TITLE
Move BrowserWorld Controller code to its own class

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#73]
BrowserWorld is getting too big. Moving the controller management code to its own class would help make the class a little more manageable.

**Comment by MortimerGoro** [comment]
I'm going to work on this. I need to add some more controller code for resize and yep, we need to better split it into a separate class and methods.

**Comment by bluemarvin** [comment]
Should be pretty straight forward since we already have the ControllerDelegate. What ever you come up with, hopefully it will make it easy to populate the controller part of the shared struct defined in: gfx/vr/external_api/moz_external_vr.h

@kearwood Said he would be working on getting the controller portion stood up so the structs might change. Might want to coordinate with him to ensure a smooth integration? I don't want moz_external_vr.h included outside of ExternalVR.cpp (see my immersive branch) so crow::ExternalVR will eventually need to be expanded to accept input data.

Maybe the new Controller class can have a controller interface that can be passed into ExternalVR?

**Comment by MortimerGoro** [comment]
Done via https://github.com/MozillaReality/FirefoxReality/pull/137 and https://github.com/MozillaReality/FirefoxReality/pull/158/files
