### ISSUE TITLE
FxR Crash in java.lang.NullPointerException: at org.mozilla.gecko.GeckoSystemStateListener.prefersReducedMotion(GeckoSystemStateListener.java)

### ISSUE THREAD

**Issue by nancyhang** [MozillaReality/FirefoxReality#732]
This bug was filed from the Socorro interface and is
report [bp-49bd55ec-aa9c-470c-bea2-1341c0181029](https://crash-stats.mozilla.com/report/index/49bd55ec-aa9c-470c-bea2-1341c0181029).

Java stack trace:

java.lang.NullPointerException
	at org.mozilla.gecko.GeckoSystemStateListener.prefersReducedMotion(GeckoSystemStateListener.java:86)
	at org.mozilla.gecko.mozglue.GeckoLoader.nativeRun(Native Method)
	at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:499)

https://bugzilla.mozilla.org/show_bug.cgi?id=1503075

**Comment by philip-lamb** [comment]
The original bug is reported fixed. @cvan Please test and close if fixed.

**Comment by philip-lamb** [comment]
Closing as no original bug is fixed and merged and no new reports.
