### ISSUE TITLE
google.com loads Desktop version in Private Browsing mode

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#737]
## Hardware
Oculus Go
7c8b949

## Steps to Reproduce
1. Load https://www.google.com/ in Firefox Reality (in normal / non-Private Browsing mode)
2. Notice the site's layout is correct
3. Click the Private Browsing mode
4. Load https://www.google.com/ in Private Browsing
5. Notice the site's layout is different (Google is serving the Desktop instead of Mobile version)

## Current Behavior
[Google](https://www.google.com/) is serving the Desktop instead of Mobile version when loaded in Private Browsing mode.

![image](https://user-images.githubusercontent.com/203725/48231127-12696f80-e362-11e8-8a9f-c1da51c8f9c7.png)

![image](https://user-images.githubusercontent.com/203725/48231139-15646000-e362-11e8-8542-2542d45e96b8.png)

## Expected Behavior
The Mobile version of [Google](https://www.google.com/) is also loaded in Private Browsing mode.

![image](https://user-images.githubusercontent.com/203725/48231143-16958d00-e362-11e8-82c9-617ed88bda8e.png)

**Comment by caseyyee** [comment]
I'm not seeing it either.  Reopen if you see otherwise!
