### ISSUE TITLE
google.co.uk loads as desktop mode instead of mobile-optimised (with new Mobile VR UA)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#743]
## Hardware
Oculus Go
5eeebbe

## Steps to Reproduce

1. Load https://google.co.uk
2. Compare with https://google.com, https://google.ca, etc.

## Current Behavior
![google-uk-desktop](https://user-images.githubusercontent.com/203725/48248056-a7905680-e3aa-11e8-8e33-b166b36e6381.png)

## Expected Behavior
To look like https://google.com, https://google.ca, etc.

**Comment by caseyyee** [comment]
You still seeing this?  I don't think i've encountered it with Google.com, but I have seen language selection on YouTube. Unsure if this is related to https://github.com/MozillaReality/FirefoxReality/issues/786

**Comment by cvan** [comment]
nope! not seeing it anymore. thanks!

**Comment by caseyyee** [comment]
Cool, will close then.  Thanks
