### ISSUE TITLE
Fullscreen mode should present larger window (especially for 2D Videos)

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/FirefoxReality#748]
## Hardware
Oculus Go.

## Steps to Reproduce

1. Goto Vimeo, Youtube or other video service and play a video.
2. Press full-screen option.
3. Note how browser window size remains the same.

## Current Behavior
When viewing videos in Fullscreen mode, the size of the video is the same size as the standard browser window.  I would expect, especially for video content, that the screen becomes larger so that it feels more immersive to view. Currently, only the environment dims down slightly.

Additionally, it would be really great to have options to change the screen aspect ratio to common movie formats ie: 2.35:1

![small-fullscreen](https://user-images.githubusercontent.com/1560884/48386269-33a1c700-e6a6-11e8-9d1c-89e232abea82.gif)

## Expected Behavior
Full-screen mode should present a larger window size so that videos are more immersive. 

"The Empire of C":
https://vimeo.com/channels/staffpicks/299666256

This video really highlights the problems well, fullscreen mode is particularly unsatisfying because of the letterboxing and small relative view. There doesn't seem to be much of a point of full-screen if I can't see content at a larger size.

**Comment by MortimerGoro** [comment]
What size in pixels would you use for fullscreen?

Idea: we can autodetect the aspect ratio for fullscreen videos and adjust it automatically.

**Comment by jenniferhoang** [comment]
Please see UF-18 700. The video will enlarge 1.5x and stay 16:9 (1470x826)

[UF-18 2D Movie Mode_004.pdf](https://github.com/MozillaReality/FirefoxReality/files/2577872/UF-18.2D.Movie.Mode_004.pdf)

<img width="653" alt="screen shot 2018-11-13 at 12 07 52 pm" src="https://user-images.githubusercontent.com/41343760/48440102-d1e06c00-e73c-11e8-874a-ef56b120b962.png">

**Comment by thenadj** [comment]
Based on a meeting this morning with @cvan @jenniferhoang , @fernandojsg, here's what we suggest for a better user experience entering 2D and 360 movies:

+ User navigates to video details page
+ User clicks on play button for video
     (+ Rather than old flow which is very hidden: hover over video, choose full screen mode)
+ User now clicks on play button and FxR automatically detects movie format and puts user either into 2D movie mode or 360 movie mode with FxR transport controls

Pros of this flow are:
+ Intuitive for user to play movies in proper mode (no more hidden "full screen" path to final view)
+ User can still very easily access details page for related video and comments/links

**Comment by thenadj** [comment]
Correction - Scenario from above doesn't work because YouTube auto-plays video upon loading details page! 
Ideally, we'd ask YouTube to NOT auto play videos for VR. Short of that we have a couple of options:
A) Stick with what we currently have which is a bad user experience and prone to not be discovered. The flow goes like this: user chooses video, video auto-plays in details page in browser window, user clicks on full screen icon, FxR auto-detects movie mode and plays video in proper mode.
B) Show a dialog asking the user if they want to enter 2D movie mode, 360 movie mode, etc... with checkbox (do not show this in the future).

**Comment by caseyyee** [comment]
👍 1.5x seems like a reasonable size upgrade.

So we should adjust viewport window sizes to the folllowing:

Regular browser size: 800 x 450
Full-screen browser size: 1040 x 585
3D/VR mode browser size: 2560 x 1440

2560 x 1440 is the Oculus Go native display resolution, but it seems appropriate to set the resolution that would be best optimized for the given device the user is viewing on.

**Comment by thenadj** [comment]
Updated UF-19 to illustrate auto-detection scenario from above. Option A and B. 
[UF-19 360 Movie Mode_003.pdf](https://github.com/MozillaReality/FirefoxReality/files/2578553/UF-19.360.Movie.Mode_003.pdf)


@cvan Is this the correct issue to add the updated UF-19? If there is a different issue, please advise.

**Comment by thenadj** [comment]
Also adding UF-35 which shows a new feature: Video Title.
The title would A) give context for the currently playing movie and B) allow a user to navigate to the video details page even if they get straight to the video via a different path (i.e. direct link from Content Feed). 

This feature is a result of today's meeting with @cvan @fernandojsg and @jenniferhoang - it is ready for review and feedback/approval.

[UF-35 Auto Detection for Video Projection_003.pdf](https://github.com/MozillaReality/FirefoxReality/files/2578574/UF-35.Auto.Detection.for.Video.Projection_003.pdf)

**Comment by thenadj** [comment]
Also adding updated UF-18 to keep all of these related User Flows in one place.

[UF-18 2D Movie Mode_004.pdf](https://github.com/MozillaReality/FirefoxReality/files/2578579/UF-18.2D.Movie.Mode_004.pdf)

**Comment by cvan** [comment]
@MortimerGoro do you think you could chat with @caseyyee on this?

**Comment by MortimerGoro** [comment]
@cvan @caseyyee yest, let's chat today about this

**Comment by MortimerGoro** [comment]
`3D/VR mode browser size: 2560 x 1440`

The size is automatically set to the video size. Otherwise we are resampling the same texture twice for different sizes which is not good

**Comment by cvan** [comment]
Woo! Thank you, @MortimerGoro and @caseyyee, for chatting this through and getting the implementation quickly merged.

If there are loose ends that folks feel are in scope for 1.1, please comment here. Otherwise, for post-1.1 requests, please file issues (or let me know and I can file).

Thanks, everyone!
