### ISSUE TITLE
Keyboard bar should close when chrome/UI buttons are pressed

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#749]
## Hardware
Oculus Go
[`1.0.1`](https://github.com/MozillaReality/FirefoxReality/tree/1.0.1), eaa4fc5

## Steps to Reproduce
1. Press the URL bar to focus it.
2. Press the `Reload` button.
3. Notice the keyboard does not close.

## Current Behavior
The keyboard remains open when a chrome/UI button is pressed.

![image](https://user-images.githubusercontent.com/203725/48389666-669e8780-e6b3-11e8-9840-8293d657b265.png)

## Expected Behavior
The keyboard should automatically close when a chrome/UI button is pressed.

**Comment by caseyyee** [comment]
Yup, works for me.

**Comment by cvan** [comment]
I can verify that this has been fixed. Thank you!
