### ISSUE TITLE
Wrong icon/look with new Resize Mode icons (and in Private Browsing mode)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#750]
## Hardware
Oculus Go
eaa4fc5

## Steps to Reproduce
1. Press the Resize Mode icon (below the URL bar in the bottom-right corner).
2. Notice the new style of the Resize Mode.
3. Press the Private Browsing icon in the Tray.
4. Notice the last icon (the checkmark icon) is curved in non-Private Browsing.

## Current Behavior
in eaa4fc5:
![image](https://user-images.githubusercontent.com/203725/48390230-ceee6880-e6b5-11e8-84ea-596caf2f4974.png)
![image](https://user-images.githubusercontent.com/203725/48390231-d150c280-e6b5-11e8-859c-be01944f14f4.png)

## Expected Behavior
in `1.0.1`:
![image](https://user-images.githubusercontent.com/203725/48389976-b893dd00-e6b4-11e8-9553-f43762af6e41.png)
![image](https://user-images.githubusercontent.com/203725/48389979-bcbffa80-e6b4-11e8-80fa-1cbcd3a91611.png)

**Comment by thenadj** [comment]
Added this to bug https://github.com/MozillaReality/FirefoxReality/issues/480 But also adding it here now. @MortimerGoro @keianhzo @avrignaud @cvan 

The size control in resizing looks off. See attached for what it is supposed to look like. Also in UIS-41.
[UIS-41 Resize Mode_002.pdf](https://github.com/MozillaReality/FirefoxReality/files/2586706/UIS-41.Resize.Mode_002.pdf)
![image](https://user-images.githubusercontent.com/13240857/48576049-5dd2cf00-e8c8-11e8-8d7f-0c7dd0646ddb.png)

**Comment by keianhzo** [comment]
There are two issues here:
- Resize icons styles are not updated when in Private Browsing
- Once you exit from PB the styles are broken.

@avrignaud we should consider fixing this for 1.1 as a P1 maybe? Is quite noticeable and not difficult to fix.

**Comment by cvan** [comment]
I will take this one for 1.1. Thanks!
