### ISSUE TITLE
Rename 'Telemetry' to a more recognisable word in the 'Settings' UI

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#752]
## Steps to Reproduce
1. Load the Settings in the Tray.
2. Notice the word `Telemetry` as an option.
3. That word is not obvious to folks. We should call it `Mozilla Analytics` or something.

## Current Behavior
`Telemetry` is an ambiguous/uncommon word for folks.

![image](https://user-images.githubusercontent.com/203725/48390666-0cec8c00-e6b8-11e8-894d-004cda74ec2d.png)

## Expected Behavior
`Telemetry` should be a clearer word.

## Possible Solution
Rename the `Telemetry` option to read as `Mozilla Analytics` or similar.

**Comment by cvan** [comment]
@larsbergstrom: do you have any ideas for a more obvious name for Telemetry to show in the Settings?

**Comment by larsbergstrom** [comment]
@cvan "Usage data" seems most commonly used in other products, though I am not an expert.

**Comment by caseyyee** [comment]
It's a trust thing, so we should tell users why we're doing this as well.

I'd like it to be along the lines of:
 "Allow Mozilla to collect usage data to help improve the product"

I rather not shorten it, and if we absolutely had to, maybe a tool-tip/hint that gives users the full line.

**Comment by caseyyee** [comment]
While we're here, we should probably also have strings for _Crash Reporting_ as well.

_Send detailed crash reports to Mozilla_  I like the text on desktop FF about what data is sent.  I think it's important to disclose exactly what is inside a crash report.

**Comment by jvonitter** [comment]
needed by #1243

**Comment by jvonitter** [comment]
fixed by #1372
