### ISSUE TITLE
VR video playback mode has artifacts

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/FirefoxReality#754]
## Hardware
Oculus Go
FXR: eaa4fc5

## Steps to Reproduce
1. Goto Youtube and watch any 360 or 180 content.
2. Fullscreen and Select a VR projection mode, you can see this in any of the modes.
3. Notice especially along top and bottom parts of the video, there is a shimmering/stairstepping/distortion effect when viewing the video.

You can see this in the grass of this video, the effect is much more pronounced in-headset:

![video-artifacts](https://user-images.githubusercontent.com/1560884/48444792-ce9fad00-e749-11e8-9b8c-56b11d6b6f7a.gif)

**Comment by MortimerGoro** [comment]
https://github.com/MozillaReality/FirefoxReality/pull/778 fixes this on Oculus.

This artifact didn't happen on the first version (without the layers). So we still need to fix this for the other platforms

**Comment by cvan** [comment]
note: fixed in PR #778 and #853
