### ISSUE TITLE
Issues with loading Facebook 360 Photos

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#756]
## Hardware
Oculus Go

## Steps to Reproduce
TBD (placeholder)

## Current Behavior
TBD (placeholder)

## Expected Behavior
TBD (placeholder)

## Possible Solution
TBD (placeholder)

## Context
- https://facebook360.fb.com/360-photos/
- https://www.facebook.com/help/529997907206001?helpref=faq_content

## Error Logs and Stack Traces
TBD (placeholder)

<details open>

```
```

</details>

**Comment by caseyyee** [comment]
Same issue as detailed in https://github.com/MozillaReality/FirefoxReality/issues/841#issuecomment-441855094
