### ISSUE TITLE
Unknown Youtube 360 mode

### ISSUE THREAD

**Issue by joshmarinacci** [MozillaReality/FirefoxReality#757]
Load this page in FxR 1.1

https://www.youtube.com/watch?v=LdUxW8_59bA&t=0s&app=desktop

You will see that the video has one channel that is horizontal and one that is vertical. When I enter immersive mode none of the video modes matches whatever 360 layout this video is using.

```
```

</details>

**Comment by cvan** [comment]
YouTube's metadata says `"projectionType": "EQUIRECTANGULAR"`, btw

**Comment by caseyyee** [comment]
Works for me in all resolutions tested 480p, 1440p and 4k.
