### ISSUE TITLE
What is the new tab page for FxR?

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#759]
## Hardware
Any

## Steps to Reproduce
1. Press the `Home` button.
2. Notice the production FxR Content Feed always loads and cannot be changed to point to a different Home page.

## Current Behavior
 [`SessionStore.HOME_WITHOUT_REGION`](https://github.com/MozillaReality/FirefoxReality/blob/d90f804/app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java#L69) is a hardcoded constant.

## Expected Behavior
 [`SessionStore.HOME_WITHOUT_REGION`](https://github.com/MozillaReality/FirefoxReality/blob/d90f804/app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java#L69) can be customised by an `a hardcoded constant.

Either allow the user to set it via a pref in `Settings > Developer Options` and/or an `adb` command (when the device is set in `Developer Mode`, for example:

```
adb shell setprop debug.org.mozilla.vrbrowser.homeUri https://www.futurefonts.xyz/
```

We should be sure to change the code for hiding the URL text in the `NavigationURLBar` so the custom URL is shown if it's not our production, HTTPS+TLS-secured one.

**Comment by philip-lamb** [comment]
Interacts with #935.

**Comment by philip-lamb** [comment]
Current Firefox desktop configuration is quite sophisticated here: <img width="709" alt="screen shot 2019-03-05 at 1 06 24 am" src="https://user-images.githubusercontent.com/5752887/53732538-26be1300-3ee3-11e9-8926-8c641d5b036b.png">

**Comment by jvonitter** [comment]
Consider aligning to Firefox new tab content and settings:
![newtabsettings](https://user-images.githubusercontent.com/48839872/61243018-ec1f7f00-a6fb-11e9-8751-cbdba151d8a8.PNG)
