### ISSUE TITLE
Firefox Reality's URL Launcher activity prompts for YouTube VR activity when both apps are installed

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#762]
## Hardware
Oculus Go
54f045e

## Steps to Reproduce
0. Ensure you have `Developer Mode` enabled for your headset.
1. Run this `adb` command in the Terminal/command-line prompt:

    ```
    adb shell am start -a android.intent.action.VIEW -d "https://www.youtube.com/watch?v=SGP6Y0Pnhe4" -n org.mozilla.vrbrowser/org.mozilla.vrbrowser.VRBrowserActivity
    ```
2. Because I have the YouTube VR app installed, notice this prompt appears asking me if I want to launch these URLs in the YouTube VR app instead of in Firefox Reality.

## Current Behavior
![screenshot of Firefox Reality vs. YouTube VR prompt](https://user-images.githubusercontent.com/203725/48544937-9ac3a500-e879-11e8-8383-da28270439ad.png)

## Expected Behavior
I'm curious at what level Android is looking at this activity for Firefox Reality and suggesting YouTube's as another activity to launch (and persist). @bluemarvin: do you have an idea?

(P.S. It'd be nice if we removed the transparency in the Android application icon. I'll file that later.)

**Comment by keianhzo** [comment]
Weird it doesn't behave like that in my Go using master with both YoutubeVR and FxR installed. 
If I run:

`adb shell am start -a android.intent.action.VIEW -d "https://www.youtube.com/watch?v=SGP6Y0Pnhe4" -n org.mozilla.vrbrowser/org.mozilla.vrbrowser.VRBrowserActivity`

it just opens FxR, but if I run:

`adb -s 1KWPH803DL8163 shell am start -a android.intent.action.VIEW -d "https://www.youtube.com/watch?v=SGP6Y0Pnhe4"`

I get the launcher menu.

**Comment by philip-lamb** [comment]
Like Manuel, I get the expected behaviour. Interestingly, the launcher menu doesn't show FxR as an option at all. Only Youtube VR and VRBrowserLauncher (which launches Oculus browser). Will close as worksforme and reopen if we can isolate it under different circumstances.
