### ISSUE TITLE
Quality of Voice Search results impacted by improper phrases (double-encoded entities) being sent

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#767]
## Hardware
Oculus Go
350af99

## Steps to Reproduce
1. Press the Mic icon in the URL bar for a Voice Search.
2. Say `la biblioteca`.
3. Notice the Google Search bar on the results page shows `la+biblioteca`.

## Current Behavior
Notice the Google Search bar on the results page shows `la+biblioteca`.

## Expected Behavior
Notice the Google Search bar on the results page shows `la biblioteca`.

**Comment by cvan** [comment]
@avrignaud FYI this issue is important for us in 1.1 to properly  highlight the Voice Search improvements and added locales

**Comment by keianhzo** [comment]
@cvan This one is fixed in #728. Should be ready to be merged so feel free to land if you don't see any outstanding issues.
