### ISSUE TITLE
Private browsing Interaction colors are inconsistent

### ISSUE THREAD

**Issue by thenadj** [MozillaReality/FirefoxReality#774]
## Hardware
Oculus Go
## Steps to Reproduce
Load APK from 2018-11-16
Go to Private Browsing mode

## Current Behavior
Interaction colors for URL bar and tray are inconsistent with rest of UI. 

## Expected Behavior
See attached document for details. 

[Bug-19 Private Browsing Mode_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2591095/Bug-19.Private.Browsing.Mode_001.pdf)

```
```

</details>

**Comment by caseyyee** [comment]
Fixed with https://github.com/MozillaReality/FirefoxReality/pull/760
