### ISSUE TITLE
Media controls show for non-video sources in VR video modes

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/FirefoxReality#776]
FXR:
eaa4fc5

## Hardware
Oculus Go

## Steps to Reproduce
1. Enter fullscreen
2. Navigate to 
https://mixedreality.mozilla.org/fxr-html-tests/window-size.html
3. Fullscreen
4. Select VR video mode

## Current Behavior
Media transport controls show.  If you interact with the controls, the browser crashes.

## Expected Behavior
For non-video sources, we should not be showing transport controls.

**Comment by cvan** [comment]
@caseyyee I recall you saying you saw some crashes with non-video sources? can you provide STR?

**Comment by cvan** [comment]
From my testing, this is important because it is confusing to the user, but it does not block a user flow or crash. @caseyyee if you can reproduce with a crash, please post a comment with `adb logcat | grep -i gecko` logs, and we can escalate this issue. Thanks!

**Comment by MortimerGoro** [comment]
I created https://github.com/MozillaReality/FirefoxReality/pull/796 for now

@thenadj created a different UI for this scenario, but it's too much work for v1.1. We can address this later
