### ISSUE TITLE
50p and 60p Youtube video does not play

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/FirefoxReality#780]
## Hardware
Go

## Steps to Reproduce
1. Watch https://www.youtube.com/watch?v=KaCQ8SQ6ZHQ

## Current Behavior
Get audio, but little or no video playback. 
Have tried lower resolutions 720p60 and 480p60 without much luck either.
Works with Oculus browser.

**Comment by cvan** [comment]
@caseyyee: thanks for filing. how severe is this? blocker, important, or nice to have after release v1.1?

**Comment by larsbergstrom** [comment]
Possibly related to: https://bugzilla.mozilla.org/show_bug.cgi?id=1463904 ?

**Comment by caseyyee** [comment]
Found this on reddit. Appears to be a issue on desktop as well:

https://www.reddit.com/r/firefox/comments/a080sd/firefox_youtube_60fps_1080p_dropped_frames_video/?st=JOXA734N&sh=30a4b91c

The fix in the post that could provide hints:

layers.gpu-process.enabled = false
media.gpu-process-decoder = false

Also sounds like it occurres with avc1

**Comment by caseyyee** [comment]
Moving to P1 since there is a bunch of content on YT that is 50 or 60p only and cannot be viewed otherwise.

**Comment by bluemarvin** [comment]
> Found this on reddit. Appears to be a issue on desktop as well:
> 
> https://www.reddit.com/r/firefox/comments/a080sd/firefox_youtube_60fps_1080p_dropped_frames_video/?st=JOXA734N&sh=30a4b91c
> 
> The fix in the post that could provide hints:
> 
> layers.gpu-process.enabled = false
> media.gpu-process-decoder = false
> 
> Also sounds like it occurres with avc1

Gecko doesn't support GPU process on Android so these prefs will have no effect on GeckoView.

**Comment by jvonitter** [comment]
no longer able to repro
