### ISSUE TITLE
Suggestion widget does not dismiss.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#782]
## Hardware

Go

## Steps to Reproduce

1. Type some text into the URL bar to see the suggestion widget.
2. Click on the browser window to dismiss the keyboard.

## Current Behavior

Suggestion widget can no longer be dismissed.
![suggest](https://user-images.githubusercontent.com/3066/48746614-fe0c5900-ec24-11e8-8a00-c40d4eed1b30.png)

## Expected Behavior

The suggestion UI should be dismissible.

**Comment by keianhzo** [comment]
Should have been closed by #760. Closing.
