### ISSUE TITLE
Slow YouTube UI, breaks fullscreen (likely because of Polymer polyfills)

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/FirefoxReality#785]
Youtube UI is super slow to load and respond.

Could be due to Polymer as per:
https://twitter.com/cpeterso/status/1021626510296285185?s=21

Youtube classic extension:
https://github.com/thisdotvoid/youtube-classic-extension

**Comment by cvan** [comment]
@caseyyee as we talked about, can we try enabling Multiprocess in the Developer Options to investigate the loading issues with YouTube videos (namely the Fullscreen icon being unresponsive until the document is 100% completely loaded).

**Comment by caseyyee** [comment]
I did try multiprocess, it didn't seem to help much.  But, the fullscreen button being unresponsive until content is loaded is a issue. It'll take upwards of 30-40 seconds.

**Comment by cvan** [comment]
> But, the fullscreen button being unresponsive until content is loaded is a issue. It'll take upwards of 30-40 seconds.

Yikes! I was hoping it was just my headset, but this resembles my experience on the Go.

This sounds like a major blocker. We can discuss tomorrow AM (Wed, Nov 21).

**Comment by MortimerGoro** [comment]
This looks like a blocker. I was able to reproduce the same problems

**Comment by caseyyee** [comment]
Fixed with https://github.com/MozillaReality/FirefoxReality/pull/824
