### ISSUE TITLE
Add new documentation page for new Media Controls to support.mozilla.org

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#791]
## Hardware
All

## Steps to Reproduce
1. Load a 2D _video with controls_, such as one from the `Media` section of https://mzl.la/2JSKHWC
2. Press the Fullscreen icon in the bottom of the native video controls.
3. Once in Fullscreen Mode, you will see the Media Controls.

![screenshot of Media Controls with 'Video Projection' list opened](https://user-images.githubusercontent.com/203725/48545348-8f24ae00-e87a-11e8-9067-5c3620f51b3b.png)

## Current Behavior
https://support.mozilla.org/en-US/products/firefox-reality/get-started does not have any specific docs page for videos/media playback.

## Expected Behavior
https://support.mozilla.org/en-US/products/firefox-reality/get-started should link to a page called **Watching videos in Firefox Reality** (or similar).

## Possible Solution
We should coordinate with the SUMO (support.mozilla.org) folks to document the new media controls (added as part of issue #330) in the upcoming release, version 1.1.

_cc @larsbergstrom: do you know which of our SUMO friends to collaborate with to get new pages added?_

## Context
For issue #330, with the GeckoView Media API (https://phabricator.services.mozilla.com/D9026, https://phabricator.services.mozilla.com/D10137) added and used by Firefox Reality, there are now Media Controls (aka Transport Controls) shown when a video or video-esque element is fullscreened.

**Comment by philip-lamb** [comment]
As well as new pages like this, we could probably move a bunch more user-specific documentation from the wiki to SUMO. @jvonitter something for product to consider.
