### ISSUE TITLE
Add options for user to define Website Content Language order

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#794]
## Steps to Reproduce
1. Launch `Settings` from the Tray.
2. Press the `Language` (added in PR #634, which was for issue #559) button.
3. Notice locales are listed for only the `Voice Search Language`.

## Current Behavior
`Settings > Language` lists locales (and a `Reset Language` button) for `Voice Search Language`.

## Expected Behavior
`Settings > Language` should list all locales.

There are three different languages/locales:

1. Browser-chrome UI (e.g., which appear in text in Settings and Tooltips).
2. Content Language (i.e., `Accept-Language` HTTP request header).
3. Voice-Search Language (i.e., the language understood when the user performs a Voice Search).
 
As consistent with Firefox on other platforms & other modern browsers, there needs to be an option for users to define their preferred locales, and in a particular order.

This behaviour will comply with the `Accept-Language` behaviour defined in the HTTP spec, [RFC 7231](https://tools.ietf.org/html/rfc7231#section-5.3.5).

## Possible Solution & Context
In `Settings > Language`, we could have a separate list for the website content Language ordering. Or we could merge the `Voice Search Language` with this one.

This could be implemented with a smart-autocomplete widget.

We need to list *all known locales* because a user's locale is different from the locales we support in the Firefox browser-UI chrome. This locale ordering is important for websites to know in order to serve their content correctly for the user's locale. This is based on the `Accept-Language` HTTP request, in conjunction with a `Vary: Accept-Language` header or a server-side redirect, and the server then responds with the served locale in a `Content-Language` HTTP response header (though the `Content-Language` header is optional). (See the [RFC 7231 spec](https://tools.ietf.org/html/rfc7231#section-3.1.3.2) for more details.)

<hr>

needs #786.

**Comment by jvonitter** [comment]
needed by #1243

**Comment by jvonitter** [comment]
Final designs: https://trello.com/c/53CURr28/378-uis-82-choose-display-language

**Comment by keianhzo** [comment]
@thenadj @jvonitter A few things about the spec:

- I can't find the help icon for the languages header in the Trello task
- I can't see the spec for "Preferred Language for Displaying Websites" and "Voice Search Language"
- I'll need the link for the header help button?
- The settings header and footer text sizes are the same (14sp) but they look different sizes in the spec

**Comment by keianhzo** [comment]
@thenadj @jvonitter There it goes a testing APK. Remaining things:
- Final links for the help buttons. Voice has the an specific SUMO link but content and display currenlty point to the Desktop help.
- We need a dialog spec for switching the display language as we cannot refresh the UI without restarting the activity.
- The webcontent language list is the system available locales as there is no limitation there. It's quite a long list, would be good to have a search filter or just provide a limited locale list. 
- Any other visual or functional issues please let me know.

https://send.firefox.com/download/0b1e39d1a0f360ff/#bKBPMB2r1BU6r2g3qqWnIg

**Comment by jvonitter** [comment]
@keianhzo did you get what you needed or do you still need updates from @thenadj ?

**Comment by keianhzo** [comment]
@jvonitter yes, the sent me the info by email.

**Comment by philip-lamb** [comment]
As part of this work, please document steps required for a functional test, including test website content.

**Comment by Softvision-GeluHaiduc** [comment]
This was implemented and tested in the 1.4 release.
I will remove the QA label.
