### ISSUE TITLE
Remove scrollbar in video menu dropdown

### ISSUE THREAD

**Issue by thenadj** [MozillaReality/FirefoxReality#795]
## Hardware
Oculus Go

## Steps to Reproduce
Go to YouTube or Vimeo, click fullscreen button

## Current Behavior
The menu dropdown for Environment customization and video playback has a scrollbar in it. 

![image](https://user-images.githubusercontent.com/13240857/48821187-18b9fd00-ed0d-11e8-8cf9-5271e4dfb5e7.png)

## Expected Behavior
There should not be a scrollbar in that menu as the options are limited. 

## Possible Solution
Remove scrollbar

[Bug-21 Video Transport Control Menus_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/2602773/Bug-21.Video.Transport.Control.Menus_001.pdf)

```
```

</details>

```
```

</details>

**Comment by MortimerGoro** [comment]
Related, sometimes the first click doesn't work. It may happen because of the scrolling.

**Comment by MortimerGoro** [comment]
It's a easy fix, created this PR: https://github.com/MozillaReality/FirefoxReality/pull/797

**Comment by cvan** [comment]
@MortimerGoro fixed this in PR #797, which is merged into `master`
