### ISSUE TITLE
Widget resizing issue with layers

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#799]
@keianhzo found this issue:` I've seen issues with the widget resizing in onWidgetUpdate in the navigation bar mainly as it's the only widget that get's resized on demand after a browser window resize, I didn't have time to dive deeper into it but seems to be working fine for ratios <1.0 but it's not resizing properly for ratios >1.0`

I'm going to investigate the problem

**Comment by cvan** [comment]
In Private Browsing, I also notice the (×) gets taller (and a purple rectangle appears below it) when I resize the width and height of the browser window.
