### ISSUE TITLE
Migrate to Android Component?

### ISSUE THREAD

**Issue by paulrouget** [MozillaReality/FirefoxReality#80]
https://github.com/mozilla-mobile/android-components

As far as I understand, Android Component abstract Gecko/GeckoBeta/Webkit under a common interface. I was wondering if we could use that instead of the GeckoView directly?

Asking because we also want a Servo backend for Crow. And adding Servo along Gecko and Webkit in AndroidComponent feels like the natural thing to do.

/cc @MortimerGoro  @jdm

**Comment by MortimerGoro** [comment]
I have some concerns about using that component at this stage:

- [EngineSession](https://github.com/mozilla-mobile/android-components/blob/master/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt) provides a really small API now, and we are using very specific things on FxR: e.g. full screen callbacks, keyboard delegate, private browsing, tracking delegate, etc. Not sure if the team implementing the engine abstraction is willing to add all those things things or they want to keep the API small, or how much time will it take to add all the APIs.
- It may slow down the dev worflow. GV API is constantly changing, if we want to use the latest version waiting for additional layer updates may be blocking.

I think that it would be easier to create an ad-hoc solution until all the APIs are stable and EngineSession gets the whole API. Idea: we could create a ServoGeckoSession bridge class that inherits from GeckoSession and internally delegates all the calls to the Servo Implementation. I think that way we'd only need to abstract they way to create a new Session, but other parts of the code wouldn't need to be touched.

@bluemarvin any thought? you may have more context on the plans of the team implementing the android-components

**Comment by daoshengmu** [comment]
Our telemetry system is starting to use Android-Telemetry-Component.

**Comment by MortimerGoro** [comment]
Closing this because the engine abstraction wants to keep the API small and we can't use all the APIs required that way

**Comment by MortimerGoro** [comment]
We can create a different issue for the Servo bridge mentioned above. I think that it will be the easiest and most flexible way for the integration
