### ISSUE TITLE
Crash on start up with Go

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#810]
## Hardware

Go
## Steps to Reproduce

1. Start FxR from AS with the display on the device asleep.
2. put on device to activate display.

## Current Behavior

FxR crashes after rendering one frame.

## Expected Behavior

FxR should start as expected.

This seems to be intermittent.

Crash report: https://crash-stats.mozilla.com/report/index/7ea53c97-a59a-44f8-abb2-e45bd0181121

**Comment by philip-lamb** [comment]
Pushing to 1.3 as it is not user-facing.

**Comment by jvonitter** [comment]
Need to see if this is still happening. @bluemarvin can you check?

**Comment by keianhzo** [comment]
@jvonitter I've been trying for a while and I can't reproduce this anymore. In the crash-stats it seems that all the related reports are related to 66.0a1 which is from and old release, not sure when but probably early this year. Here are fewer crashes in May and no crashes in June.

**Comment by philip-lamb** [comment]
OK, I'll close.
