### ISSUE TITLE
Change `Gamepad#id` from "Gear VR Controller" to "Oculus Go Controller"

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#812]
# Hardware
Oculus Go

Unless there are particular Web Compatibility reasons (cc @bluemarvin), with the Oculus Go we should change the `Gamepad`'d `id` string from `Gear VR Controller` to `Oculus Go Controller`. If there are particular known sites that are (or were) affected, let me know and we can figure something out.

This noticeably would fix some WebVR video players/experiences that sniff for the `id` of the `Gamepad` object to use the respective controller model mesh.

### Firefox Reality

```js
navigator.getGamepads()[0]
```

```
Gamepad
​axes: Array [ 0, 0 ]
​buttons: Array [ GamepadButton, GamepadButton ]
​connected: true
​displayId: 1
​hand: "right"
​hapticActuators: Array []
​id: "Gear VR Controller"
​index: 0
​mapping: ""
​pose: GamepadPose { hasOrientation: true, hasPosition: false, position: null, … }
​timestamp: 191406
<prototype>: GamepadPrototype { id: Getter, index: Getter, mapping: Getter, … }
```

![screenshot](https://user-images.githubusercontent.com/203725/48879622-9ac42780-edda-11e8-8769-b958529ec23b.png)

<hr>

### Chrome

```js
navigator.getGamepads()[0]
```

```
Gamepad {id: "Oculus Go Controller", index: 0, connected: true, timestamp: 2653221748, mapping: "", …}axes: (2) [0, 0]buttons: (2) [GamepadButton, GamepadButton]connected: truedisplayId: 1hand: "right"id: "Oculus Go Controller"index: 0mapping: ""pose: GamepadPoseangularAcceleration: Float32Array(3) [0.09922924637794495, 0.46682077646255493, 0.21701952815055847]angularVelocity: Float32Array(3) [0.0015635552117601037, 0.003237674245610833, 0.0039522601291537285]hasOrientation: truehasPosition: falselinearAcceleration: Float32Array(3) [0.009476134553551674, 0.08094597607851028, -0.009985487908124924]linearVelocity: Float32Array(3) [0, 0, 0]orientation: Float32Array(4) [-0.030928365886211395, 0.06747458130121231, -0.6488243341445923, -0.75730961561203]position: null__proto__: GamepadPosetimestamp: 2654424216vibrationActuator: null__proto__: Gamepad
```

![image](https://user-images.githubusercontent.com/203725/48880400-4c188c80-edde-11e8-95d4-2acc013c67a3.png)

**Comment by caseyyee** [comment]
Nice find. Could also be a factor with issue https://github.com/MozillaReality/FirefoxReality/issues/770. I noticed the controller model returned is wrong with FXR (get VIVE controller) and they could be applying the wrong translations because of it.

**Comment by 3DataWill** [comment]
Just submitted aframevr/aframe#3876 to add proper support for the Vive Focus controller, expecting a gamepad ID of "HTC Vive Focus Controller"

**Comment by bluemarvin** [comment]
This controller string was requested previously for web compat.

**Comment by philip-lamb** [comment]
Per https://github.com/aframevr/aframe/issues/3390 we should definitely use the correct string for each device. @cvan Which module currently supplies the string?

**Comment by cvan** [comment]
Also see https://github.com/MozillaReality/FirefoxReality/issues/401#issuecomment-469518151.

**Comment by cvan** [comment]
handled in PR #812. thanks, @daoshengmu!
