### ISSUE TITLE
Resizing window while in fullscreen breaks UI

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/FirefoxReality#818]
## Hardware
Go 
FXR https://github.com/MozillaReality/FirefoxReality/commit/e92f5a311fcd68506042b8b10f4e97451de2a96c

## Steps to Reproduce
1. View video or site that uses `requestFullscreen()`.
Anything will work here:
YouTube,
Test cases 2 and 3 on https://webxr.sh/window-screen

2. Press Fullscreen
3. Resize window

## Current Behavior
UI widgets shrink and alignment breaks.
Exiting fullscreen mode, URL and navigator controls also break and browser needs to be restarted,

![resize-small-ui](https://user-images.githubusercontent.com/1560884/48920853-51aeba80-ee50-11e8-91c6-d3b6b13c3c4f.gif)

**Comment by MortimerGoro** [comment]
Did you test this before https://github.com/MozillaReality/FirefoxReality/pull/816 was merged?

**Comment by caseyyee** [comment]
Ah yes, looks like it's fixed with #816.  Thanks!
