### ISSUE TITLE
Cannot perform Voice Searches with es-ES locale

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#826]
## Hardware
Oculus Go

## Steps to Reproduce

1. Factory reset the Go with the linked device locale set to Spanish (Spain)
1. Click on the Voice Search mic (accept permissions if prompted)

## Current Behavior
Stuck at the !Lo Siento! screen (Sorry! I could not understand.) indefinitely. I waited a good 1 minute+.
Click on the Voice Search mic icon again.

## Expected Behavior
The screen should show "¿Qué le gustaría buscar en Internet? (What would you like to search on the Web?)"

## Error Logs and Stack Traces
<details open>

```
```

</details>

**Comment by cvan** [comment]
For context: [**Here's a video**](https://vimeo.com/302177210/e3a73474e3)

**Comment by philip-lamb** [comment]
@MortimerGoro Do you have your Go set to es_ES locale? If so, could you comment on whether this is still an issue?

**Comment by MortimerGoro** [comment]
I tested it and it worked perfectly, so we can close this issue
