### ISSUE TITLE
Set a better URL for home

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#83]
The URL of the home page is a long URL (resource://......). It's not pretty for a product. Keep the URL bar empty or find a better text

The same for error pages.

**Comment by cvan** [comment]
this can/will be `about:home` (which we have now with #132 / #133)

**Comment by keianhzo** [comment]
@MortimerGoro After fixing the jar: issue the home now is always empty URL same as Firefox does. Can we close this issue?

**Comment by avrignaud** [comment]
We should figure out where the official content feed URL will live. Maybe https://mixedreality.mozilla.org/content ?
@larsbergstrom @cvan Thoughts?

**Comment by cvan** [comment]
@avrignaud: for now, it'll be https://mixedreality.mozilla.org/fxr/

**Comment by larsbergstrom** [comment]
I think this issue can be closed as it has been fixed. @avrignaud We should open new issues for different discussions to avoid cluttering the `P0` bug list with things that are done :-)

**Comment by MortimerGoro** [comment]
yes, this can be closed.
