### ISSUE TITLE
<video>s gets increasingly smaller after entering and exiting fullscreen VR videos (reproducible on any site, including YouTube)

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#833]
STR:

1) Load https://www.youtube.com/watch?v=sPyAQQklc1s
2) Enter Fullscreen
3) Enter 360 video projection
4) Exit video projection
5) Exit fullscreen
6) See Repeat step 2

**Comment by caseyyee** [comment]
This happens with just regular Fullscreen viewing on Youtube as well.  Does not seem to be an issue anywhere else.

**Comment by cvan** [comment]
1. Load [test case `#5`](https://mdn.github.io/learning-area/html/multimedia-and-embedding/video-and-audio-content/extra-video-features.html) from https://webxr.sh/media
2. Click the video's Fullscreen icon to enter fullscreen
3. Change the Projection Mode (i.e., the VR Goggles icon)
4. Press the ← button in the Media/Transport Controls to exit 
5. Re-enter with a new Projection Mode
6. Notice upon exiting again, the video gets exponentially smaller it seems

**Comment by caseyyee** [comment]
OK, so I noticed that with this, the window.innerWidth and Height is changing every fullscreen cycle:

1x 800x450
2x 980x551
3x 1296x729

window.outerWidth and Height remain at 800x450, and screen.width and screen.height also remain 1200x1200
