### ISSUE TITLE
Texture resize issue with some aspect ratios

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#834]
## Hardware
Oculus Go

## Steps to Reproduce

1. Launch the Bookmarks list from the Tray.
2. Open Resize Mode.
3. Press the 1x button.
4. Drag the right handle to drag the window horizontally.

## Current Behavior
![49000394-6678a000-f127-11e8-8ca8-4b26aa86f1f3](https://user-images.githubusercontent.com/837184/49032323-14ed0700-f161-11e8-9b5f-2cbb1c0aee32.png)

## Expected Behavior
Texture should fill the new size.

## Context
[Here's a video.](https://vimeo.com/302776426)

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by nancyhang** [comment]
Possibly related to #835
