### ISSUE TITLE
Density issues in widgets when scaled down

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#835]
## Hardware
All

## Steps to Reproduce
1. Open Bookmarks
2. Enter resize mode
3. Use the preset to resize 3x
3. Use the handlers to resize to the horizontal minimum allow size

## Current Behavior
![49000044-6e841000-f126-11e8-920b-a511a2eccc3f](https://user-images.githubusercontent.com/837184/49033529-45827000-f164-11e8-8ee8-a7cafb821236.png)

## Expected Behavior
The view content should be visible in the new size.

## Possible Solution
Maybe we could adjust the widget density dynamically  so the view content better fits the new size.

## Error Logs and Stack Traces
<details open>

```
```

</details>

**Comment by caseyyee** [comment]
Maybe have a minimum width for the window? Problem with scaling is that it'll get to small to read at some point.

**Comment by nancyhang** [comment]
Need to test to see what is the optimal size.

**Comment by keianhzo** [comment]
Fixed with #888  Closing.
