### ISSUE TITLE
"360 video playback is not supported" message on YouTube

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/FirefoxReality#837]
## Hardware
Go
a9da13

## Steps to Reproduce
1. Navigate to any 360 content on Youtube. (eg https://www.youtube.com/watch?v=LdUxW8_59bA)

## Current Behavior
YouTube displays "360 video playback is not supported on this browser"

![360](https://user-images.githubusercontent.com/1560884/49038978-54bcea00-f173-11e8-8b26-f2b4892e65b9.png)

**Comment by cvan** [comment]
I also notice a similar warning appears for [VR180 videos](https://www.youtube.com/watch?v=PZtpnL8x21g):

> VR180 video playback is not supported on this browser.

![image](https://user-images.githubusercontent.com/203725/49058800-9aa99a80-f1d3-11e8-8f67-a5cd36b1e63d.png)

**Comment by cvan** [comment]
this has been fixed since PR #1052, but Firefox chokes on the syntax error in the style selector here https://github.com/MozillaReality/FirefoxReality/pull/1052/files#r283601515, which causes the `Full screen is unavailable` message to still be visible (see issue #1056).
