### ISSUE TITLE
Browser window size is set to fullscreen size on restart.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#839]
## Hardware

Focus

## Steps to Reproduce

1. Make video fullscreen.
2. Manually resize the window with the drag handles.
3. Press home button to exit the app.
4. Relaunch the application

## Current Behavior

Browser window is now using the fullscreen window size.

## Expected Behavior

Browser window should still have the same size from before exiting the application.

**Comment by caseyyee** [comment]
This also happens on the Go.
