### ISSUE TITLE
Crash in CustomKeyboard on Android P

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#843]
## Hardware

Android P at least with NoAPI and GVR builds.
## Steps to Reproduce

1. Open keyboard.

## Current Behavior

FxR crashes.

## Expected Behavior

The virtual keyboard should be visible.

## Error Logs and Stack Traces

`java.lang.IllegalArgumentException: at android.graphics.Canvas.checkValidClipOp(Canvas.java) …`
https://crash-stats.mozilla.com/report/index/e0807521-b3c3-4069-ad81-291990181126

**Comment by philip-lamb** [comment]
@cvan Do you have an Android P device you can test this on?

**Comment by bluemarvin** [comment]
I think this was fixed and just not closed. I run FxR on P with out issue.

**Comment by philip-lamb** [comment]
Thanks @bluemarvin.
