### ISSUE TITLE
Should not allow about:privatebrowsing page to be Bookmarked

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/FirefoxReality#847]
## Hardware
Go
FXR 7496873

## Steps to Reproduce
1. Enter private browsing
2. Press Bookmark icon in URL bar

## Current Behavior
Note Private Browsing page in Bookmarks.

![private-bookmark](https://user-images.githubusercontent.com/1560884/49051518-0f151700-f19d-11e8-8c90-900c64bcda3e.png)

**Comment by philip-lamb** [comment]
Possible easy base of a solution is to hide the "add bookmark" element for any URI with a scheme of "data:".

**Comment by cvan** [comment]
Unless I am misunderstanding, it should not be for `data:` URIs, but it should be for `about:` URIs (and error pages).

**Comment by philip-lamb** [comment]
> Unless I am misunderstanding, it should not be for `data:` URIs, but it should be for `about:` URIs (and error pages).

You're right, although I observed that while the URI hint is "about:privatebrowsing", when you add a bookmark, the bookmark summary begins "data:".

Interestingly, desktop Firefox allows you to bookmark the "about:privatebrowsing" page which seems like the same bug 😄
