### ISSUE TITLE
Keyboard appears upon a crash

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#849]
## Hardware

Oculus Go
f5e522d

## Steps to Reproduce

1. Load the URL `about:crashparent`
2. Notice upon relaunch, the keyboard appears opened

## Context
Related: issue #846

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by keianhzo** [comment]
Probably related or duplicate of #846

**Comment by keianhzo** [comment]
Fixed with #889 Closing.
