### ISSUE TITLE
Performance of Matterport is slower than in Oculus Browser

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#850]
## Steps to Reproduce

1. Load https://my.matterport.com/show/?m=4s92ARZUpdm

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by philip-lamb** [comment]
Works for me on v1.1.2. @cvan Please test again and close if it now does what you expect.

**Comment by cvan** [comment]
Tested this in FxR on the Oculus Go. The WebVR mode loads correctly. The tracking is noticeably slow, but it's usable.

In Oculus Browser, the perf is much better; the tracking is nearly flawless.

I did notice that in both browsers, there's a several-second lag in the time between when the VR session is requested and presented.

WebVR perf issues are tracked in GV and in other issues here. But this could be worth profiling further. @fernandojsg: if you have spare cycles, could you use your `webgfx-tests` tool to get numbers for this? I can do it too; I just have to set it up.

**Comment by philip-lamb** [comment]
Pushing JS and media-related perf issues to 1.3 as we won't comprehensively test for v1.2.

**Comment by philip-lamb** [comment]
Tested this again just now with FxR 1.2.3. The tracking performance seems similar, although loading time is definitely longer on FxR than OB, so navigating from point-to-point feels snapper on OB. Pushing this to 1.x with P5 as an interesting performance test case but nothing much actionable right now.
