### ISSUE TITLE
Add an option to download/export Bookmarks

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#851]
Especially after uninstalling FxR, you may purge your local bookmarks. Which is an unfortunate footgun we can avoid.

Stretch goal: share via URL.

**Comment by philip-lamb** [comment]
FxA implementation with bookmarks sync would provide a workaround.

**Comment by cvan** [comment]
I like that. To my knowledge, with Firefox Sync (via Firefox Accounts) you still have to have a desktop computer, install Firefox, launch Firefox, sign in to Firefox Sync with your Firefox Accounts account, from Firefox's UI near the address bar click the `Library` button (i.e., the library books icon), from the drop-down menu that appears click the `Bookmarks` row, click the `Show all Bookmarks` button at the bottom of the drop-down menu, find the folder for your synced tabs, click the `Import and backup your bookmarks` (i.e., the icon of a star with arrows inside it), `Export Bookmarks to HTML…`, and then save that file.

![image](https://user-images.githubusercontent.com/203725/54170439-f838be80-4433-11e9-9192-9d49edc9ae46.png)

Here is the [SUMO article](https://support.mozilla.org/en-US/kb/export-firefox-bookmarks-to-backup-or-transfer) documenting the process (though it doesn't mention sync'd tabs or Pocket).

Also, notice that in the `Library` drop-down, besides `Bookmarks`, there are options for `View Pocket List` and `Synced Tabs`:

![image](https://user-images.githubusercontent.com/203725/54170525-4f3e9380-4434-11e9-88dd-b614c60fbdaa.png)

If you click on `Synced Tabs` but are not signed in (or, more problematically, if you have not created a Firefox Accounts account (and clicked on the confirmation link sent to your email), you see this screen:

![image](https://user-images.githubusercontent.com/203725/54170603-988ee300-4434-11e9-9747-91d39a2d9453.png)

I'd say to qualify this issue as closed, we ought to work through the possible scenarios and verify that

1. from Firefox Reality, users can export or download (e.g., to `/data/data/org.mozilla.vrbrowser/`) a list of their saved Bookmarks (i.e., ideally in an accessible format such as an `.html` document, à la desktop Firefox). (also, see relevant related issues: #685 and #672.)
2. bookmarked tabs are available via Firefox Sync.
3. bookmarked tabs are available via Pocket. (likely optional, but will need to product guidance wrt protocol with Firefox Sync.)
4. expose option to Export Bookmarks (e.g., `Export Bookmarks to HTML…`, `Sync Tabs`, `Save to Pocket`, etc.) clearly in obvious places in the UI (likely in the Bookmarks List, `about:bookmarks`, itself).
5. publish a new a [SUMO user-guide article](https://support.mozilla.org/en-US/products/firefox-reality) for users to learn how to export their Bookmarks from Firefox Reality.

**Comment by MortimerGoro** [comment]
We are closer to support firefox sync after this PR: https://github.com/MozillaReality/FirefoxReality/pull/1251

**Comment by grigoryk** [comment]
https://github.com/MozillaReality/FirefoxReality/pull/1389 adds Firefox Sync support for bookmarks.
