### ISSUE TITLE
Kuula.co WebVR performance issues

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#852]
## Hardware
Oculus Go

## Steps to Reproduce
1. Launch https://kuula.co/post/7PP6r
2. Enter VR

## Current Behavior
Performance is not usable.

## Expected Behavior
Performance is stable for proper 360º playback in Immersive Mode.

## Context
Have a few email threads with Kuula.com folks.

We need to do some further Remote Profiling. Here's a useful [FxR Remote Debugging article](https://blog.mozvr.com/remote-debugging-firefox-reality/) written by the great @joshmarinacci. We can adapt some of the priniciples for Profiling (vs. Debugging).

## Error Logs and Stack Traces
TBD

<details open>

```
```

</details>

**Comment by cvan** [comment]
Update: Kuula panos still enter VR, but now the canvas is completely black/void. They work in Oculus Browser. Will investigate and follow up. (Likely with an accompanying [WebCompat issue](https://github.com/webcompat/web-bugs/issues) to file.)

**Comment by philip-lamb** [comment]
Tested with 1.2-rc5. The experience works OK now (no black canvas) except the odd thing is that the frame rate in just the left eye is a bit lower. The right eye frame rate is usable but the left lags.

**Comment by philip-lamb** [comment]
Leaving open in 1.x to followup on left-eye oddity.
