### ISSUE TITLE
 [l10n] Update strings for Traditional Chinese

### ISSUE THREAD

**Issue by Delphine** [MozillaReality/FirefoxReality#858]
Traditional Chinese (zh-TW) localizers have updated the localized strings for v1.1.
Please find attached the files.
[rezhtwfirefoxrealitytestingv1_1localizations.zip](https://github.com/MozillaReality/FirefoxReality/files/2621552/rezhtwfirefoxrealitytestingv1_1localizations.zip)
 that we'll need to use instead of current versions of both localpages.xml, strings.xml and a-c Error pages
thanks!
(CC @nancyhang and @larsbergstrom so they are aware)

**Comment by cvan** [comment]
updated in PR #859. thanks, @Delphine!
