### ISSUE TITLE
Keyboard stays open after entering a URL

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#860]
## Hardware
Oculus Go
9cf66ae

## Steps to Reproduce

1. Press the URL bar
2. Enter an address
3. Notice the URL bar stays open even after the page is loaded

## Current Behavior
The URL bar remains upon after a URL is entered / a page is requested.

## Expected Behavior
The URL bar closes after a URL is entered / a page is requested.

## Context
Not sure if this is a regression I added in PR #830. I haven't dug deep enough yet.

**Comment by keianhzo** [comment]
Probably related or duplicate of #846

**Comment by cvan** [comment]
Yep, I notice it after a crash prompt, search suggestions, and a few others. Probably the same fix for all?

**Comment by keianhzo** [comment]
Fixed with ##889 Closing
