### ISSUE TITLE
YouTube displays 980px layout

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/FirefoxReality#862]
Doesn't matter what the window size is adjusted to, YouTube always displays the 980px layout making text small, hard to read and interact with.

We also get a extra layout column (with video suggestions and a ad) when you click into Videos. This slows page rendering down and doesn't maximize the video sizing well.

**Comment by cvan** [comment]
@caseyyee assuming YouTube doesn't change its WebCopmat for VR browsers in the near future, what are the actionable things we can do today?

on a related note, should we close or merge @MortimerGoro's PR #832?

**Comment by caseyyee** [comment]
@cvan will try these changes with the correct url params and see if it makes a difference.  Worth a try!
