### ISSUE TITLE
Expose gamepads (`navigator.getGamepads()`) outside of Immersive Mode (an active WebVR session)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#863]
## Hardware
All

## Steps to Reproduce
1. Load http://html5gamepad.com/
2. Expect VR gamepads to be exposed

## Current Behavior
`navigator.getGamepads()` is empty unless the user is in an active VR presentation.

I reproduced this same behaviour in Oculus Browser. (Also: last time I checked, Microsoft Edge exposes the gamepads outside of the WebVR (1.1) session, but I could be wrong.)

## Expected Behavior
`navigator.getGamepads()` contains my gamepad(s) even when the user is not in an active VR presentation.

**Comment by bluemarvin** [comment]
My main concern with this is that we are using the controllers to emulate touch events when not in immersive mode. Do you expect that both touch events and gamepads events to fire? That seems like it might cause problems?

**Comment by philip-lamb** [comment]
Closing until we have a demand for gamepad API in 2D browsing contexts. Possible future support for Sony PlayStation Now or Google Stadia.
