### ISSUE TITLE
Have VR projection options for Images

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/FirefoxReality#869]
Current, you have to `requestFullscreen()` on image elements to be able to view images using VR  modes. It would be nice to have those modes available on directly linked/standalone images.

eg: https://roadtovrlive-5ea0.kxcdn.com/wp-content/uploads/2014/09/Venice.Still001.jpeg

The flow might be similar to Video's where you get a fullscreen widget in the corner.

**Comment by Brenebon** [comment]
I created an account on GitHub just to request this very feature. I'd like to be able to view images in VR and alter their projections in the same way you can for videos.
