### ISSUE TITLE
Automatically enable `Remote Debugging` and `Redirect Console to Logcat` when in Developer Mode (Oculus' Developer Mode, adb, or Android Studio)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#874]
## Hardware
Oculus Go
ab56151

## Steps to Reproduce

1. Ensure Developer Mode is enabled for your device (from the Oculus mobile companion app, open `Settings`, select the headset in the list, then enable from `More Options > Developer Mode`)
2. Run in the Terminal: `adb uninstall org.mozilla.vrbrowser`
3. Sideload an APK from `master` via `adb` or from Android Studio
4. The first two developer options, `Remote Debugging` and `Redirect Console to Logcat`, in `Settings > Developer Options` are default to `Off`.

## Current Behavior
The first two developer options, `Remote Debugging` and `Redirect Console to Logcat`, in `Settings > Developer Options` are default to `Off`.

## Expected Behavior
If we know FxR is in Developer Mode, it'd be nice for the first two developer options, `Remote Debugging` and `Redirect Console to Logcat`, in `Settings > Developer Options` to default to `On`.

**Comment by bluemarvin** [comment]
I'm not sure we can detect when developer mode is enabled on the device. I did a quick search and was not able to find anything. Maybe instead we can have both default on for debug/non-release builds?

**Comment by philip-lamb** [comment]
For future reference: to detect if the user has placed their device into developer mode:

```
    public boolean isDeveloperModeEnabled() {
        if (BuildConfig.FLAVOR_platform == "oculusvr") {
            return android.provider.Settings.Global.getInt(mContext.getContentResolver(),
                    "vrmode_developer_mode", 0) != 0;
        } else {
            return android.provider.Settings.Secure.getInt(mContext.getContentResolver(),
                    android.provider.Settings.Global.DEVELOPMENT_SETTINGS_ENABLED, 0) != 0;
        }
    }
```

**Comment by cvan** [comment]
Note for posterity's sake:
@philip-lamb's PR #1029 was closed for this reason, which is totally reasonable: https://github.com/MozillaReality/FirefoxReality/pull/1029#issuecomment-481169044
