### ISSUE TITLE
Consider altering behaviour of Private Browsing restored sessions

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#875]
When FxR is closed (by the user manually, by a crash, or from a shutdown) with a Private Browsing session, we should make considerations of whether to destroy the session.

**Comment by bluemarvin** [comment]
The session is destroyed by the crash, private or otherwise. Same with a shutdown. What we should consider is if we want to save state on a shutdown. Restoring from a crash would be harder.

**Comment by philip-lamb** [comment]
OK, so asking the question a different way. Under what circumstances would restoring a private browsing session after a shutdown be the behavior the user expects?

**Comment by philip-lamb** [comment]
Closing as **not** restoring private browsing sessions after a crash or forced shutdown is the user-friendly option.
