### ISSUE TITLE
WebVR performance issues in Hubs when spawning ducks

### ISSUE THREAD

**Issue by brianpeiris** [MozillaReality/FirefoxReality#878]
## Hardware
Oculus Go

## Steps to Reproduce

1. Visit hubs.mozilla.com
2. Create a room. I used the "Meeting Room" space.
3. Enter room and teleport near the duck spawner.
4. Spawn lots of ducks.

## Current Behavior
You experience a significant frame-lock/hitch with every duck you spawn. (Hitching occurs when you spawn other media as well, but it's easy to repro with the duck spawner.)

## Expected Behavior
Comparing with Oculus Browser, where spawning ducks does not cause any hitching.

<details open>

```
```

</details>

**Comment by bluemarvin** [comment]
This is most likely a Gecko/SpiderMonkey performance issue. Please capture a [profile](https://perf-html.io/docs/#/./guide-remote-profiling) of the issue and share the profile here: https://bugzilla.mozilla.org/show_bug.cgi?id=1498485

**Comment by brianpeiris** [comment]
:+1: Added the profile to the bugzilla ticket.

**Comment by bluemarvin** [comment]
Thanks, I’ll make sure the right eyeballs see it.

**Comment by philip-lamb** [comment]
Pushing JS-related performance issues to v1.3 as we won't be able to adequately test before closing v1.2.

**Comment by philip-lamb** [comment]
Pushing to 1.4 to test with new Geckoview and 64-bit.
