### ISSUE TITLE
Adding a GeckoView in a Fragment as part of a plugin for Unity causes the program to crash

### ISSUE THREAD

**Issue by IanPhilips** [MozillaReality/FirefoxReality#881]
## Hardware

Oculus Go

## Steps to Reproduce

1. Download/clone `geckoviewslow` branch https://github.com/IanPhilips/UnityAndroidVRBrowser/tree/geckoviewslow
2. open the UnityProject in Unity 2018.2.0b2
3. Connect the Oculus Go and Build 

## Current Behavior

The project immediately crashes following `geckoView = new GeckoView(getContext());` in my `Fragment`'s `onCreateView`. I've tried adding a `GeckoView` to the layout but this method crashes as well.

## Expected Behavior

I'd expect the `GeckoView` to not crash the project.

## Context

I've created an in-game 3D browser for developers to use on the Android platform in Unity3D (wanted [here](https://stackoverflow.com/questions/46479953/render-website-as-texture-in-unity3d-on-android/53582886?noredirect=1#comment94034517_53582886) and [here](https://stackoverflow.com/questions/53508682/web-browser-in-oculus-go-vr-application-built-with-unity?noredirect=1#comment93978281_53508682)). I'm currently using the android `WebView` but it can be buggy and can't display video. I'd like to transfer over to a `GeckoView` 
## Error Logs and Stack Traces

<details open>

12-04 16:23:56.090 15665 15665 D AndroidUnity: On inflate  View!
12-04 16:23:56.119  1194 15218 W ActivityManager:   Force finishing activity com.ianphilips.UnityAndroidVRBrowser/com.unity3d.player.UnityPlayerActivity
12-04 16:23:56.140  1194 15218 W ActivityManager:   Force finishing activity com.ianphilips.UnityAndroidVRBrowser/com.unity3d.player.UnityPlayerActivity
12-04 16:23:56.140  1194 15218 W ActivityManager: Duplicate finish request for ActivityRecord{e9cdd45 u0 com.ianphilips.UnityAndroidVRBrowser/com.unity3d.player.UnityPlayerActivity t62 f}

```
```

</details>

**Comment by caseyyee** [comment]
This issue might be better addressed with the Gecko View team?  @bluemarvin could you help 
 direct this issue to the right place?

**Comment by IanPhilips** [comment]
@bluemarvin  I'd love an update on this, should I submit a bug at bugzilla? I'm not sure in which category to file it: https://bugzilla.mozilla.org/enter_bug.cgi#h=otherProducts%7C

**Comment by bluemarvin** [comment]
https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox%20for%20Android And select GeckoView for the component. I've mentioned this to the team but we are a small team and all quite busy. Additionally, no one on the team is a Unity developer so I don't know how much traction this will get.

**Comment by IanPhilips** [comment]
follow the bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1515373

thanks!

**Comment by caseyyee** [comment]
Thanks for filing @IanPhilips!  Hopefully it works out for you. Very cool project!  Will be following along to see progress :)
