### ISSUE TITLE
Switch Google search code to new code

### ISSUE THREAD

**Issue by mkaply** [MozillaReality/FirefoxReality#885]
So we are going to make a simple switch for the search code. We'd also like to rename the engine to make it clear it's using the new code.

Change will be to add -o to the end of the codes:

firefox-b-1-o | firefox-b-o

There will no longer be a separate code (-ab) for using the address bar.

**Comment by cvan** [comment]
@mkaply thanks for filing. is there a particular date for this to be changed - or effective immediately?

**Comment by mkaply** [comment]
As soon as you can (no need for a release just for this).

**Comment by keianhzo** [comment]
@mkaply @cvan we are using browser-search android component for this now so this will be ready as soon as https://github.com/mozilla-mobile/android-components/issues/1563 lands and we update the AC version.

**Comment by mkaply** [comment]
Will we be able to use a different code for Reality?

**Comment by keianhzo** [comment]
@mkaply Yes, we can override any search plugin assets from AC in FxR to use different codes.

**Comment by cvan** [comment]
handled in PR #916
