### ISSUE TITLE
[l10n] Merge localpages.xml and strings.xml

### ISSUE THREAD

**Issue by Delphine** [MozillaReality/FirefoxReality#887]
It would make sense to merge localpages.xml and strings.xml in the same file at this point, like we do for other mobile projects (so, just one file containing all the strings). In fact, there are only two strings left in the localpages.xml file at this point.
Thoughts?
(CC @Pike so he's aware I filed this)

**Comment by Pike** [comment]
sgtm, we'll want to adjust l10n.toml, if #882 lands before. We'll also want to do that for the localized files.

**Comment by keianhzo** [comment]
@Delphine Makes sense, I can't think of any reason why we would need them separated.
