### ISSUE TITLE
Performance is bad following link traversal

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#896]
## Hardware
Oculus Go

## Steps to Reproduce
Framerate drops, or on complicated sites, the page never renders, after following a hyperlink in VR mode.  Visiting the page without following a hyperlink results in normal performance. (Reloading the page is not an option for end-users, as there is no reload button in VR mode.)

Sites where this crops up:
https://aframe.io/aframe/examples/showcase/link-traversal/
https://elfland-glider.surge.sh/

## Originally reported
https://twitter.com/PlumCantaloupe/status/1073977826141978625
https://developer.oculus.com/bugs/bug/2292885641000989/?fbclid=IwAR20fyz7XVu-DyKHhd6KgW4az6ZVkoDOPvWL8yArCfsv79u5y6eVnvD257k

**Comment by philip-lamb** [comment]
This appears improved with https://github.com/MozillaReality/FirefoxReality/pull/1060, but we ought to verify that we're not leaking memory here.
