### ISSUE TITLE
Issues with opening keyboard with `<input autofocus>`

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#898]
1. Load the test case root page: https://webxr.sh/?#autofocus
2. Click on the link for the test case.
3. Notice the `<input autofocus>` gets automatically focussed *and* the keyboard does as well

Compare to this:

1. Load the test case page directly: https://webxr.sh/autofocus.html (Or go press Back and Forward in history.)
2. Notice the `<input autofocus>` gets automatically focussed, but the keyboard does not.

**Comment by philip-lamb** [comment]
In current build off HEAD, both tests produce the same behaviour, which is that the autofocus field is focussed and the keyboard does not appear until a click in that field. What is the expected behaviour here? If this is fixed, please close.

**Comment by bluemarvin** [comment]
While not intuitive, I believe this is standard mobile behavior. Otherwise when navigating to a page with autofocus would cause the virtual keyboard to show and cover half the page.
