### ISSUE TITLE
Async loader crash in Daydream

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#90]
It happens when launching from the icon or Android Studio.

Launching from head set works ok.

**Comment by keianhzo** [comment]
@bluemarvin The privatebrowsing branch has the async loading for the tray already implemented if you want to try that one. It crashes randomly but works works fine when launching with the debugger attached.

**Comment by bluemarvin** [comment]
To fix the "back button" to reopen crash I think you need in native-lib.cpp line 35:
   
      // Check if we are exiting.
      if (aAppState->destroyRequested != 0) {
        sAppContext->mEgl->MakeCurrent();
        BrowserWorld::Instance().ShutdownGL();
        BrowserWorld::Instance().ShutdownJava();
        // ADD THIS LINE
        BrowserWorld::Destroy();

**Comment by bluemarvin** [comment]
Pushed a fix. Reponen if there are still problems.
