### ISSUE TITLE
Think about two controllers mechanism

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#901]
We would expect more and more 6 DOF controller headsets will join to the market, so we should think about how to use two controllers to do selection and point.

## Possible Solution
1. Both of this two controllers are allowed to do selection and show the light beam simultaneously.
2. Only one controller has the ownership. When one controller is pressed a special button, it will take the ownership, then, starting to do selection and showing its light beam model. The other controller only shows its model and can't do anything. 

```
```

</details>

**Comment by avrignaud** [comment]
@thenadj Another 6DOF design consideration to think through - how we use multiple 6DOF controllers, with additional buttons and functionality.

**Comment by thenadj** [comment]
@daoshengmu @avrignaud Absolutely! Also resizing and moving windows can be much easier that way.

**Comment by larsbergstrom** [comment]
Use of dual controllers for text input (as is now the default in Oculus and clearly was influenced by "hands" support) is the #1 complaint in the Oculus user feedback forums.

**Comment by bluemarvin** [comment]
Fixed by #2936
