### ISSUE TITLE
Add mechanism for fetching from the network a UA Override list

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#902]
So we can make additions/removals without needing to cut a release and publish a new version to the app stores, it'd be nice if there was a way to remotely host a JSON file that takes precedence over [`userAgentOverride.json`](https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/main/assets/userAgentOverride.json) on ([raw](https://raw.githubusercontent.com/MozillaReality/FirefoxReality/master/app/src/main/assets/userAgentOverride.json)).

Proposed workflow:

1. The default *Latest UA List* is parsed on FxR runtime from [`userAgentOverride.json`](https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/main/assets/userAgentOverride.json).
2. Once a day per FxR client, make a `GET` request for [this JSON file hosted on GitHub](https://raw.githubusercontent.com/MozillaReality/FirefoxReality/master/app/src/main/assets/userAgentOverride.json).
3. Per best practices, persist that *Latest UA List* on the user's disk (e.g., in `/sdcard/Android/data/org.mozilla.vrbrowser/files/` or the [`Places.sqlite` sqlite database](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Places/Database)).
4. If for whatever reason the network fails, use the *Latest UA List*.
    - If the hosted JSON file is an object in any form (even `{}`), update the caches (in-memory and disk) and use that as the *Latest UA List*.
    - If there is a network error or the user is offline, use the last *Latest UA List*.

**Comment by philip-lamb** [comment]
I will investigate Gecko platform support for this.

**Comment by philip-lamb** [comment]
Putting on Ice until we can demonstrate user need based on telemetry collected after #962
