### ISSUE TITLE
Bookmarks broken on lenovo mirage & HTC Focus

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#911]
## Hardware
Reproduced on HTC Focus; reported on Lenovo Mirage
Version 1.1.1 in-stores.

## Steps to Reproduce
1. Visit website
2. Click Star to bookmark
3. View bookmarks page

## Current Behavior
No bookmark added

## Expected Behavior
Bookmark added

**Comment by bluemarvin** [comment]
Looks like #888 is the commit that broke it. I reverted it and was able to see the booksmarks page.

**Comment by cvan** [comment]
@bluemarvin: @MortimerGoro: in your opinion, what would be the quickest and safest way to patch this?

**Comment by MortimerGoro** [comment]
I'm going to research this
