### ISSUE TITLE
Consider toggling UI in Fullscreen Mode

### ISSUE THREAD

**Issue by duckboo** [MozillaReality/FirefoxReality#922]
When any media goes full screen in Firefox Reality, a mini UI is still left right under the screen, which is often distracting and might affect immersion.

Also, full screen resets its ratio every time it's used. I think it should remember the last used ratio in full screen mode.

## Possible Solution
Maybe add a toggle button or hide the UI after a set amount of time when in fullscreen.

Make sure it remembers the last setting set in fullscreen mode.
<details open>

```
```

</details>

**Comment by cvan** [comment]
This is a good observation, and we can improve in this area. Thank you for taking the time to write this up.

**Comment by MortimerGoro** [comment]
`Also, full screen resets its ratio every time it's used. I think it should remember the last used ratio in full screen mode.`

If you are watching a video right know it resets the aspect ratio to the one from the video. This has the advantage of removing the black bars from the video to get better immersion.

**Comment by duckboo** [comment]
> `Also, full screen resets its ratio every time it's used. I think it should remember the last used ratio in full screen mode.`
> 
> If you are watching a video right know it resets the aspect ratio to the one from the video. This has the advantage of removing the black bars from the video to get better immersion.

I guess my use case differs from average. I use fullscreen to view galleries and sometimes even full screen student documents. For what I use it for, it's very annoying. Also it resets the size.

**Comment by larsbergstrom** [comment]
There was another report on Reddit, similarly asking if we could hide the mini UI somehow while watching videos: https://www.reddit.com/r/OculusGo/comments/dsyrsy/can_i_get_rid_of_the_address_bar_beneath_the/

**Comment by bluemarvin** [comment]
I think we need to treat fullscreen like we do immersive video where the UI *and* Controllers can be hidden while watching. I find them both very annoying when trying to watch something in fullscreen.

**Comment by keianhzo** [comment]
For the UI maybe we could fade them in/out when the user hovers the navigation bar or window. For the controllers not sure what's the best approach, hiding them while still doesn't seem like a good option as you tend to hold them most of the time. Maybe show/hide with any button click?

**Comment by keianhzo** [comment]
Per our conversation in the team meeting, we want to replicate the same behaviour as the media controls in immersive mode so:

- Hide controls and controllers when entering fullscreen mode. 
- Show hide with any button click.

**Comment by Softvision-GeluHaiduc** [comment]
I have a few questions/concerns regarding the new behavior for theater mode:

1. If you select a video projection and then go back to full the controllers and mini controls are still displayed, is this intended?
2. If you click to the right or to the left of the mini controls until the video borders the controllers and mini controls do not disappear, is this intended?
3. If you go into resize mode and click outside the predefined sizes or the video the controllers disappear, this could be a bit confusing.
4. The brightness remains the one selected previously it does not reset like the resize does, this isn’t a new issue but I thought to ask this as well.
5. On the Pico G2, Oculus Go and HTC Vive Focus Plus pressing on the touchpad displays/hides the controller and controls, on the HTC Vive Focus it does not.
6. On the Pico Neo2 and Oculus Quest only pressing the trigger button or the joystick displays/hides the controller and controls the other buttons like the grip button or the A B X Y buttons do not display/hide the controller and controls.

Also on HTC Vive Focus Plus and HTC Vive Focus the controllers do not disappear, I don’t think this is intended and I will log an issue. (#3743)

**Comment by bluemarvin** [comment]
> I have a few questions/concerns regarding the new behavior for theater mode:
> 
>     1. If you select a video projection and then go back to full the controllers and mini controls are still displayed, is this intended?
> 

I didn't consider this case. Currently the code will only hide the controllers when entering fullscreen. Internally immersive mode is also in fullscreen so leaving immersive mode after setting a projection means we are still in fullscreen mode instead of entering it. I could add some code for this case but I'm not sure it is worth the effort. 

>     2. If you click to the right or to the left of the mini controls until the video borders the controllers and mini controls do not disappear, is this intended?
> 

The problem is the mini controls UI is much wider than it looks. I think this is a bigger issue we have with all UI elements that have transparent surfaces. We probably need an issue for propagating the event up if it isn't handled by the UI. If you can see the pointer, it means FxR thinks there is a UI surface even if you do not see one.

>     3. If you go into resize mode and click outside the predefined sizes or the video the controllers disappear, this could be a bit confusing.
> 

Yep, this can probably be fixed.

>     4. The brightness remains the one selected previously it does not reset like the resize does, this isn’t a new issue but I thought to ask this as well.
> 

If you mean the resize in fullscreen, it gets reset because we use the video's aspect ratio to calculate fullscreen. I think we should be fixing the aspect ratio when in fullscreen and only allow a size multiplier, that way we could remember that value between fullscreen sessions.

>     5. On the Pico G2, Oculus Go and HTC Vive Focus Plus pressing on the touchpad displays/hides the controller and controls, on the HTC Vive Focus it does not.
> 

I would need to investigate that. It should work.

>     6. On the Pico Neo2 and Oculus Quest only pressing the trigger button or the joystick displays/hides the controller and controls the other buttons like the grip button or the A B X Y buttons do not display/hide the controller and controls.
> 

We probably need to be more consistent. The back/menu button not working in immersive video mode is also annoying.

**Comment by bluemarvin** [comment]
>     3. If you go into resize mode and click outside the predefined sizes or the video the controllers disappear, this could be a bit confusing.
> 

Created this PR to fix this issue: https://github.com/MozillaReality/FirefoxReality/pull/3748

>     5. On the Pico G2, Oculus Go and HTC Vive Focus Plus pressing on the touchpad displays/hides the controller and controls, on the HTC Vive Focus it does not.
> 

With my fix for WaveVR https://github.com/MozillaReality/FirefoxReality/pull/3746 focus touch pad buttons seems to work as does the trigger.
