### ISSUE TITLE
Do not disable Projection Mode (VR-goggles icon) when `?mozVideoProjection` is used

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#925]
## Hardware
Oculus Go
1.1.2

## Steps to Reproduce
1. Launch the Content Feed / Home.
2. Launch one of the YouTube 360° videos from **Travel Around the Globe** or **Out of This World**. Press the **Play** button.
3. Click the YouTube video page has loaded, press the Fullscreen icon to enter 360° mode.
4. Notice because we are using `&mozVideoProjection=360_auto`, Firefox Reality grays out the VR-goggles icon (which normally allows the user to set the Projection Mode).

## Current Behavior
Notice because we are using `&mozVideoProjection=360_auto`, Firefox Reality grays out the VR-goggles icon (which normally allows the user to set the Projection Mode).

![image](https://user-images.githubusercontent.com/203725/51225445-79297d00-18ff-11e9-94e4-9df1bc1eb8a4.png)

(Screenshot and bug report courtesy of @thenadj.)

## Expected Behavior
Even with a `mozVideoProjection`, the user should be able to override the Projection Mode defined in the URL.

## Context
Functionality added in PR #746 in release [`v1.1`](https://github.com/MozillaReality/FirefoxReality/releases/tag/1.1e) (published to app stores on Nov 29, 2018).

**Comment by MortimerGoro** [comment]
What's the use case for selecting a different projection if we know the correct one for the video? (via the parameter)

Is it because Youtube or other video web can redirect to another video and the parameter remains in the URL?

**Comment by cvan** [comment]
The projection value could be wrong. Or the video provider could contain the wrong projection in the metadata. Like I forgot to include one in one of the Feed's YouTube video URLs (https://github.com/MozillaReality/ContentFeed/issues/238), one could easily assume 360 instead of 360s and have a broken experience.
