### ISSUE TITLE
Intermittent errors in playing videos (YouTube) because of JavaScript error: `AbortError: The operation was aborted.`

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#926]
## Hardware
Oculus Go
1.1.2

## Steps to Reproduce

1. Launch https://www.youtube.com/watch?v=fSo_BDant_s&mozVideoProjection=360s_auto and press the Play button for the video.
2. Press the Fullscreen icon to enter the 360 Stereo projection.
3. Ensure `Remote Debugging` is enabled. Launch the WebIDE from desktop Firefox.
4. Click on the Tab on the left side.
5. Notice the error in the DevTools console:
    
    ```
    AbortError: The operation was aborted.
    ```

## Current Behavior
Sometimes, the video cannot be played due to a JavaScript error:

    AbortError: The operation was aborted.

![screenshot of JavaScript error in Firefox WebIDE](https://user-images.githubusercontent.com/203725/51226794-eb04c500-1905-11e9-8818-6169296941fe.png)

## Expected Behavior
The video consistently plays correctly.

## Context
Originally identified and reproduced by @thenadj. Reported in https://github.com/MozillaReality/FirefoxReality/issues/925#issue-399637415.

![screenshot](https://user-images.githubusercontent.com/203725/51226906-71210b80-1906-11e9-88d9-8b5f4c1643bb.png)

I've encountered similar errors with video playback on videos hosted on non-YouTube sources. I've reproduced this with standard <video> elements from the test cases here: https://webxr.sh/media

My hunch is this is most likely a regression in GeckoView, since desktop Gecko does not seem affected. I'm currently investigating more and trying to determine reliable Steps to Reproduce.

CC: @MortimerGoro @thenadj @avrignaud @bluemarvin @caseyyee @adamopenweb

**Comment by philip-lamb** [comment]
@cvan Is there any way we can test this on Firefox Android?

**Comment by philip-lamb** [comment]
Pushing to 1.3 as unable to regress to GV in time for v1.2.

**Comment by cvan** [comment]
I've tested this quite a bit. Can't reproduce. I'd say let's close.
