### ISSUE TITLE
Investigate Compatiblity with Humble Play

### ISSUE THREAD

**Issue by moocow1452** [MozillaReality/FirefoxReality#931]
## Hardware

Oculus Go
## Steps to Reproduce

1. Go to a demo of FTL from Humble Bundle. (https://www.humblebundle.com/store/ftl-faster-than-light)
2. Launch game through Humble Play applet.
3. Wait for game to load.

## Current Behavior

Game loads and user as able to scroll through menu options, but nothing can be selected. Also, the Fullscreen option crops oddly.

## Expected Behavior

Ideally, the Humble Play applet should run as well on desktop as it would in Mobile VR. Not sure if it would be something specific to the Firefox Reality product or something deeper in Firefox Mobile?

## Possible Solution

Maybe add a developer option to mimic mouse controls or some sort of intergration with Humble Play?

## Context

It would be nice to play Humble Games on more platforms and if a solution can be made that works with conventional mobile, all the better.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by cvan** [comment]
Will take a look at this once I open a Pull Request to update GeckoView with the latest initial WebExtension API support. Thank you for filing!

**Comment by philip-lamb** [comment]
It works fine in Gecko 68.0 b2 (Firefox desktop) but not in Geckoview (Fenix preview).

**Comment by philip-lamb** [comment]
Not functional in Google Chrome either. It looks like the app lacks some essential support for touchscreen interaction. If you'd like to follow up, I suggest filing a bug with the creator. Sorry we can't help in this case.
