### ISSUE TITLE
Kiosk mode support

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#935]
How would we support devices that support a kiosk mode? Basically, where they are supporting training/education/arcade/demo scenarios and want to pin Firefox Reality to a single page.

The idea is that the device supports booting into Firefox Reality but you want to set a kiosk mode where there is a single web page and you can reset to that page (between users) but otherwise it's fairly locked down.

cc @thenadj @cvan

**Comment by philip-lamb** [comment]
Just collecting notes here. Is Firefox command-line profile option "-no-remote" (see https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options) valid in Geckoview?

**Comment by cvan** [comment]
Imanol Martin added to the Settings the ability to change the Homepage URL.

Can you give URLs of example web pages for this kiosk use case?

I recently learned about Oculus Go's kiosk mode for enterprise use cases. You can disallow other apps from being launched.

We want that plus no other URLs to be redirected or navigated to? Or would the default Homepage plus a system kiosk mode be sufficient?

Implementation wise: we could add a custom PIN flow to the Settings or Developer Settings. @thenadj: thoughts?

**Comment by ScottWitte** [comment]
I can give you a kiosk use example: I have a city visitors' center that wants to present a virtual tour as an exhibit. Just put on the goggle and the tour starts. In this case, you don't want a visitor to accidentally or purposefully exit the site. You can't count on staff to fix problems. So you want to prevent users from backing out of the web app or entering a different URL. AND, you want the desired URL to be the only URL shown. So making it the home page would be appropriate.

Still in development, but one example would be: https://www.tourdeforce360.com/greendale

You mention that you recently learned about "Oculus Go's kiosk mode for enterprise use cases." Are you talking about https://oculusgokioskmode.tweaklab.org/ or something else? A couple months ago my Oculus contact said they were quite aware of requests for a Kiosk mode but could give me no timeline for when or if it would be available.

Also, for best kiosk mode use, you should be able to run the content locally. I have done this in the Oculus Browser by sideloading and running a local server app. Too complicated for the normal user.

**Comment by larsbergstrom** [comment]
I'd also like to consider at least the following scenarios that come up when chatting with our internal & external partners:
1) Enterprise. Deploying devices that should be "locked" to a training experience.
2) Trade shows/conferences. Having devices that are easily reset to the beginning of an experience or set of experiences.
3) Educational. Locking to a set of content and/or domains that have been curated or vetted by the school / teachers.

We'd be somewhat reliant on the OS platform, of course (to have a kiosk mode that locks to Firefox Reality), but there's a lot we can do if the platform supports that - which I'd expect many/most of them to do, even if only in Enterprise setup/configurations.

**Comment by philip-lamb** [comment]
An additional feature: ability to set a criteria for automatic return to the homepage (options: inactivity timeout, fixed time, on headset removal) to cover the use case where its desirable to not have to actively reset the headset between uses.

**Comment by bluemarvin** [comment]
We can't implement this with out access to the enterprise mode for testing.
