### ISSUE TITLE
Implement "Basic Auth" for logging in to sites

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#943]
## Hardware
All

## Steps to Reproduce

1. In Firefox Reality, load https://www.httpwatch.com/httpgallery/authentication/authenticatedimage/default.aspx?
2. Notice the "Basic Auth" content cannot be accessed, since the browser does not detect the request by the web site and does not prompt the user with a login prompt.

## Current Behavior

Firefox Reality does not display a UI for the user to authenticate when visiting a site that uses the "Basic Auth" mechanism.

## Expected Behavior

That sites using "Basic Auth" work.

## Possible Solution

Support "Basic Auth" and prompt the user with a UI similar to that of the `<select>` menus and `alert`/`prompt`/`confirm` dialogues.

## Context

Reported in webcompat/web-bugs#25244

Oculus Browser and Samsung Browser also do not properly support "Basic Auth" but all modern mobile and desktop browsers do.

Info. on the Basic Auth HTTP API:

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication
- https://tools.ietf.org/html/rfc7617

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by philip-lamb** [comment]
Implement interface https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoSession.PromptDelegate.html#onAlert-org.mozilla.geckoview.GeckoSession-java.lang.String-java.lang.String-org.mozilla.geckoview.GeckoSession.PromptDelegate.AlertCallback-

**Comment by cvan** [comment]
Does GeckoView properly handle Basic Auth to be able to fire those events? I haven't tested it in a non-FxR environment.

**Comment by philip-lamb** [comment]
It looks like it. Tested Firefox Focus for Android against basic auth at http://httpbin.org/#/Auth/get_basic_auth__user___passwd_ and it correctly shows an auth prompt.

**Comment by bluemarvin** [comment]
Depending on which version of Focus you used it may have been WebView based.

**Comment by philip-lamb** [comment]
OK, yeah I really should have checked that. Firefox Focus v8.0.8 (Build #330452036)

**Comment by MortimerGoro** [comment]
GeckoView has an API to handle "Basic Auth" but we haven't implemented it in FxR yet. I'm going to work on it.

**Comment by philip-lamb** [comment]
Tested with Focus nightly (verified with Geckoview) and HTTP auth works OK.
