### ISSUE TITLE
First run of voice search is broken on WaveVR

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#950]
## Hardware

Vive Focus FxR 1.1.2
## Steps to Reproduce

1. Do a clean install of FxR for WaveVR
2. Press the voice search button.
3. Grant permission to use the microphone.

## Current Behavior

The voice search prompt is show but the microphone is not read. So voice search is not possible until the voice search prompt is dismissed and the voice search button is pressed again.

## Expected Behavior

Voice search should work after the microphone permission has been granted.

**Comment by bluemarvin** [comment]
This happens in the 1.1.2 release currently in the store, but I can reproduce it with the current master.

**Comment by MortimerGoro** [comment]
I still can't reproduce it. 

@philip-lamb I think you also have a Vive Focus, can you reproduce this issue?

**Comment by philip-lamb** [comment]
Yes, I can confirm. The first voice input after the permissions dialog does not display any audio input. Canceling and trying again works.
