### ISSUE TITLE
Window resize broken on WaveVR

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#952]
## Hardware

Vive Focus FxR 1.1.2
## Steps to Reproduce

1. Do a clean install of FxR
2. Do a voice search
3. Click window resize button

## Current Behavior

Resize menu bar disappears and the user is unable to quit the resize mode.
## Expected Behavior

User should be able to resize the window.
## Comments
This seems to only happen on first run after a clean install.

**Comment by MortimerGoro** [comment]
I can't reproduce this one doing a clean install

**Comment by philip-lamb** [comment]
Can no longer reproduce since https://github.com/MozillaReality/FirefoxReality/pull/1012.
