### ISSUE TITLE
Unable to select items in a multi-picklist

### ISSUE THREAD

**Issue by parkerlreed** [MozillaReality/FirefoxReality#953]
## Hardware
Oculus Go

## Steps to Reproduce

1. Try to use any picklist (where multiple items can be selected)

![image](https://user-images.githubusercontent.com/841440/52835633-3d780380-30b5-11e9-848f-2dbd04f9f4e1.png)

## Current Behavior

Resulting dialog is too small to use and attempting to scroll through the list is impossible. Only the first couple if items can be selected. Anything after that it keeps auto scrolling to the top of the list.

## Expected Behavior

Being able to select multiple items in a picklist.

<details open>

```
```

</details>

**Comment by cvan** [comment]
Thank you for filing this bug. Great catch. :+1:

This appears to be a bug in our implementation of the UI for `<select multiple>`. We should make the `<select>` grow organically if the `<option>` text needs to wrap to additional lines.

Thanks again, @parkerlreed.

**Comment by cvan** [comment]
Test case to use (the third field down):

- https://webxr.sh/forms, select `#22`
- https://mdn.github.io/learning-area/html/forms/native-form-widgets/drop-down-content.html

**Comment by parkerlreed** [comment]
I know it's not out yet, but is there a build I can test?

Thanks @MortimerGoro!

**Comment by MortimerGoro** [comment]
@parkerlreed You can download taskcluster builds but only once https://github.com/MozillaReality/FirefoxReality/pull/1001 is merged (it should be merged soon)

**Comment by parkerlreed** [comment]
Thanks. I somehow missed the PR. Hope that gets cleared up! :D

**Comment by MortimerGoro** [comment]
Fixed in https://github.com/MozillaReality/FirefoxReality/pull/1001

There is a intermittent issue but seems related to Gecko code. Filed here: https://github.com/MozillaReality/FirefoxReality/issues/1013

**Comment by parkerlreed** [comment]
@MortimerGoro @cvan Thanks! Works great. Now I can actually do work in VR, lol.

**Comment by cvan** [comment]
Thank you for reporting! :+1:
