### ISSUE TITLE
Oculus Go freezes in VR mode

### ISSUE THREAD

**Issue by GrimOrk** [MozillaReality/FirefoxReality#954]
## Hardware
Oculus Go. Firmware version 3.57.5

## Steps to Reproduce
Visit https://aframe.io/examples/showcase/anime-UI/ and enter VR mode.

## Current Behavior
The picture is freezing for few moments. On the edge of view it fade to black. Freezing is more intensive if player's head moving is more intensive. In some cases, that freezing effect can disappear after some time.  

## Expected Behavior
Probably, some power-saving hardware technology is on. Looks like CPU/GPU speed is not on normal level.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by philip-lamb** [comment]
/remind me Close if no further info received in 1 week.
