### ISSUE TITLE
Editing only the first field of screen size and max screen do not get saved.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#955]
## Version

FxR 1.1.2
## Steps to Reproduce

1. Open settings widget
2. Click on display option.
3. Edit only the width of either window or max window option.
4. Click save.

## Current Behavior

The options retain their previous value.

## Expected Behavior

The values should be updated to the new entered value.

**Comment by MortimerGoro** [comment]
@bluemarvin did the problem happen in Oculus? Just tried but it worked ok

**Comment by bluemarvin** [comment]
It happens on Oculus for me. Just reproduced on master.

**Comment by cvan** [comment]
Reproduced this just now on the Oculus Go and the [Pico G2](https://www.pico-interactive.com/g2) (WaveVR) as well.

**Comment by cvan** [comment]
@philip-lamb: BTW, we should probably remove the `UX` label, as this isn't IMO a UX bug but an implementation one.
