### ISSUE TITLE
[meta] Keyboard

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#958]
needs #843, needs #60, needs #191, needs #620, needs #636, needs #640, needs #775, needs #699, needs #840, needs #898, needs #969, needs #970, needs #971, needs #972, needs #973, needs #974, needs #975, needs #413

**Comment by jvonitter** [comment]
Refer to keyboard UI Spec: https://drive.google.com/open?id=1GVx58e7sYBLlK1WegWzpha-MX1xSJqt6

**Comment by jvonitter** [comment]
Updated UI Spec: https://trello.com/c/VLsCI8iC/35-uis-6-english-keyboard

**Comment by philip-lamb** [comment]
needs #1180, needs #1179

**Comment by philip-lamb** [comment]
needs #1235

**Comment by bluemarvin** [comment]
@emstanley I think we can close this issue.

**Comment by bluemarvin** [comment]
Only #413 and #898 are still open.
