### ISSUE TITLE
Improve the visual quality on Vive Focus

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#959]
We have some quality/aliasing issues on Vive:

- [x] Aliasing specially on the edges of the UI
- [x] Blurry/Shimmery/Too small fonts specially noticeable on the Settings panel
- [x] Aliasing on the resize bar lines
- [ ] Some lines in the UI (e.g. dividers on the settings or search suggestions) are hardly visible

Possible solutions that could help:

- Try to blur on the edges of the UI. If you check the Vive Launcher UI they have a big blur/glow color on the edges of their UI widgets
- Add some shadows to the fonts
- Make the divider lines bigger
- Add some fade to transparent on the resizebar edges. We could use a texture or add some more geometry:
![image 1](https://user-images.githubusercontent.com/1070794/53017615-b0d09b00-3450-11e9-9324-adf773f97c55.png)

**Comment by thenadj** [comment]
@MortimerGoro We do not have a Vive Focus to test this on. Is there any work you need from us, modifying specific art assets, or can you fix this programmatically?

**Comment by cvan** [comment]
I have one. I will test and report back here.

**Comment by MortimerGoro** [comment]
@thenadj I pushed some PRs to make things better programmatically, waiting from feedback now from people with a Vive. I'll let you know if we need any more specific thing from art assets.

**Comment by philip-lamb** [comment]
@MortimerGoro Did https://github.com/MozillaReality/FirefoxReality/pull/968 address all the issues documented here? If so, we can close this.

**Comment by cvan** [comment]
@philip-lamb: no biggie, and I don't mean to be too pedantic. I am asking so I can better understand the triaged labels. I interpret the `UX` label as meaning "UX and/or UI guidance needed" - is that an incorrect assumption? Otherwise, nearly all visual bugs would be considered `UX` bugs. Thanks!

**Comment by MortimerGoro** [comment]
@philip-lamb The 3 firstp oint has been addressed. We only need to fix ` Some lines in the UI (e.g. dividers on the settings or search suggestions) are hardly visible` on Vive to close this
