### ISSUE TITLE
Widevine EME playback UI support

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#967]
## Hardware
All supported Android

## Current Behavior
Playback of Digital Rights Management (DRM) content via the Android Widevine Encrypted Media Extensions (EME) is not currently supported in Geckoview except nightly, and FxR will require UI to notify user to use EME in Geckoview beta or stable.

## Expected Behavior
Launch of Widevine-protected content should trigger a user prompt to allow or deny identification of the device to enable DRM-protected content playback. There should also be a toggle setting under "Privacy and security" titled "Play DRM-controlled content" which shows "Ask everytime" when off, or "On" when on.

## Context
FxR will connect with the Geckoview (GV) API for EME UI. See https://bugzilla.mozilla.org/show_bug.cgi?id=1506924 (top level bug for Widevine EME support in GV) and https://bugzilla.mozilla.org/show_bug.cgi?id=1524091 (API support in GV). 

For a detailed breakdown of the UI requirements and design mockups, see this doc: https://docs.google.com/document/d/1O7mPFSW2AO2MxWM1t3CwHrwPEJ7THxHjgXWUG74JBAc/edit#heading=h.8wv8zg2ybxre

**Comment by larsbergstrom** [comment]
That's really curious, because we're using GeckoView from Nightly, which _does_ have WideVine DRM playback enabled by default and Amazon Prime and many other streaming sites previously worked. Did we pick up an update in 1.1.2 that disabled it? IIRC, it's just a pref.

Also, my understanding is that we only need to display UI when we are exposing a client-specific identifier, which only happens in Level 1 playback, which are not supported on any of our devices or target websites today. This topic is definitely worth a deeper dive with the media team.

**Comment by philip-lamb** [comment]
I have clarified the issue description to note that we need to add the EME UI support to be able to access EME in beta or stable GV.

**Comment by cvan** [comment]
It's a known issue, but for posterity's sake, here are a few user-submitted WebCompat issues about this issue:

- https://github.com/webcompat/web-bugs/issues/19322 (Amazon Prime Video)
- https://github.com/webcompat/web-bugs/issues/29996 (Amazon Prime Video)
- https://github.com/webcompat/web-bugs/issues/26158 (Hulu)

**Comment by cipriansv** [comment]
> It's a known issue

@cvan, is there a referenced issue that we can connect with the ones you previously mentioned?

**Comment by softvision-sergiulogigan** [comment]
> @cvan, is there a referenced issue that we can connect with the ones you previously mentioned?

Reping @cvan

**Comment by philip-lamb** [comment]
Blocked as EME UI is not yet landed in GV.

**Comment by cvan** [comment]
@cipriansv:

> It's a known issue

@cvan, is there a referenced issue that we can connect with the ones you previously mentioned?


@softvision-sergiulogigan:

> > @cvan, is there a referenced issue that we can connect with the ones you previously mentioned?
> 
> Reping @cvan

This issue, #967, is the issue I'm referring to.

> FxR will connect with the Geckoview (GV) API for EME UI. See https://bugzilla.mozilla.org/show_bug.cgi?id=1506924 (top level bug for Widevine EME support in GV) and https://bugzilla.mozilla.org/show_bug.cgi?id=1524091 (API support in GV).

And on the GeckoView platform side of things:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1506924
- https://bugzilla.mozilla.org/show_bug.cgi?id=1524091

**Comment by softvision-sergiulogigan** [comment]
Thank you for the info!
I have closed our webcompat issues as duplicates, in favor of this one.

**Comment by jvonitter** [comment]
Final design is here: https://trello.com/c/DBeWo7OI/390-uis-83-drm-toggle-restricted-page
Note that it uses regular dialogs - no new components.

**Comment by philip-lamb** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1524091 is marked as in-work for October, so we should be able to pick it up prior to v1.5.

**Comment by bluemarvin** [comment]
This is still in progress and will not be ready by code freeze. After the Gecko work is done, there still needs to be a GV API. I will add the GV API. The UI work should probably be handled by @keianhzo

**Comment by bluemarvin** [comment]
Blocking bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1524091

**Comment by jvonitter** [comment]
This isnt going to land in 6, so pushing it out.

**Comment by keianhzo** [comment]
Still blocked.

**Comment by bluemarvin** [comment]
The permission prompt has landed in GV.

**Comment by emstanley** [comment]
Final Design: https://trello.com/c/DBeWo7OI/390-uis-83-drm-toggle-restricted-page
