### ISSUE TITLE
Spanish keyboard

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#969]
@MortimerGoro please review design at https://trello.com/c/0N8s6qs1/197-uis-54-spanish-keyboard for correctness for es_ES locale.

**Comment by MortimerGoro** [comment]
@philip-lamb @thenadj The spanish keyboard looks good! I'd also add `¿` and `¡` in the longpress menu of the original keys.

My only other concern is not having `:` in the main keyboard layout. It's used a lot for URLs with ports. Maybe a dev use case only though :)

**Comment by thenadj** [comment]
@MortimerGoro We replaced the : with the ñ. It seems like that's the more often used character for URLs than : If you feel super strong about adding the : back to the primary view, then we'll have to figure out another character to remove. And yes, we'll have long press menus. Adding the ¿ and ¡ into there makes sense. Plus we'll mimic iOS and Android for all the other characters that have long press options.

**Comment by thenadj** [comment]
Attaching the PDF for the Spanish keyboard. 
[UIS-54 Spanish Keyboard_002.pdf](https://github.com/MozillaReality/FirefoxReality/files/2911796/UIS-54.Spanish.Keyboard_002.pdf)

**Comment by jvonitter** [comment]
Latest spec from design: https://trello.com/c/0N8s6qs1/197-uis-54-spanish-keyboard
cc: @thenadj

**Comment by philip-lamb** [comment]
Implementation landed for testing in #1158.

Followup issues @MortimerGoro 
 * Updated UIS includes modified primary layout with inverted question mark and exclamation mark.
 * Changed layout of symbols

**Comment by MortimerGoro** [comment]
> Updated UIS includes modified primary layout with inverted question mark and exclamation mark.

@thenadj @jvonitter 

I don't think that's the best option for spanish. In informal language inverted question marks are often omitted, so is more important to show `?` and `!` in the main page. In addition to the symbols page I also made the inverted question and exclamations symbols accessible via long press on the normal ones.

**Comment by thenadj** [comment]
Thanks @MortimerGoro for making these suggestions. Please proceed with your recommendations, you're the language expert for Spanish!

**Comment by MortimerGoro** [comment]
Fixed via https://github.com/MozillaReality/FirefoxReality/pull/1193/files
