### ISSUE TITLE
German keyboard

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#970]
Reviewer needed for https://trello.com/c/Qz8ezugE/195-uis-55-german-keyboard for locale de_DE

**Comment by philip-lamb** [comment]
[UIS-55_German_Keyboard_002.pdf](https://github.com/MozillaReality/FirefoxReality/files/2908031/UIS-55_German_Keyboard_002.pdf)

**Comment by thenadj** [comment]
@philip-lamb 
[UIS-55 German Keyboard_002.pdf](https://github.com/MozillaReality/FirefoxReality/files/2911783/UIS-55.German.Keyboard_002.pdf)
Attached is an updated version of the keyboard. Please ignore the previous one. This is ready for review.

**Comment by cvan** [comment]
@thenadj there are several variations in this German keyboard layout vs. the ones I'm seeing online:

- https://en.wikipedia.org/wiki/German_keyboard_layout
- https://www.apple.com/uk/shop/product/MLA22D/A/magic-keyboard-german

if the couple key omissions and variations were intentional, could you document it here or in an updated UIS-55?

**Comment by thenadj** [comment]
@philip-lamb Hold off on the german keyboard. It's being finalized right now. I'll post the latest UIS to this GH issue when it's ready.

**Comment by thenadj** [comment]
@cvan Updated UIS-55 is attached. We reviewed it with German speakers and feel that it captures all the variations necessary.
[UIS-55 German Keyboard_003.pdf](https://github.com/MozillaReality/FirefoxReality/files/3159750/UIS-55.German.Keyboard_003.pdf)

**Comment by philip-lamb** [comment]
First implementation in #1176 to allow testing.

Followup issues @MortimerGoro:
 * changed width and layout on primary display
 * rearrangement of symbols on symbols display

**Comment by MortimerGoro** [comment]
@thenadj I'd add the `:` to the main layout instead of making space key wider. It's important for URLs and testing

**Comment by thenadj** [comment]
@MortimerGoro Yes, go ahead and do that!

**Comment by MortimerGoro** [comment]
Fixed in #1198

btw @thenadj I didn't remember we have one button less in this release (the microphone one) so I didn't need to reduce the spacebar width
