### ISSUE TITLE
Italian keyboard

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#971]
Reviewer needed for https://trello.com/c/mXP7Jxlo/196-uis-56-italian-keyboard for it_IT locale.

**Comment by thenadj** [comment]
Attaching the pdf for the Italian keyboard. 
[UIS-56 Italian Keyboard_002.pdf](https://github.com/MozillaReality/FirefoxReality/files/2911801/UIS-56.Italian.Keyboard_002.pdf)

**Comment by philip-lamb** [comment]
Implemented in #1178

**Comment by MortimerGoro** [comment]
Updated in #1198
