### ISSUE TITLE
French keyboard

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#972]
Awaiting draft design https://trello.com/c/L0wfBtta/194-uis-53-french-keyboard for fr_FR locale.

**Comment by thenadj** [comment]
[UIS-53 French Keyboard_002.pdf](https://github.com/MozillaReality/FirefoxReality/files/2907279/UIS-53.French.Keyboard_002.pdf)

**Comment by MortimerGoro** [comment]
@paulrouget could you help review the french keyboard?

**Comment by paulrouget** [comment]
The long press looks good.
The symbols looks good.
The letter should be using the AZERTY layout, not QWERTY.

**Comment by philip-lamb** [comment]
@thenadj Feedback from Paul above.

**Comment by thenadj** [comment]
Thank you, @paulrouget for reviewing the keyboard. I updated the arrangement of letters to AZERTY. Here's the updated UI spec. 
[UIS-53 French Keyboard_003.pdf](https://github.com/MozillaReality/FirefoxReality/files/2911760/UIS-53.French.Keyboard_003.pdf)

**Comment by paulrouget** [comment]
Looks good to me.

**Comment by jvonitter** [comment]
Spec has been updated - https://trello.com/c/L0wfBtta/194-uis-53-french-keyboard
Reopening for a few additional changes.

**Comment by MortimerGoro** [comment]
Fixed in #1198
