### ISSUE TITLE
Russian keyboard

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#973]
Need reviewer for draft design https://trello.com/c/ZfDFrOgQ/258-uis-63-russian-keyboard for ru_RU locale.

**Comment by thenadj** [comment]
Attaching the pdf for the Russian keyboard. 
[UIS-63 Russian Keyboard_007.pdf](https://github.com/MozillaReality/FirefoxReality/files/2911804/UIS-63.Russian.Keyboard_007.pdf)

**Comment by philip-lamb** [comment]
Optional for v1.2.

**Comment by jvonitter** [comment]
Latest russian keyboard - https://trello.com/c/ZfDFrOgQ/258-uis-63-russian-keyboard
I'll work on finding a native russian speaker

**Comment by jvonitter** [comment]
Got feedback, passed it to Nadja. Updates are in progress and the final design should be here soon.

**Comment by thenadj** [comment]
Attached is the updated Russian keyboard. It is now ready for implementation. 
[UIS-63 Russian Keyboard_009.pdf](https://github.com/MozillaReality/FirefoxReality/files/3213302/UIS-63.Russian.Keyboard_009.pdf)
