### ISSUE TITLE
Japanese keyboard

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#974]
Awaiting draft design from https://trello.com/c/v128IrGt/199-uis-58-japanese-keyboard for ja_JP locale.

**Comment by thenadj** [comment]
The Japanese keyboard is ready for review. 
[UIS-58_Japanese Keyboard_003.pdf](https://github.com/MozillaReality/FirefoxReality/files/2908252/UIS-58_Japanese.Keyboard_003.pdf)

**Comment by philip-lamb** [comment]
Pushing to 1.3.

**Comment by jvonitter** [comment]
New spec is ready! https://trello.com/c/v128IrGt/199-uis-58-japanese-keyboard
cc @thenadj

**Comment by thenadj** [comment]
We made one small change to the Japanese keyboard for consistency reasons after Daosheng reviewed the Taiwanese keyboard. Please use UIS-58_Japanese Keyboard_007.pdf for the latest version in Trello. https://trello.com/c/v128IrGt/199-uis-58-japanese-keyboard

**Comment by MortimerGoro** [comment]
Potential database here: https://github.com/google/mozc
