### ISSUE TITLE
One of two controllers will disappear when using Oculus 6Dof devices.

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#977]
## Hardware

Oculus 6Dof device

## Steps to Reproduce

1. Open FxR, it will disappear one of controllers intermittently.

## Current Behavior

One of controllers will disappear intermittently.

## Expected Behavior

We should see both controllers, unless there is only one controller be turned on.

## Possible Solution

I would guess this is an asyn problem of the model or image loader when using multiple controllers.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by daoshengmu** [comment]
I notice the controller models are loaded properly because the callback function at `LoadFinishedCallback() in ModelLoaderAndroid.cpp` is called. When this failure happens, there is only one controller geometry be added to the drawlList (`DrawableList::AddDrawable() in DrawableList.cpp`). I am trying to find out if it is removed by the culling mechanism. 

 @bluemarvin do you have any thought?


(Sorry for my ADB sometimes will interrupt the connection with the debugger, it makes the debugging work be more complicated to me.)

**Comment by bluemarvin** [comment]
I would look to see if the Device is some how disabling the model.
