### ISSUE TITLE
Use `substitute-local-geckoview.gradle` from Bug 1533465 for local GeckoView substitution.

### ISSUE THREAD

**Issue by ncalexan** [MozillaReality/FirefoxReality#987]
This is a development ergonomics change only.  Over in [Bug 1533465](https://bugzilla.mozilla.org/show_bug.cgi?id=1533465) I'm trying to unify how downstream GeckoView consumers (at least, Mozilla consumers) substitute local GeckoView versions.  (This is all leading up to Gradle composite builds, someday, but that day is not this day.)

This is an example of consuming that ticket in a downstream consumer.

**Comment by philip-lamb** [comment]
Will be fixed by #1579
