### ISSUE TITLE
In settings, consider moving telemetry and crash-reporting to security and privacy sub-pane

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/FirefoxReality#994]
## Hardware
All

## Current Behavior
* Switches for telemetry and crash-reporting are currently at top level of settings.

## Expected Behavior
* Switches for telemetry (see separate issue #752 about naming) and crash-reporting which do not need to be toggled frequently should be grouped under "Privacy and Security" section of settings. This is also consistent with Firefox on other platforms.

## Possible Solution
Move and potentially move other options to top-level tiles.

**Comment by bluemarvin** [comment]
Crash reporting can not be opt out because we return stack traces. It’s opt out on focus because their crash reporter does not return personally identifiable information.

**Comment by philip-lamb** [comment]
@bluemarvin thanks, I've edited the description above to remove references to changes in opt in/out behaviour.

**Comment by jvonitter** [comment]
needed by #1243

**Comment by jvonitter** [comment]
Fixed by  #1372
